### ISSUE TITLE
Update Project Profile: Engage

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/website#1031]
### Overview
We want the Engage profile card to be up to date so that new volunteers can have current information when they come to the website.

### Project card
_insert url of their card here before sending - https://www.hackforla.org/projects/engage
https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md

### Action Items
- [x] Update Enage project card using the information from this issue https://github.com/hackforla/product-management/issues/36
- [x] Please confirm user acceptance by asking PM: Bryon to review #364 
- [x] Once accepted remove dependency on https://github.com/hackforla/product-management/issues/36 .

**Comment by jbubar** [comment]
@Olivia-Chiong What did you mean by 
> Please confirm user acceptance by asking PM: Bryon to review #364

**Comment by Olivia-Chiong** [comment]
> @Olivia-Chiong What did you mean by
> 
> > Please confirm user acceptance by asking PM: Bryon to review #364

Basically once changes are done, get @BryonPm to review and confirm all changes.

**Comment by Lol-Whut** [comment]
Note: whoever merges the pull request for this issue should handle the third action item (as discussed in dev meeting on 4/20/2021)

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art 
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by glenflorendo** [comment]
**Progress:**
Action Item 1: In progress. Most of the requested updates have been implemented.
Action Item 2: Not Started
Action Item 3: Not Started

**Blockers:**
1. Meeting times on the specific project page are fetched from the VRMS API. I asked Alex Anakin to help get this updated on their end.
2. Awaiting Engage project image-hero.

**Availability:**
I have a lot of time this week.

**ETA:**
Shortly after blockers are resolved and changes are approved.

**Pictures:**
![Screenshot 2021-05-02 at 01-43-41 Engage by Hack for LA](https://user-images.githubusercontent.com/9373317/116807426-0badb480-aae8-11eb-9c6d-c33032464b15.png)
![Screenshot 2021-05-02 at 01-43-52 Hack for LA](https://user-images.githubusercontent.com/9373317/116807433-0f413b80-aae8-11eb-81c9-326d3c9296fc.png)

**Comment by BryonPm** [comment]
Progress:
The Engage team will have a hero image selected by this Wednesday. 

Blockers:
The team needs a couple of days to select an appropriate image for the hero. 

Availability:
Mon. 7-9 CST
Thurs. 7-9 CST

ETA:
Wednesay

**Comment by qiqicodes** [comment]
@glenflorendo Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:
Availability:
ETA:

**Comment by glenflorendo** [comment]
@qiqicodes 

Progress:
- [ ] Action Item 1: In progress. Most of the requested updates have been implemented.
- [ ] Action Item 2: Not Started
- [ ] Action Item 3: Not Started

Blockers:

- ~~Meeting times on the specific project page are fetched from the VRMS API. I asked Alex Anakin to help get this updated on their end~~
- Awaiting Engage project image hero. @BryonPm

Availability:
I have a lot of time this week.

ETA:
Shortly after blockers are resolved and changes are approved.

Pictures:
![Screenshot_2021-05-07 Engage by Hack for LA](https://user-images.githubusercontent.com/9373317/117516475-133ce580-af4e-11eb-8ff6-5fb2007bf3bc.png)

**Comment by glenflorendo** [comment]
Progress:
- [x] Action Item 1: Done.
- [ ] Action Item 2: Awaiting review from Bryon
- [ ] Action Item 3: Not Started

Blockers:
- Awaiting review from Bryon 

Availability:
Monday, Thursday, Friday evening.

ETA:
?

Pictures:
![engage-project-page](https://user-images.githubusercontent.com/9373317/118230806-10a52900-b443-11eb-94f3-1bba578bad55.png)
![project-page](https://user-images.githubusercontent.com/9373317/118230817-13a01980-b443-11eb-95e0-9abdb88cacf5.png)

**Comment by BryonPm** [comment]
@glenflorendo Please replace hero image with the image below. 
![image](https://user-images.githubusercontent.com/76059921/120123920-405c6c80-c177-11eb-87b1-c03081218aa5.jpeg)
