### ISSUE TITLE
Identify all project images on projects page that are not 600x400 pixels or don't have 3:2 ratio

### ISSUE THREAD

**Issue by shaswa** [hackforla/website#1105]
### Overview
We need project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) to have a 3:2 ratio (standard resolution of 600x400 pixels or higher). So that the website appears consistent.

### Action Items

- [x]  Identify and document the px of all the images categorizing them as follows
   - [x]  images that are lower than 600x400 pixels
   - [x] images that are higher
   - [x] images that are at 600x400
   - [x] images that don't have a 3:2 ratio
- [x] Discuss with the product mgmt team the results and decide on next actions
   - [x] likely action: opening up new issues on the product-management repo for each one that is not correct 

### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)

**Comment by shaswa** [comment]
Added all the data in [Google spreadsheet](https://docs.google.com/spreadsheets/d/1qg2EHGc_whzPBwJEBbSswkX5TtiYsOQgrdyFpA_BEIY/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@shaswa 
- [x] Make new issues on this repo for each of these fixes that is marked "Hack for LA website UI/UX team"
- [x] Make new issues on the [product management repo](https://github.com/hackforla/product-management/) - one for each of the rest of the projects
- [x] Add links to the issues in the last column in the chart

Project | Resolution | Ratio | Comments | Who will fix | Issue number
-- | -- | -- | -- | -- | --
BallotNav | 597 x 400 | 3:2 | Almost ok (Ratio slightly less than 3:2) | BallotNav | hackforla/ballotnav#380
Open Community Survey | 2501 x 1668 | 3:2 | Almost ok (Ratio slightly less than 3:2) | Open Community Survey | hackforla/community-survey-nc-websites#16
Home Unite Us | 1080 x 1080 | 1:1 | Increase ratio | Home Unite Us | hackforla/HomeUniteUs#275
Railstats LA | 2000 x 2000 | 1:1 | Increase ratio | Hack for LA website UI/UX team | #1150 
New Schools Today | 640 x 480 | 2.67:2 | Increase ratio | Hack for LA website UI/UX team | #1151
311 Data | 388 x 258 | 3:2 | Increase resolution | 311 Data | hackforla/311-data#987
Website | 411 x 325 | 2.5:2 | Increase resolution and ratio | Hack for LA website UI/UX team | #1152

**Comment by shaswa** [comment]
Created issues in each of the repos and added issue numbers

**Comment by tarang100** [comment]
Write to project PMs for each of these projects in Slack

- Open community survey - Phoebe Ng is the UX Lead (did the logo)
- Ballot Nav - https://github.com/hackforla/product-management/issues/90#issuecomment-774725376
- 311 Data - Mahmudul is the PM for 311 Data #1196 
- Home Unite Us

**Comment by tarang100** [comment]
@ExperimentsInHonesty will bring issues back to HfLA website repo
Railstats
New Schools

**Comment by shaswa** [comment]
@ExperimentsInHonesty Is there a document listing the PMs for each project?

**Comment by shaswa** [comment]
Contacted the PMs for BallotNav, Open community survey, 311 Data and Home Unite US about the updates needed for the tasks. Will contact them again on Friday to get an update

**Comment by shaswa** [comment]
311 Data image is ready, added update to #1196

**Comment by tarang100** [comment]
**Update**
we created an issue for the hackforla.org team to do the updates

Ballotnav #1341 
Open community survey #1342 
Home Unite Us https://github.com/hackforla/HomeUniteUs/issues/275 - we have informed them but are yet to hear back from them
New Schools Today #1151 
HfLA Website UI team will work on Railstats, New Schools Today, and the HfLA Website issues

**Comment by tarang100** [comment]
@Oluwafemi-Jegede 
Check to see if the following has been done. Check these items on Saturday, 3rd April
- [ ] https://github.com/hackforla/HomeUniteUs/issues/275 - Check to see if they have provided the image in this issue; if they have then make a new issue on our repository for updating, similar to issue #1341 
- [x] https://github.com/hackforla/website/issues/1150 - Check to see if they have fixed the image for Railstats and put the labels 'front end', 'good first issue', 'feature: Project Info and Page'
- [ ] https://github.com/hackforla/website/issues/1152 - Check to see if they have fixed the image for HfLA Website and release the dependency on #1219

**Comment by Oluwafemi-Jegede** [comment]
Update requested on hackforla/HomeUniteUs#275 and #1152

**Comment by ExperimentsInHonesty** [comment]
Wrote to abby via slack today
```
Hi Abby.  This issue has been open for a while and its a quick fix.  Please assign it to one of the ui team members, or we will temporarily delist homeuniteus from the website: https://github.com/hackforla/HomeUniteUs/issues/275
```

**Comment by Oluwafemi-Jegede** [comment]
Update

* Image provided for #1152 - awaiting development 

* Awaiting feedback on  hackforla/HomeUniteUs#275

**Comment by RobertaFricker** [comment]
Replaced image on HackForLA website's Project Card, per the following link:
https://github.com/hackforla/website/issues/1152#issuecomment-819001504

**Comment by RobertaFricker** [comment]
Replaced image on RailStats Project Card per the following link:
https://github.com/hackforla/website/issues/1150#issuecomment-816023698

**Comment by Aveline-art** [comment]
Replaced image on RailStats Project Card per the following link:
#1151
