### ISSUE TITLE
GitHub Actions: Implement ESlint

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1442]
### Dependency
~#1441~
- #2651
- after the [spelling issues](https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+spelling%22) are done we can re-review this.
- [ ] Figure out which js files use liquid (and the least liquid in any file)
- [ ] Refactor a js file that uses liquid into two separate files
- [ ] Roll out plan for implementation
### Overview
We need to implement a linter for our javascript code to standardize and maintain the code properly.

### Action Items
- [ ] Create a list of possible bare minimum esLint settings that we can turn on
    - [ ] During one of the developer meetings, discuss the possible settings with the team and finalize a list of settings to implement
    - [ ] You may reference and use the list from this [comment](https://github.com/hackforla/website/issues/1442#issuecomment-873691854)
- [ ] Implement a GitHub action that triggers on pull request or on push to the gh-pages branch
    - [ ] The action should lint javascript files. The recommended tool for linting is [Super Linter](https://github.com/marketplace/actions/super-linter)
    - [ ] Create the action as part of your local fork of the repository
    - [ ] Run the action on js files that should end in a success, and ensure that the action actually succeeds
    - [ ] Run the action on js files that should end in a failure, and ensure that the action fails properly based on the correct settings
    - [ ] Demo your prototype to the team and/or the technical lead to get approval
    - [ ] After approval, create a PR for review
    - [ ] <b>Ensure that the linter does not trigger or break on liquid syntax</b>
- [ ] **For merge team**: Release dependency on #3230
  - [ ] Update action items in the dependency issue if needed. 
  - [ ] If all dependencies in #3230 have been resolved, remove the dependency label, move it to the new issue approval column and add a ready for milestone label.

### Resources/Instructions
- A GitHub action for linting the scss files is already implemented, You may use that as reference when implementing this action for Javascript files.
    - [lint-scss.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/lint-scss.yml)
    - Issue for implementing scss lint: #1441
    - PR for implementing scss lint: #1957
- Recommended tool for linting: [Super Linter](https://github.com/marketplace/actions/super-linter)
- [Super Linter article](https://dev.to/n3wt0n/the-easiest-way-to-lint-any-code-github-super-linter-deep-dive-53eo)

#### Additional resources:
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by qiqicodes** [comment]
@AmyMendelsohn Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by AmyMendelsohn** [comment]
@qiqicodes 

I ran into some issues getting ESlint running locally.

Unfortunately, I think I don't have enough time to dedicate to this right now. I will unassign this from me.

**Comment by averdin2** [comment]
- This issue is very closely tied with (https://github.com/hackforla/website/issues/1441). Once I finish up the CSS linter, my idea was to use the same GitHub action with ESLint. See the GitHub action here: https://github.com/marketplace/actions/super-linter

**Comment by qiqicodes** [comment]
@averdin2 Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by averdin2** [comment]
Es Lint Getting Started: https://eslint.org/docs/user-guide/getting-started
Es Lint Config: https://eslint.org/docs/user-guide/configuring/
Es Lint Rules: https://eslint.org/docs/rules/

**Comment by wendywilhelm10** [comment]
@sanchece How is the progress on the Es Lint Rules?

**Comment by Sihemgourou** [comment]
@averdin2 @sanchece 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by Sihemgourou** [comment]
@averdin2 is on vacation. Please tell us when you are back :)

**Comment by aliibsin** [comment]
unassigned @averdin2 because he's on too many issues

**Comment by Sihemgourou** [comment]
@averdin2 is going to reach out to @sanchece & @glenflorendo to ask for updates and maybe take over the issue.

**Comment by Sihemgourou** [comment]
@averdin2 @sanchece do you have some news about this issue ?

**Comment by averdin2** [comment]
@glenflorendo I just want to reiterate that you do not need to worry too much about the GitHub action portion of this issue, as I already have a solution for this from working on issue #1441. Just focus on finding usable ESLint rules and I can help coordinate setting up the GitHub action.

**Comment by glenflorendo** [comment]
I compiled a config of some proposed ESLint rules and a report of the output when I ran these rules on the current codebase. You can view these in the attached `txt` files.

**ESLint Config**
[eslintrc.txt](https://github.com/hackforla/website/files/6760795/eslintrc.txt)

**Output**
[eslint-output.txt](https://github.com/hackforla/website/files/6760794/eslint-output.txt)

As a suggestion, I think it may be also helpful to invoke ESLint be on the pre-commit (or maybe some other) hook. This helps to assure that every commit made has passed all configured ESLint rules prior to being pushed / merged / etc.

**Comment by glenflorendo** [comment]
@averdin2 Is there anything else I should do for this issue?

**Comment by averdin2** [comment]
@glenflorendo If you are confident with your progress on the rules you researched, you can make a eslintrc config file in the root of the project folder. You can then make a pull request draft to merge that file. I am still working on the GitHub action portion of the two linting issues, but I am almost done. When I am done, I will review your proposed rules and implement it with the GitHub action. I am going to put a dependency label on this issue since it is reliant on my progress on the other issue #1441. Until l can review this, I think you should be okay to work on other issues after making the pull request.

**Comment by Aveline-art** [comment]
@glenflorendo We will remove you from this issue until @averdin2 is done with his ESlint. Please feel free to hop back on when the dependency is completed.

**Comment by ExperimentsInHonesty** [comment]
has dependency label but no dependency listed at top

**Comment by macho-catt** [comment]
@macho-catt will rewrite the Overview and Action items to conform to our current standard + explain how it should work with the existing linting action

**Comment by ronaldpaek** [comment]
i. Friday - Sunday
ii. Sunday, maybe; never implemented a linter before, but I really want to get this done cause I don't like seeing red squigglies on my screen.

**Comment by ronaldpaek** [comment]
@macho-catt Hi, I'm looking at the previous SCSS linter rules and only selected a few sets of rules. Usually, I opt for the standard config rule set, which is usually recommended and will ensure more consistency. And I reviewed the earlier comments to figure out what rules to apply. I know I usually apply eslint:recommended, and know that will apply pretty good robust setup rules for my js files without enforcing any of the stricter styling rules like semicolons, training commas, etc... Should I set each rule individually and the least amount of rules applied? I considered applying eslint:recommended by itself or with eslint:standard.

I also have another concern/suggestion as well. I know some of the js files I've checked also contain liquid syntax in them, which is why I currently get so many lint warnings. I checked the other day and set the file to be recognized as a liquid file, and the errors went away, but then we lost the IntelliSense, so that's not helpful plus, we want the linter to catch errors. And I believe even if we get eslint to work for JS stuff since the liquid syntax is in the js files, I think it would still throw an error and complain, and we would have to tell es-lint to ignore this block of code manually, like the example shown below.

```js
/* eslint-disable */
{% assign name = 'world' %}
/* eslint-enable */

console.log('Hello, ' + name + '!');
```

I think this solution would be okay for the first step, and then, we can separate the liquid portion, the data, and the js portion, the logic.
[potential issues](https://github.com/eslint/eslint/issues/2428)

🙇
@roslynwythe @t-will-gillis

**Comment by ronaldpaek** [comment]
@glenflorendo, your pre-commit hooks suggestion makes sense, and I've seen many people set it up that way. I have never worked on a project that used Jekyll to build out the static portions of the site. I know that Jekyll is written in ruby, but to run Husky, I would need to install node, and I don't see a package.json file at the root level, only a package-lock.json file. Do you know if converting the whole project to run on a node would cause issues?

**Comment by ronaldpaek** [comment]
Hello, I did some research and did a lot of PRs to my repo. I'm not saying it's perfect, but I was just doing some testing, and I first got the super-linter to work for the JS files, then after researching, I saw we can use super linter/slim version which is a little smaller so the GHA/linting finishes faster.

<img width="1473" alt="CleanShot 2023-07-15 at 19 13 37@2x" src="https://github.com/hackforla/website/assets/95109313/b54f6d69-1ea4-4c79-a2a0-39642a87e5ab">

<img width="1309" alt="CleanShot 2023-07-15 at 19 13 21@2x" src="https://github.com/hackforla/website/assets/95109313/5aff5a08-643f-4597-9c5a-39c5ac586fb8">

<img width="380" alt="CleanShot 2023-07-15 at 19 05 43@2x" src="https://github.com/hackforla/website/assets/95109313/86179907-d371-4520-9fa4-bb8153e3c050">
<img width="459" alt="CleanShot 2023-07-15 at 19 06 09@2x" src="https://github.com/hackforla/website/assets/95109313/56161bea-55c5-45a7-b7db-0e73a559a50f">

**Comment by ronaldpaek** [comment]
I then figured out and tested the pre-commit hook feature others mentioned earlier, basically having the linter enforce rule check before making a pull request, which would ensure that every review is formatted correctly and no immediate glaring issues.

It took a bit of figuring out and testing, but I was able to get do pre-commits with JS and CSS

<img width="1128" alt="CleanShot 2023-07-15 at 19 42 13@2x" src="https://github.com/hackforla/website/assets/95109313/2477e0b8-d50f-4776-9927-e73aa2df42ef">

<img width="1216" alt="CleanShot 2023-07-15 at 19 42 05@2x" src="https://github.com/hackforla/website/assets/95109313/dbfb3385-cde9-41fe-82c6-1de3c335803d">

<img width="1255" alt="CleanShot 2023-07-15 at 19 45 45@2x" src="https://github.com/hackforla/website/assets/95109313/d737ae59-e858-4414-9cb7-a4cec2d876d7">


So the pre-commit works, but you can bypass that if you want and commit anyway. Since we already have our linter set up, it isn't a problem. It runs like normal, as if we never had a pre-commit linter going on.

<img width="1223" alt="CleanShot 2023-07-15 at 19 49 25@2x" src="https://github.com/hackforla/website/assets/95109313/e958a32f-5302-4bb1-9843-c89d64095607">

<img width="1200" alt="CleanShot 2023-07-15 at 19 49 20@2x" src="https://github.com/hackforla/website/assets/95109313/da6cfa1f-c523-47f4-b476-d3b5dd629454">

**Comment by ronaldpaek** [comment]
So I realize all these photos show prettier installed and, yes, prettier, was the last thing I was testing, and they play well with each other. I left just the prettier default setting because I know someone was ticking off every rule set if we know what rules to apply, I think it should be very fast to apply. but seeing as I was committing and pushing/saving files, I don't think the way I have it set up it will try to prettify the whole codebase.

I think some of the rules can be adjusted for prettier as we need. I think we can also adjust it to warn but still be able to make commits as well. Like this head tag thing for liquid/front matter, it doesn't know that that's not an HTML  page. 


<img width="1363" alt="CleanShot 2023-07-15 at 19 57 12@2x" src="https://github.com/hackforla/website/assets/95109313/660a6afa-6d23-4e70-95fd-ef597cccba1e">

I think this is useful; we can quickly see where inconsistencies are, and should be easy to fix. 

<img width="1363" alt="CleanShot 2023-07-15 at 19 57 12@2x" src="https://github.com/hackforla/website/assets/95109313/a4ef33ce-5671-4f0f-9d34-4db2cfed6227">

I think if a codebase had single and double quotes switching back and forth, it could potentially stress new team members. I know it would stress me out, haha.

<img width="1048" alt="CleanShot 2023-07-15 at 20 03 12@2x" src="https://github.com/hackforla/website/assets/95109313/f1d31359-796a-41c2-8c48-22016118a65f">

And in this example, I clicked a random js file, which already gives me a useful measure. About a variable that isn't defined, I think those things are super helpful on those big files I tend to get overwhelmed. 😆

**Comment by ronaldpaek** [comment]
Lastly, my last task was to fix the liquid syntax, and actually, that was kind of the reason why I took on this task, but I guess all of this stuff is tied together. I'm not that detailed and organized, so I took a lot of videos and pictures and am reporting my findings.

 
<img width="1093" alt="CleanShot 2023-07-15 at 20 05 33@2x" src="https://github.com/hackforla/website/assets/95109313/fcb2c37b-10ec-4ac9-9d12-54d23db87a40">


I could not solve this issue yet, but I am thinking of reorganizing the liquid data, probably in a separate file. I'm just not 100% confident about how the data flows and is used, yet I still need to review the codebase some more.

<img width="250" alt="CleanShot 2023-07-15 at 20 09 00@2x" src="https://github.com/hackforla/website/assets/95109313/9c74138c-29b0-4e8a-b844-9d8a4ad9e2f9">

Oh yes, I actually ended up creating a lot of config files. I wanted to mention I had to init the root folder to node so I could install things on the package.json.

I know I don't think I didn't it when I just did the linter for JS, but when I was looking into the pre-commit stuff since it's a front-end/client side thing, you need a package.json to be in the root, but I'm just reporting my findings I'm sure there is a better way, but at least we have some data, that this is all possible, and it can be done incrementally without breaking everything. 

<img width="812" alt="CleanShot 2023-07-15 at 20 13 04@2x" src="https://github.com/hackforla/website/assets/95109313/f5fe990b-f025-4278-afe8-2dafb0e46c03">

<img width="841" alt="CleanShot 2023-07-15 at 20 13 23@2x" src="https://github.com/hackforla/website/assets/95109313/ebfaa066-1b37-4e3a-ba55-8a09204d3cdc">

Okay, I am done with my report. 😄 
@roslynwythe @t-will-gillis @blulady @ExperimentsInHonesty

**Comment by ronaldpaek** [comment]
I hope not to sound like a salesman for linting and formatting software. But now I'll post more photos to convince us why we want this.

<img width="849" alt="CleanShot 2023-07-15 at 21 39 33@2x" src="https://github.com/hackforla/website/assets/95109313/aa768a93-007f-4b9a-82d6-acb8ac50267b">

<img width="860" alt="CleanShot 2023-07-15 at 21 40 22@2x" src="https://github.com/hackforla/website/assets/95109313/336620fd-9cd2-4a69-add9-0cae8910f4e8">

I think this is a good thing. Large codebases are intimidating, and it's worse if much of the code is not even. Being used, and if it is harder for new people to adopt the style we want, it will ultimately take longer to ramp up.

<img width="860" alt="CleanShot 2023-07-15 at 21 43 41@2x" src="https://github.com/hackforla/website/assets/95109313/b1e2b260-5dec-437b-ae99-8e07c7fc0970">

Clean Code = Happy Coder. It's like studying on a cluttered desk. 😆 

<img width="871" alt="CleanShot 2023-07-15 at 21 45 12@2x" src="https://github.com/hackforla/website/assets/95109313/39e29bca-6c62-47a9-9e45-4d44a55db190">

I'd be willing to do all transferring/updating and 10000 commits to update every 1 week if you want ;)

<img width="869" alt="CleanShot 2023-07-15 at 21 47 12@2x" src="https://github.com/hackforla/website/assets/95109313/65a9279d-978e-483a-afc2-ebdccee65c7e">

**Comment by ExperimentsInHonesty** [comment]
@ronaldpaek why did you unassign?  Where should this issue be moved?

**Comment by ExperimentsInHonesty** [comment]
Once this issue comes out of the icebox, This issue will need a really good read, and then a decision on what to do next by the dev lead.

**Comment by ExperimentsInHonesty** [comment]
- @roslynwythe   I don't understand the dependencies
> - [ ]  Figure out which js files use liquid (and the least liquid in any file)
> - [ ]  Refactor a js file that uses liquid into two separate files
> - [ ]  Roll out plan for implementation
