### ISSUE TITLE
UX Research Roadmap for the Impact page content

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1696]
### Overview
We need to conduct UX Research to determine what would be the most effective content for the Impact page, to properly appeal to our target users.

### Action Items
- [x] Determine what forms of UX Research will be appropriate for determining potential content for the Impact page
   - [ ] Interviews, C&C Analysis
- [ ] Determine what content (data, quotes, etc) is feasible/possible to include in Impact page
- [ ] Conduct UX Research interviews for Impact page
- [ ] Summarize findings in executive summary/slide deck for Bonnie, PM's, and design team
- [ ] Draft the Impact Page Roadmap using template

### Resources/Instructions
#815 
[Figma file for Impact page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3491%3A1)
[Impact page original issue](https://github.com/hackforla/website/issues/815) 
[Planning for Impact Research Page](https://docs.google.com/document/d/1-rX6jkKYqrkeDvHVtSjAN2Wm2HdKx6rQb5zvmvg_Y6k/edit?usp=sharing)
[Recommended UX Methods for Impact Page](https://docs.google.com/document/d/19a2aOiB7vQ79Vme20fzSZdbO9UzGOB65G3NZuXQLD6s/edit)

**Comment by Basu3040** [comment]
@daniellex0  What's the target group here for the interview?

**Comment by ExperimentsInHonesty** [comment]
@Basu3040 
Organizations that we are going to ask for grant money from, who will fund things in LA but only if they can be useful beyond LA.
Corporate impact investors who want to work with global concerns

**Comment by JackieRiley1** [comment]
Here is the planning guide for the impact research methods
(https://docs.google.com/document/d/1-rX6jkKYqrkeDvHVtSjAN2Wm2HdKx6rQb5zvmvg_Y6k/edit?usp=sharing)

I have made recommendations for the type of UX methods needed for the Impact page: (https://docs.google.com/document/d/19a2aOiB7vQ79Vme20fzSZdbO9UzGOB65G3NZuXQLD6s/edit?usp=sharing)

**Comment by JackieRiley1** [comment]
Jackie shared the "Planning for Impact Page" document at the team meeting on 1/16.  Bonnie, Simone, Providence and Jackie will meet again on 1/19 @3PM (Central) to prioritize users groups and research questions to inform the content of the impact page.

**Comment by sacamp** [comment]
Will follow up with @JackieRiley1  on current status of the issue.
