### ISSUE TITLE
Add illustrations to guide cards in Toolkit page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1708]
### Overview
We need to match illustrations to our guide cards on the Toolkit page so that each guide can have a unique, fitting image.

### Action Items
- [ ] Select one of the guides in the full guide topics list below 
- [ ] Find an illustration that matches the topic of the guide, and also matches the style of illustrations on the Hack for LA website overall
   - [ ] Choose the illustration (or illustration options) on [Freepik Stories](https://www.freepik.com/stories)
   - [ ] Click Edit button, and then adjust the color to HfLA pink (find exact hex # on Figma)
   - [ ] Click 'download SVG' 
   - [ ] Add the SVG image to the [Toolkit page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) (in blue rectangle on bottom left) along with the guide name, link, and the following credit information because devs will need this:
      - Name: _____ (what the illustration is called on Freepik- it's usually in the URL and below the image)
      - Used in: Toolkit
      - Artist: stories
      - Provider: Freepik
      - Link to image on Freepik: _____ (must be Freepik link, not the image editing program Storyset link)
   - [ ] Add a comment on the guide's issue (linked below next to each guide listed) that says "For devs adding this guide to the Toolkit page: the guide card Illustration and image credit information is in the [Toolkit page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) (blue rectangle on bottom left) " 
      - [ ] This has to be via Figma because you can't post an svg image in a Github comment/post, and these images do have to be svg files (they will make the page load faster)
   - [ ] Note in a comment in this issue below all of the guides that you completed adding illustrations to (by adding the link to the image and the proper credits in a comment on each guide's issue), so that we can keep track of the guides that already have illustrations

Guides to find images for (check off any that you complete):

- [x] How to assign and work on issues at HfLA ([guide](https://docs.google.com/document/d/15KE8jVvp2ZhmkX7MY7Rethoye0LF5H0Gb8F29lrqeG0/edit#)) - [Issue # 227](https://github.com/hackforla/knowledgebase-content/issues/87)
- [x] How to write a one-sheet ([guide](https://docs.google.com/document/d/14-nYNCjrMrC8lucUNBfLOFQZk2sWbkRlJgigWDAlqlI/edit#heading=h.z4tpbshl55b9)) - [Issue # 74](https://github.com/hackforla/knowledgebase-content/issues/85)
- [x] How to set Slack reminders ([guide](https://docs.google.com/document/d/1T-h3YJ8Pp4hsfq9ouRHRnwrrHROSz0-kQz5O9VTE62U/edit#heading=h.v35todi80sv3)) - [Issue # 88](https://github.com/hackforla/knowledgebase-content/issues/84)
- [x] How to use images on HfLA websites ([guide](https://docs.google.com/document/d/1w9EIJYe-HL5dVbTnp8dTiyOM_KDR9VH8RBM77bR30Co/edit#heading=h.c8tc614ce3iu)) - Issue hackforla/knowledgebase-content#105 
- [x] How HfLA uses Github Kanban boards ([guide](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit#heading=h.nl3p4nf4eqb4)) - [Issue # 70](https://github.com/hackforla/knowledgebase-content/issues/16)
- [x] Product Manager Interview ([guide](https://docs.google.com/document/d/1GvEAtmFYpG1be2tcBADrlTCy4TTzNd0qGeit2voaOc4/edit#heading=h.v35todi80sv3)) -[Issue # 92](https://github.com/hackforla/knowledgebase-content/issues/13)
- [x] Figma for Developers ([guide](https://docs.google.com/document/d/1Is5Ah0tUH07kWYG_J6HTo0RF8Z9Foi2l/edit?rtpof=true)) - [Issue # 27](https://github.com/hackforla/knowledgebase-content/issues/125)
- [x] Giving Feedback on Designs ([guide](https://drive.google.com/file/d/1O45DnXZ6vVdmEI8At1b1oGkoWQjWAH8Z/view?usp=sharing)) - [Issue # 21](https://github.com/hackforla/knowledgebase-content/issues/132)
- [x] How to Present your Design Work ([guide](https://docs.google.com/document/d/1DpGCa6tvYQrJb5Lmv2LggmCZeT8FEHj9/edit?rtpof=true)) - [Issue # 23](https://github.com/hackforla/knowledgebase-content/issues/137)
- [x] How to Add Screenshots and Graphics to your Guide ([guide](https://docs.google.com/document/d/1liK5u5_jKa06h3pFng4O7zC9pcf_jJsN)) - [Issue # 92](https://github.com/hackforla/knowledgebase-content/issues/91)

### Resources/Instructions
[Toolkit page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) (in blue rectangle on bottom left)
[Toolkit page](https://www.hackforla.org/toolkit/)
[Credits page](https://www.hackforla.org/credits/)

**Comment by SaashaG** [comment]
Est Completion Date 6/16/21

**Comment by SaashaG** [comment]
Complete: 06/16/21
Figma link: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967
( Blue Rectangle)
![image](https://user-images.githubusercontent.com/83323065/122325257-3ae17f00-cef8-11eb-8bc8-66caf2120ca1.png)

**Comment by daniellex0** [comment]
Great job @SaashaG , thank you!

Notes for future volunteers that take on this issue:
- The source link should be to Freepik URL (not storyset editing site)
- The image name can be found below the image on Freepik and in the URL)

**Comment by anonymousanemone** [comment]
Complete: 6/26/21
Figma link: [Toolkit page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) (blue rectangle on bottom left)
![Screen Shot 2021-06-25 at 4 29 02 PM](https://user-images.githubusercontent.com/86015625/123493794-76540b80-d5d2-11eb-97c3-9219d9a7c393.png)

**Comment by daniellex0** [comment]
Great job @anonymousanemone !

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey it looks like all the related guides have images (they are checked off), what are the next steps on this?

**Comment by ExperimentsInHonesty** [comment]
Bonnie will close this issue and make a new one (putting in icebox) to revisit the toolkit page once we have some finished guide.
