### ISSUE TITLE
HfLA: ALL TEAM Meeting Agenda☀️

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1734]
### Overview
This issue tracks the agenda for the HFLA website team and weekly roll call.

Please check in on the [Roll Call Spreadsheet]() 

### Weekly Agenda
[21/06/20](https://github.com/hackforla/website/issues/1734#issuecomment-864607554)
[21/06/27](https://github.com/hackforla/website/issues/1734#issuecomment-864609580)
[21/07/18](https://github.com/hackforla/website/issues/1734#issuecomment-881875270)
[22/01/16](https://github.com/hackforla/website/issues/1734#issuecomment-1013922203)
[22/01/23](https://github.com/hackforla/website/issues/1734#issuecomment-1019538611)
[22/01/30](https://github.com/hackforla/website/issues/1734#issuecomment-1025016798)
[22/02/06](https://github.com/hackforla/website/issues/1734#issuecomment-1030883057)
[22/02/13](https://github.com/hackforla/website/issues/1734#issuecomment-1038301427)
[22/02/20](https://github.com/hackforla/website/issues/1734#issuecomment-1046287098)
[22/03/06](https://github.com/hackforla/website/issues/1734#issuecomment-1059882684)

**Comment by Sihemgourou** [comment]
### Agenda 21/06/20

- [ ] Brief on leading dev team 
- [ ] Improving the development to design handoff

**Comment by Sihemgourou** [comment]
Agenda 21/06/27

- [ ] Go through all the feature missing issues

**Comment by Sihemgourou** [comment]
Agenda 21/06/27

- [x] Go through all the feature missing issues
- [x] Choose a timekeeper 
- [x] New organization for issue review during the ALL TEAM
- [ ] Should we remove the question about getting the github picture and take it directly ? Because we are already showing all the contributors pitcures on the project profile cards (see akib comment in PR toggle see more/see less on wins card #1732) => we wanted to ask which image they prefer

**Comment by Sihemgourou** [comment]
Agenda July 4: 

- [x] Best practice : When to take a new issue ? 2 issues at the same time = no
- [x] How to update your issue ? To Update label, Checkboxes ([1 example](https://github.com/hackforla/website/issues./1793),[ 2nd example](https://github.com/hackforla/website/issues/1817)); Blocker ? (Ice box, seek help)
- [x] website merge team
- [x] Credit page !
- [x] ask if everyone has the calendar invite
- [x] Talk with the dev team about how the column dev meeting is working / create notes

**Comment by Sihemgourou** [comment]
Agenda July 11: @sayalikotkar will run the meeting 

- [ ] Check the review column 
- [ ] Check the issues with the to update label

**Comment by Sihemgourou** [comment]
Agenda for July 18
- [x] Guthub analytics
- [x] Github automation
- [x] Reminder about using the template when updating your issue

Actions to take: 

- [x] @Sihemgourou will create an issue to change the wording on the header of the homepage

**Comment by Sihemgourou** [comment]
Agenda for July 25

- [ ] New column "New Issue Approval"
- [ ] #1983 see @ExperimentsInHonesty comment

**Comment by ExperimentsInHonesty** [comment]
2022-01-09

### Prework
- [ ] PM to review the New Issue Approval Column for
  - [ ] Design
  - [ ] Research
  - [ ] Front End
  - [ ] Back End

### Recurring Items
- [ ] Review anything in the [Questions and Review](https://github.com/hackforla/website/projects/7#column-8178690) Column

**Comment by JessicaLucindaCheng** [comment]
# 2022-01-16

### Prework

### Recurring Items
- [ ] Review anything in the [Questions and Review](https://github.com/hackforla/website/projects/7#column-8178690) Column

### Questions
- Question for UX Design from Development: For the Typography section of the [Figma Design Systems](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3), can the Class names all be changed to lowercase?
  - So, Title1 becomes title1, Title 2 becomes title2, Paragraph1 becomes paragraph1, Paragraph2 becomes paragraph2, and changing the rest of the title and paragraph classes to lowercase.
     - Answer: Yes, Isaac will change it (since he has edit rights on the figma).  
  - Also, [Figma comment](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr?node-id=3464:3#140625597) about it
  <details>
    <summary>Current Class names for Headings and Paragraphs</summary>
    <img width="880" alt="paragraph-header-class-names" src="https://user-images.githubusercontent.com/31293603/149849477-8532ef4d-1fcd-4e50-abf5-f42471a37009.png">
  </details>
- Question for UX Design/PM from Development: For [issue #2464](https://github.com/hackforla/website/issues/2464#issuecomment-1013809482), Isaac still wants the header colors to be changed. However, Isaac wants us to hold off on the "Adjust bottom padding of SDG card so that it matches the Figma design." portion of the issue because the 14px font size for the paragraph is not easy to read and that will impact how the padding looks. How should we proceed?
   - Design to create a new issue
      -  The font size in figma should be 16px, like the current website.
     -  website SDG image is 120px and on figma its 88. Since we are increasing font size to 16, figma should update SDG size to match website
- Question for UX Design from Development: On the [Wins page](https://www.hackforla.org/wins/), the star icon has a tooltip that can have various length text. On the 4th page of the [Wins form](https://docs.google.com/forms/d/e/1FAIpQLSeTiFjtxKbYgrJHAdFUovXlE55BdwwUQ9NePOXRY2q-h-w1tg/viewform), the star icon text comes from the question, "What do you want to celebrate (select all that apply)?" and choosing "Other," which allows input of various length text. Bonnie said we should shorten all tooltips to a certain number of characters/words and then click "See more" to see the full text for what the icon is. Could you redesign each tooltip so that the description for each tooltip is shortened to be a few words/characters? You will need to figure out many characters/words the text for star tooltips will display since it can differ every time.
  - Will discuss in Design/PM meeting

- Design: Jenna's issue https://github.com/hackforla/website/issues/2606

**Comment by JessicaLucindaCheng** [comment]
2022-01-23

### Prework

### Recurring Items
- [ ] Review anything in the [Questions and Review](https://github.com/hackforla/website/projects/7#column-8178690) Column

### Questions
- Question for UX Design: Are paragraphs supposed to be the same font size across different size screens (mobile, tablet, desktop) for the privacy policy page?
  - Just follow what is on the Figma design in terms of font size for the privacy policy page.

**Comment by JessicaLucindaCheng** [comment]
2022-01-30

### Prework
- [ ] PM to review the New Issue Approval Column for
  - [ ] Design
  - [ ] Research
  - [ ] Front End
  - [ ] Back End

### Recurring Items
- [ ] Review anything in the [Questions and Review](https://github.com/hackforla/website/projects/7#column-8178690) Column

### New Items
- [x] Make Jessica a maintainer for the repo

**Comment by JessicaLucindaCheng** [comment]
2022-02-06

### Prework

### Recurring Items
- [ ] Review anything in the [Questions and Review](https://github.com/hackforla/website/projects/7#column-8178690) Column

### New Items
 - [x] For Design from Development: The Trophy link on the [Credits page](https://www.hackforla.org/credits/) goes to "Page Not Found" on the external website [The Noun Project website](https://thenounproject.com/). Here is the link it goes to https://thenounproject.com/term/trophy/3115497/. Please find the image and let development know the correct link. If it can't be found, then please find a different image to use and provide all the information needed to create a new credit to development.
    <details>
      <summary>Screenshot of problem: Trophy link on Credits page</summary>
      <img width="212" alt="credits-trophy-link" src="https://user-images.githubusercontent.com/31293603/150619089-7b84154d-6c73-4ed8-977f-8d1059fbee98.png">
    </details>

**Comment by JessicaLucindaCheng** [comment]
2022-02-13

### Prework

### Recurring Items
- [x] Review anything in the [Questions and Review](https://github.com/hackforla/website/projects/7#column-8178690) Column

### New Items
- [x] Follow up on issue #2773, onboarding pending.
- [x] Request feedback on epic issue #2775
- [x] For the [ignore labels](https://github.com/hackforla/website/labels?q=ignore), what color do you want them to be?

**Comment by JessicaLucindaCheng** [comment]
2022-02-20

### Prework

### Recurring Items
- [ ] Review anything in the [Questions and Review](https://github.com/hackforla/website/projects/7#column-8178690) Column

### New Items
- [x] For Design from Dev: I don't think the title and link for the [credit info](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724) is correct. Here is a screenshot of it:
  <img width="440" alt="titleAndTitleLinkWrongInfo" src="https://user-images.githubusercontent.com/31293603/154855482-4f1c29fa-652d-4693-ae8b-b08aa65f8cbb.png">
  - [x] ~Reach out to kristine-eudey~ Don't need to. Found the correct link already. 
- [ ] For Design from Dev: The font size for the mini cards on [Program Areas page](https://www.hackforla.org/program-areas) page is 13px for both mobile and desktop views. On the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21046), the font size for the mini cards is 13px for desktop and 14px for mobile. Is this okay for the icons according to the Design System?
  - Design System notes on text size:
    - [Text under paragraph classes](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144)
    - [Text Size section](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4724%3A32)
  - [ ] Put in decision record that it is okay as is because it takes a lot of work and the text size guide in figma design system
  
- [x] https://github.com/hackforla/website/issues/2606#issuecomment-1040776157
  - [x] ~Reach out to the people who worked on this issue https://github.com/hackforla/knowledgebase-content/issues/134~ No need the designer was able to increase the font size to 16px, so fits the requirements
    - [x] ~Reach out to them via slack first and then email if no response~

**Comment by SAUMILDHANKAR** [comment]
Mar 6, 22

### Prework

### Recurring Items

### FYI
- Requesting few days off next week, Mar 13-16 (Saumil)

### New Items
- [x] Discussion item for meeting on Mar 6: https://github.com/hackforla/website/issues/2401
- [x] Should website leadership have access to engineering team roster?

**Comment by ExperimentsInHonesty** [comment]
2022-10-30 All Team Meeting Agenda
- [x] https://github.com/hackforla/website/issues/3109 - we added a new requirement
- [x] https://github.com/hackforla/website/issues/2010 - asking why Katherine closed it
- [x] https://github.com/hackforla/website/issues/3034 - it's in the last comment on the issue.  This is how the handoff issues work.  The designers or researchers finish the issue, it gets accepted by product, then its handed off to dev leads to make an issue for it (by product adding it to the new issue approval column with a `ready for dev lead` label)
- [x] https://github.com/hackforla/website/issues/3626 - added new categories (technologies)

**Comment by ExperimentsInHonesty** [comment]
2022-11-13

**Comment by 7kram** [comment]
2022-11-06 All Team Meeting Agenda
- [x] #3277 - Ask about Sarah's comment on research for accessibility
- [x] #2114 - We need clarification on what the action items in this section mean.
- [x] #3641 - We're confused about the action items in the issue

**Comment by 7kram** [comment]
2022-11-13 All Team Meeting Agenda

- [x] #3691 We'd like a cleaner version of the issue before it gets the "ready for milestone" label
- [x] #3701
- [x] Did you hear back from new people on Slack? (ex. #3571)

**Comment by bishrfaisal** [comment]
2022-11-20 All Team Meeting Agenda
- [ ] https://github.com/hackforla/website/issues/3191 We would like to discuss this issue with the team and get their opinion on what the best zoom background is for the HfLA organization.

**Comment by HackforLABot** [comment]
This issue was reopened because it did not have any of the following:
- A linked PR,
- An `Ignore` label
- A `non-PR contribution` label
