### ISSUE TITLE
Homepage Research - Donors / Partners / Advisors

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2015]
### Dependency
- [ ] #2706
- [ ] #2704 
- [x] #2589
- [x] #2705 

### Overview
We need to create personas for our three target user groups (volunteers, donors / partners, and advisors) in order to ensure the design of the site accounts for each of their goals and concerns, and to support alignment and communication across the team. 

### Action Items
UX / Research 
- [x] Compile existing volunteer research #2561 
- [x] Interview Bonnie to gain insight on donors/partners
- [x] Conduct interviews with donors/partners.
- [x] Present prototype of new homepage to interviewees for feedback. 
- [ ] Speak with Rachel Parker Chavez (works at Super By Design) Bonnie will connect us once we’re ready/have a set of questions reviewed and in place. She can advise us in terms of institutional giving and partnership/advisory. #2309 
- [x] Conduct affinity mapping in order to distill research of target groups and identify overarching themes
- [ ] Create personas from research findings
   - [x] individual donors
   - [ ] volunteers  #2662
   - [ ] corporate donors
   - [ ] partners
   - [ ] advisors

### Resources/Instructions
- [Donor/Partner Research Plan](https://docs.google.com/document/d/1ELtk7H_uubatggRcTO9imHzdheeiPWkDLs3KZepMwh0/edit)
- [HfLA UX Research - Google Drive Folder](https://drive.google.com/drive/folders/14ZChVwBKzURRPSey7NAZGDbMwA4BzwRo?usp=sharing)
- [Recording/transcript of interview with Bonnie 7/25/21](https://drive.google.com/drive/folders/1tQbN7EtJBmFuiASY4-9gw4pVVtoVw80R)
   - [Slide deck to summarize insights from interview with Bonnie](https://docs.google.com/presentation/d/1YYgEuKMGV_gmmxTLQF1gOvVd_wDJDN5E2f7mHwDorKg/edit#slide=id.gc6f8954bc_0_96)
- [Interview Questions for Donors & Financial Partners - Slide Deck](https://docs.google.com/presentation/d/1p5iOAOiqfWzjndOGhFkvL0FDSUfKRHrcHSmL1CA8J_c/edit#slide=id.ge77ae0ae07_0_0)
- [Miro Board for affinity diagramming](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Messaging and outreach communication to recruit interviewees]

**Comment by Basu3040** [comment]
Finished interview questions for the donors/partners/advisors. The document is for the review!

**Comment by Basu3040** [comment]
1. Progress: The research team is meeting on 8/9 to work further on the interview template and a short demographic survey.  We will also start working on the usability testing based on the updated design. Here is the document we are working on: https://docs.google.com/presentation/d/1p5iOAOiqfWzjndOGhFkvL0FDSUfKRHrcHSmL1CA8J_c/edit#slide=id.ge77ae0ae07_0_834
2. Blockers: None
3. Availability: 1-2 hours of collaborative work
4. ETA: 8/16/21

**Comment by Basu3040** [comment]
Progress: We reviewed the "Homepage redesign Plan" and resolved most of the issues. Waiting for the PM team to give us feedback on the plan. Completed interview guide to interviewing donors, now we need to finish the survey questionnaire.
Blockers: None
Availability: 2-3 hours of collaborative and individual work
ETA: 8/16/2021

**Comment by Basu3040** [comment]
We are looking for potential donors to get started with the interview process and survey. We reached out to the dev team and our team for possible leads.

**Comment by Basu3040** [comment]
Progress: "We have made changes to the Homepage redesign plan based on the suggestions of PMs. We still have a few questions that will be discussed in the meeting. 
Blockers: A few questions on KPIs
Availability:  2 hours of collaborative and  1 hour of individual work
ETA: 8/23/2021

**Comment by Basu3040** [comment]
Progress: PM team will review the interview guide 
Blockers: None
Availability: 2 hours of collaborative and 1 hour of individual work
ETA: 8/23/2021

**Comment by Basu3040** [comment]
@hackforla/website-pm Waiting for the PM team to review the interview guide. The research team is meeting tomorrow to review and go through the questions. Then we will run through it and it will be all set for the interview process to begin. Thank you all.

**Comment by Basu3040** [comment]
Progress: The interview guide and survey questionnaire are finished. We have run through the interviews. We will be conducting 30-40 mins interviews with each participant. We are aiming for 5 interviewees to start with. The plan is each person in the research team will conduct the interview with participants.
A review of the Research Plan will be done in the next UXR meeting.
Blockers: None
Availability: 2 hours of collaborative and 1 hour of individual work
ETA: 9/30/2021

**Comment by Basu3040** [comment]
Progress: We have cleaned the homepage redesign research plan. Interview and survey questions are done. Next, we will create questions for usability testing and layout a detailed plan of participant recruitment.
Our one password email is, siteresearch@hackforla.org. This email will be used to communicate with the interviewees. 
Blockers: None
Availability: 2 hours of collaborative and 1 hour of individual work
ETA: 9/13/2021

**Comment by Basu3040** [comment]
Progress:
This message is for the general channel to recruit donors/partners:
HfLA UX Research team is looking to interview people who have donated money and/or service in the past for social causes.  In this study we are trying to understand their motivations to donate for a cause.  If you know someone who has given a donation and would be willing to be interviewed and be part of a short survey (expected duration 45-50 mins), please contact @Basu3040 @kristine-eudey. Prospective participants can also directly email us. Our email address is:  sitesearch@hackforla.org. Thank you for your support.

**Comment by Basu3040** [comment]
Progress:  We will work on re-writing the homepage header, recruiting script for research participants, and on crafting the usability test for the homepage.
Blockers: None
Availability: 2-3 hours of individual and collaborative work.
ETA: 09/20/21

**Comment by ExperimentsInHonesty** [comment]
@Basu3040 I want to suggest a rewrite of this to make it clear we are not soliciting donations and to make sure it gets a response.  Are you ready for me to post this if you agree with changes?


💸 **HfLA UX Research team is conducting research into what motivates people to donate to social causes.**

📋 If you or someone you know has donated to a social cause and would be willing to be interviewed (expected duration 45 mins), please contact @Basu3040 @kristine-eudey. Prospective participants can also directly email us at sitesearch@hackforla.org. 

Thank you for your support.  🤓 _p.s. we are not asking for donations, we are conducting interviews._

**Comment by Basu3040** [comment]
@ExperimentsInHonesty Sounds good. I agree with you and please post this on the channel. In the meantime, we are working on writing a script to recruit participants.

**Comment by ExperimentsInHonesty** [comment]
Slacked in the general channel

Bonnie  12:20 PM
@channel :money_with_wings: HfLA UX Research team is conducting research into what motivates people to donate to social causes.
:clipboard: If you or someone you know has donated to a social cause and would be willing to be interviewed (expected duration 45 mins), please contact @Basudhara Sen @Simone Campbell  via our channel #hfla-site-ux   -- Prospective participants can also directly email us at sitesearch@hackforla.org.
Thank you for your support. :nerd_face: p.s. we are not asking for donations, we are conducting interviews

**Comment by Basu3040** [comment]
Progress: 1. Participant recruitment script has been posted in the general channel
                2. Potential participants have contacted and team and we are scheduling the interviews
                2. We have started working on the script for recruiting corporates
Blockers: None
Availability: 3-4 hours every week (both individual and collaborative)
ETA: 10/15/21

**Comment by Basu3040** [comment]
Progress: 
1. Participants have been contacted and the interviews are scheduled 
2. The script for recruiting corporates is finished and reviewed by Bonnie
Blockers: None
Availability: 3-4 hours every week (both individual and collaborative)
ETA: 10/15/21

**Comment by Basu3040** [comment]
Progress: Participants have been contacted and the interviews are scheduled.
HfLA zoom will be used to interview participants and record their responses. 
Blockers: Interviewees are canceling interviews
Availability: 3-4 hours every week (both individual and collaborative)
ETA: 10/15/21

**Comment by Basu3040** [comment]
Progress: 3 interviews are done and will start analysing the data next week
Blockers: 2 more interviewees are required
Availability: 3-4 hours every week (both individual and collaborative)
ETA: 10/15/21

**Comment by Basu3040** [comment]
Progress: We have started analyzing the data
Blockers: Corporate donors need to be contacted
Availability: 3-4 hours every week (both individual and collaborative)
ETA: 10/15/21

**Comment by Basu3040** [comment]
Progress: Interview 4 is done and we are analyzing the data
Blockers: Only individual donors are interviewed
Availability: 2-3 hours a week
ETA: 10/31/2021

**Comment by Basu3040** [comment]
Progress: We are creating the persona for the project
Blockers: It is hard to recruit donors for the interview process
Availability: 4-6 hours individually and collaboratively
ETA: 10/30/2021 
Pictures: https://docs.google.com/document/d/18vYTKszsGAVnhrQodkHp7HS3FQOQ6eClmogf_ePCD1g/edit

**Comment by sacamp** [comment]
Progress: Persona created, final research presentation being prepared
Blockers: none
Availability: 4-6 hours individually and collaboratively
ETA: 11/07/2021
Pictures: https://docs.google.com/document/d/18vYTKszsGAVnhrQodkHp7HS3FQOQ6eClmogf_ePCD1g/edit

**Comment by sacamp** [comment]
Progress: Individual donor persona completed. Will begin institutional donor research next.
Blockers: None
Availability: 3-4 hours individually and collaboratively
ETA: 12/7/21
Pictures: [Individual donor research results](https://docs.google.com/presentation/d/1qJZMH92gPwCt3d34Ba5RFvw4ZnH-NAqej2wQRPn5yXE/edit#slide=id.g100598eeae6_0_296)

**Comment by sacamp** [comment]
Progress: Individual donor persona completed. Will begin corporate donor research next.
Blockers: waiting on corporate donor introductions
Availability: 3-4 hours individually and collaboratively
ETA: 12/7/21

**Comment by sacamp** [comment]
Progress: Onboarded new UX team members, working on tailoring research plan to each user group
Blockers: none
Availability: 2-4 hours collaborative
ETA: 12/15

**Comment by sacamp** [comment]
Progress: Individual donor persona completed. 
Blockers: waiting on corporate donor introductions
Availability: 3-4 hours individually and collaboratively
ETA: 1/7/21
