### ISSUE TITLE
HFLA.org Roadmap

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#2040]
### Overview
As a product manager, I need to create a roadmap each 6 months so that the website team work more efficiently.

### Action Items

Product

- [x] Create milestones from prioritization framework
- [x] Check milestones with Bonnie 
- [x] Create milestones filters
- [x] Prioritize the prioritized backlog
- [x] Check filters and milestones with Bonnie
- [x] Prioritize all the issues in the Prioritized Backlog by Milestone
- [ ] Review all the Milestones to make sure that all the issues necessary to complete the milestone are included.

### Resources/Instructions
- Marketing Inventory [Prioritization framework ](https://docs.google.com/spreadsheets/d/1x1DhAr_tJ2m-6hVmzoaWB9nOuq8lRiE4q8Xuj5AwLOI/edit?usp=sharing) - used by the marketing team to understand details about the project
- [Current Prioritization](https://docs.google.com/spreadsheets/d/1g3QQH2qsWGa11KgpvE-RdlhEfqD-8gdw1TJAV0LNzl8/edit#gid=1754442892)
- [Project Milestones](https://github.com/hackforla/website/milestones?direction=asc&sort=title&state=open)

**Comment by Sihemgourou** [comment]
Progress: Milestones implemented into  project board
Blockers: none
Availability: 2h
ETA: 08/15
