### ISSUE TITLE
Add tracking code for Google Tag Manager to three pages in the code

### ISSUE THREAD

**Issue by PamelaLi36** [hackforla/website#2164]
### Overview
We need to connect Google Tag Manager to the website in order to test out Event Tracking

### Action Items
- [x] Add Google Tag Manager script within the [`<head>` of the page](https://github.com/hackforla/website/blob/gh-pages/_includes/head.html)
- [x] Add the code snippet in the resources section to the Events (should be pages that can be interacted with) 
- [x] Add the code snippet in the resources section to the Projects (should be pages that can be interacted with)
- [x] Add the code snippet in the resources section to the Credits (should be pages that can be interacted with)   
- [ ] Run locally after making changes and verify you do not have any errors in the developer console

### Resources/Instructions
Paste this code as high in the `<head>` of the page as possible:
```html
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PMQK7VL');</script>
<!-- End Google Tag Manager -->

```

Additionally, paste this code immediately after the opening <body> tag of 3 pages:
```html
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PMQK7VL"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```
[Google Tag Manager Tracking Code](https://docs.google.com/document/d/10CngMu6wCbKzNAg_yKFRDXhDND8mmmdnautM8RJbr4o/edit)
This issue is an extension of #1730 
https://github.com/hackforla/website/blob/gh-pages/_includes/head.html
