### ISSUE TITLE
Standardize how 'Overview' links open pdf files

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2211]
### Dependency
- [x] #2238 
- [x] #2233
- [x] #2234
- [x] #2235
- [x] #2236
- [x] #2237
- [x] #2238
- [x] #2239
- [x] #2240
- [x] #2162
- [x] #2242
- [x] #2243

### Overview
As a user, clicking on the 'Overview' link for each project page should act the same way. Currently, the 'Overview' links for each project act differently. Clicking the link should open a new tab to the pdf file directly. We will convert each action item into an issue and create a pull request to close the corresponding issue. Then, as a last action item, we will check all overview links appear on the homepage to make sure they are all working the same way. 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How pdf files currently open](https://github.com/hackforla/product-management/blob/master/project-one-sheets/100-Automations-Project-One-Sheet.pdf)
[How pdf files should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

The process for a developer would involve:
- Use the newly created directory for pdf files: [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- Place a copy of a project's pdf overview file into the /assets/pdfs directory
- Change the 'Overview' link for a project to point to the pdf file living under /assets/pdfs
- Ensure that the links in both the home page and the project's dedicated page open the pdf file properly after the change

### Action Items
- [x] Check all overview links that appear on the [Projects page](https://www.hackforla.org/projects/) to make sure they are all working the same way and opening the pdfs the same way
  - [x] If the overview links do **not** work the same way nor open the pdfs the same way, let a Merge Team member or Technical Lead know so that they can help you with writing issues to fix the overview links.
  - [x] If the overview links all work the same way and open the pdfs the same way, add a new comment to the homepage launch issue #2481 stating all the overview links work correctly and adding this link to your comment: #2211 

### Resources/Instructions
[How pdf files currently open](https://github.com/hackforla/product-management/blob/master/project-one-sheets/100-Automations-Project-One-Sheet.pdf)
[How pdf files should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)
[Project Page](https://www.hackforla.org/projects/)
Each individual landing page for affected projects: [100 Automations as an example](https://www.hackforla.org/projects/100-automations)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

**Comment by ExperimentsInHonesty** [comment]
@macho-catt did you use the label collaborative work because this issue is an epic?  Or because you did this issue with another person?

**Comment by macho-catt** [comment]
@ExperimentsInHonesty because this issue is an epic. Should that be a different label?

**Comment by JessicaLucindaCheng** [comment]
Note: All the issues to change the Overview links are completed. The only remaining action items are to check that all overview links that appear on the homepage work the same way and to add a link and note to the homepage launch issue https://github.com/hackforla/website/issues/2481

**Comment by abdiaz2018** [comment]
ETA: end of day friday
Availability: 2 hours

**Comment by abdiaz2018** [comment]
Availability: 3 hours 
ETA: Thursday night

**Comment by JessicaLucindaCheng** [comment]
Developer has added the following comment in the homepage launch issue: https://github.com/hackforla/website/issues/2481#issuecomment-1248871301. Thus, I'm closing this issue as completed.
