### ISSUE TITLE
Wiki: Create a wiki for milestone information

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2316]
### Dependency
- [x] #1534 
- [x] #3636

### Overview
As a member of the team, we need to have a basic understanding about our project board. For this issue, we will create a milestone wiki that will provide basic information about how our milestone system works.

### Action Items
- [x] Create a wiki that notes all of our current milestones.
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Please refer to [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) for instructions about where to place "Content to be Added/Edited in the New website-wiki Repo."

### Resources/Instructions

- [BETA Milestone wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-Milestones)
- [HfLA Website Milestone page](https://github.com/hackforla/website/milestones?direction=asc&sort=title&state=open)
- [All the issues with no milestones](https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)
- [link to the issue table to display issues with no milestone](https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)

**Comment by phuonguvan** [comment]
@Providence-o Hey! This is the design team lead and I was wondering if you are still working on this project. Bonnie told me to update you guys so let me know as soon as possible!

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty This issue is missing a milestone and nobody is assigned to, so I am moving this back to New Issue Approval.

**Comment by JessicaLucindaCheng** [comment]
This issue needs to be edited by a lead to reflect our migration to the [website-wiki repo](https://github.com/hackforla/website-wiki). For more info, read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki).

**Comment by ExperimentsInHonesty** [comment]
Make sure to explain difference between Onboarding Flow and Team Workflow milestones - question came up when working on this issue https://github.com/hackforla/website/issues/4350

**Comment by Josiah-O** [comment]
Revewing issues without milestone for better categorisation and generate content for Milestones Wiki.

- [ ] Issue #4587 fits into [Program areas visibility](https://github.com/hackforla/website/milestone/11)
   - [ ] 
- [x] Issue #4601 fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] x
- [x] Issue #4595 fits into [05. Know HFLA](https://github.com/hackforla/website/milestone/6)
   - [ ] 
- [x] Issue #4594 fits into [05. Know HFLA](https://github.com/hackforla/website/milestone/6)
   - [ ] 
- [x] Issue #4593 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [x] Issue #4592 fits into [05. Know HFLA](https://github.com/hackforla/website/milestone/6)
   - [ ] 
- [ ] Issue #4591 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/issues/4591)
   - [ ] 
- [x] Issue #4590 fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] 
- [ ] Issue #4589 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [ ] Issue #4587 fits into [09. Program areas visibility](https://github.com/hackforla/website/milestone/11)
   - [ ] 
- [ ] Issue #4565 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [x] Issue #4564 fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] 
- [ ] Issue #4563 fits into [09. Program areas visibility](https://github.com/hackforla/website/milestone/11)
   - [ ] 
- [ ] Issue #4562 fits into [09. Program areas visibility](https://github.com/hackforla/website/milestone/11)
   - [ ] 
- [ ] Issue #4556 fits into [11. HFLA impact](https://github.com/hackforla/website/milestone/12)
   - [ ] 
- [x] Issue #4544 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [ ] Issue #4543 fits into [10. Frameworks](https://github.com/hackforla/website/milestone/14)
   - [ ] 
- [ ] Issue #4542 fits into [02. Security](https://github.com/hackforla/website/milestone/18)
   - [ ] 
- [ ] Issue #4541 fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] 
- [ ] Issue #4538 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [ ] Issue #4537 fits into [06. Data strategy](https://github.com/hackforla/website/milestone/9)
   - [ ] 
- [x] Issue #4536  fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] 
- [x] Issue #4534 fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] 
- [ ] Issue #4533 fits into [03.01 Roadmaps](https://github.com/hackforla/website/milestone/19)
   - [ ] 
- [ ] Issue #4532 fits into [w. Accessibility](https://github.com/hackforla/website/milestone/10)
   - [ ] 
- [x] Issue #4525 fits into [x. Technical debt](https://github.com/hackforla/website/milestone/16)
   - [ ] 
- [x] Issue #4514 fits into [w. Accessibility](https://github.com/hackforla/website/milestone/10)
   - [ ] 
- [ ] Issue #4510 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [x] Issue #4508 fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] 
- [x] Issue #4507 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [x] Issue #4506 fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] 
- [x] Issue #4504 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [x] Issue #4492 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [x] Issue #4466 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [x] Issue #4456 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [x] Issue #4455 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [x] Issue #4454 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [ ] Issue #4452 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [x] Issue #4440 fits into [04. Donation flow](https://github.com/hackforla/website/milestone/3)
   - [ ] 
- [ ] Issue #4405 fits into [08. Team workflow](https://github.com/hackforla/website/milestone/8)
   - [ ] 
- [x] Issue #4390 fits into [06. Data strategy](https://github.com/hackforla/website/milestone/9)
   - [ ] 
- [x] Issue #4388 fits into [06. Data strategy](https://github.com/hackforla/website/milestone/9)
   - [ ] 
- [x] Issue #4370 fits into [w. Accessibility](https://github.com/hackforla/website/milestone/10)
   - [ ] 
- [ ] Issue #4363 fits into [x. Technical debt](https://github.com/hackforla/website/milestone/16)
   - [ ] 
- [ ] Issue #4332 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [ ] Issue #4331 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [ ] Issue #4324 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [ ] Issue #4315 fits into [03.02 Onboarding flow](https://github.com/hackforla/website/milestone/5)
   - [ ] 
- [x] Issue #4301 fits into [w. Accessibility](https://github.com/hackforla/website/milestone/10)
   - [ ] 
- [x] Issue #4300 fits into [w. Accessibility](https://github.com/hackforla/website/milestone/10)
   - [ ] 
- [ ] Issue #4299 fits into [x. Technical debt](https://github.com/hackforla/website/milestone/16)
   - [ ] 
- [ ] Issue #4186 fits into [03.01 Roadmaps](https://github.com/hackforla/website/milestone/19)

**Comment by ExperimentsInHonesty** [comment]
### Toolkit relaunch
issues that go into the relaunch

### Ongoing 
Issues that never close, because we just reuse them.  Usually they will have instructions on how to do the thing.  We might also use the issue for tracking having done it
- Agendas  (each agenda appears as a comment)
- label checks (each week, the next audit is added to a comment)
- onboarding and offboarding (each person who is onboarded, has a checklist in a comment.  Later, their offboarding also happens in the same issue on a new comment, and then both comments are hidden).

### Frameworks
This milestone might get depreciated.  Have not decided.  Before assigning any issue to this milestone, discuss with the Product Team.
- A plan to do a major feature
  - where we are storing things
  - how we will maintain

### Ignore Test
Issues that are using in the process of testing Automations.  They should be excluded from Metrics and Analysis (unless the metrics/analysis are about how many test issues we create).

**Comment by Josiah-O** [comment]
**Compliance**

Dependency : Privacy policy (cf PM Cop)
Check credit page is meeting standards
This milestone is complete when there are no outstanding issues that potential could cause us to loose access to resources (e.g., images we are licensing) and that we are up to date on any legal documents that must appear on the site.
The specific features within the "Compliance" milestone are:
**Credits page
Privacy Policy**

**Know HFLA**

The milestone focuses on providing users with comprehensive information about Hack for LA's overarching value, achievements, and ways to engage with the organization. It aims to educate and engage users by offering a clear understanding of Hack for LA's mission, impact, and opportunities for involvement.
- About us : put CTA to wins page and donate page
- Features:
- Website Homepage
- Sitemap
- Wins
- About
- Donate
“The "Know HFLA" milestone includes several key features that facilitate users' exploration and understanding of the organization:
Data provided to users that wants to know our overreaching value. “

**Security:**

It focuses on identifying, addressing, and mitigating security vulnerabilities and risks associated with the Hack for LA platform.

**Roadmaps:** 

Serve as a guiding document for the website or project teams, helping them prioritize tasks, allocate resources, and track progress towards their objectives. All milestones are made during roadmap sessions.
This is all the large scale planning for the website
- Design
- Research
- Product.

**Onboarding flow**

The primary reason of the issue is to onboard new users, it affects new HfLA volunteers who have not yet joined a project.
The onboarding flow includes several key features/issues that facilitate the onboarding process and familiarize new volunteers with the HfLA community.
The onboarding flow includes several key features that facilitate the onboarding process and familiarize new volunteers with the HfLA community:
- Project page
- Join Us
- Getting started
- 404 page
- Team meeting times
- Community of Practice

**Donation Flow**

Focuses on providing a seamless and user-friendly experience for individuals who wish to make donations to support the organization's initiatives. 
It involves creating a well-defined flow that guides users through the process of making individual donations. Additionally, all the necessary content related to donation, including information about Hack for LA, program areas, and the Community of Practice (CoP), is incorporated to provide donors with comprehensive information and inspire their contributions.
The specific features within the "Program Area Visibility" milestone are:
- Home page (anything that make it clear how to donate, other homepage changes are likely under Homepage Launch)
- About us
- Donate
- Program Area

**Know HFLA**

The milestone focuses on providing users with comprehensive information about Hack for LA's overarching value, achievements, and ways to engage with the organization. It aims to educate and engage users by offering a clear understanding of Hack for LA's mission, impact, and opportunities for involvement.
It includes several key features that facilitate users' exploration and understanding of the organization:
- About us : put CTA to wins page and donate page
- Website Homepage
- Sitemap
- Wins
- About
- Donate

**Data Strategy:**

It focuses on implementing and utilizing effective data management and analytics practices to support the organization's goals and initiatives.
Feature:
- Google analytics

**Homepage launch**

It focuses on enhancing the organization's main website homepage to effectively highlight projects with significant impacts. The primary goal is to engage users and showcase the most impactful initiatives and activities of Hack for LA prominently.
It includes several key features that contribute to the overall enhancement of the homepage:
- Home page
- Impact
- Toolkit
- CoP
- Program area

**Team Work Flow**

Focuses on optimizing the collaboration and efficiency of the HfLA website team. It encompasses various initiatives and processes aimed at streamlining project management, improving communication, and fostering a productive work environment. 
Affects HfLA website team, everything about;
- Good first issues
- Pre-works 
- Process for board maintenance
- Github automation
- Github analytics
- Design system

**Program Area Visibility**

Focuses on enhancing the visibility and accessibility of program areas within the organization's website. The primary features associated with this milestone are the inclusion of program areas and the implementation of a program areas filter on the project page.
The specific features within the "Program Area Visibility" milestone are:
- Program areas
- Project page (program areas filter++)

**HFLA impact**

The "HfLA" milestone at Hack for LA focuses on showcasing the organization's achievements, impact, and success stories. It aims to highlight the positive outcomes and contributions of projects and members within the Hack for LA community. The milestone is centered around providing a platform to celebrate wins, demonstrate the global impact of projects, and recognize the excellent work of members.
Features:
- Wins page
- Global impact (rename impact page)
- (excellent => member feature page)

**Accessibility** 

Aims to remove barriers and create an inclusive user experience for individuals with disabilities. This can involve considerations such as providing alternative text for images, ensuring proper color contrast, implementing keyboard navigation support, screen readers, all texts, providing captions and transcripts for multimedia content, and following web accessibility standards and guidelines, such as the Web Content Accessibility Guidelines (WCAG).

**Technical Debt** 

This is used to describe code that functions correctly but is not optimized for long-term development and maintenance. It may be poorly structured, contain redundant or inefficient code, lack proper documentation, or deviate from coding best practices. The Technical Debt milestone aims to address these issues and improve the quality, readability, and maintainability of the codebase.
The milestone emphasizes refactoring and improving the codebase to enhance maintainability, efficiency, and ease of editing.

**Excellent Level**

Focuses on enhancing features and initiatives that are already functioning well but have room for improvement. This milestone recognizes that while these eatures or initiatives are not considered critical or high-priority, there is still value in refining and optimizing them to achieve a higher level of excellence.
"It works well, but could be improved, because it’s not crucial, there is negligible value.".

**Comment by ExperimentsInHonesty** [comment]
# Wiki page draft
Milestones at Hack for LA serve as crucial stages or goals within a project, enabling progress tracking and guiding task completion. They effectively break down the work, align with objectives, and ensure efficient project management.

To identify and categorize milestones for issues, it is vital to consider the issue's primary objective and desired outcome. It is important to think beyond the surface-level appearance of the issue and focus on what it is ultimately trying to achieve. 

### [Compliance](https://github.com/hackforla/website/milestone/4)
This milestone is complete when there are no outstanding issues that potential could cause us to loose access to resources (e.g., images we are licensing) and that we are up to date on any legal documents that must appear on the site.
The specific pages most used within the "Compliance" milestone are:
- Credits page
- Privacy Policy
- Know HFLA

### [Security](https://github.com/hackforla/website/milestone/18)
Focuses on identifying, addressing, and mitigating security vulnerabilities and risks associated with the Hack for LA platform.

### [Roadmaps](https://github.com/hackforla/website/milestone/19)
Serve as a guiding document for the website or project teams, helping them prioritize tasks, allocate resources, and track progress towards their objectives. All milestones are made during roadmap sessions.
This is all the large scale planning for the website
- Design
- Research
- Product

### [Onboarding flow](https://github.com/hackforla/website/milestone/5)
Contains issues that affects new HfLA volunteers who have not yet joined a project and include several key features/issues that facilitate the onboarding process and familiarize new volunteers with the HfLA community.  Any issues that are concerning onboarding but that only affect people on the website team, use the milestone **Team Workflow**.
The onboarding flow includes several key features that facilitate the onboarding process and familiarize new volunteers with the HfLA community:
- Project pages
- Project's page
- Join Us
- Getting started
- 404 page
- Team meeting times
- Community of Practice

### [Donation Flow](https://github.com/hackforla/website/milestone/3)
Focuses on providing a seamless and user-friendly experience for individuals who wish to make donations to support the organization's initiatives. 
The specific features within the "Donation Flow" milestone are:
- Home page (anything that make it clear how to donate, other homepage changes are likely under Homepage Launch)
- About us (where it has donate information)
- Donate

### [Know Hack for LA](https://github.com/hackforla/website/milestone/6)
Provides users with comprehensive information about Hack for LA's overarching value, achievements, and ways to engage with the organization. It aims to educate and engage users by offering a clear understanding of Hack for LA's mission, impact, and opportunities for involvement (except where it falls into onboarding)
- About us 
- Website Homepage (after relaunch)
- Sitemap
- Wins

### [Data Strategy](https://github.com/hackforla/website/milestone/9)
It focuses on implementing and utilizing effective data management and analytics practices to support the organization's goals and initiatives.
Feature:
- Google analytics

### [Homepage launch](https://github.com/hackforla/website/milestone/7)
We are rebuilding the homepage to highlight all the sections of the website (including hidden new sections)
The pages involved are 
- Home page
- Impact
- Toolkit
- CoP
- Program areas

### [Team Work Flow](https://github.com/hackforla/website/milestone/8)
Focuses on optimizing the collaboration and efficiency of the HfLA website team. It encompasses various initiatives and processes aimed at streamlining project management, improving communication, and fostering a productive work environment. Some the most common labels used are:
- Good first issues
- Pre-works 
- Process for board maintenance
- Github automation
- Design system

### [Program Area Visibility](https://github.com/hackforla/website/milestone/11)
Focuses on enhancing the visibility and accessibility of program areas within the organization's website. 
The specific features within the "Program Area Visibility" milestone are:
- Program areas
- Project page (program areas filter++)

### [Frameworks](https://github.com/hackforla/website/milestone/14)
This milestone might get depreciated.  Have not decided.  Before assigning any issue to this milestone, discuss with the Product Team.
- A plan to do a major feature
  - where we are storing things
  - how we will maintain

### [HFLA impact](https://github.com/hackforla/website/milestone/12)
The "HfLA" milestone at Hack for LA focuses on showcasing the organization's achievements, impact, and success stories. It aims to highlight the positive outcomes and contributions of projects and members within the Hack for LA community. The milestone is centered around providing a platform to celebrate wins, demonstrate the global impact of projects, and recognize the excellent work of members.
Features:
- Wins page
- Global impact (rename impact page)
- (excellent => member feature page)

### [Toolkit relaunch](https://github.com/hackforla/website/milestone/13)
issues that go into the relaunch

### [Ongoing](https://github.com/hackforla/website/milestone/17) 
Issues that never close, because we just reuse them.  Usually they will have instructions on how to do the thing.  We might also use the issue for tracking having done it
- Agendas  (each agenda appears as a comment)
- label checks (each week, the next audit is added to a comment)
- onboarding and offboarding (each person who is onboarded, has a checklist in a comment.  Later, their offboarding also happens in the same issue on a new comment, and then both comments are hidden).

### [Accessibility](https://github.com/hackforla/website/milestone/10)
Aims to remove barriers and create an inclusive user experience for individuals with disabilities. This can involve considerations such as providing alternative text for images, ensuring proper color contrast, implementing keyboard navigation support, screen readers, all texts, providing captions and transcripts for multimedia content, and following web accessibility standards and guidelines, such as the Web Content Accessibility Guidelines (WCAG).

### [Technical Debt](https://github.com/hackforla/website/milestone/16)
Issues for code that functions correctly but is not optimized for long-term development and maintenance. It may be poorly structured, contain redundant or inefficient code, lack proper documentation, or deviate from coding best practices. The Technical Debt milestone aims to address these issues and improve the quality, readability, and maintainability of the codebase.
The milestone emphasizes refactoring and improving the codebase to enhance maintainability, efficiency, and ease of editing.

### [Excellent Level](https://github.com/hackforla/website/milestone/15)
Focuses on enhancing features and initiatives that are already functioning well but have room for improvement. This milestone recognizes that while these features or initiatives are not considered critical or high-priority, there is still value in refining and optimizing them to achieve a higher level of excellence.
"It works well, but could be improved, because it’s not crucial, there might be negligible value."

### [Ignore Test](https://github.com/hackforla/website/milestone/20)
Issues that are using in the process of testing Automations.  They should be excluded from Metrics and Analysis (unless the metrics/analysis are about how many test issues we create)

**Comment by ExperimentsInHonesty** [comment]
@Josiah-O I have edited the description of each milestone in the [comment above](https://github.com/hackforla/website/issues/2316#issuecomment-1546946975).  Please add a link to each of the titles to the specific milestone

**Comment by Josiah-O** [comment]
@ExperimentsInHonesty  Thank you for updating the milestone descriptions, I have added the links.

**Comment by TJameel120** [comment]
- [link to the issue table to display issues with no milestone](https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)

- #4704 (MILESTONE TARGET)

**Comment by ExperimentsInHonesty** [comment]
I am signing off on the milestone descriptions and they are ready to add to wiki

@Josiah-O has some additional guidance to add re how to think about the objective of milestone.

**Comment by Josiah-O** [comment]
@ExperimentsInHonesty I have added the additional guidance on how to think about the objective of milestone.

**Comment by Josiah-O** [comment]
@ExperimentsInHonesty I have added the milestone descriptions link to [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page.
