### ISSUE TITLE
UX Designer pre-work checklist

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2360]
---
name: 'Pre-work Template - Design'
about: 'New Design team members should start with by making this issue for themselves. '
title: 'Pre-work Checklist: Designer: [replace brackets with your name]'
labels: 'role: design', 'good first issue'
assignees: ''

---

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [ ] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [ ] Share your Gmail address with the team lead
- [ ] (once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [ ] Confirm with the team lead, that they have added you to the meeting invites and Github repo
- [ ] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [ ] Attend weekly team meetings: 
   - [ ] UX weekly team meeting, Thursdays 5pm PST
   - [ ] All team meeting (UX, Development, Product), Sunday 10am PST
- [ ] Review the prioritized Backlog to see what Design Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead.
- [ ] Meet with team lead to receive first assignment

### Resources/Instructions
[GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
[GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
[Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
[Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
[Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
[Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by ExperimentsInHonesty** [comment]
Design is finished with this issue.  Its ready for product to turn into a template and add milestone.

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey Please test the template and see if you have any changes https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+role%3A+design&template=pre-work-template---design.md&title=Pre-work+Checklist%3A+Designer%3A+%5Breplace+brackets+with+your+name%5D

**Comment by kristine-eudey** [comment]
@ExperimentsInHonesty Looks great! Only one change please:

Please change the last bullet point to say:
- Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.

**Comment by ExperimentsInHonesty** [comment]
Updates made
