### ISSUE TITLE
Add new project to website: EMS Triage Tracker

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2383]
### Overview
We need to create a project card for the closed project called EMS Triage Tracker so that people can see the projects we have completed.

### Project Details

- Name: EMS Triage Tracker
- Name of future project.md file: ems-triage-tracker.md
- Files you will need to upload to the website repository: ems-triage-tracker.jpg and ems-triage-tracker-hero.jpg
- Where you will store the files:
   - images go in this folder: /assets/images/projects
   - project.md file goes in this folder: _projects

### Action Items
- [x] Find the assets, or create new ones to present the project
   - [x] image for the card
   - [x] image for the hero
   - [x] Overview link: https://github.com/hackforla/product-management/issues/111
   - [x] Video Link from presentation
   - [x] Find team members from roster or slide deck
- [x] Update the template below
- [x] create project.md file using the content provided below
- [x] make sure it is formatted the same was as https://github.com/hackforla/website/wiki/project.md-file-template
- [x] do a pr

### Resources/Instructions
[Google Drive for the EMS Triage Tracker](https://drive.google.com/drive/folders/1lhaif6UrGv1BvVJCfCQkvrkbJs5cerNm)

---
identification: '221542759'
title: EMS Triage Tracker
description: 
image: /assets/images/projects/ems-triage-tracker.jpg
alt text: EMS Triage Tracker Logo
image-hero: /assets/images/projects/ems-triage-tracker-hero.jpg
leadership:
   - name: Bonnie Wolfe
      role: Agile Coach
      links:
        slack: 'https://hackforla.slack.com/team/UE1UG1YFP'
        github: 'https://github.com/experimentsinhonesty'
     picture: https://avatars.githubusercontent.com/experimentsinhonesty
   - name: Dr. Stephen M. Hubbard
      role: System Design Project Advisor
      links:
        slack: 'https://hackforla.slack.com/team/UPXH1Q3RP'
        github: 'https://github.com/lwanderson-triage'
     picture: https://avatars.githubusercontent.com/lwanderson-triage
   - name: Shawn Duenas
      role: Project Manager, Presentation Build and UX Research
      links: 
       slack: 'https://hackforla.slack.com/team/UN4EV6CG3'
        github: 'https://github.com/McRawly'
     picture: https://avatars.githubusercontent.com/McRawly
   - name: Simone Wojtaszek
      role: Lead UX/UI Design and UX Research
      links:
        slack: 'https://hackforla.slack.com/team/UNY9Q55B7'
        github: 'https://github.com/designsimone'
     picture: https://avatars.githubusercontent.com/designsimone
   - name: Nicole Doan
      role: Lead UX/UI Design and UX Research
      links:
        slack: 'https://hackforla.slack.com/team/UBPKHJJVC'
        github: 'https://github.com/nekobox'
     picture: https://avatars.githubusercontent.com/nekobox
   - name: Conor McKiernan
      role: Logo Design and UX Strategy/Research
      links:
        slack: 'https://hackforla.slack.com/team/UNHNCALSE'
        github: 'https://github.com/redmckiernan'
     picture: https://avatars.githubusercontent.com/redmckiernan
   - name: Selena Jiang
      role: UI Design, Life Saving Measures screen
      links:
        slack: 'https://hackforla.slack.com/team/UMYN9DVSB'
        github: 'https://github.com/ysjiang18'
     picture: https://avatars.githubusercontent.com/ysjiang18
   - name: Richa Srivastava
      role: UX Research & 
      links:
        slack: 'https://hackforla.slack.com/team/UJ8M64E5V'
   - name: Kelvin Nguyen
      role: UI Design, Individual Assessment screen
      links:
        slack: 'https://hackforla.slack.com/team/UPNR0KG00'
links: 
  - name: Github
    url: 'https://github.com/hackforla/ems-triage-tracker'
  - name: Slack
    url: 'https://hackforla.slack.com/archives/CQ5J1DA72'
  - name: Clickable Prototype
    url: 'https://drive.google.com/file/d/1WWxADa3aBKtTk47Fx1vzoMSn0-yWKp3X/view?usp=sharing'
  - name: Overview
    url: https://github.com/hackforla/product-management/blob/master/project-one-sheets/EMS-Triage-Tracker-One-Sheet.pdf
location: 
  - Downtown LA
partner: General Assembly (Downtown Campus), Lisa W. Anderson
tools: Figma, video production
program area:
 - Civic Tech Infrastructure
status: Completed
visible: true
completed-contact: team@hackforla.org
---

**Comment by ExperimentsInHonesty** [comment]
![emstriagetrack](https://user-images.githubusercontent.com/37763229/139644230-b47c572b-b51d-455c-b628-3fdcf1722587.png)

alt text: EMS Triage Tracker Logo

**Comment by ExperimentsInHonesty** [comment]
Hero 
![ems-triage-tracker-hero](https://user-images.githubusercontent.com/37763229/139642581-bc3a81d6-5569-430c-b280-6dc6e3f3bb76.png)

**Comment by JimGeist** [comment]
1. ems-triage-tracker.md file created and updated as required.
2. 'The EMS Triage Tracker app provides the ability to both primary and secondary triage during Mass Casualty Incidents, as well as provide incident command with tools to view and direct the operaiton of all personnel involved.' from the overview pdf was added as a description for the card.
2. Hero and logo pngs were copied to assets/images/projects as ems-triage-tracker-hero.png and ems-triage-tracker.png respectively. Hero (1500 x 700) and logo (600x400) have the correct dimensions (w x h).
3. 'EMS Triage Tracker dashboard with breakdown of casualty numbers and a satellite view of the street grid with blue casualty location markers.' was added as alt text for hero image.
4. EMS-Triage-Tracker-One-Sheet.pdf was copied from GitHub to assets/pdfs. The Overview link uses the assets (HackForLa.org) hosted pdf instead of the GitHub-hosted pdf. This aligns to Issue 2237 / How Overview links should open.
5. A no-photo.png was created and placed in assets/images/misc. Richa Srivastava and Kelvin Nguyen did not have images, but no image for Richa resulted in a 'card' that was half the height of other Project Team cards. The no-photo.png will give us the expected layout without requiring updating the project template.
6. The GitHub repo for EMS Triage Tracker looks like a placeholder repo. The repo also has no contributors and that is why the 'Looks like this project has not connected a GitHub repository message appears. The id for the repo at the top of the ems-triage-tracker.md file, 221542759, was verified via https://api.github.com/repos/hackforla/ems-triage-tracker. The only difference I found with this repo versus other repos is no contributors.
7. Wrapping up and hopefully creating a pull request for this issue tonight / Wed. Dec. 1, 2021.

**Comment by JimGeist** [comment]
Some changes were requested -- there were comments in the ems-triage-tracker.md from the template that required removal, and a second change was required because "program area:" had to change to "program-area:".
Changes were pushed and issue is awaiting final review and merge.
