### ISSUE TITLE
Identify all mispelled words on site and make issues to fix

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2401]
### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items
- [x] Identify which VS Code plugin to use for future development
- [x] Make issues from the notes from design
- [x] add all notes from list below in resources, by page  - to a spreadsheet (see if design has already made one) #2597
- [x] Audit all the pages to find misspellings not identified by design and add to spreadsheet
- [x] make issues

### Resources/Instructions
[Spreadsheet from design team with all the misspellings they found](https://docs.google.com/spreadsheets/d/1qDD7n9XbogIJgDh6mcgdEJAH1x3FMoPnGYNt3pKhhUk/edit?usp=sharing)
[VS Code Plugins for spelling](https://marketplace.visualstudio.com/search?term=spell&target=VSCode&category=All%20categories&sortBy=Relevance)
[Web Based Chrome Extension checker](https://chrome.google.com/webstore/detail/spell-check/ofbiibdnnhllfldbglbhmiojndiepejl?u_producttype=chrome-extension-759435&u_country=us&funnel=esign&gclid=CjwKCAjwzt6LBhBeEiwAbPGOgWBYIwbWhghZ-uWgoMQS16y7t8pHC7kKXM0RQjeg27To0YlYVBisdRoCueMQAvD_BwE)
[Web based external checker](https://www.icwebdesign.co.uk/how-to-spell-check-a-whole-website) - more sensitive than the chrome extension however will only check pages that are linked to main page (not about page, etc.)
[Figma spell check plug in SPELL](https://www.figma.com/community/plugin/754026612866636376/SPELLL---Spell-Checking-for-Figma-%26-FigJam)
[Figma spell check plug in Spellchecker](https://www.figma.com/community/plugin/738839069237725273/Spellchecker)

#### [https://www.hackforla.org/program-areas](https://www.hackforla.org/program-areas)
- policymaking needs to be changed to policy making
- susainability needs to be changed to sustainability

#### [https://www.hackforla.org/join](https://www.hackforla.org/join)
- community is misspelled commmunity
- non-profit should be nonprofit

#### [https://www.hackforla.org/donate](https://www.hackforla.org/donate)
- community is misspelled commmunity

#### [https://www.hackforla.org/communities-of-practice](https://www.hackforla.org/communities-of-practice)
- none

#### [https://www.hackforla.org/project-meetings](https://www.hackforla.org/project-meetings)
- none

#### [https://www.hackforla.org/about](https://www.hackforla.org/about)
- definitley needs to be definitely
- langugage needs to be language

#### [https://www.hackforla.org/projects](https://www.hackforla.org/projects)
-  scaleable needs to be corrected to scalable

#### [https://www.hackforla.org/credits/](https://www.hackforla.org/credits/)
- none

### [https://hackforla.org/citizen-engagement](https://hackforla.org/citizen-engagement)
- This page is not resolving yet.  Check it when it is

**Comment by isletprogramiz** [comment]
Can i work on this issue @ExperimentsInHonesty

**Comment by ExperimentsInHonesty** [comment]
@isletprogramiz I don't see that you have joined the hackforla website team.  Have you been to our onboarding?  Or how did you find us?  We welcome new contributors, I want to make sure you have access to our tools.

**Comment by ExperimentsInHonesty** [comment]
Bumping this back to your inbox @isletprogramiz I don't see that you have joined the hackforla website team. Have you been to our onboarding? Or how did you find us? We welcome new contributors, I want to make sure you have access to our tools.

**Comment by isletprogramiz** [comment]
i am new to open source so can you guide me what i have to do and how at initial

**Comment by ExperimentsInHonesty** [comment]
@isletprogramiz You are welcome to work on our projects, in order to join the organization, please see this webpage https://www.hackforla.org/getting-started, then once you have attended one of our onboarding sessions we can help you work on this issue.  Remind us when you show up, that you came to work on this issue.

It is free to join our organization.

**Comment by isletprogramiz** [comment]
Ya 
I am participating  in Jan 5 meet
Hope this will help me to understand how to process further
Thanku for replying:)

**Comment by ExperimentsInHonesty** [comment]
This is being held in the new issue approval column until it has a link for the spreadsheet that design is working on.

**Comment by ExperimentsInHonesty** [comment]
@isletprogramiz I have not seen you join the website team yet.  Did you come to our hackforla onboarding yet?

@isletprogramiz 
https://github.com/hackforla/website/issues/2401#issuecomment-1002910759
> Ya
> I am participating in Jan 5 meet
> Hope this will help me to understand how to process further
> Thanku for replying:)

**Comment by answebdev** [comment]
Availability: 4 hours
ETA: 3/3/2022 (end of day)

**Comment by answebdev** [comment]
@JessicaLucindaCheng @SAUMILDHANKAR As per the Action Items for this issue, I created separate issues for each of the listed pages so that the spelling mistakes can be fixed. The following are the pages referred to in this issue, along with the issue(s) I created for each of them:

**List of pages with issues:**

program-areas: Issue #2909 and Issue #2910 
join: Issue #2913 and Issue #2914 
donate: #2907 
communities-of-practice: No spelling mistakes found
project-meetings: No spelling mistakes found
about: Issue #2911 (as for the misspelling "langugage", I did not see the misspelling on the live site, so it looks as though it has already been corrected)
projects: Issue #2912 
credits: No spelling mistakes found
citizen-engagement: Issue #2916 

Also, I have added the misspellings to the [spreadsheet](https://docs.google.com/spreadsheets/d/1qDD7n9XbogIJgDh6mcgdEJAH1x3FMoPnGYNt3pKhhUk/edit#gid=0) if they were not already there, including those not identified by design (which in this case, was only "web app", from Issue #2916) after having audited all the listed pages.

Finally, I do not need to submit a PR for this, right, since my issue involved auditing, issue creation, and adding to a spreadsheet?

Thank you.

**Comment by JessicaLucindaCheng** [comment]
- Availability: 3 hours
- Review ETA: ~Either Fri, Mar 4, 2022 or Sat, Mar 5, 2022~ Sun, Mar 6, 2022

**Comment by JessicaLucindaCheng** [comment]
@answebdev Thanks for writing the issues to fix the misspelled words!
- [x] Saumil and I edited issue #2907, and you can take a look at that issue as an example. However, for the rest of the issues you wrote, please do the following: 
  - [x] Please make the action item for changing the misspelled words into one action item because having it as two Action Items for one change may be confusing.
  - [x] Also, add an action item to "Make sure the changes look fine in your local environment. (For both desktop and mobile views)"
  - [x] Make sure to include a permalink to the line of code in your issue under the Resources section because the line number may change if there are changes to the code between when you wrote the issue and when a new developer works on the issue. Thus, a permalink can help the new developer see the line of code in the context of the rest of the code when they click on the permalink and help make it easier to find the line of code if the line number changes. 
- [x] Please make an issue for the [Site Map page's ](https://www.hackforla.org/sitemap/) misspelled word, which is supposed to be corrected to "accommodate". See details in the spreadsheet.
- [x] I found this typo on the Citizen Engagement page:
  - [x] Add the typo to the spreadsheet
  - [x] Make an issue for it
<img width="960" alt="throughout-out-typo" src="https://user-images.githubusercontent.com/31293603/156983200-92f2b77a-89b8-4d27-b7cc-758f089c71ea.png">

- [x] When you have made all the changes and are ready for me to review your issue again, please @ mention me in a comment below.

**Comment by answebdev** [comment]
@JessicaLucindaCheng Thank you for reviewing my issue and for the feedback. I have made all the changes you listed above and am ready for you to review my issue again.

**Comment by JessicaLucindaCheng** [comment]
- Availability: 3 hours
- Re-review: ~Thursday, March 10, 2022~ Friday, March 11, 2022

**Comment by JessicaLucindaCheng** [comment]
@answebdev Good job on writing issues to fix the misspellings. Feel free to pick up your next issue (either Medium or a Large size).

**Comment by ExperimentsInHonesty** [comment]
@answebdev can you tell us what VScode plugin you used?

**Comment by answebdev** [comment]
@ExperimentsInHonesty Are you talking about a plugin for finding spelling mistakes? If so, I do not use a plug-in for that. I used a Chrome Extension called [Spell Check](https://chrome.google.com/webstore/detail/spell-check/ofbiibdnnhllfldbglbhmiojndiepejl?u_producttype=chrome-extension-759435&u_country=us&funnel=esign&gclid=CjwKCAjwzt6LBhBeEiwAbPGOgWBYIwbWhghZ-uWgoMQS16y7t8pHC7kKXM0RQjeg27To0YlYVBisdRoCueMQAvD_BwE), which was mentioned up above in the "Resources/Instructions" section.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng @answebdev It was my fault for not being clear enough, but everyone who has touched this issue seems to have misunderstood the mission.  So let's talk about what we should do next.

### The mission
The mission is to have a VS code plugin, that has a matching version we can put as a check when PRs are made in github (like code climate for spelling) .. and when I say matching, it's because it would be problematic if someone caught a spelling error on their local that the github check disagreed with.  So using the same vendor for both, would solve that. 

Then we could have the instructions in the contributing to have people download the vscode plugin and use it before they commit.

### Next steps
We still need to do this.  So do you want it to be part of this issue, or do we need to make a new one.

<details>
<summary>spelling errors to use to check that the plugin is effective</summary>

- In 1.5.a Docker installation troubleshooting of CONTRIBUTING.md, fix spelling of "te" to "the" in "the following wiki page is a guide for solving te issue:"
- line 41 "your" to "you're" Mobile_responsiveness.yml
- line 33 `each changes` to `each change` in Mobile_responsiveness.yml
- line 46 `figma` should be capitalized in Mobile_responsiveness.yml --> Not sure if this will be caught since it isn't a dictionary word
- "it's" should be "its" on homepage in "Hack for LA is a project of Code for America and is it's official Los Angeles chapter."
- "Non-profit" button and description "I am a non-profit organization." should be "nonprofit" on homepage
- "responsivenes" should be "responsiveness" in How to use Figma effectively on Open Source Volunteer Teams card on https://www.hackforla.org/toolkit/
- "elipsis" should be "ellipsis" in "Click the vertical elipsis located at the top right of the survey form" on https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide
- "elipsis" should be "ellipsis" in "VERTICAL ELIPSIS" on https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide
- "elipsis" should be "ellipsis" in "(2) Hovering over the new page added within the dropdown menu, you will see a vertical elipsis."  on https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide
- #2909 
</details>

**Comment by JessicaLucindaCheng** [comment]
Once we identify the spell checker to be used, please update and edit issue #2909 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2909 to the New Issue Approval column and remove the Dependency label

**Comment by ExperimentsInHonesty** [comment]
@answebdev can you respond to my question in this comment https://github.com/hackforla/website/issues/2401#issuecomment-1146721700

> ...do you want it to be part of this issue, or do we need to make a new one.

**Comment by answebdev** [comment]
@ExperimentsInHonesty Sorry, I think I didn't think the question was directed at me. My mistake. But I think it best to make a new one.

**Comment by ExperimentsInHonesty** [comment]
Dev lead to make a new issue from this comment https://github.com/hackforla/website/issues/2401#issuecomment-1146721700


Also, add the following as the last action item in the issue you write:
```
Once we identify the spell checker to be used, please update and edit issue #2909 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2909 to the New Issue Approval column and remove the Dependency label
```

**Comment by ExperimentsInHonesty** [comment]
- This is 100% resolved by the creation of https://github.com/hackforla/website/issues/3546
