### ISSUE TITLE
Pre-work Checklist: Developer: Jim Geist

### ISSUE THREAD

**Issue by JimGeist** [hackforla/website#2468]
### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site-pr and #hfla-site Slack channels
- [x] Share your Gmail address with the team lead
- [x] (once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Confirm with the team lead that they have added you to the meeting invites and GitHub repo
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once all tasks are completed, close this issue

### Resources/Instructions
[Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
[GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
[GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
[Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
[Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
[Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
[Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
[How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by ExperimentsInHonesty** [comment]
@JimGeist anytime you see anything in brackets on a template, it usually means that you replace the value including the brackets.

**Comment by JimGeist** [comment]
Completed Docker setup on my desktop computer. The laptop is next but a whole bunch of other things are needed for that! 
Forked, cloned, and docked the website locally to get familiar with the layout and also looked at the live website at hackforla.org.
Running through a docker tutorial.

**Comment by HackforLABot** [comment]
## Activity Log: JimGeist
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- JimGeist opened: https://github.com/hackforla/website/issues/2468 at 11/09/2021, 07:57 PM PST
- JimGeist assigned: https://github.com/hackforla/website/issues/2468 at 11/09/2021, 07:57 PM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2468#issuecomment-968109086 at 11/13/2021, 09:58 AM PST
- JimGeist assigned: https://github.com/hackforla/website/issues/2342#issuecomment-953524913 at 11/14/2021, 07:17 PM PST
- JimGeist opened: https://github.com/hackforla/website/pull/2491 at 11/15/2021, 07:45 PM PST
- JimGeist commented on: https://github.com/hackforla/website/pull/2491#issuecomment-969831875 at 11/15/2021, 07:50 PM PST
- JimGeist issue closed by PR 2491: https://github.com/hackforla/website/issues/2342#event-5626988939 at 11/16/2021, 10:33 AM PST
- JimGeist PR was merged: https://github.com/hackforla/website/pull/2491#event-5626988962 at 11/16/2021, 10:33 AM PST
- JimGeist closed as completed: https://github.com/hackforla/website/issues/2468#event-5628673101 at 11/16/2021, 05:03 PM PST
- JimGeist assigned: https://github.com/hackforla/website/issues/2237 at 11/16/2021, 08:16 PM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2237#issuecomment-974576026 at 11/19/2021, 06:12 PM PST
- JimGeist opened: https://github.com/hackforla/website/pull/2507 at 11/21/2021, 03:32 PM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2237#issuecomment-974925709 at 11/21/2021, 04:05 PM PST
- JimGeist issue closed by PR 2507: https://github.com/hackforla/website/issues/2237#event-5656470331 at 11/22/2021, 12:17 PM PST
- JimGeist PR was merged: https://github.com/hackforla/website/pull/2507#event-5656470350 at 11/22/2021, 12:17 PM PST
- JimGeist assigned: https://github.com/hackforla/website/issues/2383#issuecomment-956029832 at 11/29/2021, 08:30 PM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2383#issuecomment-984260240 at 12/01/2021, 07:28 PM PST
- JimGeist opened: https://github.com/hackforla/website/pull/2535 at 12/01/2021, 09:19 PM PST
- JimGeist submitted review: https://github.com/hackforla/website/pull/2538#pullrequestreview-824633883 at 12/06/2021, 04:13 PM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2383#issuecomment-987541249 at 12/06/2021, 07:44 PM PST
- JimGeist issue closed by PR 2535: https://github.com/hackforla/website/issues/2383#event-5731117980 at 12/07/2021, 06:38 PM PST
- JimGeist PR was merged: https://github.com/hackforla/website/pull/2535#event-5731117988 at 12/07/2021, 06:38 PM PST
- JimGeist assigned: https://github.com/hackforla/website/issues/2408#issuecomment-955088300 at 12/11/2021, 08:30 PM PST
- JimGeist submitted review: https://github.com/hackforla/website/pull/2574#pullrequestreview-830971085 at 12/13/2021, 07:07 PM PST
- JimGeist submitted review: https://github.com/hackforla/website/pull/2566#pullrequestreview-830990411 at 12/13/2021, 07:54 PM PST
- JimGeist submitted review: https://github.com/hackforla/website/pull/2566#pullrequestreview-832160917 at 12/14/2021, 03:50 PM PST
- JimGeist opened: https://github.com/hackforla/website/pull/2594 at 12/16/2021, 05:27 PM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2408#issuecomment-996442602 at 12/16/2021, 09:10 PM PST
- JimGeist submitted review: https://github.com/hackforla/website/pull/2588#pullrequestreview-835737901 at 12/17/2021, 07:08 PM PST
- JimGeist commented on: https://github.com/hackforla/website/pull/2603#issuecomment-997989663 at 12/20/2021, 06:48 AM PST
- JimGeist assigned: https://github.com/hackforla/website/issues/2554#issuecomment-992033003 at 12/20/2021, 06:58 AM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2554#issuecomment-998000226 at 12/20/2021, 07:00 AM PST
- JimGeist unassigned: https://github.com/hackforla/website/issues/2554#issuecomment-998155986 at 12/20/2021, 06:17 PM PST
- JimGeist opened: https://github.com/hackforla/website/issues/2610 at 12/20/2021, 06:55 PM PST
- JimGeist PR was merged: https://github.com/hackforla/website/pull/2594#event-5798032848 at 12/21/2021, 02:29 AM PST
- JimGeist assigned: https://github.com/hackforla/website/issues/2456#issuecomment-962257808 at 12/21/2021, 08:17 AM PST
- JimGeist submitted review: https://github.com/hackforla/website/pull/2603#pullrequestreview-838977755 at 12/22/2021, 07:19 PM PST
- JimGeist submitted review: https://github.com/hackforla/website/pull/2603#pullrequestreview-838978640 at 12/22/2021, 07:22 PM PST
- JimGeist submitted review: https://github.com/hackforla/website/pull/2603#pullrequestreview-838996508 at 12/22/2021, 08:23 PM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2456#issuecomment-1001225928 at 12/26/2021, 10:36 AM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2408#issuecomment-1002822575 at 12/29/2021, 04:19 PM PST
- JimGeist opened: https://github.com/hackforla/website/pull/2644 at 12/29/2021, 04:58 PM PST
- JimGeist commented on: https://github.com/hackforla/website/issues/2456#issuecomment-1002846341 at 12/29/2021, 06:29 PM PST
- JimGeist opened: https://github.com/hackforla/website/pull/2647 at 12/30/2021, 05:49 PM PST
- JimGeist issue closed by PR 2647: https://github.com/hackforla/website/issues/2456#event-5857669539 at 01/07/2022, 04:43 AM PST
- JimGeist PR was merged: https://github.com/hackforla/website/pull/2647#event-5857669548 at 01/07/2022, 04:43 AM PST
- JimGeist commented on: https://github.com/hackforla/website/pull/2644#issuecomment-1008341780 at 01/09/2022, 09:35 AM PST
- JimGeist unassigned: https://github.com/hackforla/website/issues/2408#event-5900708128 at 01/16/2022, 11:28 AM PST
- JimGeist PR was closed: https://github.com/hackforla/website/pull/2644#event-5938638877 at 01/23/2022, 11:32 AM PST
