### ISSUE TITLE
Pre-work Checklist: Developer: Jovanni Morales

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2496]
### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once all tasks are completed, close this issue

### Resources/Instructions
[Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
[GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
[GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
[Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
[Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
[Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
[Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
[How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by ExperimentsInHonesty** [comment]
@jnmrles One last item that was not on the original instructions but has since been added

- [ ] Once you take a issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [ ] Once all tasks are completed, close this issue

**Comment by JessicaLucindaCheng** [comment]
@jnmrles Did you have any questions or need help with this pre-work checklist? Also, are you still interested in working on this issue? Please let me know by Friday, February 11, 2022. If I do not hear back from you by then, I will close this issue and I will unassign you from other open issues you have.

**Comment by JessicaLucindaCheng** [comment]
I sent a Slack message to Jovanni.

**Comment by JessicaLucindaCheng** [comment]
@jnmrles I am closing this pre-work checklist since I have not heard back from you. You can re-open this issue when you are ready to work on it again.

**Comment by HackforLABot** [comment]
## Activity Log: jnmrles
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- jnmrles assigned: https://github.com/hackforla/website/issues/2496 at 11/16/2021, 07:47 PM PST
- jnmrles closed as completed: https://github.com/hackforla/website/issues/2496#event-5715981735 at 12/04/2021, 11:30 AM PST
- jnmrles assigned: https://github.com/hackforla/website/issues/2425#issuecomment-964405965 at 12/04/2021, 11:32 AM PST
- jnmrles opened: https://github.com/hackforla/website/pull/2543 at 12/04/2021, 12:13 PM PST
- jnmrles issue closed by PR 2543: https://github.com/hackforla/website/issues/2425#event-5716188651 at 12/04/2021, 03:45 PM PST
- jnmrles PR was merged: https://github.com/hackforla/website/pull/2543#event-5716188661 at 12/04/2021, 03:45 PM PST
- jnmrles assigned: https://github.com/hackforla/website/issues/2382 at 12/10/2021, 08:44 AM PST
- jnmrles commented on: https://github.com/hackforla/website/issues/2382#issuecomment-1002353855 at 12/28/2021, 05:33 PM PST
- jnmrles assigned: https://github.com/hackforla/website/issues/2271#issuecomment-926945747 at 12/28/2021, 06:07 PM PST
- jnmrles opened: https://github.com/hackforla/website/pull/2643 at 12/28/2021, 07:20 PM PST
- jnmrles issue closed as completed: https://github.com/hackforla/website/issues/2382#event-5826560711 at 12/29/2021, 06:50 PM PST
- jnmrles issue closed as completed: https://github.com/hackforla/website/issues/2496#event-6057963103 at 02/12/2022, 11:26 AM PST
- jnmrles unassigned: https://github.com/hackforla/website/issues/2271#issuecomment-926945747 at 02/15/2022, 06:32 PM PST
- jnmrles PR was closed: https://github.com/hackforla/website/pull/2643#event-6079593203 at 02/15/2022, 06:34 PM PST
- jnmrles assigned: https://github.com/hackforla/website/issues/2726#issuecomment-1024995606 at 02/23/2022, 06:51 PM PST
- jnmrles commented on: https://github.com/hackforla/website/issues/2726#issuecomment-1049445410 at 02/23/2022, 06:58 PM PST
- jnmrles opened: https://github.com/hackforla/website/pull/2881 at 02/23/2022, 07:18 PM PST
- jnmrles assigned: https://github.com/hackforla/website/issues/2715#issuecomment-1030472118 at 02/23/2022, 11:00 PM PST
- jnmrles commented on: https://github.com/hackforla/website/issues/2715#issuecomment-1049558839 at 02/23/2022, 11:12 PM PST
- jnmrles unassigned: https://github.com/hackforla/website/issues/2715#issuecomment-1050317245 at 02/24/2022, 02:16 PM PST
- jnmrles issue closed by PR 2881: https://github.com/hackforla/website/issues/2726#event-6142369959 at 02/25/2022, 03:05 PM PST
- jnmrles PR was merged: https://github.com/hackforla/website/pull/2881#event-6142369968 at 02/25/2022, 03:05 PM PST
- jnmrles assigned: https://github.com/hackforla/website/issues/2715#issuecomment-1050317245 at 02/25/2022, 10:52 PM PST
- jnmrles opened: https://github.com/hackforla/website/pull/3001 at 03/22/2022, 02:57 PM PDT
- jnmrles issue closed by PR 3001: https://github.com/hackforla/website/issues/2715#event-6304640303 at 03/24/2022, 09:45 PM PDT
- jnmrles PR was merged: https://github.com/hackforla/website/pull/3001#event-6304640309 at 03/24/2022, 09:45 PM PDT
- jnmrles assigned: https://github.com/hackforla/website/issues/2502#issuecomment-1094085497 at 04/25/2022, 09:25 PM PDT
- jnmrles unassigned: https://github.com/hackforla/website/issues/2502#issuecomment-1173148805 at 07/03/2022, 11:23 AM PDT
