### ISSUE TITLE
Pre-work Checklist: Researcher: Jackie Riley

### ISSUE THREAD

**Issue by JackieRiley1** [hackforla/website#2500]
### Overview
As a new researcher on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [X] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [X] Share your Gmail address with the research team lead
- [x]  (once added to the drive) Add yourself to the team roster.
- [x]  Confirm with the research team lead that they have added you to the meeting invites and Github repo
- [x]  Confirm that the research team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings:
   - UX weekly team meeting, Thursdays 5 pm PST
   - All team meetings (UX, Development, Product), Sunday 10 am PST
   - Research team meetings, Mondays, 11:30 am PST
- [x] Review the  [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) to see what Research Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Meet with team lead to receive first assignment
- [x] Once you accept an assignment (issue), please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
provide update
1. Progress
2. Blockers
3. Availability
4. ETA
```

### Resources/Instructions
[Project Board filtered to show role: user research](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22)
[Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
[Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149)
[Googledrive-UI/UX](https://drive.google.com/drive/folders/1Jq24FlOJTEmRD09M5xOgpWuHcKswH5Dk)
[Googledrive-HackforLA website](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT)
[UX Research Presentations](https://drive.google.com/drive/folders/1yV9YRrjVKmVLU_xSM_BjtdIaNITRhP5j)
[Weekly Meeting Agendas](https://github.com/hackforla/website/issues/2106)

**Comment by JackieRiley1** [comment]
Availability for this week: Tues, Wed, Thurs
My estimated ETA for completing this issue: 2 hours

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 Please see this issue for instructions about how to do updates every week on your issue.  Once you have done that two weeks in a row then you can close this issue.  Remember to provide an overall ETA for completion and on the next issue you work on, do that when you first self assign.

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 I do not see that you are putting updates, as prescribed above, in the issue you are working on.  Please re-read the guidance in this issue for how to communicate on the team effectively.

**Comment by phuonguvan** [comment]
@JackieRiley1 Hey! This is the design team lead and I was wondering if you are still working on this project. Bonnie told me to update you guys so let me know as soon as possible!

**Comment by JackieRiley1** [comment]
Hello,
What project are you referring to?
Jackie

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 sorry for the confusion.  Phu was checking in on your because we have not gotten updates from you on this issue... but this issue should have been closed.  Sorry for the mixup.

**Comment by HackforLABot** [comment]
## Activity Log: JackieRiley1
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- JackieRiley1 opened: https://github.com/hackforla/website/issues/2500 at 11/17/2021, 02:21 PM PST
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/2500 at 11/17/2021, 02:22 PM PST
- JackieRiley1 opened: https://github.com/hackforla/website/issues/2536 at 12/02/2021, 09:30 AM PST
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/2536 at 12/02/2021, 09:30 AM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2500#issuecomment-989195108 at 12/08/2021, 01:05 PM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2536#issuecomment-991936009 at 12/12/2021, 09:16 AM PST
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/191#issuecomment-636588497 at 12/15/2021, 02:55 PM PST
- JackieRiley1 unassigned: https://github.com/hackforla/website/issues/191#issuecomment-636588497 at 12/16/2021, 07:15 AM PST
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/191#issuecomment-636588497 at 12/16/2021, 07:17 AM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/191#issuecomment-995913648 at 12/16/2021, 07:19 AM PST
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/1696#issuecomment-917681123 at 12/28/2021, 07:26 PM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/191#issuecomment-1003740128 at 01/02/2022, 08:19 AM PST
- JackieRiley1 unassigned: https://github.com/hackforla/website/issues/191#issuecomment-1003740128 at 01/06/2022, 01:32 PM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/1696#issuecomment-1006951211 at 01/06/2022, 01:34 PM PST
- JackieRiley1 unassigned: https://github.com/hackforla/website/issues/2536#issuecomment-991936009 at 01/06/2022, 01:38 PM PST
- JackieRiley1 unassigned: https://github.com/hackforla/website/issues/2500#issuecomment-989195108 at 01/06/2022, 01:38 PM PST
- JackieRiley1 opened: https://github.com/hackforla/website/issues/2663 at 01/06/2022, 01:46 PM PST
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/2663 at 01/06/2022, 01:46 PM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/1696#issuecomment-1013931512 at 01/16/2022, 10:53 AM PST
- JackieRiley1 unassigned: https://github.com/hackforla/website/issues/2663#issuecomment-1006958269 at 01/16/2022, 12:08 PM PST
- JackieRiley1 issue closed as completed: https://github.com/hackforla/website/issues/2500#event-5927927110 at 01/20/2022, 12:42 PM PST
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/2500#event-5927927110 at 01/20/2022, 01:14 PM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2663#issuecomment-1028328734 at 02/02/2022, 12:27 PM PST
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/2733#issuecomment-1028385806 at 02/02/2022, 01:46 PM PST
- JackieRiley1 issue closed as completed: https://github.com/hackforla/website/issues/2500#event-5998902139 at 02/02/2022, 02:00 PM PST
- JackieRiley1 unassigned: https://github.com/hackforla/website/issues/1696#issuecomment-1030898446 at 02/09/2022, 12:25 PM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2733#issuecomment-1047168730 at 02/21/2022, 11:20 AM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2733#issuecomment-1058338009 at 03/03/2022, 10:09 AM PST
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2663#issuecomment-1069403307 at 03/16/2022, 11:05 AM PDT
- JackieRiley1 assigned: https://github.com/hackforla/website/issues/2663#issuecomment-1069403307 at 03/16/2022, 11:35 AM PDT
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2663#issuecomment-1069441691 at 03/16/2022, 11:36 AM PDT
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2663#issuecomment-1074052523 at 03/21/2022, 08:36 AM PDT
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2500#issuecomment-1077778030 at 03/24/2022, 08:51 AM PDT
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2663#issuecomment-1079937306 at 03/27/2022, 06:57 AM PDT
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2663#issuecomment-1098432423 at 04/13/2022, 01:01 PM PDT
- JackieRiley1 commented on: https://github.com/hackforla/website/issues/2663#issuecomment-1109016687 at 04/25/2022, 01:37 PM PDT
- JackieRiley1 issue closed as completed: https://github.com/hackforla/website/issues/2733#event-6529807094 at 05/01/2022, 10:08 AM PDT
- JackieRiley1 unassigned: https://github.com/hackforla/website/issues/2663#issuecomment-1119330582 at 05/11/2022, 02:42 PM PDT
