### ISSUE TITLE
Pre-work Checklist: Developer: Sydney Walcoff

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/website#2519]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [ ] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [x] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by sydneywalcoff** [comment]
Update
1. Progress - Submitted PR 
2. Blockers - waiting for review
3. Availability - full
4. ETA - waiting for PR review

**Comment by HackforLABot** [comment]
## Activity Log: sydneywalcoff
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- sydneywalcoff opened: https://github.com/hackforla/website/issues/2519 at 11/29/2021, 07:40 PM PST
- sydneywalcoff assigned: https://github.com/hackforla/website/issues/2519 at 11/29/2021, 07:40 PM PST
- sydneywalcoff assigned: https://github.com/hackforla/website/issues/2443#issuecomment-960383604 at 12/01/2021, 10:52 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/issues/2443#issuecomment-983962881 at 12/01/2021, 10:59 AM PST
- sydneywalcoff opened: https://github.com/hackforla/website/pull/2526 at 12/01/2021, 11:23 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/issues/2519#issuecomment-985743643 at 12/03/2021, 10:39 AM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2532#pullrequestreview-823019908 at 12/03/2021, 11:38 AM PST
- sydneywalcoff issue closed by PR 2526: https://github.com/hackforla/website/issues/2443#event-5716173629 at 12/04/2021, 03:40 PM PST
- sydneywalcoff PR was merged: https://github.com/hackforla/website/pull/2526#event-5716173639 at 12/04/2021, 03:40 PM PST
- sydneywalcoff closed as completed: https://github.com/hackforla/website/issues/2519#event-5736957363 at 12/08/2021, 02:22 PM PST
- sydneywalcoff assigned: https://github.com/hackforla/website/issues/2236 at 12/08/2021, 02:28 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/issues/2236#issuecomment-989280151 at 12/08/2021, 02:30 PM PST
- sydneywalcoff opened: https://github.com/hackforla/website/pull/2564 at 12/08/2021, 03:56 PM PST
- sydneywalcoff issue closed by PR 2564: https://github.com/hackforla/website/issues/2236#event-5744200743 at 12/09/2021, 02:54 PM PST
- sydneywalcoff PR was merged: https://github.com/hackforla/website/pull/2564#event-5744200757 at 12/09/2021, 02:54 PM PST
- sydneywalcoff assigned: https://github.com/hackforla/website/issues/2396#issuecomment-956040984 at 12/09/2021, 03:07 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/issues/2396#issuecomment-990388395 at 12/09/2021, 03:11 PM PST
- sydneywalcoff opened: https://github.com/hackforla/website/pull/2574 at 12/10/2021, 10:59 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2584#issuecomment-992803697 at 12/13/2021, 11:34 AM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2584#pullrequestreview-830770824 at 12/13/2021, 01:23 PM PST
- sydneywalcoff assigned: https://github.com/hackforla/website/issues/2552#issuecomment-987538036 at 12/13/2021, 04:07 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/issues/2552#issuecomment-993025808 at 12/13/2021, 04:10 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2584#issuecomment-993129647 at 12/13/2021, 07:46 PM PST
- sydneywalcoff issue closed by PR 2574: https://github.com/hackforla/website/issues/2396#event-5768315047 at 12/14/2021, 06:12 PM PST
- sydneywalcoff PR was merged: https://github.com/hackforla/website/pull/2574#event-5768315053 at 12/14/2021, 06:12 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2584#issuecomment-995395789 at 12/15/2021, 07:02 PM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2584#pullrequestreview-834423458 at 12/16/2021, 09:51 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/issues/2552#issuecomment-996045218 at 12/16/2021, 09:52 AM PST
- sydneywalcoff opened: https://github.com/hackforla/website/pull/2593 at 12/16/2021, 11:14 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2593#issuecomment-996104386 at 12/16/2021, 11:15 AM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2584#pullrequestreview-834608407 at 12/16/2021, 01:11 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2594#issuecomment-996956603 at 12/17/2021, 10:58 AM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2594#pullrequestreview-835584018 at 12/17/2021, 11:43 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2593#issuecomment-997432698 at 12/19/2021, 09:47 AM PST
- sydneywalcoff assigned: https://github.com/hackforla/website/issues/2488#issuecomment-968551127 at 12/19/2021, 11:25 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2593#issuecomment-998242276 at 12/20/2021, 12:21 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/issues/2488#issuecomment-998265721 at 12/20/2021, 01:01 PM PST
- sydneywalcoff issue closed by PR 2593: https://github.com/hackforla/website/issues/2552#event-5797501253 at 12/21/2021, 12:57 AM PST
- sydneywalcoff PR was merged: https://github.com/hackforla/website/pull/2593#event-5797501277 at 12/21/2021, 12:57 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/issues/2488#issuecomment-1000527626 at 12/23/2021, 01:18 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2640#issuecomment-1002811363 at 12/29/2021, 03:23 PM PST
- sydneywalcoff opened: https://github.com/hackforla/website/pull/2646 at 12/30/2021, 01:52 PM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2640#pullrequestreview-842102507 at 12/30/2021, 02:03 PM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2640#pullrequestreview-842282941 at 12/31/2021, 09:04 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2644#issuecomment-1003420216 at 12/31/2021, 09:10 AM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2647#pullrequestreview-843872369 at 01/04/2022, 10:21 AM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2644#pullrequestreview-843917142 at 01/04/2022, 11:14 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2646#issuecomment-1005906226 at 01/05/2022, 09:03 AM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2646#issuecomment-1007692742 at 01/07/2022, 11:52 AM PST
- sydneywalcoff issue closed by PR 2646: https://github.com/hackforla/website/issues/2488#event-5861725851 at 01/08/2022, 03:18 PM PST
- sydneywalcoff PR was merged: https://github.com/hackforla/website/pull/2646#event-5861725852 at 01/08/2022, 03:18 PM PST
- sydneywalcoff assigned: https://github.com/hackforla/website/issues/2629#issuecomment-1002334995 at 01/09/2022, 11:45 AM PST
- sydneywalcoff opened: https://github.com/hackforla/website/pull/2682 at 01/09/2022, 05:07 PM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2665#pullrequestreview-849725639 at 01/11/2022, 01:05 PM PST
- sydneywalcoff submitted review: https://github.com/hackforla/website/pull/2665#pullrequestreview-852422133 at 01/13/2022, 06:03 PM PST
- sydneywalcoff commented on: https://github.com/hackforla/website/pull/2682#issuecomment-1017848978 at 01/20/2022, 11:28 AM PST
- sydneywalcoff issue closed by PR 2682: https://github.com/hackforla/website/issues/2629#event-5937857065 at 01/22/2022, 11:06 PM PST
- sydneywalcoff PR was merged: https://github.com/hackforla/website/pull/2682#event-5937857069 at 01/22/2022, 11:06 PM PST
- sydneywalcoff opened: https://github.com/hackforla/website/issues/7321 at 08/20/2024, 11:36 AM PDT
