### ISSUE TITLE
Pre-work Checklist: Developer: Anthony Sim

### ISSUE THREAD

**Issue by anthonysim** [hackforla/website#2521]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [x] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by HackforLABot** [comment]
## Activity Log: anthonysim
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- anthonysim opened: https://github.com/hackforla/website/issues/2521 at 11/29/2021, 07:42 PM PST
- anthonysim assigned: https://github.com/hackforla/website/issues/2521 at 11/29/2021, 07:44 PM PST
- anthonysim assigned: https://github.com/hackforla/website/issues/2434#issuecomment-958188543 at 12/01/2021, 12:06 PM PST
- anthonysim commented on: https://github.com/hackforla/website/issues/2434#issuecomment-984013562 at 12/01/2021, 12:07 PM PST
- anthonysim opened: https://github.com/hackforla/website/pull/2534 at 12/01/2021, 06:30 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2534#issuecomment-984236309 at 12/01/2021, 06:31 PM PST
- anthonysim closed as completed: https://github.com/hackforla/website/issues/2521#event-5703086247 at 12/01/2021, 07:24 PM PST
- anthonysim assigned: https://github.com/hackforla/website/issues/2234 at 12/02/2021, 06:42 PM PST
- anthonysim commented on: https://github.com/hackforla/website/issues/2234#issuecomment-985168748 at 12/02/2021, 06:43 PM PST
- anthonysim issue closed by PR 2534: https://github.com/hackforla/website/issues/2434#event-5716184132 at 12/04/2021, 03:44 PM PST
- anthonysim PR was merged: https://github.com/hackforla/website/pull/2534#event-5716184139 at 12/04/2021, 03:44 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2546#pullrequestreview-823424127 at 12/05/2021, 11:19 AM PST
- anthonysim commented on: https://github.com/hackforla/website/issues/2515#issuecomment-986295260 at 12/05/2021, 12:32 PM PST
- anthonysim opened: https://github.com/hackforla/website/pull/2548 at 12/05/2021, 08:14 PM PST
- anthonysim closed: https://github.com/hackforla/website/pull/2548#event-5718016375 at 12/05/2021, 08:21 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2548#issuecomment-986426114 at 12/05/2021, 08:22 PM PST
- anthonysim opened: https://github.com/hackforla/website/pull/2549 at 12/05/2021, 08:27 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2549#issuecomment-986429662 at 12/05/2021, 08:30 PM PST
- anthonysim assigned: https://github.com/hackforla/website/issues/2487#issuecomment-968535572 at 12/06/2021, 05:49 PM PST
- anthonysim commented on: https://github.com/hackforla/website/issues/2487#issuecomment-987494335 at 12/06/2021, 05:52 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2556#pullrequestreview-825985244 at 12/07/2021, 07:54 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2549#issuecomment-989443995 at 12/08/2021, 06:22 PM PST
- anthonysim issue closed by PR 2549: https://github.com/hackforla/website/issues/2234#event-5744517870 at 12/09/2021, 04:18 PM PST
- anthonysim PR was merged: https://github.com/hackforla/website/pull/2549#event-5744517886 at 12/09/2021, 04:18 PM PST
- anthonysim commented on: https://github.com/hackforla/website/issues/2487#issuecomment-991086738 at 12/10/2021, 07:54 AM PST
- anthonysim opened: https://github.com/hackforla/website/pull/2575 at 12/10/2021, 04:08 PM PST
- anthonysim assigned: https://github.com/hackforla/website/issues/2474#issuecomment-965937454 at 12/10/2021, 04:33 PM PST
- anthonysim commented on: https://github.com/hackforla/website/issues/2474#issuecomment-991392123 at 12/10/2021, 04:35 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2577#pullrequestreview-829658549 at 12/12/2021, 10:58 AM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2575#issuecomment-992110336 at 12/12/2021, 08:55 PM PST
- anthonysim issue closed by PR 2575: https://github.com/hackforla/website/issues/2487#event-5768317084 at 12/14/2021, 06:13 PM PST
- anthonysim PR was merged: https://github.com/hackforla/website/pull/2575#event-5768317096 at 12/14/2021, 06:13 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2587#pullrequestreview-833110649 at 12/15/2021, 09:15 AM PST
- anthonysim opened: https://github.com/hackforla/website/pull/2602 at 12/18/2021, 02:30 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2602#issuecomment-997294291 at 12/18/2021, 02:36 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2602#issuecomment-997296113 at 12/18/2021, 02:53 PM PST
- anthonysim closed: https://github.com/hackforla/website/pull/2602#event-5788542482 at 12/18/2021, 02:53 PM PST
- anthonysim opened: https://github.com/hackforla/website/pull/2603 at 12/18/2021, 02:59 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2603#issuecomment-997297121 at 12/18/2021, 03:03 PM PST
- anthonysim assigned: https://github.com/hackforla/website/issues/2397#issuecomment-951195918 at 12/18/2021, 03:32 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2594#pullrequestreview-835892643 at 12/19/2021, 10:50 AM PST
- anthonysim unassigned: https://github.com/hackforla/website/issues/2397#issuecomment-951195918 at 12/19/2021, 11:27 AM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2603#issuecomment-997489587 at 12/19/2021, 04:10 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2603#issuecomment-998224797 at 12/20/2021, 11:54 AM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2603#issuecomment-999276159 at 12/21/2021, 08:23 PM PST
- anthonysim assigned: https://github.com/hackforla/website/issues/2397#issuecomment-951195918 at 12/22/2021, 09:34 AM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2603#pullrequestreview-838975729 at 12/22/2021, 07:12 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2603#issuecomment-1000416367 at 12/23/2021, 08:40 AM PST
- anthonysim issue closed by PR 2603: https://github.com/hackforla/website/issues/2474#event-5827135211 at 12/30/2021, 12:31 AM PST
- anthonysim PR was merged: https://github.com/hackforla/website/pull/2603#event-5827135221 at 12/30/2021, 12:31 AM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2643#issuecomment-1003141522 at 12/30/2021, 10:40 AM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2643#pullrequestreview-842377134 at 01/01/2022, 07:23 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2648#issuecomment-1005329099 at 01/04/2022, 06:28 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2648#issuecomment-1005350888 at 01/04/2022, 07:24 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2648#pullrequestreview-844186010 at 01/04/2022, 07:24 PM PST
- anthonysim opened: https://github.com/hackforla/website/pull/2672 at 01/07/2022, 07:18 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2678#pullrequestreview-848615891 at 01/10/2022, 09:31 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1009639665 at 01/10/2022, 10:32 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1009649128 at 01/10/2022, 10:54 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1013931101 at 01/16/2022, 10:51 AM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2696#issuecomment-1016045240 at 01/18/2022, 07:27 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2693#pullrequestreview-856212958 at 01/18/2022, 07:35 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1019027297 at 01/21/2022, 07:04 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2696#pullrequestreview-860160774 at 01/21/2022, 07:09 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2710#issuecomment-1021834773 at 01/25/2022, 07:46 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2713#pullrequestreview-863094724 at 01/25/2022, 08:00 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2710#issuecomment-1021844451 at 01/25/2022, 08:11 PM PST
- anthonysim commented on: https://github.com/hackforla/website/pull/2643#issuecomment-1022663533 at 01/26/2022, 02:31 PM PST
- anthonysim submitted review: https://github.com/hackforla/website/pull/2710#pullrequestreview-866885035 at 01/28/2022, 11:17 PM PST
- anthonysim unassigned: https://github.com/hackforla/website/issues/2397#issuecomment-1014154476 at 01/28/2022, 11:21 PM PST
- anthonysim unassigned: https://github.com/hackforla/website/issues/2397#issuecomment-1014154476 at 01/28/2022, 11:21 PM PST
