### ISSUE TITLE
Pre-work Checklist: Developer: Miguel Lopez

### ISSUE THREAD

**Issue by lopezpedres** [hackforla/website#2522]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [x] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by lopezpedres** [comment]
Availability for this week:
    -Wednesday  : 12:00 pm - 3:00  pm
    -Thursday:  3 pm- 5:30 pm
    -Sunday: 9 am - 12 pm

My estimated ETA for completing this issue: 
    - 2021/12/02

**Comment by HackforLABot** [comment]
## Activity Log: lopezpedres
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- lopezpedres opened: https://github.com/hackforla/website/issues/2522 at 11/29/2021, 07:43 PM PST
- lopezpedres assigned: https://github.com/hackforla/website/issues/2522 at 11/29/2021, 07:44 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/issues/2522#issuecomment-983233047 at 11/30/2021, 06:48 PM PST
- lopezpedres closed as completed: https://github.com/hackforla/website/issues/2522#event-5701435437 at 12/01/2021, 11:50 AM PST
- lopezpedres assigned: https://github.com/hackforla/website/issues/2433#issuecomment-958168887 at 12/01/2021, 11:53 AM PST
- lopezpedres opened: https://github.com/hackforla/website/pull/2532 at 12/01/2021, 03:12 PM PST
- lopezpedres assigned: https://github.com/hackforla/website/issues/2235 at 12/01/2021, 07:30 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/issues/2235#issuecomment-984263302 at 12/01/2021, 07:37 PM PST
- lopezpedres opened: https://github.com/hackforla/website/pull/2540 at 12/02/2021, 05:58 PM PST
- lopezpedres issue closed by PR 2532: https://github.com/hackforla/website/issues/2433#event-5716179429 at 12/04/2021, 03:42 PM PST
- lopezpedres PR was merged: https://github.com/hackforla/website/pull/2532#event-5716179438 at 12/04/2021, 03:42 PM PST
- lopezpedres closed: https://github.com/hackforla/website/pull/2540#event-5716192181 at 12/04/2021, 03:47 PM PST
- lopezpedres opened: https://github.com/hackforla/website/pull/2545 at 12/04/2021, 10:43 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2546#pullrequestreview-823446113 at 12/05/2021, 03:09 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2538#pullrequestreview-823450053 at 12/05/2021, 03:42 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2538#issuecomment-986330465 at 12/05/2021, 04:09 PM PST
- lopezpedres assigned: https://github.com/hackforla/website/issues/2296#issuecomment-927235170 at 12/08/2021, 02:24 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/issues/2296#issuecomment-989278833 at 12/08/2021, 02:28 PM PST
- lopezpedres issue closed by PR 2545: https://github.com/hackforla/website/issues/2235#event-5738204430 at 12/08/2021, 08:20 PM PST
- lopezpedres PR was merged: https://github.com/hackforla/website/pull/2545#event-5738204445 at 12/08/2021, 08:20 PM PST
- lopezpedres opened: https://github.com/hackforla/website/pull/2566 at 12/09/2021, 01:26 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2575#pullrequestreview-829664018 at 12/12/2021, 12:03 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2566#issuecomment-994013890 at 12/14/2021, 01:11 PM PST
- lopezpedres issue closed by PR 2566: https://github.com/hackforla/website/issues/2296#event-5768294578 at 12/14/2021, 06:06 PM PST
- lopezpedres PR was merged: https://github.com/hackforla/website/pull/2566#event-5768294589 at 12/14/2021, 06:06 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2587#pullrequestreview-832284084 at 12/14/2021, 08:26 PM PST
- lopezpedres assigned: https://github.com/hackforla/website/issues/2385#issuecomment-948119363 at 12/14/2021, 08:38 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/issues/2385#issuecomment-994287788 at 12/14/2021, 08:43 PM PST
- lopezpedres opened: https://github.com/hackforla/website/pull/2590 at 12/15/2021, 03:07 PM PST
- lopezpedres issue closed by PR 2566: https://github.com/hackforla/website/issues/2296#event-5775872515 at 12/15/2021, 09:07 PM PST
- lopezpedres PR was merged: https://github.com/hackforla/website/pull/2590#event-5775872526 at 12/15/2021, 09:07 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2593#pullrequestreview-834665978 at 12/16/2021, 02:30 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2599#pullrequestreview-838010331 at 12/21/2021, 06:06 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/issues/2385#issuecomment-1001099041 at 12/25/2021, 06:44 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2624#pullrequestreview-840540161 at 12/27/2021, 11:50 AM PST
- lopezpedres opened: https://github.com/hackforla/website/pull/2635 at 12/27/2021, 12:23 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2635#issuecomment-1001740229 at 12/27/2021, 12:25 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2635#issuecomment-1002716701 at 12/29/2021, 10:03 AM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2635#issuecomment-1002844681 at 12/29/2021, 06:20 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/issues/2385#issuecomment-1005279212 at 01/04/2022, 04:33 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2643#issuecomment-1006158312 at 01/05/2022, 03:29 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2643#pullrequestreview-846205058 at 01/06/2022, 05:15 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1009432127 at 01/10/2022, 03:04 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1009465587 at 01/10/2022, 03:52 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1009466776 at 01/10/2022, 03:55 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2665#issuecomment-1009468404 at 01/10/2022, 03:59 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1009572022 at 01/10/2022, 07:44 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2672#pullrequestreview-848573936 at 01/10/2022, 07:46 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2665#pullrequestreview-849803013 at 01/11/2022, 02:40 PM PST
- lopezpedres commented on: https://github.com/hackforla/website/pull/2672#issuecomment-1010436107 at 01/11/2022, 02:47 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2665#pullrequestreview-849823567 at 01/11/2022, 03:12 PM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2682#pullrequestreview-852096882 at 01/13/2022, 10:29 AM PST
- lopezpedres submitted review: https://github.com/hackforla/website/pull/2672#pullrequestreview-854853749 at 01/17/2022, 04:33 PM PST
- lopezpedres PR was closed: https://github.com/hackforla/website/pull/2635#event-6165828291 at 03/01/2022, 04:17 PM PST
- lopezpedres unassigned: https://github.com/hackforla/website/issues/2385#issuecomment-1056024820 at 03/11/2022, 12:17 PM PST
