### ISSUE TITLE
Pre-work Checklist: Developer: John Guan

### ISSUE THREAD

**Issue by jqg123** [hackforla/website#2523]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [ ] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by ExperimentsInHonesty** [comment]
Let's talk about what to do when no one responds to your updates on the issue in a timely manner.

**Comment by SAUMILDHANKAR** [comment]
@jqg123 Once you have given a progress report on an issue (other than your newly assigned status), then you can check off the box above and close this issue.  See the following section above

- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```

**Comment by SAUMILDHANKAR** [comment]
@jqg123: Hi John, I am planning to close this issue, since haven't heard from you in a while. If you want, you can work on it later based on availability. I left a message for you on Slack stating the same. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@jqg123 Thanks for getting back to me on Slack. Please update your progress on #2557 as well. Thank you.

**Comment by jqg123** [comment]
Done

**Comment by SAUMILDHANKAR** [comment]
@jqg123 Once you have given a progress report on an issue (other than this issue), then you can check off the box above and close this issue. I understand this might happen when you are working on another issue which takes long time to complete. Until that time this issue should remain open, so I am reopening this issue. See the following section above

- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```

**Comment by JessicaLucindaCheng** [comment]
@jqg123 As [Saumil commented](https://github.com/hackforla/website/issues/2523#issuecomment-1036986972), you still need to check off the box for a progress update, which should include the following:
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
You can provide that update in this issue you working on: https://github.com/hackforla/website/issues/2528. After you provide that update, you can check off the checkbox for the "Weekly, please also provide an update on the issue" and close this issue.

**Comment by JessicaLucindaCheng** [comment]
Slack messaged John about https://github.com/hackforla/website/issues/2523#issuecomment-1051393045 on Fri, Feb 25, 2022.

Edit: John said he will work on it but has limited availability because of college.

**Comment by SAUMILDHANKAR** [comment]
Closing this issue due to change in availability, as John has an upcoming job. Marked inactive on roster.

**Comment by HackforLABot** [comment]
## Activity Log: jqg123
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- jqg123 assigned: https://github.com/hackforla/website/issues/2519 at 11/29/2021, 07:42 PM PST
- jqg123 unassigned: https://github.com/hackforla/website/issues/2519 at 11/29/2021, 07:43 PM PST
- jqg123 opened: https://github.com/hackforla/website/issues/2523 at 11/29/2021, 07:44 PM PST
- jqg123 assigned: https://github.com/hackforla/website/issues/2523 at 11/29/2021, 07:45 PM PST
- jqg123 assigned: https://github.com/hackforla/website/issues/2441#issuecomment-960296427 at 12/01/2021, 01:05 PM PST
- jqg123 commented on: https://github.com/hackforla/website/issues/2441#issuecomment-984069300 at 12/01/2021, 01:27 PM PST
- jqg123 opened: https://github.com/hackforla/website/pull/2530 at 12/01/2021, 02:32 PM PST
- jqg123 assigned: https://github.com/hackforla/website/issues/2356#issuecomment-939420187 at 12/02/2021, 10:57 AM PST
- jqg123 commented on: https://github.com/hackforla/website/issues/2356#issuecomment-984912160 at 12/02/2021, 11:02 AM PST
- jqg123 opened: https://github.com/hackforla/website/pull/2538 at 12/02/2021, 12:21 PM PST
- jqg123 issue closed by PR 2530: https://github.com/hackforla/website/issues/2441#event-5716176767 at 12/04/2021, 03:41 PM PST
- jqg123 PR was merged: https://github.com/hackforla/website/pull/2530#event-5716176775 at 12/04/2021, 03:41 PM PST
- jqg123 closed as completed: https://github.com/hackforla/website/issues/2523#event-5730528853 at 12/07/2021, 03:34 PM PST
- jqg123 assigned: https://github.com/hackforla/website/issues/2528#issuecomment-984062441 at 12/07/2021, 03:52 PM PST
- jqg123 commented on: https://github.com/hackforla/website/issues/2528#issuecomment-988353933 at 12/07/2021, 03:55 PM PST
- jqg123 commented on: https://github.com/hackforla/website/issues/2528#issuecomment-988420809 at 12/07/2021, 05:48 PM PST
- jqg123 opened: https://github.com/hackforla/website/pull/2557 at 12/07/2021, 06:06 PM PST
- jqg123 issue closed by PR 2538: https://github.com/hackforla/website/issues/2356#event-5731116510 at 12/07/2021, 06:38 PM PST
- jqg123 PR was merged: https://github.com/hackforla/website/pull/2538#event-5731116522 at 12/07/2021, 06:38 PM PST
- jqg123 closed as completed: https://github.com/hackforla/website/issues/2523#event-6030438237 at 02/08/2022, 03:11 PM PST
- jqg123 commented on: https://github.com/hackforla/website/issues/2523#issuecomment-1033153969 at 02/08/2022, 03:11 PM PST
- jqg123 commented on: https://github.com/hackforla/website/pull/2557#issuecomment-1033158588 at 02/08/2022, 03:19 PM PST
- jqg123 opened: https://github.com/hackforla/website/pull/2774 at 02/12/2022, 10:05 PM PST
- jqg123 commented on: https://github.com/hackforla/website/issues/2528#issuecomment-1037820304 at 02/12/2022, 10:09 PM PST
- jqg123 PR was closed: https://github.com/hackforla/website/pull/2557#event-6079579827 at 02/15/2022, 06:29 PM PST
- jqg123 opened: https://github.com/hackforla/website/issues/2810 at 02/20/2022, 12:08 PM PST
- jqg123 assigned: https://github.com/hackforla/website/issues/2810 at 02/20/2022, 12:08 PM PST
- jqg123 unassigned: https://github.com/hackforla/website/issues/2810#issuecomment-1046316268 at 02/26/2022, 12:39 PM PST
- jqg123 commented on: https://github.com/hackforla/website/pull/2774#issuecomment-1052589264 at 02/26/2022, 12:44 PM PST
- jqg123 PR was closed: https://github.com/hackforla/website/pull/2774#event-6228962242 at 03/11/2022, 05:34 PM PST
- jqg123 unassigned: https://github.com/hackforla/website/issues/2528#issuecomment-1043829929 at 03/11/2022, 05:39 PM PST
- jqg123 issue closed as completed: https://github.com/hackforla/website/issues/2523#event-6229567739 at 03/12/2022, 03:01 AM PST
