### ISSUE TITLE
Pre-work Checklist: Developer: Johnnie Hicks

### ISSUE THREAD

**Issue by Johnnie007** [hackforla/website#2524]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [x] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by Johnnie007** [comment]
Availability for this week 12/5 -12/11:
Tuesday & Thursday  Evenings/Night EST
My estimated ETA for completing this issue:
15 mins

**Comment by ExperimentsInHonesty** [comment]
@Johnnie007

I noticed on your next issue https://github.com/hackforla/website/issues/2267 that you did not post availability when you self assigned. 

Then you did post a note when you had a question, and later followed up by at mentioning Matt (which was awesome)

When you didn't get a response, you did not bring it up at the team meeting today.  Feel free to put things in the column labeled Development team meeting discussion items 🤔 https://github.com/hackforla/website/projects/7#column-14434559

**Comment by Johnnie007** [comment]
@ExperimentsInHonesty Thanks for reaching out. I noticed that my comment lacks detail. All in all, the issue was resolved when the Wins page was converted to use the Jekyll template( I believe in a previous issue). So no work needs to be done on the #2267 issue. The issue just needs to be closed. I'll be sure to leave a more detailed comment on the issue.

**Comment by SAUMILDHANKAR** [comment]
@Johnnie007 Once you have given an progress report on an issue (other than your newly assigned status), then you can check off the box above and close this issue.  See the following section above

- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```

**Comment by JessicaLucindaCheng** [comment]
@Johnnie007 I'm reopening your pre-work checklist because a weekly progress report still needs to be given on an issue you are working on (not including this pre-work issue). A weekly progress report should be given every week for an open issue that you are working on.

I see you are working on issue #1498 and you gave an initial ETA and availability. However, it has been over a week since you gave that initial ETA and availability, so please give a weekly progress report as a comment in issue #1498 that includes the following: 
```
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"
```
Once you have added a weekly progress report to an issue, then you can check off the checkbox above for " Weekly, please also provide an update on the issue". Thank you.

**Comment by SAUMILDHANKAR** [comment]
@Johnnie007 Please share your weekly progress report and then you can check off the item in the checklist above. Thanks.

**Comment by JessicaLucindaCheng** [comment]
@Johnnie007 For this pre-work checklist, a weekly progress report is still needed to be given on an issue you are working on (not including this pre-work issue). A weekly progress report should be given every week for an open issue that you are working on.

I see you are working on issue #1498 and you gave an initial ETA and availability. However, it has been over a week since you gave that initial ETA and availability, so please give a weekly progress report as a comment in issue #1498 that includes the following: 
```
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"
```
Once you have added a weekly progress report to an issue, then you can check off the checkbox above for " Weekly, please also provide an update on the issue". Thank you.

**Comment by JessicaLucindaCheng** [comment]
Left a Slack message for Johnnie about https://github.com/hackforla/website/issues/2524#issuecomment-1051405799 on Fri, Feb 25, 2022.

**Comment by Johnnie007** [comment]
Completing a course, and I will be inactive for the next 5 weeks.

**Comment by HackforLABot** [comment]
## Activity Log: Johnnie007
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Johnnie007 opened: https://github.com/hackforla/website/issues/2524 at 11/29/2021, 07:47 PM PST
- Johnnie007 assigned: https://github.com/hackforla/website/issues/2524 at 11/29/2021, 07:50 PM PST
- Johnnie007 assigned: https://github.com/hackforla/website/issues/2490#issuecomment-968561829 at 12/03/2021, 08:49 AM PST
- Johnnie007 opened: https://github.com/hackforla/website/pull/2541 at 12/03/2021, 09:40 AM PST
- Johnnie007 commented on: https://github.com/hackforla/website/issues/2524#issuecomment-985709543 at 12/03/2021, 09:44 AM PST
- Johnnie007 issue closed by PR 2541: https://github.com/hackforla/website/issues/2490#event-5716186909 at 12/04/2021, 03:45 PM PST
- Johnnie007 PR was merged: https://github.com/hackforla/website/pull/2541#event-5716186916 at 12/04/2021, 03:45 PM PST
- Johnnie007 assigned: https://github.com/hackforla/website/issues/2094 at 12/05/2021, 06:56 AM PST
- Johnnie007 commented on: https://github.com/hackforla/website/issues/2094#issuecomment-987485109 at 12/06/2021, 05:30 PM PST
- Johnnie007 opened: https://github.com/hackforla/website/pull/2551 at 12/06/2021, 06:19 PM PST
- Johnnie007 closed as completed: https://github.com/hackforla/website/issues/2524#event-5731768063 at 12/07/2021, 10:34 PM PST
- Johnnie007 issue closed by PR 2551: https://github.com/hackforla/website/issues/2094#event-5737891575 at 12/08/2021, 06:31 PM PST
- Johnnie007 PR was merged: https://github.com/hackforla/website/pull/2551#event-5737891584 at 12/08/2021, 06:31 PM PST
- Johnnie007 submitted review: https://github.com/hackforla/website/pull/2549#pullrequestreview-827708829 at 12/09/2021, 05:52 AM PST
- Johnnie007 assigned: https://github.com/hackforla/website/issues/2267#issuecomment-920334512 at 12/09/2021, 07:16 AM PST
- Johnnie007 commented on: https://github.com/hackforla/website/issues/2267#issuecomment-989992949 at 12/09/2021, 08:07 AM PST
- Johnnie007 commented on: https://github.com/hackforla/website/issues/2267#issuecomment-989994226 at 12/09/2021, 08:08 AM PST
- Johnnie007 commented on: https://github.com/hackforla/website/issues/2524#issuecomment-992521678 at 12/13/2021, 06:14 AM PST
- Johnnie007 commented on: https://github.com/hackforla/website/issues/2267#issuecomment-992545237 at 12/13/2021, 06:38 AM PST
- Johnnie007 commented on: https://github.com/hackforla/website/issues/2267#issuecomment-996012799 at 12/16/2021, 09:10 AM PST
- Johnnie007 opened: https://github.com/hackforla/website/pull/2621 at 12/22/2021, 01:32 PM PST
- Johnnie007 issue closed by PR 2621: https://github.com/hackforla/website/issues/2267#event-5816927091 at 12/27/2021, 12:06 AM PST
- Johnnie007 PR was merged: https://github.com/hackforla/website/pull/2621#event-5816927113 at 12/27/2021, 12:06 AM PST
- Johnnie007 closed as completed: https://github.com/hackforla/website/issues/2524#event-6004942646 at 02/03/2022, 10:47 AM PST
- Johnnie007 commented on: https://github.com/hackforla/website/issues/2524#issuecomment-1051423649 at 02/25/2022, 05:33 PM PST
- Johnnie007 issue closed as completed: https://github.com/hackforla/website/issues/2524#event-6142734968 at 02/25/2022, 05:40 PM PST
