### ISSUE TITLE
Pre-work Checklist: Designer: Stephen Parent

### ISSUE THREAD

**Issue by Stephen-Parent** [hackforla/website#2531]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the team lead
- [x] (once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Confirm with the team lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [x] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings: 
   - [x] UX weekly team meeting, Thursdays 5pm PST
   - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Review the prioritized Backlog to see what Design Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [x] Once you accept an assignment (issue), please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
provide update
1. Progress
2. Blockers
3. Availability
4. ETA
```
### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by HackforLABot** [comment]
## Activity Log: Stephen-Parent
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Stephen-Parent opened: https://github.com/hackforla/website/issues/2531 at 12/01/2021, 03:12 PM PST
- Stephen-Parent assigned: https://github.com/hackforla/website/issues/2511#issuecomment-975817799 at 12/01/2021, 03:31 PM PST
- Stephen-Parent commented on: https://github.com/hackforla/website/issues/2511#issuecomment-986136304 at 12/04/2021, 03:41 PM PST
- Stephen-Parent issue closed as completed: https://github.com/hackforla/website/issues/2511#event-5716983950 at 12/05/2021, 08:47 AM PST
- Stephen-Parent issue closed as completed: https://github.com/hackforla/website/issues/2511#event-5717086528 at 12/05/2021, 10:35 AM PST
- Stephen-Parent closed as completed: https://github.com/hackforla/website/issues/2531#event-5722042734 at 12/06/2021, 09:07 AM PST
- Stephen-Parent assigned: https://github.com/hackforla/website/issues/2531#event-5722042734 at 12/07/2021, 07:33 AM PST
- Stephen-Parent assigned: https://github.com/hackforla/website/issues/2361#issuecomment-939510317 at 12/08/2021, 03:43 PM PST
- Stephen-Parent commented on: https://github.com/hackforla/website/issues/2361#issuecomment-989325156 at 12/08/2021, 04:01 PM PST
- Stephen-Parent commented on: https://github.com/hackforla/website/issues/2361#issuecomment-996346074 at 12/16/2021, 05:22 PM PST
- Stephen-Parent unassigned: https://github.com/hackforla/website/issues/2361#issuecomment-1002763549 at 01/05/2022, 10:48 AM PST
- Stephen-Parent assigned: https://github.com/hackforla/website/issues/2694#issuecomment-1014847765 at 01/30/2022, 11:53 AM PST
- Stephen-Parent commented on: https://github.com/hackforla/website/issues/2694#issuecomment-1025218581 at 01/30/2022, 11:57 AM PST
- Stephen-Parent commented on: https://github.com/hackforla/website/issues/2694#issuecomment-1035811451 at 02/10/2022, 06:40 PM PST
- Stephen-Parent unassigned: https://github.com/hackforla/website/issues/2694#issuecomment-1092221869 at 04/14/2022, 12:38 PM PDT
