### ISSUE TITLE
Pre-work Checklist: Developer: Lindsey Dinkel

### ISSUE THREAD

**Issue by lindseyindev** [hackforla/website#2547]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [x] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by HackforLABot** [comment]
## Activity Log: lindseyindev
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- lindseyindev opened: https://github.com/hackforla/website/issues/2547 at 12/05/2021, 04:17 PM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2547#issuecomment-986332714 at 12/05/2021, 04:17 PM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2444#issuecomment-960388898 at 12/10/2021, 06:04 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2444#issuecomment-991411588 at 12/10/2021, 06:06 PM PST
- lindseyindev closed as completed: https://github.com/hackforla/website/issues/2547#event-5753248670 at 12/12/2021, 12:18 PM PST
- lindseyindev opened: https://github.com/hackforla/website/pull/2583 at 12/12/2021, 07:17 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2444#issuecomment-992075397 at 12/12/2021, 07:23 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2583#issuecomment-992753611 at 12/13/2021, 10:30 AM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2194#issuecomment-912421166 at 12/13/2021, 10:33 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2194#issuecomment-992760447 at 12/13/2021, 10:39 AM PST
- lindseyindev issue closed by PR 2583: https://github.com/hackforla/website/issues/2444#event-5760940724 at 12/13/2021, 05:54 PM PST
- lindseyindev PR was merged: https://github.com/hackforla/website/pull/2583#event-5760940732 at 12/13/2021, 05:54 PM PST
- lindseyindev opened: https://github.com/hackforla/website/pull/2587 at 12/13/2021, 10:34 PM PST
- lindseyindev issue closed by PR 2587: https://github.com/hackforla/website/issues/2194#event-5774867526 at 12/15/2021, 03:17 PM PST
- lindseyindev PR was merged: https://github.com/hackforla/website/pull/2587#event-5774867540 at 12/15/2021, 03:17 PM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2465#issuecomment-963672512 at 12/16/2021, 12:12 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2465#issuecomment-996161974 at 12/16/2021, 12:14 PM PST
- lindseyindev opened: https://github.com/hackforla/website/pull/2599 at 12/18/2021, 11:22 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2599#issuecomment-997274374 at 12/18/2021, 11:33 AM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2483#issuecomment-968431484 at 12/19/2021, 06:45 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2483#issuecomment-997546226 at 12/19/2021, 06:46 PM PST
- lindseyindev issue closed by PR 2599: https://github.com/hackforla/website/issues/2465#event-5802361334 at 12/21/2021, 07:12 PM PST
- lindseyindev PR was merged: https://github.com/hackforla/website/pull/2599#event-5802361342 at 12/21/2021, 07:12 PM PST
- lindseyindev opened: https://github.com/hackforla/website/pull/2624 at 12/23/2021, 05:23 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2624#issuecomment-1000598735 at 12/23/2021, 05:26 PM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2081 at 12/26/2021, 08:38 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2081#issuecomment-1001210342 at 12/26/2021, 08:38 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2624#issuecomment-1002797798 at 12/29/2021, 02:24 PM PST
- lindseyindev issue closed by PR 2624: https://github.com/hackforla/website/issues/2483#event-5826413985 at 12/29/2021, 04:49 PM PST
- lindseyindev PR was merged: https://github.com/hackforla/website/pull/2624#event-5826413993 at 12/29/2021, 04:49 PM PST
- lindseyindev opened: https://github.com/hackforla/website/pull/2645 at 12/29/2021, 08:23 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2641#issuecomment-1002869859 at 12/29/2021, 08:33 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2645#issuecomment-1003599437 at 01/01/2022, 10:43 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2648#issuecomment-1003607060 at 01/01/2022, 11:37 AM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2464#issuecomment-963658780 at 01/01/2022, 11:51 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2464#issuecomment-1003608533 at 01/01/2022, 11:53 AM PST
- lindseyindev submitted review: https://github.com/hackforla/website/pull/2648#pullrequestreview-842959787 at 01/03/2022, 10:44 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2645#issuecomment-1005336283 at 01/04/2022, 06:49 PM PST
- lindseyindev submitted review: https://github.com/hackforla/website/pull/2648#pullrequestreview-844184599 at 01/04/2022, 07:20 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2464#issuecomment-1005443452 at 01/04/2022, 11:26 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2464#issuecomment-1007115723 at 01/06/2022, 07:38 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2464#issuecomment-1009187605 at 01/10/2022, 10:04 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2678#issuecomment-1009188447 at 01/10/2022, 10:05 AM PST
- lindseyindev submitted review: https://github.com/hackforla/website/pull/2678#pullrequestreview-848575559 at 01/10/2022, 07:50 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2645#issuecomment-1011589463 at 01/12/2022, 04:42 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2464#issuecomment-1013809482 at 01/15/2022, 08:36 PM PST
- lindseyindev opened: https://github.com/hackforla/website/pull/2696 at 01/17/2022, 07:28 PM PST
- lindseyindev submitted review: https://github.com/hackforla/website/pull/2693#pullrequestreview-854920691 at 01/17/2022, 07:47 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2696#issuecomment-1018129669 at 01/20/2022, 07:17 PM PST
- lindseyindev submitted review: https://github.com/hackforla/website/pull/2700#pullrequestreview-859080275 at 01/20/2022, 07:39 PM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2204#issuecomment-907894023 at 01/22/2022, 10:32 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2204#issuecomment-1019425031 at 01/22/2022, 10:33 PM PST
- lindseyindev issue closed by PR 2696: https://github.com/hackforla/website/issues/2464#event-5945711302 at 01/24/2022, 01:49 PM PST
- lindseyindev PR was merged: https://github.com/hackforla/website/pull/2696#event-5945711311 at 01/24/2022, 01:49 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2645#issuecomment-1021816095 at 01/25/2022, 07:00 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2718#issuecomment-1021827874 at 01/25/2022, 07:26 PM PST
- lindseyindev submitted review: https://github.com/hackforla/website/pull/2718#pullrequestreview-863096284 at 01/25/2022, 08:05 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2204#issuecomment-1023915226 at 01/27/2022, 10:06 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2645#issuecomment-1025394241 at 01/30/2022, 09:27 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2204#issuecomment-1025410357 at 01/30/2022, 10:09 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2204#issuecomment-1030864990 at 02/06/2022, 08:18 AM PST
- lindseyindev commented on: https://github.com/hackforla/website/pull/2645#issuecomment-1030867970 at 02/06/2022, 08:35 AM PST
- lindseyindev issue closed by PR 2645: https://github.com/hackforla/website/issues/2081#event-6022326959 at 02/07/2022, 01:10 PM PST
- lindseyindev PR was merged: https://github.com/hackforla/website/pull/2645#event-6022326978 at 02/07/2022, 01:10 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2204#issuecomment-1035935745 at 02/10/2022, 11:15 PM PST
- lindseyindev opened: https://github.com/hackforla/website/pull/2767 at 02/11/2022, 11:18 PM PST
- lindseyindev submitted review: https://github.com/hackforla/website/pull/2819#pullrequestreview-888192927 at 02/20/2022, 08:40 PM PST
- lindseyindev issue closed by PR 2767: https://github.com/hackforla/website/issues/2204#event-6114501569 at 02/21/2022, 03:44 PM PST
- lindseyindev PR was merged: https://github.com/hackforla/website/pull/2767#event-6114501571 at 02/21/2022, 03:44 PM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2743#issuecomment-1030950232 at 02/22/2022, 03:00 PM PST
- lindseyindev commented on: https://github.com/hackforla/website/issues/2743#issuecomment-1048292042 at 02/22/2022, 03:00 PM PST
- lindseyindev opened: https://github.com/hackforla/website/pull/2894 at 02/26/2022, 08:26 PM PST
- lindseyindev issue closed by PR 2894: https://github.com/hackforla/website/issues/2743#event-6164828520 at 03/01/2022, 12:53 PM PST
- lindseyindev PR was merged: https://github.com/hackforla/website/pull/2894#event-6164828536 at 03/01/2022, 12:53 PM PST
- lindseyindev unassigned: https://github.com/hackforla/website/issues/2204#event-6114501569 at 11/06/2022, 11:15 AM PST
- lindseyindev issue closed by PR 2767: https://github.com/hackforla/website/issues/2204#event-7747808850 at 11/06/2022, 11:40 AM PST
- lindseyindev assigned: https://github.com/hackforla/website/issues/2204#event-7747808850 at 11/06/2022, 11:40 AM PST
