### ISSUE TITLE
Pre-work Checklist: Developer: Lamar Robinson

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2558]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [ ] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@lrobinson823: Just wanted to follow up if you had any questions or need any help. Please let me know. Thanks.

**Comment by SAUMILDHANKAR** [comment]
@lrobinson823 Great job on finishing all the items and picking up your good first issue. One last item is closing this issue. You can find the button to close the issue at the bottom of this page. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@lrobinson823 Hi Lamar, once you have given a progress report on an issue (other than your newly assigned status), then you can check off the box above and close this issue.  See the following section above

- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```

Thank you.

**Comment by SAUMILDHANKAR** [comment]
@lrobinson823: Hi Lamar, I am planning to close this issue, since haven't heard from you in a while. If you want you can work on it later based on availability. I left a message for you on Slack stating the same. Thank you.

**Comment by HackforLABot** [comment]
## Activity Log: lrobinson823
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- lrobinson823 assigned: https://github.com/hackforla/website/issues/2558 at 12/07/2021, 07:57 PM PST
- lrobinson823 assigned: https://github.com/hackforla/website/issues/2489#issuecomment-968559716 at 12/30/2021, 07:39 PM PST
- lrobinson823 commented on: https://github.com/hackforla/website/issues/2489#issuecomment-1003261649 at 12/30/2021, 08:09 PM PST
- lrobinson823 opened: https://github.com/hackforla/website/pull/2648 at 12/31/2021, 12:22 AM PST
- lrobinson823 closed as completed: https://github.com/hackforla/website/issues/2558#event-5843906573 at 01/04/2022, 06:53 PM PST
- lrobinson823 commented on: https://github.com/hackforla/website/pull/2648#issuecomment-1005341682 at 01/04/2022, 07:03 PM PST
- lrobinson823 issue closed by PR 2648: https://github.com/hackforla/website/issues/2489#event-5855193496 at 01/06/2022, 04:06 PM PST
- lrobinson823 PR was merged: https://github.com/hackforla/website/pull/2648#event-5855193502 at 01/06/2022, 04:06 PM PST
- lrobinson823 issue closed as completed: https://github.com/hackforla/website/issues/2558#event-6079139271 at 02/15/2022, 04:41 PM PST
