### ISSUE TITLE
Pre-work Checklist: Developer: George Ma

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2559]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [ ] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [ ] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by Georgema20** [comment]
Availability for this week: Monday evening/night, Tuesday early morning, Wednesday early morning and evening/late night, Thursday early morning, Friday early morning, and noon. 

My estimated ETA for completing this issue: 2 days?

**Comment by Georgema20** [comment]
Provide Update
1. Progress
Finished everything except my second issue (will be taking that on tomorrow) 
2. Blockers
Nothing. Just mild confusion, but getting through it. 
3. Availability
Monday evening/night, Tuesday early morning, Wednesday early morning and evening/late night, Thursday early morning, Friday early morning, and noon.
4. ETA
This issue should be finished by tomorrow if no major tech problems that I cannot solve arise.

**Comment by SAUMILDHANKAR** [comment]
@Georgema20: Please share your availability and ETA for all the issues on the issues themselves instead of here on pre work template. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@Georgema20: Hi George, I am reopening this issue since some of the items in the checklist are pending. 

Also, once you have given an progress report on an issue (other than your newly assigned status), then you can check off the box above and close this issue.  See the following section above

- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```

Thank you.

**Comment by Georgema20** [comment]
Provide Update
1. Progress
Finished one medium PR - waiting for it to be checked. Reviewed one small PR. 
2. Blockers
No blockers
3. Availability
This entire weekend 
4. ETA
Everything is done.

**Comment by SAUMILDHANKAR** [comment]
@Georgema20 Hey George, so we want you to do a weekly progress update on an actual issue that you are working on and not on this pre work checklist. Please keep this issue open until you have done that. Thank you.

**Comment by Georgema20** [comment]
Please elaborate.

Do you want me to go on the issue I am working on and just basically
comment on my progress, blockers, and such? Is that it?

**Comment by JessicaLucindaCheng** [comment]
@Georgema20 Yes, in the issue you are working on you should give a progress report on a weekly basis that includes the following:
```
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"
```

Also, in the future, when you leave comments in GitHub for someone, can you @ mention the person(s) you are directing the message to? This will notify the person you have a message or question for them. Thanks.

**Comment by JessicaLucindaCheng** [comment]
@Georgema20 I couldn't find your Slack id to contact you and I'm not sure if you saw my comment above: https://github.com/hackforla/website/issues/2559#issuecomment-1030663441

**Comment by JessicaLucindaCheng** [comment]
@Georgema20 I'm not sure if you saw my comment above, so repeating it here.

Yes, in the issue you are working on you should give a progress report on a weekly basis that includes the following:
```
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"
```

Also, in the future, when you leave comments in GitHub for someone, can you @ mention the person(s) you are directing the message to? This will notify the person you have a message or question for them. Thanks.

**Comment by JessicaLucindaCheng** [comment]
Left a Slack message on Fri, Feb 25, 2022.

**Comment by SAUMILDHANKAR** [comment]
Closing issue due to inactivity. Will drop an email as well.

**Comment by HackforLABot** [comment]
## Activity Log: Georgema20
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Georgema20 assigned: https://github.com/hackforla/website/issues/2559 at 12/07/2021, 07:58 PM PST
- Georgema20 assigned: https://github.com/hackforla/website/issues/2348#issuecomment-938228116 at 12/12/2021, 08:06 AM PST
- Georgema20 opened: https://github.com/hackforla/website/pull/2582 at 12/12/2021, 03:04 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/issues/2559#issuecomment-991991000 at 12/12/2021, 03:20 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/issues/2559#issuecomment-992009957 at 12/12/2021, 04:45 PM PST
- Georgema20 assigned: https://github.com/hackforla/website/issues/2087 at 12/12/2021, 04:57 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2582#issuecomment-992636392 at 12/13/2021, 08:14 AM PST
- Georgema20 opened: https://github.com/hackforla/website/pull/2584 at 12/13/2021, 09:20 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2584#issuecomment-992827312 at 12/13/2021, 11:54 AM PST
- Georgema20 issue closed by PR 2582: https://github.com/hackforla/website/issues/2348#event-5760937835 at 12/13/2021, 05:53 PM PST
- Georgema20 PR was merged: https://github.com/hackforla/website/pull/2582#event-5760937845 at 12/13/2021, 05:53 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2584#issuecomment-993138647 at 12/13/2021, 08:08 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2584#issuecomment-996050046 at 12/16/2021, 09:58 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2584#issuecomment-996179156 at 12/16/2021, 12:42 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2584#issuecomment-996387158 at 12/16/2021, 06:35 PM PST
- Georgema20 closed as completed: https://github.com/hackforla/website/issues/2559#event-5782087807 at 12/16/2021, 06:37 PM PST
- Georgema20 issue closed by PR 2584: https://github.com/hackforla/website/issues/2087#event-5786162516 at 12/17/2021, 10:12 AM PST
- Georgema20 PR was merged: https://github.com/hackforla/website/pull/2584#event-5786162524 at 12/17/2021, 10:12 AM PST
- Georgema20 assigned: https://github.com/hackforla/website/issues/2544#issuecomment-989575961 at 12/22/2021, 11:35 AM PST
- Georgema20 opened: https://github.com/hackforla/website/pull/2620 at 12/22/2021, 12:28 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2620#issuecomment-1000937588 at 12/24/2021, 01:53 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2620#issuecomment-1000941319 at 12/24/2021, 02:28 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2620#issuecomment-1000941467 at 12/24/2021, 02:30 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2620#issuecomment-1000943060 at 12/24/2021, 02:49 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2620#issuecomment-1000960597 at 12/24/2021, 06:23 PM PST
- Georgema20 issue closed by PR 2620: https://github.com/hackforla/website/issues/2544#event-5816672764 at 12/26/2021, 10:27 PM PST
- Georgema20 PR was merged: https://github.com/hackforla/website/pull/2620#event-5816672769 at 12/26/2021, 10:27 PM PST
- Georgema20 assigned: https://github.com/hackforla/website/issues/2604#issuecomment-997490870 at 12/28/2021, 07:57 AM PST
- Georgema20 opened: https://github.com/hackforla/website/pull/2640 at 12/28/2021, 08:53 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2611#issuecomment-1002776157 at 12/29/2021, 01:06 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2611#issuecomment-1002776760 at 12/29/2021, 01:08 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2645#issuecomment-1003073608 at 12/30/2021, 07:20 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2640#issuecomment-1003225274 at 12/30/2021, 04:45 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2640#issuecomment-1003240687 at 12/30/2021, 06:09 PM PST
- Georgema20 submitted review: https://github.com/hackforla/website/pull/2645#pullrequestreview-842356148 at 01/01/2022, 11:38 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2645#issuecomment-1003607123 at 01/01/2022, 11:38 AM PST
- Georgema20 submitted review: https://github.com/hackforla/website/pull/2611#pullrequestreview-842356199 at 01/01/2022, 11:39 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2611#issuecomment-1003607241 at 01/01/2022, 11:39 AM PST
- Georgema20 PR was closed: https://github.com/hackforla/website/pull/2640#event-5832150541 at 01/01/2022, 03:46 PM PST
- Georgema20 unassigned: https://github.com/hackforla/website/issues/2604#issuecomment-1003637667 at 01/01/2022, 03:53 PM PST
- Georgema20 assigned: https://github.com/hackforla/website/issues/2598#issuecomment-997095473 at 01/04/2022, 07:47 AM PST
- Georgema20 opened: https://github.com/hackforla/website/pull/2665 at 01/06/2022, 07:45 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2665#issuecomment-1010443344 at 01/11/2022, 03:01 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2665#issuecomment-1017017775 at 01/19/2022, 05:08 PM PST
- Georgema20 issue closed by PR 2665: https://github.com/hackforla/website/issues/2598#event-5927247589 at 01/20/2022, 10:30 AM PST
- Georgema20 PR was merged: https://github.com/hackforla/website/pull/2665#event-5927247618 at 01/20/2022, 10:30 AM PST
- Georgema20 assigned: https://github.com/hackforla/website/issues/2604#issuecomment-1003637667 at 01/20/2022, 07:09 PM PST
- Georgema20 unassigned: https://github.com/hackforla/website/issues/2604#issuecomment-1003637667 at 01/20/2022, 07:09 PM PST
- Georgema20 assigned: https://github.com/hackforla/website/issues/2604#issuecomment-1003637667 at 01/20/2022, 07:31 PM PST
- Georgema20 opened: https://github.com/hackforla/website/pull/2710 at 01/20/2022, 07:34 PM PST
- Georgema20 submitted review: https://github.com/hackforla/website/pull/2696#pullrequestreview-859081217 at 01/20/2022, 07:42 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/issues/2559#issuecomment-1018776842 at 01/21/2022, 10:57 AM PST
- Georgema20 closed as completed: https://github.com/hackforla/website/issues/2559#event-5934126770 at 01/21/2022, 10:58 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/issues/2559#issuecomment-1019382859 at 01/22/2022, 04:21 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2718#issuecomment-1022552907 at 01/26/2022, 11:59 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2710#issuecomment-1022553226 at 01/26/2022, 11:59 AM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2710#issuecomment-1022590352 at 01/26/2022, 12:49 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/pull/2718#issuecomment-1022598849 at 01/26/2022, 01:02 PM PST
- Georgema20 issue closed by PR 2710: https://github.com/hackforla/website/issues/2604#event-5974796378 at 01/29/2022, 01:01 AM PST
- Georgema20 PR was merged: https://github.com/hackforla/website/pull/2710#event-5974796380 at 01/29/2022, 01:01 AM PST
- Georgema20 assigned: https://github.com/hackforla/website/issues/2391#issuecomment-1024815778 at 02/02/2022, 01:41 PM PST
- Georgema20 commented on: https://github.com/hackforla/website/issues/2391#issuecomment-1028553242 at 02/02/2022, 06:51 PM PST
- Georgema20 unassigned: https://github.com/hackforla/website/issues/2391#issuecomment-1059719546 at 03/05/2022, 12:19 AM PST
- Georgema20 issue closed as completed: https://github.com/hackforla/website/issues/2559#event-6189072353 at 03/05/2022, 12:23 AM PST
