### ISSUE TITLE
Pre-work Checklist: Developer: Shantanu Shende

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2560]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [ ] Once you take a good first issue, please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [ ] Once all tasks are completed, close this issue

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@shantanushende: Thanks for finishing up with this checklist. Please feel free to pick up a good first issue from the prioritized backlog column. Let me know if you have any questions. Or you can post in our slack channel.

**Comment by ExperimentsInHonesty** [comment]
@shantanushende please add a label for front end or backend or both.  Depending on what is appropriate for you.

**Comment by shantanushende** [comment]
Hey Bonnie,
legally I need to report my employment to my international student services
before I start work. For that, I need an offer letter. I have attached the
request below!

https://github.com/hackforla/governance/issues/61#issuecomment-992626831

Thank You
Shantanu Shende

**Comment by SAUMILDHANKAR** [comment]
@shantanushende: Hi Shantanu, I am planning to close this issue, since haven't heard from you in a while. If you want you can work on it later based on availability. I left a message for you on Slack stating the same. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@shantanushende 

Hey Shantanu,

You wrote that you needed an offer letter from Hack for LA back on January 3. I am really sorry we overlooked your request for an offer letter. If you are still interested in volunteering for Hack for LA, please respond to this message and we can get you an offer letter.

Sincerely,
Jessica Cheng

**Comment by JessicaLucindaCheng** [comment]
I haven't heard back from Shantanu, so I will be closing this pre-work checklist for now.

**Comment by HackforLABot** [comment]
## Activity Log: shantanushende
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- shantanushende assigned: https://github.com/hackforla/website/issues/2560 at 12/07/2021, 08:02 PM PST
- shantanushende closed as completed: https://github.com/hackforla/website/issues/2560#event-5745135278 at 12/09/2021, 07:08 PM PST
- shantanushende commented on: https://github.com/hackforla/website/issues/2560#issuecomment-1004525707 at 01/03/2022, 08:44 PM PST
- shantanushende issue closed as completed: https://github.com/hackforla/website/issues/2560#event-6013212644 at 02/04/2022, 11:38 PM PST
- shantanushende issue closed as completed: https://github.com/hackforla/website/issues/2560#event-6189838936 at 03/05/2022, 12:29 PM PST
