### ISSUE TITLE
Pre-work Checklist: Researcher: Summer Harvey

### ISSUE THREAD

**Issue by summerharveyux** [hackforla/website#2562]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new researcher on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the research team lead
- [x]  (once added to the drive) Add yourself to the team roster.
- [x]  Confirm with the research team lead that they have added you to the meeting invites and Github repo
- [x]  Confirm that the research team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings:
   - UX weekly team meeting, Thursdays 5 pm PST
   - All team meetings (UX, Development, Product), Sunday 10 am PST
   - Research team meetings, Wednesdays, 2:00 pm PST
- [x] Review the  [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) to see what Research Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Meet with team lead to receive first assignment
- [x] Once you accept an assignment (issue), please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
provide update
1. Progress
2. Blockers
3. Availability
4. ETA
```

### Resources/Instructions
- [Project Board filtered to show role: user research](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149)
- [Googledrive-UI/UX](https://drive.google.com/drive/folders/1Jq24FlOJTEmRD09M5xOgpWuHcKswH5Dk)
- [Googledrive-HackforLA website](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT)
- [UX Research Presentations](https://drive.google.com/drive/folders/1yV9YRrjVKmVLU_xSM_BjtdIaNITRhP5j)
- [Weekly Meeting Agendas](https://github.com/hackforla/website/issues/2106)

**Comment by t-will-gillis** [comment]
- Replace by #2562

**Comment by HackforLABot** [comment]
## Activity Log: summerharveyux
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- summerharveyux opened: https://github.com/hackforla/website/issues/2499 at 11/17/2021, 02:18 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2499#issuecomment-984138654 at 12/01/2021, 03:05 PM PST
- summerharveyux opened: https://github.com/hackforla/website/issues/2562 at 12/08/2021, 02:07 PM PST
- summerharveyux assigned: https://github.com/hackforla/website/issues/2562#issuecomment-989265799 at 12/08/2021, 02:09 PM PST
- summerharveyux assigned: https://github.com/hackforla/website/issues/2537#issuecomment-989182930 at 12/08/2021, 02:42 PM PST
- summerharveyux closed as completed: https://github.com/hackforla/website/issues/2498#event-5744650688 at 12/09/2021, 04:56 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2527#issuecomment-990488510 at 12/09/2021, 05:21 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-990494850 at 12/09/2021, 05:26 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-993029763 at 12/13/2021, 04:17 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-995253791 at 12/15/2021, 02:11 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-998401672 at 12/20/2021, 05:47 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-1006142801 at 01/05/2022, 02:57 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-1011525708 at 01/12/2022, 02:59 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-1016928630 at 01/19/2022, 02:25 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2498#issuecomment-1016956292 at 01/19/2022, 03:13 PM PST
- summerharveyux issue closed as completed: https://github.com/hackforla/website/issues/2499#event-5927926277 at 01/20/2022, 12:42 PM PST
- summerharveyux assigned: https://github.com/hackforla/website/issues/2499#event-5927926277 at 01/20/2022, 01:14 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-1022672205 at 01/26/2022, 02:45 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-1022703780 at 01/26/2022, 03:40 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-1027425303 at 02/01/2022, 04:20 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-1034276082 at 02/09/2022, 02:47 PM PST
- summerharveyux assigned: https://github.com/hackforla/website/issues/2763#event-6047300984 at 02/14/2022, 02:06 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2537#issuecomment-1039622090 at 02/14/2022, 02:11 PM PST
- summerharveyux closed as completed: https://github.com/hackforla/website/issues/2537#event-6070565997 at 02/14/2022, 02:11 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1039631114 at 02/14/2022, 02:21 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1047313036 at 02/21/2022, 04:15 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1048102474 at 02/22/2022, 10:44 AM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1048309242 at 02/22/2022, 03:29 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1048310042 at 02/22/2022, 03:30 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2498#issuecomment-1049282151 at 02/23/2022, 02:35 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1057341247 at 03/02/2022, 12:20 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1063453606 at 03/09/2022, 02:43 PM PST
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1069662903 at 03/16/2022, 02:41 PM PDT
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1069680825 at 03/16/2022, 03:06 PM PDT
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1076821602 at 03/23/2022, 02:07 PM PDT
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1083625776 at 03/30/2022, 02:07 PM PDT
- summerharveyux issue closed as completed: https://github.com/hackforla/website/issues/2562#event-6392121449 at 04/07/2022, 02:18 PM PDT
- summerharveyux commented on: https://github.com/hackforla/website/issues/2763#issuecomment-1104438812 at 04/20/2022, 01:43 PM PDT
