### ISSUE TITLE
Pre-work Checklist: Designer: Zoe Zhong

### ISSUE THREAD

**Issue by zzhoje** [hackforla/website#2563]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the team lead
- [x] (once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Confirm with the team lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [x] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings: 
   - [x] UX weekly team meeting, Thursdays 5pm PST
   - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Review the prioritized Backlog to see what Design Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [x] Once you accept an assignment (issue), please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
provide update
1. Progress
2. Blockers
3. Availability
4. ETA
```
### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by zzhoje** [comment]
1. Progress: complete
2. Blockers
3. Availability
4. ETA

**Comment by HackforLABot** [comment]
## Activity Log: zzhoje
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- zzhoje opened: https://github.com/hackforla/website/issues/2563 at 12/08/2021, 02:40 PM PST
- zzhoje assigned: https://github.com/hackforla/website/issues/2563#issuecomment-989285350 at 12/08/2021, 02:49 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2563#issuecomment-989299047 at 12/08/2021, 03:06 PM PST
- zzhoje closed as completed: https://github.com/hackforla/website/issues/2563#event-5737130748 at 12/08/2021, 03:06 PM PST
- zzhoje assigned: https://github.com/hackforla/website/issues/2066 at 12/11/2021, 07:41 AM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2066#issuecomment-991927959 at 12/12/2021, 08:26 AM PST
- zzhoje assigned: https://github.com/hackforla/website/issues/2585#issuecomment-993026293 at 12/13/2021, 04:14 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2066#issuecomment-993074700 at 12/13/2021, 05:38 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2585#issuecomment-993075483 at 12/13/2021, 05:40 PM PST
- zzhoje assigned: https://github.com/hackforla/website/issues/2608#issuecomment-997465987 at 12/20/2021, 04:08 PM PST
- zzhoje unassigned: https://github.com/hackforla/website/issues/2066#issuecomment-993074700 at 12/20/2021, 04:30 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2585#issuecomment-998385932 at 12/20/2021, 05:07 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2585#issuecomment-1002371597 at 12/28/2021, 06:56 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2585#issuecomment-1004349612 at 01/03/2022, 12:48 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2585#issuecomment-1008521414 at 01/09/2022, 07:51 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2585#issuecomment-1019626593 at 01/23/2022, 05:19 PM PST
- zzhoje issue closed as completed: https://github.com/hackforla/website/issues/2585#event-5946337041 at 01/24/2022, 04:26 PM PST
- zzhoje commented on: https://github.com/hackforla/website/issues/2481#issuecomment-1094299544 at 04/10/2022, 08:42 AM PDT
- zzhoje unassigned: https://github.com/hackforla/website/issues/2608#issuecomment-998361894 at 06/04/2023, 11:58 AM PDT
