### ISSUE TITLE
HfLA: Content/PM Agenda and Notes

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2608]
### Dependency
- When we are ready to bring content person back to the team.  There should be another issue for recruiting a content lead that will be the dependency for this issue.

### Overview
This issue tracks the agenda and notes for the Content/PM/Org meeting

### Action Items
- [ ] Add the Date of the next meeting below
- [ ] Link the Agenda/Notes from meeting

#### Template
```
## [DATE] Meeting Agenda and Notes

### Prework to prep for meeting
- [ ] Review the QA
   - [ ] Prework issues: Add notes to this meeting agenda as a discussion or FYI item (if no action needs to be taken).
     - [ ] Check to see how new team members are doing 
       - [ ] [UX writing](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+writing%22#column-15490305)
     - [ ] Can we improve the prework template based on something we see as a pattern?  

### Role Call (who is here)

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column for 
    - [ ] [UX Writing](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+writing%22#column-15235217)
    - [ ] [Product] - that are related to writing
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/website/issues/assigned/ExperimentsInHonesty)
       - [ ] [Zoe](https://github.com/hackforla/website/issues?q=assignee%3Azzhoje+is%3Aopen)

### New Items 
add issue numbers to be discussed and any notes that will be helpful


### Notes from meeting

### Tasks

### Items for next week's agenda
```

**Comment by ExperimentsInHonesty** [comment]
## 2021-12-20 Meeting Agenda and Notes

### Prework to prep for meeting
- [x] Review the QA
   - [x] Prework issues: Add notes to this meeting agenda as a discussion or FYI item (if no action needs to be taken).
     - [x] Check to see how new team members are doing 
       - [x] [UX writing](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+writing%22#column-15490305)
     - [x] Can we improve the prework template based on something we see as a pattern?  

### Role Call (who is here)
Zoe, Bonnie

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [x] review any issues that are in the new issue approval column for 
    - [x] [UX Writing](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+writing%22#column-15235217)
    - [x] [Product] - that are related to writing
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/website/issues/assigned/ExperimentsInHonesty)
       - [ ] [Zoe](https://github.com/hackforla/website/issues?q=assignee%3Azzhoje+is%3Aopen)

### New Items 
add issue numbers to be discussed and any notes that will be helpful
- [ ] review the content on the cards and replace where necessary https://www.hackforla.org/citizen-engagement

### Notes from meeting
- Reviewed the accomplishments, and Bonnie added some notes (got through about half of them)
- Talked about prework issue review (what we are looking for)

### Tasks

### Items for next week's agenda

**Comment by ExperimentsInHonesty** [comment]
## 2022-01-03 Meeting Agenda and Notes

### Prework to prep for meeting
- [ ] Review the QA
   - [ ] Prework issues: Add notes to this meeting agenda as a discussion or FYI item (if no action needs to be taken).
     - [ ] Check to see how new team members are doing 
       - [ ] [UX writing](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+writing%22#column-15490305)
     - [ ] Can we improve the prework template based on something we see as a pattern?  

### Role Call (who is here)

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column for 
    - [ ] [UX Writing](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+writing%22#column-15235217)
    - [ ] [Product] - that are related to writing
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/website/issues/assigned/ExperimentsInHonesty)
       - [ ] [Zoe](https://github.com/hackforla/website/issues?q=assignee%3Azzhoje+is%3Aopen)

### Carried over from last meeting
- [ ] review the content on the cards and replace where necessary https://www.hackforla.org/citizen-engagement

### New Items 
add issue numbers to be discussed and any notes that will be helpful
- [ ] Discuss what writing needs to be done in order to launch the homepage https://github.com/hackforla/website/issues/2481


### Notes from meeting

### Tasks

### Items for next week's agenda
