### ISSUE TITLE
Pre-work Checklist: Developer: Patrick McGuigan

### ISSUE THREAD

**Issue by pattshreds** [hackforla/website#2636]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [ ] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [ ] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please post the following as a comment in your new issue as well as in all the subsequent issues that you pick up or are assigned to:
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [x] Once all tasks are completed, close this issue

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@pattshreds: Hi Patrick, please assign this issue to yourself. Further, once you have given a progress report on an issue (other than your newly assigned status), then you can check off the box above and close this issue.  See the following section above

- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```

Reopening this issue for now. Thanks.

**Comment by HackforLABot** [comment]
## Activity Log: pattshreds
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- pattshreds opened: https://github.com/hackforla/website/issues/2636 at 12/27/2021, 07:38 PM PST
- pattshreds assigned: https://github.com/hackforla/website/issues/2633#issuecomment-1001466319 at 01/16/2022, 08:44 PM PST
- pattshreds unassigned: https://github.com/hackforla/website/issues/2633#issuecomment-1001466319 at 01/17/2022, 09:40 AM PST
- pattshreds assigned: https://github.com/hackforla/website/issues/2627#issuecomment-1013828431 at 01/17/2022, 10:11 AM PST
- pattshreds commented on: https://github.com/hackforla/website/issues/2627#issuecomment-1014791079 at 01/17/2022, 10:12 AM PST
- pattshreds opened: https://github.com/hackforla/website/pull/2693 at 01/17/2022, 11:00 AM PST
- pattshreds closed by PR 2693: https://github.com/hackforla/website/issues/2627#event-5906340621 at 01/17/2022, 11:03 AM PST
- pattshreds reopened: https://github.com/hackforla/website/issues/2627#event-5906340621 at 01/17/2022, 11:04 AM PST
- pattshreds closed as completed: https://github.com/hackforla/website/issues/2636#event-5906348988 at 01/17/2022, 11:05 AM PST
- pattshreds issue closed by PR 2693: https://github.com/hackforla/website/issues/2627#event-5915140451 at 01/18/2022, 09:22 PM PST
- pattshreds PR was merged: https://github.com/hackforla/website/pull/2693#event-5915140467 at 01/18/2022, 09:22 PM PST
- pattshreds assigned: https://github.com/hackforla/website/issues/2636#issuecomment-1017059806 at 01/22/2022, 10:12 AM PST
- pattshreds assigned: https://github.com/hackforla/website/issues/2657#issuecomment-1005324750 at 01/22/2022, 10:39 AM PST
- pattshreds unassigned: https://github.com/hackforla/website/issues/2657#issuecomment-1019337301 at 01/22/2022, 10:52 AM PST
- pattshreds assigned: https://github.com/hackforla/website/issues/2619#issuecomment-1003752150 at 01/22/2022, 10:58 AM PST
- pattshreds commented on: https://github.com/hackforla/website/issues/2619#issuecomment-1019360401 at 01/22/2022, 01:23 PM PST
- pattshreds assigned: https://github.com/hackforla/website/issues/2084 at 01/22/2022, 10:15 PM PST
- pattshreds commented on: https://github.com/hackforla/website/issues/2084#issuecomment-1019423681 at 01/22/2022, 10:18 PM PST
- pattshreds commented on: https://github.com/hackforla/website/issues/2084#issuecomment-1020230645 at 01/24/2022, 07:37 AM PST
- pattshreds issue closed as completed: https://github.com/hackforla/website/issues/2619#event-5945877919 at 01/24/2022, 02:23 PM PST
- pattshreds commented on: https://github.com/hackforla/website/issues/2084#issuecomment-1022268701 at 01/26/2022, 06:49 AM PST
- pattshreds opened: https://github.com/hackforla/website/pull/2723 at 01/28/2022, 06:39 AM PST
- pattshreds closed as completed: https://github.com/hackforla/website/issues/2636#event-5975493081 at 01/29/2022, 12:24 PM PST
- pattshreds commented on: https://github.com/hackforla/website/pull/2723#issuecomment-1076978032 at 03/23/2022, 06:30 PM PDT
- pattshreds merged: https://github.com/hackforla/website/pull/2723#event-6371752163 at 04/05/2022, 07:26 AM PDT
- pattshreds reopened: https://github.com/hackforla/website/pull/2723#event-6371752163 at 04/05/2022, 07:26 AM PDT
- pattshreds commented on: https://github.com/hackforla/website/pull/2723#issuecomment-1088780795 at 04/05/2022, 07:28 AM PDT
- pattshreds commented on: https://github.com/hackforla/website/pull/2723#issuecomment-1104000058 at 04/20/2022, 07:27 AM PDT
- pattshreds issue closed by PR 2723: https://github.com/hackforla/website/issues/2084#event-6697414823 at 05/28/2022, 11:02 AM PDT
