### ISSUE TITLE
Pre-work Checklist: Developer: Gabriel Garcia

### ISSUE THREAD

**Issue by Garcia1416** [hackforla/website#2638]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [ ] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [ ] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please post the following as a comment in your new issue as well as in all the subsequent issues that you pick up or are assigned to:
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [x] Once all tasks are completed, close this issue

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@Gorck1416 good progress on this issue. Please move this issue from new issue approval column to the [in progress (actively working)](https://github.com/hackforla/website/projects/7#column-7198228) column. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@Gorck1416 Also, please assign this pre-work issue to yourself. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@Gorck1416: Hi Gabriel, I am planning to close this issue, since haven't heard from you in a while. If you want you can work on it later based on availability. I left a message for you on Slack stating the same. Thank you.

**Comment by Garcia1416** [comment]
Progress: I need to start my first issue and a weekly report in the comment section.
    Blockers: No blockers
    Availability: I will have 4 hours to complete this task
    ETA: I expect to have this issue completed in 2 days
    Pictures: n/a

**Comment by Garcia1416** [comment]
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
        I have submitted my first pull request. All I need to do is close this issue.
    2. Blockers: "Difficulties or errors encountered."
         No blockers.
    3. Availability: "How much time will you have this week to work on this issue?"
        I will have 6 hours to complete this issue.
    4. ETA: "When do you expect this issue to be completed?"
        I expect to complete this issue today
    5. Pictures: "Add any pictures of the visual changes made to the site so far."
        N/A

**Comment by JessicaLucindaCheng** [comment]
@Gorck1416 I'm reopening this issue and unchecking the weekly update box because you haven't put a progress update in an issue you are working on (not including this pre-work issue). This weekly update should occur every week you are working on an issue.

- [ ] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```

**Comment by SAUMILDHANKAR** [comment]
@Gorck1416 Hope you are doing well. Just wanted to share one of the decisions made during our team meeting. We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis. I will leave a message for you on slack as well. Thank you.

**Comment by Garcia1416** [comment]
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
    I have completed my first issue. I need to have an issue and post a weekly update to complete the last task.
2. Blockers: "Difficulties or errors encountered."
     No blockers.
3. Availability: "How much time will you have this week to work on this issue?"
    I will have 5 hours a week to complete this issue.
4. ETA: "When do you expect this issue to be completed?"
    I expect to complete this issue the following week when I pick up an issue this week.
5. Pictures: "Add any pictures of the visual changes made to the site so far."
    N/A

**Comment by Garcia1416** [comment]
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
    I have completed my first issue. I need to have an issue and post a weekly update to complete the last task.
2. Blockers: "Difficulties or errors encountered."
     No blockers.
3. Availability: "How much time will you have this week to work on this issue?"
    I will have 2 hours a week to complete this issue.
4. ETA: "When do you expect this issue to be completed?"
    I expect to complete this issue the following week when I pick up an issue this week.
5. Pictures: "Add any pictures of the visual changes made to the site so far."
    N/A

**Comment by SAUMILDHANKAR** [comment]
@Gorck1416 Good job in finishing all the action items in this pre-work checklist (including the weekly progress report). Please check-off the pending action item and close this issue. Thank you.

**Comment by HackforLABot** [comment]
## Activity Log: Garcia1416
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Garcia1416 opened: https://github.com/hackforla/website/issues/2638 at 12/27/2021, 07:40 PM PST
- Garcia1416 assigned: https://github.com/hackforla/website/issues/2638#issuecomment-1018074008 at 01/21/2022, 08:01 AM PST
- Garcia1416 commented on: https://github.com/hackforla/website/issues/2638#issuecomment-1031122805 at 02/06/2022, 10:34 PM PST
- Garcia1416 assigned: https://github.com/hackforla/website/issues/2659#issuecomment-1005329755 at 02/08/2022, 01:30 AM PST
- Garcia1416 commented on: https://github.com/hackforla/website/issues/2659#issuecomment-1032397066 at 02/08/2022, 01:31 AM PST
- Garcia1416 assigned: https://github.com/hackforla/website/issues/2442#issuecomment-960300953 at 02/16/2022, 09:47 PM PST
- Garcia1416 commented on: https://github.com/hackforla/website/issues/2442#issuecomment-1042597711 at 02/16/2022, 09:48 PM PST
- Garcia1416 opened: https://github.com/hackforla/website/pull/2788 at 02/17/2022, 02:00 PM PST
- Garcia1416 unassigned: https://github.com/hackforla/website/issues/2659#issuecomment-1043672010 at 02/17/2022, 04:27 PM PST
- Garcia1416 commented on: https://github.com/hackforla/website/issues/2638#issuecomment-1044808947 at 02/18/2022, 08:40 AM PST
- Garcia1416 issue closed by PR 2788: https://github.com/hackforla/website/issues/2442#event-6103084670 at 02/18/2022, 02:50 PM PST
- Garcia1416 PR was merged: https://github.com/hackforla/website/pull/2788#event-6103084688 at 02/18/2022, 02:50 PM PST
- Garcia1416 closed as completed: https://github.com/hackforla/website/issues/2638#event-6106326804 at 02/19/2022, 11:19 AM PST
- Garcia1416 commented on: https://github.com/hackforla/website/issues/2638#issuecomment-1056175242 at 03/01/2022, 08:22 PM PST
- Garcia1416 assigned: https://github.com/hackforla/website/issues/2768#issuecomment-1037524345 at 03/11/2022, 04:49 PM PST
- Garcia1416 commented on: https://github.com/hackforla/website/issues/2638#issuecomment-1065754086 at 03/11/2022, 04:51 PM PST
- Garcia1416 commented on: https://github.com/hackforla/website/issues/2768#issuecomment-1066012174 at 03/12/2022, 07:10 PM PST
- Garcia1416 commented on: https://github.com/hackforla/website/pull/2973#issuecomment-1066146938 at 03/13/2022, 10:30 AM PDT
- Garcia1416 commented on: https://github.com/hackforla/website/issues/2768#issuecomment-1073173005 at 03/19/2022, 10:40 PM PDT
- Garcia1416 opened: https://github.com/hackforla/website/pull/2998 at 03/21/2022, 07:56 PM PDT
- Garcia1416 issue closed by PR 2998: https://github.com/hackforla/website/issues/2768#event-6285921875 at 03/22/2022, 11:41 AM PDT
- Garcia1416 PR was merged: https://github.com/hackforla/website/pull/2998#event-6285921891 at 03/22/2022, 11:41 AM PDT
- Garcia1416 closed as completed: https://github.com/hackforla/website/issues/2638#event-6314128565 at 03/27/2022, 12:16 PM PDT
