### ISSUE TITLE
Explore, document and make a new issue to implement linters which can be installed locally

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2651]
### Overview
In this issue, we will explore and implement linters which can be installed locally so that developers can identify errors before making a PR

### Action Items
- [x] Explore linters (Example: [Super-Linter](https://github.com/github/super-linter)) which can be used for HfLA website repo
- [x] Demo a use case in your local environment during the team meeting
- [x] Make sure the dev team can use the linter with VS code in their local environment
- [x] Write further issues to create documentation or a wiki article
- [x] Add instructions for other developers to follow
- [x] **For merge team**: Release dependency on #3230
  - [x] Update action items in the dependency issue if needed. 
  - [ ] If all dependencies in #3230 have been resolved, remove the dependency label, move it to the new issue approval column and add a ready for milestone label.
- [x] **For merge team**: Release dependency on #2695 
  - [x] Update action items in the dependency issue if needed. 
  - [ ] If all dependencies in these issues have been resolved, remove the dependency label, move it to the new issue approval column and add a ready for milestone label.
     - [ ] #1442
     - [ ] #2695 

### Resources/Instructions
* Helpful links: [VS code with linter](https://github.com/github/super-linter#visual-studio-code), [VS code remote container](https://code.visualstudio.com/docs/remote/containers)
* Related documentation: [Run linter locally](https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md)
* Nice read #1443

**Comment by bootcamp-brian** [comment]
ETA: 2 weeks (need to make a demo for team meeting and the next one isn't until the 14th)
Availability: Weekdays before 5pm

**Comment by ExperimentsInHonesty** [comment]
@bootcamp-brian I moved your issue to in progress.

**Comment by bootcamp-brian** [comment]
Provide Update
1. Progress: Did some research on linters and decided to test out ESLint. Went through set up in my local environment and confirmed it worked in VSCode. Did a write up of the set up process going step by step to prepare for presenting a demo.
2. Blockers: I don't know of a way to test if ESLint is compatible with a mac environment. I haven't seen anything saying that it isn't but also  haven't come across any confirmation that it does.
3. Availability: Weekdays before 5pm of next week
4. ETA: By end of next week

**Comment by bootcamp-brian** [comment]
Provide Update
1. Progress: Put together a demo to present at the meeting last Tuesday, but it was suggested that I wait until more of the merge team was in attendance to present it. The plan is to demo it at this Sunday's meeting instead. Also found confirmation that ESLint is compatible with macs.
2. Blockers: None
3. Availability: Weekdays before 5pm next week
4. ETA: By end of next week

**Comment by bootcamp-brian** [comment]
Provide Update
1. Progress: Presented demo, wrote documentation and created issue. Sent merge team member a message asking what I should do next and am currently awaiting a reply.
2. Unsure of next steps to take (already reached out for assistance)
3. Availability: Weekdays before 5pm
4. ETA: Within the next week.

**Comment by jdingeman** [comment]
This issue will make way for more issues. Dev created the decision record [here](https://github.com/hackforla/website/wiki/DR:-Exploring-linters-that-can-be-used-on-local-machines), also created new issue here:
- https://github.com/hackforla/website/issues/4264 for installing ESlint locally

Need new issues for:
- Roll out plan
  - What messages will need to be sent and where
    - Possible changes to GitHub actions and HackforLA bot to notify members of upcoming changes
- Update Contributing.md https://github.com/hackforla/website/issues/4264
- Create messaging for issues (Dev & prework), meetings, GHA messages on PRs

Dev has completed scope of work and we will close this issue. Thank you Brian!
