### ISSUE TITLE
Pre-work Checklist: Designer: Tammy

### ISSUE THREAD

**Issue by tamalatrinh** [hackforla/website#2654]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the team lead
- [x] (Once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Confirm with the team lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [x] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings: 
   - [x] UX weekly team meeting, Thursdays 5pm PST
   - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Review [Design_Short Term Goals, Plan, and Tasks](https://docs.google.com/document/d/1FxwgdnWBbbQ8Pi3tspnukZTWwXtqnRXfNkNhVMEloY0/edit)
- [x] Review the [Start Here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465) and [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) pages in Figma
- [x] Review the prioritized Backlog to see what Design Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Once you accept an assignment (issue), please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
provide update
1. Progress
2. Blockers
3. Availability
4. ETA
```
### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by IsaacDesigns** [comment]
H @tamalatrinh, it looks like you have two more task items to check off in this issue. Please complete them and close this issue when completed, thanks!

**Comment by IsaacDesigns** [comment]
@tamalatrinh this issue will have pages in the Resources/Instructions section that you can't find on the live H4LA site https://github.com/hackforla/website/issues/2512

**Comment by HackforLABot** [comment]
## Activity Log: tamalatrinh
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- tamalatrinh opened: https://github.com/hackforla/website/issues/2654 at 01/03/2022, 01:29 PM PST
- tamalatrinh assigned: https://github.com/hackforla/website/issues/2654#issuecomment-1004372286 at 01/03/2022, 01:56 PM PST
- tamalatrinh closed as completed: https://github.com/hackforla/website/issues/2654#event-5855451328 at 01/06/2022, 05:29 PM PST
- tamalatrinh assigned: https://github.com/hackforla/website/issues/2597#issuecomment-997088137 at 01/06/2022, 05:30 PM PST
- tamalatrinh commented on: https://github.com/hackforla/website/issues/2597#issuecomment-1007068514 at 01/06/2022, 05:33 PM PST
- tamalatrinh closed as completed: https://github.com/hackforla/website/issues/2654#event-5862698462 at 01/09/2022, 11:56 AM PST
- tamalatrinh commented on: https://github.com/hackforla/website/issues/2597#issuecomment-1010524700 at 01/11/2022, 05:03 PM PST
- tamalatrinh commented on: https://github.com/hackforla/website/issues/2597#issuecomment-1014922800 at 01/17/2022, 02:19 PM PST
- tamalatrinh closed as completed: https://github.com/hackforla/website/issues/2597#event-5907005546 at 01/17/2022, 02:19 PM PST
