### ISSUE TITLE
Pre-work Checklist: Developer: Frank Stepanski

### ISSUE THREAD

**Issue by frankstepanski** [hackforla/website#2660]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, please post the following as a comment in your new issue as well as in all the subsequent issues that you pick up or are assigned to:
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
- [x] Once all tasks are completed, close this issue

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@frankstepanski Hi Frank, good progress on this issue. Please move this issue from new issue approval column to the [in progress (actively working)](https://github.com/hackforla/website/projects/7#column-7198228) column. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@frankstepanski Also, please assign this pre-work issue to yourself. Thank you.

**Comment by SAUMILDHANKAR** [comment]
> @frankstepanski Hi Frank, good progress on this issue. Please move this issue from new issue approval column to the [in progress (actively working)](https://github.com/hackforla/website/projects/7#column-7198228) column. Thank you.

During the team meeting, we have decided that PM/Leadership team will move the Pre-work checklist issues from New Issue Approval column to In progress column. So, @frankstepanski you can ignore my previous comment. Thanks.

**Comment by frankstepanski** [comment]
Availability for this week:
My estimated ETA for completing this issue: Today

**UPDATE**
Progress: Have submitted a pull request. Awaiting approval
Blockers: None
Availability: Weeknights (EST) and Sunday
ETA: Completed
Pictures: https://github.com/hackforla/website/pull/2741

**Comment by SAUMILDHANKAR** [comment]
@frankstepanski This issue should remain open until you have provided a weekly progress report on any of your issue:
- [x] Weekly, please also provide an update on the issue
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
Feel free to check it off in the action items at the top and close the issue once you mark it complete. Reopening the issue for now.

**Comment by SAUMILDHANKAR** [comment]
@frankstepanski Hope you are doing well. Just wanted to share one of the decisions made during our team meeting. We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis. I will leave a message for you on slack as well. Thank you.

**Comment by SAUMILDHANKAR** [comment]
Received slack message from Frank, has an upcoming job interview next week. Would continue after that.

**Comment by frankstepanski** [comment]
UPDATE
Progress: Merged
Blockers: None
Availability: Weeknights (EST) and Sunday
ETA: Completed
Pictures: https://github.com/hackforla/website/pull/2741

**Comment by HackforLABot** [comment]
## Activity Log: frankstepanski
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- frankstepanski opened: https://github.com/hackforla/website/issues/2660 at 01/04/2022, 07:32 PM PST
- frankstepanski opened: https://github.com/hackforla/website/issues/2673 at 01/07/2022, 07:58 PM PST
- frankstepanski commented on: https://github.com/hackforla/website/issues/2673#issuecomment-1008156253 at 01/08/2022, 01:18 PM PST
- frankstepanski assigned: https://github.com/hackforla/website/issues/2673#issuecomment-1023707635 at 02/06/2022, 07:52 AM PST
- frankstepanski opened: https://github.com/hackforla/website/pull/2741 at 02/06/2022, 08:47 AM PST
- frankstepanski commented on: https://github.com/hackforla/website/issues/2660#issuecomment-1030871404 at 02/06/2022, 08:56 AM PST
- frankstepanski commented on: https://github.com/hackforla/website/issues/2673#issuecomment-1030872112 at 02/06/2022, 09:00 AM PST
- frankstepanski closed as completed: https://github.com/hackforla/website/issues/2666#event-6015324898 at 02/06/2022, 09:41 AM PST
- frankstepanski reopened: https://github.com/hackforla/website/issues/2666#event-6015324898 at 02/06/2022, 09:41 AM PST
- frankstepanski assigned: https://github.com/hackforla/website/issues/2591#issuecomment-995353120 at 02/06/2022, 11:00 AM PST
- frankstepanski unassigned: https://github.com/hackforla/website/issues/2591#issuecomment-995353120 at 02/06/2022, 11:00 AM PST
- frankstepanski assigned: https://github.com/hackforla/website/issues/2591#issuecomment-995353120 at 02/06/2022, 11:01 AM PST
- frankstepanski closed as completed: https://github.com/hackforla/website/issues/2660#event-6015418443 at 02/06/2022, 11:08 AM PST
- frankstepanski closed by PR 2741: https://github.com/hackforla/website/issues/2673#event-6015419445 at 02/06/2022, 11:09 AM PST
- frankstepanski opened: https://github.com/hackforla/website/pull/2742 at 02/06/2022, 11:39 AM PST
- frankstepanski commented on: https://github.com/hackforla/website/issues/2591#issuecomment-1030899957 at 02/06/2022, 11:41 AM PST
- frankstepanski closed by PR 2742: https://github.com/hackforla/website/issues/2591#event-6015453941 at 02/06/2022, 11:41 AM PST
- frankstepanski PR was merged: https://github.com/hackforla/website/pull/2741#event-6016628534 at 02/06/2022, 09:40 PM PST
- frankstepanski issue closed by PR 2742: https://github.com/hackforla/website/issues/2591#event-6016992433 at 02/06/2022, 11:18 PM PST
- frankstepanski PR was merged: https://github.com/hackforla/website/pull/2742#event-6016992439 at 02/06/2022, 11:18 PM PST
- frankstepanski assigned: https://github.com/hackforla/website/issues/2660#issuecomment-1031148862 at 02/28/2022, 01:26 AM PST
- frankstepanski commented on: https://github.com/hackforla/website/issues/2660#issuecomment-1073285595 at 03/20/2022, 09:27 AM PDT
- frankstepanski closed as completed: https://github.com/hackforla/website/issues/2660#event-6271414705 at 03/20/2022, 09:27 AM PDT
- frankstepanski commented on: https://github.com/hackforla/website/pull/2988#issuecomment-1073295508 at 03/20/2022, 10:20 AM PDT
- frankstepanski submitted review: https://github.com/hackforla/website/pull/2988#pullrequestreview-916579861 at 03/21/2022, 07:12 PM PDT
- frankstepanski assigned: https://github.com/hackforla/website/issues/2669#issuecomment-1065786460 at 03/26/2022, 10:29 AM PDT
- frankstepanski commented on: https://github.com/hackforla/website/issues/2669#issuecomment-1079751170 at 03/26/2022, 11:38 AM PDT
- frankstepanski commented on: https://github.com/hackforla/website/issues/2669#issuecomment-1079954782 at 03/27/2022, 08:33 AM PDT
- frankstepanski opened: https://github.com/hackforla/website/pull/3030 at 04/02/2022, 10:16 PM PDT
- frankstepanski commented on: https://github.com/hackforla/website/issues/2669#issuecomment-1086779054 at 04/02/2022, 10:19 PM PDT
- frankstepanski issue closed by PR 3030: https://github.com/hackforla/website/issues/2669#event-6372241803 at 04/05/2022, 08:24 AM PDT
- frankstepanski PR was merged: https://github.com/hackforla/website/pull/3030#event-6372241827 at 04/05/2022, 08:24 AM PDT
- frankstepanski closed as completed: https://github.com/hackforla/website/issues/1878#event-6474262247 at 04/21/2022, 02:51 PM PDT
- frankstepanski reopened: https://github.com/hackforla/website/issues/1878#event-6474262247 at 04/21/2022, 02:51 PM PDT
- frankstepanski assigned: https://github.com/hackforla/website/issues/3059#issuecomment-1104696934 at 05/14/2022, 01:15 PM PDT
- frankstepanski commented on: https://github.com/hackforla/website/issues/3059#issuecomment-1126805949 at 05/14/2022, 01:24 PM PDT
- frankstepanski commented on: https://github.com/hackforla/website/issues/3059#issuecomment-1132186162 at 05/19/2022, 01:40 PM PDT
- frankstepanski opened: https://github.com/hackforla/website/pull/3179 at 05/29/2022, 10:21 AM PDT
- frankstepanski commented on: https://github.com/hackforla/website/pull/3179#issuecomment-1213643104 at 08/12/2022, 08:27 PM PDT
- frankstepanski unassigned: https://github.com/hackforla/website/issues/3059#issuecomment-1140203060 at 08/19/2022, 02:10 PM PDT
- frankstepanski PR was closed: https://github.com/hackforla/website/pull/3179#event-7225076507 at 08/19/2022, 02:17 PM PDT
- frankstepanski unassigned: https://github.com/hackforla/website/issues/2673#issuecomment-1289853218 at 11/09/2022, 10:40 AM PST
