### ISSUE TITLE
Create a UXR Roadmap for HfLA Website 

### ISSUE THREAD

**Issue by sacamp** [hackforla/website#2679]
### Overview
We need to create a UXR roadmap in order to prioritize and communicate current and future UX research projects for the website.

### Action Items
- [x] Define scope: describe the high-level goal for the product (website).
- [x] Describe the current state of the research done on the product from the new content added to wiki #2680 
- [ ] Define themes: 
   - [ ] Key issues:
      - [x] problems which need to be solved by research
      - [ ] intended recipients of the UX work (end users, internal stakeholders, etc.)
   - [ ] Business objectives:
      - [ ] objectives and outcomes (success metrics) which will result from the research
   - [ ] Actions:
      - [ ] describe the high-level types of research work that will need to be done

### Resources/Instructions

- [Nielson Norman Group article on creating UX roadmaps](https://www.nngroup.com/articles/ux-roadmaps/)
- [How to build UX roadmaps](https://medium.com/design-ibm/how-to-build-a-compelling-ux-research-roadmap-227448005c82)
- [UX Research Roadmap Outline](https://docs.google.com/document/d/1yZTd2aWo-D4Dhd5y8bKLm7qp2XedxgdntoAQAR5oWGc/edit)

### Wiki pages
- [HfLA Research Team member](https://github.com/hackforla/website/wiki/UI-UX-Researcher)

### Examples from other projects
- [Internship project Research Overiew page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)

**Comment by sacamp** [comment]
Progress: Self-assigned the issue
Blockers: Need to acquire product roadmap (if any) to determine focus areas
Availability: 4+ hours
ETA: Wed. 2/23

**Comment by sacamp** [comment]
Progress: created an [outline](https://docs.google.com/document/d/1yZTd2aWo-D4Dhd5y8bKLm7qp2XedxgdntoAQAR5oWGc/edit) document, to discuss goals with product
Blockers: None
Availability: 1 hour Thurs, Fri, Sat
ETA: 3/2

**Comment by sacamp** [comment]
Progress: created an [outline](https://docs.google.com/document/d/1yZTd2aWo-D4Dhd5y8bKLm7qp2XedxgdntoAQAR5oWGc/edit) document, need to expand research methods
Blockers: None
Availability: 1 hour Thurs, Fri, Sat
ETA: 3/15

**Comment by phuonguvan** [comment]
@sacamp Hey! This is the team lead and I was wondering if you are still working on this project. Bonnie told me to update you guys so let me know as soon as possible!

**Comment by sacamp** [comment]
@phuonguvan hi! I’m the current UX research lead so yes I am still on the project

**Comment by sacamp** [comment]
Progress: Self-assigned the issue
Blockers: Need to acquire product roadmap (if any) to determine focus areas
Availability: 4+ hours
