### ISSUE TITLE
Design Lead Tasks

### ISSUE THREAD

**Issue by IsaacDesigns** [hackforla/website#2697]
### Overview
This is a list of tasks and issues create for the design lead to complete. It should be ordered from highest to least priority.

### Action Items
- [ ] Add tasks from weekly meeting agendas 
- [ ] Add issues that need to be created

### Tasks
- [ ] Make an issue to recruit another Design Lead
  - [x] [Posting](https://github.com/hackforla/UI-UX/projects/3#card-76736352) on Design Open Roles Board
- [x] Update the Wiki to onboard new Designers and Design lead
- [ ] Recruit and train new Design Lead
- [ ] Meet with Hanna of the Design System team to speak with Bonnie and Isaac about issue #2685 

### Issues to Create
- [ ] Create issues to create icons for Wins page: 
  - "I found a mentor(s)", 
  - "I got leadership experience"
  - Replacing star icon with something different that makes more sense
- [ ] Create separate issue templates for UX and UI Design issues. The UI design issues will include instructions for designers to update the Figma Design System with their new designs and create components or styles so that we can easily reuse them.
- [ ] I may create an issue to create user flows if I don't find any that have already been made.
- [ ] Figure out how to get this icon or replace it [1734](https://github.com/hackforla/website/issues/1734#issuecomment-1030883057)

### Resources/Instructions
[Design Team Goals](https://docs.google.com/document/d/1FxwgdnWBbbQ8Pi3tspnukZTWwXtqnRXfNkNhVMEloY0/edit)
[Design Lead Role and Responsibilities](https://docs.google.com/document/d/1htV6aEGzYtcc2rF1elTd560xTHowgUiPz_ziYGPk_-c/edit)
WIKI for designers: https://github.com/hackforla/website/wiki/UI-UX-Designer
