### ISSUE TITLE
Pre-work Checklist: Developer: Hiram Riddle

### ISSUE THREAD

**Issue by riddle015** [hackforla/website#2701]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" label to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will providing estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by riddle015** [comment]
Provide Update
1. Progress: "Just starting"
2. Blockers : "None"
3. Availability: 5 hours this week
4. ETA: 2/6

**Comment by JessicaLucindaCheng** [comment]
@riddle015 How are you doing on this pre-work checklist? Did you have any questions?

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Once you provide a progress report on #2238, you can check off the corresponding action line item in this issue. Thanks.

**Comment by SAUMILDHANKAR** [comment]
@riddle015: Just wanted to reach out and check if you are still available to work on your issues. Please let us know. Thanks.

**Comment by riddle015** [comment]
I'm still available. I'm being blocked by my good second issue. Will try to make it to office hours on Thursday to get help with it.

Thank you

Hiram

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Hi Hiram, I see that you have already provided weekly progress reports in your good second issue, so you can check off that action item at top. Also, feel free to close this issue if all the remaining items are complete. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Hello Hiram, Hope you are doing well. Just wanted to follow up if you are planning to pick up your next issue. Please let us know if your availability has changed. I will leave a slack message about the same as well. Thanks.

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Thanks for letting me know that you are planning to take up your next issue in the upcoming week. Also, wanted to check if the pending action items in this issue are complete. If yes, feel free to close this issue. Thanks.

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Hope you are doing well. Please let me know if you are still planning to pick up your next issue or your availability has changed. Will leave a slack message as well. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Hi Hiram, I noticed that the small issue that you last picked wasn't ready to be worked upon. Please pick your next small issue from the Prioritized Backlog column. Based on the role filter that you want to go for, it should be the top small issue in the Prioritized Backlog column once you filter by small issues. I can demo this for you in our next team meeting as well. Please let me know when you are planning to attend one. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Just a reminder to pick up your small issue next. Will leave a slack message as well. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Hi Hiram, jusr wanted to follow up on your pending action items above. You can check them off and close this issue if you are done with them. Also, please provide an update on #2952. Thank you.

**Comment by riddle015** [comment]
Completed all the items in the checklist!

Best,
Hiram

**Comment by HackforLABot** [comment]
## Activity Log: riddle015
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- riddle015 opened: https://github.com/hackforla/website/issues/2701 at 01/18/2022, 07:56 PM PST
- riddle015 assigned: https://github.com/hackforla/website/issues/2701#issuecomment-1016056363 at 01/18/2022, 08:03 PM PST
- riddle015 assigned: https://github.com/hackforla/website/issues/1564 at 01/18/2022, 11:05 PM PST
- riddle015 commented on: https://github.com/hackforla/website/issues/1564#issuecomment-1016146546 at 01/18/2022, 11:10 PM PST
- riddle015 opened: https://github.com/hackforla/website/pull/2714 at 01/23/2022, 05:05 PM PST
- riddle015 assigned: https://github.com/hackforla/website/issues/2238 at 01/23/2022, 05:23 PM PST
- riddle015 issue closed by PR 2714: https://github.com/hackforla/website/issues/1564#event-5967346975 at 01/27/2022, 03:23 PM PST
- riddle015 PR was merged: https://github.com/hackforla/website/pull/2714#event-5967346978 at 01/27/2022, 03:23 PM PST
- riddle015 commented on: https://github.com/hackforla/website/issues/2701#issuecomment-1028028791 at 02/02/2022, 07:01 AM PST
- riddle015 commented on: https://github.com/hackforla/website/issues/2238#issuecomment-1028035551 at 02/02/2022, 07:08 AM PST
- riddle015 commented on: https://github.com/hackforla/website/issues/2238#issuecomment-1046293957 at 02/20/2022, 10:21 AM PST
- riddle015 opened: https://github.com/hackforla/website/issues/2806 at 02/20/2022, 12:00 PM PST
- riddle015 commented on: https://github.com/hackforla/website/issues/2701#issuecomment-1066145718 at 03/13/2022, 10:22 AM PDT
- riddle015 commented on: https://github.com/hackforla/website/issues/2238#issuecomment-1066145835 at 03/13/2022, 10:23 AM PDT
- riddle015 commented on: https://github.com/hackforla/website/pull/2973#issuecomment-1066146856 at 03/13/2022, 10:30 AM PDT
- riddle015 opened: https://github.com/hackforla/website/pull/2995 at 03/20/2022, 03:26 PM PDT
- riddle015 issue closed by PR 2995: https://github.com/hackforla/website/issues/2238#event-6273326484 at 03/21/2022, 12:48 AM PDT
- riddle015 PR was merged: https://github.com/hackforla/website/pull/2995#event-6273326509 at 03/21/2022, 12:48 AM PDT
- riddle015 closed by PR 3961: https://github.com/hackforla/website/issues/2806#event-6313998924 at 03/27/2022, 10:19 AM PDT
- riddle015 assigned: https://github.com/hackforla/website/issues/3056#issuecomment-1100208451 at 04/17/2022, 01:33 PM PDT
- riddle015 unassigned: https://github.com/hackforla/website/issues/3056#issuecomment-1104392914 at 04/20/2022, 12:46 PM PDT
- riddle015 assigned: https://github.com/hackforla/website/issues/2952#issuecomment-1075792069 at 05/12/2022, 10:16 PM PDT
- riddle015 commented on: https://github.com/hackforla/website/issues/2952#issuecomment-1140492052 at 05/29/2022, 10:28 AM PDT
- riddle015 opened: https://github.com/hackforla/website/pull/3237 at 06/11/2022, 10:58 PM PDT
- riddle015 commented on: https://github.com/hackforla/website/issues/2952#issuecomment-1153080649 at 06/11/2022, 11:06 PM PDT
- riddle015 issue closed by PR 3237: https://github.com/hackforla/website/issues/2952#event-6815991567 at 06/15/2022, 01:37 PM PDT
- riddle015 PR was merged: https://github.com/hackforla/website/pull/3237#event-6815991591 at 06/15/2022, 01:37 PM PDT
- riddle015 commented on: https://github.com/hackforla/website/pull/3301#issuecomment-1166595198 at 06/26/2022, 10:28 AM PDT
- riddle015 opened: https://github.com/hackforla/website/issues/3305 at 06/26/2022, 10:58 AM PDT
- riddle015 opened: https://github.com/hackforla/website/issues/3311 at 06/26/2022, 11:53 AM PDT
- riddle015 assigned: https://github.com/hackforla/website/issues/2600#issuecomment-997282293 at 08/21/2022, 10:13 AM PDT
- riddle015 unassigned: https://github.com/hackforla/website/issues/2600#issuecomment-1261125508 at 10/02/2022, 11:47 AM PDT
