### ISSUE TITLE
Pre-work Checklist: Developer: Paul Yi

### ISSUE THREAD

**Issue by Pauljsyi** [hackforla/website#2716]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" or "role: back end" label*(s) to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will providing estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by Pauljsyi** [comment]
Progress:  Complete
Blockers: none
Availability: 
ETA: Friday
Pictures: N/A

**Comment by SAUMILDHANKAR** [comment]
@Pauljsyi: Great job in finishing up with all the items. Feel free to close this issue when you get a chance. Thanks.

**Comment by HackforLABot** [comment]
## Activity Log: Pauljsyi
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Pauljsyi opened: https://github.com/hackforla/website/issues/2716 at 01/24/2022, 07:59 PM PST
- Pauljsyi assigned: https://github.com/hackforla/website/issues/2716#issuecomment-1020786534 at 01/24/2022, 08:01 PM PST
- Pauljsyi assigned: https://github.com/hackforla/website/issues/2553#issuecomment-1023535713 at 01/28/2022, 11:17 AM PST
- Pauljsyi commented on: https://github.com/hackforla/website/issues/2553#issuecomment-1024532888 at 01/28/2022, 11:20 AM PST
- Pauljsyi commented on: https://github.com/hackforla/website/issues/2716#issuecomment-1024797340 at 01/28/2022, 05:20 PM PST
- Pauljsyi closed as completed: https://github.com/hackforla/website/issues/2716#event-5974343663 at 01/28/2022, 06:33 PM PST
- Pauljsyi unassigned: https://github.com/hackforla/website/issues/2553#issuecomment-1024532888 at 01/29/2022, 11:53 AM PST
- Pauljsyi opened: https://github.com/hackforla/website/pull/2725 at 01/29/2022, 12:24 PM PST
- Pauljsyi issue closed by PR 2725: https://github.com/hackforla/website/issues/2553#event-5978462578 at 01/30/2022, 10:52 PM PST
- Pauljsyi PR was merged: https://github.com/hackforla/website/pull/2725#event-5978462596 at 01/30/2022, 10:52 PM PST
- Pauljsyi assigned: https://github.com/hackforla/website/issues/2240 at 02/01/2022, 05:17 PM PST
- Pauljsyi commented on: https://github.com/hackforla/website/issues/2240#issuecomment-1027500462 at 02/01/2022, 05:52 PM PST
- Pauljsyi opened: https://github.com/hackforla/website/pull/2732 at 02/02/2022, 11:58 AM PST
- Pauljsyi assigned: https://github.com/hackforla/website/issues/2669#issuecomment-1007374781 at 02/02/2022, 12:03 PM PST
- Pauljsyi commented on: https://github.com/hackforla/website/issues/2669#issuecomment-1029563962 at 02/03/2022, 05:45 PM PST
- Pauljsyi opened: https://github.com/hackforla/website/pull/2736 at 02/03/2022, 06:33 PM PST
- Pauljsyi issue closed by PR 2732: https://github.com/hackforla/website/issues/2240#event-6007374327 at 02/03/2022, 10:09 PM PST
- Pauljsyi PR was merged: https://github.com/hackforla/website/pull/2732#event-6007374336 at 02/03/2022, 10:09 PM PST
- Pauljsyi commented on: https://github.com/hackforla/website/pull/2736#issuecomment-1031933975 at 02/07/2022, 01:17 PM PST
- Pauljsyi PR was closed: https://github.com/hackforla/website/pull/2736#event-6228985234 at 03/11/2022, 05:49 PM PST
- Pauljsyi unassigned: https://github.com/hackforla/website/issues/2669#issuecomment-1065786460 at 03/11/2022, 05:56 PM PST
- Pauljsyi assigned: https://github.com/hackforla/website/issues/3026#issuecomment-1086584020 at 05/17/2022, 04:31 PM PDT
- Pauljsyi unassigned: https://github.com/hackforla/website/issues/3026#issuecomment-1166584104 at 06/26/2022, 09:44 AM PDT
