### ISSUE TITLE
Remove unused alt-hero in project md files

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2722]
### Dependency
- [x] https://github.com/hackforla/website/issues/3209
- [x] https://github.com/hackforla/website/issues/2891
- [x] https://github.com/hackforla/website/issues/2892
- [x] https://github.com/hackforla/website/issues/2920
- [x] https://github.com/hackforla/website/issues/2921
- [x] https://github.com/hackforla/website/issues/2922
- [x] https://github.com/hackforla/website/issues/2923
- [x] https://github.com/hackforla/website/issues/2924
- [x] https://github.com/hackforla/website/issues/2925
- [x] https://github.com/hackforla/website/issues/2926
- [x] https://github.com/hackforla/website/issues/2927
- [x] https://github.com/hackforla/website/issues/3194
- [x] https://github.com/hackforla/website/issues/3195
- [x] https://github.com/hackforla/website/issues/3196
- [x] https://github.com/hackforla/website/issues/3197
- [x] https://github.com/hackforla/website/issues/3198
- [x] https://github.com/hackforla/website/issues/3199
- [x] https://github.com/hackforla/website/issues/3200
- [x] https://github.com/hackforla/website/issues/3201
- [x] https://github.com/hackforla/website/issues/3202
- [x] https://github.com/hackforla/website/issues/3203
- [x] https://github.com/hackforla/website/issues/3204
- [x] https://github.com/hackforla/website/issues/3205
- [x] https://github.com/hackforla/website/issues/3206
- [x] https://github.com/hackforla/website/issues/3207
- [x] https://github.com/hackforla/website/issues/3208
- [x] https://github.com/hackforla/website/issues/3210
- [x] https://github.com/hackforla/website/issues/3211
- [x] https://github.com/hackforla/website/issues/3212
- [x] https://github.com/hackforla/website/issues/3213
- [x] https://github.com/hackforla/website/issues/3214
- [x] https://github.com/hackforla/website/issues/3215
- [x] https://github.com/hackforla/website/issues/3216

### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

For this epic, we will write issues to remove the `alt-hero` field in the project md files, which will be added as Dependency items above.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.  

Developers will write issues for this epic by following the "Instructions for Developers" in the [Instructions tab of the HfLA-Website: Remove unused alt-hero field from project mds Google Sheet](https://docs.google.com/spreadsheets/d/1IeF3UdS9cpg33ChTxJi7YSv0n-fc1MsQF2Mvo5V0npE/edit#gid=2051410398) and using the [Project md file: Removing unused `alt-hero` field issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Good+second+issue%2C+size%3A+1pt&template=project-md-file--removing-unused--alt-hero--field.md&title=Remove+unused+%60alt-hero%60+field+from+%5BINSERT+FILE+NAME+HERE%5D.md+project+file). After an issue is created, the technical lead(s) will review each issue by following the "Instructions for Technical Leads" in the [Instructions tab of the HfLA-Website: Remove unused alt-hero field from project mds Google Sheet](https://docs.google.com/spreadsheets/d/1IeF3UdS9cpg33ChTxJi7YSv0n-fc1MsQF2Mvo5V0npE/edit#gid=2051410398).

### Action Items
- [x] Write issues for this epic. See this spreadsheet [HfLA-Website: Remove unused alt-hero field from project mds Google Sheet](https://docs.google.com/spreadsheets/d/1IeF3UdS9cpg33ChTxJi7YSv0n-fc1MsQF2Mvo5V0npE/edit#gid=2051410398) and the issues that need to be written.
- [x] Once all the issues in the Dependency section are checked off and closed, use the search function in your IDE to check the following for the .md files in [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects):
  - [ ] There is _**no**_ `alt-hero:` field in any of the `.md` files in [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects). (If you are using VSCode as your IDE, you can search for `alt-hero:` and restrict the search by filling in the "files to include" field with `_projects`. Other IDEs may have similar search capabilities.)
    - [x] If you find any `alt-hero:` fields in any of the `.md` files in [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects), list the .md file(s) you found them in in a new comment below.
      - [x] Then reach out to the [merge team and technical leads](https://github.com/hackforla/website/wiki/Meet-the-Team) to help you write issues to fix what you found.
    - [ ] If you find _**no**_ `alt-hero:` fields in any of the `.md` files  in [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects), then in a new comment below say you found no `alt-hero:` fields and close the issue.

### Resources/Instructions
- Google Sheet with instructions to write the issue and to track issue creation: [HfLA-Website: Remove unused alt-hero field from project mds Google Sheet](https://docs.google.com/spreadsheets/d/1IeF3UdS9cpg33ChTxJi7YSv0n-fc1MsQF2Mvo5V0npE/edit#gid=2051410398)
- Issue template to use: [Project md file: Removing unused `alt-hero` field](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Good+second+issue%2C+size%3A+1pt&template=project-md-file--removing-unused--alt-hero--field.md&title=Remove+unused+%60alt-hero%60+field+from+%5BINSERT+FILE+NAME+HERE%5D.md+project+file)
- Directory to find project md files: [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects)

**Accessibility information**
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

**Comment by JessicaLucindaCheng** [comment]
- Progress: Some of the issues related to the epic have been written
- Blockers: None
- Availability: None this week for this issue
- ETA: April 25, 2022

**Comment by JessicaLucindaCheng** [comment]
- Progress: Some of the issues related to the epic have been written. After I finalize the individual issue format in terms of dependencies, I may put this back into the prioritized backlog for someone else to work on.
- Blockers: None
- Availability: Not sure
- ETA: April 25, 2022

**Comment by JessicaLucindaCheng** [comment]
Progress: Some of the issues related to the epic have been written. After I finalize the individual issue format in terms of dependencies, I may put this back into the prioritized backlog for someone else to work on.
Blockers: None
Availability: Not sure
ETA: April 27, 2022

**Comment by JessicaLucindaCheng** [comment]
Progress: Some of the issues related to the epic have been written. After I finalize the individual issue format in terms of dependencies, I may put this back into the prioritized backlog for someone else to work on.
Blockers: None
Availability: Not sure
ETA: Hopefully, May 14, 2022

**Comment by JessicaLucindaCheng** [comment]
Progress: Some of the issues related to the epic have been written. After I finalize the individual issue format in terms of dependencies, I may put this back into the prioritized backlog for someone else to work on.
Blockers: None
Availability: Not sure
ETA: July 9, 2022

**Comment by JessicaLucindaCheng** [comment]
All issues have been written for this epic.

**Comment by JessicaLucindaCheng** [comment]
I pulled this out of the Ice Box because all the dependencies have been met.

**Comment by vmaineng** [comment]
The only 'alt-hero' fields are located in project-md-file--removing-unused--alt-hero--field.md
