### ISSUE TITLE
Pre-work Checklist: Developer: Luke Karis

### ISSUE THREAD

**Issue by luke-karis** [hackforla/website#2727]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" or "role: back end" label*(s) to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Self Assign this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [ ] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will providing estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@luke-karis I am reopening this issue since the weekly progress report is still pending. Once you have done that in any of your issues, please feel free to check off the line item and close this issue. Thanks.
Provide Update on the following items weekly:
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by SAUMILDHANKAR** [comment]
Update: Waiting for an issue where weekly progress report could be provided,

**Comment by phuonguvan** [comment]
@SAUMILDHANKAR  @JessicaLucindaCheng Hey! This is the design team lead and I was wondering if you are still working on this project. Bonnie told me to update you guys so let me know as soon as possible!

**Comment by JessicaLucindaCheng** [comment]
@SAUMILDHANKAR @phuonguvan Luke is still working on this pre-work.

I left a comment for Luke in the issue they're working on: https://github.com/hackforla/website/issues/2901#issuecomment-1078478725

**Comment by HackforLABot** [comment]
## Activity Log: luke-karis
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- luke-karis assigned: https://github.com/hackforla/website/issues/2426#issuecomment-958012986 at 01/29/2022, 01:08 PM PST
- luke-karis unassigned: https://github.com/hackforla/website/issues/2426#issuecomment-958012986 at 01/29/2022, 01:14 PM PST
- luke-karis opened: https://github.com/hackforla/website/issues/2727 at 01/30/2022, 10:36 AM PST
- luke-karis assigned: https://github.com/hackforla/website/issues/2727 at 01/30/2022, 10:36 AM PST
- luke-karis assigned: https://github.com/hackforla/website/issues/2427 at 01/31/2022, 08:22 PM PST
- luke-karis commented on: https://github.com/hackforla/website/issues/2427#issuecomment-1026466779 at 01/31/2022, 08:24 PM PST
- luke-karis opened: https://github.com/hackforla/website/pull/2730 at 01/31/2022, 09:15 PM PST
- luke-karis commented on: https://github.com/hackforla/website/pull/2730#issuecomment-1026487643 at 01/31/2022, 09:18 PM PST
- luke-karis issue closed by PR 2730: https://github.com/hackforla/website/issues/2427#event-5986634224 at 02/01/2022, 01:13 AM PST
- luke-karis PR was merged: https://github.com/hackforla/website/pull/2730#event-5986634247 at 02/01/2022, 01:13 AM PST
- luke-karis assigned: https://github.com/hackforla/website/issues/2243 at 02/09/2022, 07:48 PM PST
- luke-karis commented on: https://github.com/hackforla/website/issues/2243#issuecomment-1034536974 at 02/09/2022, 10:16 PM PST
- luke-karis commented on: https://github.com/hackforla/website/issues/2243#issuecomment-1038646420 at 02/13/2022, 09:05 PM PST
- luke-karis opened: https://github.com/hackforla/website/pull/2780 at 02/15/2022, 06:22 PM PST
- luke-karis closed as completed: https://github.com/hackforla/website/issues/2727#event-6079648389 at 02/15/2022, 06:52 PM PST
- luke-karis issue closed by PR 2780: https://github.com/hackforla/website/issues/2243#event-6094641769 at 02/17/2022, 04:49 PM PST
- luke-karis PR was merged: https://github.com/hackforla/website/pull/2780#event-6094641775 at 02/17/2022, 04:49 PM PST
- luke-karis assigned: https://github.com/hackforla/website/issues/2744#issuecomment-1031776832 at 02/22/2022, 11:44 PM PST
- luke-karis commented on: https://github.com/hackforla/website/issues/2744#issuecomment-1052995629 at 02/26/2022, 06:48 PM PST
- luke-karis opened: https://github.com/hackforla/website/pull/2905 at 02/28/2022, 09:59 PM PST
- luke-karis opened: https://github.com/hackforla/website/pull/2905 at 02/28/2022, 09:59 PM PST
- luke-karis issue closed by PR 2905: https://github.com/hackforla/website/issues/2744#event-6174014499 at 03/02/2022, 01:31 PM PST
- luke-karis PR was merged: https://github.com/hackforla/website/pull/2905#event-6174014507 at 03/02/2022, 01:31 PM PST
- luke-karis PR was merged: https://github.com/hackforla/website/pull/2905#event-6174014507 at 03/02/2022, 01:31 PM PST
- luke-karis assigned: https://github.com/hackforla/website/issues/2751#issuecomment-1055777159 at 03/08/2022, 09:21 PM PST
- luke-karis commented on: https://github.com/hackforla/website/issues/2751#issuecomment-1062566819 at 03/08/2022, 09:24 PM PST
- luke-karis opened: https://github.com/hackforla/website/pull/2963 at 03/10/2022, 10:05 PM PST
- luke-karis commented on: https://github.com/hackforla/website/pull/2963#issuecomment-1065481787 at 03/11/2022, 12:21 PM PST
- luke-karis issue closed by PR 2963: https://github.com/hackforla/website/issues/2751#event-6231511234 at 03/13/2022, 12:15 PM PDT
- luke-karis PR was merged: https://github.com/hackforla/website/pull/2963#event-6231511236 at 03/13/2022, 12:15 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/2982#issuecomment-1067501658 at 03/14/2022, 07:38 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2982#pullrequestreview-909607607 at 03/14/2022, 07:59 PM PDT
- luke-karis assigned: https://github.com/hackforla/website/issues/2901#issuecomment-1053981229 at 03/15/2022, 06:43 PM PDT
- luke-karis assigned: https://github.com/hackforla/website/issues/2901#issuecomment-1053981229 at 03/15/2022, 06:43 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1068646129 at 03/15/2022, 06:47 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1068646129 at 03/15/2022, 06:47 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/2962#issuecomment-1068671145 at 03/15/2022, 07:36 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1068671376 at 03/15/2022, 07:37 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2962#pullrequestreview-915258492 at 03/20/2022, 10:14 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2962#pullrequestreview-915258830 at 03/20/2022, 10:15 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2962#pullrequestreview-915262578 at 03/20/2022, 10:25 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2962#pullrequestreview-915264549 at 03/20/2022, 10:30 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2962#pullrequestreview-915265409 at 03/20/2022, 10:32 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2984#pullrequestreview-916635440 at 03/21/2022, 09:10 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1075822781 at 03/22/2022, 06:46 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1075830060 at 03/22/2022, 07:02 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1075830060 at 03/22/2022, 07:02 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2962#pullrequestreview-919593757 at 03/23/2022, 05:39 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2962#pullrequestreview-919595484 at 03/23/2022, 05:43 PM PDT
- luke-karis closed as completed: https://github.com/hackforla/website/issues/2727#event-6311004923 at 03/25/2022, 08:36 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/2962#issuecomment-1082472097 at 03/29/2022, 04:42 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2962#pullrequestreview-929622569 at 04/02/2022, 08:28 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1087077336 at 04/03/2022, 08:41 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1087077336 at 04/03/2022, 08:41 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1096099733 at 04/11/2022, 10:44 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1096099733 at 04/11/2022, 10:44 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1104574860 at 04/20/2022, 05:21 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1104574860 at 04/20/2022, 05:21 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1110487488 at 04/26/2022, 08:15 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/3083#issuecomment-1110487653 at 04/26/2022, 08:15 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/2984#pullrequestreview-959948824 at 05/02/2022, 10:01 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/3086#pullrequestreview-959955749 at 05/02/2022, 10:24 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1115752555 at 05/02/2022, 10:30 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1115752555 at 05/02/2022, 10:30 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1128269253 at 05/16/2022, 05:26 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1128269253 at 05/16/2022, 05:26 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1142871993 at 05/31/2022, 05:34 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1142871993 at 05/31/2022, 05:34 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/3179#issuecomment-1143104003 at 05/31/2022, 09:27 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/3179#pullrequestreview-997494989 at 06/06/2022, 09:45 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1155845199 at 06/14/2022, 05:32 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1155845199 at 06/14/2022, 05:32 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1161148670 at 06/20/2022, 07:44 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1161148670 at 06/20/2022, 07:44 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/3320#pullrequestreview-1021060930 at 06/27/2022, 08:50 PM PDT
- luke-karis assigned: https://github.com/hackforla/website/issues/3316#issuecomment-1166619880 at 06/28/2022, 07:34 PM PDT
- luke-karis unassigned: https://github.com/hackforla/website/issues/3316#issuecomment-1166619880 at 06/28/2022, 07:35 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1182652741 at 07/12/2022, 06:13 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1182652741 at 07/12/2022, 06:13 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/3359#issuecomment-1185090794 at 07/14/2022, 06:58 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/pull/3359#issuecomment-1186651207 at 07/17/2022, 05:54 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1189737178 at 07/19/2022, 07:29 PM PDT
- luke-karis commented on: https://github.com/hackforla/website/issues/2901#issuecomment-1189737178 at 07/19/2022, 07:29 PM PDT
- luke-karis opened: https://github.com/hackforla/website/issues/3398 at 07/19/2022, 08:09 PM PDT
- luke-karis opened: https://github.com/hackforla/website/issues/3417 at 07/21/2022, 06:44 PM PDT
- luke-karis submitted review: https://github.com/hackforla/website/pull/3471#pullrequestreview-1079588387 at 08/20/2022, 03:57 PM PDT
