### ISSUE TITLE
Pre-work Checklist: Developer: Johan Suh

### ISSUE THREAD

**Issue by codessi** [hackforla/website#2747]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [ ] Add the "role: front end" or "role: back end" label*(s) to this issue and remove the "role missing" label
- [ ] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [ ] Share your Gmail address with the team lead so you can be added to the Google Drive
- [ ] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [ ] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [ ] Self Assign this issue (gear in right side panel)
- [ ] Add this issue to Projects: Project Board (gear in right side panel)
- [ ] Signup for a [Figma](https://Figma.com) account
- [ ] Attend weekly team meetings: 
  - [ ] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [ ] (Optional) Office Hours, Thursdays 7pm PST
  - [ ] All team meeting (UX, Development, Product), Sunday 10am PST
- [ ] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [ ] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [ ] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [ ] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [ ] Once you take a good first issue, you will providing estimates and progress reports. 
   - [ ] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [ ] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [ ] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [ ] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by Providence-o** [comment]
@codessi we have added you to the google calendar invites for the website team and the google drive. Please fill out the roster

**Comment by JessicaLucindaCheng** [comment]
Closing this issue because Johan told me they won't be able to commit to Hack for LA.

**Comment by HackforLABot** [comment]
## Activity Log: codessi
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- codessi assigned: https://github.com/hackforla/website/issues/1558 at 06/07/2021, 08:30 PM PDT
- codessi opened: https://github.com/hackforla/website/pull/1744 at 06/15/2021, 03:05 PM PDT
- codessi closed: https://github.com/hackforla/website/pull/1744#event-4930331461 at 06/23/2021, 10:43 AM PDT
- codessi opened: https://github.com/hackforla/website/pull/1857 at 06/29/2021, 12:46 PM PDT
- codessi commented on: https://github.com/hackforla/website/pull/1857#issuecomment-873126853 at 07/02/2021, 09:43 AM PDT
- codessi issue closed by PR 1857: https://github.com/hackforla/website/issues/1558#event-4972430744 at 07/02/2021, 09:44 AM PDT
- codessi PR was merged: https://github.com/hackforla/website/pull/1857#event-4972430755 at 07/02/2021, 09:44 AM PDT
- codessi opened: https://github.com/hackforla/website/issues/2747 at 02/07/2022, 07:23 PM PST
- codessi assigned: https://github.com/hackforla/website/issues/2747#issuecomment-1032968237 at 02/15/2022, 02:59 PM PST
- codessi issue closed as completed: https://github.com/hackforla/website/issues/2747#event-6078800594 at 02/15/2022, 03:04 PM PST
