### ISSUE TITLE
Pre-work Checklist: Developer: Utkarsh Saboo

### ISSUE THREAD

**Issue by usaboo** [hackforla/website#2748]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" or "role: back end" label*(s) to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels. ----> Done
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive 
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Self Assign this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will providing estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by Providence-o** [comment]
@usaboo we have added you to the google calendar invites for the website team and the google drive. Please fill out the team roster (see link above). Reply to our comment when you are done so you can be added to the hack for LA website git hub team

**Comment by SAUMILDHANKAR** [comment]
@usaboo Just wanted to follow up on the pending action item on this issue. Feel free to close this issue when all the action items are checked off. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@usaboo Just wanted to follow up on the pending action item on this issue. Feel free to close this issue when all the action items are checked off. Thank you.

**Comment by usaboo** [comment]
@SAUMILDHANKAR I have closed it now! Thank you for reminding.

**Comment by HackforLABot** [comment]
## Activity Log: usaboo
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- usaboo opened: https://github.com/hackforla/website/issues/2748 at 02/07/2022, 07:47 PM PST
- usaboo assigned: https://github.com/hackforla/website/issues/2748#issuecomment-1032972780 at 02/11/2022, 01:09 PM PST
- usaboo assigned: https://github.com/hackforla/website/issues/2799#issuecomment-1046093336 at 02/20/2022, 09:21 AM PST
- usaboo assigned: https://github.com/hackforla/website/issues/2426#issuecomment-958012986 at 02/20/2022, 09:34 AM PST
- usaboo unassigned: https://github.com/hackforla/website/issues/2426#issuecomment-958012986 at 02/20/2022, 09:35 AM PST
- usaboo closed by PR 2841: https://github.com/hackforla/website/issues/2426#event-6107553795 at 02/20/2022, 09:35 AM PST
- usaboo reopened: https://github.com/hackforla/website/issues/2426#event-6107553795 at 02/20/2022, 09:35 AM PST
- usaboo assigned: https://github.com/hackforla/website/issues/2659#issuecomment-1043672010 at 02/20/2022, 09:35 AM PST
- usaboo unassigned: https://github.com/hackforla/website/issues/2799#issuecomment-1046093336 at 02/20/2022, 09:36 AM PST
- usaboo commented on: https://github.com/hackforla/website/issues/2659#issuecomment-1046287015 at 02/20/2022, 09:40 AM PST
- usaboo opened: https://github.com/hackforla/website/issues/2807 at 02/20/2022, 12:00 PM PST
- usaboo commented on: https://github.com/hackforla/website/issues/2807#issuecomment-1046346904 at 02/20/2022, 03:35 PM PST
- usaboo opened: https://github.com/hackforla/website/issues/2821 at 02/20/2022, 05:02 PM PST
- usaboo opened: https://github.com/hackforla/website/issues/2822 at 02/20/2022, 05:07 PM PST
- usaboo opened: https://github.com/hackforla/website/issues/2823 at 02/20/2022, 05:12 PM PST
- usaboo opened: https://github.com/hackforla/website/issues/2824 at 02/20/2022, 05:20 PM PST
- usaboo opened: https://github.com/hackforla/website/issues/2825 at 02/20/2022, 05:23 PM PST
- usaboo opened: https://github.com/hackforla/website/issues/2826 at 02/21/2022, 06:55 AM PST
- usaboo opened: https://github.com/hackforla/website/issues/2827 at 02/21/2022, 07:00 AM PST
- usaboo opened: https://github.com/hackforla/website/issues/2828 at 02/21/2022, 07:05 AM PST
- usaboo opened: https://github.com/hackforla/website/issues/2829 at 02/21/2022, 07:08 AM PST
- usaboo commented on: https://github.com/hackforla/website/pull/2841#issuecomment-1048422301 at 02/22/2022, 07:39 PM PST
- usaboo merged: https://github.com/hackforla/website/pull/2841#event-6128245660 at 02/23/2022, 01:59 PM PST
- usaboo commented on: https://github.com/hackforla/website/pull/2841#issuecomment-1049256804 at 02/23/2022, 02:01 PM PST
- usaboo opened: https://github.com/hackforla/website/pull/2884 at 02/24/2022, 01:07 PM PST
- usaboo commented on: https://github.com/hackforla/website/issues/2659#issuecomment-1050267015 at 02/24/2022, 01:09 PM PST
- usaboo PR was closed: https://github.com/hackforla/website/pull/2884#event-6146639532 at 02/26/2022, 11:22 AM PST
- usaboo commented on: https://github.com/hackforla/website/pull/2884#issuecomment-1052668061 at 02/26/2022, 01:50 PM PST
- usaboo opened: https://github.com/hackforla/website/pull/2893 at 02/26/2022, 02:14 PM PST
- usaboo assigned: https://github.com/hackforla/website/issues/2283#issuecomment-927332428 at 02/26/2022, 02:29 PM PST
- usaboo commented on: https://github.com/hackforla/website/issues/2283#issuecomment-1052717268 at 02/26/2022, 02:31 PM PST
- usaboo issue closed by PR 2893: https://github.com/hackforla/website/issues/2659#event-6149415202 at 02/26/2022, 11:49 PM PST
- usaboo PR was merged: https://github.com/hackforla/website/pull/2893#event-6149415211 at 02/26/2022, 11:49 PM PST
- usaboo opened: https://github.com/hackforla/website/pull/2899 at 02/27/2022, 09:08 AM PST
- usaboo commented on: https://github.com/hackforla/website/pull/2882#issuecomment-1053638894 at 02/27/2022, 10:26 AM PST
- usaboo issue closed by PR 2899: https://github.com/hackforla/website/issues/2283#event-6159086068 at 02/28/2022, 07:51 PM PST
- usaboo PR was merged: https://github.com/hackforla/website/pull/2899#event-6159086078 at 02/28/2022, 07:51 PM PST
- usaboo submitted review: https://github.com/hackforla/website/pull/2882#pullrequestreview-896669044 at 03/01/2022, 10:21 AM PST
- usaboo assigned: https://github.com/hackforla/website/issues/2155 at 03/01/2022, 10:31 AM PST
- usaboo commented on: https://github.com/hackforla/website/issues/2155#issuecomment-1055737024 at 03/01/2022, 10:33 AM PST
- usaboo commented on: https://github.com/hackforla/website/issues/2155#issuecomment-1061076762 at 03/07/2022, 11:57 AM PST
- usaboo opened: https://github.com/hackforla/website/pull/2962 at 03/10/2022, 08:33 PM PST
- usaboo submitted review: https://github.com/hackforla/website/pull/2963#pullrequestreview-907686475 at 03/11/2022, 11:58 AM PST
- usaboo commented on: https://github.com/hackforla/website/pull/2963#issuecomment-1065532852 at 03/11/2022, 01:13 PM PST
- usaboo submitted review: https://github.com/hackforla/website/pull/2943#pullrequestreview-907801321 at 03/11/2022, 01:40 PM PST
- usaboo commented on: https://github.com/hackforla/website/pull/2982#issuecomment-1068110453 at 03/15/2022, 08:18 AM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1068672233 at 03/15/2022, 07:39 PM PDT
- usaboo submitted review: https://github.com/hackforla/website/pull/2984#pullrequestreview-915176382 at 03/20/2022, 05:42 PM PDT
- usaboo closed as completed: https://github.com/hackforla/website/issues/2748#event-6272134956 at 03/20/2022, 06:01 PM PDT
- usaboo commented on: https://github.com/hackforla/website/issues/2748#issuecomment-1073394873 at 03/20/2022, 06:02 PM PDT
- usaboo submitted review: https://github.com/hackforla/website/pull/2982#pullrequestreview-915182501 at 03/20/2022, 06:14 PM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3014#issuecomment-1079978729 at 03/27/2022, 10:24 AM PDT
- usaboo submitted review: https://github.com/hackforla/website/pull/3014#pullrequestreview-922521863 at 03/27/2022, 05:29 PM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3014#issuecomment-1084669617 at 03/31/2022, 07:33 AM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/2962#issuecomment-1090407751 at 04/06/2022, 08:31 AM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1120131715 at 05/06/2022, 09:30 PM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3116#issuecomment-1123113058 at 05/10/2022, 07:30 PM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3225#issuecomment-1155981584 at 06/14/2022, 09:44 PM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3235#issuecomment-1155989237 at 06/14/2022, 10:01 PM PDT
- usaboo submitted review: https://github.com/hackforla/website/pull/3225#pullrequestreview-1008433550 at 06/15/2022, 08:01 PM PDT
- usaboo submitted review: https://github.com/hackforla/website/pull/3235#pullrequestreview-1008478104 at 06/15/2022, 09:32 PM PDT
- usaboo issue closed by PR 2962: https://github.com/hackforla/website/issues/2155#event-6870535073 at 06/23/2022, 05:01 PM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3225#issuecomment-1166594993 at 06/26/2022, 10:27 AM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3183#issuecomment-1166595271 at 06/26/2022, 10:28 AM PDT
- usaboo commented on: https://github.com/hackforla/website/issues/2625#issuecomment-1166596854 at 06/26/2022, 10:35 AM PDT
- usaboo opened: https://github.com/hackforla/website/issues/3314 at 06/26/2022, 11:55 AM PDT
- usaboo assigned: https://github.com/hackforla/website/issues/3170#issuecomment-1135150046 at 06/26/2022, 12:10 PM PDT
- usaboo unassigned: https://github.com/hackforla/website/issues/3170#issuecomment-1166619215 at 06/26/2022, 12:10 PM PDT
- usaboo submitted review: https://github.com/hackforla/website/pull/3225#pullrequestreview-1022661216 at 06/28/2022, 07:24 PM PDT
- usaboo assigned: https://github.com/hackforla/website/issues/3274#issuecomment-1160927695 at 06/28/2022, 07:35 PM PDT
- usaboo unassigned: https://github.com/hackforla/website/issues/3274#issuecomment-1169468944 at 06/28/2022, 07:50 PM PDT
- usaboo unassigned: https://github.com/hackforla/website/issues/3274#issuecomment-1169468944 at 06/28/2022, 07:50 PM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3225#issuecomment-1172484456 at 07/01/2022, 08:54 AM PDT
- usaboo submitted review: https://github.com/hackforla/website/pull/3225#pullrequestreview-1026394109 at 07/01/2022, 08:54 AM PDT
- usaboo submitted review: https://github.com/hackforla/website/pull/3183#pullrequestreview-1035133303 at 07/11/2022, 07:18 PM PDT
- usaboo commented on: https://github.com/hackforla/website/pull/3161#issuecomment-1186576746 at 07/17/2022, 10:27 AM PDT
- usaboo assigned: https://github.com/hackforla/website/issues/2675#issuecomment-1090982728 at 07/21/2022, 09:11 PM PDT
- usaboo unassigned: https://github.com/hackforla/website/issues/2675#issuecomment-1192160542 at 10/03/2022, 06:00 PM PDT
