### ISSUE TITLE
Pre-work Checklist: Developer: Jason Yee

### ISSUE THREAD

**Issue by JasonY188** [hackforla/website#2750]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" or "role: back end" label*(s) to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Self Assign this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings: 
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will providing estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by Providence-o** [comment]
@JasonY188 
we have added you to the google calendar invites for the website team and the google drive. Please fill out the team roster (see link above). Reply to our comment when you are done so you can be added to the hack for LA website GitHub team

**Comment by SAUMILDHANKAR** [comment]
@JasonY188: Once you provide your weekly progress update on issue #2458, you can check off the progress reports action item in this issue. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@JasonY188 Thanks for sharing your weekly progress report on #2458. Feel free to check-off the action item. Also, you can close this issue if you have completed all the action items. Thank you.

**Comment by JasonY188** [comment]
All tasks are completed.

**Comment by HackforLABot** [comment]
## Activity Log: JasonY188
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- JasonY188 opened: https://github.com/hackforla/website/issues/2750 at 02/07/2022, 09:33 PM PST
- JasonY188 assigned: https://github.com/hackforla/website/issues/2750#issuecomment-1032975812 at 02/08/2022, 04:26 PM PST
- JasonY188 assigned: https://github.com/hackforla/website/issues/2428#issuecomment-958019170 at 02/09/2022, 12:23 PM PST
- JasonY188 commented on: https://github.com/hackforla/website/issues/2428#issuecomment-1034164551 at 02/09/2022, 12:29 PM PST
- JasonY188 opened: https://github.com/hackforla/website/pull/2762 at 02/09/2022, 05:40 PM PST
- JasonY188 issue closed by PR 2762: https://github.com/hackforla/website/issues/2428#event-6046330318 at 02/10/2022, 02:11 PM PST
- JasonY188 PR was merged: https://github.com/hackforla/website/pull/2762#event-6046330333 at 02/10/2022, 02:11 PM PST
- JasonY188 assigned: https://github.com/hackforla/website/issues/2233 at 02/10/2022, 07:36 PM PST
- JasonY188 commented on: https://github.com/hackforla/website/issues/2233#issuecomment-1035860506 at 02/10/2022, 07:51 PM PST
- JasonY188 opened: https://github.com/hackforla/website/pull/2785 at 02/15/2022, 10:34 PM PST
- JasonY188 issue closed by PR 2785: https://github.com/hackforla/website/issues/2233#event-6094542465 at 02/17/2022, 04:18 PM PST
- JasonY188 PR was merged: https://github.com/hackforla/website/pull/2785#event-6094542471 at 02/17/2022, 04:18 PM PST
- JasonY188 assigned: https://github.com/hackforla/website/issues/2480#issuecomment-968336717 at 02/21/2022, 03:15 PM PST
- JasonY188 commented on: https://github.com/hackforla/website/issues/2480#issuecomment-1047295578 at 02/21/2022, 03:25 PM PST
- JasonY188 opened: https://github.com/hackforla/website/issues/2860 at 02/22/2022, 08:49 PM PST
- JasonY188 opened: https://github.com/hackforla/website/issues/2861 at 02/22/2022, 08:57 PM PST
- JasonY188 submitted review: https://github.com/hackforla/website/pull/2862#pullrequestreview-892047597 at 02/23/2022, 11:01 PM PST
- JasonY188 opened: https://github.com/hackforla/website/pull/2882 at 02/23/2022, 11:22 PM PST
- JasonY188 commented on: https://github.com/hackforla/website/pull/2882#issuecomment-1050536736 at 02/24/2022, 09:26 PM PST
- JasonY188 submitted review: https://github.com/hackforla/website/pull/2883#pullrequestreview-893289383 at 02/24/2022, 09:46 PM PST
- JasonY188 issue closed by PR 2882: https://github.com/hackforla/website/issues/2480#event-6165449930 at 03/01/2022, 02:58 PM PST
- JasonY188 PR was merged: https://github.com/hackforla/website/pull/2882#event-6165449952 at 03/01/2022, 02:58 PM PST
- JasonY188 assigned: https://github.com/hackforla/website/issues/2458#issuecomment-962288923 at 03/01/2022, 11:24 PM PST
- JasonY188 commented on: https://github.com/hackforla/website/issues/2458#issuecomment-1056454152 at 03/01/2022, 11:28 PM PST
- JasonY188 commented on: https://github.com/hackforla/website/pull/2943#issuecomment-1065787443 at 03/11/2022, 06:00 PM PST
- JasonY188 submitted review: https://github.com/hackforla/website/pull/2943#pullrequestreview-907933832 at 03/11/2022, 06:16 PM PST
- JasonY188 commented on: https://github.com/hackforla/website/issues/2458#issuecomment-1066319925 at 03/13/2022, 09:10 PM PDT
- JasonY188 opened: https://github.com/hackforla/website/pull/2984 at 03/15/2022, 05:55 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2967#issuecomment-1068724899 at 03/15/2022, 09:39 PM PDT
- JasonY188 submitted review: https://github.com/hackforla/website/pull/2967#pullrequestreview-913842690 at 03/17/2022, 05:44 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1075870408 at 03/22/2022, 08:13 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/issues/2750#issuecomment-1080082604 at 03/27/2022, 06:19 PM PDT
- JasonY188 closed as completed: https://github.com/hackforla/website/issues/2750#event-6314631925 at 03/27/2022, 06:19 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1080107650 at 03/27/2022, 07:12 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1092451859 at 04/07/2022, 10:20 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1094476174 at 04/10/2022, 07:19 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1103406264 at 04/19/2022, 07:35 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1120132318 at 05/06/2022, 09:36 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1124419609 at 05/11/2022, 05:55 PM PDT
- JasonY188 commented on: https://github.com/hackforla/website/pull/2984#issuecomment-1126994132 at 05/15/2022, 11:41 AM PDT
- JasonY188 issue closed by PR 2984: https://github.com/hackforla/website/issues/2458#event-6773463350 at 06/08/2022, 03:23 PM PDT
