### ISSUE TITLE
Pre-work Checklist: Developer: Carlos Perez

### ISSUE THREAD

**Issue by Carlos-A-P** [hackforla/website#2753]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" or "role: back end" label*(s) to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Self Assign this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7pm PST
  - [x] (Optional) Office Hours, Thursdays 7pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will providing estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Questions / In Review" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by Carlos-A-P** [comment]
How much time did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue?
12 hrs

**Comment by ExperimentsInHonesty** [comment]
- [PRs that Carlos has reviewed](https://github.com/hackforla/website/issues?q=is%3Aissue+assignee%3ACarlos-A-P+is%3Aclosed)
- [Issues that Carlos has completed](https://github.com/hackforla/website/issues?q=is%3Aissue+assignee%3ACarlos-A-P+is%3Aclosed)

**Comment by ExperimentsInHonesty** [comment]
@Carlos-A-P I see that you have gotten up to medium level issues.  But when I look to see reviews by [Carlos-A-P PR reviews for other developers](https://github.com/hackforla/website/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3A%40Carlos-A-P), I don't see any.  So you will need to rejoin the website team.  Please reach out in the hfla-site Slack channel for instructions on how to do that.

Then please write back with what you have not yet done skill wise (see [developer self test](https://docs.google.com/presentation/d/1RUQk4mOrv4G1fja_D3GMWMtCyCqsdj64fNPlrIDJhxg/)), and then add the `ready for product` label, and I will help you find issues and activities that will fulfil those requirements.

**Comment by ExperimentsInHonesty** [comment]
@Carlos-A-P I am going to close this issue since you seem to be off the team.

**Comment by HackforLABot** [comment]
## Activity Log: Carlos-A-P
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Carlos-A-P opened: https://github.com/hackforla/website/issues/2753 at 02/08/2022, 04:14 PM PST
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/2753#issuecomment-1033191074 at 02/10/2022, 07:07 PM PST
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/2661#issuecomment-1005361397 at 02/10/2022, 07:42 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2661#issuecomment-1035869413 at 02/10/2022, 08:13 PM PST
- Carlos-A-P opened: https://github.com/hackforla/website/pull/2769 at 02/12/2022, 02:32 PM PST
- Carlos-A-P issue closed by PR 2769: https://github.com/hackforla/website/issues/2661#event-6060553744 at 02/13/2022, 02:02 AM PST
- Carlos-A-P PR was merged: https://github.com/hackforla/website/pull/2769#event-6060553751 at 02/13/2022, 02:03 AM PST
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/2088 at 02/14/2022, 02:29 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2088#issuecomment-1039640043 at 02/14/2022, 02:33 PM PST
- Carlos-A-P opened: https://github.com/hackforla/website/pull/2779 at 02/15/2022, 05:41 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2780#issuecomment-1041062520 at 02/15/2022, 07:35 PM PST
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/2780#pullrequestreview-886534514 at 02/17/2022, 12:49 PM PST
- Carlos-A-P issue closed by PR 2779: https://github.com/hackforla/website/issues/2088#event-6095376975 at 02/17/2022, 07:38 PM PST
- Carlos-A-P PR was merged: https://github.com/hackforla/website/pull/2779#event-6095376987 at 02/17/2022, 07:38 PM PST
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/2086 at 02/18/2022, 07:11 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2086#issuecomment-1045641583 at 02/18/2022, 07:14 PM PST
- Carlos-A-P opened: https://github.com/hackforla/website/pull/2803 at 02/19/2022, 01:59 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2789#issuecomment-1046294029 at 02/20/2022, 10:22 AM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2790#issuecomment-1046294271 at 02/20/2022, 10:23 AM PST
- Carlos-A-P opened: https://github.com/hackforla/website/issues/2820 at 02/20/2022, 02:05 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2790#issuecomment-1046332664 at 02/20/2022, 02:17 PM PST
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/2789#pullrequestreview-889147139 at 02/21/2022, 02:46 PM PST
- Carlos-A-P issue closed by PR 2803: https://github.com/hackforla/website/issues/2086#event-6114861756 at 02/21/2022, 06:12 PM PST
- Carlos-A-P PR was merged: https://github.com/hackforla/website/pull/2803#event-6114861764 at 02/21/2022, 06:12 PM PST
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/2339#issuecomment-1030189909 at 02/21/2022, 07:20 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2339#issuecomment-1047388465 at 02/21/2022, 07:22 PM PST
- Carlos-A-P reopened: https://github.com/hackforla/website/pull/2790#event-6119925346 at 02/22/2022, 09:58 AM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2790#issuecomment-1048069028 at 02/22/2022, 10:03 AM PST
- Carlos-A-P opened: https://github.com/hackforla/website/issues/2873 at 02/23/2022, 08:59 AM PST
- Carlos-A-P opened: https://github.com/hackforla/website/issues/2874 at 02/23/2022, 09:06 AM PST
- Carlos-A-P opened: https://github.com/hackforla/website/issues/2875 at 02/23/2022, 09:10 AM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2889#issuecomment-1052653710 at 02/26/2022, 01:38 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2339#issuecomment-1052693141 at 02/26/2022, 02:11 PM PST
- Carlos-A-P closed as completed: https://github.com/hackforla/website/issues/2753#event-6147338751 at 02/26/2022, 02:12 PM PST
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/2889#pullrequestreview-894444688 at 02/26/2022, 02:27 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2339#issuecomment-1059862608 at 03/05/2022, 04:48 PM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2723#issuecomment-1062512021 at 03/08/2022, 07:13 PM PST
- Carlos-A-P opened: https://github.com/hackforla/website/pull/2977 at 03/13/2022, 12:55 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2339#issuecomment-1067418966 at 03/14/2022, 04:49 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2986#issuecomment-1069906788 at 03/16/2022, 07:29 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2986#issuecomment-1069911509 at 03/16/2022, 07:31 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2339#issuecomment-1070335565 at 03/16/2022, 10:16 PM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/2986#pullrequestreview-913989809 at 03/17/2022, 11:42 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3001#issuecomment-1075857132 at 03/22/2022, 07:42 PM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3001#pullrequestreview-919700164 at 03/23/2022, 09:42 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2977#issuecomment-1080019998 at 03/27/2022, 02:11 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2977#issuecomment-1082526939 at 03/29/2022, 06:35 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2977#issuecomment-1082571129 at 03/29/2022, 08:01 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2723#issuecomment-1084800087 at 03/31/2022, 09:14 AM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/2723#pullrequestreview-928401476 at 03/31/2022, 08:43 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/2977#issuecomment-1089149480 at 04/05/2022, 11:21 AM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3037#issuecomment-1092418456 at 04/07/2022, 09:02 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3037#issuecomment-1093019394 at 04/08/2022, 08:42 AM PDT
- Carlos-A-P issue closed by PR 2977: https://github.com/hackforla/website/issues/2339#event-6398643149 at 04/08/2022, 12:12 PM PDT
- Carlos-A-P PR was merged: https://github.com/hackforla/website/pull/2977#event-6398643164 at 04/08/2022, 12:12 PM PDT
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/3026#issuecomment-1086584020 at 04/08/2022, 01:23 PM PDT
- Carlos-A-P unassigned: https://github.com/hackforla/website/issues/3026#issuecomment-1086584020 at 04/08/2022, 01:25 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2753#issuecomment-1094333363 at 04/10/2022, 10:32 AM PDT
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/2802#issuecomment-1046109777 at 04/13/2022, 08:10 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2802#issuecomment-1098666061 at 04/13/2022, 08:12 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3057#issuecomment-1100769895 at 04/16/2022, 04:25 PM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3057#pullrequestreview-943913052 at 04/16/2022, 11:47 PM PDT
- Carlos-A-P opened: https://github.com/hackforla/website/pull/3075 at 04/20/2022, 09:10 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3072#issuecomment-1104689475 at 04/20/2022, 09:15 PM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3072#pullrequestreview-948029965 at 04/20/2022, 09:25 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1107689241 at 04/23/2022, 07:29 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1110491508 at 04/26/2022, 08:23 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1114445490 at 05/01/2022, 07:49 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3086#issuecomment-1114448412 at 05/01/2022, 08:02 PM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3086#pullrequestreview-958685531 at 05/01/2022, 08:03 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3085#issuecomment-1114450222 at 05/01/2022, 08:05 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3085#issuecomment-1114450605 at 05/01/2022, 08:06 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3086#issuecomment-1116204700 at 05/03/2022, 08:02 AM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3085#issuecomment-1116874134 at 05/03/2022, 07:31 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1116914193 at 05/03/2022, 09:23 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1117714373 at 05/04/2022, 12:08 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1120139194 at 05/06/2022, 10:36 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3085#issuecomment-1120142420 at 05/06/2022, 11:02 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1120518126 at 05/08/2022, 05:24 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3085#issuecomment-1123121646 at 05/10/2022, 07:48 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1123132320 at 05/10/2022, 08:09 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3075#issuecomment-1129523850 at 05/17/2022, 08:18 PM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3085#pullrequestreview-976315035 at 05/17/2022, 08:32 PM PDT
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/2955#issuecomment-1063874330 at 05/22/2022, 10:16 AM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2955#issuecomment-1133939432 at 05/22/2022, 10:28 AM PDT
- Carlos-A-P issue closed by PR 3075: https://github.com/hackforla/website/issues/2802#event-6694294473 at 05/27/2022, 10:37 AM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3086#issuecomment-1140285448 at 05/28/2022, 08:39 AM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3086#pullrequestreview-988533063 at 05/28/2022, 08:43 AM PDT
- Carlos-A-P issue closed by PR 3075: https://github.com/hackforla/website/issues/2802#event-6697626294 at 05/28/2022, 04:06 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/2955#issuecomment-1144353244 at 06/01/2022, 07:31 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3183#issuecomment-1146664858 at 06/04/2022, 11:30 AM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3183#pullrequestreview-997397111 at 06/06/2022, 06:18 PM PDT
- Carlos-A-P unassigned: https://github.com/hackforla/website/issues/2955#issuecomment-1144353244 at 06/09/2022, 07:10 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3237#issuecomment-1154249750 at 06/13/2022, 11:35 AM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3225#issuecomment-1154255212 at 06/13/2022, 11:41 AM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3237#pullrequestreview-1006878975 at 06/14/2022, 10:19 PM PDT
- Carlos-A-P submitted review: https://github.com/hackforla/website/pull/3225#pullrequestreview-1008422640 at 06/15/2022, 07:39 PM PDT
- Carlos-A-P commented on: https://github.com/hackforla/website/pull/3225#issuecomment-1157238463 at 06/15/2022, 10:10 PM PDT
- Carlos-A-P assigned: https://github.com/hackforla/website/issues/3944 at 02/13/2023, 09:45 AM PST
- Carlos-A-P commented on: https://github.com/hackforla/website/issues/3944#issuecomment-1428389293 at 02/13/2023, 09:45 AM PST
- Carlos-A-P opened: https://github.com/hackforla/website/pull/3993 at 02/16/2023, 07:25 PM PST
- Carlos-A-P PR was merged: https://github.com/hackforla/website/pull/3993#event-8552105263 at 02/17/2023, 05:54 PM PST
- Carlos-A-P issue closed by PR 3993: https://github.com/hackforla/website/issues/3944#event-8552105307 at 02/17/2023, 05:54 PM PST
- Carlos-A-P issue closed as completed: https://github.com/hackforla/website/issues/2753#event-14463588518 at 09/30/2024, 04:24 PM PDT
