### ISSUE TITLE
Edit content field and remove type field from yml credit files

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2775]
### Dependency
- [x] #2806
- [x] #2830 
- [x] #2833 
- [x] #2874
- [x] #2863 
- [x] #2864 
- [x] #2865 
- [x] #2861 
- [x] #2866 
- [x] #2867 
- [x] #2868 
- [x] #2869   
- [x] #2870 
- [x] #2871 
- [x] #2633
- [x] #2791
- [x] #2792
- [x] #2793
- [x] #2794
- [x] #2795
- [x] #2796
- [x] #2797
- [x] #2798
- [x] #2799
- [x] #2800 
- [x] #2804
- [x] #2810
- [x] #2805 
- [x] #2811
- [x] #2808
- [x] #2807
- [x] #2816
- [x] #2812
- [x] #2820 
- [x] #2813
- [x] #2815
- [x] #2809 
- [x] #2817
- [x] #2818 
- [x] #2814 
- [x] #2821 
- [x] #2822 
- [x] #2823 
- [x] #2824 
- [x] #2825 
- [x] #2831 
- [x] #2826 
- [x] #2827 
- [x] #2829 
- [x] #2828 
- [x] #2832 
- [x] #2834 
- [x] #2836
- [x] #2842 
- [x] #2843
- [x] #2844 
- [x] #2845 
- [x] #2846 
- [x] #2847 
- [x] #2848 
- [x] #2849 
- [x] #2850
- [x] #2851 
- [x] #2852 
- [x] #2853
- [x] #2855 
- [x] #2856
- [x] #2876 
- [x] #2877 
- [x] #2860
- [x] #2873
- [x] #2875 
- [x] #2857 
- [x] #2858 
- [x] #2859
- [x] #2878 

### Overview
As a developer, I want to edit the content field and remove the type field from all the credits' yml files so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

To incorporate this, the following will be implemented: the content field will be edited to content-type and the type field will be removed from each of the issues mentioned in the action items below. The issues will be created using the [Credits file template: Edit content field and remove type field](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Credit%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&template=credits-file-template--edit-content-field-and-remove-type-field.md&title=Edit+content+field+and+remove+type+field+from+%5BINSERT+FILE+NAME+HERE%5D.yml+credits+file). Once the issue is created the information will be updated in the following [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1yHo08dVVxI-Bvf_4MXJwMB9jSTr23pk_pydirWkgDgs/edit#gid=0). Tech Leads will take a look at the issue before adding the ready for milestone label on each issue and the issue numbers to the Dependency section above.

The process for a developer to follow when writing an issue for this epic:
- Locate the yml file in the credits directory `website/_data/internal/credits`
- Change the content and type fields in the respective yml files

### Action Items
- [x] Write issues and add to the Dependency section above. See instructions in [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1yHo08dVVxI-Bvf_4MXJwMB9jSTr23pk_pydirWkgDgs/edit#gid=456708813).
- [ ] Once all the issues in the Dependency section are checked off and closed, use the search function in your IDE to check the following for the .yml files in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits):
  - [x] There is _**no**_ `content:` field in any of the `.yml` files  in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits). (If you are using VSCode as your IDE, you can search for `content:` and restrict the search by filling in the "files to include" field with `_data\internal\credits`. Other IDEs may have similar search capabilities.)
    - [x] If you find any `content:` fields in any of the `.yml` files  in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits), list the .yml file(s) you found them in in a new comment below.
  - [x] There is _**no**_ `type:` field in any of the `.yml` files in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits). If you see any `content-type: image` in your search, that is okay.
    - [x] If you find _**any**_ `type:` fields in any of the `.yml` files  in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits), list the .yml file(s) you found them in in a new comment below.
- [x] After you do the searches above,    
  - [x] If you find _**no**_ `content:` nor `type:` fields in any of the `.yml` files  in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits), then close this issue.
  - [x] If you find _**any**_ `content:` or `type:` fields in any of the `.yml` files in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits),
    - [x] Then reach out to the [merge team and technical leads](https://github.com/hackforla/website/wiki/Meet-the-Team) with the list of .yml files that had `content:` or `type:` fields and ask them to help you write issues to fix what you found.

### Resources/Instructions
[Credits Page](https://www.hackforla.org/credits/)
[Credits file template: Edit content field and remove type field](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Credit%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&template=credits-file-template--edit-content-field-and-remove-type-field.md&title=Edit+content+field+and+remove+type+field+from+%5BINSERT+FILE+NAME+HERE%5D.yml+credits+file)
[Google spreadsheet for tracking issue creation progress](https://docs.google.com/spreadsheets/d/1yHo08dVVxI-Bvf_4MXJwMB9jSTr23pk_pydirWkgDgs/edit#gid=0)
Location of yml files in the credits directory `website/_data/internal/credits`

**Comment by JessicaLucindaCheng** [comment]
All the issues for this epic have been written and prioritized.

**Comment by JessicaLucindaCheng** [comment]
- Progress: All the issues have been written but now I need to add a dependency to all the issues.
- Blockers: Still a little confused as to what to do with this epic, especially with additional action items.
- Availability: Not sure.
- ETA: Tue, April 12, 2022

**Comment by JessicaLucindaCheng** [comment]
Progress: All the issues have been written and prioritized but now I need to add a release dependency to all the issues.
Blockers: None
Availability: 6 hours
ETA: Tue, April 19, 2022

**Comment by JessicaLucindaCheng** [comment]
Progress: All the issues have been written and prioritized but now I need to add a release dependency to all the issues. I have added release dependency to some of the issues already but just need to finish the rest.
Blockers: None
Availability: 6 hours
ETA: Sun, May 1, 2022

**Comment by JessicaLucindaCheng** [comment]
Progress: All the issues have been written and prioritized and a release dependency Action Item has been added to all the issues. All the issues are now ready to be worked on.
Blockers: None
Availability: 6 hours
ETA: Wed, May 4, 2022

**Comment by jdingeman** [comment]
Moving to New Issue Approval since all dependencies have been satisfied

**Comment by jdingeman** [comment]
Checked via VS code and can confirm there are no more `content: ` or `type: ` fields in _data/internal/credits
