### ISSUE TITLE
Pre-work Checklist: Developer: Ben Montgomery

### ISSUE THREAD

**Issue by maybleMyers** [hackforla/website#2940]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add the "role: front end" or "role: back end" label*(s) to this issue and remove the "role missing" label
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Self Assign this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will provide estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
    - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
    - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [ ] Progress through issues with increasing complexity in the following order:
  - Good first issue
  - Good second issue
  - Small 
  - Medium 
  - Large
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
- [ ] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [ ] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by maybleMyers** [comment]
Progress: I have 3more issues to complete
Blockers: No big difficulties
Availability: 6 hours
ETA: 4/1/2022

**Comment by SAUMILDHANKAR** [comment]
@Benji-Montgomery Thanks for doing your weekly progress report in your medium issue, you can check off that action item above. Also feel free to check off the remaining items and close this issue once done. Please let us know if you have any questions or need help with any of the pending action items. Thanks.

**Comment by SAUMILDHANKAR** [comment]
@Benji-Montgomery Please feel free to check off your weekly progress report action item in the checklist above, since you have already done that in your latest issue. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@Benji-Montgomery Just wanted to follow up on your pending action items. They are mostly for your understanding, once you go through them, please check them off and close this issue. 
Also, noticed that you haven't picked up your medium issue next. Please let us know if your availability has changed or have any questions. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@Benji-Montgomery Hope you are doing well. Planning to close this issue due to inactivity. I will leave a slack message as well about the same. Please feel free to join us back when your availability changes. Thanks.

**Comment by HackforLABot** [comment]
## Activity Log: maybleMyers
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- maybleMyers opened: https://github.com/hackforla/website/issues/2940 at 03/08/2022, 04:15 AM PST
- maybleMyers assigned: https://github.com/hackforla/website/issues/2940#issuecomment-1061715812 at 03/08/2022, 06:12 PM PST
- maybleMyers assigned: https://github.com/hackforla/website/issues/2792#issuecomment-1051349764 at 03/11/2022, 12:41 AM PST
- maybleMyers commented on: https://github.com/hackforla/website/issues/2792#issuecomment-1064897011 at 03/11/2022, 12:44 AM PST
- maybleMyers opened: https://github.com/hackforla/website/pull/2965 at 03/11/2022, 01:48 AM PST
- maybleMyers commented on: https://github.com/hackforla/website/issues/2792#issuecomment-1064954291 at 03/11/2022, 01:56 AM PST
- maybleMyers closed: https://github.com/hackforla/website/pull/2965#event-6229720616 at 03/12/2022, 05:19 AM PST
- maybleMyers opened: https://github.com/hackforla/website/pull/2971 at 03/12/2022, 06:37 AM PST
- maybleMyers issue closed by PR 2971: https://github.com/hackforla/website/issues/2792#event-6231362757 at 03/13/2022, 09:56 AM PDT
- maybleMyers PR was merged: https://github.com/hackforla/website/pull/2971#event-6231362760 at 03/13/2022, 09:56 AM PDT
- maybleMyers assigned: https://github.com/hackforla/website/issues/2891#issuecomment-1051621260 at 03/14/2022, 09:54 AM PDT
- maybleMyers opened: https://github.com/hackforla/website/pull/2980 at 03/14/2022, 10:19 AM PDT
- maybleMyers issue closed by PR 2980: https://github.com/hackforla/website/issues/2891#event-6243754027 at 03/15/2022, 07:34 AM PDT
- maybleMyers PR was merged: https://github.com/hackforla/website/pull/2980#event-6243754064 at 03/15/2022, 07:34 AM PDT
- maybleMyers commented on: https://github.com/hackforla/website/issues/2940#issuecomment-1073045268 at 03/19/2022, 10:04 AM PDT
- maybleMyers assigned: https://github.com/hackforla/website/issues/2895#issuecomment-1053129439 at 03/19/2022, 10:23 AM PDT
- maybleMyers opened: https://github.com/hackforla/website/pull/2992 at 03/19/2022, 11:03 AM PDT
- maybleMyers issue closed by PR 2992: https://github.com/hackforla/website/issues/2895#event-6271594175 at 03/20/2022, 11:38 AM PDT
- maybleMyers PR was merged: https://github.com/hackforla/website/pull/2992#event-6271594182 at 03/20/2022, 11:38 AM PDT
- maybleMyers assigned: https://github.com/hackforla/website/issues/2987#issuecomment-1071942949 at 03/20/2022, 12:16 PM PDT
- maybleMyers opened: https://github.com/hackforla/website/pull/2994 at 03/20/2022, 01:18 PM PDT
- maybleMyers commented on: https://github.com/hackforla/website/pull/2994#issuecomment-1073341540 at 03/20/2022, 01:19 PM PDT
- maybleMyers submitted review: https://github.com/hackforla/website/pull/2996#pullrequestreview-915202515 at 03/20/2022, 07:39 PM PDT
- maybleMyers issue closed by PR 2994: https://github.com/hackforla/website/issues/2987#event-6280143233 at 03/21/2022, 07:23 PM PDT
- maybleMyers PR was merged: https://github.com/hackforla/website/pull/2994#event-6280143251 at 03/21/2022, 07:23 PM PDT
- maybleMyers assigned: https://github.com/hackforla/website/issues/2502#issuecomment-974833271 at 03/24/2022, 02:13 AM PDT
- maybleMyers commented on: https://github.com/hackforla/website/issues/2502#issuecomment-1077403488 at 03/24/2022, 02:14 AM PDT
- maybleMyers unassigned: https://github.com/hackforla/website/issues/2502#issuecomment-1094085497 at 04/09/2022, 11:00 AM PDT
- maybleMyers issue closed as completed: https://github.com/hackforla/website/issues/2940#event-6567633238 at 05/07/2022, 08:51 AM PDT
