### ISSUE TITLE
Pre-work Checklist: Developer: Poorvi

### ISSUE THREAD

**Issue by poorvi4** [hackforla/website#2964]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address and GitHub handle with the team lead so you can be added to the Google Drive and the website-write team
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [ ] (Optional) Office Hours, Thursdays 7-8pm PST
  - [ ] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will provide estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [ ] Progress through issues with increasing complexity in the following order:
  - Good first issue
  - Good second issue
  - Small 
  - Medium 
  - Large
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by JessicaLucindaCheng** [comment]
@poorvi4 Please provide an update on your progress on this prework checklist. Let us know if you have questions or need help.

Edit: Sent a Slack DM and email on Wed, Apr 6, 2022 as well.

**Comment by poorvi4** [comment]
Progress: Working on small issue (issue #2939)
Blockers: Not sure how to test github action/workflow on a non- default branch (non-main branch). Template md file does not update when trying to run the github action despite changing the file on a branch.
Availability: 3 hours
ETA: Tonight or tomorrow morning
Pictures: NA

**Comment by SAUMILDHANKAR** [comment]
@poorvi4 Thanks for sharing your update. Just wanted to add that the weekly progress report about your latest issue should be posted on that issue itself. Once you do that, please feel free to close the corresponding action item in the above checklist. Thank you.

**Comment by Providence-o** [comment]
@poorvi4 Before closing your pre-work issue, please assign a size label (from one of the point systems below) giving an estimate on how long it has taken you to work through the checklist. The size label can be found by clicking the gear icon next to 'Label' on the right above.
![image](https://user-images.githubusercontent.com/97491889/163020160-39b88328-d22e-4861-a082-4d6c46c5a67c.png)

**Comment by SAUMILDHANKAR** [comment]
@poorvi4 I see some of your suggested readings (in the action items list above) are still pending and just wanted to check if you had questions or need more time completing them. If you are already done with them, please check them off. Thank you.

**Comment by SAUMILDHANKAR** [comment]
> @poorvi4 Before closing your pre-work issue, please assign a size label (from one of the point systems below) giving an estimate on how long it has taken you to work through the checklist. The size label can be found by clicking the gear icon next to 'Label' on the right above. ![image](https://user-images.githubusercontent.com/97491889/163020160-39b88328-d22e-4861-a082-4d6c46c5a67c.png)

**Updated decision**
@poorvi4 Based on our team meeting discussion on Sat, 4/16, requesting you to add a comment answering the question `How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?` in a comment below instead of adding the size label. Thank you.

Note: This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.

**Comment by poorvi4** [comment]
@SAUMILDHANKAR 
1. How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?

I would say anywhere 2-3 hours (including attending the first meeting)

**Comment by JessicaLucindaCheng** [comment]
Poorvi shared on 4/26/22 with @SAUMILDHANKAR, planning to take a break for 3 weeks.

**Comment by SAUMILDHANKAR** [comment]
@poorvi4 Hi Poorvi, hope you're doing well. Just wanted to follow up if you are planning to join back the website team now. Please let us know if you need more time. Thank you.

Reached out on slack and email as well on 5/28.

**Comment by poorvi4** [comment]
@SAUMILDHANKAR sorry for the late update however given my work schedule in the coming weeks , is it possible to take another 2-3 weeks off? If not, I understand. Sorry for any inconveniences and delays.

**Comment by JessicaLucindaCheng** [comment]
@poorvi4 Yeah, sure. Let us know when you are ready to join back.

**Comment by tamara-snyder** [comment]
Hi @poorvi4, I hope you had a nice vacation. Please provide a progress update on your Pre-Work Checklist and any issues/PRs you're assigned to when you're back.

**Comment by Zak234** [comment]
@poorvi4 It looks like you are making good progress on issues and that you have already completed your first progress report, so we're going to close this issue as it seems like you have finished your pre-work checklist.

**Comment by HackforLABot** [comment]
## Activity Log: poorvi4
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- poorvi4 opened: https://github.com/hackforla/website/issues/2964 at 03/10/2022, 10:45 PM PST
- poorvi4 assigned: https://github.com/hackforla/website/issues/2964#issuecomment-1064822725 at 03/10/2022, 10:50 PM PST
- poorvi4 assigned: https://github.com/hackforla/website/issues/2812#issuecomment-1049454355 at 03/14/2022, 09:57 PM PDT
- poorvi4 unassigned: https://github.com/hackforla/website/issues/2812#issuecomment-1049454355 at 03/14/2022, 09:59 PM PDT
- poorvi4 assigned: https://github.com/hackforla/website/issues/2795#issuecomment-1045520603 at 03/14/2022, 10:10 PM PDT
- poorvi4 opened: https://github.com/hackforla/website/pull/2983 at 03/14/2022, 10:53 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/2795#issuecomment-1067592181 at 03/14/2022, 10:56 PM PDT
- poorvi4 issue closed by PR 2983: https://github.com/hackforla/website/issues/2795#event-6266877741 at 03/18/2022, 08:10 AM PDT
- poorvi4 PR was merged: https://github.com/hackforla/website/pull/2983#event-6266877772 at 03/18/2022, 08:10 AM PDT
- poorvi4 submitted review: https://github.com/hackforla/website/pull/2979#pullrequestreview-916680169 at 03/21/2022, 10:34 PM PDT
- poorvi4 assigned: https://github.com/hackforla/website/issues/2927#issuecomment-1058629344 at 03/21/2022, 10:40 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/2927#issuecomment-1074748323 at 03/21/2022, 10:42 PM PDT
- poorvi4 opened: https://github.com/hackforla/website/pull/3000 at 03/21/2022, 11:01 PM PDT
- poorvi4 issue closed by PR 3000: https://github.com/hackforla/website/issues/2927#event-6285813727 at 03/22/2022, 11:24 AM PDT
- poorvi4 PR was merged: https://github.com/hackforla/website/pull/3000#event-6285813739 at 03/22/2022, 11:24 AM PDT
- poorvi4 assigned: https://github.com/hackforla/website/issues/3016#issuecomment-1079776078 at 03/27/2022, 11:09 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/3016#issuecomment-1080242422 at 03/27/2022, 11:14 PM PDT
- poorvi4 unassigned: https://github.com/hackforla/website/issues/3016#issuecomment-1080250796 at 03/27/2022, 11:27 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/3016#issuecomment-1080255931 at 03/27/2022, 11:34 PM PDT
- poorvi4 assigned: https://github.com/hackforla/website/issues/2764#issuecomment-1035854914 at 03/27/2022, 11:36 PM PDT
- poorvi4 unassigned: https://github.com/hackforla/website/issues/2764#issuecomment-1035854914 at 03/27/2022, 11:37 PM PDT
- poorvi4 assigned: https://github.com/hackforla/website/issues/2939#issuecomment-1061530603 at 03/27/2022, 11:51 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/2939#issuecomment-1080265999 at 03/27/2022, 11:52 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/2964#issuecomment-1091133534 at 04/06/2022, 11:36 PM PDT
- poorvi4 opened: https://github.com/hackforla/website/pull/3042 at 04/10/2022, 04:41 PM PDT
- poorvi4 assigned: https://github.com/hackforla/website/issues/2221 at 04/12/2022, 07:39 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3042#issuecomment-1097493632 at 04/12/2022, 07:44 PM PDT
- poorvi4 issue closed by PR 3042: https://github.com/hackforla/website/issues/2939#event-6448677531 at 04/18/2022, 08:30 AM PDT
- poorvi4 PR was merged: https://github.com/hackforla/website/pull/3042#event-6448677544 at 04/18/2022, 08:30 AM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/2964#issuecomment-1107674235 at 04/23/2022, 05:41 PM PDT
- poorvi4 assigned: https://github.com/hackforla/website/issues/2395#issuecomment-1003769340 at 04/23/2022, 05:48 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/2395#issuecomment-1107675648 at 04/23/2022, 05:54 PM PDT
- poorvi4 unassigned: https://github.com/hackforla/website/issues/2395#issuecomment-1120285387 at 05/07/2022, 01:40 PM PDT
- poorvi4 unassigned: https://github.com/hackforla/website/issues/2221#issuecomment-1120289117 at 05/07/2022, 01:58 PM PDT
- poorvi4 issue closed by PR 3000: https://github.com/hackforla/website/issues/2927#event-6568209309 at 05/07/2022, 09:50 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/2964#issuecomment-1140342150 at 05/28/2022, 04:15 PM PDT
- poorvi4 assigned: https://github.com/hackforla/website/issues/2220#issuecomment-912687694 at 07/17/2022, 06:13 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/issues/2220#issuecomment-1186661978 at 07/17/2022, 06:15 PM PDT
- poorvi4 opened: https://github.com/hackforla/website/pull/3405 at 07/19/2022, 08:34 PM PDT
- poorvi4 closed: https://github.com/hackforla/website/pull/3405#event-7025671766 at 07/19/2022, 08:38 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3405#issuecomment-1189781531 at 07/19/2022, 08:39 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3394#issuecomment-1192282401 at 07/22/2022, 12:43 AM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3394#issuecomment-1193572858 at 07/24/2022, 09:44 PM PDT
- poorvi4 opened: https://github.com/hackforla/website/pull/3426 at 07/24/2022, 10:24 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3431#issuecomment-1196202059 at 07/26/2022, 07:40 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3431#issuecomment-1200493184 at 07/31/2022, 01:20 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3426#issuecomment-1200499660 at 07/31/2022, 02:02 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3426#issuecomment-1228104084 at 08/25/2022, 11:24 PM PDT
- poorvi4 commented on: https://github.com/hackforla/website/pull/3426#issuecomment-1231096691 at 08/29/2022, 08:27 PM PDT
- poorvi4 PR was closed: https://github.com/hackforla/website/pull/3426#event-7851917166 at 11/20/2022, 09:53 AM PST
- poorvi4 unassigned: https://github.com/hackforla/website/issues/2220#issuecomment-1485584784 at 03/27/2023, 05:23 PM PDT
