### ISSUE TITLE
Proposal to change project.md file format to create uniform links across projects

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#297]
### Overview 
We need a way to tell the project homepage which links to render at the top, and be able to add or remove links in the future.  This should be across all project homepages.

NOTE: must be worked on by someone with access to project homepage prototype

### Action items
- [x] submit this proposal as comment to issue #294 and follow instructions there.
- [x] Indicate current state
engage.md has the following
```yaml
links: 
  - name: Github
    url: 'https://github.com/hackla-engage'
  - name: Site
    url: 'https://sm.engage.town'
```
public-tree-map.md has the following:
```yaml
links: 
  - name: Github
    url: 'https://github.com/Public-Tree-Map/'
  - name: Test Site
    url: 'http://public-tree-map.surge.sh/'
  - name: Slack
    url: 'https://hackforla.slack.com/messages/C9UU5KKAA/'
  # - name: Site
  #   url: ''
```
- [x] Indicate desired future state
change project.md files to use this format
```yaml
links: 
  - name: Github
    url: 'https://www.example.com'
  - name: Slack
    url: 'https://www.example.com'
  - name: Testing Site
    url: 'https://www.example.com'
  - name: Live Site
    url: 'https://www.example.com'
# unused links can be commented out
  # - name: Showcase deck
  #   url: ''
```
add logic to this file _/includes/project-homepage.html that renders the following links at the top, if they exist:
Github, Slack Channel, Testing Site, Live Site 

- [ ] wait for approval on issue #294 
   - once approved
   - [ ] Perform test 
      - [ ] one project.md file
      - [ ] updating logic of appropriate include file
      - [ ] Get signoff
  - [ ] update all project.md files with new or revised fields
  - [ ] Update Template project.md wiki page 
  - [ ] Submit pull request - indicating Issue #294 is affected (format changes log), and the text "fixes Issue #[number that you are creating now]

### Resources
Wiki page - [Template of a project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

***Links to comments on other issues where this proposal originated***

1. https://github.com/hackforla/website/issues/157#issuecomment-582546238
2. https://github.com/hackforla/website/issues/157#issuecomment-582548902
3. https://github.com/hackforla/website/issues/157#issuecomment-582612863
4. https://github.com/hackforla/website/issues/157#issuecomment-582644033

**Comment by alexandrastubbs** [comment]
@ExperimentsInHonesty has asked for this issue to be closed. It is longer relevant.
