### ISSUE TITLE
Pre-work Checklist: Designer: [Phuong Van]

### ISSUE THREAD

**Issue by phuonguvan** [hackforla/website#2993]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the team lead
- [x] (Once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Confirm with the team lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [x] Self Assign yourself to this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings: 
   - [x] UX weekly team meeting, Thursdays 5pm PST
   - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Review [Design_Short Term Goals, Plan, and Tasks](https://docs.google.com/document/d/1FxwgdnWBbbQ8Pi3tspnukZTWwXtqnRXfNkNhVMEloY0/edit)
- [x] Review the [Start Here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465) and [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) pages in Figma
- [x] Review the prioritized Backlog to see what Design Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Once you accept an issue, please add your "Availability for this week" in that new issue's comment section using the 4 statuses below.
```
Availability for this week:

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
Images: "Add any images that would better help convey your progress of the issue."
```
### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by HackforLABot** [comment]
## Activity Log: phuonguvan
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- phuonguvan opened: https://github.com/hackforla/website/issues/2993 at 03/20/2022, 10:07 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2679#issuecomment-1077420926 at 03/24/2022, 02:33 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2317#issuecomment-1077450405 at 03/24/2022, 03:03 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2105#issuecomment-1077456402 at 03/24/2022, 03:09 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2613#issuecomment-1077464694 at 03/24/2022, 03:19 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2084#issuecomment-1077465560 at 03/24/2022, 03:20 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2727#issuecomment-1077470719 at 03/24/2022, 03:25 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2500#issuecomment-1077473845 at 03/24/2022, 03:29 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2615#issuecomment-1077475652 at 03/24/2022, 03:31 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/1994#issuecomment-1077482451 at 03/24/2022, 03:38 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2937#issuecomment-1077493208 at 03/24/2022, 03:51 AM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/2993#issuecomment-1073293085 at 03/24/2022, 12:31 PM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/2613#issuecomment-1078728693 at 03/26/2022, 10:26 AM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/2612#issuecomment-999090470 at 03/27/2022, 01:32 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2612#issuecomment-1079894210 at 03/27/2022, 02:49 AM PDT
- phuonguvan unassigned: https://github.com/hackforla/website/issues/2613#issuecomment-1078728693 at 03/29/2022, 07:39 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2612#issuecomment-1084978279 at 03/31/2022, 11:46 AM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/2613#issuecomment-1078728693 at 03/31/2022, 11:51 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2936#issuecomment-1085024712 at 03/31/2022, 12:39 PM PDT
- phuonguvan closed as completed: https://github.com/hackforla/website/issues/2936#event-6346738332 at 03/31/2022, 12:39 PM PDT
- phuonguvan unassigned: https://github.com/hackforla/website/issues/2613#issuecomment-1078728693 at 03/31/2022, 12:48 PM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/2613#issuecomment-1078728693 at 03/31/2022, 12:49 PM PDT
- phuonguvan unassigned: https://github.com/hackforla/website/issues/2613#issuecomment-1085525076 at 04/01/2022, 06:14 PM PDT
- phuonguvan closed as completed: https://github.com/hackforla/website/issues/2993#event-6358546518 at 04/03/2022, 10:17 AM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3034 at 04/07/2022, 02:12 AM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3035 at 04/07/2022, 03:17 AM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/3040#issuecomment-1094331934 at 04/10/2022, 10:23 AM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/2106#issuecomment-1035681718 at 04/14/2022, 12:50 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2392#issuecomment-1099576584 at 04/14/2022, 01:03 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2614#issuecomment-1099594508 at 04/14/2022, 01:29 PM PDT
- phuonguvan closed as completed: https://github.com/hackforla/website/issues/3066#event-6486152874 at 04/24/2022, 10:50 AM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/2601#issuecomment-1006992697 at 04/24/2022, 10:54 AM PDT
- phuonguvan unassigned: https://github.com/hackforla/website/issues/2601#issuecomment-1006992697 at 04/24/2022, 10:56 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2106#issuecomment-1116995046 at 05/04/2022, 12:11 AM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3117 at 05/10/2022, 04:13 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3040#issuecomment-1122888424 at 05/10/2022, 02:28 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3141 at 05/15/2022, 09:53 AM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/2697#issuecomment-1029717143 at 05/18/2022, 01:18 AM PDT
- phuonguvan opened: https://github.com/hackforla/website/pull/3184 at 05/31/2022, 01:40 AM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3191 at 06/01/2022, 01:06 AM PDT
- phuonguvan PR was merged: https://github.com/hackforla/website/pull/3184#event-6723786346 at 06/01/2022, 04:13 PM PDT
- phuonguvan closed as completed: https://github.com/hackforla/website/issues/3141#event-6773500519 at 06/08/2022, 03:33 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3040#issuecomment-1150505946 at 06/08/2022, 04:15 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3289 at 06/22/2022, 04:12 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/916#issuecomment-1170734961 at 06/29/2022, 09:13 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3040#issuecomment-1170737265 at 06/29/2022, 09:17 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3277#issuecomment-1170843586 at 06/30/2022, 12:01 AM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/2617#issuecomment-1178130768 at 07/07/2022, 12:35 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3434 at 07/27/2022, 02:35 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/916#issuecomment-1204518870 at 08/03/2022, 02:47 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3040#issuecomment-1204566847 at 08/03/2022, 04:03 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3040#issuecomment-1211546976 at 08/10/2022, 09:39 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3461 at 08/11/2022, 12:06 AM PDT
- phuonguvan assigned: https://github.com/hackforla/website/issues/3461#issuecomment-1211624237 at 09/01/2022, 12:46 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3461#issuecomment-1240234765 at 09/07/2022, 10:23 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3040#issuecomment-1240262898 at 09/07/2022, 11:09 PM PDT
- phuonguvan commented on: https://github.com/hackforla/website/issues/3040#issuecomment-1240273143 at 09/07/2022, 11:19 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3522 at 09/07/2022, 11:24 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3523 at 09/07/2022, 11:26 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3524 at 09/07/2022, 11:31 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3525 at 09/07/2022, 11:34 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3526 at 09/07/2022, 11:37 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3527 at 09/07/2022, 11:40 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3528 at 09/07/2022, 11:41 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3529 at 09/07/2022, 11:42 PM PDT
- phuonguvan opened: https://github.com/hackforla/website/issues/3555 at 09/13/2022, 09:29 PM PDT
- phuonguvan unassigned: https://github.com/hackforla/website/issues/2612#issuecomment-1276470868 at 10/12/2022, 09:55 AM PDT
- phuonguvan unassigned: https://github.com/hackforla/website/issues/2697#issuecomment-1029717143 at 11/16/2022, 09:39 AM PST
- phuonguvan unassigned: https://github.com/hackforla/website/issues/3461#issuecomment-1319637015 at 11/20/2022, 10:44 AM PST
- phuonguvan unassigned: https://github.com/hackforla/website/issues/3040#issuecomment-1240273143 at 01/08/2023, 07:43 PM PST
