### ISSUE TITLE
Pre-work Checklist: Developer: Ryan Cahela

### ISSUE THREAD

**Issue by RyanCahela** [hackforla/website#2999]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address and GitHub handle with the team lead so you can be added to the Google Drive and the website-write team
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will provide estimates and progress reports. 
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Progress through issues with increasing complexity in the following order:
  - Good first issue
  - Good second issue
  - Small 
  - Medium 
  - Large
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by JessicaLucindaCheng** [comment]
@RyanCahela Please provide an update on your progress on this prework checklist. Let us know if you have questions or need help.

Edit: Sent a Slack message and an email on Wed, Apr 6, 2022 as well.

**Comment by SAUMILDHANKAR** [comment]
@RyanCahela I see some of your suggested readings (in the action items list above) are still pending and just wanted to check if you had questions or need more time completing them. If you are already done with them, please check them off. Thank you.

**Comment by RyanCahela** [comment]
Provide Update
1. Progress: I've been setting up a new development environment the last few days. Now I think I'm at a point where I can start reviewing PR's and continue with reading the documentation.
2. Blockers: none
3. Availability: 2 Hours 4/20/22
4. ETA: 3 days

**Comment by SAUMILDHANKAR** [comment]
@RyanCahela I just noticed that you shared the weekly progress report using the following format:
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA

in your pre-work issue and not on any of the other issues. Therefore, I am unchecking the corresponding action item. Once you have shared your weekly progress report on any other issue using the above format, please feel free to check off the above item. You can close this issue after that as it looks like that is the only pending item left. Also, let me know of you have already done that and I missed it. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@RyanCahela Hope you are doing well. Please feel free to pick up your next issue. Thanks.

**Comment by tamara-snyder** [comment]
Hi @RyanCahela, please add a progress update to your Pre-Work issue. If you are no longer interested in being a part of Hack for LA, let us know so that we can remove you from the roster. Thanks!

**Comment by RyanCahela** [comment]
Progress: I've been working on rebuilding my personal portfolio site but I'm going to get back into completing issues.
Blockers: None right now.
Availability: I'll finish and close this issue once I assign myself to a new issue on Saturday 6/2/22.
ETA: "When do you expect this issue to be completed? Saturday 6/2/22"

**Comment by HackforLABot** [comment]
## Activity Log: RyanCahela
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- RyanCahela assigned: https://github.com/hackforla/website/issues/150 at 10/07/2019, 07:04 PM PDT
- RyanCahela opened: https://github.com/hackforla/website/pull/154 at 10/08/2019, 07:14 PM PDT
- RyanCahela unassigned: https://github.com/hackforla/website/issues/150 at 11/11/2019, 07:18 PM PST
- RyanCahela PR was merged: https://github.com/hackforla/website/pull/154#event-2907491097 at 12/24/2019, 06:59 PM PST
- RyanCahela opened: https://github.com/hackforla/website/issues/2999 at 03/21/2022, 09:24 PM PDT
- RyanCahela assigned: https://github.com/hackforla/website/issues/2999#issuecomment-1074712112 at 03/22/2022, 08:04 PM PDT
- RyanCahela assigned: https://github.com/hackforla/website/issues/2911#issuecomment-1055957771 at 03/23/2022, 10:48 AM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2911#issuecomment-1076641449 at 03/23/2022, 10:53 AM PDT
- RyanCahela opened: https://github.com/hackforla/website/pull/3006 at 03/23/2022, 02:05 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/pull/3006#issuecomment-1076838416 at 03/23/2022, 02:28 PM PDT
- RyanCahela issue closed by PR 3006: https://github.com/hackforla/website/issues/2911#event-6296102899 at 03/23/2022, 07:59 PM PDT
- RyanCahela PR was merged: https://github.com/hackforla/website/pull/3006#event-6296102900 at 03/23/2022, 07:59 PM PDT
- RyanCahela assigned: https://github.com/hackforla/website/issues/2089#issuecomment-903313941 at 03/24/2022, 11:07 AM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2089#issuecomment-1077905402 at 03/24/2022, 11:12 AM PDT
- RyanCahela opened: https://github.com/hackforla/website/pull/3008 at 03/24/2022, 12:37 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/pull/3008#issuecomment-1080002742 at 03/27/2022, 12:22 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/pull/3008#issuecomment-1083697968 at 03/30/2022, 03:29 PM PDT
- RyanCahela issue closed by PR 3008: https://github.com/hackforla/website/issues/2089#event-6340106128 at 03/30/2022, 07:05 PM PDT
- RyanCahela PR was merged: https://github.com/hackforla/website/pull/3008#event-6340106138 at 03/30/2022, 07:05 PM PDT
- RyanCahela assigned: https://github.com/hackforla/website/issues/3016#issuecomment-1086560598 at 04/12/2022, 01:14 PM PDT
- RyanCahela unassigned: https://github.com/hackforla/website/issues/3016#issuecomment-1086560598 at 04/12/2022, 01:14 PM PDT
- RyanCahela assigned: https://github.com/hackforla/website/issues/3016#issuecomment-1086560598 at 04/12/2022, 01:16 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/3016#issuecomment-1097175379 at 04/12/2022, 01:18 PM PDT
- RyanCahela opened: https://github.com/hackforla/website/pull/3046 at 04/12/2022, 02:41 PM PDT
- RyanCahela issue closed by PR 3046: https://github.com/hackforla/website/issues/3016#event-6431658997 at 04/13/2022, 09:02 PM PDT
- RyanCahela PR was merged: https://github.com/hackforla/website/pull/3046#event-6431659012 at 04/13/2022, 09:02 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2999#issuecomment-1104493989 at 04/20/2022, 02:59 PM PDT
- RyanCahela assigned: https://github.com/hackforla/website/issues/2728#issuecomment-1086903359 at 04/20/2022, 03:04 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2728#issuecomment-1104497608 at 04/20/2022, 03:05 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2728#issuecomment-1104513498 at 04/20/2022, 03:18 PM PDT
- RyanCahela unassigned: https://github.com/hackforla/website/issues/2728#issuecomment-1104513498 at 04/20/2022, 03:19 PM PDT
- RyanCahela assigned: https://github.com/hackforla/website/issues/2934#issuecomment-1090993404 at 04/20/2022, 03:27 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2934#issuecomment-1104518831 at 04/20/2022, 03:27 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2934#issuecomment-1106854869 at 04/22/2022, 01:56 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/pull/3083#issuecomment-1112489348 at 04/28/2022, 10:41 AM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2934#issuecomment-1112607370 at 04/28/2022, 01:05 PM PDT
- RyanCahela submitted review: https://github.com/hackforla/website/pull/3083#pullrequestreview-958609137 at 05/01/2022, 09:33 AM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2934#issuecomment-1118875181 at 05/05/2022, 10:45 AM PDT
- RyanCahela opened: https://github.com/hackforla/website/pull/3134 at 05/12/2022, 01:01 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/pull/3134#issuecomment-1126580728 at 05/13/2022, 04:41 PM PDT
- RyanCahela issue closed by PR 3134: https://github.com/hackforla/website/issues/2934#event-6610193588 at 05/14/2022, 09:09 AM PDT
- RyanCahela PR was merged: https://github.com/hackforla/website/pull/3134#event-6610193603 at 05/14/2022, 09:09 AM PDT
- RyanCahela issue closed by PR 3134: https://github.com/hackforla/website/issues/2934#event-6656505321 at 05/22/2022, 11:39 AM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/2999#issuecomment-1171572229 at 06/30/2022, 12:02 PM PDT
- RyanCahela closed as completed: https://github.com/hackforla/website/issues/2999#event-6922628162 at 07/02/2022, 04:00 PM PDT
- RyanCahela assigned: https://github.com/hackforla/website/issues/3217#issuecomment-1154386071 at 07/02/2022, 04:14 PM PDT
- RyanCahela commented on: https://github.com/hackforla/website/issues/3217#issuecomment-1172977044 at 07/02/2022, 04:17 PM PDT
- RyanCahela opened: https://github.com/hackforla/website/pull/3330 at 07/05/2022, 01:03 PM PDT
- RyanCahela issue closed by PR 3330: https://github.com/hackforla/website/issues/3217#event-6963248408 at 07/08/2022, 06:09 PM PDT
- RyanCahela PR was merged: https://github.com/hackforla/website/pull/3330#event-6963248410 at 07/08/2022, 06:09 PM PDT
