### ISSUE TITLE
HfLA: PM/Design Meeting Agenda 2022

### ISSUE THREAD

**Issue by Providence-o** [hackforla/website#3040]
### Dependency
- When we are ready to bring designers back to the team.  There should be another issue for recruiting a lead designer that will be the dependency for this issue.

### Overview
This issue tracks the agenda for the weekly meeting between the Design lead and the product managers.

### Action Items
- [ ] Copy agenda template to a new comment below
- [ ] Add the date of the agenda with comment link to the list 

```
## 2022-MM-DD Agenda and Notes 

### Prework to prep for meeting

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column
   - [ ] [Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Lead and Org rep
       - [ ] [Bonnie](https://github.com/hackforla/website/issues/assigned/ExperimentsInHonesty)
       - [ ] [Providence](https://github.com/hackforla/website/issues/assigned/Providence-o)
       - [ ] [Phu](https://github.com/hackforla/website/issues/assigned/phuonguvan)
     

### New Items


### Notes from meeting
- 
### Tasks


### Items for next meeting agenda
```
### Resources
- #2607
- #1734 
- [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149) - HfLA Figma page 
#### Past Agendas
- #1797

**Comment by Providence-o** [comment]
Add to next agenda 
- [ ] Discuss #2694 with Phu

**Comment by Providence-o** [comment]
- [ ] We need to let Phu know she is responsible for the [open roles for design](https://github.com/hackforla/UI-UX/projects/3#card-68944804)
- [ ] We need to make sure Phu monitors the ux channel mentioned on the card hfla-site-ux

**Comment by Providence-o** [comment]
## 2022-04-14 Agenda and Notes 

### Prework to prep for meeting

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column
   - [ ] [Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Lead and Org rep
       - [ ] [Bonnie](https://github.com/hackforla/website/issues/assigned/ExperimentsInHonesty)
       - [ ] [Providence](https://github.com/hackforla/website/issues/assigned/Providence-o)
       - [ ] [Phu](https://github.com/hackforla/website/issues/assigned/phuonguvan)
     

### New Items
- [x] Discuss #2694 with Phu 
- [x] We need to let Phu know she is responsible for the [open roles for design](https://github.com/hackforla/UI-UX/projects/3#card-68944804).  You can make edits.  Make sure the team meeting time is updated.  If you add a meeting, please let vrms know by opening an issue on their repo specifically [adding meeting times](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)
- [x] We need to make sure Phu monitors the ux slack channel mentioned on the card hfla-site-ux 
- [x] Review and clean up agenda for design only meeting #2106 

### Notes from meeting
- 
### Tasks


### Items for next meeting agenda

**Comment by ExperimentsInHonesty** [comment]
Add to next agenda, discussing the differences between the templates for development (which have evolved over the last two months) and the one for design. We probably need to look at the new content they have added for lessons learned to update the one for design

**Comment by phuonguvan** [comment]
## 2022-05-10 Agenda 

- [x] Review New issue #3117 
- [ ] Ask questions about making new issue regarding #2361 
- [x] Discuss the differences between the templates for development & design

**Comment by Providence-o** [comment]
Add to next agenda:

- [x] discuss #3117 to explain how we (product) modified the content of this issue.

**Comment by Providence-o** [comment]
- [ ] ask Bonnie about Miro- is it still relevant? And do we have login ?
- [ ] Adding Phu to 1password ?

**Comment by Providence-o** [comment]
Add to next agenda 

- People assigned to more than 1 issue 
- [ ] https://github.com/hackforla/website/issues/assigned/nathan944
- Members not active (update pre-work in QA after discussion)
- [ ] https://github.com/hackforla/website/issues/assigned/nathan944

**Comment by ExperimentsInHonesty** [comment]
Please review this issue and update, then you can remove the ready for design lead https://github.com/hackforla/website/issues/3177

**Comment by phuonguvan** [comment]
## 2022-06-09 Agenda 

- [x] Questions about #3177 
- [x] Review [Sijia's Figma](https://www.figma.com/file/MVRUNtLFjuamihX8PQg2Ic/Hack-for-LA-about%2Faccomplishment?node-id=117%3A12876)
- [x] Review [Gold's Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=22417%3A129125)
- [x] Review [Johnathan's Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=22417%3A129125)

**Comment by phuonguvan** [comment]
## 2022-06-29 Agenda 

- [ ] Review [Gold's Issue](https://github.com/hackforla/website/issues/2617) as what is the alt text for the site map image and further action items need to be taken for the issue
- [x] Review [Johnathan's Video](https://github.com/hackforla/website/issues/916): Is it necessary to have details on how to make an issue as the issue mostly needs to show labeling the wrong tags 
- [x] Review [Text Components Audit](https://github.com/hackforla/website/issues/3289): How do we sign off the audit? Do we audit each page as a different page on Figma? or do we audit in the same figma page it was in?

**Comment by phuonguvan** [comment]
## 2022-08-03 Agenda 
- [x] How to add @JolleenI to Github's access
- [x] Review [Johnathan's Video](https://drive.google.com/drive/folders/1bOCThYoN0Xe8BHQ-617xPrY3eFDmdeK2): Ask about the cover page and more suggestions on the video
- [x] Review [Gold's Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625%3A0): Should the mobile design have the SDG image as 16pt font? It looks really tacky
- [x] Ask Bonnie if the researchers talk to her about [Sijia's Figma](https://www.figma.com/file/MVRUNtLFjuamihX8PQg2Ic/Hack-for-LA-about%2Faccomplishment-and-Toolkit-page?node-id=307%3A388197)

**Comment by phuonguvan** [comment]
## 2022-08-1- Agenda 
- [x] Review [Gold's Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625%3A0): Should the mobile design have the SDG image as 16pt font? It looks really tacky
- [x] For the [Text Components issue](https://github.com/hackforla/website/issues/3289), how should we add the text components? We can [add the text components](https://www.figma.com/best-practices/component-architecture/text-components/) but that is a long process. We could also copy the texts that have the text components.
- [ ] There was an issue about auditing the class codes but I could only find the class codes for button sizes so are we auditing that?
- [ ] There was an issue with the inconsistency of text sizes between the desktop and mobile versions so should we audit the text sizes first and then fix the inconsistency?
- [ ] Review [Sijia's Issue](https://github.com/hackforla/website/issues/3191) and her [Figma](https://www.figma.com/file/kiB0pk0XrLq2ZTLz8lcleD/zoom-background?node-id=0%3A1)

**Comment by phuonguvan** [comment]
## 2022-09-07 Agenda 
- [ ] Clean up the Project Board
- [ ] Ask help for [Resume Content Building Tool](https://docs.google.com/spreadsheets/d/1J2uhQomDIKrkur7xCJubyC__XoeStIETiu0-NqBrfSk/edit#gid=1869629152)

**Comment by phuonguvan** [comment]
- [ ] ask Bonnie about Miro- is it still relevant? And do we have login?
- [ ] Review [Gold's Issue](https://github.com/hackforla/website/issues/2617) as what is the alt text for the site map image and further action items need to be taken for the issue
- [ ] There was an issue about auditing the class codes but I could only find the class codes for button sizes so are we auditing that?
- [ ] There was an issue with the inconsistency of text sizes between the desktop and mobile versions so should we audit the text sizes first and then fix the inconsistency?
- [ ] Review [Sijia's Issue](https://github.com/hackforla/website/issues/3191) and her [Figma](https://www.figma.com/file/kiB0pk0XrLq2ZTLz8lcleD/zoom-background?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
Currently, not having meetings
