### ISSUE TITLE
Pre-work Checklist: Developer: Eric Vennemeyer

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/website#3048]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address and GitHub handle with the team lead so you can be added to the Google Drive and the website-write team
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue
  - Good second issue
  - Small 
  - Medium 
  - Large
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by ericvennemeyer** [comment]
I have my first blocker, right in the pre-work checklist. In part 1.6.a of Setting Up The Development Environment, after running `docker-compose up` on my forked and locally cloned website repo, I get the following error:

```
jekyll 3.9.0 | Error:  no implicit conversion of Hash into Integer
hfla_site  | /usr/gem/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
```

The above is followed by a long stack trace, which I can also paste in if it will be helpful. 

I did a quick google on the error, and some results suggest that Ruby 3 is not compatible with Jekyll, but this is really beyond me at this point.  

I'm running a MacBook Air with M1 chip, if that has any bearing on this issue.

Please let me know if anyone else has had this issue and how to proceed. Thanks!!

**Comment by ericvennemeyer** [comment]
Full error message and stack trace for the Docker/Jekyll error described above:

```
hfla_site  | jekyll 3.9.0 | Error:  no implicit conversion of Hash into Integer
hfla_site  | /usr/gem/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
hfla_site  | 	from /usr/gem/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:75:in `proc_version'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:40:in `bash_on_windows?'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:77:in `watch'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:43:in `process'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
hfla_site  | 	from /usr/gem/bin/jekyll:25:in `load'
hfla_site  | 	from /usr/gem/bin/jekyll:25:in `<main>'
hfla_site exited with code 1
```

**Comment by SAUMILDHANKAR** [comment]
@ericvennemeyer Thanks for sharing your blocker. Hope someone more experienced with Docker will get back to you on our slack channel. I will keep an eye out for solutions as well. I just moved your prework issue to New Issue Approval, since PM is supposed to move pre-work issues to In-progress once they take a look. Just wanted to let you know. Thanks,

**Comment by ericvennemeyer** [comment]
@SAUMILDHANKAR Thanks for the heads-up. I've actually found a solution to the Docker issue that will, at least temporarily, allow me to run the website locally. I'll assign myself my first issue and finish the rest of my prework checklist items on Monday.

**Comment by ExperimentsInHonesty** [comment]
Hi @ericvennemeyer if you are still on the team, please let us know in the issue.  Someone said you might be on vacation, etc.  Please note that in this issue, so we don't reach out uncessarilyl

**Comment by ericvennemeyer** [comment]
Hi @ExperimentsInHonesty sorry, I've been working on the Docker issue for so long that I stopped paying attention to the prework checklist notifications. I was also recently on vacation, but back now and will close out this issue soon.

**Comment by ericvennemeyer** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?

It took several months, but I'm a special case--I ended up working on a Docker error issue I encountered while going through the pre-work checklist and sidelining the rest of the checklist items until now.

**Comment by ericvennemeyer** [comment]
All pre-work checklist items complete. Good first issue successfully completed and merged.

**Comment by HackforLABot** [comment]
## Activity Log: ericvennemeyer
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- ericvennemeyer opened: https://github.com/hackforla/website/issues/3048 at 04/12/2022, 08:10 PM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/3048#issuecomment-1097506136 at 04/13/2022, 03:23 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3048#issuecomment-1099420209 at 04/14/2022, 10:08 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3048#issuecomment-1099728251 at 04/14/2022, 04:59 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3048#issuecomment-1100781723 at 04/16/2022, 06:18 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/issues/3068 at 04/19/2022, 10:07 AM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/3068 at 04/19/2022, 10:07 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1102900272 at 04/19/2022, 10:21 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1106949359 at 04/22/2022, 03:28 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1111678732 at 04/27/2022, 07:39 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1112693681 at 04/28/2022, 03:01 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1116371802 at 05/03/2022, 10:41 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1118027375 at 05/04/2022, 04:35 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1120088083 at 05/06/2022, 05:20 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1126576213 at 05/13/2022, 04:26 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1133463183 at 05/20/2022, 04:31 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1140117821 at 05/27/2022, 05:27 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1152793930 at 06/10/2022, 04:12 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1154264042 at 06/13/2022, 11:51 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1155464975 at 06/14/2022, 10:05 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3258#issuecomment-1159780236 at 06/19/2022, 10:24 AM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3258#pullrequestreview-1012812187 at 06/20/2022, 04:29 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/pull/3319 at 06/27/2022, 11:15 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3320#issuecomment-1169230471 at 06/28/2022, 01:51 PM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/2211#issuecomment-1090773428 at 06/28/2022, 07:35 PM PDT
- ericvennemeyer unassigned: https://github.com/hackforla/website/issues/2211#issuecomment-1090773428 at 06/28/2022, 07:36 PM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/3232#issuecomment-1167629697 at 06/28/2022, 07:37 PM PDT
- ericvennemeyer unassigned: https://github.com/hackforla/website/issues/3232#issuecomment-1169470246 at 06/28/2022, 07:37 PM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/3058#issuecomment-1100374784 at 06/28/2022, 07:40 PM PDT
- ericvennemeyer unassigned: https://github.com/hackforla/website/issues/3058#issuecomment-1100374784 at 06/28/2022, 07:45 PM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/3058#issuecomment-1100374784 at 06/28/2022, 07:46 PM PDT
- ericvennemeyer unassigned: https://github.com/hackforla/website/issues/3058#issuecomment-1169474354 at 06/28/2022, 07:46 PM PDT
- ericvennemeyer PR was merged: https://github.com/hackforla/website/pull/3319#event-6904736668 at 06/29/2022, 11:11 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3048#issuecomment-1194656273 at 07/25/2022, 02:32 PM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/2809#issuecomment-1046311281 at 07/26/2022, 04:10 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/2809#issuecomment-1196072629 at 07/26/2022, 04:13 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3048#issuecomment-1196074229 at 07/26/2022, 04:16 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/pull/3430 at 07/26/2022, 04:55 PM PDT
- ericvennemeyer PR was merged: https://github.com/hackforla/website/pull/3430#event-7076221057 at 07/27/2022, 01:05 PM PDT
- ericvennemeyer issue closed by PR 3430: https://github.com/hackforla/website/issues/2809#event-7076221186 at 07/27/2022, 01:05 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3048#issuecomment-1197457053 at 07/27/2022, 03:51 PM PDT
- ericvennemeyer closed as completed: https://github.com/hackforla/website/issues/3048#event-7077001170 at 07/27/2022, 03:51 PM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/3107#issuecomment-1194651649 at 07/27/2022, 04:25 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3107#issuecomment-1197484433 at 07/27/2022, 04:27 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/pull/3435 at 07/27/2022, 04:57 PM PDT
- ericvennemeyer PR was merged: https://github.com/hackforla/website/pull/3435#event-7085944914 at 07/28/2022, 06:18 PM PDT
- ericvennemeyer issue closed by PR 3435: https://github.com/hackforla/website/issues/3107#event-7085944962 at 07/28/2022, 06:18 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3444#issuecomment-1200288855 at 07/30/2022, 01:27 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3444#pullrequestreview-1056497905 at 07/30/2022, 03:29 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3454#issuecomment-1209897036 at 08/09/2022, 02:06 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3454#pullrequestreview-1067507680 at 08/09/2022, 05:02 PM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/3331#issuecomment-1175690910 at 08/11/2022, 11:39 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/3331#issuecomment-1212359612 at 08/11/2022, 11:42 AM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/pull/3462 at 08/11/2022, 12:54 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3460#pullrequestreview-1070289469 at 08/11/2022, 01:03 PM PDT
- ericvennemeyer PR was merged: https://github.com/hackforla/website/pull/3462#event-7176351043 at 08/11/2022, 09:22 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3462#issuecomment-1213281665 at 08/12/2022, 09:10 AM PDT
- ericvennemeyer assigned: https://github.com/hackforla/website/issues/2172#issuecomment-1194658612 at 08/12/2022, 04:30 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/2172#issuecomment-1213589225 at 08/12/2022, 04:33 PM PDT
- ericvennemeyer issue closed as completed: https://github.com/hackforla/website/issues/3331#event-7182381572 at 08/12/2022, 04:42 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3467#issuecomment-1214205901 at 08/13/2022, 11:51 AM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3467#pullrequestreview-1071990588 at 08/13/2022, 12:12 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3470#issuecomment-1217076861 at 08/16/2022, 12:33 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3470#pullrequestreview-1074835583 at 08/16/2022, 03:16 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/2172#issuecomment-1220083477 at 08/18/2022, 04:43 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/issues/2172#issuecomment-1224382184 at 08/23/2022, 10:16 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3480#issuecomment-1224904664 at 08/23/2022, 02:27 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3480#pullrequestreview-1082888190 at 08/23/2022, 02:58 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3476#issuecomment-1225104563 at 08/23/2022, 07:36 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/pull/3483 at 08/24/2022, 11:44 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1226115710 at 08/24/2022, 11:58 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1226143634 at 08/24/2022, 12:21 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1226158433 at 08/24/2022, 12:34 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/pull/3484 at 08/24/2022, 12:42 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/pull/3486 at 08/24/2022, 12:52 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1226212252 at 08/24/2022, 01:01 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1226238633 at 08/24/2022, 01:13 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1226258386 at 08/24/2022, 01:23 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1226346445 at 08/24/2022, 02:06 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1226419209 at 08/24/2022, 02:39 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/issues/3488 at 08/24/2022, 06:34 PM PDT
- ericvennemeyer opened: https://github.com/hackforla/website/issues/3489 at 08/25/2022, 11:42 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1228012626 at 08/25/2022, 08:31 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3476#pullrequestreview-1087592392 at 08/26/2022, 04:45 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3476#issuecomment-1229239297 at 08/27/2022, 11:12 AM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1229265789 at 08/27/2022, 01:56 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3490#issuecomment-1229266650 at 08/27/2022, 02:03 PM PDT
- ericvennemeyer PR was closed: https://github.com/hackforla/website/pull/3484#event-7272846511 at 08/27/2022, 08:34 PM PDT
- ericvennemeyer PR was closed: https://github.com/hackforla/website/pull/3486#event-7272846974 at 08/27/2022, 08:35 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3490#pullrequestreview-1087899982 at 08/28/2022, 11:52 AM PDT
- ericvennemeyer PR was merged: https://github.com/hackforla/website/pull/3483#event-7274130745 at 08/28/2022, 04:18 PM PDT
- ericvennemeyer issue closed by PR 3483: https://github.com/hackforla/website/issues/2172#event-7274130772 at 08/28/2022, 04:18 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3483#issuecomment-1229691050 at 08/28/2022, 07:55 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3497#issuecomment-1230692466 at 08/29/2022, 11:22 AM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3497#pullrequestreview-1089266730 at 08/29/2022, 12:45 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3476#issuecomment-1232088388 at 08/30/2022, 12:41 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3446#issuecomment-1233329231 at 08/31/2022, 12:19 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3476#issuecomment-1234924450 at 09/01/2022, 05:00 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3446#pullrequestreview-1095160048 at 09/02/2022, 10:22 AM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3516#pullrequestreview-1095414031 at 09/02/2022, 04:09 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3476#issuecomment-1238596025 at 09/06/2022, 01:03 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3476#issuecomment-1239739318 at 09/07/2022, 11:35 AM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3476#pullrequestreview-1101365344 at 09/08/2022, 01:19 PM PDT
- ericvennemeyer submitted review: https://github.com/hackforla/website/pull/3446#pullrequestreview-1104940196 at 09/12/2022, 04:22 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3548#issuecomment-1246025009 at 09/13/2022, 03:50 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3548#issuecomment-1246039385 at 09/13/2022, 04:09 PM PDT
- ericvennemeyer commented on: https://github.com/hackforla/website/pull/3548#issuecomment-1246059239 at 09/13/2022, 04:41 PM PDT
