### ISSUE TITLE
Pre-work Checklist: Developer: Trisha Johnson

### ISSUE THREAD

**Issue by trishajjohnson** [hackforla/website#3049]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address and GitHub handle with the team lead so you can be added to the Google Drive and the website-write team
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue
  - Good second issue
  - Small 
  - Medium 
  - Large
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [ ] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@trishajjohnson Hi Trisha, I just noticed that you haven't updated any of your issues with the weekly progress report using the following format:
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA

So, I have unchecked the corresponding action item. Please feel free to check it off again once you are done with it. Thank you.

**Comment by trishajjohnson** [comment]
Progress Update:

1. Progress - just about finished. Just need to post this update and close issue.
2. Blockers - none.
3. Availability - 6hrs this week.
4. ETA - end of day Wednesday.

**Comment by trishajjohnson** [comment]
@SAUMILDHANKAR how do I close this issue once all tasks are done?

**Comment by SAUMILDHANKAR** [comment]
@trishajjohnson Sorry, I was not clear enough in my earlier comment but the weekly progress update needs to be posted in the issue that you are currently working on (other than this prework issue). So, I am unchecking the action item for now but please feel free to check it off once you post on an issue. Thank you.

FYI: To close an issue, just click on close issue button at the bottom of the issue.

**Comment by ExperimentsInHonesty** [comment]
@trishajjohnson - Just checking in with you to see how onboarding is going.  It looks like you finished your first issue.  Congrats.  On your second issue (the one you are working on now), it looks like you have not moved it to the in progress column.  Please do that.
https://github.com/hackforla/website/issues/2892

**Comment by trishajjohnson** [comment]
Progress: All items are completed, just needs to be closed.
Blockers: None
Availability: 6hrs
ETA: End of week.
Pictures: None

**Comment by trishajjohnson** [comment]
@SAUMILDHANKAR may I close this issue now?

**Comment by SAUMILDHANKAR** [comment]
@trishajjohnson Hi Trisha, just a reminder, you can close this issue. Thank you.

**Comment by HackforLABot** [comment]
## Activity Log: trishajjohnson
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- trishajjohnson opened: https://github.com/hackforla/website/issues/3049 at 04/12/2022, 08:10 PM PDT
- trishajjohnson assigned: https://github.com/hackforla/website/issues/3049#issuecomment-1097506176 at 04/12/2022, 08:20 PM PDT
- trishajjohnson assigned: https://github.com/hackforla/website/issues/2913#issuecomment-1056028927 at 04/19/2022, 05:09 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/2913#issuecomment-1103285155 at 04/19/2022, 05:17 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/2913#issuecomment-1103351500 at 04/19/2022, 06:42 PM PDT
- trishajjohnson opened: https://github.com/hackforla/website/pull/3072 at 04/20/2022, 04:40 PM PDT
- trishajjohnson issue closed by PR 3072: https://github.com/hackforla/website/issues/2913#event-6475056474 at 04/21/2022, 07:13 PM PDT
- trishajjohnson PR was merged: https://github.com/hackforla/website/pull/3072#event-6475056487 at 04/21/2022, 07:13 PM PDT
- trishajjohnson assigned: https://github.com/hackforla/website/issues/3041#issuecomment-1094362337 at 04/23/2022, 04:22 PM PDT
- trishajjohnson unassigned: https://github.com/hackforla/website/issues/3041#issuecomment-1094362337 at 04/23/2022, 04:27 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3079#issuecomment-1107943082 at 04/24/2022, 04:57 PM PDT
- trishajjohnson submitted review: https://github.com/hackforla/website/pull/3079#pullrequestreview-951357951 at 04/24/2022, 10:25 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/3049#issuecomment-1110439359 at 04/26/2022, 06:40 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/3049#issuecomment-1110439874 at 04/26/2022, 06:41 PM PDT
- trishajjohnson assigned: https://github.com/hackforla/website/issues/2892#issuecomment-1051648112 at 04/26/2022, 07:31 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/2892#issuecomment-1110467109 at 04/26/2022, 07:32 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/2892#issuecomment-1119757696 at 05/06/2022, 08:47 AM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/3049#issuecomment-1119820963 at 05/06/2022, 10:05 AM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/3049#issuecomment-1119821384 at 05/06/2022, 10:06 AM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/2892#issuecomment-1119822672 at 05/06/2022, 10:08 AM PDT
- trishajjohnson opened: https://github.com/hackforla/website/pull/3108 at 05/06/2022, 02:19 PM PDT
- trishajjohnson issue closed by PR 3108: https://github.com/hackforla/website/issues/2892#event-6568169460 at 05/07/2022, 08:39 PM PDT
- trishajjohnson PR was merged: https://github.com/hackforla/website/pull/3108#event-6568169465 at 05/07/2022, 08:39 PM PDT
- trishajjohnson assigned: https://github.com/hackforla/website/issues/3084#issuecomment-1114044814 at 05/16/2022, 10:58 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/3084#issuecomment-1128447278 at 05/16/2022, 11:03 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/2723#issuecomment-1130892847 at 05/18/2022, 06:03 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/2723#issuecomment-1132400638 at 05/19/2022, 07:48 PM PDT
- trishajjohnson submitted review: https://github.com/hackforla/website/pull/2723#pullrequestreview-979558603 at 05/19/2022, 11:04 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/issues/3084#issuecomment-1132573599 at 05/20/2022, 12:28 AM PDT
- trishajjohnson opened: https://github.com/hackforla/website/pull/3162 at 05/20/2022, 01:05 AM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3162#issuecomment-1136555166 at 05/24/2022, 05:19 PM PDT
- trishajjohnson closed as completed: https://github.com/hackforla/website/issues/3049#event-6673764056 at 05/24/2022, 07:25 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3162#issuecomment-1138168234 at 05/25/2022, 10:28 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3174#issuecomment-1138178248 at 05/25/2022, 10:48 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3173#issuecomment-1138178978 at 05/25/2022, 10:50 PM PDT
- trishajjohnson submitted review: https://github.com/hackforla/website/pull/3173#pullrequestreview-986836268 at 05/26/2022, 02:57 PM PDT
- trishajjohnson submitted review: https://github.com/hackforla/website/pull/3174#pullrequestreview-986921290 at 05/26/2022, 05:17 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3162#issuecomment-1145111190 at 06/02/2022, 10:19 AM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3193#issuecomment-1145166764 at 06/02/2022, 11:12 AM PDT
- trishajjohnson submitted review: https://github.com/hackforla/website/pull/3193#pullrequestreview-993975088 at 06/02/2022, 11:16 AM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3178#issuecomment-1145186287 at 06/02/2022, 11:33 AM PDT
- trishajjohnson submitted review: https://github.com/hackforla/website/pull/3178#pullrequestreview-994009977 at 06/02/2022, 11:49 AM PDT
- trishajjohnson issue closed by PR 3162: https://github.com/hackforla/website/issues/3084#event-6825721802 at 06/16/2022, 07:48 PM PDT
- trishajjohnson PR was merged: https://github.com/hackforla/website/pull/3162#event-6825721810 at 06/16/2022, 07:48 PM PDT
- trishajjohnson commented on: https://github.com/hackforla/website/pull/3338#issuecomment-1178081819 at 07/07/2022, 11:57 AM PDT
- trishajjohnson submitted review: https://github.com/hackforla/website/pull/3338#pullrequestreview-1032381668 at 07/07/2022, 09:14 PM PDT
