### ISSUE TITLE
Pre-work Checklist: Developer: Wilny Duong

### ISSUE THREAD

**Issue by Wny-Duong** [hackforla/website#3053]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address and GitHub handle with the team lead so you can be added to the Google Drive and the website-write team
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) 
- [x] Confirm with the team lead that they have added you to the zoom meeting calendar invites and GitHub repository
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [ ] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue
  - Good second issue
  - Small 
  - Medium 
  - Large
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [ ] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@Wny-Duong Thanks for adding the role labels to this issue, good job. Please feel free to check off the corresponding action item above.

**Comment by Wny-Duong** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?

Spread out over three days, only about 5 hours in total. 3 hours for meetings and orientation/onboarding stuff and getting  added to drives and Github. 2 hours of actually reading through, assigning myself to an issue, and setting up the environment with the forking, Docker installation, etc. (I'm ignoring the amount of time taken up from the Jekyll image issue since a temporary fix was found for that).

**Comment by Wny-Duong** [comment]
Progress: I still have the small, medium, and large issues remaining. Every else is complete.
Blockers: My time availability has prevented me from getting a satisfactory amount of work done this week. My time availability should become more free in following week.
Availability: 8 hours this week and the next foreseeable weeks.
ETA: May 22nd, assuming at least one issue gets completed every week on average.

**Comment by SAUMILDHANKAR** [comment]
@Wny-Duong You can check off the action item about progressing through issues small, medium, large as it is just for your understanding and you are aware of it now. However, the weekly progress report which has to posted on an issue other than this prework issue using the following format:
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA

is still pending. Once you do that you can check off the corresponding item. If all the action items in this prework are checked off, you can close this issue. Thank you.

**Comment by Wny-Duong** [comment]
I didn't realize that I missed that checkbox. Thanks for reminding me, Saumil.

**Comment by SAUMILDHANKAR** [comment]
@Wny-Duong Great job in finishing up with all the action items in this issue. You can close this issue now. Thank you.

**Comment by HackforLABot** [comment]
## Activity Log: Wny-Duong
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Wny-Duong opened: https://github.com/hackforla/website/issues/3053 at 04/14/2022, 07:28 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/3053#issuecomment-1099793707 at 04/14/2022, 07:34 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/2912#issuecomment-1055993965 at 04/17/2022, 06:54 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2912#issuecomment-1101020334 at 04/17/2022, 06:57 PM PDT
- Wny-Duong opened: https://github.com/hackforla/website/pull/3062 at 04/17/2022, 08:42 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2912#issuecomment-1101063857 at 04/17/2022, 08:47 PM PDT
- Wny-Duong issue closed by PR 3062: https://github.com/hackforla/website/issues/2912#event-6451889113 at 04/18/2022, 09:48 PM PDT
- Wny-Duong PR was merged: https://github.com/hackforla/website/pull/3062#event-6451889122 at 04/18/2022, 09:48 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/3053#issuecomment-1103217356 at 04/19/2022, 03:09 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/2183 at 04/23/2022, 02:59 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2183#issuecomment-1107872204 at 04/24/2022, 09:16 AM PDT
- Wny-Duong opened: https://github.com/hackforla/website/pull/3081 at 04/24/2022, 07:59 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3081#issuecomment-1108917951 at 04/25/2022, 11:47 AM PDT
- Wny-Duong issue closed by PR 3081: https://github.com/hackforla/website/issues/2183#event-6499342361 at 04/26/2022, 07:25 AM PDT
- Wny-Duong PR was merged: https://github.com/hackforla/website/pull/3081#event-6499342389 at 04/26/2022, 07:25 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3083#issuecomment-1112826862 at 04/28/2022, 07:41 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3083#issuecomment-1113742742 at 04/29/2022, 02:18 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3083#pullrequestreview-958265655 at 04/29/2022, 02:20 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/3053#issuecomment-1119339145 at 05/06/2022, 12:34 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/3053#issuecomment-1120312517 at 05/07/2022, 03:54 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/2728#issuecomment-1104513498 at 05/07/2022, 04:10 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2728#issuecomment-1120314246 at 05/07/2022, 04:12 PM PDT
- Wny-Duong opened: https://github.com/hackforla/website/pull/3114 at 05/08/2022, 06:51 PM PDT
- Wny-Duong issue closed by PR 3114: https://github.com/hackforla/website/issues/2728#event-6583589902 at 05/10/2022, 09:39 AM PDT
- Wny-Duong PR was merged: https://github.com/hackforla/website/pull/3114#event-6583589922 at 05/10/2022, 09:39 AM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/2554#issuecomment-1013943263 at 05/20/2022, 06:51 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2554#issuecomment-1132929691 at 05/20/2022, 06:55 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2554#issuecomment-1140187388 at 05/27/2022, 11:38 PM PDT
- Wny-Duong opened: https://github.com/hackforla/website/pull/3183 at 05/30/2022, 06:37 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3185#issuecomment-1143030922 at 05/31/2022, 06:54 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3185#pullrequestreview-991343330 at 05/31/2022, 08:00 PM PDT
- Wny-Duong closed as completed: https://github.com/hackforla/website/issues/3053#event-6734219425 at 06/03/2022, 12:22 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3185#pullrequestreview-995941128 at 06/04/2022, 10:15 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3221#issuecomment-1147459687 at 06/06/2022, 06:40 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3224#issuecomment-1147460257 at 06/06/2022, 06:40 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3221#pullrequestreview-996960131 at 06/06/2022, 10:47 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3224#pullrequestreview-996981297 at 06/06/2022, 11:03 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3224#pullrequestreview-997545155 at 06/06/2022, 11:05 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3226#issuecomment-1148234279 at 06/06/2022, 11:07 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3226#pullrequestreview-997549100 at 06/06/2022, 11:10 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3225#issuecomment-1148953055 at 06/07/2022, 10:18 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3225#pullrequestreview-998636523 at 06/07/2022, 11:10 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3231#issuecomment-1150286397 at 06/08/2022, 12:02 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3231#pullrequestreview-1000295598 at 06/08/2022, 12:06 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3235#issuecomment-1151670801 at 06/09/2022, 03:10 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3235#pullrequestreview-1002066063 at 06/09/2022, 03:21 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/2909#issuecomment-1141521069 at 06/21/2022, 07:44 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/2909#issuecomment-1141521069 at 06/21/2022, 07:44 PM PDT
- Wny-Duong unassigned: https://github.com/hackforla/website/issues/2909#issuecomment-1141521069 at 06/21/2022, 07:45 PM PDT
- Wny-Duong unassigned: https://github.com/hackforla/website/issues/2909#issuecomment-1141521069 at 06/21/2022, 07:45 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3225#issuecomment-1166585216 at 06/26/2022, 09:48 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3225#pullrequestreview-1020890715 at 06/27/2022, 04:17 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/3315#issuecomment-1166741594 at 06/28/2022, 07:38 PM PDT
- Wny-Duong unassigned: https://github.com/hackforla/website/issues/3315#issuecomment-1166741594 at 06/28/2022, 07:38 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3324#issuecomment-1170318260 at 06/29/2022, 11:04 AM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3319#event-6904736668 at 06/29/2022, 11:11 AM PDT
- Wny-Duong closed by PR 3322: https://github.com/hackforla/website/issues/3236#event-6904923134 at 06/29/2022, 11:38 AM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3322#event-6904923179 at 06/29/2022, 11:38 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3324#pullrequestreview-1023861267 at 06/29/2022, 12:06 PM PDT
- Wny-Duong closed by PR 3324: https://github.com/hackforla/website/issues/3135#event-6905118610 at 06/29/2022, 12:08 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3324#event-6905118630 at 06/29/2022, 12:08 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3225#pullrequestreview-1024147538 at 06/29/2022, 05:54 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3321#issuecomment-1170744038 at 06/29/2022, 09:27 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3321#pullrequestreview-1025470666 at 06/30/2022, 01:43 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3326#issuecomment-1171658619 at 06/30/2022, 01:44 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3326#pullrequestreview-1025490264 at 06/30/2022, 02:03 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3327#issuecomment-1172389267 at 07/01/2022, 07:08 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3327#issuecomment-1172424091 at 07/01/2022, 07:45 AM PDT
- Wny-Duong closed by PR 3225: https://github.com/hackforla/website/issues/2097#event-6921512921 at 07/01/2022, 05:22 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3225#event-6921512923 at 07/01/2022, 05:22 PM PDT
- Wny-Duong closed by PR 3321: https://github.com/hackforla/website/issues/3257#event-6921545448 at 07/01/2022, 05:54 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3321#event-6921545450 at 07/01/2022, 05:54 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3327#pullrequestreview-1026780365 at 07/02/2022, 11:44 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3327#pullrequestreview-1026813474 at 07/02/2022, 11:43 PM PDT
- Wny-Duong opened: https://github.com/hackforla/website/pull/3332 at 07/05/2022, 07:26 PM PDT
- Wny-Duong closed by PR 3321: https://github.com/hackforla/website/issues/3257#event-6938828809 at 07/05/2022, 07:36 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3332#event-6938828825 at 07/05/2022, 07:36 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3329#issuecomment-1177084001 at 07/06/2022, 10:18 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3329#pullrequestreview-1031994669 at 07/07/2022, 11:23 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3329#issuecomment-1178051558 at 07/07/2022, 11:34 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3330#issuecomment-1179447162 at 07/08/2022, 05:51 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3338#issuecomment-1179447237 at 07/08/2022, 05:51 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3330#pullrequestreview-1033462750 at 07/08/2022, 06:05 PM PDT
- Wny-Duong closed by PR 3330: https://github.com/hackforla/website/issues/3217#event-6963248408 at 07/08/2022, 06:09 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3330#event-6963248410 at 07/08/2022, 06:09 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3338#pullrequestreview-1033576263 at 07/09/2022, 04:25 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3338#event-6964440313 at 07/09/2022, 04:26 PM PDT
- Wny-Duong closed by PR 3329: https://github.com/hackforla/website/issues/2112#event-6964460687 at 07/09/2022, 05:05 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3329#event-6964460690 at 07/09/2022, 05:05 PM PDT
- Wny-Duong PR was merged: https://github.com/hackforla/website/pull/3183#event-6982036591 at 07/12/2022, 06:14 PM PDT
- Wny-Duong opened: https://github.com/hackforla/website/issues/3364 at 07/12/2022, 08:12 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/3364#issuecomment-1182715265 at 07/12/2022, 08:13 PM PDT
- Wny-Duong closed by PR 3363: https://github.com/hackforla/website/issues/2817#event-6986692300 at 07/13/2022, 07:45 AM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3363#event-6986692338 at 07/13/2022, 07:45 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3369#issuecomment-1183992392 at 07/13/2022, 10:05 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3369#pullrequestreview-1038319649 at 07/13/2022, 10:43 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3369#pullrequestreview-1039324373 at 07/14/2022, 11:37 AM PDT
- Wny-Duong closed by PR 3369: https://github.com/hackforla/website/issues/2875#event-6997164875 at 07/14/2022, 01:23 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3369#event-6997164893 at 07/14/2022, 01:23 PM PDT
- Wny-Duong assigned: https://github.com/hackforla/website/issues/2502#issuecomment-1173148805 at 07/14/2022, 07:07 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2502#issuecomment-1185096329 at 07/14/2022, 07:12 PM PDT
- Wny-Duong closed by PR 3372: https://github.com/hackforla/website/issues/2812#event-7005276916 at 07/15/2022, 04:36 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3372#event-7005276927 at 07/15/2022, 04:36 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3371#issuecomment-1186024916 at 07/15/2022, 04:40 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3371#pullrequestreview-1040896200 at 07/15/2022, 04:56 PM PDT
- Wny-Duong closed by PR 3371: https://github.com/hackforla/website/issues/3306#event-7005324394 at 07/15/2022, 04:59 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3371#event-7005324401 at 07/15/2022, 04:59 PM PDT
- Wny-Duong opened: https://github.com/hackforla/website/issues/3400 at 07/19/2022, 08:14 PM PDT
- Wny-Duong closed by PR 3390: https://github.com/hackforla/website/issues/3094#event-7031138790 at 07/20/2022, 09:44 AM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3390#event-7031138806 at 07/20/2022, 09:44 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3395#issuecomment-1190514167 at 07/20/2022, 09:45 AM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3395#pullrequestreview-1045417608 at 07/20/2022, 10:25 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3407#issuecomment-1190814564 at 07/20/2022, 03:14 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3407#pullrequestreview-1045737138 at 07/20/2022, 03:21 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3407#event-7033303436 at 07/20/2022, 03:22 PM PDT
- Wny-Duong closed by PR 3407: https://github.com/hackforla/website/issues/3026#event-7033303509 at 07/20/2022, 03:22 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3393#event-7047132854 at 07/22/2022, 07:51 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2502#issuecomment-1193029515 at 07/22/2022, 06:13 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3421#event-7051448308 at 07/24/2022, 06:49 AM PDT
- Wny-Duong closed by PR 3421: https://github.com/hackforla/website/issues/2813#event-7051448332 at 07/24/2022, 06:49 AM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3427#event-7068760501 at 07/26/2022, 04:46 PM PDT
- Wny-Duong closed by PR 3427: https://github.com/hackforla/website/issues/2815#event-7068760589 at 07/26/2022, 04:46 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3432#issuecomment-1197050720 at 07/27/2022, 10:03 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3432#issuecomment-1197314268 at 07/27/2022, 01:09 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3435#issuecomment-1198726154 at 07/28/2022, 04:36 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3432#issuecomment-1198728153 at 07/28/2022, 04:40 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3432#pullrequestreview-1054905683 at 07/28/2022, 06:01 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3435#pullrequestreview-1054912602 at 07/28/2022, 06:17 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3435#event-7085944914 at 07/28/2022, 06:18 PM PDT
- Wny-Duong closed by PR 3435: https://github.com/hackforla/website/issues/3107#event-7085944962 at 07/28/2022, 06:18 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3439#issuecomment-1198786996 at 07/28/2022, 06:19 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3439#pullrequestreview-1054920582 at 07/28/2022, 06:35 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3439#event-7085994921 at 07/28/2022, 06:35 PM PDT
- Wny-Duong closed by PR 3439: https://github.com/hackforla/website/issues/2816#event-7085994994 at 07/28/2022, 06:35 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3432#pullrequestreview-1054953613 at 07/28/2022, 07:48 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3443#pullrequestreview-1054956445 at 07/28/2022, 07:55 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3442#issuecomment-1198829010 at 07/28/2022, 07:57 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3442#pullrequestreview-1054959519 at 07/28/2022, 08:01 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3442#event-7089999633 at 07/29/2022, 07:40 AM PDT
- Wny-Duong closed by PR 3442: https://github.com/hackforla/website/issues/3400#event-7089999767 at 07/29/2022, 07:40 AM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3443#event-7090876602 at 07/29/2022, 09:51 AM PDT
- Wny-Duong closed by PR 3443: https://github.com/hackforla/website/issues/3166#event-7090876707 at 07/29/2022, 09:51 AM PDT
- Wny-Duong issue closed as completed: https://github.com/hackforla/website/issues/2554#event-7106183068 at 08/01/2022, 07:45 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/issues/2502#issuecomment-1207085201 at 08/05/2022, 04:23 PM PDT
- Wny-Duong opened: https://github.com/hackforla/website/pull/3452 at 08/07/2022, 11:41 AM PDT
- Wny-Duong issue closed as not planned: https://github.com/hackforla/website/issues/3364#event-7149834336 at 08/08/2022, 12:37 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3454#event-7168558040 at 08/10/2022, 08:57 PM PDT
- Wny-Duong closed by PR 3454: https://github.com/hackforla/website/issues/3339#event-7168558083 at 08/10/2022, 08:57 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3161#pullrequestreview-1069231945 at 08/10/2022, 11:33 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3456#issuecomment-1211602319 at 08/10/2022, 11:36 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3462#issuecomment-1212463647 at 08/11/2022, 01:30 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3462#pullrequestreview-1070391299 at 08/11/2022, 02:33 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3456#pullrequestreview-1070405128 at 08/11/2022, 02:49 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3462#event-7176351043 at 08/11/2022, 09:22 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3466#issuecomment-1213451277 at 08/12/2022, 12:34 PM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3457#event-7181578127 at 08/12/2022, 12:48 PM PDT
- Wny-Duong closed as completed: https://github.com/hackforla/website/issues/3331#event-7182381572 at 08/12/2022, 04:42 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3466#pullrequestreview-1071846315 at 08/12/2022, 04:49 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3452#issuecomment-1216941390 at 08/16/2022, 10:31 AM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3452#issuecomment-1218305413 at 08/17/2022, 10:30 AM PDT
- Wny-Duong merged: https://github.com/hackforla/website/pull/3468#event-7210331226 at 08/17/2022, 07:32 PM PDT
- Wny-Duong commented on: https://github.com/hackforla/website/pull/3452#issuecomment-1220167017 at 08/18/2022, 07:20 PM PDT
- Wny-Duong submitted review: https://github.com/hackforla/website/pull/3476#pullrequestreview-1079732538 at 08/21/2022, 04:32 PM PDT
- Wny-Duong PR was merged: https://github.com/hackforla/website/pull/3452#event-7263692114 at 08/25/2022, 05:59 PM PDT
- Wny-Duong issue closed by PR 3452: https://github.com/hackforla/website/issues/2502#event-7263692177 at 08/25/2022, 05:59 PM PDT
