### ISSUE TITLE
Pre-work Checklist: Developer: Olanrewaju Akinola

### ISSUE THREAD

**Issue by Olanrewaju-Ak** [hackforla/website#3065]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] Also, confirm with the team lead that they have added you to the Zoom meeting calendar invites
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
- [x] After you have finished adding yourself to the roster, let a team lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
  - [x] Use the information from part 2 to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
- [x] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue (one per person)
  - Good second issue (one per person)
  - Small (one per person, with some exceptions, see below)
  - Medium (you can work on more than one medium issue, but only one at a time)
  - Large (you can work on more than one large issue, but only one at a time)
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
    - You can work on back-to-back small issues if it meets the following criteria:
      - You are learning something new and need to work on an issue of a lesser complexity
      - Special request by a lead or pm
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@Olanrewaju-Ak I remember from our last meeting you were setting up your dev environment. Just wanted to follow up on that if it is going well. Please feel free to post on our [hfla-site slack channel](https://app.slack.com/client/T04502KQX/C4UM52W93) if you have any questions or need help. Thank you,

**Comment by Olanrewaju-Ak** [comment]
> @Olanrewaju-Ak I remember from our last meeting you were setting up your dev environment. Just wanted to follow up on that if it is going well. Please feel free to post on our [hfla-site slack channel](https://app.slack.com/client/T04502KQX/C4UM52W93) if you have any questions or need help. Thank you,

**Comment by Olanrewaju-Ak** [comment]
> @Olanrewaju-Ak I remember from our last meeting you were setting up your dev environment. Just wanted to follow up on that if it is going well. Please feel free to post on our [hfla-site slack channel](https://app.slack.com/client/T04502KQX/C4UM52W93) if you have any questions or need help. Thank you,

Hello @SAUMILDHANKAR , i had issues installing the docker desktop because it does not run on Windows 10 Home. I had to download Docker Toolbox and VirtualBox. After installing and trying the docker compose-up code from the guideline, it does not seem to be working well. I will post pictures on the slack channel so you or anyone else could help

**Comment by ExperimentsInHonesty** [comment]
Please don't close the issue until we get you fully onboarded.

**Comment by SAUMILDHANKAR** [comment]
@Olanrewaju-Ak Just wanted to follow up and check if you were able to set up your Docker based on the discussion on slack. Please let us know if you have more questions. If your blocker is resolved now. you can go ahead and pick up your good first issue. Thanks.

**Comment by Olanrewaju-Ak** [comment]
@SAUMILDHANKAR I have been able to resolve it. I will go ahead to work on my first issue. Thank you

**Comment by SAUMILDHANKAR** [comment]
@Olanrewaju-Ak I have unchecked your weekly progress report action item as you haven't posted an update using the format in any of your issues. Also, please pick up your good second issue next. Thank you.

**Comment by Olanrewaju-Ak** [comment]
1. Progress: Worked on Good second issue #2922. pull request created
2. Blockers: none
3.Availability: 
4. ETA: 30/5
5. Pictures: None

**Comment by Olanrewaju-Ak** [comment]
1. Progress: Worked on a small issue: CONTRIBUTING.md: Additional Column Filtering Description in Section 2.2 #3018, pull request created
2. Blockers: none
3. Availability:
4. ETA: 6/10
5.Pictures: 
![2-After](https://user-images.githubusercontent.com/103976465/172709913-f598ad90-184c-4763-91bf-e5cd527c0a59.jpg)

**Comment by Olanrewaju-Ak** [comment]
Progress: I have completed all the tasks in this issue
Blockers: none

**Comment by Sparky-code** [comment]
@Olanrewaju-Ak Looks like you're well and onboarded now, thank you for posting the issue updates.

**Comment by HackforLABot** [comment]
## Activity Log: Olanrewaju-Ak
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Olanrewaju-Ak opened: https://github.com/hackforla/website/issues/3065 at 04/18/2022, 08:28 PM PDT
- Olanrewaju-Ak assigned: https://github.com/hackforla/website/issues/3065#issuecomment-1101956564 at 04/18/2022, 08:29 PM PDT
- Olanrewaju-Ak closed as completed: https://github.com/hackforla/website/issues/3065#event-6517416439 at 04/28/2022, 11:31 AM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/issues/3065#issuecomment-1112536529 at 04/28/2022, 11:36 AM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/issues/3065#issuecomment-1120445308 at 05/08/2022, 09:09 AM PDT
- Olanrewaju-Ak assigned: https://github.com/hackforla/website/issues/3026#issuecomment-1086584020 at 05/08/2022, 09:35 AM PDT
- Olanrewaju-Ak unassigned: https://github.com/hackforla/website/issues/3026#issuecomment-1086584020 at 05/08/2022, 09:37 AM PDT
- Olanrewaju-Ak assigned: https://github.com/hackforla/website/issues/2953#issuecomment-1063718387 at 05/08/2022, 09:42 AM PDT
- Olanrewaju-Ak unassigned: https://github.com/hackforla/website/issues/2953#issuecomment-1063718387 at 05/08/2022, 09:44 AM PDT
- Olanrewaju-Ak assigned: https://github.com/hackforla/website/issues/2953#issuecomment-1063718387 at 05/08/2022, 09:44 AM PDT
- Olanrewaju-Ak opened: https://github.com/hackforla/website/pull/3116 at 05/09/2022, 01:55 PM PDT
- Olanrewaju-Ak PR was closed: https://github.com/hackforla/website/pull/3116#event-6609335425 at 05/13/2022, 06:40 PM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/pull/3116#issuecomment-1126801518 at 05/14/2022, 12:46 PM PDT
- Olanrewaju-Ak unassigned: https://github.com/hackforla/website/issues/2953#issuecomment-1063718387 at 05/20/2022, 02:14 PM PDT
- Olanrewaju-Ak assigned: https://github.com/hackforla/website/issues/2794#issuecomment-1045512593 at 05/22/2022, 09:59 AM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/issues/2794#issuecomment-1133935986 at 05/22/2022, 10:06 AM PDT
- Olanrewaju-Ak opened: https://github.com/hackforla/website/pull/3171 at 05/23/2022, 03:28 PM PDT
- Olanrewaju-Ak issue closed by PR 3171: https://github.com/hackforla/website/issues/2794#event-6665303518 at 05/23/2022, 07:37 PM PDT
- Olanrewaju-Ak PR was merged: https://github.com/hackforla/website/pull/3171#event-6665303527 at 05/23/2022, 07:37 PM PDT
- Olanrewaju-Ak assigned: https://github.com/hackforla/website/issues/2922#issuecomment-1058577349 at 05/29/2022, 02:50 AM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/issues/2922#issuecomment-1140414571 at 05/29/2022, 02:51 AM PDT
- Olanrewaju-Ak opened: https://github.com/hackforla/website/pull/3178 at 05/29/2022, 04:29 AM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/issues/3065#issuecomment-1140429916 at 05/29/2022, 04:35 AM PDT
- Olanrewaju-Ak PR was merged: https://github.com/hackforla/website/pull/3178#event-6741072476 at 06/03/2022, 09:14 PM PDT
- Olanrewaju-Ak unassigned: https://github.com/hackforla/website/issues/2922#event-6741072471 at 06/08/2022, 11:19 AM PDT
- Olanrewaju-Ak assigned: https://github.com/hackforla/website/issues/3110#issuecomment-1120046677 at 06/08/2022, 11:47 AM PDT
- Olanrewaju-Ak unassigned: https://github.com/hackforla/website/issues/3110#issuecomment-1120046677 at 06/08/2022, 11:48 AM PDT
- Olanrewaju-Ak assigned: https://github.com/hackforla/website/issues/3018#issuecomment-1089447945 at 06/08/2022, 12:03 PM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/issues/3018#issuecomment-1150289563 at 06/08/2022, 12:04 PM PDT
- Olanrewaju-Ak opened: https://github.com/hackforla/website/pull/3235 at 06/08/2022, 12:38 PM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/issues/3065#issuecomment-1150370448 at 06/08/2022, 01:22 PM PDT
- Olanrewaju-Ak issue closed by PR 3235: https://github.com/hackforla/website/issues/3018#event-6825256424 at 06/16/2022, 06:02 PM PDT
- Olanrewaju-Ak PR was merged: https://github.com/hackforla/website/pull/3235#event-6825256434 at 06/16/2022, 06:02 PM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/pull/3260#issuecomment-1159781502 at 06/19/2022, 10:33 AM PDT
- Olanrewaju-Ak submitted review: https://github.com/hackforla/website/pull/3260#pullrequestreview-1012582182 at 06/20/2022, 10:26 AM PDT
- Olanrewaju-Ak commented on: https://github.com/hackforla/website/issues/3065#issuecomment-1163833673 at 06/22/2022, 06:48 PM PDT
- Olanrewaju-Ak issue closed as completed: https://github.com/hackforla/website/issues/3065#event-6869513457 at 06/23/2022, 01:49 PM PDT
