### ISSUE TITLE
Pre-work Checklist: Designer: Jonathan Nathan

### ISSUE THREAD

**Issue by nathan944** [hackforla/website#3066]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the team lead
- [x] (Once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Confirm with the team lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [x] Self Assign yourself to this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings: 
   - [x] UX weekly team meeting, Thursdays 5pm PST
   - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Review [Design_Short Term Goals, Plan, and Tasks](https://docs.google.com/document/d/1FxwgdnWBbbQ8Pi3tspnukZTWwXtqnRXfNkNhVMEloY0/edit)
- [x] Review the [Start Here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465) and [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) pages in Figma
- [x] Review the [prioritized Backlog to see what Design Issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257) are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Once you accept an issue, please add your "Availability for this week" in that new issue's comment section using the 4 statuses below.
```
Availability for this week:

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
Images: "Add any images that would better help convey your progress of the issue."
```
### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by HackforLABot** [comment]
## Activity Log: nathan944
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- nathan944 opened: https://github.com/hackforla/website/issues/3066 at 04/18/2022, 08:50 PM PDT
- nathan944 assigned: https://github.com/hackforla/website/issues/3066#issuecomment-1101965181 at 04/18/2022, 08:51 PM PDT
- nathan944 assigned: https://github.com/hackforla/website/issues/2501#issuecomment-1089607678 at 04/20/2022, 03:49 PM PDT
- nathan944 commented on: https://github.com/hackforla/website/issues/2501#issuecomment-1106865428 at 04/22/2022, 02:08 PM PDT
- nathan944 issue closed as completed: https://github.com/hackforla/website/issues/3066#event-6486152874 at 04/24/2022, 10:50 AM PDT
- nathan944 assigned: https://github.com/hackforla/website/issues/2601#issuecomment-1006992697 at 04/24/2022, 10:56 AM PDT
- nathan944 assigned: https://github.com/hackforla/website/issues/2694#issuecomment-1099560647 at 05/01/2022, 09:16 AM PDT
- nathan944 unassigned: https://github.com/hackforla/website/issues/2601#issuecomment-1006992697 at 05/04/2022, 01:45 PM PDT
- nathan944 unassigned: https://github.com/hackforla/website/issues/2694#issuecomment-1099560647 at 05/04/2022, 01:45 PM PDT
- nathan944 assigned: https://github.com/hackforla/website/issues/2601#issuecomment-1122945325 at 05/21/2022, 06:57 PM PDT
- nathan944 commented on: https://github.com/hackforla/website/issues/2601#issuecomment-1140504917 at 05/29/2022, 11:53 AM PDT
- nathan944 commented on: https://github.com/hackforla/website/issues/2601#issuecomment-1144245027 at 06/01/2022, 04:30 PM PDT
- nathan944 unassigned: https://github.com/hackforla/website/issues/2601#issuecomment-1152055030 at 06/12/2022, 11:48 AM PDT
- nathan944 assigned: https://github.com/hackforla/website/issues/916#issuecomment-979746665 at 06/12/2022, 12:06 PM PDT
- nathan944 commented on: https://github.com/hackforla/website/issues/2601#issuecomment-1153369689 at 06/12/2022, 06:41 PM PDT
- nathan944 opened: https://github.com/hackforla/website/issues/3302 at 06/25/2022, 04:39 PM PDT
- nathan944 assigned: https://github.com/hackforla/website/issues/3302 at 06/25/2022, 04:39 PM PDT
- nathan944 commented on: https://github.com/hackforla/website/issues/916#issuecomment-1166400249 at 06/25/2022, 07:18 PM PDT
- nathan944 opened: https://github.com/hackforla/website/issues/3370 at 07/13/2022, 06:17 PM PDT
- nathan944 commented on: https://github.com/hackforla/website/issues/916#issuecomment-1197421194 at 07/27/2022, 03:06 PM PDT
- nathan944 commented on: https://github.com/hackforla/website/issues/916#issuecomment-1229500151 at 08/28/2022, 09:24 AM PDT
- nathan944 opened: https://github.com/hackforla/website/issues/3532 at 09/10/2022, 02:57 PM PDT
- nathan944 closed as not planned: https://github.com/hackforla/website/issues/3532#event-7361528345 at 09/10/2022, 04:36 PM PDT
- nathan944 closed as completed: https://github.com/hackforla/website/issues/3532#event-7361528532 at 09/10/2022, 04:36 PM PDT
- nathan944 opened: https://github.com/hackforla/website/issues/3533 at 09/10/2022, 04:51 PM PDT
- nathan944 unassigned: https://github.com/hackforla/website/issues/3302#issuecomment-1166379335 at 11/16/2022, 09:41 AM PST
- nathan944 unassigned: https://github.com/hackforla/website/issues/916#issuecomment-1319638102 at 11/20/2022, 10:44 AM PST
