### ISSUE TITLE
Pre-work Checklist: Designer: Gold O.

### ISSUE THREAD

**Issue by gold-o** [hackforla/website#3069]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [x] Share your Gmail address with the team lead
- [x] Confirm with the team lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [x] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] (Once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Self Assign yourself to this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Attend weekly team meetings: 
   - [x] UX weekly team meeting, Thursdays 5pm PST
   - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Review [Design_Short Term Goals, Plan, and Tasks](https://docs.google.com/document/d/1FxwgdnWBbbQ8Pi3tspnukZTWwXtqnRXfNkNhVMEloY0/edit)
- [x] Review the [Start Here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465) and [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) pages in Figma
- [x] Review the [prioritized Backlog to see what Design Issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257) are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Once you accept an issue, please add your "Availability for this week" in that new issue's comment section using the 4 statuses below.
```
Availability for this week:

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
Images: "Add any images that would better help convey your progress of the issue."
```
### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by HackforLABot** [comment]
## Activity Log: gold-o
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- gold-o opened: https://github.com/hackforla/website/issues/3069 at 04/19/2022, 10:26 AM PDT
- gold-o assigned: https://github.com/hackforla/website/issues/3069#issuecomment-1102905420 at 04/20/2022, 03:36 PM PDT
- gold-o assigned: https://github.com/hackforla/website/issues/3034#issuecomment-1091394048 at 04/20/2022, 03:46 PM PDT
- gold-o commented on: https://github.com/hackforla/website/issues/3034#issuecomment-1111451291 at 04/27/2022, 01:29 PM PDT
- gold-o closed as completed: https://github.com/hackforla/website/issues/3069#event-6510454340 at 04/27/2022, 03:06 PM PDT
- gold-o commented on: https://github.com/hackforla/website/issues/3034#issuecomment-1140504416 at 05/29/2022, 11:49 AM PDT
- gold-o commented on: https://github.com/hackforla/website/issues/3034#issuecomment-1160086251 at 06/20/2022, 12:39 AM PDT
- gold-o closed as completed: https://github.com/hackforla/website/issues/3034#event-6836996427 at 06/20/2022, 12:39 AM PDT
- gold-o assigned: https://github.com/hackforla/website/issues/1848#issuecomment-894829423 at 06/22/2022, 01:59 PM PDT
- gold-o assigned: https://github.com/hackforla/website/issues/2617#issuecomment-999099692 at 06/22/2022, 03:22 PM PDT
- gold-o unassigned: https://github.com/hackforla/website/issues/1848#issuecomment-894829423 at 06/22/2022, 03:22 PM PDT
- gold-o commented on: https://github.com/hackforla/website/issues/2617#issuecomment-1166593171 at 06/26/2022, 10:20 AM PDT
- gold-o assigned: https://github.com/hackforla/website/issues/3117#issuecomment-1149279469 at 07/06/2022, 12:02 PM PDT
- gold-o unassigned: https://github.com/hackforla/website/issues/3117#issuecomment-1149279469 at 07/06/2022, 12:02 PM PDT
- gold-o assigned: https://github.com/hackforla/website/issues/3117#issuecomment-1149279469 at 07/06/2022, 12:03 PM PDT
- gold-o commented on: https://github.com/hackforla/website/issues/2617#issuecomment-1178280519 at 07/07/2022, 03:10 PM PDT
- gold-o commented on: https://github.com/hackforla/website/issues/3117#issuecomment-1186617457 at 07/17/2022, 03:18 PM PDT
- gold-o commented on: https://github.com/hackforla/website/issues/3117#issuecomment-1244636993 at 09/12/2022, 03:40 PM PDT
- gold-o commented on: https://github.com/hackforla/website/issues/3117#issuecomment-1244645781 at 09/12/2022, 03:43 PM PDT
- gold-o closed as completed: https://github.com/hackforla/website/issues/3117#event-7371598729 at 09/12/2022, 03:43 PM PDT
- gold-o unassigned: https://github.com/hackforla/website/issues/2617#issuecomment-1263227729 at 10/05/2022, 09:10 AM PDT
