### ISSUE TITLE
Pre-work Checklist: Designer: Sijia 

### ISSUE THREAD

**Issue by sijiapitts** [hackforla/website#3071]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the team lead
- [x] (Once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Confirm with the team lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [x] Self Assign yourself to this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings: 
   - [x] UX weekly team meeting, Wednesday 2:30 pm PST
   - [x] All team meeting (UX, Development, Product), Sunday 10am PST
- [x] Review [Design_Short Term Goals, Plan, and Tasks](https://docs.google.com/document/d/1FxwgdnWBbbQ8Pi3tspnukZTWwXtqnRXfNkNhVMEloY0/edit)
- [x] Review the [Start Here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465) and [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) pages in Figma
- [x] Review the [prioritized Backlog to see what Design Issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257) are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Once you accept an issue, please add your "Availability for this week" in that new issue's comment section using the 4 statuses below.
```
Availability for this week:

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
Images: "Add any images that would better help convey your progress of the issue."
```
### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by HackforLABot** [comment]
## Activity Log: sijiapitts
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- sijiapitts opened: https://github.com/hackforla/website/issues/3071 at 04/20/2022, 03:41 PM PDT
- sijiapitts assigned: https://github.com/hackforla/website/issues/3035#issuecomment-1091504315 at 04/20/2022, 03:44 PM PDT
- sijiapitts assigned: https://github.com/hackforla/website/issues/3071#issuecomment-1104525746 at 04/20/2022, 04:57 PM PDT
- sijiapitts closed as completed: https://github.com/hackforla/website/issues/3071#event-6510424064 at 04/27/2022, 02:58 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3035#issuecomment-1111541509 at 04/27/2022, 03:28 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3035#issuecomment-1133941717 at 05/22/2022, 10:43 AM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3035#issuecomment-1146187593 at 06/03/2022, 10:09 AM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3035#issuecomment-1150489730 at 06/08/2022, 03:49 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3035#issuecomment-1157012295 at 06/15/2022, 03:27 PM PDT
- sijiapitts opened: https://github.com/hackforla/website/issues/3277 at 06/21/2022, 03:40 PM PDT
- sijiapitts assigned: https://github.com/hackforla/website/issues/3277 at 06/21/2022, 03:40 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3035#issuecomment-1162435721 at 06/21/2022, 03:45 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3277#issuecomment-1171528664 at 06/30/2022, 11:11 AM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3277#issuecomment-1176845071 at 07/06/2022, 04:13 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3035#issuecomment-1179771250 at 07/10/2022, 10:51 AM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3277#issuecomment-1179773403 at 07/10/2022, 11:06 AM PDT
- sijiapitts assigned: https://github.com/hackforla/website/issues/3191#issuecomment-1143258113 at 08/03/2022, 03:38 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3191#issuecomment-1209946185 at 08/09/2022, 03:15 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3277#issuecomment-1247289194 at 09/14/2022, 01:51 PM PDT
- sijiapitts opened: https://github.com/hackforla/website/issues/3626 at 10/15/2022, 11:54 PM PDT
- sijiapitts assigned: https://github.com/hackforla/website/issues/3626 at 10/15/2022, 11:54 PM PDT
- sijiapitts opened: https://github.com/hackforla/website/issues/3627 at 10/16/2022, 12:06 AM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3277#issuecomment-1279909420 at 10/16/2022, 12:13 AM PDT
- sijiapitts closed as completed: https://github.com/hackforla/website/issues/3277#event-7595975450 at 10/16/2022, 12:14 AM PDT
- sijiapitts opened: https://github.com/hackforla/website/issues/3661 at 10/25/2022, 05:59 PM PDT
- sijiapitts assigned: https://github.com/hackforla/website/issues/3661 at 10/25/2022, 05:59 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3661#issuecomment-1291551411 at 10/25/2022, 11:12 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3626#issuecomment-1295335458 at 10/28/2022, 11:42 AM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3626#issuecomment-1296357545 at 10/30/2022, 02:44 PM PDT
- sijiapitts closed as completed: https://github.com/hackforla/website/issues/3626#event-7699817026 at 10/30/2022, 02:45 PM PDT
- sijiapitts commented on: https://github.com/hackforla/website/issues/3661#issuecomment-1310632591 at 11/10/2022, 09:22 AM PST
- sijiapitts commented on: https://github.com/hackforla/website/issues/1878#issuecomment-1310635547 at 11/10/2022, 09:24 AM PST
- sijiapitts issue closed as completed: https://github.com/hackforla/website/issues/3661#event-7826498690 at 11/16/2022, 09:45 AM PST
- sijiapitts commented on: https://github.com/hackforla/website/issues/3191#issuecomment-1317879586 at 11/16/2022, 04:37 PM PST
- sijiapitts unassigned: https://github.com/hackforla/website/issues/3191#issuecomment-1317879586 at 11/16/2022, 04:37 PM PST
- sijiapitts assigned: https://github.com/hackforla/website/issues/3627#issuecomment-1321212365 at 01/23/2023, 09:47 PM PST
- sijiapitts commented on: https://github.com/hackforla/website/issues/3983#issuecomment-1432648106 at 02/15/2023, 11:37 PM PST
- sijiapitts unassigned: https://github.com/hackforla/website/issues/3627#issuecomment-1495143197 at 06/26/2023, 06:42 PM PDT
