### ISSUE TITLE
Pre-work Checklist:  Rejoice

### ISSUE THREAD

**Issue by Richey24** [hackforla/website#3120]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [ ] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [ ] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [ ] Share your Gmail address with the team lead
- [ ] (Once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [ ] Confirm with the team lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [ ] Self Assign yourself to this issue (gear in right side panel)
- [ ] Add this issue to Projects: Project Board (gear in right side panel)
- [ ] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [ ] Attend weekly team meetings: 
   - [ ] UX weekly team meeting, Wednesday 2:30 pm PST
   - [ ] All team meeting (UX, Development, Product), Sunday 10am PST
- [ ] Review [Design_Short Term Goals, Plan, and Tasks](https://docs.google.com/document/d/1FxwgdnWBbbQ8Pi3tspnukZTWwXtqnRXfNkNhVMEloY0/edit)
- [ ] Review the [Start Here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465) and [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) pages in Figma
- [ ] Review the [prioritized Backlog to see what Design Issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257) are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [ ] Once you accept an issue, please add your "Availability for this week" in that new issue's comment section using the 4 statuses below.
```
Availability for this week:

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
Images: "Add any images that would better help convey your progress of the issue."
```
### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by SAUMILDHANKAR** [comment]
Deleting the issue as created by error.

**Comment by SAUMILDHANKAR** [comment]
Deleting this issue as Rejoice is a developer and used the designer template by error.
