### ISSUE TITLE
Pre-work Checklist: Developer: Julian Smith

### ISSUE THREAD

**Issue by juliansmith0** [hackforla/website#3122]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] Also, confirm with the team lead that they have added you to the Zoom meeting calendar invites
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
- [x] After you have finished adding yourself to the roster, let a team lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [ ] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [ ] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Follow the steps in section [2.3 Where can I find GitHub issues to work on?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
- [x] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [ ] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue (one per person)
  - Good second issue (one per person)
  - Small (one per person, with some exceptions, see below)
  - Medium (you can work on more than one medium issue, but only one at a time)
  - Large (you can work on more than one large issue, but only one at a time)
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
    - You can work on back-to-back small issues if it meets the following criteria:
      - You are learning something new and need to work on an issue of a lesser complexity
      - Special request by a lead or pm
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their SCSS classes)
- [ ] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@juliansmith0 Hello Julian, my name is Saumil and I am one of the tech leads of the website team. Just wanted to follow up on your progress with this issue. Please check-off the above action items as you go along. Also, were you able to set up your dev environment? Feel free to post in our hfla-site slack channel if you have questions. Thank you.

**Comment by juliansmith0** [comment]
@SAUMILDHANKAR Hi Saumil! I'll be working more through this today. I do have a blocker on Step 1.6 of the Dev setup. I posted the error I'm receiving in the hfla-site channel on Slack (here: https://hackforla.slack.com/archives/C4UM52W93/p1652825159579999). I will copy here as well for ease of reference and in the mean time am jumping to other steps.

> Hi all! I'm working on the pre-work checklist and on step 1.6 of the Dev Setup (Build and serve the website locally) I'm running into an issue. I ran docker-compose up but doing so ultimately results in the message hfla_site exited with code 1. This is after I had just run git fetch upstream to make sure everything was up-to-date.
Here is the more detailed output from running docker-compose up:

> ❯ docker-compose up
[+] Running 2/2
 ⠿ Network website_default  Created                                                                     0.0s
 ⠿ Container hfla_site      Created                                                                     0.0s
Attaching to hfla_site
hfla_site  | ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
hfla_site  | Configuration file: _config.yml
hfla_site  | Configuration file: _config.docker.yml
hfla_site  |             Source: .
hfla_site  |        Destination: /srv/jekyll/_site
hfla_site  |  Incremental build: enabled
hfla_site  |       Generating...
hfla_site  |                     done in 37.427 seconds.
hfla_site  |  Auto-regeneration: enabled for '.'
hfla_site  | <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
hfla_site  | 	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:184:in `require_relative'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:184:in `setup'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:102:in `process'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
hfla_site  | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
hfla_site  | 	from /usr/gem/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
hfla_site  | 	from /usr/gem/bin/jekyll:25:in `load'
hfla_site  | 	from /usr/gem/bin/jekyll:25:in `<main>'
hfla_site exited with code 1

**Comment by juliansmith0** [comment]
@SAUMILDHANKAR Scratch the above! Got a solution in Slack from Eric that worked.

That being said, for you and @JessicaLucindaCheng,  per 1.6.a in CONTRIBUTING.md: "NOTE: If it takes longer than 2 minutes to build your website using docker-compose up, please let the [technical leads](https://github.com/hackforla/website/wiki/Meet-the-Team) know about this and add your website build time in a comment to https://github.com/hackforla/website/issues/1443. Also, once you are part of the merge team, you can work on https://github.com/hackforla/website/issues/1443 and fix it (if you want)."

It did indeed take longer than 2 minutes. Total, it took 16.5 minutes. I will add a comment to issue #1443 as well regarding this.

**Comment by juliansmith0** [comment]
**How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?**

~2 hours 46 minutes (166 minutes) -- this not including onboarding and the meeting I attended Sunday.

**Comment by SAUMILDHANKAR** [comment]
@juliansmith0 Reopening this issue as you haven't provided a weekly progress update using the format shared in the action item above. Once, you do that in any of your issues going forward, feel free to close this prework issue. Thanks.

**Comment by tamara-snyder** [comment]
Hi @juliansmith0, I noticed that you still need to do a progress update in the issue you are assigned to. Please keep your Pre-Work open until you have provided a weekly update on an issue. You can use the following format:
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
See [this section of the HfLA Wiki](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue) for more details.

**Comment by ExperimentsInHonesty** [comment]
@juliansmith0 closing this issue.  If its in error, because you have not left the team, but rather are just on leave, then please reopen and give us an update.

**Comment by HackforLABot** [comment]
## Activity Log: juliansmith0
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- juliansmith0 opened: https://github.com/hackforla/website/issues/3122 at 05/10/2022, 08:21 PM PDT
- juliansmith0 assigned: https://github.com/hackforla/website/issues/3122#issuecomment-1126973812 at 05/15/2022, 11:39 AM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/issues/3122#issuecomment-1129368758 at 05/17/2022, 03:16 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/issues/3122#issuecomment-1129504369 at 05/17/2022, 07:32 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/issues/1443#issuecomment-1129506631 at 05/17/2022, 07:37 PM PDT
- juliansmith0 assigned: https://github.com/hackforla/website/issues/2423#issuecomment-1073045830 at 05/17/2022, 08:02 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/issues/2423#issuecomment-1129522307 at 05/17/2022, 08:15 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/issues/3122#issuecomment-1129523892 at 05/17/2022, 08:18 PM PDT
- juliansmith0 opened: https://github.com/hackforla/website/pull/3160 at 05/19/2022, 08:17 PM PDT
- juliansmith0 issue closed by PR 3160: https://github.com/hackforla/website/issues/2423#event-6647317061 at 05/19/2022, 08:39 PM PDT
- juliansmith0 PR was merged: https://github.com/hackforla/website/pull/3160#event-6647317066 at 05/19/2022, 08:39 PM PDT
- juliansmith0 closed as completed: https://github.com/hackforla/website/issues/3122#event-6665574886 at 05/23/2022, 09:04 PM PDT
- juliansmith0 assigned: https://github.com/hackforla/website/issues/2921#issuecomment-1058573652 at 05/23/2022, 09:07 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/issues/2921#issuecomment-1135382073 at 05/23/2022, 09:10 PM PDT
- juliansmith0 opened: https://github.com/hackforla/website/pull/3172 at 05/23/2022, 09:22 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/pull/3172#issuecomment-1136652205 at 05/24/2022, 07:34 PM PDT
- juliansmith0 issue closed by PR 3172: https://github.com/hackforla/website/issues/2921#event-6678425872 at 05/25/2022, 07:40 AM PDT
- juliansmith0 PR was merged: https://github.com/hackforla/website/pull/3172#event-6678425890 at 05/25/2022, 07:40 AM PDT
- juliansmith0 assigned: https://github.com/hackforla/website/issues/2930#issuecomment-1059838228 at 05/26/2022, 01:50 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/issues/2930#issuecomment-1139034159 at 05/26/2022, 01:52 PM PDT
- juliansmith0 opened: https://github.com/hackforla/website/pull/3176 at 05/26/2022, 03:01 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/pull/3178#issuecomment-1143027455 at 05/31/2022, 06:47 PM PDT
- juliansmith0 submitted review: https://github.com/hackforla/website/pull/3178#pullrequestreview-991344771 at 05/31/2022, 08:03 PM PDT
- juliansmith0 assigned: https://github.com/hackforla/website/issues/2172#issuecomment-904871690 at 05/31/2022, 08:24 PM PDT
- juliansmith0 commented on: https://github.com/hackforla/website/issues/2172#issuecomment-1143076519 at 05/31/2022, 08:25 PM PDT
- juliansmith0 issue closed by PR 3176: https://github.com/hackforla/website/issues/2930#event-6742589935 at 06/04/2022, 05:33 PM PDT
- juliansmith0 PR was merged: https://github.com/hackforla/website/pull/3176#event-6742589937 at 06/04/2022, 05:33 PM PDT
- juliansmith0 unassigned: https://github.com/hackforla/website/issues/2172#issuecomment-1194658612 at 07/25/2022, 02:34 PM PDT
- juliansmith0 issue closed as completed: https://github.com/hackforla/website/issues/3122#event-7059890650 at 07/25/2022, 02:36 PM PDT
