### ISSUE TITLE
Pre-work Checklist: Developer: Olivia Wang

### ISSUE THREAD

**Issue by oliviaywangn** [hackforla/website#3126]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your Gmail address with the team lead so you can be added to the Google Drive
- [x] Also, confirm with the team lead that they have added you to the Zoom meeting calendar invites
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
- [x] After you have finished adding yourself to the roster, let a team lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Follow the steps in section [2.3 Where can I find GitHub issues to work on?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
- [x] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue (one per person)
  - Good second issue (one per person)
  - Small (one per person, with some exceptions, see below)
  - Medium (you can work on more than one medium issue, but only one at a time)
  - Large (you can work on more than one large issue, but only one at a time)
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
    - You can work on back-to-back small issues if it meets the following criteria:
      - You are learning something new and need to work on an issue of a lesser complexity
      - Special request by a lead or pm
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their SCSS classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by SAUMILDHANKAR** [comment]
@oliviaywangn Hello Olivia, my name is Saumil and I am one of the tech leads of the website team. Just wanted to follow up on your progress with this issue. Please check-off the above action items as you go along. Also, were you able to set up your dev environment? Feel free to post in our hfla-site slack channel if you have questions. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@oliviaywangn Hello Olivia, hope you are doing well. I just noticed you haven't finished setting up your dev environment yet. If you have any questions or need help, please feel free to post in our hfla-site slack channel. Thank you.

**Comment by ExperimentsInHonesty** [comment]
@oliviaywangn We did not hear from you last week after we reached out and its been 18 days since you joined the team, please write back as a comment on this issue 
1. Progress: "What is the current status of your getting set up? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by oliviaywangn** [comment]
Hi, I had issues opening up Docker and I messaged the slacker chat for help, but because I am on a windows 10 it was harder for people to help me. Jessica Cheng gave me this link (https://github.com/hackforla/website/wiki/Add-local-user-accounts-to-the-docker-users-group-on-Windows-10), but I could not find "Local Users and Groups" on my computer. I did not know when was the best time to ask for help, since I cannot come to the office hours meeting. Is it still ok for me to come during the other times?

**Comment by oliviaywangn** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
About 7-8 hours
ETA: 3 weeks
availability 8 hours/week

**Comment by tamara-snyder** [comment]
Hi @oliviaywangn, I noticed that you still need to do a progress update in the issue you are assigned to. Please keep your Pre-Work open until you have provided a weekly update on an issue. You can use the following format:
```
Provide Update
1. Progress
2. Blockers
3. Availability
4. ETA
```
See [this section of the HfLA Wiki](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue) for more details.
I have unchecked the item for the progress update. Please check it off again once you've given a progress update on your issue.

**Comment by oliviaywangn** [comment]
1. Progress: First issue was merged, and submitted pull request for second issue. 
2. Blockers: Being able to push things to personal repository (fixed). 
3. Availability this week: 1 hr
4. ETA: 1 week

**Comment by HackforLABot** [comment]
## Activity Log: oliviaywangn
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- oliviaywangn opened: https://github.com/hackforla/website/issues/3126 at 05/10/2022, 08:26 PM PDT
- oliviaywangn assigned: https://github.com/hackforla/website/issues/3126#issuecomment-1126974754 at 05/17/2022, 05:54 PM PDT
- oliviaywangn commented on: https://github.com/hackforla/website/issues/3126#issuecomment-1140489205 at 05/29/2022, 10:11 AM PDT
- oliviaywangn assigned: https://github.com/hackforla/website/issues/2800#issuecomment-1046095089 at 05/31/2022, 09:16 PM PDT
- oliviaywangn commented on: https://github.com/hackforla/website/issues/2800#issuecomment-1143099637 at 05/31/2022, 09:17 PM PDT
- oliviaywangn commented on: https://github.com/hackforla/website/issues/3126#issuecomment-1152864879 at 06/10/2022, 11:10 PM PDT
- oliviaywangn commented on: https://github.com/hackforla/website/issues/2800#issuecomment-1152865135 at 06/10/2022, 11:12 PM PDT
- oliviaywangn opened: https://github.com/hackforla/website/pull/3258 at 06/16/2022, 08:03 PM PDT
- oliviaywangn commented on: https://github.com/hackforla/website/issues/2800#issuecomment-1158441490 at 06/16/2022, 08:07 PM PDT
- oliviaywangn assigned: https://github.com/hackforla/website/issues/2898#issuecomment-1053530633 at 06/19/2022, 11:08 PM PDT
- oliviaywangn unassigned: https://github.com/hackforla/website/issues/2898#issuecomment-1053530633 at 06/19/2022, 11:13 PM PDT
- oliviaywangn assigned: https://github.com/hackforla/website/issues/2897#issuecomment-1053494402 at 06/19/2022, 11:16 PM PDT
- oliviaywangn opened: https://github.com/hackforla/website/pull/3262 at 06/19/2022, 11:28 PM PDT
- oliviaywangn issue closed by PR 3258: https://github.com/hackforla/website/issues/2800#event-6842955195 at 06/20/2022, 06:12 PM PDT
- oliviaywangn PR was merged: https://github.com/hackforla/website/pull/3258#event-6842955215 at 06/20/2022, 06:12 PM PDT
- oliviaywangn issue closed by PR 3262: https://github.com/hackforla/website/issues/2897#event-6871260603 at 06/23/2022, 08:49 PM PDT
- oliviaywangn PR was merged: https://github.com/hackforla/website/pull/3262#event-6871260609 at 06/23/2022, 08:49 PM PDT
- oliviaywangn commented on: https://github.com/hackforla/website/issues/3126#issuecomment-1166180017 at 06/24/2022, 08:15 PM PDT
- oliviaywangn closed as completed: https://github.com/hackforla/website/issues/3126#event-6907471555 at 06/29/2022, 09:57 PM PDT
- oliviaywangn assigned: https://github.com/hackforla/website/issues/3131#issuecomment-1164877942 at 06/29/2022, 09:58 PM PDT
- oliviaywangn commented on: https://github.com/hackforla/website/issues/3131#issuecomment-1170764870 at 06/29/2022, 10:00 PM PDT
- oliviaywangn unassigned: https://github.com/hackforla/website/issues/3131#issuecomment-1170764870 at 07/02/2022, 09:20 PM PDT
- oliviaywangn assigned: https://github.com/hackforla/website/issues/2898#issuecomment-1053530633 at 07/02/2022, 09:23 PM PDT
- oliviaywangn unassigned: https://github.com/hackforla/website/issues/2898#issuecomment-1173009227 at 07/02/2022, 09:23 PM PDT
