### ISSUE TITLE
Add credits for images for redesigned homepage

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3130]
### Dependency
- [x] #3131
- [x] #3294
- [x] #3295
- [x] #3296
- [x] #3331
- [x] #3336
- [x] #3337
- [x] #3342
- [x] #3351 
- [x] #3352
- [x] #3353
- [x] #3358 
- [x] #3415
- [x] #3416 
- [x] #3418 
- [x] #3423
- [x] #3775 

### Overview
We need to add credits for all new images used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Action Items
- [x] Create a spreadsheet auditing the current credits and images for the redesigned homepage that are already in the feature-homepage-launch branch.
  - [x] Include a column for "Link to Issue"
  - [x] Add a link to the spreadsheet in the "Resources/Instructions" below
- [x] Based on the credits named in this [Spreadsheet - Epic #3130 Redesign Homepage Credits and Images Audit](https://docs.google.com/spreadsheets/d/1Qo1_iOJ1fA8cw2ZZO8dv4B-QjR1o4iyqThvHxJqLaRc/edit#gid=764865707), write issues to create credits for all the new images on the redesigned homepage and add them to the "Dependency" section at the top.
  - [x] Add this as a comment to every issue:
    ```
    This issue would usually have the milestone 01. Compliance. However, it's specifically for the homepage launch, which has not happened yet.
    ``` 
- [x] Once all the issues in the Dependency section are checked off and closed,
  - [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. In the [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) wiki article, please read and follow `Step 1: Create your branch`.
  - [x] Then use Docker to see the [Credits page](https://www.hackforla.org/credits/) in a browser locally on your computer
  - [x] Using the search function in your browser, check each of the credits on the Credits page match the information and image provided in the credits listed in the [Figma homepage redesign](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724) inside the red box, on the right. (Note: You are only checking the credits for any images used in the redesigned homepage.)
    - [x] Notes:
      - [x] If you search "Design", you will find two credits with that name but different images. Check the credit that says, "Used in: Homepage". 
      - [x] If you search "Citizen Engagement", you will find two credits with that name but different images. Check the credit that says, "Used in: Homepage".   
  - [x] After you do the searches above,
    - [x] If you find the credits on the Credits page _**matches**_ the information and images in the Figma design, then close this issue.
    - [x] If you find the credits on the Credits page _**does not match**_ the information and images in the Figma design,
      - [x] In a new comment below, list which credits had a discrepancy and needs to be fixed in [_data/internal/credits on the feature-homepage-launch branch](https://github.com/hackforla/website/tree/feature-homepage-launch/_data/internal/credits) 
      - [x] Then reach out to the member(s) of Merge Team and the Tech Lead(s) to help you write issues to fix what you found. (See [Meet the Team wiki page](https://github.com/hackforla/website/wiki/Meet-the-Team) for who the Merge Team members and Tech Leads are.)

### Resources/Instructions
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Figma - Homepage Redesign: Credits](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)
- [_data/internal/credits on the feature-homepage-launch branch](https://github.com/hackforla/website/tree/feature-homepage-launch/_data/internal/credits) 
- [Spreadsheet - Epic #3130 Redesign Homepage Credits and Images Audit](https://docs.google.com/spreadsheets/d/1Qo1_iOJ1fA8cw2ZZO8dv4B-QjR1o4iyqThvHxJqLaRc/edit#gid=764865707)
- Related issue: #2528

**Comment by JessicaLucindaCheng** [comment]
- Progress: Completed writing 3 of the credits for the homepage redesign = 3 hours of work
- Blocker: None
- Availability: Possibly 2 hours each on Mon, Tue, Wed, Thu
- ETA: Sat, July 2, 2022 (maybe sooner)

**Comment by JessicaLucindaCheng** [comment]
Progress: Completed writing 8 of the credits for the homepage redesign = 6 hours of work
Blocker: None
Availability: 2 hours today and 8 hours Monday
ETA: Mon, July 11, 2022

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 

Edit: Bonnie already answered my questions

## Hands credit
In the [redesigned homepage in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), there is a Hands credit listed; here is a screenshot of it:
  <details>
    <summary>Screenshot of Hands credit in Figma</summary>
    <img alt="" src="https://user-images.githubusercontent.com/31293603/178167040-e0080bec-8518-4d49-8318-da1cb9dfc77b.png">
  </details>

However, I do not see this image used on the redesigned homepage; here is a screenshot of the redesigned homepage:
  <details>
    <summary>Screenshot of redesigned homepage</summary>
    <img src="https://user-images.githubusercontent.com/31293603/178167102-9c5aa340-2553-4f9b-90a7-40f0eaf1c008.png" alt="">
  </details>

Did you want me to write an issue for the Hands credit even though I don't currently see it being used on the Homepage? No, because we are currently still deciding what image to use. We will add the credit for that image once that has been finalized.

## Edited image
There are some differences between an actual image we use and the one we link to on the Credits page. I think the image may have been edited by a HfLA designer by looking at previous version of the redesigned homepage in Figma: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15962%3A100862.
1. How do we tell if it is edited by a HfLA designer? These were edited by Kristine Eudey
2. If it it is edited by a HfLA designer, how do we go about giving credit to an edited image that is a combination of images? Add an "Altered by:" field.
3. If it it is edited by a HfLA designer, do we need to give credit to each individual icon/image within the overall image too?

### Resources/Notes
- **From Unsplash**
  - See #5 in https://unsplash.com/terms
  - https://help.unsplash.com/en/articles/2612315-can-i-use-unsplash-photos-for-personal-or-commercial-projects
- **From Burst**
  - https://burst.shopify.com/licenses/shopify-some-rights-reserved

### From Civic Tech Infrastructure comment https://github.com/hackforla/website/issues/3352#issuecomment-1192015662:
For this credit, the link for the image is: https://unsplash.com/photos/unRkg2jH1j0
  <details>
  <summary>Click here to see the image from Unsplash</summary>
  <img src="https://user-images.githubusercontent.com/31293603/180331367-2503b241-6887-41a0-89f3-9a7ee4a1e97c.jpg" alt="man looking at analytics on a tablet device">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Civic Tech Infrastructure credit in Figma</summary>
    <img width="377" alt="" src="https://user-images.githubusercontent.com/31293603/180331815-3d3da6e3-5b6a-41c2-b1fa-993e516f5f67.png">
  </details>

### From Diversity, Equity, Inclusion comment https://github.com/hackforla/website/issues/3353#issuecomment-1192044729:
For this credit, the link for the image is: https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity
  <details>
    <summary>Click here to see the image from Burst</summary>
    <img src="https://user-images.githubusercontent.com/31293603/180334642-3cf45c33-9e40-4f40-8b2d-0496570965e0.jpg" alt="team hands in the middle">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Diversity, Equity, Inclusion credit in Figma</summary>
    <img width="553" alt="" src="https://user-images.githubusercontent.com/31293603/180334762-86967c48-3ff9-4f31-83b4-f8ad5383696a.png">
  </details>

### From Social Safety Net comment https://github.com/hackforla/website/issues/3416#issuecomment-1193024853:
For this credit, the link for the image is: https://unsplash.com/photos/lyiKExA4zQA
  <details>
    <summary>Click here to see the image from Unsplash</summary>
    <img src="https://user-images.githubusercontent.com/31293603/180583999-965a026a-2fdc-461d-8355-a553334b31cf.jpg" alt="">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Social Safety Net credit in Figma</summary>
    <img src="https://user-images.githubusercontent.com/31293603/180583969-12a0d498-a800-495b-b70d-8ce0e8268f8d.png" alt="">
  </details>

## Page not found link for Justice image
From Justice comment https://github.com/hackforla/website/issues/3415#issuecomment-1193022680

The link to the specific image says, "Page not found". Here is the link: https://unsplash.com/photos/bvHcG6334dE

Is this okay? Use the author's page instead.

**Comment by JessicaLucindaCheng** [comment]
- Progress: Completed writing all the issues. Still need to do the following once my blockers/questions are answered
  - [ ] Once all the issues are written and added to the "Dependency" section above,
    - [ ] Unassign myself 
    - [ ] Add a "Dependency" label to this issue
    - [ ] Move it to the "Ice Box" column
    - [ ] Change the labels so it is a Small complexity issue, size: 0.5pt, role: front end
- Blockers: See https://github.com/hackforla/website/issues/3130#issuecomment-1179828880
- Availability: Will update once blockers are answered
- ETA: Will update once blockers are answered

**Comment by JessicaLucindaCheng** [comment]
### Notes
From Dev/PM meeting with Bonnie on September 19, 2022, 
- Q: Did you want me to write an issue for the Hands credit even though I don't currently see it being used on the Homepage?
  - A: No, we don't need to write an issue for it because research/design is still trying to figure out what image is the best to use.

### Progress Update
- Progress: Still need to contact Kristine Eudey and change one of the small issues to a medium issue with an "Altered by:" field and name of designer that altered the image
- Blockers: Having Internet problems
- Availability: Dependent on Internet, so not sure.
- ETA: November 15, 2022 dependent on my Internet

**Comment by JessicaLucindaCheng** [comment]
### To Dos
- [ ] Kristine Eudey follow up with her on the images that were modified and figure out who modified each image
- [ ] Change one small issue with a modified image into one medium issue to add an "Altered by" field and with the designer's name, and add dependencies to other 2-3 small issues that are similar to it

### Progress Update
- Progress: Still need to do above To Dos but didn't get to it because I was fixing my Internet problems. My Internet problems are fixed. So, I should be able to get the above done.
- Blockers: None.
- Availability: 4 hours
- ETA: November 15, 2022

**Comment by JessicaLucindaCheng** [comment]
### To Dos
- [x] Kristine Eudey follow up with her on the images that were modified and figure out who modified each image. 
  - No need to contact Kristine. 
    - I found Kristine was assigned to these issues as the designer: #2057 and #2328
    - Also, Bonnie confirmed it was Kristine. 
- [x] Add an `altered-by` field with the designer's name
- [ ] Write a medium issue to have the "Altered by:" field show up on the Credits page

### Progress Update
- Progress: Still need to do above To Dos but didn't get to it because I was fixing my Internet problems. My Internet problems are fixed. So, I should be able to get the above done.
- Blockers: None.
- Availability: 4 hours
- ETA: November 22, 2022

**Comment by JessicaLucindaCheng** [comment]
### Progress Update
- Progress: Still need to finish the remaining To Dos below.
- Blockers: Question on a link for one of the credits. See this comment: https://github.com/hackforla/website/issues/3415#issuecomment-1333559213
- Availability: 6 hours
- ETA: Dependent on blocker being answered

### To Dos
- [ ] Write a medium issue to have the "Altered by:" field show up on the Credits page
- [ ] See if this question has been answered: https://github.com/hackforla/website/issues/3415#issuecomment-1333559213

**Comment by JessicaLucindaCheng** [comment]
### Progress Update
- Progress: Still need to finish the remaining To Dos below.
- Blockers: Question on a link for one of the credits. See this comment: https://github.com/hackforla/website/issues/3415#issuecomment-1333559213
- Availability: 6 hours
- ETA: Dependent on blocker being answered

### To Dos
- [ ] Write a medium issue to have the "Altered by:" field show up on the Credits page
- [ ] See if this question has been answered: https://github.com/hackforla/website/issues/3415#issuecomment-1333559213

**Comment by JessicaLucindaCheng** [comment]
### Progress Update
- Progress: Still need to finish the remaining To Dos below.
- Blockers: Question on a link for one of the credits. See this comment: https://github.com/hackforla/website/issues/3415#issuecomment-1333559213
- Availability: 6 hours
- ETA: Dependent on blocker being answered

### To Dos
- [ ] Write a medium issue to have the "Altered by:" field show up on the Credits page
- [ ] See if this question has been answered: https://github.com/hackforla/website/issues/3415#issuecomment-1333559213

**Comment by JessicaLucindaCheng** [comment]
### Progress Update
- Progress: Still need to finish the remaining To Dos below.
- Blockers: Question on a link for one of the credits. See this comment: https://github.com/hackforla/website/issues/3415#issuecomment-1333559213
- Availability: 6 hours
- ETA: Dependent on blocker being answered

### To Dos
- [x] Write a medium issue to have the "Altered by:" field show up on the Credits page
- [x] See if this question has been answered: https://github.com/hackforla/website/issues/3415#issuecomment-1333559213
- [x] See if this question has been answered: https://github.com/hackforla/website/issues/3130#issuecomment-1374865443
- [x] Contact Kristine Eudey to find out where the composite (smaller) images are from for each icon in the Civic Tech Infrastructure image and Diversity, Equity, Inclusion image. See comment https://github.com/hackforla/website/issues/3130#issuecomment-1374865443 for more info.
  - Emailed on 2023-01-12 using websitedevs@hackforla.org email account. 
  - On 2023-01-16, checked email and no response yet.
- [ ] Once we get a response from Kristine, figure out with PM(s) what to do with the composite images in terms of credits.

**Comment by JessicaLucindaCheng** [comment]
Question for PM(s): If it it is edited by a HfLA designer, do we need to give credit to each individual icon's/image's author within the overall image too?
Ans from Bonnie at Dev/PM on 2023-01-09: Contact Kristine Eudey to find out where the composite (smaller) images are from for each icon

### From Civic Tech Infrastructure comment https://github.com/hackforla/website/issues/3352#issuecomment-1192015662:
For this credit, the link for the image is: https://unsplash.com/photos/unRkg2jH1j0
  <details>
  <summary>Click here to see the image from Unsplash</summary>
  <img src="https://user-images.githubusercontent.com/31293603/180331367-2503b241-6887-41a0-89f3-9a7ee4a1e97c.jpg" alt="man looking at analytics on a tablet device">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Civic Tech Infrastructure credit in Figma</summary>
    <img width="377" alt="" src="https://user-images.githubusercontent.com/31293603/180331815-3d3da6e3-5b6a-41c2-b1fa-993e516f5f67.png">
  </details>

### From Diversity, Equity, Inclusion comment https://github.com/hackforla/website/issues/3353#issuecomment-1192044729:
For this credit, the link for the image is: https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity
  <details>
    <summary>Click here to see the image from Burst</summary>
    <img src="https://user-images.githubusercontent.com/31293603/180334642-3cf45c33-9e40-4f40-8b2d-0496570965e0.jpg" alt="team hands in the middle">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Diversity, Equity, Inclusion credit in Figma</summary>
    <img width="553" alt="" src="https://user-images.githubusercontent.com/31293603/180334762-86967c48-3ff9-4f31-83b4-f8ad5383696a.png">
  </details>

**Comment by JessicaLucindaCheng** [comment]
### Progress Update
- Progress: Still need to finish the remaining To Dos below.
- Blockers: As of 2023-01-21, I haven't received a response from Kristine. I'm going to wait another week for a response.
- Availability: Dependent on blocker being answered
- ETA: Dependent on blocker being answered

### To Dos
- [x] Contact Kristine Eudey to find out where the composite (smaller) images are from for each icon in the Civic Tech Infrastructure image and Diversity, Equity, Inclusion image. See comment https://github.com/hackforla/website/issues/3130#issuecomment-1374865443 for more info.
  - Emailed on 2023-01-12 using websitedevs@hackforla.org email account. 
  - On 2023-01-21, checked email and no response yet.
- [ ] Once we get a response from Kristine, figure out with PM(s) what to do with the composite images in terms of credits.

**Comment by JessicaLucindaCheng** [comment]
### Progress Update
- Progress: Still need to finish the remaining To Dos below.
- Blockers: As of 2023-01-26, I haven't received a response from Kristine.
- Availability: Dependent on blocker being answered
- ETA: Dependent on blocker being answered

### To Dos
- [x] Contact Kristine Eudey to find out where the composite (smaller) images are from for each icon in the Civic Tech Infrastructure image and Diversity, Equity, Inclusion image. See comment https://github.com/hackforla/website/issues/3130#issuecomment-1374865443 for more info.
  - Emailed on 2023-01-12 using websitedevs@hackforla.org email account. 
  - On 2023-01-21, checked email and no response yet.
  - On 2023-01-26, checked email and still no response.
- [x] No response from Kristine. Will need to figure out with PM(s) what to do with the composite images in terms of credits. I'm going to ask at the Dev/PM on Jan 30.
- [ ] From 2023-01-30 Dev/PM, Bonnie said to create an issue for Product with 
  - [ ] Details
    - [ ] That I already emailed Kristine using the websitedevs@hackforla.org email address.
    - [ ] PDF the email and attach it to the issue
  - [ ] Action items
    - [ ] to follow up with Kristine to figure out where the images are from
    - [ ] If you figure out where the images are from, issues for devs need to be written to update the ___________ list the credits_____________ and their files
    - [ ] If you don't figure out where the images are from, decide what we will do as next steps for the composite images

**Comment by JessicaLucindaCheng** [comment]
### Progress Update
- Progress: Just need to write another issue for Product to follow up with Kristine and figure out 
- Blockers: None
- Availability: 2 hours
- ETA: Mon, Feb 6, 2023

### To Dos
- [x] Contact Kristine Eudey to find out where the composite (smaller) images are from for each icon in the Civic Tech Infrastructure image and Diversity, Equity, Inclusion image. See comment https://github.com/hackforla/website/issues/3130#issuecomment-1374865443 for more info.
  - Emailed on 2023-01-12 using websitedevs@hackforla.org email account. 
  - On 2023-01-21, checked email and no response yet.
  - On 2023-01-26, checked email and still no response.
- [x] No response from Kristine. Will need to figure out with PM(s) what to do with the composite images in terms of credits. I'm going to ask at the Dev/PM on Jan 30.
- [ ] From 2023-01-30 Dev/PM, Bonnie said to create an issue for Product with 
  - [ ] Details
    - [ ] That I already emailed Kristine using the websitedevs@hackforla.org email address.
    - [ ] PDF the email and attach it to the issue
  - [ ] Action items
    - [ ] to follow up with Kristine to figure out where the images are from
    - [ ] If you figure out where the images are from, issues for devs need to be written to update the ___________ list the credits_____________ and their files
    - [ ] If you don't figure out where the images are from, decide what we will do as next steps for the composite images


### Composite Images
#### From Civic Tech Infrastructure comment https://github.com/hackforla/website/issues/3352#issuecomment-1192015662:
For this credit, the link for the image is: https://unsplash.com/photos/unRkg2jH1j0
  <details>
  <summary>Click here to see the image from Unsplash</summary>
  <img src="https://user-images.githubusercontent.com/31293603/180331367-2503b241-6887-41a0-89f3-9a7ee4a1e97c.jpg" alt="man looking at analytics on a tablet device">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Civic Tech Infrastructure credit in Figma</summary>
    <img width="377" alt="" src="https://user-images.githubusercontent.com/31293603/180331815-3d3da6e3-5b6a-41c2-b1fa-993e516f5f67.png">
  </details>

#### From Diversity, Equity, Inclusion comment https://github.com/hackforla/website/issues/3353#issuecomment-1192044729:
For this credit, the link for the image is: https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity
  <details>
    <summary>Click here to see the image from Burst</summary>
    <img src="https://user-images.githubusercontent.com/31293603/180334642-3cf45c33-9e40-4f40-8b2d-0496570965e0.jpg" alt="team hands in the middle">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Diversity, Equity, Inclusion credit in Figma</summary>
    <img width="553" alt="" src="https://user-images.githubusercontent.com/31293603/180334762-86967c48-3ff9-4f31-83b4-f8ad5383696a.png">
  </details>

**Comment by JessicaLucindaCheng** [comment]
### Progress Update
- Progress: I need to finish writing issue #3934 for Product to follow up with Kristine and figure out 
- Blockers: None
- Availability: 2 hours
- ETA: Mon, Feb 20, 2023

### To Dos
- [x] Contact Kristine Eudey to find out where the composite (smaller) images are from for each icon in the Civic Tech Infrastructure image and Diversity, Equity, Inclusion image. See comment https://github.com/hackforla/website/issues/3130#issuecomment-1374865443 for more info.
  - Emailed on 2023-01-12 using websitedevs@hackforla.org email account. 
  - On 2023-01-21, checked email and no response yet.
  - On 2023-01-26, checked email and still no response.
- [x] No response from Kristine. Will need to figure out with PM(s) what to do with the composite images in terms of credits. I'm going to ask at the Dev/PM on Jan 30.
- [x] From 2023-01-30 Dev/PM, Bonnie said to create an issue for Product and make sure to include the following:
  - [x] Details
    - [x] That I already emailed Kristine using the websitedevs@hackforla.org email address.
    - [x] Added a copy of the contents of the email to the issue
  - [x] Action items
    - [x] If you figure out where the images are from, issues for devs need to be written to update the credit for Civic Tech Infrastructure and the credit for Diversity, Equity, Inclusion
    - [x] If you don't figure out where the images are from, decide what we will do as next steps for the composite images


### Composite Images
#### From Civic Tech Infrastructure comment https://github.com/hackforla/website/issues/3352#issuecomment-1192015662:
For this credit, the link for the image is: https://unsplash.com/photos/unRkg2jH1j0
  <details>
  <summary>Click here to see the image from Unsplash</summary>
  <img src="https://user-images.githubusercontent.com/31293603/180331367-2503b241-6887-41a0-89f3-9a7ee4a1e97c.jpg" alt="man looking at analytics on a tablet device">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Civic Tech Infrastructure credit in Figma</summary>
    <img width="377" alt="" src="https://user-images.githubusercontent.com/31293603/180331815-3d3da6e3-5b6a-41c2-b1fa-993e516f5f67.png">
  </details>

#### From Diversity, Equity, Inclusion comment https://github.com/hackforla/website/issues/3353#issuecomment-1192044729:
For this credit, the link for the image is: https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity
  <details>
    <summary>Click here to see the image from Burst</summary>
    <img src="https://user-images.githubusercontent.com/31293603/180334642-3cf45c33-9e40-4f40-8b2d-0496570965e0.jpg" alt="team hands in the middle">
  </details>

It doesn't look exactly like the contents of this image we are using: 
  <details>
    <summary>Click here to see the screenshot of the marked up Diversity, Equity, Inclusion credit in Figma</summary>
    <img width="553" alt="" src="https://user-images.githubusercontent.com/31293603/180334762-86967c48-3ff9-4f31-83b4-f8ad5383696a.png">
  </details>

**Comment by JessicaLucindaCheng** [comment]
This issue is done. 
- I checked all the credits for the redesigned homepage and they all look good, except for the Coding credit where the artist's last name is misspelled. I have written this issue to fix this problem: #4111. 
- There is a `Hands` credit listed in the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724) but Bonnie told me to hold off on writing an issue to add that credit to the Credits page because we are still determining which header image to use for the redesigned homepage and whether or not that will be the `Hands` image.
- #3934 is a follow-up issue to address providing credit to all the artists in the composite images, specifically Civic Tech Infrastructure image and the Diversity, Equity, Inclusion image.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng is there an issue for this (in the icebox with the reason), so you don't have to keep a note about it?

> There is a Hands credit listed in the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724) but Bonnie told me to hold off on writing an issue to add that credit to the Credits page because we are still determining which header image to use for the redesigned homepage and whether or not that will be the Hands image.

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty For the next issue, did you want me to write an issue to determine what header image we should use? If yes, would this be for `role: user research` or `role: designer`?

> @JessicaLucindaCheng is there an issue for this (in the icebox with the reason), so you don't have to keep a note about it?
> 
> > There is a Hands credit listed in the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724) but Bonnie told me to hold off on writing an issue to add that credit to the Credits page because we are still determining which header image to use for the redesigned homepage and whether or not that will be the Hands image.

Edit:
Answer from Bonnie: The decision was to go with the current header image of the people and not the hands image according to research that was done asking people which image they liked better for the redesigned homepage header. Thus, we don't need to add the Hands image to the Credits page, since we aren't using that image on the redesigned homepage.
