### ISSUE TITLE
Pre-work Checklist: Designer: Emily Tat

### ISSUE THREAD

**Issue by phuonguvan** [hackforla/website#3141]
### Prerequisite
We are looking forward to having you on our team.  Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new designer on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Meet with team lead to introduce you to the project, introduce you to the GitHub board, and receive your first assignment.
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the team lead
- [x] (Once added to the drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0). 
- [x] Confirm with the design lead, that they have added you to the meeting invites and [added you to the GitHub team](https://github.com/orgs/hackforla/teams/website-write/members) and GitHub repo
- [x] Self Assign yourself to this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x] Confirm that team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings: 
   - [x] UX weekly team meeting, Wednesday 2:30 pm PST
   - [x] All team meeting (UX, Development, Product), Sunday 10am PST
 - [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Wednesdays and Sundays). In case, you are unable in any given week, you should reach out to the design lead. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the design lead know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Review [Design_Short Term Goals, Plan, and Tasks](https://docs.google.com/document/d/1FxwgdnWBbbQ8Pi3tspnukZTWwXtqnRXfNkNhVMEloY0/edit)
- [x] Review the [Start Here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465) and [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) pages in Figma
- [x] Review the [prioritized Backlog to see what Design Issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257) are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Once you take an issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the text below and put it in the issue that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
### Additional notes:
- [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue (one per person)
  - Good second issue (one per person)
  - Small (one per person, with some exceptions, see below)
  - Medium (you can work on more than one medium issue, but only one at a time)
  - Large (you can work on more than one large issue, but only one at a time)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Design Weekly Meeting Agenda" column of the Project Board so that it can be addressed in the next design meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [GitHub Project Board - Hack for LA ](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Design](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+design%22#column-7198257)
- [Design Weekly Meeting Agenda](https://github.com/hackforla/website/issues/2106)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - UX Team weekly meeting](https://github.com/hackforla/website/issues/2106)

**Comment by EmilyTat** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?

15 days

**Comment by HackforLABot** [comment]
## Activity Log: EmilyTat
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- EmilyTat assigned: https://github.com/hackforla/website/issues/3141#issuecomment-1126977952 at 05/23/2022, 08:24 AM PDT
- EmilyTat assigned: https://github.com/hackforla/website/issues/3117#issuecomment-1122252414 at 05/23/2022, 09:17 AM PDT
- EmilyTat commented on: https://github.com/hackforla/website/issues/3117#issuecomment-1149265126 at 06/07/2022, 04:21 PM PDT
- EmilyTat commented on: https://github.com/hackforla/website/issues/3141#issuecomment-1149267244 at 06/07/2022, 04:22 PM PDT
- EmilyTat commented on: https://github.com/hackforla/website/issues/3117#issuecomment-1149279005 at 06/07/2022, 04:42 PM PDT
- EmilyTat commented on: https://github.com/hackforla/website/issues/3117#issuecomment-1149279469 at 06/07/2022, 04:43 PM PDT
- EmilyTat unassigned: https://github.com/hackforla/website/issues/3117#issuecomment-1149279469 at 06/08/2022, 03:28 PM PDT
- EmilyTat issue closed as completed: https://github.com/hackforla/website/issues/3141#event-6773500519 at 06/08/2022, 03:33 PM PDT
- EmilyTat opened: https://github.com/hackforla/website/issues/3408 at 07/20/2022, 02:30 PM PDT
- EmilyTat assigned: https://github.com/hackforla/website/issues/3408 at 07/20/2022, 02:30 PM PDT
- EmilyTat issue closed as completed: https://github.com/hackforla/website/issues/3408#event-7777046078 at 11/09/2022, 12:27 PM PST
