### ISSUE TITLE
Collect Project Leadership Information

### ISSUE THREAD

**Issue by KianBadie** [hackforla/website#318]
### Overview
Collect leadership roles information for each project that will be displayed in project home page. 

### Action Items
For each project collect:
- [ ] Who project leaders are
- [ ] Which role each leader has in the project
- [ ] Slack contact information

### Resources/Instructions
This wireframe: ![image](https://user-images.githubusercontent.com/18221058/74795203-29438500-527a-11ea-8902-9e6eb1784043.png)

**Comment by KianBadie** [comment]
@ExperimentsInHonesty 
I forgot if Slack was the medium of communication we decided on shooting for first. If it wasn't, please let me know and I will edit the issue accordingly (that goes for any other necessary edits as well). Also, I didn't know how to structure the action items, so I hope the way it is currently structured is fine. Again, if any necessary edits are needed or if I am missing information/displaying wrong information from our discussion last night let me know.

**Comment by KianBadie** [comment]
Another thing that came up, do we want to get images of these leaders? If not, what would we do to replace the wireframe? We can get github avatar picture links and hardcode those in the project md file.

**Comment by cnk** [comment]
Current state of project pages after 3/3/2020 DTLA hack night

https://www.hackforla.org/projects/311-data.html  
https://www.hackforla.org/projects/adopt-civic-art.html  
https://www.hackforla.org/projects/criminal-sentencing.html  
https://www.hackforla.org/projects/curbmap.html  
https://www.hackforla.org/projects/engage.html  
https://www.hackforla.org/projects/equity-language.html  
https://www.hackforla.org/projects/food-oasis.html  
https://www.hackforla.org/projects/heart.html  
https://www.hackforla.org/projects/hellogov.html  
https://www.hackforla.org/projects/jobs-for-hope.html  
https://www.hackforla.org/projects/light-the-way.html  
https://www.hackforla.org/projects/lucky-parking.html  
https://www.hackforla.org/projects/metro-ontime.html  
https://www.hackforla.org/projects/new-schools-today.html  
https://www.hackforla.org/projects/public-tree-map.html  
https://www.hackforla.org/projects/record-clearance-project.html  
https://www.hackforla.org/projects/shared-housing-project.html  
https://www.hackforla.org/projects/spare.html  
https://www.hackforla.org/projects/tdm-calculator.html  
https://www.hackforla.org/projects/undebate.html
https://www.hackforla.org/projects/vrms.html
https://www.hackforla.org/projects/website.html
https://www.hackforla.org/projects/work-for-la.html

**Comment by ExperimentsInHonesty** [comment]
- [ ] 311-data
   - [ ] no hero - still waiting for them to provide one https://github.com/hackforla/311-data/issues/207
   - [x] add link to their wiki: https://github.com/hackforla/311-data/wiki
   - [x] add link to their slack: https://hackforla.slack.com/archives/CJY4R382X
- [ ] engage
   - [x] add hero from their [issue comment](https://github.com/hackforla/website/issues/251#issuecomment-593806771)
   - [x] add eli's title
   - [x] add link to their slack: https://hackforla.slack.com/archives/C6JBH478W
-  [x] equity- language
   - [x] add hero image from their [issue comment](https://github.com/hackforla/website/issues/301#issuecomment-594357599)
   -[ ] add link to their slack: https://hackforla.slack.com/archives/C6JBH478W
- [x] food oasis
   - the readme is not showing up in the getting started section, I think its referenced as read.me, so it might be the way we are referring to it in the project markdown file.
   -[ ] add link to food oasis's slack: https://hackforla.slack.com/archives/CMER3R1RD
- [ ] hellogov
   - [x] add hero image was provided see the [Issue comment](https://github.com/hackforla/website/issues/252#issuecomment-593208326)
   - [x] update description: HelloGOV is helping grassroots organizations connect supporters to their state assembly and state senate representatives for call campaigns to advocate on the legislation that matters most to their work. The HelloGOV webapp generates a campaign shortlink that can be used in texts, social posts, and more.
   - [x] update looking for: Q&A to help with implementing end to end testing, UX testing and outreach, UI redesign. All skill levels, all kinds of contribution welcome.
   - [x] add link to their readme.md: https://github.com/helloGov/webapp/blob/master/README.md
   - [x] add link to their slack: https://hackforla.slack.com/archives/CMER3R1RD
- [ ] lucky parking
   - [x] add a link to their slack: https://hackforla.slack.com/archives/CPFDMSV6V
- [ ] railstats.la (aka metro-ontime)
   - [x] add the hero image we decided to use temporarily see the [issue comment](https://github.com/hackforla/website/issues/266#issuecomment-586756931) - the first of the two images
   - [x] add a link to the readme https://github.com/metro-ontime/performance_tracker/blob/master/README.md
   - [x] add a link to their slack: https://hackforla.slack.com/archives/CBPK5D3BQ
- [ ] new schools today
   - [x] add hero image from this [issue comment](https://github.com/hackforla/website/issues/257#issuecomment-586742838) (choose the one that is the correct size)
   - [x] add link to their readme.md https://github.com/hackforla/new-schools-today/blob/master/README.md
   - [x] add link to their wiki https://github.com/hackforla/new-schools-today/wiki
- [ ] public tree map
   - [x] add hero image from this [issue comment](https://github.com/hackforla/website/issues/246#issuecomment-586745834)
   - [x] add tools: Zeplin
- [ ] record-clearance
   - [x] add link to their readme: https://github.com/hackforla/record-clearance/blob/master/README.md
- [x] TDM calculator
   - [x] correct their github link to point to: https://github.com/hackforla/tdm-calculator
   - [x] add link to their wiki: https://github.com/hackforla/tdm-calculator/wiki
   - [x] add a link to their slack: https://hackforla.slack.com/archives/CKY65G266
   - [ ] add a few people to leadership
      - [x] add Bonnie Wolfe as the Product owner, github is experiementsinhonesty, slack link is https://hackforla.slack.com/archives/DE1HK083W
      - [x] add Mindy Morgan as Front End Lead, github is mmorgs, slack link is https://hackforla.slack.com/archives/DPQBYJ5T3
      - [x] add Claire Nguyen as Sr. Fullstack Developer, github is nclairesays, slack link is https://hackforla.slack.com/archives/DHR7M22DN
- [ ] undebate
**needs a bunch of stuff, I will review it tomorrow**
- [x] VRMS
   - [x] add a link to their slack: https://hackforla.slack.com/archives/CRGH5HM0Q
   - [x] add a link to their readme: https://github.com/hackforla/VRMS/blob/master/README.md
   - [x] add a link to their wiki: https://github.com/hackforla/VRMS/wiki
- [ ] Website
**needs a bunch of stuff, I will review it tomorrow**

**Comment by ExperimentsInHonesty** [comment]
- [x] 311 data
   - [x] add hero image from this [issue comment](https://github.com/hackforla/311-data/issues/207#issuecomment-596250233)
- [x] engage
   - [x] update eli's slack link to be: https://app.slack.com/team/U0611PL2D
   - [x] update teddy's slack link to be: https://app.slack.com/team/UAYBYQVV3
- [x] equity language
   - [x] update charlottes slack link to be: https://app.slack.com/team/UA69HNWPQ
   - [x] update Joel's slack link to be: https://app.slack.com/team/UP1U7C53L
- [x] lucky parking
   - [x] update Breeze's slack link to be: https://app.slack.com/team/UNYMHBSQ1
   - [x] update Greg Pawin slack link to be: https://app.slack.com/team/UUEQF3AJG
   - [x] Update Matt Colwin's slack link to be: https://app.slack.com/team/UUF8X8RKP
- [x] tdm-calculator
   - [x] add hero image from this [issue comment](https://github.com/hackforla/website/issues/327#issuecomment-592973026)
- [x] website
    - [x] add the following 
```yaml
  - name: Wiki
    url: 'https://github.com/hackforla/website/wiki'
  - name: Slack
    url: 'https://hackforla.slack.com/archives/C4UM52W93'
```

Notes for myself: 

- sent a [note](https://hackforla.slack.com/archives/C6JBH478W/p1583714269007000) to Teddy on the Engage channel to get Teddy's role on Engage
- sent a [note](https://hackforla.slack.com/archives/C9UU5KKAA/p1583711439004600) to figure out what Mark Jackson's slack handle is on public-tree-map
- sent a [note](https://hackforla.slack.com/archives/CN8NXTPK5/p1583711766000900) to record-clearance re having them do a small redo on their hero image https://github.com/hackforla/record-clearance/issues/37#issuecomment-596268006
- follow up with Kate in person on Monday

**Comment by ExperimentsInHonesty** [comment]
@cnk  this one is different than the rest, so I am sending it to you to figure out why since you probably know the most about this:
- [x] undebate
   - [x] it looks like the project.md file located [here](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/undebate.md) is missing the identification number at the top of the file, which is keeping its languages and contributors from showing up.
   - [x] add hero image from this [issue comment](https://github.com/hackforla/website/issues/255#issuecomment-593977556

**Comment by cnk** [comment]
Undebate is missing it's id because the repo is missing it's hack-for-la tag and so won't get languages and contributors even if we put in the id. (The first call to the GitHub API is 'all projects tagged hack-for-la')

https://github.com/EnCiv/undebate

**Comment by ExperimentsInHonesty** [comment]
@cnk undebate has added the requested tags.  Can you pull the id number now?

**Comment by cnk** [comment]
Yes I have added the hero and id to Undebate #354 Tonight's 3 AM job should pull the data and it will go in the project page once that commit is merged.

**Comment by ExperimentsInHonesty** [comment]
- [x] 311 
   - [x] John R: https://app.slack.com/team/UNFV029Q8
   - [x] Joyce L: https://app.slack.com/team/UQZ71S04A
   - [x] Joshua M: https://app.slack.com/team/UG4G54YUD
   - [x] Ryan S: https://app.slack.com/team/UPB2FHJCX
   - [x] Russell T: https://app.slack.com/team/UKBN4RB7G
- [x] Food Oasis
   - [x] Jenny M:  https://app.slack.com/team/UM4FE6ELQ
   - [x] Tina M:  https://app.slack.com/team/UP4AZM459
   - [x] John D:  https://app.slack.com/team/UFLDX9V19
   - [x] Lucas H:  https://app.slack.com/team/UMQ5H55TN
   - [x] Gabby C:  https://app.slack.com/team/UQG8PEXPX
   - [x] Steven E:  https://app.slack.com/team/UNFG6M8FN

**Comment by ExperimentsInHonesty** [comment]
- [x] Metro-ontime
   - [x] Cameron S:  https://app.slack.com/team/UBENYBXGV
- [x] New Schools Today
   - [x] Ben Swedlow:  https://app.slack.com/team/UKUHHS94L
   - [x] Joshua Bubar: https://app.slack.com/team/UMNNMHXV2
   - [x] Jacob Zwang: https://app.slack.com/team/USM20BUFP

**Comment by ExperimentsInHonesty** [comment]
- [x] Public Tree Map
   - [x] Emily F. : https://app.slack.com/team/U1E5ADA03
   - [x] Isabelle Wagenvoord: https://app.slack.com/team/ULFE20LGY
   - [x] Mark Jackson: https://app.slack.com/team/UNQTRN0DC

**Comment by ExperimentsInHonesty** [comment]
- [x] record clearance
   - [x] Angelina Molina: https://app.slack.com/team/UNG92TWSV
   - [x] Kelsey Justis: https://app.slack.com/team/UP92GTCG2
   - [x] Charlotte Soestini: https://app.slack.com/team/UA69HNWPQ
   - [x] Wesley Rowe: https://app.slack.com/team/U3C7Z2GLE

**Comment by ExperimentsInHonesty** [comment]
- [x] tdm calculator
   - [x] Bonnie Wolfe: https://hackforla.slack.com/team/UE1UG1YFP
   - [x] Kevin Howley: https://app.slack.com/team/UL53VUVPZ
   - [x] John Darragh: https://app.slack.com/team/UFLDX9V19
   - [x] Nicole Doan: https://app.slack.com/team/UBPKHJJVC
   - [x] Mindy Morgan: https://app.slack.com/team/UPGMZK1KR
   - [x] Fang Liu: https://app.slack.com/team/UCE01B4AX
   - [x] Claire Nguyen: https://app.slack.com/team/UHJKN8UJD

**Comment by ExperimentsInHonesty** [comment]
- [x] undebate
   - [x] David F.: https://app.slack.com/team/U6RCX5XRD
- [x] vrms
   - [x] Matt Tapper: https://hackforla.slack.com/team/UPMRJ2R1N
   - [x] Kelsey Capps: https://hackforla.slack.com/team/USU144NL8
   - [x] Bonnie Wolfe: https://hackforla.slack.com/team/UE1UG1YFP

**Comment by ExperimentsInHonesty** [comment]
- [x] website
   - [x] Kegan Maher: https://hackforla.slack.com/team/U0BMTH6A1
   - [x] Bonnie Wolfe: https://hackforla.slack.com/team/UE1UG1YFP
   - [x] Harish Lingam: https://hackforla.slack.com/team/ULYUA6MNF
   - [x] Kian Badie: https://hackforla.slack.com/team/UNAQGKW91
   - [x] please add Cnythia Kiser as Backend Lead:  https://hackforla.slack.com/team/USBB18YDR

**Comment by ExperimentsInHonesty** [comment]
opps can you add 
- [x] vrms
   - [x] Steven Ettinger as API integration : https://app.slack.com/team/UNFG6M8FN

**Comment by leonelRos** [comment]
Ok team. I went through every single project file to check slack URLs and they all are good to go. @ExperimentsInHonesty
