### ISSUE TITLE
Pre-work Checklist: Developer: Don

### ISSUE THREAD

**Issue by DonaldBrower** [hackforla/website#3188]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your GitHub handle and Gmail address with the team lead so you can be added to the Google Drive
- [x] Also, confirm with the team lead that they have added you to the Zoom meeting calendar invites
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
- [x] After you have finished adding yourself to the roster, let a team lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label (gear in right side panel)
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [ ] Attend weekly team meetings:
  - [ ] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [ ] (Optional) Office Hours, Thursdays 7-8pm PST
  - [ ] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [ ] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Follow the steps in section [2.3 Where can I find GitHub issues to work on?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
- [ ] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment.
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [ ] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue.  This update should be done every week for every issue.  The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [ ] Additional notes:
   - [ ] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue (one per person)
  - Good second issue (one per person)
  - Small (one per person, with some exceptions, see below)
  - Medium (you can work on more than one medium issue, but only one at a time)
  - Large (you can work on more than one large issue, but only one at a time)
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
    - You can work on back-to-back small issues if it meets the following criteria:
      - You are learning something new and need to work on an issue of a lesser complexity
      - Special request by a lead or pm
- [ ] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their SCSS classes)
- [ ] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points
- Then, add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting
- You may also add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question
- Lastly, you can post your question in the hfla slack channel and link the issue you're working on, so other volunteers can see and respond

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by DonaldBrower** [comment]
I had a non-blocking issue while setting up the development environment:

* Running `docker-compose up` fails with the following output.  It fails because Ruby can't find the `webrick` package:

```
$  docker-compose up

Creating network "website_default" with the default driver
Pulling hfla_site (jekyll/jekyll:pages)...
pages: Pulling from jekyll/jekyll
df9b9388f04a: Pull complete
837e9cfc7e43: Pull complete
c7850f1a8c23: Pull complete
6ca4c39baa3d: Pull complete
daa3a8cb79d3: Pull complete
482896067e92: Pull complete
Digest: sha256:12400f663c4216295e4da3be29edd7eb9933dd697e0f663b167f538ad674e535
Status: Downloaded newer image for jekyll/jekyll:pages
Creating hfla_site ... done
Attaching to hfla_site
hfla_site    | ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
hfla_site    | Configuration file: _config.yml
hfla_site    | Configuration file: _config.docker.yml
hfla_site    |             Source: .
hfla_site    |        Destination: /srv/jekyll/_site
hfla_site    |  Incremental build: enabled
hfla_site    |       Generating...
hfla_site    |                     done in 29.182 seconds.
hfla_site    |  Auto-regeneration: enabled for '.'
hfla_site    | <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
hfla_site    | ...
hfla_site exited with code 1
```

* [This issue from the jekyll project](https://github.com/jekyll/jekyll/issues/8523) says that webrick isn't included in Ruby 3.x versions, and that it should be included manually.

* For a work around, I made a copy of `docker-compose.yml` called `docker-compose.local.yml`, and included `gem install webrick` in the command for the hfla_site service.  Here is the new file:

```
version: "3"
services:
  hfla_site:
    image: jekyll/jekyll:pages
    container_name: hfla_site
    command: >
      bash -c 
      "gem install webrick && jekyll serve --force_polling --livereload --config _config.yml,_config.docker.yml -I"
    environment:
      - JEKYLL_ENV=docker
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
```

* `docker-compose -f docker-compose.local.yml up` to start the services with the new file.

---

I think anyone else setting up the environment for the first time, or otherwise pulling the latest jekyll:pages Docker image will have the same problem. [This commit shows the authors updating to Ruby 3 on March 26](https://github.com/envygeeks/jekyll-docker/commit/499c8abfbf06e12d731935145e3ab64c13ab27c7)

**Comment by Sparky-code** [comment]
Hi @DonaldBrower Sorry for the slow reply

If you are having issues with Docker please see t[his thread](https://hackforla.slack.com/archives/C4UM52W93/p1655862959161349) on slack, it should solve the issue for now. We are working on a more permanent fix. A reminder to not use `git add .` when pushing changes to github as we do not want to push the altered docker-compose file.

Please move this issue to the In-Progress column on the Project Board.
<img width="336" alt="Screen Shot 2022-06-23 at 3 15 54 PM" src="https://user-images.githubusercontent.com/57715733/175379979-c7298127-cf2e-4d8f-9174-2750e8a32586.png">

**Comment by ExperimentsInHonesty** [comment]
@DonaldBrower we see you did two issues and then we didn't hear from you anymore.  Are you still interested in working on the hfla website?

**Comment by HackforLABot** [comment]
## Activity Log: DonaldBrower
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- DonaldBrower opened: https://github.com/hackforla/website/issues/3188 at 05/31/2022, 08:14 PM PDT
- DonaldBrower assigned: https://github.com/hackforla/website/issues/3188#issuecomment-1143072322 at 06/01/2022, 08:47 PM PDT
- DonaldBrower commented on: https://github.com/hackforla/website/issues/3188#issuecomment-1146677190 at 06/04/2022, 12:58 PM PDT
- DonaldBrower assigned: https://github.com/hackforla/website/issues/2877#issuecomment-1049094817 at 06/04/2022, 01:29 PM PDT
- DonaldBrower commented on: https://github.com/hackforla/website/issues/2877#issuecomment-1146685251 at 06/04/2022, 02:02 PM PDT
- DonaldBrower commented on: https://github.com/hackforla/website/issues/2877#issuecomment-1146685942 at 06/04/2022, 02:09 PM PDT
- DonaldBrower opened: https://github.com/hackforla/website/pull/3218 at 06/04/2022, 02:28 PM PDT
- DonaldBrower issue closed by PR 3218: https://github.com/hackforla/website/issues/2877#event-6742566844 at 06/04/2022, 05:08 PM PDT
- DonaldBrower PR was merged: https://github.com/hackforla/website/pull/3218#event-6742566848 at 06/04/2022, 05:08 PM PDT
- DonaldBrower assigned: https://github.com/hackforla/website/issues/3214#issuecomment-1145857701 at 06/06/2022, 10:29 PM PDT
- DonaldBrower commented on: https://github.com/hackforla/website/issues/3214#issuecomment-1148222618 at 06/06/2022, 10:46 PM PDT
- DonaldBrower opened: https://github.com/hackforla/website/pull/3226 at 06/06/2022, 11:03 PM PDT
- DonaldBrower issue closed by PR 3226: https://github.com/hackforla/website/issues/3214#event-6789394648 at 06/10/2022, 06:22 PM PDT
- DonaldBrower PR was merged: https://github.com/hackforla/website/pull/3226#event-6789394653 at 06/10/2022, 06:22 PM PDT
- DonaldBrower commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1152843793 at 06/10/2022, 08:12 PM PDT
- DonaldBrower commented on: https://github.com/hackforla/website/issues/3068#issuecomment-1154647750 at 06/13/2022, 07:43 PM PDT
- DonaldBrower issue closed as completed: https://github.com/hackforla/website/issues/3188#event-7282058072 at 08/29/2022, 01:44 PM PDT
