### ISSUE TITLE
Creating issues: Review GHAs in wiki pages

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#3229]
### Dependency
- [x] #3274
- [x] #3283

### Overview
As a developer, I would like up to date information about our GitHub actions in a wiki page. For this epic, we will write issues to review and update wiki pages for [each GitHub action](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions#hack-for-las-ghas) which will then be added to dependency items above.

### Action Items
- [ ] This issue should only be assigned to a lead.
- [ ] Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki). When writing new issues to update the wiki, please keep the following in mind and consider adding something about it in the new issues created.
- [ ] Lead would guide other developers on creating issues using the following steps (These steps would be recurring for each issue that would be created, and this action item should stay unchecked until all the issues have been created):
    - Check the following [Google spreadsheet tab](https://docs.google.com/spreadsheets/d/1PpuBt-2NP4re3rQup_YXQNM3jRC5-QsOvMhsxI2nO0M/edit#gid=0) to track the issue creation progress. (there are 13 issues in total that need to be made)
    - Choose a row for which issue needs to be created and add your name in the Issue writer column. (If multiple team members creating issues simultaneously, let other team members know which row you would be working on, so there are no duplicate issues.) See column B to know if someone has started writing the issue already.
    - Write an issue with steps to review and update a wiki page following the sample issue below as well as using [How to create issues](https://github.com/hackforla/website/wiki/How-to-create-issues) wiki.
    - Update the issue link in the [Google spreadsheet tab](https://docs.google.com/spreadsheets/d/1PpuBt-2NP4re3rQup_YXQNM3jRC5-QsOvMhsxI2nO0M/edit#gid=0)
- [ ] Add the issue numbers of all the issues that have been created to the dependency section above as well as add ready for milestone labels on each of these issues if it looks good.
- [ ] If all the issues for the spreadsheet tab have been created, add a dependency label and move this issue to ice box column.
- [ ] If all the dependency issues are closed, remove the dependency label, move this issue from ice box to In progress column, check off the dependency from #3229 (if all the dependencies in #3229 are checked off, remove the dependency label, move #3229 issue from ice box to In progress column) and close this issue.

### Resources/Instructions
- [GitHub actions refactor proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=291026990)
- [List of HfLA GitHub actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)
- [How to create issues](https://github.com/hackforla/website/wiki/How-to-create-issues) wiki
- [Issue creation tracker spreadsheet](https://docs.google.com/spreadsheets/d/1PpuBt-2NP4re3rQup_YXQNM3jRC5-QsOvMhsxI2nO0M/edit#gid=0).

### Overview
As a developer, I would like up to date information about our GitHub Actions in a wiki page. For this issue, we will review and update the wiki page for [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly).

### Action Items
- [ ] Read the information about the add-update-label-weekly GHA [here](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions#add-update-label-weekly)
- [ ] Understand how the workflow works. Related files: [move-closed-issues.yaml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/move-closed-issues.yaml) and [sort-closed-issues.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/move-closed-issues/sort-closed-issues.js)
- [ ] Review the information on the [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) wiki page
- [ ] Add or edit the following information for the [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) wiki page for each of the following sections:
    - [ ] Summary (update overview, links, definitions for the GHA if possible). [Note: update the info [here](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions#add-update-label-weekly) as well, if required]
    - [ ] Schedule (When does it trigger).
    - [ ] Workflow (Include the link to the workflow file as well as the process steps for a complete workflow cycle)
    - [ ] Supporting Files/Folder (Include links to the files or folders that are referenced in the workflow files as well as briefly describe the functionality of each file involved)
- [ ] Reach out to the leads during the team meeting or on slack for a review since no PR would be required for this issue.
- [ ] For reviewers: Once this issue has been reviewed and approved, please update and edit epic https://github.com/hackforla/website/issues/3229 by
    - [ ] Checking off the dependency for this issue
    - [ ] If all dependencies are checked off, please move issue https://github.com/hackforla/website/issues/3229 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- [GHA list](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions#hack-for-las-ghas)
- [Move-closed-issues.yaml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/move-closed-issues.yaml) 
- [Sort-closed-issues.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/move-closed-issues/sort-closed-issues.js)
- [Move closed issues GitHub action folder](https://github.com/hackforla/website/tree/gh-pages/github-actions/move-closed-issues).

**Comment by vincentdang** [comment]
@SAUMILDHANKAR I am interested in this issue but I am not a lead.

**Comment by ExperimentsInHonesty** [comment]
This might be a duplicate of another issue.  If it is, close it if appropriate.

**Comment by roslynwythe** [comment]
- Duplicate of #6403
