### ISSUE TITLE
Pre-work Checklist: Researcher: Vaisali Krishna Kumar

### ISSUE THREAD

**Issue by vaisali89** [hackforla/website#3239]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new researcher on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the research team lead
- [x]  (once added to the drive) Add yourself to the team roster.
- [x]  Confirm with the research team lead that they have added you to the meeting invites 
  - [ ] UX weekly team meeting, Thursdays 5 pm PST
  - [x] All team meetings (UX, Development, Product), Sunday 10 am PST
  - [x] Research team meetings, Wednesdays, 2:00 pm PST
- [x] Confirm with the research team lead that they have added you to Github repo
- [x] Self Assign this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [x]  Confirm that the research team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings:
   - UX weekly team meeting, Thursdays 5 pm PST
   - All team meetings (UX, Development, Product), Sunday 10 am PST
   - Research team meetings, Wednesdays, 2:00 pm PST
- [x] Review the  [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) to see what Research Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [x] Meet with team lead to receive first assignment
- [x] Once you accept an assignment (issue), please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [x] Weekly, please also provide an update on the issue
```
provide update
1. Progress
2. Blockers
3. Availability
4. ETA
```

### Resources/Instructions
- [Project Board filtered to show role: user research](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149)
- [Googledrive-UI/UX](https://drive.google.com/drive/folders/1Jq24FlOJTEmRD09M5xOgpWuHcKswH5Dk)
- [Googledrive-HackforLA website](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT)
- [UX Research Presentations](https://drive.google.com/drive/folders/1yV9YRrjVKmVLU_xSM_BjtdIaNITRhP5j)
- [Weekly Meeting Agendas](https://github.com/hackforla/website/issues/2106)
- [Example of an issue with really good updates](https://github.com/hackforla/website/issues/2537), this issue also is a good example of when you have finished an issue, but there is still more work to be done, so it leads to a new issue being made instead of changing the scope of the original issue.

**Comment by HackforLABot** [comment]
## Activity Log: vaisali89
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- vaisali89 opened: https://github.com/hackforla/website/issues/3239 at 06/12/2022, 10:43 AM PDT
- vaisali89 assigned: https://github.com/hackforla/website/issues/3239#issuecomment-1153244077 at 06/12/2022, 11:57 AM PDT
- vaisali89 assigned: https://github.com/hackforla/website/issues/3003#issuecomment-1079440137 at 06/15/2022, 03:00 PM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/3003#issuecomment-1156988044 at 06/15/2022, 03:01 PM PDT
- vaisali89 closed as completed: https://github.com/hackforla/website/issues/3239#event-6816430135 at 06/15/2022, 03:01 PM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/3003#issuecomment-1166582876 at 06/26/2022, 09:39 AM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/3003#issuecomment-1174008957 at 07/04/2022, 10:02 AM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/3003#issuecomment-1186561214 at 07/17/2022, 09:19 AM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/3003#issuecomment-1188424328 at 07/18/2022, 04:14 PM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/2498#issuecomment-1190673409 at 07/20/2022, 12:32 PM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/2680#issuecomment-1200620185 at 07/31/2022, 07:35 PM PDT
- vaisali89 assigned: https://github.com/hackforla/website/issues/2949#issuecomment-1063270297 at 08/01/2022, 06:23 PM PDT
- vaisali89 opened: https://github.com/hackforla/website/issues/3448 at 08/02/2022, 02:21 PM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/2498#issuecomment-1211222296 at 08/10/2022, 01:17 PM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/2705#issuecomment-1214412947 at 08/14/2022, 09:44 AM PDT
- vaisali89 opened: https://github.com/hackforla/website/issues/3473 at 08/17/2022, 12:39 PM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/3473#issuecomment-1218421803 at 08/17/2022, 12:44 PM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/2705#issuecomment-1229528340 at 08/28/2022, 11:41 AM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/3003#issuecomment-1229971437 at 08/29/2022, 01:51 AM PDT
- vaisali89 commented on: https://github.com/hackforla/website/issues/2949#issuecomment-1241765693 at 09/09/2022, 02:59 AM PDT
- vaisali89 closed as completed: https://github.com/hackforla/website/issues/2949#event-7429723565 at 09/21/2022, 03:47 AM PDT
- vaisali89 assigned: https://github.com/hackforla/website/issues/3343#issuecomment-1418248835 at 02/05/2023, 11:48 AM PST
- vaisali89 unassigned: https://github.com/hackforla/website/issues/2949#issuecomment-1257240182 at 02/14/2023, 09:39 PM PST
- vaisali89 unassigned: https://github.com/hackforla/website/issues/3343 at 10/25/2024, 04:31 PM PDT
