### ISSUE TITLE
Pre-work Checklist: Developer: [Matthew Eichler]

### ISSUE THREAD

**Issue by Mattre7** [hackforla/website#3243]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events.

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your GitHub handle and Gmail address with merge team members and technical leads so you can be added to the Google Drive
  - [x] To find contact information for the merge team members and technical leads, please take a look at our [Meet the Team wiki page](https://github.com/hackforla/website/wiki/Meet-the-Team)
- [x] Also, confirm with the technical lead that they have added you to the Zoom meeting calendar invites
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
- [x] After you have finished adding yourself to the roster, let a technical lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label (gear in right side panel)
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note: There are no meetings the 1st-7th of every month.
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Follow the steps in section [2.3 Where can I find GitHub issues to work on?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
- [x] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment. (Note: Please provide estimates on all the issues that you pick up, going forward.)
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below (in this pre-work issue only) and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [x] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue. **This update should be done every week for every issue that you are assigned to**. The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue (one per person)
  - Good second issue (one per person)
  - Small (one per person, with some exceptions, see below)
  - Medium (you can work on more than one medium issue, but only one at a time)
  - Large (you can work on more than one large issue, but only one at a time)
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
    - You can work on back-to-back small issues if it meets the following criteria:
      - You are learning something new and need to work on an issue of a lesser complexity
      - Special request by a lead or pm
- [x] Read the [Start Here - Developers](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8583%3A0) in Figma
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their SCSS classes)
- [x] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points.
- Then, add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question. In addition, you will still need to post a Slack message or bring it up in meeting so we know you need help; see below for how to do that.
- Also, you can post your question on the hfla-site slack channel and link the issue you're working on, so other developers can see and respond.
- Lastly, you can add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting. Please bring it during the meeting that you need help.

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by tamara-snyder** [comment]
Hi @Mattre7, please move this issue to the In-Progress column on the old Project Board (we aren't using the new one yet).
<img width="336" alt="Screen Shot 2022-06-23 at 3 15 54 PM" src="https://user-images.githubusercontent.com/57715733/175392392-efbbb0d6-1481-4617-aa2b-e8ae5085c443.png">

**Comment by Mattre7** [comment]
Hi Tamara, sorry for the late response but hope I fixed it correctly!

**Comment by Mattre7** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings? 

So far I would say I have spent somewhere around 6-8 hours including the onboarding and one of the meetings. A lot of my time was spent trying to figure out a docker-compose up issue until I found the solution in the community website slack page. I believe I finished that issue and am waiting for review to make sure I pushed my changes correctly

**Comment by HackforLABot** [comment]
## Activity Log: Mattre7
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- Mattre7 opened: https://github.com/hackforla/website/issues/3243 at 06/13/2022, 07:31 PM PDT
- Mattre7 assigned: https://github.com/hackforla/website/issues/3243#issuecomment-1154641396 at 06/13/2022, 08:32 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/3243#issuecomment-1166358052 at 06/25/2022, 01:39 PM PDT
- Mattre7 assigned: https://github.com/hackforla/website/issues/2816#issuecomment-1046317017 at 06/25/2022, 03:23 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/2816#issuecomment-1166374674 at 06/25/2022, 03:55 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/3243#issuecomment-1166375244 at 06/25/2022, 04:00 PM PDT
- Mattre7 opened: https://github.com/hackforla/website/pull/3429 at 07/25/2022, 11:17 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/2816#issuecomment-1195053536 at 07/25/2022, 11:19 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3429#issuecomment-1196137304 at 07/26/2022, 05:26 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3429#issuecomment-1197424661 at 07/27/2022, 03:10 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3429#issuecomment-1197533027 at 07/27/2022, 06:00 PM PDT
- Mattre7 closed: https://github.com/hackforla/website/pull/3429#event-7077391255 at 07/27/2022, 06:00 PM PDT
- Mattre7 opened: https://github.com/hackforla/website/pull/3439 at 07/28/2022, 01:11 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3439#issuecomment-1198791784 at 07/28/2022, 06:30 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/2816#issuecomment-1198793952 at 07/28/2022, 06:35 PM PDT
- Mattre7 PR was merged: https://github.com/hackforla/website/pull/3439#event-7085994921 at 07/28/2022, 06:35 PM PDT
- Mattre7 issue closed by PR 3439: https://github.com/hackforla/website/issues/2816#event-7085994994 at 07/28/2022, 06:35 PM PDT
- Mattre7 closed as completed: https://github.com/hackforla/website/issues/3243#event-7086001142 at 07/28/2022, 06:37 PM PDT
- Mattre7 assigned: https://github.com/hackforla/website/issues/3400 at 07/28/2022, 07:01 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/3400#issuecomment-1198814297 at 07/28/2022, 07:22 PM PDT
- Mattre7 opened: https://github.com/hackforla/website/pull/3442 at 07/28/2022, 07:38 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/3400#issuecomment-1198821552 at 07/28/2022, 07:39 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3442#issuecomment-1198864773 at 07/28/2022, 09:21 PM PDT
- Mattre7 PR was merged: https://github.com/hackforla/website/pull/3442#event-7089999633 at 07/29/2022, 07:40 AM PDT
- Mattre7 issue closed by PR 3442: https://github.com/hackforla/website/issues/3400#event-7089999767 at 07/29/2022, 07:40 AM PDT
- Mattre7 assigned: https://github.com/hackforla/website/issues/3358#issuecomment-1180866276 at 07/29/2022, 10:13 PM PDT
- Mattre7 opened: https://github.com/hackforla/website/pull/3444 at 07/29/2022, 10:33 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/3358#issuecomment-1200099050 at 07/29/2022, 11:07 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3444#issuecomment-1200292352 at 07/30/2022, 01:56 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3444#issuecomment-1200307045 at 07/30/2022, 03:46 PM PDT
- Mattre7 PR was merged: https://github.com/hackforla/website/pull/3444#event-7095882969 at 07/30/2022, 10:55 PM PDT
- Mattre7 assigned: https://github.com/hackforla/website/issues/2451#issuecomment-961536900 at 07/31/2022, 04:31 PM PDT
- Mattre7 opened: https://github.com/hackforla/website/pull/3446 at 08/01/2022, 02:05 AM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/2451#issuecomment-1200926342 at 08/01/2022, 02:06 AM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3446#issuecomment-1203019153 at 08/02/2022, 10:30 AM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3446#issuecomment-1203375666 at 08/02/2022, 06:19 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3446#issuecomment-1204621024 at 08/03/2022, 05:26 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3446#issuecomment-1226041600 at 08/24/2022, 10:43 AM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3446#issuecomment-1234954453 at 09/01/2022, 06:06 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3446#issuecomment-1244235982 at 09/12/2022, 12:29 PM PDT
- Mattre7 PR was merged: https://github.com/hackforla/website/pull/3446#event-7381082948 at 09/13/2022, 05:56 PM PDT
- Mattre7 issue closed by PR 3446: https://github.com/hackforla/website/issues/2451#event-7381083204 at 09/13/2022, 05:56 PM PDT
- Mattre7 issue closed by PR 3444: https://github.com/hackforla/website/issues/3358#event-7417430757 at 09/19/2022, 03:39 PM PDT
- Mattre7 assigned: https://github.com/hackforla/website/issues/3489#issuecomment-1236396829 at 09/19/2022, 10:23 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/issues/3489#issuecomment-1251866319 at 09/19/2022, 10:41 PM PDT
- Mattre7 opened: https://github.com/hackforla/website/pull/3581 at 09/25/2022, 10:25 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3581#issuecomment-1258202069 at 09/26/2022, 08:18 AM PDT
- Mattre7 issue closed by PR 3581: https://github.com/hackforla/website/issues/3489#event-7473359091 at 09/27/2022, 06:06 PM PDT
- Mattre7 PR was merged: https://github.com/hackforla/website/pull/3581#event-7473359028 at 09/27/2022, 06:06 PM PDT
- Mattre7 commented on: https://github.com/hackforla/website/pull/3581#issuecomment-1260265132 at 09/27/2022, 06:09 PM PDT
