### ISSUE TITLE
Pre-work Checklist: Researcher: [Sandarsh]

### ISSUE THREAD

**Issue by sandarshp** [hackforla/website#3253]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events

### Overview
As a new researcher on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [x] Share your Gmail address with the research team lead
- [x]  (once added to the drive) Add yourself to the team roster.
- [x]  Confirm with the research team lead that they have added you to the meeting invites and Github repo
- [x] Self Assign this issue (gear in right side panel)
- [x] Add this issue to Projects: Project Board (gear in right side panel)
- [ ]  Confirm that the research team lead has given you login credentials for the team Miro and Figma accounts
- [x] Attend weekly team meetings:
   - UX weekly team meeting, Thursdays 5 pm PST
   - All team meetings (UX, Development, Product), Sunday 10 am PST
   - Research team meetings, Wednesdays, 2:00 pm PST
- [x] Review the  [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) to see what Research Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [ ] Meet with team lead to receive first assignment
- [ ] Once you accept an assignment (issue), please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [ ] Weekly, please also provide an update on the issue
```
provide update
1. Progress
2. Blockers
3. Availability
4. ETA
```

### Resources/Instructions
- [Project Board filtered to show role: user research](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22)
- [Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
- [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149)
- [Googledrive-UI/UX](https://drive.google.com/drive/folders/1Jq24FlOJTEmRD09M5xOgpWuHcKswH5Dk)
- [Googledrive-HackforLA website](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT)
- [UX Research Presentations](https://drive.google.com/drive/folders/1yV9YRrjVKmVLU_xSM_BjtdIaNITRhP5j)
- [Weekly Meeting Agendas](https://github.com/hackforla/website/issues/2106)
- [Example of an issue with really good updates](https://github.com/hackforla/website/issues/2537), this issue also is a good example of when you have finished an issue, but there is still more work to be done, so it leads to a new issue being made instead of changing the scope of the original issue.

**Comment by ExperimentsInHonesty** [comment]
Hi @sandarshp 
- I left a message for you on the issue you are assigned to #2662 

> Hi @sandarshp  😃! I noticed that you joined the Hack for LA website team on June 15th but have not finished the Pre-work process or closed any issues. 
> 
> Will you be coming back?  Please let us know so that we can unassign you from this issue if you are not going to work on it.
> 
> Do you have feedback for us?

**Comment by roslynwythe** [comment]
Hi @sandarshp we are closing this issue because we have not heard from you in almost a year, but if you are interested in participating in Hack for LA in the future, you are welcome to reopen this issue, leave an update,  and move it into the "In Progress" column.  Thank you.

**Comment by HackforLABot** [comment]
## Activity Log: sandarshp
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- sandarshp opened: https://github.com/hackforla/website/issues/3253 at 06/15/2022, 02:19 PM PDT
- sandarshp assigned: https://github.com/hackforla/website/issues/3253#issuecomment-1156957293 at 06/15/2022, 02:25 PM PDT
- sandarshp assigned: https://github.com/hackforla/website/issues/1696#issuecomment-1030898446 at 06/22/2022, 01:04 PM PDT
- sandarshp unassigned: https://github.com/hackforla/website/issues/1696#issuecomment-1030898446 at 06/29/2022, 12:14 PM PDT
- sandarshp assigned: https://github.com/hackforla/website/issues/2662#issuecomment-1158573419 at 06/29/2022, 12:15 PM PDT
- sandarshp commented on: https://github.com/hackforla/website/issues/2662#issuecomment-1192768837 at 07/22/2022, 09:59 AM PDT
- sandarshp commented on: https://github.com/hackforla/website/issues/2662#issuecomment-1200456922 at 07/31/2022, 09:28 AM PDT
- sandarshp commented on: https://github.com/hackforla/website/issues/2662#issuecomment-1213108455 at 08/12/2022, 06:26 AM PDT
- sandarshp commented on: https://github.com/hackforla/website/issues/2662#issuecomment-1218481287 at 08/17/2022, 01:54 PM PDT
- sandarshp commented on: https://github.com/hackforla/website/issues/2662#issuecomment-1254144713 at 09/21/2022, 12:37 PM PDT
- sandarshp unassigned: https://github.com/hackforla/website/issues/2662#issuecomment-1254144713 at 09/21/2022, 12:41 PM PDT
- sandarshp issue closed as not planned: https://github.com/hackforla/website/issues/3253#event-9712095398 at 07/03/2023, 10:44 AM PDT
