### ISSUE TITLE
Pre-work Checklist: Developer: Beckett

### ISSUE THREAD

**Issue by BeckettOBrien** [hackforla/website#3267]
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events.

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Action Items
- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your GitHub handle and Gmail address with a merge team member or technical lead so you can be added to the Google Drive
  - [x] To find contact information for the merge team members and technical leads, please take a look at our [Meet the Team wiki page](https://github.com/hackforla/website/wiki/Meet-the-Team)
- [x] Also, confirm with a merge team member or a technical lead that they have added you to the Google Calendar invites for our Zoom meetings
- [x] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
- [x] After you have finished adding yourself to the roster, let a merge team member or a technical lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub
- [x] Once added to the website-write team:
  - [x] Self Assign this issue (gear in right side panel)
  - [x] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label (gear in right side panel)
  - [x] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [x] Signup for a [Figma](https://Figma.com) account
- [x] Attend weekly team meetings:
  - [x] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [x] (Optional) Office Hours, Thursdays 7-8pm PST
  - [x] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [x] Note: There are no meetings on the 1st-7th of every month.
- [x] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [x] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [x] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [x] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [x] Follow the steps in section [2.3 Where can I find GitHub issues to work on?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
  - [x] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
- [ ] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [x] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment. (Note: Please provide estimates on all the issues that you pick up, going forward.)
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [x] Time spent so far: Copy the question below into a new comment below (in this pre-work issue only) and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [ ] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue. **This update should be done every week for every issue that you are assigned to**. The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [x] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [x] Additional notes:
   - [x] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [x] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [x] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues with increasing complexity in the following order:
  - Good first issue (one per person)
  - Good second issue (one per person)
  - Small (one per person, with some exceptions, see below)
  - Medium (you can work on more than one medium issue, but only one at a time)
  - Large (you can work on more than one large issue, but only one at a time)
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
    - You can work on back-to-back small issues if it meets the following criteria:
      - You are learning something new and need to work on an issue of a lesser complexity
      - Special request by a lead or pm
- [x] Read the [Start Here - Developers](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8583%3A0) in Figma
- [x] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their SCSS classes)
- [ ] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points.
- Then, add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question. In addition, you will still need to post a Slack message or bring it up in meeting so we know you need help; see below for how to do that.
- Also, you can post your question on the hfla-site slack channel and link the issue you're working on, so other developers can see and respond.
- Lastly, you can add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting. Please bring it during the meeting that you need help.

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

**Comment by BeckettOBrien** [comment]
I've run into an issue while trying to run the website server. `docker-compose up` runs normally until it throws an error saying `'require': cannot load such file -- webrick (LoadError)`. So far I have tried:
* Following the same steps on another, non-WSL machine to make sure that it isn't an issue with my local environment, but I get the same error
* I was able to get the site running by adding a `gem install webrick` command to the docker compose configuration, but I'm not sure if that's the right solution or if this error is indicative of a bigger issue with either the docker image or my environment

Here is the full output of running `docker-compose up`:
```
[+] Running 2/2
 ⠿ Network website_default  Created                                                                                0.1s
 ⠿ Container hfla_site      Created                                                                                0.1s
Attaching to hfla_site
hfla_site  | ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
hfla_site  | Configuration file: _config.yml
hfla_site  | Configuration file: _config.docker.yml
hfla_site  |             Source: .
hfla_site  |        Destination: /srv/jekyll/_site
hfla_site  |  Incremental build: enabled
hfla_site  |       Generating...
hfla_site  |                     done in 3.215 seconds.
hfla_site  |                     Auto-regeneration may not work on some Windows versions.
hfla_site  |                     Please see: https://github.com/Microsoft/BashOnWindows/issues/216
hfla_site  |                     If it does not work, please upgrade Bash on Windows or run Jekyll with --no-watch.
hfla_site  |  Auto-regeneration: enabled for '.'
hfla_site  | <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
hfla_site  |    from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:184:in `require_relative'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:184:in `setup'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:102:in `process'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
hfla_site  |    from /usr/gem/bin/jekyll:25:in `load'
hfla_site  |    from /usr/gem/bin/jekyll:25:in `<main>'
hfla_site exited with code 1
```

I would really appreciate any help with this. Thank you!

**Comment by tamara-snyder** [comment]
Hi @BeckettOBrien, I am unchecking the "Time spent so far" section since you haven't added a comment for that yet. Please check the box again once you have posted your "Time spent" comment.

**Comment by BeckettOBrien** [comment]
Sorry, I accidentally posted it on a different issue. I'll move it here right away

**Comment by BeckettOBrien** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings? Probably 6-7 hours (including the internship onboarding meeting)

**Comment by HackforLABot** [comment]
## Activity Log: BeckettOBrien
### Repo: https://github.com/hackforla/website

#####  ⚠ Important note: The bot updates this comment automatically - do not edit

- BeckettOBrien opened: https://github.com/hackforla/website/issues/3267 at 06/20/2022, 02:41 PM PDT
- BeckettOBrien assigned: https://github.com/hackforla/website/issues/3267#issuecomment-1160868474 at 06/20/2022, 02:56 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3267#issuecomment-1162514873 at 06/21/2022, 06:13 PM PDT
- BeckettOBrien assigned: https://github.com/hackforla/website/issues/2876#issuecomment-1049090274 at 06/21/2022, 07:45 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/2876#issuecomment-1162574489 at 06/21/2022, 07:50 PM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/pull/3285 at 06/21/2022, 08:14 PM PDT
- BeckettOBrien issue closed by PR 3285: https://github.com/hackforla/website/issues/2876#event-6853033478 at 06/21/2022, 10:24 PM PDT
- BeckettOBrien PR was merged: https://github.com/hackforla/website/pull/3285#event-6853033498 at 06/21/2022, 10:24 PM PDT
- BeckettOBrien assigned: https://github.com/hackforla/website/issues/3093#issuecomment-1116761701 at 06/22/2022, 03:30 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3093#issuecomment-1163715523 at 06/22/2022, 03:33 PM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/pull/3288 at 06/22/2022, 03:53 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3224#issuecomment-1163752423 at 06/22/2022, 04:18 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3224#pullrequestreview-1016131290 at 06/22/2022, 04:37 PM PDT
- BeckettOBrien issue closed by PR 3288: https://github.com/hackforla/website/issues/3093#event-6869155925 at 06/23/2022, 12:53 PM PDT
- BeckettOBrien PR was merged: https://github.com/hackforla/website/pull/3288#event-6869155950 at 06/23/2022, 12:53 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3267#issuecomment-1164825027 at 06/23/2022, 01:13 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3267#issuecomment-1164825075 at 06/23/2022, 01:13 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3297#issuecomment-1164975221 at 06/23/2022, 03:28 PM PDT
- BeckettOBrien assigned: https://github.com/hackforla/website/issues/3177#issuecomment-1147996123 at 06/23/2022, 04:18 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3177#issuecomment-1165003659 at 06/23/2022, 04:19 PM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/pull/3298 at 06/23/2022, 04:37 PM PDT
- BeckettOBrien issue closed by PR 3298: https://github.com/hackforla/website/issues/3177#event-6879104849 at 06/25/2022, 07:50 AM PDT
- BeckettOBrien PR was merged: https://github.com/hackforla/website/pull/3298#event-6879104854 at 06/25/2022, 07:50 AM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/issues/3307 at 06/26/2022, 11:40 AM PDT
- BeckettOBrien assigned: https://github.com/hackforla/website/issues/3257#issuecomment-1162705692 at 06/27/2022, 01:37 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3257#issuecomment-1167864276 at 06/27/2022, 01:38 PM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/pull/3321 at 06/27/2022, 02:19 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3257#issuecomment-1169259075 at 06/28/2022, 02:26 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3319#issuecomment-1169360677 at 06/28/2022, 03:42 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3319#pullrequestreview-1022560062 at 06/28/2022, 03:52 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3322#issuecomment-1169459288 at 06/28/2022, 07:16 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3322#pullrequestreview-1022659022 at 06/28/2022, 07:19 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3321#issuecomment-1170486890 at 06/29/2022, 01:58 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3321#issuecomment-1170572777 at 06/29/2022, 03:56 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3321#issuecomment-1170608684 at 06/29/2022, 05:05 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3321#issuecomment-1171566666 at 06/30/2022, 11:56 AM PDT
- BeckettOBrien issue closed by PR 3321: https://github.com/hackforla/website/issues/3257#event-6921545448 at 07/01/2022, 05:54 PM PDT
- BeckettOBrien PR was merged: https://github.com/hackforla/website/pull/3321#event-6921545450 at 07/01/2022, 05:54 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3321#issuecomment-1173168293 at 07/03/2022, 01:42 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3321#issuecomment-1173168931 at 07/03/2022, 01:47 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3321#issuecomment-1175482608 at 07/05/2022, 01:47 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3257#issuecomment-1175484735 at 07/05/2022, 01:49 PM PDT
- BeckettOBrien reopened: https://github.com/hackforla/website/issues/3257#issuecomment-1175484735 at 07/05/2022, 01:49 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3257#issuecomment-1175506616 at 07/05/2022, 02:16 PM PDT
- BeckettOBrien issue closed by PR 3321: https://github.com/hackforla/website/issues/3257#event-6938828809 at 07/05/2022, 07:36 PM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/pull/3333 at 07/05/2022, 10:03 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3333#issuecomment-1175785431 at 07/05/2022, 10:05 PM PDT
- BeckettOBrien closed: https://github.com/hackforla/website/pull/3333#event-6945236987 at 07/06/2022, 11:31 AM PDT
- BeckettOBrien reopened: https://github.com/hackforla/website/pull/3333#event-6945236987 at 07/06/2022, 11:31 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3333#issuecomment-1176548248 at 07/06/2022, 11:36 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3333#issuecomment-1177051723 at 07/06/2022, 09:27 PM PDT
- BeckettOBrien closed: https://github.com/hackforla/website/pull/3333#event-6948169665 at 07/06/2022, 09:27 PM PDT
- BeckettOBrien assigned: https://github.com/hackforla/website/issues/3131#issuecomment-1170764870 at 07/07/2022, 10:10 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3131#issuecomment-1177949617 at 07/07/2022, 10:11 AM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/pull/3338 at 07/07/2022, 10:34 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3329#issuecomment-1178021534 at 07/07/2022, 11:08 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3257#issuecomment-1178040749 at 07/07/2022, 11:25 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3329#pullrequestreview-1032012010 at 07/07/2022, 11:35 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3257#issuecomment-1178232280 at 07/07/2022, 02:08 PM PDT
- BeckettOBrien PR was merged: https://github.com/hackforla/website/pull/3338#event-6964440313 at 07/09/2022, 04:26 PM PDT
- BeckettOBrien issue closed by PR 3338: https://github.com/hackforla/website/issues/3131#event-6964501816 at 07/09/2022, 06:11 PM PDT
- BeckettOBrien assigned: https://github.com/hackforla/website/issues/2221#issuecomment-1120289117 at 07/11/2022, 01:55 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/2221#issuecomment-1180861635 at 07/11/2022, 01:56 PM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/pull/3359 at 07/11/2022, 02:17 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3359#issuecomment-1180885849 at 07/11/2022, 02:25 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/3257#issuecomment-1182648781 at 07/12/2022, 06:05 PM PDT
- BeckettOBrien closed by PR 3321: https://github.com/hackforla/website/issues/3257#event-6982275847 at 07/12/2022, 07:17 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3368#issuecomment-1183689459 at 07/13/2022, 02:20 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3368#pullrequestreview-1038009950 at 07/13/2022, 02:37 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3372#issuecomment-1185850192 at 07/15/2022, 12:40 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3372#pullrequestreview-1040766609 at 07/15/2022, 01:19 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3373#issuecomment-1185964373 at 07/15/2022, 02:35 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3373#pullrequestreview-1040837912 at 07/15/2022, 02:56 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3373#pullrequestreview-1041075322 at 07/16/2022, 11:24 PM PDT
- BeckettOBrien issue closed by PR 3359: https://github.com/hackforla/website/issues/2221#event-7008811970 at 07/17/2022, 09:30 PM PDT
- BeckettOBrien PR was merged: https://github.com/hackforla/website/pull/3359#event-7008811983 at 07/17/2022, 09:30 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3362#issuecomment-1186789011 at 07/17/2022, 10:40 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3368#issuecomment-1187842497 at 07/18/2022, 10:23 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3368#pullrequestreview-1042333468 at 07/18/2022, 11:52 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3368#issuecomment-1188246633 at 07/18/2022, 01:03 PM PDT
- BeckettOBrien assigned: https://github.com/hackforla/website/issues/2065 at 07/18/2022, 04:44 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/2065#issuecomment-1188444519 at 07/18/2022, 04:45 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3368#issuecomment-1188503939 at 07/18/2022, 06:44 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3368#pullrequestreview-1043874054 at 07/19/2022, 11:02 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3385#issuecomment-1189401206 at 07/19/2022, 11:10 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3385#pullrequestreview-1043914355 at 07/19/2022, 11:33 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3385#pullrequestreview-1043993148 at 07/19/2022, 12:47 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3385#issuecomment-1189552467 at 07/19/2022, 02:09 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3385#issuecomment-1189636255 at 07/19/2022, 04:08 PM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/issues/3396 at 07/19/2022, 08:05 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3394#issuecomment-1190528038 at 07/20/2022, 10:00 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3394#pullrequestreview-1045393503 at 07/20/2022, 10:05 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/issues/2065#issuecomment-1190579335 at 07/20/2022, 10:51 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3394#pullrequestreview-1045506656 at 07/20/2022, 11:29 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3385#pullrequestreview-1045541233 at 07/20/2022, 12:00 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3385#issuecomment-1190808342 at 07/20/2022, 03:05 PM PDT
- BeckettOBrien opened: https://github.com/hackforla/website/pull/3414 at 07/21/2022, 01:23 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3393#issuecomment-1191903884 at 07/21/2022, 01:29 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3385#pullrequestreview-1048366525 at 07/22/2022, 01:26 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3422#issuecomment-1193182393 at 07/23/2022, 01:11 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3422#pullrequestreview-1048575380 at 07/23/2022, 04:06 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3426#issuecomment-1194389201 at 07/25/2022, 10:29 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3426#pullrequestreview-1049967786 at 07/25/2022, 12:38 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3427#issuecomment-1194535671 at 07/25/2022, 12:38 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3426#issuecomment-1194572555 at 07/25/2022, 01:14 PM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3427#pullrequestreview-1050168170 at 07/25/2022, 03:55 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3428#issuecomment-1195812708 at 07/26/2022, 11:05 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3429#issuecomment-1195813861 at 07/26/2022, 11:06 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3429#issuecomment-1195822474 at 07/26/2022, 11:15 AM PDT
- BeckettOBrien submitted review: https://github.com/hackforla/website/pull/3429#pullrequestreview-1051813471 at 07/26/2022, 07:28 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3429#issuecomment-1197453410 at 07/27/2022, 03:45 PM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3414#issuecomment-1197454186 at 07/27/2022, 03:46 PM PDT
- BeckettOBrien issue closed as completed: https://github.com/hackforla/website/issues/3267#event-7083516246 at 07/28/2022, 10:31 AM PDT
- BeckettOBrien commented on: https://github.com/hackforla/website/pull/3414#issuecomment-1198486711 at 07/28/2022, 11:18 AM PDT
- BeckettOBrien PR was closed: https://github.com/hackforla/website/pull/3414#event-7517885874 at 10/04/2022, 08:49 AM PDT
- BeckettOBrien issue closed as completed: https://github.com/hackforla/website/issues/2065#event-9296276538 at 05/21/2023, 09:48 AM PDT
