### ISSUE TITLE
Incorporate Open Graph meta tags into each project page

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#352]
### Overview
we need to  incorporate appropriate open graph tags, because right now, if you send someone a link to a page, it shows hackforla's open graph meta data:
e.g. https://www.hackforla.org/projects/engage.html
![Screen Shot 2020-03-05 at 5 27 08 PM](https://user-images.githubusercontent.com/37763229/76041295-90159f00-5f06-11ea-8b90-ccb42d78b16c.png)

### Action Items

- [ ] Figure out what architecture changes will be needed to accommodate this and propose them in a comment on this issue.
- [ ] Define data collection we will need to perform and share with PM
- [ ] Get approval for changes
- [ ] Outline next steps

### Resources/Instructions
[Facebook's guide to Sharing on social media](https://developers.facebook.com/docs/sharing/webmasters#markup)

**Comment by ExperimentsInHonesty** [comment]
snipit from slack:
cnk  5:25 PM
I feel like it would be nice to have some mention of HackForLA but agree it would be nice to have the project's artwork

Bonnie  5:32 PM
good point, we should figure out what the template language is.  Maybe
[project name] is a Project of Hack for LA. [Description of project]

**Comment by cnk** [comment]
I modified the existing OpenGraph tags in the existing _includes/head.html to use a page's title, description, and image if they exist - otherwise stay with the site's defaults. Pull request #353
