### ISSUE TITLE
Agenda for discussing functionality of issue 2978 - convert markdown to HTML

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/website#3550]
### Prework to prep for meeting
- [x] Filled out this agenda

### Recurring items: 
- [ ] [Status](https://docs.google.com/document/d/1Tx17ewpeI8r7u_-nSazJtUPjKsFeiSYWu-qmJAsbV3I/edit#heading=h.n3l0nsw3ylk)

#### Convert Google Docs to Markdown 
- [ ] Bonnie - make this an official project
- [x] Recruit the "Flag" team
  - "Flag" is a Code for Boston project that is winding down
  - They are looking for a new project
  - Team is very stable and has been working together for a long time
  - Team is all on East Coast
  - Other East Coast folks could join
- [ ] Bonnie - link to Figma and contact for design discussions
- [ ] Bonnie - Someone to review new project?
- [ ] Bonnie - Proposal: creating new repository(s) through 101 Automations  and package on npmjs - [Repositories](https://docs.google.com/document/d/1Tx17ewpeI8r7u_-nSazJtUPjKsFeiSYWu-qmJAsbV3I/edit#heading=h.n3l0nsw3ylk)
- [ ] Bonnie - Proposal for dir structure - [Dir structure of guides](https://docs.google.com/document/d/1Tx17ewpeI8r7u_-nSazJtUPjKsFeiSYWu-qmJAsbV3I/edit#heading=h.j558e0dd17ae)
- [ ] Bonnie - Attributes that require HTML 
      - text styling (color, size, etc)
      - center and right align
- [ ] Bonnie - "-gdoc" suffix to URL

#### Jekyll
- [x] Keep instructions for Docker and Jekyll.  Add instructions for how to do locally?
  - Docker easier for most circumstances
  - I was modifying website content quickly and had some problems with Docker (speed?) so did it locally
  - It was easy for me once I identified the steps, but maybe I was lucky     
- [x] [Agenda template](https://github.com/hackforla/website/issues/3550) for hackforla/website?  
   - [x] Deriving front matter not already provided - front matter in google doc, database.  See below for front matter needed and ways to store.
       - [x] Category - database, front matter in doc, dir or metadata 
       - [x] Overview - database, front matter in doc, section titled "overview" or meta data 
       - [x] Description - database, front matter in doc, section titles "description" or meta data
       - [x] Image 
          - ***** database  ****
          - front matter in doc
          - first image before first h1, ABSOLUTELY NOT
          - image in section titled "Webpage Image"
          - naming convention - <document id>.jpg
### FYIs
-

### Task Items
