### ISSUE TITLE
HfLA: DEV LEAD Meeting Agenda Thursday📝

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#3704]
### Overview
This issue tracks the agenda and notes for the Dev Leads meeting

### Action Items
- [ ] Add the Date of the next meeting below
- [ ] Link the Agenda/Notes from meeting

#### Template
```
## [DATE] Meeting Agenda

### Prework to prep for meeting
- [ ] Review the [QA](https://github.com/hackforla/website/projects/7#column-15490305)
   - [ ] Prework issues: Add notes to this meeting agenda as a discussion or FYI item (if no action needs to be taken).
     - [ ] Check to see how new team members are doing 
       - [ ] Check 2 week inactive label on the in progress column 
          - [ ] [Frontend 2 weeks inactive](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%222+weeks+inactive%22++label%3A%22role%3A+front+end%22)
          - [ ] [Backend 2 weeks inactive](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%222+weeks+inactive%22+++label%3A%22role%3A+back+end%2Fdevops%22)
       - [ ] Check 2 week inactive PRs
       - [ ] Check all open pre-work developers checklists anywhere on the board AND any closed pre-work developers checklist in QA
         - [ ] If it's in New Issue Approval, see if the prework is `ready for milestone` meaning it is assigned to the person who opened the prework, has a role label, and is on the Project Board. 
         - [ ] [Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22feature%3A+onboarding%2Fcontributing.md%22+label%3A%22role%3A+front+end%22#column-15490305)
         - [ ] [Back End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22feature%3A+onboarding%2Fcontributing.md%22++label%3A%22role%3A+back+end%2Fdevops%22#column-15490305)
     - [ ] Can we improve the prework template based on something we see as a pattern?  

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column for 
    - [ ] [Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22#column-15235217)
    - [ ] [Back End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22#column-15235217)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/website/issues/assigned/ExperimentsInHonesty)
       - [ ] [Kathryn](https://github.com/hackforla/website/issues/assigned/kathrynsilvaconway)

### New Items 
add issue numbers to be discussed and any notes that will be helpful


### Notes from meeting

### Tasks

### Items for next week's agenda
```

**Comment by jdingeman** [comment]
## November 10, 2022 Meeting Agenda

### Prework to prep for meeting
- [ ] Review the [QA](https://github.com/hackforla/website/projects/7#column-15490305)
   - [ ] Prework issues: Add notes to this meeting agenda as a discussion or FYI item (if no action needs to be taken).
     - [ ] Check to see how new team members are doing 
       - [ ] Check 2 week inactive label on the in progress column 
          - [ ] [Frontend 2 weeks inactive](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%222+weeks+inactive%22++label%3A%22role%3A+front+end%22)
          - [ ] [Backend 2 weeks inactive](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%222+weeks+inactive%22+++label%3A%22role%3A+back+end%2Fdevops%22)
       - [ ] Check 2 week inactive PRs
       - [ ] Check all open pre-work developers checklists anywhere on the board AND any closed pre-work developers checklist in QA
         - [ ] If it's in New Issue Approval, see if the prework is `ready for milestone` meaning it is assigned to the person who opened the prework, has a role label, and is on the Project Board. 
         - [ ] [Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22feature%3A+onboarding%2Fcontributing.md%22+label%3A%22role%3A+front+end%22#column-15490305)
         - [ ] [Back End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22feature%3A+onboarding%2Fcontributing.md%22++label%3A%22role%3A+back+end%2Fdevops%22#column-15490305)
     - [ ] Can we improve the prework template based on something we see as a pattern?  

### FYIs (nothing needs to be done, just keeping each other informed)

### Recurring items: 
 - [ ] review any issues that are in the new issue approval column for 
    - [ ] [Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22#column-15235217)
    - [ ] [Back End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22#column-15235217)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/website/issues/assigned/ExperimentsInHonesty)
       - [ ] [Kathryn](https://github.com/hackforla/website/issues/assigned/kathrynsilvaconway)

### New Items 
add issue numbers to be discussed and any notes that will be helpful


### Notes from meeting

### Tasks

### Items for next week's agenda

**Comment by JessicaLucindaCheng** [comment]
- Figure out who will be in charge of onboarding and offboarding dev leads: #2689

**Comment by MattPereira** [comment]
Hey @jdingeman is this meeting still happening ? have I been missing it this whole time? lol

**Comment by jdingeman** [comment]
Closed this issue as meetings were not planned as intended. Limited scheduling prevented holding a regular merge team meeting.
