### ISSUE TITLE
Testing "Ready for Milestone" label bug (add label after creation)

### ISSUE THREAD

**Issue by MattPereira** [hackforla/website#3747]
### Overview
- Replicating the creation of #2676 where the github-actions bot removed the `Ready for Milestone` label

### Action Items
- [x] create this issue with same labels as #2676
- [x] add issue to the Project Board
- [x] add the `Ready for Milestone` label
- [ ] watch to see if github-actions bot removes it

### Resources/Instructions
- Trying to solve #3334
