### ISSUE TITLE
Change the status of some projects

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3891]
### Overview
We need to update the website so that any projects that are showing as Active that should have another status get updated.

### Action Items
- [x] Identify all the projects that need to change status
  - [x] Identify the new status
  - [x] Identify project.md file
- [x] Copy the template to the new issue (per project)
- [x] customize template by doing a search and replace for the following items
   - [PROJECT MD FILE]
   - [PROJECT NAME]
   - [PROJECT MD FILE NAME WITHOUT MD]

### Resources/Instructions
Directory where the project.md files can be found: https://github.com/hackforla/website/tree/gh-pages/_projects

#### Projects that need to change status
- [x] 100 Automations #3892 
   - status change: put on hold 
   - md file: 100-automations.md
- [x] Civic Opportunity Project #3893 
   - status change: put on hold 
   - md file: civic-opportunity-project.md
- [x] Civic Tech Structure #3895
   - status change: remove from website 
   - md file: civic-tech-structure.md

#### Title Template
```
Mark [PROJECT NAME] as On Hold
```
#### Body Template

````
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to mark the [PROJECT NAME] project as `On Hold` so that 
- our website accurately reflects the status (Active, Complete, or On Hold) of our projects, 
- and visitors to our website can know the status of our projects.

### Action Items
- [ ] In `_projects/[PROJECT MD FILE]`, change the status for [PROJECT NAME] from
  ```
  status: Active
  ```
  to
  ```
  status: On Hold
  ```
- [ ] Ensure that the `On Hold` status is displayed properly on the [projects page](https://www.hackforla.org/projects/) and [[PROJECT NAME] page](https://www.hackforla.org/projects/[PROJECT MD FILE NAME WITHOUT MD])

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/[PROJECT MD FILE]`
- [hackforla.org, Projects page](https://www.hackforla.org/projects/)
- [hackforla.org, [PROJECT NAME] page](https://www.hackforla.org/projects/[PROJECT MD FILE NAME WITHOUT MD])
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/[PROJECT MD FILE]?plain=1
- This issue is part of an epic: #3891
````

**Comment by ExperimentsInHonesty** [comment]
I have created all the issues and moved them into prioritized backlog
