### ISSUE TITLE
Change "Ready for Milestone" to "Ready for Prioritization"

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4077]
### Overview
We need to change the existing "Ready for Milestone" label to "Ready for Priortization" to make the workflow from the New Issue Approval column to the Prioritized Backlog column more efficient. This will allow product to determine where an issue's priority falls when it has been approved for developers to work on. 

### Action Items
- [x] Currently, the "Ready for Milestone" label acts as signal to product that an issue is ready to be assigned a milestone
  - [x] Since most issues will have their milestones predetermined, it is not as useful as it was meant to be
- [x] Edit the "Ready for Milestone" to be "Ready for Prioritization"
- [x] Find all references across the codebase and the [Wiki](https://github.com/hackforla/website/wiki) to "Ready for Milestone"
  - [x] Change any text and associated links to reference "Ready for Prioritization" instead
- [x] When complete, review this issue with Bonnie/product at a Sunday meeting
 
### Resources/Instructions
- HackforLA [labels](https://github.com/hackforla/website/labels)

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - so I am not sure if you would want to completely change it to "Ready for Prioritization" or just add an entirely new label. I think it's important for us to determine the best way to push an issue back and forth between leads and product when an issue needs to be edited/cleaned up.

**Comment by mademarc** [comment]
i. Availability:3/17/2023 
ii. ETA: 3/18/2023

**Comment by mademarc** [comment]
Progress: just edited the he "Ready for Milestone" label to be "Ready for Prioritization
Blockers: no blockers
Availability: 3/16/2023
ETA: 7:25pm

**Comment by jdingeman** [comment]
Checked wikis and confirmed work was complete. Signing off this issue.
