### ISSUE TITLE
ER: Build a tool to verify activities of HfLA members

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4186]
**Note:** This issue came from the [Task List Dev Leads](https://docs.google.com/spreadsheets/d/1qEiDFUKPCVH3JNzGQSKl_HMl9vqNv8Z9gGrvw9MyYvU/edit#gid=0).

### Emergent Requirement - Problem
**Issue Description**
Write an issue to build a tool to be used for verification of activity of the HfLA members (might use GHA to build the tool). This tool would search all HackforLA projects for user activity and it can be used for verification requests for a HfLA member from potential employers.

### Who was involved
**GitHub Handle(s):**
- ExperimentsInHonesty
- JessicaLucindaCheng
- SAUMILDHANKAR   

### What happens if this is not addressed
Nothing changes and we continue manually checking each person for background checks and verification requests.

### Action Items
- [x] Check with the Stakeholder Rep (Bonnie) if this is something we still want to do within the Website Team repo
- [x] Discuss with team
- [x] In the 100 Automations repo,
  - [ ] Search and check
    - [ ] If an open issue exists that addresses this ER
    - [ ] If a closed issue exists that has already addressed this ER
  - [x] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng This should get moved to another repo.  We have one for org wide automations (.github) but I think that is meant to be used for automations that are used on repos.  So then the question is where do we put automations that are not for project but instead for the organization.  Perhaps a repo called admin-automations?  Let me know if this sounds good.

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
> @JessicaLucindaCheng This should get moved to another repo. We have one for org wide automations (.github) but I think that is meant to be used for automations that are used on repos. So then the question is where do we put automations that are not for project but instead for the organization. Perhaps a repo called admin-automations? Let me know if this sounds good.

I think it is a good idea for the automation to be in a separate repo, though not sure what we call it yet. However, for moving the issue itself, I was thinking either
A) The issue would be part of the repo where the automation will be made. Then, in terms of project management, there can be a project board (using the new GitHub projects) because the new projects can have issues from multiple repos.
B) [100 Automations board](https://github.com/100Automations/futureautomations/projects/1) might be a good place for the issue since it is an automation issue but I know the 100 Automations project is on hold. 

Let me know what you think. I'll put this on our Dev/PM agenda so we can discuss it.

Edit:
Answer from Bonnie
- Yes, put it in the issue in 100 Automations repo/project board using the Google Form on the board.

**Comment by JessicaLucindaCheng** [comment]
- Progress: On April 2, 2023, I submitted Automation Proposal using the form on this card: https://github.com/100Automations/futureautomations/projects/1#card-52500418
- Blocker: I don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it.
- Availability: 15 minutes to check on blocker
- ETA: Dependent on blocker.

**Comment by JessicaLucindaCheng** [comment]
- Progress: On April 2, 2023, I submitted Automation Proposal using the form on this card: https://github.com/100Automations/futureautomations/projects/1#card-52500418
- Blocker: I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
- Availability: 15 minutes to check on blocker
- ETA: Dependent on blocker.

**Comment by JessicaLucindaCheng** [comment]
# To Dos
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488
- **Blockers:** None
- **Availability:** Not sure
- **ETA:** Not sure because there are some other issues take priority

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form on this card: https://github.com/100Automations/futureautomations/projects/1#card-52500418
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488
- **Blockers:** None
- **Availability:** Not sure
- **ETA:** Not sure because there are some other issues take priority

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form on this card: https://github.com/100Automations/futureautomations/projects/1#card-52500418
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488
- **Blockers:** Water damaged laptop
- **Availability:** TBD - need to find a solution to my laptop problems
- **ETA:**  TBD - need to find a solution to my laptop problems

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form on this card: https://github.com/100Automations/futureautomations/projects/1#card-52500418
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488
- **Blockers:** Water damaged laptop but it works now
- **Availability:** TBD - I need this week to catch up and prioritize what needs to be done.
- **ETA:** TBD - I need this week to catch up and prioritize what needs to be done.

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form on this card: https://github.com/100Automations/futureautomations/projects/1#card-52500418
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488
- **Blockers:** None
- **Availability:** TBD
- **ETA:** TBD

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form on this card: https://github.com/100Automations/futureautomations/projects/1#card-52500418
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488
- **Blockers:** None
- **Availability:** TBD
- **ETA:** TBD

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form on this card: https://github.com/100Automations/futureautomations/projects/1#card-52500418
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488
- **Blockers:** None
- **Availability:** TBD
- **ETA:** TBD

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form from https://github.com/100Automations/futureautomations/issues/new/choose
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [x] Re-activate the repo by making a commit to the repo to wake it up.
  - [x] Created this pr: https://github.com/100Automations/futureautomations/pull/53
    - [x] It needs to be merged.
 - [x] Resubmit the form to see if it is working now
   - Copy of Overview text
      ``` 
      - Repetitive Thing: Verifying the activities of HfLA members requires Bonnie or leads to manually search for each member's activities in Github. Sometimes this would require searching multiple Hack for LA projects for user activity. Activities include assigned issues, pull requests reviewed, issues authored, leaving comments on issues, etc. 
      - Benefit of Automating It: It can show all the activity for a member can be used for verification requests for a HfLA member from potential employers.
      ``` 
   - Copy of Stakeholders and Impact text
      ```
      The main stakeholder is Hack for LA's Executive Director Bonnie Wolf. Additional stakeholders are Hack for LA's leads and product/project managers. The impact is that it reduces the time required to verify a member's activities since they are in one place.
      ```
- [ ] Ask if there is a secret token in the script that is expired
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488. Still trying to figure out why the form isn't working.
- **Blockers:** Is there an expired GitHub token in the script? 
  - If not, I can write the issue for an Automation Proposal in the futureautomations repo without using the form. Then I can write another issue in that repo saying the Automation Proposal Google Form is not working and needs to be fixed. Is that okay?
- **Availability:** TBD based on blocker being answered
- **ETA:** TBD based on blocker being answered

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form from https://github.com/100Automations/futureautomations/issues/new/choose
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [x] Re-activate the repo by making a commit to the repo to wake it up.
  - [x] Created this pr: https://github.com/100Automations/futureautomations/pull/53
    - [x] It needs to be merged.
 - [x] Resubmit the form to see if it is working now
   - Copy of Overview text
      ``` 
      - Repetitive Thing: Verifying the activities of HfLA members requires Bonnie or leads to manually search for each member's activities in Github. Sometimes this would require searching multiple Hack for LA projects for user activity. Activities include assigned issues, pull requests reviewed, issues authored, leaving comments on issues, etc. 
      - Benefit of Automating It: It can show all the activity for a member can be used for verification requests for a HfLA member from potential employers.
      ``` 
   - Copy of Stakeholders and Impact text
      ```
      The main stakeholder is Hack for LA's Executive Director Bonnie Wolf. Additional stakeholders are Hack for LA's leads and product/project managers. The impact is that it reduces the time required to verify a member's activities since they are in one place.
      ```
- [ ] Ask if there is a secret token in the script that is expired
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488. Still trying to figure out why the form isn't working. I have access to the 100Automations org
   - Is there an expired GitHub token in the script?
     - If not, I can write the issue for an Automation Proposal in the futureautomations repo without using the form. Then I can write another issue in that repo saying the Automation Proposal Google Form is not working and needs to be fixed. Is that okay?
- **Blockers:** Is there an expired GitHub token in the script? 
  - [x] I need access to the Google Drive with this form and its response spreadsheet on it
    - Form: https://docs.google.com/forms/d/e/1FAIpQLSemmRJ1tBDVrGtPpwpxLVCQbw2O-tVVRpcbRW3SzRdNbZ9olg/viewform
    - It is an issue template here: https://github.com/100Automations/futureautomations/issues/new/choose 
  - [x] Also, I need to access this account https://github.com/100AutomationsProject, which generates the issue after the form is submitted.
- **Availability:** TBD based on blocker being answered
- **ETA:** TBD based on blocker being answered

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form from https://github.com/100Automations/futureautomations/issues/new/choose
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [x] Re-activate the repo by making a commit to the repo to wake it up.
  - [x] Created this pr: https://github.com/100Automations/futureautomations/pull/53
    - [x] It needs to be merged.
 - [x] Resubmit the form to see if it is working now
   - Copy of Overview text
      ``` 
      - Repetitive Thing: Verifying the activities of HfLA members requires Bonnie or leads to manually search for each member's activities in Github. Sometimes this would require searching multiple Hack for LA projects for user activity. Activities include assigned issues, pull requests reviewed, issues authored, leaving comments on issues, etc. 
      - Benefit of Automating It: It can show all the activity for a member can be used for verification requests for a HfLA member from potential employers.
      ``` 
   - Copy of Stakeholders and Impact text
      ```
      The main stakeholder is Hack for LA's Executive Director Bonnie Wolf. Additional stakeholders are Hack for LA's leads and product/project managers. The impact is that it reduces the time required to verify a member's activities since they are in one place.
      ```
- [ ] Ask if there is a secret token in the script that is expired
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng I upgraded your access to the GitHub org for 100 Automations

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Found this closed issue, which might be helpful: https://github.com/100Automations/Website/issues/488. Still trying to figure out why the form isn't working. I have access to the 100Automations org
   - Is there an expired GitHub token in the script?
     - If not, I can write the issue for an Automation Proposal in the futureautomations repo without using the form. Then I can write another issue in that repo saying the Automation Proposal Google Form is not working and needs to be fixed. Is that okay?
- **Blockers:** Is there an expired GitHub token in the script? 
  - [x] I need access to the Google Drive with this form and its response spreadsheet on it
    - Form: https://docs.google.com/forms/d/e/1FAIpQLSemmRJ1tBDVrGtPpwpxLVCQbw2O-tVVRpcbRW3SzRdNbZ9olg/viewform
    - It is an issue template here: https://github.com/100Automations/futureautomations/issues/new/choose 
  - [x] Also, I need to access this account https://github.com/100AutomationsProject, which generates the issue after the form is submitted.
- **Availability:** TBD based on blocker being answered
- **ETA:** TBD based on blocker being answered

# Tasks
- [x] On April 2, 2023, I submitted Automation Proposal using the form from https://github.com/100Automations/futureautomations/issues/new/choose
- [x] I checked again on April 9. 2023, and I still don't see a card on the [board](https://github.com/100Automations/futureautomations/projects/1) yet. I'm just waiting for the card to show up so I can add a link to it in this ER before I close it. I will add this to the Dev/PM agenda to ask Bonnie.
  - Bonnie said I should try to figure out what is going on 
- [x] Re-activate the repo by making a commit to the repo to wake it up.
  - [x] Created this pr: https://github.com/100Automations/futureautomations/pull/53
    - [x] It needs to be merged.
 - [x] Resubmit the form to see if it is working now
   - Copy of Overview text
      ``` 
      - Repetitive Thing: Verifying the activities of HfLA members requires Bonnie or leads to manually search for each member's activities in Github. Sometimes this would require searching multiple Hack for LA projects for user activity. Activities include assigned issues, pull requests reviewed, issues authored, leaving comments on issues, etc. 
      - Benefit of Automating It: It can show all the activity for a member can be used for verification requests for a HfLA member from potential employers.
      ``` 
   - Copy of Stakeholders and Impact text
      ```
      The main stakeholder is Hack for LA's Executive Director Bonnie Wolf. Additional stakeholders are Hack for LA's leads and product/project managers. The impact is that it reduces the time required to verify a member's activities since they are in one place.
      ```
- [ ] Ask if there is a secret token in the script that is expired
- [ ] See if I can figure it out from the closed https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+%22form%22 or from the wiki in the above repo or the future automations wiki
  - [ ] See if this issue is helpful: https://github.com/100Automations/Website/issues/488
    - [ ] Specifically, check this comment: https://github.com/100Automations/Website/issues/488#issuecomment-966779548
  - [ ] See if the form uses a token. If it uses a token, ask Bonnie to check if it is expired and to renew the token.
- [ ] If I can't figure out how the automation works, reach out to Olivia Chiong
