### ISSUE TITLE
Epic: Fix size of SDG icons to match Figma design

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4229]
### Dependency
- [x] #4254
- [x] #4255
- [x] #4256
- [x] #4225
- [x] #4257
- [x] #4253 
- [x] #4258 

### Overview
We want to check the sections that use the Sustainable Development Goal (SDG) icons on the website look good in mobile, tablet, and desktop views so that we maintain a professional website.

### Details
- SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).
- Following the [UN guidelines for SDG usage](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf), we had to replace the SDG svgs in our repo because the colors in our svgs were not correct.
- However, with replacing those svgs, the new svgs are a different size. Thus, there could be some size issues with the new svgs on the pages that use them.

### Action Items
- [ ] Using the [Figma design: All pages overview](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464-0&t=W18ZNL5chEZvnogs-0) as a reference, check the following pages in mobile, tablet, and desktop views to see if the SDG icons look good and the size of the icons matches the Figma design in those views
  - [ ] [About page Sustainability section](https://www.hackforla.org/about/#sustainability)
  - [ ] [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
  - [ ] Project detailed pages: [311 Data](https://www.hackforla.org/projects/311-data) and [Lucky Parking](https://www.hackforla.org/projects/lucky-parking)
- [ ] If needed, make issues to fix the problems on each page. To understand about the SDG files in our repo, you can read epic #4153

### Resources/Instructions
- [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals)
- [UN guidelines for SDG usage](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf)
- [Figma design: All pages overview](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464-0&t=W18ZNL5chEZvnogs-0)
- [About page Sustainability section](https://www.hackforla.org/about/#sustainability)
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- Project detailed pages: [311 Data](https://www.hackforla.org/projects/311-data) and [Lucky Parking](https://www.hackforla.org/projects/lucky-parking)
- This issue is tracked in epic #4153

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng The dependencies have all been addressed.  

I gave a quick review and the icons and their backgrounds on the 311-data and lucky parking don't look right.  So I reviewed the instructions and I don't think we have written up enough info about how to fix.  

Meaning I know there are specific files (css with the colors, SDG images, etc).  But there is no information in this issue about where those files are. 

I am concerned the person working on this issue will start making new files, if they don't know where the existing files are.  

Has you made any wiki content for this?

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 

> @JessicaLucindaCheng The dependencies have all been addressed.
> 
> I gave a quick review and the icons and their backgrounds on the 311-data and lucky parking don't look right. So I reviewed the instructions and I don't think we have written up enough info about how to fix.

- Issue #4187 fixes the background color problem for the 311 Data and Lucky Parking problem. 
- This issue (#4229) is only to address the size of the icons on the pages listed: About page, Citizen Engagement, 311 Data and Lucky Parking.

> Meaning I know there are specific files (css with the colors, SDG images, etc). But there is no information in this issue about where those files are.
>
> I am concerned the person working on this issue will start making new files, if they don't know where the existing files are.

- This issue is meant for a dev lead to write Issue Making: Level 2 issues from it, not a developer to implement it. Thus, I didn't provide too much info. However, I should have put a link to the SDG epic so that the dev lead could have more information, which I have gone ahead and done. I can also add a link to the wiki content once it is written.

> Has you made any wiki content for this?

- No, but I wrote issue #4676. Once you prioritize the issue, I can self-assign and write the wiki page.

**Comment by ExperimentsInHonesty** [comment]
I have looked at the lucky-parking page and the about page sustainability section and I see we are using a color name for the background of the lucky parking page
background-color-sdg11
![image](https://github.com/hackforla/website/assets/37763229/a6ee3bee-f401-4e5f-9e67-9b7fb6dd7b96)

![image](https://github.com/hackforla/website/assets/37763229/b1de7b5d-93da-4174-8d9d-441a87fed7cb)

And we probably should have used a more generic name, such as color-sdg11 instead of including the word background, because we are going to have to use something for this part of the about page, that uses the same colors, and it doesn't seem to make sense to have two references to the color in the class files
![image](https://github.com/hackforla/website/assets/37763229/3892b94a-df00-40b3-bf48-f7987712bf94)
![image](https://github.com/hackforla/website/assets/37763229/9fb15c7b-f783-4b6e-bf2a-edc806b18bb3)

**Comment by JessicaLucindaCheng** [comment]
@JessicaLucindaCheng 
### Action Items
- [ ] Write SDG wiki page, specifically for file locations, including css with the colors, SDG images, etc.
- [ ] Add link to this issue
- [ ] Make ready for prioritization

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng it looks like there is a resizing issue for mobile too, here is a screenshot.  I took this from my desktop, but it looks pretty much the same on my mobile phone 
https://www.hackforla.org/citizen-engagement

<details><summary>Details</summary>
<p>

![image](https://github.com/hackforla/website/assets/37763229/c4c4c758-bd9c-46d6-917d-99e0296f8edd)

</p>
</details>

**Comment by JessicaLucindaCheng** [comment]
I will review this epic by Wednesday, June 12, 2024.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng I had a chance to look at this issue and the pages It's related to.  It seems like It's supposed to be covering the fact that the icons are smaller on the Figma and larger on the website page (see below), but the problem with changing it on the citizen engagement page, is that it would also have to be smaller on the project page which is not going to look good (and also might affect accessibility).  So we propose closing this issue as unplanned.

### Figma
[figma: citizen engagement](https://www.figma.com/design/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17601-123536&t=z8eB1YcqpTS5xfkq-0)
<details><summary>Figma screenshot</summary>

<img src="https://github.com/hackforla/website/assets/37763229/5f5e6752-f513-46ad-b0ec-da31803d84c6" width=200px>

</details> 

### Citizen Engagement Page
https://www.hackforla.org/citizen-engagement
<details><summary>live citizen engagement page</summary>
<p>

<img src="https://github.com/hackforla/website/assets/37763229/5192c3f4-5b40-467c-845b-1d2ae788c48a" width=200px>


</p>
</details>

**Comment by ExperimentsInHonesty** [comment]
no need to change the sizes
