### ISSUE TITLE
Create a Roll Out Plan for adding Code Spell Checker VS Code Extension

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4349]
### Dependency
- [x] https://github.com/hackforla/website/issues/4469
- [x] https://github.com/hackforla/website/issues/4470
- [x] https://github.com/hackforla/website/issues/4471
- [ ] #5248
- [ ] #5312
- [x] #5313
- [x] #5450
- [x] #5652
- [ ] #6446

### Overview
We need to create a roll out plan for having all HfLA website developers install the Code Spell Checker VS Code extension so that we can reduce confusion for our dev team when using in their local development environment, during PRs, and while reviewing PRs.

### Action Items
- [x] Draft a Plan Overview
- [ ] Decide if feature branches are necessary
- [ ] Review with Merge Team
- [ ] Create issues for each of the items that need it
  - [ ] Add them to the Dependencies section of this issue
- [ ] Once all components (dependency issues) of the plan are drafted (not yet completed)
  - [ ] Identify what can be done now, and what has to wait until a specific trigger
  - [ ] TBD...
  
### Resources/Instructions
- https://github.com/hackforla/website/issues/4101
- [Decision Records](https://github.com/hackforla/website/wiki/Decision-Records)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - I know the Wiki is on a pause right now but my thought was that the Wiki would likely be migrated to Mkdocs before this gets implemented, but please let me know if we should go with an alternative, like Google Docs.

**Comment by ExperimentsInHonesty** [comment]
# Plan Overview

## Instructions
### Requirements
- Clear wording
- Links to relevant files
- Screenshots when required

### What to cover
- How to install locally
- How to increase the scope of your issue if the local linter finds problems (what to note in the issue and pr)
- What do we expect will happen when you do a PR and what to do about it
  - if you **don't** catch all the problems, the linter will find locally
  - if you **do** catch all the problems, the linter will find locally
  - if the repo linter finds other problems the local linter did not (we hope it won't but...)
- PR reviewers: How to handle scope changes, caused by the local linter, in the PR you are reviewing

### Where to message
#### Contributing.md
#### Wiki
- DR
- Other?

#### Prework template 
- for new preworks

#### Slack
- Which channels
#### GHAs
- GHA messages on PRs
- GHA messages on existing issues
   - size of issue:
      - prework
      - ?
#### In Meetings
- HfLA onboarding
- Dev meetings (Tues, Thurs, Sun)

## Actions & Timelines
You don't have to answer `When?` until all the messages are ready

### Publish Instructions
#### Where
- Contributing file https://github.com/hackforla/website/issues/4101
- GHAs
- Slides
#### When?

### Direct Developers to install the VS Code plugin during dev environment setup
#### Who: 
- Existing developers
- New developers
#### When?

### Install Linter on GitHub repo
#### When?

**Comment by ExperimentsInHonesty** [comment]
# Draft ISSUE

Title: Spell Linter: GHA Messaging

### Overview
Review the GHAs, identify what messaging will support the rollout plan, and draft messages.

### Action Items
- [ ] Familiarize yourself with our existing GitHub Actions
  - [ ]  Identify if any of them should be temporarily edited to include messages to developers about the new implementation
     - [ ] Add list to a comment, with general instructions on what might be included per GHA
     - [ ] Add any additional GHAs you think we could write that would post something on an issue or PR that would be helpful.
- [ ] Present your documentation (a comment with the details of where and what) to the Product and Dev Lead team and refine plan as needed 
- [ ] Create issues to make the changes (one per GHA).
   - [ ] Add this issue as a Dependency to the new issues 

#### Potential Scenarios
- [ ] A GitHub Action that leaves a comment when developers assign themselves to issues
   - [ ] The message serves as a reminder that we are implementing a new VS Code extension
  - [ ] The message should include a checkbox for the dev to acknowledge that they've read and understand the instructions and changes to the contributing.md
- [ ] A GitHub Action that leaves a comment on new prework issues
   - [ ] The message serves as a reminder for the new dev that we are implementing a new VS Code extension
   - [ ] The message should include a checkbox for the dev to acknowledge that they've read and understand the instructions and changes to the contributing.md
  - [ ] A GitHub Action that leaves a comment on newly created pull requests
    - [ ] This message will notify pull request reviewers that any changes in a developer's pull request (specifically spelling corrections) will be considered within the scope of their issue, since they can make the changes in a file containing spelling errors
    - e.g. 
      > We added a spelling linter on X date,
      > If the PR contains spelling changes, those are included in the scope of this issue.
      > if the PR has not passed the linter because spelling changes are suggested, please see the contributing X section for installing the VS code plugin.

#### For PM, Tech Lead, Merge Team
- [ ] When the GHA Messaging plan is accepted, review the changes and determine how they will be implemented (feature branch, etc.)
- [ ] release dependency on #4349 and move that issue into the New Issue Approval column with the `ready for dev lead` or `ready for product` label for review and a note about where to find the finished plan.

### Resources
- WIKI page with GHAs

**Comment by ExperimentsInHonesty** [comment]
# Draft ISSUE

Title: Spell Linter: Meeting Messaging

### Overview
Review the slides or instructions used during meetings, if any, and create additions or new materials to share the messaging that will support the rollout plan.

### Action Items
  - [ ] [@jdingeman ADD SOME STEPS HERE]

### Resources
- [ADD LEAD RESOURCES??]
- [HfLA website onboarding slide](https://docs.google.com/presentation/d/1aaAS4azzP84T_C8LK9Rp4juDn6T1SifspVBmpupYnZA/)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) as a local linter

**Comment by ExperimentsInHonesty** [comment]
# Draft ISSUE

Title: DR: Spelling Linter

### Overview
We need to create a Decision Record so that we have the history of why & how we are using this spelling linter so that people in the future can understand it.

### Action Items
- [ ] Create a DR Solutions Adopted wiki page 
   - [ ] why we are using a linter
   - [ ] why this one (what were the requirements)
   - [ ] links
   - [ ] link to plan Issue #4349
   - [ ] etc.
- [ ] Add the wiki page to the `Decision Records on Solutions Adopted`

### Resources
[Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) as a local linter

**Comment by ExperimentsInHonesty** [comment]
# Draft ISSUE

Title: Spell Linter: Slack Messaging

### Overview
Write the messaging that will go out in Slack channels and when (related to other messages) it should go out, so that we can make sure to catch people at every location they might need to receive these messages

### Action Items
- [ ] Review the most recent Slack Audit Document
- [ ] Identify which channels we should message in
- [ ] Identify which methods you recommend employing
  - [ ] Pins
  - [ ] Bookmarks
  - [ ] Reminders
- [ ] Write up messaging in a comment (include which channel)

### Resources
- [HfLA website: Slack Audit](https://docs.google.com/document/d/11WAkHQByfXkQ3rno3kS0HxM1MWwjJZ2zBLj_YwtQ5qk/edit)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) as a local linter

#### HfLA website: Slack Channels
#hfla-site
#hfla-site-onboarding
#hfla-site-ux
#hfla-site-pr
#website-merge

**Comment by ExperimentsInHonesty** [comment]
# JD's original draft

### Overview
We need to create a roll out plan for having all HfLA website developers install the Code Spell Checker VS Code extension so that we can reduce confusion for our dev team when using in their local development environment, during PRs, and while reviewing PRs.

### Action Items
- [ ] Develop a plan of action for the implementation of [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) as a local linter
- [ ] Familiarize yourself with our existing GitHub Actions and if any of them can be temporarily edited to include messages to developers about the new implementation
- [ ] The plan should include the following:
  - [ ] How we will make sure all new and active developers know to install the extension
  - [ ] A GitHub Action that leaves a comment when developers assign themselves to issues
    - [ ] The message serves as a reminder that we are implementing a new VS Code extension
    - [ ] The message should include a checkbox for the dev to acknowledge that they've read and understand the instructions and changes to the contributing.md
  - [ ] A GitHub Action that leaves a comment on new prework issues
    - [ ] The message serves as a reminder for the new dev that we are implementing a new VS Code extension
    - [ ] The message should include a checkbox for the dev to acknowledge that they've read and understand the instructions and changes to the contributing.md
  - [ ] A GitHub Action that leaves a comment on newly created pull requests
    - [ ] This message will notify pull request reviewers that any changes in a developer's pull request (specifically spelling corrections) will be considered within the scope of their issue since they can make the changes in a file containing spelling errors
    - e.g. 
      > We added a spelling linter on X date,
      > If the PR contains spelling changes, those are included in the scope of this issue.
      > if the PR has not passed the linter because spelling changes are suggested, please see the contributing X section for installing the VS code plugin.
  - [ ] Updating the [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) with issue https://github.com/hackforla/website/issues/4101
  - [ ] Notifications during meetings, onboarding, etc.
  - [ ] You will want the plan to cover all corners and cases so that no one misses out on this new implementation
- [ ] Create a Wiki in [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted) with this details plan
  - [ ] Be sure to include proposed wording of Slack messages, wording of GHA messages, timelines for each step, potential issues to create, etc. 
  - [ ] Add a link to this new article to the main [Decision Records](https://github.com/hackforla/website/wiki/Decision-Records) page
- [ ] Present your documentation to the Product and Dev Lead team and refine plan as needed 

#### For PM, Tech Lead, Merge Team
- [ ] When the roll out plan is accepted, release dependency on https://github.com/hackforla/website/issues/4101 and move that issue into the New Issue Approval column with the `ready for dev lead` or `ready for product` label for review

### Resources/Instructions
- https://github.com/hackforla/website/issues/4101
- [Decision Records](https://github.com/hackforla/website/wiki/Decision-Records)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by ExperimentsInHonesty** [comment]
@jdingeman I have revised the top part of this issue.  I am going to bring it to the Dev Lead/PM meeting today so that we can discuss the plan with the merge team.

**Comment by ExperimentsInHonesty** [comment]
@jdingeman We discussed and made some changes.  So I have put a `role: dev leads` label on this and put it back into new issue approval, so you can add any notes from the Monday meeting to it.  Then, maybe it goes into the prioritized backlog without you being assigned to it, and we look at the rest of your [assigned issues](https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+assignee%3Ajdingeman+-label%3A%22feature%3A+agenda%22) and do a little overall reprioritizing

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I need a bit of help coming up to speed on this issue.  In particular I'm wondering if the deployment of a repo-level spell check will be part of the Roll Out Plan.  You mention a repo-level check in https://github.com/hackforla/website/issues/4349#issuecomment-1494630931 but I don't see any other mention of it.

**Comment by roslynwythe** [comment]
## Draft Roll Out Plan

### Action Items
Phase 1
- [ ] #5313 
- [ ] #5450
- [ ]  #5248
- [ ] #4101 
- [ ] #5652
- [ ] #6519
- [ ] #6446

Phase 2 (when Phase 1 is complete)
- [ ] #5312
- [ ] Epic: Create issues to correct misspelled words
- [ ] Issue to create new wiki page "How to manage spell check warnings"


Phase 3 (when Phase 2 is complete)
- [ ] #5202
- [ ] Add instructions to prework checklist issue template (part of #4469)
- [ ] GHA to post comment to open prework checklists (part of #4469)
- [ ] Update “Preliminary Comment” after issue assignment (part of #4469)
- [ ] Present your documentation to the Product and Dev Lead team and refine plan as needed 

#### For PM, Tech Lead, Merge Team
- [ ] When the roll out plan is accepted, release dependency on https://github.com/hackforla/website/issues/4101 and move that issue into the New Issue Approval column with the `ready for dev lead` or `ready for product` label for review

### Resources/Instructions
- https://github.com/hackforla/website/issues/4101
- [Decision Records](https://github.com/hackforla/website/wiki/Decision-Records)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
