### ISSUE TITLE
Rollout Plan: Refactor code with img HTML tags to end without a slash

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4362]
### Dependency
- [ ] #4922
- [ ] #5040
- [x] #6453

### Overview
We want to change img HTML tags ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Details
- See the write-up for the `DR: img tag` documentation comment [^1]
- Read the roll out plan [^2]
- See the already started but not completed spreadsheet: HfLA-Website: img Tag Audit spreadsheet [^3]
- To understand the Issue Making labels, see 4  in the Resources/Instructions section below [^4]

### Action Items
- [x] Write epic 1 as outlined in the roll out plan
  - [x] Add a link to the epic in the Dependency section above 
- [x] Write epic 2 as outlined in the roll out plan
  - [x] Add a link to the epic in the Dependency section above 
- [ ] Once all the issues are closed in the Dependency section, delete the following issue template(s):
  - [ ] .github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md [^5]

### Resources/Instructions
[^1]: [`DR: img tag` documentation comment](https://github.com/hackforla/website/issues/4363#issuecomment-1493176038)

[^2]: [Roll out plan](https://github.com/hackforla/website/issues/4362#issuecomment-1537580632)

[^3]: [HfLA-Website: img Tag Audit spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1822415835)

[^4]: To understand the Issue Making labels, refer to the Resources section of this ER: #4678

[^5]: Issue Template 1: [img Tag Refactor on Website](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&template=img-tag-refactor-on-website.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page%28s%29) and its associated Markdown file [.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md). This template works for any pages that are marked with `Template 1` in the `Template to use if <img.../> found` column on the `Page Audit` tab. Template 1 works if the img tag is on the website.

**Comment by JessicaLucindaCheng** [comment]
Awaiting approval before writing more issues: https://github.com/hackforla/website/issues/4366#issuecomment-1493273041

**Comment by JessicaLucindaCheng** [comment]
### Notes for dev lead picking up this epic
#### Progress
I audited some of the pages and wrote some of the issues. 
#### To Dos
- [ ] The rest of the pages in the `Page Audit` tab needs to be audited
- [ ] Once the pages are all audited, then the issues need to be written that are indicated in the `img with Ending Slash` tab depends on
  - [ ] If the image tag is for something on the website (so the `Link to page on website (if applicable)` column is filled out), follow the `Instructions for issue writers if "Link to page on website (if applicable)" column is filled out` on the Instructions tab
  - [ ] If the image is for something not on the website (so the `Link to page on website (if applicable)` column is **not** filled out), determine how to write the issues for those. 
    - For example, `CONTRIBUTING.md` and `.github/pull_request_template.md` are **not** files for the website and will **not** have `Link to page on website (if applicable)` column filled out. Thus, if they have img tags with an ending slash `<img.../>`, then you'll need to figure out how to write the issues for those.

**Comment by JessicaLucindaCheng** [comment]
- Notes to be added to a new wiki page about the issue making ladder. (Note: #4678 was made for adding this info.)

### Issue making ladder
- Issue Making: Level 1 - Make issues from a template and a spreadsheet
- Issue Making: Level 2 - Make an issue template and level 1 issue to use it
- Issue Making: Level 3 - Epic
- Issue Making: Level 4 - Make a Roll Out Plan that has >1 epics to achieve and timelines for interdependencies

**Comment by JessicaLucindaCheng** [comment]
# Original content of issue before changing it to a roll out plan

### Overview
We want to change img HTML tags ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Details
See the write-up for `DR: img tag` documentation comment {See 1 in Resources/Instructions below}

### Action Items
#### Audit
- [ ] Search for and find all the instances in our codebase with img HTML tags ending with a slash (<img.../>) and document them in the HfLA-Website: img Tag Audit spreadsheet. For detailed instructions follow the "Instructions for auditors" in the Instructions tab of the HfLA-Website: img Tag Audit spreadsheet. (See 2 in Resources/Instructions below.)

#### Write issues
##### Instructions for issue writers if "Link to page on website (if applicable)" column is filled out
- [ ] Write good first issues to change each instance of the img HTML tags ending with a slash (<img.../>) to an img tag without an ending slash (<img...>). For detailed instructions follow the "Instructions for issue writers if "Link to page on website (if applicable)" column is filled out" in the Instructions tab of the HfLA-Website: img Tag Audit spreadsheet. (See 2 in Resources/Instructions below.)

##### Instructions for issue writers if "Link to page on website (if applicable)" column is **not** filled out
- [ ] [DEV LEAD: Add Action Items here based on the audit]

#### Dev Lead
- [ ] Once all the issues are made, delete the following issue templates:
  - [ ] img Tag Refactor
  - [ ] [DEV LEAD: Add any other templates you created for this epic that can be deleted once all the issues for this epic are written]

### Resources/Instructions
1. [`DR: img tag` documentation comment](https://github.com/hackforla/website/issues/4363#issuecomment-1493176038)
2.  [HfLA-Website: img Tag Audit spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1822415835)
#### For issues where "Link to page on website (if applicable)" column is filled out
4. [img Tag Refactor issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&template=img-tag-refactor.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page)
5. Example issue: https://github.com/hackforla/website/issues/4445

**Comment by JessicaLucindaCheng** [comment]
### Notes for dev lead picking up this epic (OUTDATED)
#### Progress
I audited some of the pages and wrote some of the issues. 

##### Audit
- [ ] Epic of Epics: Make a template with `Complexity: Small` issue to audit each page
- [ ] Then, hand this off to someone else to use the template to make issue to audit each page

##### Write issues
- [ ] Once the pages are all audited, then the issues need to be written that are indicated in the `img with Ending Slash` tab depends on
  - [ ] If the image tag is for something on the website (so the `Link to page on website (if applicable)` column is filled out), follow the `Instructions for issue writers where "Link to page on website (if applicable)" column is filled out` on the Instructions tab
  - [ ] If the image is for something not on the website (so the `Link to page on website (if applicable)` column is **not** filled out), determine how to write the issues for those. 
    - For example, `CONTRIBUTING.md` and `.github/pull_request_template.md` are **not** files for the website and will **not** have `Link to page on website (if applicable)` column filled out. Thus, if they have img tags with an ending slash `<img.../>`, then you'll need to figure out how to write the issues for those.

**Comment by JessicaLucindaCheng** [comment]
### Notes for dev lead picking up this epic
- Progress: I audited some of the pages and wrote some of the good first issues to change `<img.../>` to `<img...>`. 
- I started the [HfLA-Website: img Tag Audit spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1822415835) with an Instructions tab.
  - Feel free to edit, delete, or add whatever you want anything in the Google Sheet. It's all yours now.
  - The instructions in the Instructions tab may not be necessary since epics and issues will be written with instructions in them.
- I created a [img Tag Refactor issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&template=img-tag-refactor.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page%28s%29) feel free to edit or modify it.

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
- I edited the roll out plan. Could you take a look to see if there is anything I should change?
- Also, I wasn't sure about how to label this roll out plan. Please check the labels.

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm 
- I edited the roll out plan. Could someone take a look to see if there is anything I should change? It's my first time writing a roll out plan.
- Also, I wasn't sure about how to label this roll out plan. Please check the labels.
- I wasn't sure what to do with this spreadsheet: [HfLA-Website: img Tag Audit spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1822415835). Should I 
  - completely remove the instructions since those will be in the other epics and issues that will be written as a result of this roll out plan
  - Or should I let the dev lead(s) that are assigned to this roll out plan decide what to do with it?
- Also, I made this [diagram of the roll out plan in terms of issue writing levels](https://user-images.githubusercontent.com/31293603/233816957-1e0c80a8-bd71-496c-8675-84efcedb804e.png). The editable version is currently saved in my personal FigJam file. Let me know if you want me to copy the editable version somewhere else so it is available for future editing.

**Comment by JessicaLucindaCheng** [comment]
To Dos
- [x] Redo the diagram
  - [x] Remove Action Items in the first epic square
  - [x] Make duplicate issues stacked like pieces of paper offset a little 
  - [x] Break down the second epic into two issues
  - [x] Make a generic good first issue template that will work for any good first issue (separate from this roll out plan) -> Made an ER for it: #4362
- [x] Add to next Dev/PM issue:
  - [x] Is this level correct for the issue: Issue Making Level 3: Epic? Reason: The person working on this issue to make epics is at a level 3. Already answered.
  - [x] I used last FigJam file.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng I took off the ready for product label because I think you got the feedback you needed from me last Monday

**Comment by JessicaLucindaCheng** [comment]
- [ ] I edited the roll out plan. Could someone take a look to see if there is anything I should change? It's my first time writing a roll out plan.
- [ ] I wasn't sure about how to label this roll out plan. Please check the labels.
- [ ] I wasn't sure what to do with this spreadsheet: [HfLA-Website: img Tag Audit spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1822415835). Should I
  - completely remove the instructions since those will be in the other epics and issues that will be written as a result of this roll out plan
  - Or should I let the dev lead(s) that are assigned to this roll out plan decide what to do with it?
- [ ] I made this [FigJam diagram of the roll out plan in terms of issue writing levels](https://www.figma.com/file/n4yjpWUuLI1eOxL3wJp7yq/Roll-out-plan-%234362?node-id=0-1&t=2zTT5UatchcWzd70-0). Is this how we envision it?

**Comment by jiyanpatil07** [comment]
Hello @JessicaLucindaCheng ,
I would like to work on the issue mentioned above.

**Comment by JessicaLucindaCheng** [comment]
@jiyanpatil07
In order to work on an issue, you need to be a member of Hack for LA. (There are no fees to join.) Please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.

**Comment by JessicaLucindaCheng** [comment]
# Roll Out Plan
## Epic 1
- Audit, find, and document all the instances in our codebase with img HTML tags ending with a slash (<img.../>) in the HfLA-Website: img Tag Audit spreadsheet [^1]. This epic will include an "Issue Making: Level 2" label. This epic will include the following action items:

### 1A: Template for auditing
- Make an issue template to audit, find, and document <img.../> in a file in a spreadsheet.
  - This issue template will include a "Complexity: Small" label and a "ready for dev lead" label along with all the other needed labels.
- Review and (if needed) edit the following in the HfLA-Website: img Tag Audit spreadsheet: 
  - "Instructions for Page Audit Issue Writers" section on the Instructions tab [^1]
  - Page Audit tab [^2]. All the files that still need to be audited are already listed in the Page Audit tab.
  - img with Ending Slash tab [^3]. This tab contains the lines of code with <img.../> that have been found so far. This tab will also be where developers auditing the files add their findings.
- Use the template to make 1 issue as an example
- Get approval from a PM on the template.

### 1B: Audit issue writing session
- After approval is given, ask a dev lead (a Merge Team member or Technical Lead) if you can do an issue writing session during one of the meetings so that other developers on the team can help with writing the issues using the template.

## Epic 2
- Dependency: Epic 1 and its issues being completed
- Change img HTML tags ending with a slash (<img.../>) to an img tag without an ending slash (<img...>).This epic will include an "Issue Making: Level 2" label. This epic will include the following action items:

### 2A: Template(s) for good first issues to change the img tag
- Determine if we need multiple templates. These templates will include a "good first issue" label and a "ready for dev lead" label along with all the other needed labels.
  - For removing the ending slash in img tags on the website, there is a template called "img Tag Refactor on Website" [^4] already. This template works for img tags on the website. This template can be modified or edited if needed.
  - Other templates may need to be made, such as for editing the img tags in the CONTRIBUTING.md or other files,
- Review and (if needed) edit the following in the HfLA-Website: img Tag Audit spreadsheet: 
  - img with Ending Slash tab [^3]. This tab contains the lines of code with <img.../> that have been found.
  - The "Instructions for img with Ending Slash Issue Writers" section on the Instructions tab [^1]
  - Add additional sections or instructions as needed to the Instructions tab if needed
- Make issue template(s) for writing good first issues to change <img.../> to <img...> and use each template to make 1 issue as an example
- Get approval from a PM on the template(s).

### 2B: Good first issue writing session
- After approval is given, ask a dev lead (a Merge Team member or Technical Lead) if you can do an issue writing session (or more than one session) during one of the meetings so that other developers on the team can help with writing the issues using the template(s).

## Resources/Instructions
[^1]: [HfLA-Website: img Tag Audit spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1822415835)
[^2]: HfLA-Website: img Tag Audit spreadsheet's [Page Audit tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1277680545&fvid=1305214134)
[^3]: HfLA-Website: img Tag Audit spreadsheet's [img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0&fvid=959329398)
[^4]: Issue Template 1: [img Tag Refactor on Website](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&template=img-tag-refactor-on-website.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page%28s%29) and its associated Markdown file [.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md). This template works for any pages that is marked with `Template 1` in the `Template to use if <img.../> found` column on the `Page Audit` tab . Template 1 works if the img tag is on the website.

**Comment by JessicaLucindaCheng** [comment]
- [x] Archive the FigJam: https://www.figma.com/file/n4yjpWUuLI1eOxL3wJp7yq/Roll-out-plan-%234362?type=whiteboard&node-id=0-1&t=5QWmxgUaE96UPfAW-0

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-merge Can someone read through and review this issue and its roll out plan to see if it is ready for prioritization? If you are interested, please leave your issue review availability and ETA in a new comment below. Thank you.

**Comment by roslynwythe** [comment]
@JessicaLucindaCheng 
Availability: 5/26 1 hr, 5/27 1 hr, 5/28 1 hr
ETA 5/28 EOD

Is there any documentation I could reference to understand the meaning of the various "Issue Making" labels?

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe Thanks for reviewing this roll out plan!

> Is there any documentation I could reference to understand the meaning of the various "Issue Making" labels?

- No but you can refer to the resources section of this issue: #4678, which sort of defines the labels

**Comment by roslynwythe** [comment]
Hi @JessicaLucindaCheng This looks good and it was interesting to see how you structured this Roll Out Plan into two child Epics.  Your instructions are quite clear and I would feel comfortable working on this epic (or the child epics).

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe Thanks for reviewing the roll out plan!

**Comment by JessicaLucindaCheng** [comment]
Questions for PM(s) and the answers:

Since Issue Making and Complexity issues are done in intertwined, parallel growth paths:
- Issue Making: Level 1 --> Level 2 --> Level 3 --> Level 4
- Complexity: 2 Good First --> Small --> Medium --> Large

1. Since this issue is for any front-end or back-end dev, will putting an existing Complexity label (good first, small, medium, or large) on this be confusing?     
    Ans: Yes, it is confusing using those labels.
    
  <details>
      <summary>Click here to see an example of how it can be confusing:</summary>
      <ul> 
        <li>Let's say this rollout plan has a Complexity: Large.</li>
        <li>Let's say a junior front-end developer is looking for a Large issue to work on.</li>
        <ul>
          <li>They have finished working on 2 good first issues, Small, and Medium issues.</li>
          <li>They have never written any issues, so they haven't completed an Issue Making Level 1 nor Level 2.</li>
        </ul>
        <li>They filter the issues by complexity (Large) and roles (front end), and they see this issue fits the criteria. They may choose it without ever having written an issue.</li>
      </ul>
  </details>

3. If we are adding a complexity label, I suggest we make a new label `Complexity: Issue Making` to indicate to look at the Issue Making labels. Is that okay? 
    Ans: Bonnie said yes, but word it `Complexity: See issue making label`

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng that seems like a reasonable suggestion

**Comment by roslynwythe** [comment]
Update:

- This Roll Out plan is in progress, and will remain open until all of the issues created as a result of #4922  and #5040 are closed.

**Comment by fyliu** [comment]
@roslynwythe Someone was asking about one of the issues that came out of this issue and I was thinking this could be done with a processing script.

Anyway, it seems like an opportunity for me to work on my commandline tools skills so I came up with this one-liner that runs from the project root.

It’s not entirely correct but I guess I don’t want to spend more time on it right now.
It does what it’s supposed to but also has the side effect of removing extra spaces in all tags.

`find . -name "*.html" -exec sed -i -e "s/<img\(.*\)\/>/<img\1>/g" -e "s/\s*>/>/g" {} +`

1. find all the html files and pass their paths to `sed` to process them
2. `sed` edit files in-place (-i flag) with 2 edit commands. {} is a placeholder for the file path and + is the ending
3. remove slash from closing bracket in `img` tags
4. remove spaces before closing brackets in all tags

Here is the one to process just one file that I originally worked on.

`sed -i -e "s/<img\(.*\)\/>/<img\1>/g" -e "s/\s*>/>/g" ./_includes/about-page/about-card-executive-letter.html`

Another major problem is it doesn't match img tags spread across multiple lines. So it didn't catch this file, which I used the "/>" regex to find all self-closing tags and manually went through the results.

- _includes/join-donate-card.html

Anyway, the commands might be good for checking purposes or if you ever need to remove extra spaces in all tags. I just want to leave this here since it's related to this issue.

**Comment by roslynwythe** [comment]
Hi @fyliu that sed command is really impressive!!  As you may know, we are always looking for `good first issues` for our junior developers on the website project.  So I'd like to generate a list of files with html tags with extra spaces that I could use for creating good first issues.  If you have a suggestion for that, please let me know.  If you would like, I'll create an issue..

**Comment by fyliu** [comment]
@roslynwythe Here's some commands to find extra spaces within tag brackets. 

Run these from the project root:

1. This one finds tags that have extra ending spaces

    ``` bash
    find . -name "*.html" -exec grep -lrP "<[^>]+\s+>" {} + | sort -u
    find . -name "*.html" -exec grep -nrP --color=always "<[^>]+\s+>" {} + | sort -u | less -r
    ```

    - That's matching both the `<` and the `>`, with the middle having characters that are not the closing bracket ([^>]) and having at least one space character (\s).
    - It returns false positives for cases where the > is used as a less-than operator.
    - The --color option is just to highlight the match within a line.
    - It sorts the lines and filters for uniqueness (| sort -u).
    - The `| less -r` displays the results in a scrollable buffer. You can do page-scroll `f`orward and `b`ack as well as use arrow keys for single lines. `q` to quit
    - Change the -l (show filenames only) flag into -n (show line numbers) to check manually for false positives.
    - You can also redirect the output to a file by adding `> extra-spaces.txt` at the end of the command. The color might show up as code so it's best to not have colors when saving to file.

1. Here's another one that finds multiple consecutive spaces inside tags

    ``` bash
    find . -name "*.html" -exec grep -lrP "<[^>]+\s{2,}[^>]+>" {} + | grep -v -e "-->" | sort -u
    find . -name "*.html" -exec grep -nrP --color=always "<[^>]+\s{2,}[^>]+>" {} + | grep -v -e "-->" | less -r
    ```

    - It finds multiple whitespaces (\s{2,})
    - Then it filters out html comment tags in the second grep command (-->)

**Comment by roslynwythe** [comment]
Now that we have a template for updates to CONTRIBUTING.md, I'm planning to create the img tag refactoring issues targeting CONTRIBUTING.md

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe does your comment mean that there is another epic needed before this rollout plan is completed?
>Now that we have a template for updates to CONTRIBUTING.md, I'm planning to create the img tag refactoring issues targeting CONTRIBUTING.md

or did you already do that?  It looks like you did in this epic
- https://github.com/hackforla/website/issues/5040

with these issues
- https://github.com/hackforla/website/issues/5619
- https://github.com/hackforla/website/issues/5620
- https://github.com/hackforla/website/issues/5621

**Comment by roslynwythe** [comment]
> @roslynwythe does your comment mean that there is another epic needed before this rollout plan is completed?
> 
> > Now that we have a template for updates to CONTRIBUTING.md, I'm planning to create the img tag refactoring issues targeting CONTRIBUTING.md
> 
> or did you already do that? It looks like you did in this epic
> 
> * [Epic: Create Issues for removing closing slash from img tags #5040](https://github.com/hackforla/website/issues/5040)
> 
> with these issues
> 
> * [img tag refactor in CONTRIBUTING.md Section 4.1 #5619](https://github.com/hackforla/website/issues/5619)
> * [img tag refactor in CONTRIBUTING.md Section 4.1 making #5620](https://github.com/hackforla/website/issues/5620)
> * [img tag refactor in CONTRIBUTING.md Section 3.1.b v #5621](https://github.com/hackforla/website/issues/5621)

- Yes.  There are more instances of img tags with closing slashes in CONTRIBUTING.md so I wrote #6453

**Comment by daras-cu** [comment]
@JessicaLucindaCheng @ExperimentsInHonesty all of the dependencies have been resolved for this issue so I believe the `.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md` template can be deleted. What is the procedure for deleting a file? Should I open a pull request?

**Comment by ExperimentsInHonesty** [comment]
I see a bunch of files in the code base that have references to issues with `/>` in them.  Here is the [search I used](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%2F%3E+NOT+path%3A%2F%5E_includes%5C%2Fsvg%5C%2F%2F+NOT+path%3A%2F%5Eassets%5C%2Fimages%5C%2F%2F&type=code&p=1).  Below are all the files I found on the results that seemed relevant.  Some of them are in the [HfLA-Website: img Tag Audit (Roll out plan #4362), img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit?gid=0#gid=0)  and some are not on the sheet at all (could have been added after sheet was made).  So I think there are probably issues left to make for this.   Either we reopen the following issues, or make new ones.  Thoughts?
- https://github.com/hackforla/website/issues/4922
- https://github.com/hackforla/website/issues/5040

### Examples
https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/_includes/resource-card.html#L18

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/pages/about.html#L17

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/assets/js/current-projects.js#L720

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/pages/credits.html#L32

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/_includes/about-page/about-card-sustainability.html#L56

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/_includes/about-page/about-card-executive-letter.html#L3

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/pages/getting-started.html#L100



### Example not on sheet
https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/CONTRIBUTING.md?plain=1#L845

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/pages/communities-of-practice.html#L24

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/_includes/donation/donate-gif-text.html#L11

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/_includes/wins-page/wins-card-template.html#L9

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/_includes/about-page/about-card-metrics.html#L25

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/_includes/about-page/about-card-accomplishments.html#L2

https://github.com/hackforla/website/blob/5d338a10624ebab25bb68997b4211f13a2b82dd0/.github/pull_request_template.md?plain=1#L20

**Comment by ExperimentsInHonesty** [comment]
@daras-cu In answer to your question below.  No, don't create a PR just yet.  We should always re-audit after a role out (audit + change issues).  That way, we catch anything that we missed during each of those stages.  See my comment above for what I found when I re-audited the code base.  I ended up finding 14 issues to review for possible changes, if they all need changes, that ends up being 17.5% of the changes missed if we had considered this closed without checking.

>@JessicaLucindaCheng @ExperimentsInHonesty all of the dependencies have been resolved for this issue so I believe the .github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md template can be deleted. What is the procedure for deleting a file? Should I open a pull request?

**Comment by ExperimentsInHonesty** [comment]
We will make a new issue to create issues [using this template](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=img-tag-refactor-on-website.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page%28s%29) and the results I found above


labels:
`issue making: level 1`
`feature: refactor HTML`


Make a note that leads back here to check to see if its all done and then remove the template.
