### ISSUE TITLE
ER: Feasibility of tracking the “Share your wins” and “Submit” buttons using Google Analytics

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4388]
**Note:** This issue came from the [Task List Dev Leads](https://docs.google.com/spreadsheets/d/1qEiDFUKPCVH3JNzGQSKl_HMl9vqNv8Z9gGrvw9MyYvU/edit#gid=0).

### Emergent Requirement - Problem
**Issue Description**
Can Google Analytics' tags track the “Share your wins” button on the Wins page to see how many times "Share your wins" button is clicked? This way we can compare it to the number of wins submissions we get (aka how many times submit button is clicked).

**Questions**
- Is it possible to use Google Analytics' tags on the “Share your wins” button?
- If using Google Analytics' tags isn't feasible, is there another way to do it?

**Note:** From Wins form research conducted by UX Researcher Vivian. 

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`  

### What happens if this is not addressed
We won't know how many people start a Wins submission but don't complete it.

### Resources
- https://www.hackforla.org/wins/
- https://usefathom.com/learn/track-button-clicks-google-analytics

### Recommended Action Items
- [ ] Create an issue to add a Google Analytics tag to the submit wins button, so that we can tell the number of times it is clicked by date range.
  - [ ] in the issue, indicate what resources beyond the normal team resources access a general member already has, that they will need to test and implement this issue.
- [ ] reference this ER in the resources of that issue
- [ ] add a ready for merge team label to the issue, so that it can get reviewed.
- [ ] add a link to that issue in this ER. 
- [ ] when that issue is added to the prioritized backlog, close this ER.

### Potential solutions [draft]

**Comment by HackforLABot** [comment]
Hi @Cloid, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by Cloid** [comment]
availability: weekdays 5:30pm-10pm pst
eta: eod march 28

**Comment by t-will-gillis** [comment]
Hi @Cloid Please give us an update to let us know if you are still working on this, and if so when you expect to be done. Thanks!
