### ISSUE TITLE
Roll Out plan: Make issues required to change all the places that Good Second Issues appears with Good First Issue

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4432]
### Dependency
- #4423

### Issues Created
- [x] #4423 
- [x] #4506 
- [x] #4508 
- [x] #5476 
- [x] #5477
- [x] #4509 
- [x] #4510
- [x] #5587
- [x] #6199 
- [x] #6242

### Overview
We need to create a plan and issues for changing from `good second issue` label to `good first issue` label, so that it all gets rolled out at once

### Action Items
- [x] Change all the closed issues and PRs to use the `good first issue` label instead of the `Complexity: Good second issue`
- [ ] Define and write all the issues required for this roll out plan (all the issues will get dependencies defined below)
  - [x] Finding all the locations https://github.com/hackforla/website/issues/4423
  - [x] Updating the code (includes contributing file, so this might require multiple issues) https://github.com/hackforla/website/issues/4506
  - [x] Updating the wiki with new information (this might make require several issues) https://github.com/hackforla/website/issues/4508
  - [x] #5476
  - [x]   #5477
  - [x] Updating the Project Board, `Onboarding infos/links` column (there could be two tasks here, once to add a card that explains the change and changing the card(s)
    - [x] https://github.com/hackforla/website/issues/4509
    - [x] https://github.com/hackforla/website/issues/4510
  - [x] Updating open PRs text if they need it (if after reviewing the PRs found in 4423 and none need updates to any text inside them, this checkbox can get checked and strike though)
  - [x] ~Making the label change on issues https://github.com/hackforla/website/issues/4431 and adding a note to any issue that has an assignee.~  No open PRs or Issues with `good second issue` so 4431 was closed.  
  - [x] Making the label change on PRs (open and closed) and adding a note to all the open PRs
- [ ] Decide in which order the issues get done, or hold a PR party on a Thursday night to do all the issues at once with the team members.  
   - [x] Update all the closed Issues and PRs again to use the `good first issue` label instead of the `Complexity: Good second issue`
   - [ ] If the issues are going to get done in a certain order (not a party), then edit each issue's dependency to represent the order.
- [ ] Update our Data Scientist that this change has been fully implemented https://github.com/hackforla/website/issues/4152#issuecomment-1499468391

### Resources/Instructions
Dependency for all the issues
```
### Dependency
- [ ] #4423
- [ ] #4432 is ready for implementation
```

Message that should go on PR issue.  See issue 4423 for example
```
Hi, we are about to change the label on your PR `Complexity: Good second issue` to `good first issue` to relect the update to our issue ladder of all members will work on two good first issues instead of the dev team making seperate issues for first and second (even though they were essentially the same).  

You might be asking youself, why do you need to do two good first issues, instead of just one?!.  The first two issues is where we catch if anyone has problems with branching appropriately on our project.  So we intentionly make them very very small and perscriptive so that we can focus on making sure you have the branching down before we move you on to the bigger issues that get less and less perscriptive as you go up the ladder.

When you sucessfully finish with this issue/PR, you can go on to a Small issue just as you would have before.
```
- [HfLA Site Audit: Good Second Issue Label](https://docs.google.com/spreadsheets/d/1xoCOAxoUXo2kVNeaQAwUgfqlNU0RiLGcHrY6sAGqhfc/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
@jdingeman Please review this and its related issues and see if these are all the steps required for the roll out plan.  Or is there something I have forgotten about.  

- I revised the issue formerly know as `Replace all "good second issue" labels with "good first issue" label` to #4431 and lowered is scope
- I moved the scope I took out to https://github.com/hackforla/website/issues/4431 
- I created this issue to serve as an epic so that you or someone else on the dev lead team can make the rest of the issues.

**Comment by jdingeman** [comment]
Hi @ExperimentsInHonesty, this looks good and is very thorough. The timing will be a little funny (of course, it's never straightforward lol), but I think #4423 will technically need to happen first before the other issues actually start getting created.

I don't think the order matters so much except that #4423 happens first, but I think it'll get too messy with an issue writing party because of how different the issues might be and it may just be easier to write them up all at once when the places are all found.

**Comment by jdingeman** [comment]
- Honestly, thinking about it now, I don't think it really matters what order they are in. Just as long as we get the answers from #4423, I don't think it will cause any kind of catastrophic confusion if they are not done in order.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty we are ready to move forward with implementation.

**Comment by ExperimentsInHonesty** [comment]
- @roslynwythe I beleive this issue needs to be closed so that the last issue can be released, since this issue is a dependency on the last unchecked box under action items https://github.com/hackforla/website/issues/5587.  Kind of circular.  If you agree, ill close this and release the other issue.

**Comment by roslynwythe** [comment]
> * @roslynwythe I beleive this issue needs to be closed so that the last issue can be released, since this issue is a dependency on the last unchecked box under action items [Remove card explaining the changes with removal of the "good second issue" labels #5587](https://github.com/hackforla/website/issues/5587).  Kind of circular.  If you agree, ill close this and release the other issue.

- @ExperimentsInHonesty We have two new issues/dependencies - #6199 and #6242

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe Can I close now?

**Comment by roslynwythe** [comment]
> @roslynwythe Can I close now?

Yes

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 13, 2024 at 12:14 PM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 27, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 3, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 10, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 17, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 8, 2024 at 12:05 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 15, 2024 at 12:04 AM PST.</sub>
