### ISSUE TITLE
Epic: Make sure that the data in the project's page filters content is properly categorized

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4434]
### Dependency
- [ ] #4262 

### Overview
We need to make sure that languages are not being added to tools and technologies fields on project.md cards and that items that should be in tools are not in technologies and vice versa.

### Action Items
- [x] Make new issues
   - [x] https://github.com/hackforla/website/issues/4427
      - Last action item should be `- [ ] Release dependency on #3487`
      - Last action item should be `- [ ] Release dependency on #4262 `
      - Resources should contain the epic text/link
      - Go to 4262 and change out the Dependency that currently says `Revise the Languages / Technology filter on the 
   - [x] https://github.com/hackforla/website/issues/3487
      - Resources should contain the epic text/link
   - [x] https://github.com/hackforla/website/issues/4262
      - Resources should contain the epic text/link
- [x] Add the following dependency text to this issue and put in the icebox
   ```
   ### Dependency
   - [ ] #4262 
   ```
- [ ] List issues to make identified by 4262
- [ ] Make the issues
- [ ] Add all appropriate
  - [ ] dependencies 
  - [ ] and Resource epic text/link

#### Text for the Resources section of the issues
```
- This issue is part of an epic: #4434
```

#### Pages involved
https://www.hackforla.org/projects/
https://www.hackforla.org/projects-check/

### History
- This Epic came from this ER https://github.com/hackforla/website/issues/4261
