### ISSUE TITLE
Creating issues to remove all "good second issue" references in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4506]
### Dependency
- [x] #4423
- [x] #4432 is ready for implementation
- [x] #5165 or #5547

### Issues
- [x] #5590
- [x] #5588
- [x] #5591
- [x] #5617

### Overview
Since we are deprecating the "good second issue" label we need to to edit the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) guide so that we no longer have references to "good second issue".

### Action Items
- [x] This issue should only be assigned to a lead
- [x] Develop a [template](https://github.com/hackforla/website/issues/4506#issuecomment-1736090948)
- [x] Find all references to `good second issue` in CONTRIBUTING.md
  - [x] For each reference, create a new issue to replace/remove them from CONTRIBUTING.md as appropriate
  - [x] Add the labels `Complexity: Small`, `size 0.5pt`, `role: front end`, `role: back end/devOps`, `Feature: Onboarding/Contributing.md`, `ready for dev lead`
- [x] Add the new issues to the Issues section above
- [x] Once all necessary issues have been created
  - [x] Add a `dependency` label
  - [x] Move this issue to the Ice Box column
- [x] If all the dependency issues are closed, remove the dependency label, move this issue from the Ice Box to the In Progress column, and close this issue

#### For Merge Team/Tech Lead/PM
- [x] When this issue is closed, release the dependency for this issue on #4432

### Resources/Instructions
- This is part of epic #4432 
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

**Comment by roslynwythe** [comment]
Template for "Removing good second issue from CONTRIBUTING.md": 
  - also see sample issue: #5590

start with the GitHub template [Update CONTRIBUTING](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Wiki%2C+Complexity%3A+Small%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&projects=&template=update-CONTRIBUTING.md&title=Update+CONTRIBUTING.md+Section+%5BINSERT+SECTION+%23%5D), then make the following additions:
- specify the section to modify in the issue title
- specify the "before" and "after" text
- add a note to reviewers:
``` 
### For Merge Team
- [ ] Resolve the dependency on this issue in #4506.  If all dependencies have been resolved, close that issue.  
```
- add to Resources section:
```
- This issue is part of #4506
```

**Comment by t-will-gillis** [comment]
All associated issues are merged, closing this issue to release dependency on #4432
