### ISSUE TITLE
Creating issues to remove all "good second issue" references in Wiki

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4508]
### Dependency
- [x] #4423
- [ ] #4432 is ready for implementation

### Issues
- [] 

### Overview
Since we are deprecating the "good second issue" label we need to to edit the HfLA Site [Wiki](https://github.com/hackforla/website/wiki)* guide so that we no longer have references to "good second issue".

### Action Items
- [ ] This issue should only be assigned to a lead
- [ ] For references detailed in [HfLA Site Audit: Good Second Issue Label Spreadsheet](https://docs.google.com/spreadsheets/d/1xoCOAxoUXo2kVNeaQAwUgfqlNU0RiLGcHrY6sAGqhfc/edit#gid=0) create new issues to replace/remove them from the Wiki* as appropriate
  - [ ] Add the labels `size 0.5pt`, `role: front end`, `role: back end/devOps`, `Feature: Onboarding/Contributing.md`, `ready for dev lead`
    - DRAFT NOTE: Complexity would likely be `good first issue` if we decide on exact phrasing to go into the issues 
- [ ] Add the new issues to the Issues section
  - DRAFT NOTE: Not sure if this will be called "Issues" or they'd go under "Dependency" with the other two dependencies. 
- [ ] Once all necessary issues have been created
  - [ ] Add a `dependency` label
  - [ ] Move this issue to the Ice Box column
- [ ] If all the dependency issues are closed, remove the dependency label, move this issue from the Ice Box to the In Progress column, and close this issue

#### For Merge Team/Tech Lead/PM
- [ ] When this issue is closed, release the dependency for this issue on #4432

*Wiki edits may depend on launch of website-wiki

### Resources/Instructions
- This is part of epic #4432 
- HfLA GitHub [Wiki](https://github.com/hackforla/website/wiki)
- HfLA new [website-wiki](https://github.com/hackforla/website-wiki)
- References to `Complexity: Good second issue` were audited in #4423 and detailed in [HfLA Site Audit: Good Second Issue Label Spreadsheet](https://docs.google.com/spreadsheets/d/1xoCOAxoUXo2kVNeaQAwUgfqlNU0RiLGcHrY6sAGqhfc/edit#gid=0)

**Comment by roslynwythe** [comment]
This issue is not necessary because Bonnie and Roslyn removed all the references to "good second issue" in the wiki

**Comment by roslynwythe** [comment]
One reference to "good second issue" remained in "How to Review Pull Requests" and was manually edited.  A link to the updated page is listed in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

**Comment by roslynwythe** [comment]
One reference to "good second issue" remained in "How to Review Pull Requests" and was manually edited.  A link to the updated page is listed in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
