### ISSUE TITLE
ER: Create a skills dashboard

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4532]
**Note:** This issue came from the [Task List Dev Leads](https://docs.google.com/spreadsheets/d/1qEiDFUKPCVH3JNzGQSKl_HMl9vqNv8Z9gGrvw9MyYvU/edit#gid=0).

### Emergent Requirement - Problem
**Issue Description**
As Hack for LA members, we need a skills dashboard so that we can track the skills we have gained at Hack for LA.

### Who was involved
- @ExperimentsInHonesty 
- @JessicaLucindaCheng 

### What happens if this is not addressed
Members won't have a skills dashboard that allows them to easily track the skills they have gained at Hack for LA.

### Resources
- [Dashboard Drive Folder](https://drive.google.com/drive/folders/1uR_9JLx4It1WgTrYmqhdg5atVp62pPwx)
- [IS21: Skill Audit](https://docs.google.com/spreadsheets/d/1OZFg3xgpH1gflQTUT7ImZlLW0Co3mvGt-jLTJhKRNk8/edit#gid=1792255924)

### Recommended Action Items
- [ ] Requirements elicitation: Discuss with Stakeholder Rep (Bonnie) what is desired for the skills dashboard
- [ ] Write an issue for implementing a skills dashboard and include a blank version of the spreadsheet for use by the website team. (See link to Google Sheet in Resources.) 

### Potential solutions [draft]
- It will mainly be an internal product.
- Skills labels will be added to all the issues 
- Then the looker dashboard will tell leads (and maybe members themselves) what skills have been gained based on completed, closed issues.

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 

1) Is this the same as https://github.com/hackforla/engineering/issues/65? If yes, should this be closed?
**Answer from Bonnie:** No, it's different. We are going to add skills labels to all the issues and then the looker dashboard will tell lead (and maybe members themselves) what skills have been gained. It will be an internal product.

2) If no,
  i. Should requirements elicitation be an action item in this ER or its resultant issue? See Recommended Action Items.
  ii. Is there anything else that needs to be added to this ER to make it `ready for issue making`? I wasn't sure what specifics you were thinking of for the skills dashboard.
  **Answer for both of these questions from Bonnie:** More specifics and details about the requirements for the skills dashboard will be added by org rep.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng I am adding Neema Humphries to this issue.  She is the Data Scientist who is going to work on it and help us get the issue defined.

**Comment by t-will-gillis** [comment]
test comment for automation

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis this is not really written up as an issue to work on.  I need to do that.  I will assign myself to this draft.  But please don't remove n2020h from the repo

**Comment by n2020h** [comment]
Got it!

I'm sorry I didn't respond sooner. I've been tied up with a new job. I'll
have an update ready by Monday.

**Comment by n2020h** [comment]
Progress: Created GH actions scripting to create csv. 
Connected csv to looker dashboard: https://lookerstudio.google.com/reporting/23182581-babc-4907-a534-e38db0ecef3e
Currently attempting to recreate original model dashboard. 

Blockers: Unsure about how some of the original data was queried or configured to create original charts and visualizations. I would like to look behind the scenes of original dashboard. Currently I am receiving "Chart configuration incomplete" errors on my dashboard. 

Availability: I have 4 hours this week

ETA:  Pending response to blocker. 

Pictures (optional): 
<img width="1483" alt="image" src="https://github.com/hackforla/website/assets/72112832/434a9a2c-526b-4653-aa1f-492225708322">

**Comment by ExperimentsInHonesty** [comment]
@Rabia2219 In order to give @n2020h access to a copy of the [skills dashboard](https://lookerstudio.google.com/reporting/98d7a4a7-9092-44f9-937f-cd3cd2a9cd27/page/p_ux94i6bfvc?s=pvg4HLLgeiM), we need to copy [IS21: Skill Audit spreadsheet,](https://docs.google.com/spreadsheets/d/1OZFg3xgpH1gflQTUT7ImZlLW0Co3mvGt-jLTJhKRNk8/edit#gid=1792255924), desidentify the data in the copy, copy the copy and remove the data that is unneeded, copy that copy, and re-connect the data to the new skills dashboard copy and share with her

### Tabs
NEW FORMAT
Matrix
Skills Data

**Comment by Rabia2219** [comment]
### Update
- The original skills audit spreadsheet was copied, PII was removed
- Created a copy again
- Made a copy of the dashboard and connected the new spreadsheet as the data source
  - each tab for new data source has to be connected first
  - you can remove the original data source
  - each visualization has to be manually connected to the data source (tabs in the data source)
  - the 'Participating Interns' chart wasn't linking properly to the data source, (even though the same data source was working for other visualizations). I replicated the chart and linked it to the related data source and it worked. I then deleted the original chart.

**Comment by mayankt153** [comment]
@n2020h We are in the process of reorganizing where we are keeping the assets for skills dashboard. We need to add you to another Google Drive because we moved some items you might have been working on.

~Please provide your email address.~ Nevermind, we found it in the roster.

**Comment by mayankt153** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- [Task List Dev Leads](https://docs.google.com/spreadsheets/d/1qEiDFUKPCVH3JNzGQSKl_HMl9vqNv8Z9gGrvw9MyYvU/edit#gid=0)
  - [ ] Have access, its located in ____
  - [x] public
- [Dashboard Drive Folder](https://drive.google.com/drive/folders/1uR_9JLx4It1WgTrYmqhdg5atVp62pPwx)
  - [x] Have access, its located in HfLA Dashboards -> Skills Dashboard
  - [ ] public
- [IS21: Skill Audit](https://docs.google.com/spreadsheets/d/1OZFg3xgpH1gflQTUT7ImZlLW0Co3mvGt-jLTJhKRNk8/edit#gid=1792255924)
  - [x] I don't have access - located in Internship > Internships > IS21 cohort - brentwood only > Skill Analysis (has PII, and we will need Rabia to make a version and relink it to the current demo so that it's movable to the new dashboard drive)
  - [ ] public
