### ISSUE TITLE
ER from TLDL: Standardize Project Slack links to use `archives`

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4535]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
- On the [Projects page](https://www.hackforla.org/projects/), for any project cards that use the `messages` Slack link (i.e. the Slack link of Civic Tech Jobs (https://hackforla.slack.com/messages/C02509WHFQQ)), change them to use the `archives` Slack link. An example that uses the `archives` Slack link is Civic Tech Index (https://hackforla.slack.com/archives/CTYAKM0CW). This would standardize Slack links for all projects on the Projects page.

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`   

### What happens if this is not addressed
The Slack links will not be standardized and some will have the `messages` version and some will have the `archives` version of the Slack links.

### Resources
- https://www.hackforla.org/projects/

### Recommended Action Items
- [ ] Search and check 
  - [ ] If an open issue exists that addresses this ER
  - [ ] If a closed issue exists that has already addressed this ER
- [ ] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue 
### Potential solutions [draft]

**Comment by Vayras** [comment]
Hey @JessicaLucindaCheng I would like to help with this issue can you assign this to me ?

**Comment by JessicaLucindaCheng** [comment]
@vayras This issue is not ready to be worked on by a developer.

Also, in order to work on an issue, you need to be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.

**Comment by jdingeman** [comment]
@JessicaLucindaCheng - is there a reason we'd want to use the archives instead of the messages?

**Comment by JessicaLucindaCheng** [comment]
@jdingeman I don't actually know the answer since I'm not familiar with the differences nor pros/cons between using the `archives` vs `messages` link. 
- However, with some playing around on my laptop, when opening the links in a new tab, I found the `archives` link redirects and opens to the channel in my Slack desktop app and the `messages` opens in my browser. 
Example: Links for EMS Triage Tracker
  - https://hackforla.slack.com/archives/CQ5J1DA72
  - https://hackforla.slack.com/messages/CQ5J1DA72

**Comment by jdingeman** [comment]
@JessicaLucindaCheng - got it. I got confused at first because I thought the `archives` and `messages` links would end with different IDs for each project. But yes, I think it's better to make them all `archives` since that leads straight to the desktop app.

**Comment by jdingeman** [comment]
@JessicaLucindaCheng 
- Issue made here https://github.com/hackforla/website/issues/4564
I think the whole Issue Making levels has thrown me for a loop

**Comment by JessicaLucindaCheng** [comment]
@jdingeman 
> I think the whole Issue Making levels has thrown me for a loop

I'm still a little confused myself but I think in the long run it will be worth it once we figure it out.
