### ISSUE TITLE
ER: Counting Activities in a PR as Activity Credit in Its Linked Issue

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4536]
**Note:** This issue came from the [Task List Dev Leads](https://docs.google.com/spreadsheets/d/1qEiDFUKPCVH3JNzGQSKl_HMl9vqNv8Z9gGrvw9MyYvU/edit#gid=0).

### Emergent Requirement - Problem
Currently, issues with a linked open pull request (PR) will not get an automated comment requesting the assignee of the issue for an update nor a `To Update !` label if it has been a week. The same thing happens for the `2 weeks inactive` comment and label, where the comment and label are not added if there is an open linked PR to the issue. 

**Problem:** If the PR's author (aka assignee of the associated issue) of an open PR doesn't make requested changes promptly and there is no `2 weeks inactive` label on the PR's associated issue, this may cause the following problems:
- The PR may get old and stale.
- There may be no updates/ETA from the developer on when the changes will be made, so we won't know if and when changes will be made.
- With no updates, we may not be able to tell if the developer ghosted us or is inactive for some reason.
- Also, this may cause issues to sit in the "In progress (actively working)" column indefinitely, since they may not be checked by leads, Merge Team members, or PMs if they don't have a `2 weeks inactive` label.

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`   

### What happens if this is not addressed
- All issues with a linked open PR have to be manually checked to see their status/activity and if they have gone stale, which can take up a lot of time.

### Resources
- https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/add-update-label-weekly

### Recommended Action Items
- [x] Discuss with the team first if this still needs to be addressed or if the problem is no longer an issue because other processes in place address the problem. **Ans:** This is still a problem that should be addressed.
- [x] If it is still a problem, decide upon what the solution will be.
- [ ] Write an epic

### Potential Solutions [Draft]
- [ ] Write an epic containing the following:
#### Counting Activities in a PR as Activity Credit in Its Linked Issue
Each of the following issues will count the described activity in the PR as activity credit in its linked issue. 
- [ ] A `Complexity: Large` issue to implement counting the activity of creating a PR by the issue's assignee (a.k.a. the PR's author). This currently is automatically noted on the issue.
- [ ] A `Complexity: Large` issue to implement counting the activity when reviewers are assigned to a PR.
- [ ] A `Complexity: Large` issue to implement counting the activity when a PR's author makes a new commit in the PR.
- [ ] A `Complexity: Large` issue to implement counting the activity when a PR's author makes a new comment in the PR.
- [ ] A `Complexity: Large` issue to implement counting the activity when a PR is merged.
#### Turn on `To Update !` and `2 weeks inactive` Automations
- [ ] A `Complexity: Large` issue to implement turning on the automation for `To Update !` and `2 weeks inactive` labels for issues with a linked open PR and the issues are in the "In progress (actively working)" column.
  - [ ] This issue will have a "Dependency" section with a link to each of the issues written for the "Counting Activities in a PR as Activity Credit in Its Linked Issue" section

**Comment by t-will-gillis** [comment]
@JessicaLucindaCheng - Just to confirm: is the goal to have the bot continue checking an issue for assignee activity and continue to add the `To update !` and `2 weeks inactive` labels on open issues that also have an open PR? 

When we have been working on the `schedule-fri-0700.yml` (i.e. the GHA which checks for activity and applies the update labels), we have purposefully included checks so that once a PR is opened for the issue, all updates cease. That is, we intentionally baked this into the code. See [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) 

Our reasoning has been that once a PR is opened on an issue, the issue assignee would be waiting for the PR review process to play out, and there would not be any reason for the assignee to provide updates on the issue because all of the activity has shifted to the PR.

Should we discuss?

**Comment by JessicaLucindaCheng** [comment]
@JessicaLucindaCheng Sorry, it wasn't clear what the problem was addressing. I updated the Problem and Potential Solutions in the issue above, and added an Action Item to discuss it.

Since this was something we wanted a long time ago (even if before this ER was open, this was in a spreadsheet), I think it is a good idea to discuss this with Bonnie, Rosyln, and the rest of dev team if this still needs to be addressed or if the problem is no longer an issue because other processes in place address the problem.

**Comment by JessicaLucindaCheng** [comment]
@t-will-gillis Sorry, it wasn't clear what the problem was addressing. I updated the "Emergent Requirement - Problem" and "Potential Solutions [draft]" in the issue above, and added a couple of Action Items.

> Should we discuss?

That's a good idea! Since this was something we wanted a long time ago (even before this ER was opened, this was in a spreadsheet), I think it is a good idea to discuss this with Bonnie, Roslyn, and the rest of the team if this still needs to be addressed or if the problem is no longer an issue because other processes are in place that address the problem.

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty @roslynwythe 

- Are we going ahead with wanting to implement the GHA for this ER? Is this still a problem that needs to be addressed or is there other processes in place to make sure PRs don't get stale? See points brought up in [Will's comment](https://github.com/hackforla/website/issues/4536#issuecomment-1694778253).

- If we are going ahead with wanting to implement this GHA, what solution do we prefer to adopt? See _Potential Solutions [draft]_ in the issue.

**Comment by roslynwythe** [comment]
@JessicaLucindaCheng @t-will-gillis I don't think this is really necessary, because merge team scans all of the Pull Requests and I think we will notice if an author stops responding.  But if we want to pursue this, I suggest that the GHA examines every PR with "changes requested" and if there is no author activity in a week or two, apply an inactive label to the PR.

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe Thanks for your input!
- When you say, "...if there is no author activity in a week or two, apply an inactive label to the PR," do you mean the "To Update!" and "2 weeks inactive" labels?
  - **Answer from Rosyln:** Yes
- Also, should the GHA also add an automated comment to the pr? I'm thinking this comment would be similar to the ones added to an issue when either a "To Update!" or a "2 weeks inactive" label is added.
   - **Answer from Rosyln:** Yes

**Comment by JessicaLucindaCheng** [comment]
Message to the author: This pr seems to have gone stale. Please let us know if you are still working on it and give us a progress update (progress, blockers, availability, ETA) in this pr.

**Comment by HackforLABot** [comment]
Hi @JessicaLucindaCheng, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 

- For point 3 in the "Potential Solutions" section, is that what you want to happen?
- If this is okay as is, then this ER is `ready for prioritization`.

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis 

What do you think about having a GHA that every time something happens on a pr, that it updates the issue with what happened?  And some of those updates would be treated as activity.

- Opened a pr which is currently and automatically noted on the issue (credit for activity)
- when reviewers are assigned (credit for activity)
- when reviews are left and if they require changes or not
- when author makes new commit or comment (credit for activity)
- when merged (credit for activity)

**Comment by HackforLABot** [comment]
Hi @JessicaLucindaCheng, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by JessicaLucindaCheng** [comment]
@JessicaLucindaCheng 
### Tasks
- [x] Update this ER to implement counting activity on pr in its related issue. 
- [x] Then, after the pr activity is counted as activity in the issue, have `to update` and `2 weeks inactive labels` be turned on for all issues.

**Comment by JessicaLucindaCheng** [comment]
@t-will-gillis 

1) Under the "Potential Solutions [Draft]", do you think all the issues in the "Counting Activities in a PR as Activity Credit in Its Linked Issue" section can be implemented/worked on at the same time?

2) Can you please review this ER? If you think it's `ready for prioritization`, please add the label. Otherwise, let me know what changes you would like me to make.

Thanks.

**Comment by t-will-gillis** [comment]
Hi @JessicaLucindaCheng this issue fell off my radar. 

Could we discuss again what this issue needs to account for?
- For comparison only: the "Schedule Friday" workflow checks the assignee's activities, with the clock starting when the assignee opens the issue and the clock being reset after every activity.
- For this issue, assume that when the author opens the PR, the clock is started.
- Assume that any activity on the PR **_by the author_** resets the clock.
- Do any activities by reviewers ever reset the clock?
- When the workflow runs, is the lack of activity since the last clock reset reported on the PR, or on the issue, or on both?

> 1. Under the "Potential Solutions [Draft]", do you think all the issues in the "Counting Activities in a PR as Activity Credit in Its Linked Issue" section can be implemented/worked on at the same time?

Ans: I think this would be one issue.
