### ISSUE TITLE
ER: Wiki page documentation for each page on our website

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4543]
### Emergent Requirement - Problem
We have to repeat information about Hack for LA's webpages when commenting on issues or a member will have to research to figure out how a webpage works instead of just providing a link to a wiki page with all the information provided.

### Issue you discovered this emergent requirement in
- Not Applicable

### Date discovered 
Not Applicable
**Note:** This issue came from the [Task List Dev Leads](https://docs.google.com/spreadsheets/d/1qEiDFUKPCVH3JNzGQSKl_HMl9vqNv8Z9gGrvw9MyYvU/edit#gid=0).

### Did you have to do something temporarily
- [x] YES , repeat information about Hack for LA's webpages when commenting on issues
- [ ] NO

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`   

### What happens if this is not addressed
Information is repeated about Hack for LA's webpages or members have to research to figure out how a webpage works. Both are time-consuming.

### Resources
- [Wins wiki page](https://github.com/hackforla/website/wiki/Wins-page)
- [Citizen Engagement wiki page](https://github.com/hackforla/website/wiki/Citizen-Engagement-page)
- Pages section in https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture

### Recommended Action Items
- [x] Make a new epic
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- [ ] Write an epic with action items to make issues to make or update the wiki page for each page on our website similar to the [Wins wiki page](https://github.com/hackforla/website/wiki/Wins-page) and [Citizen Engagement wiki page](https://github.com/hackforla/website/wiki/Citizen-Engagement-page)
- [ ] Each wiki page
  1) Every page should have a breakdown of what files are involved
  2) Any pages with automation needs a breakdown of what the automation does
  3) Pages should be short as possible
  - [ ] To see what information is currently available, see existing pages in the Pages section of https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture and by searching the wiki
- [ ] If #2676 is not completed and the [website-wiki repo](https://github.com/hackforla/website-wiki) isn't ready for submissions yet, please add the Action Item in this card as the first Action Item in the issue you are writing: https://github.com/hackforla/website/projects/7#card-88800266
