### ISSUE TITLE
WINS form analysis

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4577]
### Dependencies

Work on this issue can begin immediately and must be completed before any of the subsequent issues can be addressed
- [ ]  #4588

If the result of the above issue is that the custom HTML/JS form is secure and feasible, these issues can proceed:
- [ ] restart work on #2021 (?design, ?research)
- [x] #4556
  - Functional audit of the HTML form and associated Google Sheet to outline steps required for adoption, including what validation needs to be added and which questions, roles, and projects need to be updated.  Also determine why the form does not currently store responses in the Google Sheet.  
  - Summarize pros/cons of HTML form versus alternatives including putting Google Form in an iFrame.  
  - This issue will result in a DR on whether or not to adopt the new form.  If the form is adopted, work can proceed: 
- [ ] Issue 3: Integration of submitted WINS data into wins-form (Response) Sheet
- [ ] Issue 4: Fix problems in new WINS HTML/JS form.  

### Details
- The motivation for exploring the use of the custom HTML form include:
   -  Integration with the HfLA [website](https://hackforla.org)
   - Control over form functionality such as URL validation (see ER #4185)
   - Option of developing code to dynamically generate the list of projects options in the form. 
- Concerns related to the adoption of the custom HTML form include
   -  Security issues related to storing submission data in the wins-form (Response) Sheet (see #4588)
   - Most updates to the form will require skill using HTML and possibly JavaScript.  

### Resources/Instructions
- This epic is a result of #4390

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by roslynwythe** [comment]
@Hritik1503 I don't believe we will move forward with this issue, but if we do, it would only be available to members of the Hack for LA organization.  Perhaps you would like to join us?  Please see https://www.hackforla.org/join

**Comment by roslynwythe** [comment]
Progress
- I don't believe work will move forward at this time on WINS form development due to security concerns.  Unless the result of #4588 shows that the form does not pose any security problems, this epic will be closed as Not Planned

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe There is no overview, so I can't assign a milestone

**Comment by roslynwythe** [comment]
- The scope of #4566 was changed from the wider scope described above, to a narrow scope focused only on security concerns.  The result was a DR which will be placed [Decision Records on Solutions Not Implemented](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented) once the wiki is available for editing.   The draft can be found in https://github.com/hackforla/website/issues/4588#issuecomment-1543560276
- Since the form is not secure, no further issues will be created and the related epic #4577 will be closed as not planned.

**Comment by roslynwythe** [comment]
- The scope of #4566 was changed from the wider scope described above, to a narrow scope focused only on security concerns.  The result was that the form is not secure;  this finding will be documented in a DR which will be placed [Decision Records on Solutions Not Implemented](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented) once the wiki is available for editing.   The draft can be found in https://github.com/hackforla/website/issues/4588#issuecomment-1543560276
- Since the form is not secure, no further issues will be created and this epic will be closed as not planned.
