### ISSUE TITLE
ER from TLDL: Audit paragraphs on website

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4679]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
- Write an issue to create a Rollout Plan which will include the following Action Items:
  - Include a Dependency section at the top of the issue as written in the "Potential solutions [draft]" section below.
    - Note: The results of the "Design System Audit: Text Elements..." issues can be used to help determine the paragraph classes that need to be applied to the paragraphs on the website.
  - Do an audit of each page's paragraphs to figure out what font styling it has and see if a paragraph class can be used in its place.   
  - Write Small issues to use paragraph classes and remove font styling in other classes. Make sure to search the repo to see where a class is used before removing its font styling.

**Notes:**
- Most of the paragraphs on the site probably don't use paragraph classes because it was "recently" added to the codebase on Mar 2, 2022.
- There are no paragraph 4-5 classes in our codebase because it was determined the font size was too small and not recommended.

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`   

### What happens if this is not addressed
Instead of reusing the paragraph classes, we have duplicate font SCSS styling throughout our repo, which would make it harder to change the SCSS paragraphs' styling across the site if we decide to make changes to the design system.  

### Recommended Action Items
- [ ] Search and check 
  - [ ] If an open issue exists that addresses this ER
  - [ ] If a closed issue exists that has already addressed this ER
- [ ] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue to write a rollout plan. See the "Emergent Requirement - Problem" section above for details.

### Potential solutions [draft]
```
### Dependency
- [ ] These issues, titled "Design System Audit: Text Elements...", need to be completed or closed: https://github.com/hackforla/website/issues?q=is%3Aissue+%22Design+System+Audit%3A+Text+Elements%22+label%3A%22role%3A+design%22+
```

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm This ER is ready for PM review and approval. If the PM approves and thinks this ER is ready for an issue to be written from it, please add a `ready for dev lead` label.

**Comment by ExperimentsInHonesty** [comment]
I added this to the dev/pm agenda with the following question

> BW: JC, when you say that the roll out plan has a dependency, do you mean, we create the roll out plan and then it is put in the icebox until the dependency is addressed? https://github.com/hackforla/website/issues/4679

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 

> BW: JC, when you say that the roll out plan has a dependency, do you mean, we create the roll out plan and then it is put in the icebox until the dependency is addressed? https://github.com/hackforla/website/issues/4679

I meant 
- write an issue to create a roll out plan 
- then put it in the icebox until the dependencies are addressed

**Comment by ExperimentsInHonesty** [comment]
This is ready to make an issue from this ER.

**Comment by JessicaLucindaCheng** [comment]
Adding to next Dev/PM agenda for discussion:

Question for PM(s):
- I know in 2021 there was an audit of the headers on the website and issues were created to implement the fix/using the "title" classes (e.g. title1, title2, etc). Since there was that previous audit and issues to fix the headers, I had intended for this ER to only deal with paragraphs on the website and not the headers. However, since all the text elements will be reaudited in Figma by the designers in the ["Design System Audit: Text Elements..." issues](https://github.com/hackforla/website/issues?q=is%3Aissue+%22Design+System+Audit%3A+Text+Elements%22+label%3A%22role%3A+design%22+), should this ER be about all text elements, including headers?

**Comment by JessicaLucindaCheng** [comment]
To Do
- [ ] Write an issue with the decision record about next steps
  - Designers
    - Current design issues
    - The designer compares the Figma design with the website page visually. 
      - If there are differences, talk with PM(s) about which version (Figma or website) to keep. Then, do one of the following:
        - If keeping website version, the Figma design needs to be updated
        - If keeping Figma version, the website code needs to be updated
  - Developers
    - Medium issue template for Figma design doesn't match the current iteration of the site and we are keeping the Figma page
    - Once the pages look the same, medium issue template for Figma design looks exactly the same so just check the page to see if actual classes are used as indicated in the Figma
- [ ] Change this ER to be about this
  - [ ] Make a template: Designer compares the Figma design with the website page visually
  - [ ] Make a template: Something different on website vs Figma but we want to keep website version. So a design template
  - [ ] Make a template: Something different on Figma vs website but we are keeping Figma version, so a dev template
  - [ ] Make a template: Once the pages look the same, medium issue template for Figma design looks exactly the same so just check the page to see if actual classes are used as indicated in the Figma

**Comment by JessicaLucindaCheng** [comment]
From Dev/PM meeting on 2024-04-29, 
- developers will also audit the pages and make the code changes if needed
- one epic will be to audit all the pages by developers and the issues from this audit will be either Small or Medium size depending on how explicit the instructions are for auditing
- another epic will be to make changes and the issues out of this could be Small or Medium issues depending on the change

**Comment by ExperimentsInHonesty** [comment]
add size of the issue that will be made
