### ISSUE TITLE
Create new issues to refactor each page & files using Tools data

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4776]
### Dependency

- [x] #4525

### Overview

We need to create issues to refactor each of the pages identified in #4525 as a necessary step towards adding a Tools filter to the [projects-check](https://www.hackforla.org/projects-check/) page per issue #4427

### Action Items

- [x] Using the list created in issue #4525, create a new issue for each list entry and itemize each new issue below. 
  - [x] Each issue should identify the page affected and the edits required in the file(s) that uses that page's Tools data.
  - [x] Each new issue should be added as a separate entry to issue #4427 's list of dependencies.
  - New issues to create (**edit as needed**):  
    - [x] #4860 Projects page / current-projects.js
    - [x] #4861 Projects-check page / current-projects-check.js
    - [x] #4859 project.html
    - [x] other (if needed)

### Resources/Instructions

- [How to create issues](https://github.com/hackforla/website/wiki/How-to-create-issues)

**Comment by ronaldpaek** [comment]
1. 4/17-4/18
2. 4/18

**Comment by t-will-gillis** [comment]
Hi @ExperimentsInHonesty -
I moved this to 'In progress (actively working)' and removed the 'ready for dev lead' label: @ronaldpaek finished the preceding issue, and now would like to continue by writing the three new issues for this one.

**Comment by ronaldpaek** [comment]
@t-will-gillis @ExperimentsInHonesty I think I was able to complete this task, where should I move this issue / what column since I don't think I really made any PR's for this, I did update the label though

**Comment by t-will-gillis** [comment]
@ronaldpaek thanks- I linked the three issues to this issue in the comments and added them to the Project Board.

**Comment by ronaldpaek** [comment]
@t-will-gillis should i worry about this?

**Comment by t-will-gillis** [comment]
Closing this issue as completed- next steps are issues #4859, #4860, #4861
