### ISSUE TITLE
Create new issues to refactor Tools data in project md files 

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4777]
### Dependency

- [x] #4525
- [x] #4776
- [x] #4859 
- [x] #4860 
- [x] #4861 

### Overview

As part of the sequence of steps to revise the filters to include a dropdown menu for Tools (issue #4427), ~once the above dependencies are released, we need to create new issues for editing each of the following project .md files in the [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects) folder:~ when the above dependencies are released, move each issue below from the "Ice Box" to "New Issue Approval", remove the `Dependency` label and add `Ready for prioritization` label.

- [x] #4798
- [x] #4799
- [x] #4800
- [x] #4801
- [x] #4802
- [x] #4803
- [x] #4804
- [x] #4805 
- [x] #4806
- [x] #4807
- [x] #4808
- [x] #4809
- [x] #4810
- [x] #4811
- [x] #4812
- [x] #4813
- [x] #4814
- [x] #4913 

### Action Items

- [x] For each of the above issues, click on the target icon that appears to the far right when hovering on the line to "Convert to issue".
- [x] Edit the issue title by prepending `Refactor Tools data for ` in front of current issue title. For example:
  - if the new issue created is called `access-the-data.md` then
  - the new issue title will be `Refactor Tools data for access-the-data.md`
- [x] Add the labels `role: front end`, `role: back end/devOps`, `good first issue`, `size: 0.5pt`, `P-Feature: Project Info and Page`, `P-Feature: Projects page`, `p-feature: Projects-check` 
- [x] Add to the Projects Board in the "Ice Box"
- [x] Add the milestone `03.02 Onboarding flow` <<Confirm
- [x] Use the template below in the body of the new issue. Be sure to replace "PROJECT_NAME" with the correct md file name, and replace "<SHOW_3_BACKTICKS>"  with 3 backticks.

```
### Dependency

- [4777]

### Overview

We need to revise the filter dropdown menu on the [projects-check] page to include a dropdown for Tools, so that we can use this page to see where we might need to move projects values from tools to technologies, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.

### Action Items

- [ ] Refer to the [PROJECT_NAME.md](https://github.com/hackforla/website/blob/gh-pages/_projects/PROJECT_NAME.md) file and find the entry for `tools:`
- [ ] Change the `tools` data from a string into a list: 

`tools: tool_1, tool_2, tool_3`  becomes:
<SHOW_3_BACKTICKS>
tools: 
  - tool_1
  - tool_2
  - tool_3
<SHOW_3_BACKTICKS>
- [ ]  

### Resources/Instructions

- [Homepage](https://www.hackforla.org)
- [Projects](https://www.hackforla.org/projects/) page
- This issue is part of an epic: #4777
```
For Merge Team/Tech Leads/PMs

- [x] Once the PRs for all of the above issues are closed, remove the dependency for this issue on #4427

### Resources/Instructions

- [Homepage](https://www.hackforla.org)
- [Projects](https://www.hackforla.org/projects/) page

**Comment by t-will-gillis** [comment]
I have moved the dependencies for each of the issues that were created to #4427 because when the 18 issues above are completed, opening #4427 is the next step. Therefore, closing this issue as completed.
