### ISSUE TITLE
Refactor Tools data for ems-triage-tracker.md

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4803]
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [ems-triage-tracker.md](https://github.com/hackforla/website/blob/gh-pages/_projects/ems-triage-tracker.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, video production
```
to
```
tools:
  - Figma
  - video production
```
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

**Comment by ivan20203** [comment]
Availability for this week: July 28 - August 4. Timing July 29-30 10am - 3pm PST. Aug 2-4 10am - 3pm PST
My estimated ETA for completing this issue: Aug 1. 10 hours?

**Comment by ivan20203** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?

I onboarded on Tuesday, July 18. Did nothing with this issue until Friday July 28. And have probably spent 3 hours getting to this point.
