### ISSUE TITLE
Epic for writing issues to test GHAs for dependabot proposed updates

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4815]
### Overview
As developers, we want packages/dependencies within our codebase to stay up-to-date with the latest available versions in order to maintain both security and stability; however, we also need ensure that the package version updates do not cause unexpected behavior or otherwise effect the functionality of the site. 

### Background
Our repo's [dependabot](https://github.com/hackforla/website/blob/gh-pages/.github/dependabot.yml) has been identifying the packages/dependencies for which a more recent version is available, and for each it has created a PR detailing which files in our codebase use that package/dependency. We need to check each of these files individually to determine whether we should or should not switch to the latest version. 

### Action Items
This particular batch of dependabot-generated PRs involve package/dependency versions used in YAML files for many of our GitHub Actions. Since some YAML files include references to two or more of the packages/dependencies with available updates, we need to be systematic about testing and implementing (or not) which version updates for which YAML files. Therefore, we need issues created for: 

### Additional Information/ Comments
The following issues already exist for fixing/ checking GHAs, and checks for updating the versions are included:

- [x] #4788 schedule-monthly.yml
  - #4735
    
- [x] #4768 schedule-thu-1100.yml
  - #4735
  - #4739

### Completed  

- [x] pull-request-trigger.yml
  ✅ Updated      #4736

Note: previous issue #4189 issue-trigger.yml closed, replaced with #4822
- [x] #4822 and
        #4933
  ✅ Updated     #4734
  ✅ Updated     #4735
  ✅ Updated     #4737

- [x] #4823 
  ✅ Updated     #4735
  
- [x] #4824 
  ✅ Updated     #4734
  ✅ Updated     #4735
  ✅ Updated     #4736
 
- [x] #4825 
  ✅ Updated      #4734
  ✅ Updated      #4735
   
- [x] #4826 
  ✅ Updated     #4735
   
- [x] #4827 and 
        #4946 
  ✅ Updated      #4734
  ✅ Updated      #4735
 
- [x] #4828
  ✅ Updated      #4734
  ✅ Updated      #4735 

- [x] #4829 
  ✅ Updated     #4735
  
- [x] #4830 and
       #4934
  ✅ Updated     #4734
  ✅ Updated     #4735
  
- [x] #4831 
  ✅ Updated     #4734
  ✅ Updated     #4735

  
### When All Completed
- [x] Gather all automations flagged with ❌ Don't Update and move #4852 into 'New Issue Approval.' Add [ignore statements](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) to the dependabot configuration for each. 

### Resources/Instructions

✅ Updated          Indicates that the version update was tested, confirmed, and merged
❌ Don't Update  Indicates that the version update causes something to break and therefore will NOT be implemented. An [ignore statement](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) will need to be added to the dependabot.

**Comment by t-will-gillis** [comment]
- This issue can be closed.
- Dependabot "ignore" statements are not required for this group.
- Modules in `schedule-monthly.yml` and `schedule-thu-11000.yml` have been updated to the current version. 
- ER #5048 has been opened to determine whether `lint-scss.yml` needs refactoring.
