### ISSUE TITLE
Epic: Update GitHub Action Wiki pages' spreadsheet

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4819]
### Overview
We need to make a list of all the wiki pages that need to be updated, or new ones created for GHAs, so that people making issues and developers can find what they need quickly.

### Details
- We need to ensure that every GitHub Action is documented in the wiki, and add sections to each wiki GHA page, that provide information about relevant issue labels as well as information about dependent packages and instructions on how to test the GHA when dependent packages are updated. 
- Some workflows contain many GitHub actions

### Action Items
- [x] Update the spreadsheet with link to each related GHA wiki page, noting if it's missing in spreadsheet
- [x] Review the issues already mentioned below and update the spreadsheet
- [x] Release the dependency on #6403

#### Workflow file list
- [GitHub Actions](https://github.com/hackforla/website/tree/gh-pages/github-actions)
- [GitHub Workflows](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Wiki for GHAs on websitte team](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)
- [Workflows and GHA wiki Audit](https://docs.google.com/spreadsheets/d/1twpWLg6-EkU1UhIaCMIdE8SuyvTLcyKh16MTtR5awkQ/edit#gid=0) spreadsheet
- https://github.com/hackforla/website/issues/6402

**Comment by MarcosG119** [comment]
Availability:
- Friday 2/29 3pm-6pm
- Saturday 9am-1pm
- Sunday 6pm-9pm
- Monday 3pm-6pm
- Tuesday 6pm-9pm

ETA:
EOD Wednesday 3/6

**Comment by MarcosG119** [comment]
Help Needed:

I believe I've fully updated the spreadsheet, but I'm not 100% sure. I also am not sure how I remove the dependency from the issue, do I just remove the dependency label? Also it seems like for the create issues section it seems those issues have all been created so I'm not sure if I am to take action on those. If someone can provide some clarity it would be greatly appreciated, thank you!

**Comment by ExperimentsInHonesty** [comment]
@MarcosG119 I added the ready for dev lead label and put this in the questions column.  You can always do that if you are unsure of next steps when you have work that you think is ready for review.  If its work that anyone on the team could help you with, you can also post in the slack channel with a link to your issue comment.

**Comment by roslynwythe** [comment]
Hi @MarcosG119 I apologize for the delay in responding.  I noticed two issues with the [spreadsheet](https://docs.google.com/spreadsheets/d/1twpWLg6-EkU1UhIaCMIdE8SuyvTLcyKh16MTtR5awkQ/edit#gid=0):
1) Regarding column D - every script is invoked within at least one workflow (column D), sometimes more (column E).  You can use the GitHub search or any other full-site text search such as VS Code or text editor to find the .yml or .yaml file that references a .js script.  

2) Regarding column F - Please look at each GHA wiki page linked from https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions and enter the URL in the appropriate row in the spreadsheet.   For each GHA wiki page, the name will match either the folder name (which is actuallyor  the name of the "job") or the workflow name in one or more rows.  For Rows 2-4 you should find GHA wiki pages with titles that match the folder name in column B.  For rows 5-8, fill in the URL of the wiki page [GHA: issue trigger](https://github.com/hackforla/website/wiki/GHA:-issue-trigger), since that title matches the name of the workflow for those rows. In all cases where a GHA wiki page is found that matches either the name of the folder or workflow, we will update the page, so please check the checkbox in column H.  However for row 13, I don't think we have a GHA wiki page so leave column F blank and check the checkbox in column G.  For rows 14 - 19 there may not be GHA wiki pages so leave column F blank and check the checkbox in G.

**Comment by roslynwythe** [comment]
@MarcosG119 Regarding your question about the issues:
- The URL for #5166 can be populated in column I for all the rows with workflow "issue trigger".  
- The URL for #4856 can be populated in column I for row 10
- The URL for #6399 can be populated in column I for row 13

Regarding the third action item, I will release the dependency when this issue is closed.  Thanks!

**Comment by MarcosG119** [comment]
@roslynwythe thank you for getting back to me!

> Regarding column D - every script is invoked within at least one workflow (column D), sometimes more (column E). You 
> can use the GitHub search or any other full-site text search such as VS Code or text editor to find the .yml or .yaml file that > references a .js script.

Ok I see now the util functions are used by other functions that are used in by yml files, none of the util functions are called directly in any ymls from what I can find. I have updated the workflows to be what workflows each utils script ends up getting used in by some function not in utils.

I have updated the rest of the columns per your comments. Please let me know if there's anything else I must complete!

**Comment by roslynwythe** [comment]
@MarcosG119 Great job, thank you for completing this spreadsheet.  It will help us to organize issues to document the workflows and jobs.
