### ISSUE TITLE
Verify dependabot version updates to GHAs for schedule-daily-1100.yml

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4826]
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.
### Overview
Our repo's [dependabot](https://github.com/hackforla/website/blob/gh-pages/.github/dependabot.yml) has been identifying the packages/dependencies for which a more recent version is available, and for each it has created a PR detailing which files in our codebase use that package/dependency. We need to check each of these files individually to determine whether we should or should not switch to the latest version. 
### Action Items
Refer to the [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) file and review with the version updates recommended by the dependabot.
Select:
  - [x] PASSES TEST #4735 \`uses: actions/checkout@v2\` with \`uses: actions/checkout@v3\`
Or:
  - [ ] FAILS: #4735. Do not update.

Merge team:
- [x] Transfer results to #4815
### Resources/Instructions
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
