### ISSUE TITLE
ER: Update Project Profile: Lucky Parking

### ISSUE THREAD

**Issue by dannycpham** [hackforla/website#4909]
### Dependency (Issues that need to be completed in order to close this ER and complete these [action items](https://github.com/hackforla/website/issues/4909#issuecomment-1793873563))
- [x] #5790 
- [x] #5809
- [x] #5791 
- [x] #5796
- [x] #5797 
- [x] #5798
- [x] #5799 
- [x] #5800
- [x] #5801 
- [x] #5802
- [x] #5803
- [x] #5804  
- [x] #5805
- [x] #5806
- [x] #5807 
- [x] #5808
- [x] #5792 

### Project Name

Lucky Parking

### Project Card URL

lucky-parking.md

### Update the Technologies?

YES

### Technologies

- [x] React, TailwindCSS, Mapbox, Node.js, Express, MongoDB, AWS, Markdown

### Update the Partner(s)?

YES

### Partners

- [x] Atwater Village
  - See https://github.com/hackforla/website/issues/4909#issuecomment-1707100068 and #5098 

### Update the Tools?

YES

### Tools

- [x] pnpm, GitHub, Storybook, Google Colab

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Yuting Chu
- [x] Name: Arpita Pandya
- [x] Name: Diedrich Chavarria
- [x] Name: Jodie Chen
- [x] Name: Sijia Pitts
- [x] Name: Yujin Chang
- [x] Name: Sam Sengupta
- [x] Name: David Lam
- [x] Name: Carlos Olivas
- [x] Name: Pratibha Shivanand
- [x] Name: Aletia Trepte
- [x] Name: Yen Phan
- [x] Name: Yao Guan

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Danny Pham
GitHub Handle: dannycpham
Role: Product Manager Lead
Slack Member ID: U041DP398GH

**Comment by ExperimentsInHonesty** [comment]
On issue #4151 @Josiah-O will reach out to 
Seymour and Danny Pham in the team channel pointing out that they currently have an open issue to update the Lucky Parking teams info on the website and it does not reference Atwater Village as a partner.  Do they want that added?

**Comment by dannycpham** [comment]
@ExperimentsInHonesty @Josiah-O 

Following up on this ticket. 

We have confirmed that we can add in Atwater Village as a partner on July 24th on slack, and have received no additional updates regarding this issue to update the Lucky Parking page.

**Comment by dannycpham** [comment]
@ExperimentsInHonesty @Josiah-O 

I am now doing a second follow up. I have confirmed on July 24th on slack that we can add Atwater Village to the Lucky Parking Page. I have since requested a follow up on September 5th with no response as well.

Please advise.

**Comment by JessicaLucindaCheng** [comment]
@dannycpham Sorry for the delay in getting back to you. I will start writing issues so your requested changes can be implemented.

**Comment by JessicaLucindaCheng** [comment]
### Issue Writing
- Availability: 6 hours
- ETA: Sunday, October 29, 2023 for writing all the issues

**Comment by JessicaLucindaCheng** [comment]
```
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [ ] In your IDE, open the `_projects/lucky-parking.md` file
- [ ] Observe the existing syntax of the front matter block [^1] in the file
- [ ] [INSERT relevant action items. See the rest of the guide for action items to add here.]
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] Lucky Parking page [^2]
  - [ ] the project's card on the Projects' page [^3]   [If the ONLY changes are for the `leadership` variable, REMOVE this action item to check the project's card.]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column, add a **ready for dev lead** label to it, and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #[Insert ER number]
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
[^3]: Projects page URL: https://www.hackforla.org/projects/ [If the ONLY changes are for the `leadership` variable, REMOVE this resource to the Projects page.]
```

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty The request asks for one of the "Tools" to be listed as `Jupyter Notebook`. However, this already shows up in the "Languages" for Lucky Parking. Is it okay if I omit `Jupyter Notebook` from "Tools"?

**Comment by JessicaLucindaCheng** [comment]
```
Update Project Profile: Lucky Parking (Remove)
```

```
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [ ] In your IDE, open the `_projects/lucky-parking.md` file
- [ ] Observe the existing syntax of the front matter block [^1] in the file
- [ ] Find the `leadership` variable and remove the following:
```
[Insert the lines of code to remove the specified leadership member]
```
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] Lucky Parking page [^2]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column, add a **ready for dev lead** label to it, and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
```

**Comment by JessicaLucindaCheng** [comment]
All the issues have been written and linked in the Dependency section for this issue.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng 

> @ExperimentsInHonesty The request asks for one of the "Tools" to be listed as Jupyter Notebook. However, this already shows up in the "Languages" for Lucky Parking. Is it okay if I omit Jupyter Notebook from "Tools"?

- Yes, we should omit it from tools if it does show up under languages. I'll update #5791

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng I think I'm done with this issue.  Not sure what is next.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issues in the Dependency section have been merged, please contact the person who opened this ER to approve the changes on the [Lucky Parking page](https://www.hackforla.org/projects/lucky-parking).

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty
> @JessicaLucindaCheng I think I'm done with this issue. Not sure what is next.

I moved this issue with a **Dependency** label to the **Ice Box** column. Also, I will leave a comment for the dev lead for next steps once all the issues in the dependency are completed.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issues in the Dependency section have been merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the person who opened this ER to approve the changes on the [Lucky Parking](https://www.hackforla.org/projects/lucky-parking) and add a `ready for stakeholder` label
- [x] Once the changes have been accepted by the person who opened this ER, remove the `ready for stakeholder` label and add the `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by roslynwythe** [comment]
@dannycpham Please review the changes on [Lucky Parking](https://www.hackforla.org/projects/lucky-parking)

**Comment by JessicaLucindaCheng** [comment]
@dannycpham 
Please let us know if the changes made to the [Lucky Parking](https://www.hackforla.org/projects/lucky-parking) page match what you requested by adding a comment to this issue. Thank you.

Edit: Left a Slack message about this on February 4, 2024 as well: https://hackforla.slack.com/archives/CPFDMSV6V/p1707059568485369

**Comment by dannycpham** [comment]
@JessicaLucindaCheng The changes look good.

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.
