### ISSUE TITLE
Epic: Create Issues to audit codebase for img tags ending with a slash

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4922]
### Overview
We want to change each img HTML tag ending with a slash (<img.../>) in the HfLA codebase to an img tag without an ending slash (<img...>).   An issue template and instructions will be prepared, in order to facilitate the creation of issues for performing the audit across the entire codebase.  Each new issue will audit a single file and results will be stored in the HfLA-Website: img Tag Audit spreadsheet. 

### Action Items
- [x] Make an issue template to audit, find, and document instance of `<img.../>` in each file in the HfLA-Website: img Tag Audit spreadsheet[^1]
   - [x] This issue template will include a "Complexity: Small" label and a "ready for dev lead" label along with all the other needed labels.
- [x] Review and (if needed) edit the following in the HfLA-Website: img Tag Audit spreadsheet: 
  - [x] "Instructions for Page Audit Issue Writers" section on the Instructions tab [^1]
  - [x] Page Audit tab [^2]. All the files that still need to be audited are already listed in the Page Audit tab.
  - [x] img with Ending Slash tab [^3]. This tab contains the lines of code with <img.../> that have been found so far. This tab will also be where developers auditing the files add their findings.
- [x] Use the template to make one issue as an example
- [x] Get approval from a PM on the template. 

### Resources/Instructions
[^1]: [HfLA-Website: img Tag Audit spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1822415835)
[^2]: HfLA-Website: img Tag Audit spreadsheet's [Page Audit tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1277680545&fvid=1305214134)
[^3]: HfLA-Website: img Tag Audit spreadsheet's [img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0&fvid=959329398)
[^4]: Issue Template 1: [img Tag Refactor on Website](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&template=img-tag-refactor-on-website.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page%28s%29) and its associated Markdown file [.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md). This template works for any pages that is marked with `Template 1` in the `Template to use if <img.../> found` column on the `Page Audit` tab . Template 1 works if the img tag is on the website.

- This epic resulted from #4362

**Comment by roslynwythe** [comment]
- Here is the issue to create the audit issues #4951

**Comment by roslynwythe** [comment]
# Issue Template
```
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.  In this issue we will audit a single code file for all instances of img HTML tags ending with a slash, and will record each instance found in a spreadsheet.  

### Action Items
- [ ] Open the sheet HfLA-Website: img Tag Audit spreadsheet[^1]
- [ ] In your local IDE, navigate to Resource[^2]
- [ ] Audit Resource[^2] to find any and all instances of img HTML tags ending with a slash (<img.../>) 
- [ ] For each instance found in Resource[^2], create a new row in the `img with Ending Slash` sheet
   - [ ] Enter **[REPLACE WITH FILE PATH]** into the `Path to file` column of the spreadsheet
   - [ ] Copy the img tag (with brackets) into the `Line of Current Code` column
   - [ ] Copy the img tag (with brackets) into the `Desired Line of Code` column but remove the trailing slash and any blank spaces before the closing bracket (>)
- [ ] After all instances have been recorded in the sheet, add the `ready for dev lead` label to this issue and move it to the `Questions/In Review column`

### For merge team/dev lead
- [ ] After reviewing the issue
   - [ ] Remove the `ready for dev lead` label and close the issue.  
   - [ ] Copy the issue number, then find the corresponding item in the Dependencies section of Epic #4922.  Replace the current text with `#[ISSUE NUMBER]`
  
### Resources/Instructions
[^1]: [HfLA-Website: img Tag Audit (Roll out plan #4362)](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0)
[^2]: **[REPLACE WITH FILE PATH]**

[^3]: [`DR: img tag` documentation comment](https://github.com/hackforla/website/issues/4363#issuecomment-1493176038)

This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0) and resulted from Epic #4922 and Rollout #4362
```

**Comment by LRenDO** [comment]
Hi @roslynwythe! Looks like all of the dependencies have been completed for this task. In the case of epics, should they be closed or moved to a review column once the dependencies are completed?

**Comment by LRenDO** [comment]
Closing this epic as all Audit issues are complete.

**Comment by ExperimentsInHonesty** [comment]
This issue is being reopened, we need to do another audit on the pages that show up on this code search
[repo:hackforla/website /> NOT language:SVG](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%2F%3E+NOT+language%3ASVG&type=code&p=2)
