### ISSUE TITLE
Epic: Create Issues for removing closing slash from img tags

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5040]
### Dependency

Epic for img tag auditing
- [ ] #4922 

Issues for removing closing slash:
- [x] #5187
- [x] #5619
- [x] #5620
- [x] #5621
- [x] #5265
- [x] #5439
- [x] #5266
- [x] #5267
- [x] #5255 
- [x] #5256
- [x] #5199
- [x] #5200
- [x] #5188
- [x] #5189 
- [x] #5197
- [x] #5198 
- [x] #5171 
- [x] #5172 
- [x] #5173 
- [x] #5174 
- [x] #5175 
- [x] #5176 
- [x] #5177 
- [x] #5178 
- [x] #5179 
- [x] #5140
- [x] #5138
- [x] #5139
- [x] #5136
- [x] #5137
- [x] #4366
- [x] #4375 
- [x] #4376 
- [x] #4377 
- [x] #4378 
- [x] #4379 
- [x] #4380 
- [x] #4381 
- [x] #4382 
- [x] #4383 
- [x] #4393 
- [x] #4394 
- [x] #4395 
- [x] #4396 
- [x] #4397 
- [x] #4398 
- [x] #4399 
- [x] #4400 
- [x] #4401 
- [x] #4413
- [x] #4414
- [x] #4415 
- [x] #4416 
- [x] #4417 
- [x] #4418 
- [x] #4419 
- [x] #4420 
- [x] #5101
- [x] #5041
- [x] #5042
- [x] #5032
- [x] #5031
- [x] #5030 
- [x] #5029 
- [x] #5148 

### Overview

We need to prepare the template and instructions for the issues that will remove the closing slash from img tags that have been audited in the HfLA-Website: img Tag Audit spreadsheet[^1]

### Action Items

- [x] Prepare issue templates
  - [x] modify [img Tag Refactor](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&template=img-tag-refactor-on-website.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page%28s%29) as needed.  - ** See [comment ](https://github.com/hackforla/website/issues/5040#issuecomment-1643475170) below.  The original template has been modified with the addition of an action item displayed in bold.  
  - [x] issue template for updates to CONTRIBUTING.md is slightly differet, see https://github.com/hackforla/website/issues/5040#issuecomment-1650570533 below
- [x] Review and (if needed) edit the following in the HfLA-Website: img Tag Audit spreadsheet: 
  - [x] The "Instructions for img with Ending Slash Issue Writers" section on the Instructions tab [^1]
  - [x] Add additional sections or instructions as needed to the Instructions tab if needed

- [x] Get approval from a PM on the template(s).

### 2B: Good first issue writing session
- After approval is given, ask a dev lead (a Merge Team member or Technical Lead) if you can do an issue writing session (or more than one session) during one of the meetings so that other developers on the team can help with writing the issues using the template(s).

### Resources/Instructions
- This epic resulted from #4362

[^1]: [HfLA-Website: img Tag Audit spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1822415835)
[^2]: HfLA-Website: img Tag Audit spreadsheet's [Page Audit tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=1277680545&fvid=1305214134)
[^3]: HfLA-Website: img Tag Audit spreadsheet's [img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0&fvid=959329398)
[^4]: Issue Template 1: [img Tag Refactor on Website](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Refactor+HTML%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&template=img-tag-refactor-on-website.md&title=img+Tag+Refactor%3A+%5BINSERT+PAGE+HERE%5D+page%28s%29) and its associated Markdown file [.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/img-tag-refactor-on-website.md). This template works for any pages that is marked with `Template 1` in the `Template to use if <img.../> found` column on the `Page Audit` tab . Template 1 works if the img tag is on the website.

**Comment by roslynwythe** [comment]
### Issue Template for updates to HTML and JavaScript files

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [ ] In your local IDE, navigate to `[INSERT PATH TO FILE HERE]`
- [ ] Remove the ending slash in the img HTML tag by changing
```
[INSERT LINE OF CURRENT CODE HERE]
```
to
```
[INSERT DESIRED LINE OF CODE HERE]
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 1 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5040

### Resources/Instructions
1. Webpage(s): [INSERT LINK TO PAGE ON WEBSITE HERE]
2. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty since there was an urgent need for good first issues, I self-assigned it and started creating the issues before this Epic was approved.  There was only one change to the previously approved template, the addition of this Action Item:

**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**

**Comment by roslynwythe** [comment]
### Issue Template for updates to CONTRIBUTING.md

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [ ] In your local IDE, open the file `CONTRIBUTING.md`
- [ ] In Section `[INSERT SECTION NUMBER]` change
```
[INSERT LINE OF CURRENT CODE HERE]
```
to
```
[INSERT DESIRED LINE OF CODE HERE]
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.** 
- [ ] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL (also store the test URL for use in a later step)
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md)
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.  
```
For Reviewers: Do not test changes locally, rather test changes at [REPLACE WITH TEST URL]
```

### Merge Team
- [ ] After closing this issue, check off the dependency in #6453.  If all dependecies have been completed, close #6453 and check off its dependency in #4362.  If all dependencies have been completed in #4362, close it.  

### Resources/Instructions
1. Webpage(s): https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
2. This issue is part of #6453

**Comment by nitin-pandita** [comment]
@roslynwythe is this issue for contribution

**Comment by ExperimentsInHonesty** [comment]
- We reopened this issue because there are still ending slashes on image tags.  See issue https://github.com/hackforla/website/issues/4922#issuecomment-2484517024
