### ISSUE TITLE
Epic: Create issues to resolve CodeQL alerts 1- 24, 98 "Potentially unsafe external link"

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5129]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve CodeQL code alerts 1 - 24 of type `Potentially unsafe external link`.

### Dependencies (child issues - this issue will remain open until all these issues are completed)
- [x] #5673
- [x] #5674
- [x] #6043
- [x] #6226
- [x] #6227
- [x] #6044
- [x] #6045
- [x] #6046
- [x] #6047
- [x] #6048
- [x] #6049
- [x] #6050
- [x] #6051
- [x] #6052
- [x] #6053
- [x] #6054
- [x] #6230
- [x] #6231
- [x] #6309 
##### These address instances which were not flagged by CodeQL:
- [ ] Resolve `Potentially unsafe external link` (1) not flagged in `about-card-sponsors.html`
- [ ] Resolve `Potentially unsafe external link` (2) not flagged in `about-card-sponsors.html`
- [ ] Resolve `Potentially unsafe external link` (3) not flagged in `about-card-sponsors.html`
- [x] #6484

### Action Items
- [x] Determine whether to dismiss the alerts or to update the code
- [x] Develop a template for issues that will update the code to resolve the alerts see https://github.com/hackforla/website/issues/5129#issuecomment-1751951517
- [x] create sample issue - #5673 
- [ ] For each alert listed above, create an issue using this [template](https://github.com/hackforla/website/issues/5129#issuecomment-1751951517)
- [ ] Once each issue is created, replace the text above with a link to the issue
- [ ] Create issues to handle three additional links in includes/about-page/about-card-sponsors.html that use target=_blank that are not flagged by CodeQL.  Modify the template as needed.

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty this is the sample issue created from #5060 and if you won't mind I would like to complete the issue.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I have move this to in progress so that you can work on it.

**Comment by roslynwythe** [comment]
For all instances of the "Potentially unsafe external link" alert, I recommend code changes based on the CodeQL recommendation, which is to add the attribute rel="noopener noreferrer".

**Comment by roslynwythe** [comment]
Going forward we will not require a spreadsheet to map issues and alerts because GitHub will perform the tracking when an alert url is found in a task list item.  Updating issue templates accordingly and changing Complexity to issue making level 2.

**Comment by roslynwythe** [comment]
### Issue Template for resolving alerts 1 - 24 "Potentially unsafe external link"

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the alert "Potentially unsafe external link" which appears in the CodeQL [alert INSERT-ALERT-ID](https://github.com/hackforla/website/security/code-scanning/INSERT-ALERT-ID) by adding the attribute `rel="noopener noreferrer"`

### Action Items
- [ ] The following item is required for GitHub to establish tracking between this issue and the alert.  No action is required.  You may simply check the checkbox.  If you do follow the link to learn more about CodeQL alerts, DO NOT DISMISS THE ALERT.  
- [ ] https://github.com/hackforla/website/security/code-scanning/INSERT-ALERT-ID
- [ ] Open the file `INSERT-FILE-PATH` in your IDE
- [ ] Replace
```

```
with
```

```
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5129
  
### Resources/Instructions
1. [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
2. Webpage(s): INSERT-WEBPAGE-URL
3. This issue is part of #5129

**Comment by t-will-gillis** [comment]
Hi @roslynwythe please see this comment from https://github.com/hackforla/website/pull/5961#pullrequestreview-1769209863 There are three additional links in `includes/about-page/about-card-sponsors.html` that use `target=_blank` that are not flagged by CodeQL.

**Comment by roslynwythe** [comment]
Hi @t-will-gillis you are correct; I wonder why CodeQL didn't generate alerts for those instances.  In any case, I added an Action Item above to create issues for those instances.  Thanks!

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty A number of CodeQL alerts were found in `_layouts/guides.html` which is not currently is use and may be difficult to test.  `_layouts/guides.hml` was developed https://github.com/hackforla/website/pull/3548 but never specified as a template in _config.yml

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 13, 2024 at 12:14 PM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 27, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 3, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 10, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 17, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 8, 2024 at 12:05 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 15, 2024 at 12:04 AM PST.</sub>
