### ISSUE TITLE
ER: Inactive Members, Add'l Revs to GHAs "Schedule Thursday 1100" and "Schedule Monthly"

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5163]
### Emergent Requirement - Problem
Issue #4768 via PR #5158 fixes the bug in a previous GHA. This action finds inactive (i.e. non-contributing) members and automatically removes them from the 'website-write' team. Additional features/functionalities either need to be added to, or run in tandem with, this GHA. These are listed below.

### Issue you discovered this emergent requirement in
- #4768 
- #4788 
- #4541 

### Date discovered 
8/7/23

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@t-will-gillis 

### Recommended Action Items
- [X] Make new issues
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Additional functionalities needed

- [x] **_DONE_** See #6399 ~When the PR for #4768  is merged, create new issue to add or change the description of this GHA to the wiki. Please refer to [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) for instructions about where to place "Content to be Added/Edited in the New website-wiki Repo."~
- [x] DONE See #6399 ~see also #4819~
- [x] **_DONE_** ~Members who are placed on the one-month-inactive list need to be notified so that they can let us know if they want to continue on the 'website-write' team. Bonnie has written a [draft message here](https://github.com/hackforla/website/issues/4768#issuecomment-1648812159).~
- [x] **_DONE_** ~The previous GHA is saved as `schedule-monthly-PREV.yml`. This action was not working but its intent was to gather a list of inactive members and then create an issue on the Project Board for the leads to follow up with. Some of this code may be useful. We need to determine if any of this code should be refactored, and then remove the rest. Re: #4788~

**Comment by t-will-gillis** [comment]
PR #5158 fixes #4768 merged- This issue and PR takes care of the additional fixes and functionalities referenced by the ER

**Comment by t-will-gillis** [comment]
Issue #6399 created to address the final, outstanding item to address this ER- namely to update the Wiki pages to accurately detail the `schedule-monthly.yml` GHA and correct or remove incorrect documentation.
