### ISSUE TITLE
Epic: Process results of sitewide spell check and preparing cspell configuration file

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5244]
### Dependencies
- [ ] #5248

### Overview
Code Spell Checker in VSCode flags a large number of words, most of which are not misspellings but rather abbreviations and HfLA-specific terms that should be specified as valid words in the Code Spell Checker configuration file.  We will build a configuration file that specifies which files and words should be excluded from spell checking, and we also need to fix misspelled words.  

### Action Items
- [ ] Create issue #5248
   - Create a row for each file (html, md, json, yaml) file that contains text for display on the website and is appropriate to include in the Code Spell Check, in the HfLA spelling audit spreadsheet[^1]
  - To exclude files from spell checking, use the setting `cSpell:ignore` in `cspell.json`
  - [ ] Create Epic for creating auditing issues
   -  Each issue will cover one file.  
   - The issue will require that for each word flagged as an error, if the word is actually misspelled, a row is populated in the "misspelled words" sheet.  If it is a false positive, the word should be listed in the "whitelist words" sheet, if it is not already listed.  
- [ ] Create Epic for fixing misspellings
- [ ] Create Epic for adding false positives to spell checker configuration file

### Resources/Instructions
- ? part of #4349
[^1]:[HfLA spelling audit spreadsheet](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1277680545)

**Comment by roslynwythe** [comment]
CLosed as not planned.  The planned child issues were listed in https://github.com/hackforla/website/issues/4349#issuecomment-1676490798

**Comment by roslynwythe** [comment]
- Closed as not planned.  See #5312.
