### ISSUE TITLE
Epic: Create template, spreadsheet and list of issues for spellcheck audit

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5248]
### Dependency
- [x] #5311
- [x] #5514
- [x] #5515
- [x] #5516
- [x] #5517
- [x] #5518
- [x] #5519
- [x] #5520
- [x] #5524
- [x] #5525
- [x] #5526
- [x] #5527
- [x] #5527
- [x] #5528
- [x] #5529
- [x] #5530
- [x] #5531
- [x] #5532
- [x] #5533
- [x] #5594
- [x] #5595
- [x] #5596
- [x] #5597
- [x] #5598
- [x] #5599
- [x] #5600
- [x] #5602
- [x] #5603
- [x] #5604
- [x] #5735
- [x] #5736
- [x] #5737
- [x] #5738
- [x] #5739
- [x] #5981
- [x] #5982
- [x] #5983
- [x] #5984
- [x] #5985
- [x] #5986
- [x] #5987
- [x] #5988
- [x] #5989
- [x] #5990
- [x] #5991
- [x] #5992
- [x] #5993
- [x] #5994
- [x] #5995
- [x] #5996
- [x] #5997
- [x] #5998
- [x] #6086
- [x] #6087
- [x] #6088
- [x] #6089
- [x] #6090
- [x] #6091
- [x] #6092
- [x] #6093
- [x] #6094
- [x] #6095
- [x] #6096
- [x] #6097
- [x] #6487
- [x] #6488
- [x] #6489
- [x] #6490
- [x] #6491
- [x] #6492
- [x] #6493
- [x] #6494
- [x] #6495
- [x] #6496
- [x] #6497
- [x] #6498
- [x] #6569
- [x] #6570
- [x] #6571
- [x] #6572
- [x] #6573
- [x] #6574
- [x] #6575
- [x] #6576
- [x] #6577
- [x] #6578
- [x] #6585
- [x] #6590
- [x] #6591
- [x] #6592
- [x] #6593
- [x] #6594
- [x] #6750 
- [x] #6751 
- [x] #6752
- [x] #6753 
- [x] #6754 
- [x] #6755 
- [x] #6756 
- [x] #6757
- [x] #6758
- [x] #7142
- [x] #7143
- [x] #7144
- [x] #7145
- [x] #7146
- [x] #7147
- [x] #7148
- [x] #7149
- [x] #7386
- [x] #7387
- [x] #7388
- [x] #7389
- [x] #7390
- [x] #7391
- [x] #7392
- [x] #7393
- [x] #7394 
- [x] #7395 
- [x] #7396 
- [x] #7397 
- [x] #7398 
- [x] #7399 
- [x] #7400
- [x] #7448
- [x] #7449
- [x] #7450
- [x] #7451
- [x] #7452
- [x] #7453
- [x] #7454
- [x] #7455
- [x] #7456
- [x] #7609
- [x] #7610
- [x] #7611
- [x] #7612
- [x] #7613
- [x] #7783
- [x] #7784 
- [x] #7785 
- [x] #7786 
- [x] #7787 
- [x] #7788 
- [x] #7789 
- [ ] #7804 
- [ ] #7805 
- [ ] #7806 
- [x] #7807 
- [ ] #7808 
- [ ] #7809 
- [ ] #7810 
- [ ] #7811 
- [ ] #7812 

**Note: some spellcheck issues are not listed above - see the Issue Making Level 1 issues below**

### Dependencies/ Issue Making Level 1 issues 
   - [x] #6499
   - [x] #6541
   - [x] #6679
   - [x] #6871
   - [x] #7165
   - [x] #7166 
   - [x] #7167 
   - [x] #7587
   - [x] #7168 

### Overview
We need to create issues to audit all appropriate codebase files for Code Spell Checker results.  The HfLA spelling audit spreadsheet[^1] will be used to track spell check audit issues, record false positives and misspellings, and track resulting issues for resolving errors.  

### Action Items
- [x] Create HfLA spelling audit spreadsheet[^1] 
  - [x] List files we wish to spell check in `Page Audit` sheet
  - [x] List excluded files/paths in `Excluded Paths` sheet  
- [x] Create an issue template for spell checking (Small)   - see https://github.com/hackforla/website/issues/5248#issuecomment-1685247438
- [x] Create GitHub issue template - #5540
- [x] sample issue #5311
  - Dev will install cSpell and will check the specified page
  - Errors will be recorded and categorized as `misspellings` or `false positives`
- [ ] Create Issue Making Level 1 issues to create issues and list above
 

### Resources/Instructions
- This issue is part of #4349
[^1]:[HfLA spelling audit spreadsheet](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1277680545)

**Comment by Gourav2609** [comment]
hello @roslynwythe  , i am interested to contribute to Hack for LA's website....can u please let me know how can i ...

**Comment by roslynwythe** [comment]
Hi @Gourav2609 you will have to become a member of Hack for LA, but you don't have to live in LA.  See https://www.hackforla.org/join

**Comment by roslynwythe** [comment]
### Draft Audit Issue Template
Title: Run VSCode Spell Checker on [INSERT FILE PATH]
```
### Overview
We need to audit HfLA codebase files for spelling errors using the VSCode Code Spell Checker extension in order to ensure site quality.  Results will be categorized as misspellings, false positives in the HfLA spelling audit spreadsheet[^1] and will be resolved in later issues.  

### Action Items
- [ ] You must use VS Code as your local text editor and install the `Code Spell Checker` VS Code extension[^2]  
- [ ] Do not change any configuration settings or make any spell corrections
- [ ] Open the file '[INSERT FILE PATH]'and note any Code Spell Checker errors
- [ ] Locate the file in column A ("File") of the "Page Audit" sheet.  In the column labelled "Result Summary", select the appropriate option:  `No errors` or `At least one error`.  
- [ ] If at least one error was reported, copy/paste each cSpell message into a separate row in the `Results` sheet
- [ ] In each new row, select the appropriate value: `misspelling` or `false positive` from the "Result type" column.  A false positive is a term that is not a misspelling, but it is not recognized by the spell checker because it is a technical term, abbreviation, acronym, URL or proper noun (name of a person, place or organization).  
- [ ] Move this issue to the Questions/In Review column and apply the label 'ready for dev lead`

### Merge Team
- [ ] After this issue is closed, release the dependency on this issue in #5248
- [ ] After the last dependency has been released, close that issue. 

### Resources/Instructions
- This issue is part of #5248
[^1]: [HfLA spelling audit spreadsheet - Results](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048)
[^2]:The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). 
```

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty I created a dozen new auditing issues and there are almost 100 files remaining for which to write auditing issues.  I wrote a level 1 issue making issue - please see #6499.  If you approve of it, I will write more level 1 issue making issues.  How many issues do you think each issue making issue should create?  And regarding #6499, I'm not sure about the title or labels; should it have an epic title/label?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe 10 issues per issue making, sounds good and the merge team lead who signsoff should add the child issues to this epic.

See this screenshot for labels I choose
![image](https://github.com/hackforla/website/assets/37763229/f66b2728-07c4-487d-8017-0a4501107104)

**Comment by ExperimentsInHonesty** [comment]
- @roslynwythe I see the issue https://github.com/hackforla/website/issues/6871 but I don't see a template issue for creating the rest of the 
"Create spellcheck audit issues from line xxx-xxx of spreadsheet" issues.  If there isin't one, we should make one, and add it and the list of these issues that still need to be created, to the top of this issue.  Unless those instruction are in some other issue that I can't find.

### Issues to create
- [ ] Create spellcheck audit issues from line 126-132 of spreadsheet
- [ ] Create spellcheck audit issues from line 133-139 of spreadsheet
- [ ] Create spellcheck audit issues from line 140-147 of spreadsheet
- [ ] Create spellcheck audit issues from line 148-154 of spreadsheet
- [ ] Create spellcheck audit issues from line 155-162 of spreadsheet
- [ ] Create spellcheck audit issues from line 163-169 of spreadsheet
- [ ] Create spellcheck audit issues from line 170-177 of spreadsheet
- [ ] Create spellcheck audit issues from line 178-184 of spreadsheet
- [ ] Create spellcheck audit issues from line 185-192 of spreadsheet

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 13, 2024 at 12:14 PM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 27, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 3, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 10, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 17, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 8, 2024 at 12:05 AM PST.</sub>

**Comment by ExperimentsInHonesty** [comment]
@essencegoff remove the extra mention of the issue on the results page if it appears on the audit page

**Comment by HackforLABot** [comment]
Hello @essencegoff, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by HackforLABot** [comment]
Hi @essencegoff, HfLA appreciates your interest in this issue, but please note that it is in the  **"New Issue Approval"**  column of the Project Board because it has not been finalized, approved, or prioritized, and so it is not ready for assignment. For this reason, you have been unassigned from this issue. Please remember to assign issues only from the  **"Prioritized Backlog"**  column.  

The only exceptions to this rule are if you are writing an issue and the `Draft` label is applied, or if you are self-assigning to your "Pre-work Checklist" (the issue includes the `Complexity: Prework` label).

**Comment by HackforLABot** [comment]
Hello @essencegoff, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by HackforLABot** [comment]
Hi @essencegoff, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by HackforLABot** [comment]
@roslynwythe, @essencegoff

Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 22, 2024 at 12:04 AM PST.</sub>
