### ISSUE TITLE
Epic: Create Issues to Fix HTML linter errors

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5279]
### Overview
As developers we need to update HTML markup to address HTML linter errors as recorded in the HfLA HTML linter audit spreadsheet[^1]

### Issues to fix HTML linter errors
- [x] #5288
- [x] #5287
- [x] #5286
- [x] #5285
- [x] #5281
- [x] #5317
- [x] #5318
- [x] #5319
- [x] #5365
- [x] #5371
- [x] #5368
- [x] #5369
- [x] #5367
- [x] #5370
- [x] #5372
- [x] #5373
- [x] #5366
- [x] #5711 
- [x] #5710 

### Action Items
- [x] Create a template for updating HTML markup as per the recommendation recorded in the HfLA HTML linter audit spreadsheet
- [x] Create a sample issue - see #5281
- [x] For each row in the HfLA HTML linter audit spreadsheet[^1], create an issue and add link to "Issue to fix HTML linter errors" section above

### Resources/Instructions
- This issue is part of #5277
[^1]:[HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0)

**Comment by roslynwythe** [comment]
### Template
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [ ] In your local IDE, navigate to `_layouts/project.html`
- [ ] Remove the ending slash in the img HTML tag by changing
```
<img class='leader-img' src='{{ item.picture }}' />
```
to
```
<img class='leader-img' src='{{ item.picture }}'>
```
- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5040

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html
2. Webpage(s): https://www.hackforla.org/projects, https://www.hackforla.org/projects-check/
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

**Comment by roslynwythe** [comment]
### Template "Refactor HTML to resolve linter error"

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "[REPLACE WITH LINTER ERROR MESSAGE]"

### Action Items
- [ ] In your local IDE, navigate to `[REPLACE WITH FILE]`
- [ ] Change the line of code
```

```
to
```

```
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: [REPLACE WITH GITHUB URL]
2. Webpage(s): [REPLACE WITH WEBSITE URL]
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I changed the instructions on the last open issue to leave you a comment on this issue.  So I expect someone will pick up that issue soon.  In the meantime this is inprogress.

**Comment by freaky4wrld** [comment]
@roslynwythe , @LRenDO has confirmed that there are two open issues that were not listed in the epic here, and are now added

**Comment by LRenDO** [comment]
Hi @freaky4wrld and @roslynwythe! I did a search for open issues "Refactor HTML" that may have been missed or not listed yet in the epic and there are two that are still open. I have added them to the list.

**Comment by freaky4wrld** [comment]
@LRenDO thanks for clearing out, should I delete the comment?

**Comment by LRenDO** [comment]
@freaky4wrld I would just add an edit note in the comment if you want to update it.

**Comment by nelsonuprety1** [comment]
Please check #6409 which fixes this issue.

**Comment by t-will-gillis** [comment]
Hi @roslynwythe FYI it appears that the final issue of this epic is merged.

**Comment by t-will-gillis** [comment]
@roslynwythe Closing this as 'Completed'
