### ISSUE TITLE
Epic: Create issues to add false positives to cspell.json

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5312]
### Dependencies
- [x] #5313
- [ ] #5248 ready for implementation

### Overview
We need to create issues to update the Code Spell Checker configuration file with false positives so that they are no longer marked as errors.  The list of false positives can be found in the HfLA spelling audit spreadsheet[^1] and that sheet will be used for tracking issues as well.  

### Action Items
- [x] Create template for issues to add false positives to cspell.json - see https://github.com/hackforla/website/issues/5312#issuecomment-1736440177
- [x] labels: good first issue, Feature: Infrastructure, role: front end, role: back end/devOps
- [x] create sample issue #5618
- [ ] Decide how to handle the names of individuals.  
- [ ] Create issues to add false positives to cspell.json

### Resources/Instructions
- This issue is part of #5248
[^1]: [HfLA spelling audit spreadsheet - Results](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048)
[^2]:The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by roslynwythe** [comment]
@wanyuguan I see that you moved this item to Onboarding Info/links and I'm not sure why.  Since #5248 is ready for implementation, I would like to work on the template, so I'm releasing the dependency and moving it to In Progress.

**Comment by roslynwythe** [comment]
Template for issues that add false positives to the spell checker config file:
NOTE: for handling individuals' names, replace "words" in the template with "ignoreWords"
- see also: sample issue #5618

<details><summary>Copy template</summary>

````
### Overview
We need to update the Code Spell Checker configuration file with false positive terms so that they are no longer marked as errors. 

### Action Items
- [ ] You must use VS Code as your local text editor to install the VS Code extension for spell checking your codebase,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [ ] Do not change any configuration settings or make any spell corrections
- [ ] Open the file `cspell.json`
- [ ] Replace the line
```
  "words": [
```
with
```
  "words": [
      "[INSERT TERM]",
```
- [ ] Save `cspell.json` and then test the change by opening `[INSERT FILE PATH]` and confirming that no Code Spell Checker errors/messages are displayed.  
- [ ] No docker testing is required.  Create a Pull Request in the usual manner, with changes only to `cspell.json`.   

### Resources
[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- This issue was created as part of #5312
````
</details> 

<details><summary>View template</summary>

### Overview
We need to update the Code Spell Checker configuration file with false positive terms so that they are no longer marked as errors. 

### Action Items
- [ ] You must use VS Code as your local text editor to install the VS Code extension for spell checking your codebase,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [ ] Do not change any configuration settings or make any spell corrections
- [ ] Open the file `cspell.json`
- [ ] Replace the line
```
  "words": [
```
with
```
  "words": [
      "[INSERT TERM]",
```
- [ ] Save `cspell.json` and then test the change by opening `[INSERT FILE PATH]` and confirming that no Code Spell Checker errors/messages are displayed.  
- [ ] No docker testing is required.  Create a Pull Request in the usual manner, with changes only to `cspell.json`.   

### Resources
[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- This issue was created as part of #5312
</details>

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Please advise, how should we handle the names of individuals that are flagged as "unknown words" by the spell checker?  Currently in our spelling [spreadsheet](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048), they are categorized as "false positive" but it is not appropriate to handle them in the same manner as other false positives (such as "hackforla".  Options:
      - edit the html, surrounding names with "comments" that disable code spell checker
      - add each name to the `ignore` array in the spell checker configuration file
      - do nothing and just ignore spell check messages on individuals' names.  Are we planning to implement repo-level spell checking that would cause GitHub checks to fail?

- Also please review the [template above](https://github.com/hackforla/website/issues/5312#issuecomment-1736440177) or alternatively this sample issue #5618

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 13, 2024 at 12:14 PM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 27, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 3, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 10, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 17, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 8, 2024 at 12:05 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 15, 2024 at 12:04 AM PST.</sub>
