### ISSUE TITLE
Epic: Updates to remove CfA as our fiscal sponsor - CFA mentions

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5403]
### Overview
In order to remove CfA (Code for America) as our fiscal sponsor, we need to remove mention of CfA from various webpages.  

### Issues
- [x] #5408
- [x] #5409
- [x] #5410
- [x] #5411
- [x] #5427
- [x] #5428
- [x] #5429
- [x] #5426
- [x] #5447
- [x] #5448 
- [x] #5511 
- [x] #5934

### Action Items
- [x] Create an issue to update `_includes\about.html`
  -  replace this text:
```
	<p>
      We bring together civic-minded volunteers to build digital products, programs and services with community partners and local 
      government to address issues in our LA region. Hack for LA is a project of <a href="https://www.codeforamerica.org" rel="noopener" target="_blank">Code for America</a> and is it's 
      official Los Angeles chapter. 
    </p>
```
with
```
	<p>
      We bring together civic-minded volunteers to build digital products, programs and services with community partners and local 
      government to address issues in our LA regio. Hack for LA is a project of <a href="https://www.civictechstructure.org/" rel="noopener" target="_blank">Civic Tech Structure, Inc.</a>
    </p>
```
- [x] Create an isue to update `_data/internal/sponsors.yml`
    -  remove these lines:
```
- name: Code for America
  link: https://www.codeforamerica.org/
  img_url: /assets/images/sponsors/code-for-america.svg
  position: 1
```
    -   subtract 1 from the `position` value of the other sponsors
- [x] Create an issue to update `_projects/ballot-nav.md`
    -  replace the line
```
partner: Code for America, Other Brigades
```
with
```
partner: Code for San Jose, Code for Atlanta, Open Oakland
```
- [x] Create an issue to update `_projects/brigade-organizers-playbook.md` 
   -  replace
```
partner: Code for America (CfA), CfA National Advisory Council, Code for Boston, Code for Charlottesville
```
with
```
partner: Code for America (CfA), CfA National Advisory Council, Code for Boston, Code for Charlottesville  ????
```
  - replace
```
description: Each of the 80+ Code for America Brigades is an experiment which generates valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each others work, improving outcomes for the whole network.
```
with
```
description: Civic tech volunteer organizations often start building from scratch, which uses up valuable resources (time, labor and momentum).  This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each other's work, improving outcomes for the civic tech ecosystem.
```
- [x] Create an issue to update `_projects/civic-tech-index.md`
  - replace:
 ```
partner: Code for America, Yale OpenLab and many more.
```
with
```
partner: ???
``` 
- [x] in `_includes/events-page/header-container-content.html`
   - replace
```
      <h2 class="header-desc">
        Hack for LA is the Los Angeles brigade of
        <a href="http://brigade.codeforamerica.org/" target="_blank">Code for America</a>,
        a network of civic-minded technologists who contribute their skills
        toward using the web as a platform for local government and community
        service.
      </h2>
``` 
with
```
      <h2 class="header-desc">
        Hack for LA was incubated in the Code for America Brigade Network and continues the valuable work under Civic Tech Structure, Inc. a network of civic-minded technologists who contribute their skills toward using the web as a platform for local government and community service
      </h2>
```
- [x] Create an issue to update `_data/internal/program-areas/civic-tech-infrastructure-card.yml `
  - replace
```
description: >
  Hack for LA is creating replicable blueprints for processes and practices to be 
  shared across Code for America brigades and support other similar organizations 
  around the world.
``` 
with:
```
description: >
  Hack for LA is creating replicable blueprints for processes and practices to be shared with other similar organizations around the world
```
- [x] Create an issue to update `_pages/privacy-policy.html`
  - replace
```
HackforLA.org is an informational website managed by Hack for LA which is a project of Code for America Labs, Inc. ("Code for America", "we", "us", "our").
```
with 
```
HackforLA.org is an informational website managed by Hack for LA which is a project of Civic Tech Structure, Inc. ("Civic Tech Structure", "we", "us", "our").
```
- [x] Create an issue to update `_data\internal/privacy-policy.yml`
  - replace
 ```
  Code for America\
  Ref: Hack for LA, HackforLA.org\
  155 9th Street\
  San Francisco, CA 94103
``` 
with
```
Civic Tech Structure, Inc.
Ref: Hack for LA, HackforLA.org
13428 Maxella Ave, Unit 821
Marina Del Rey, CA 90292
```

- [x] Create an issue to update '_includes/donation/donate-gif-text.html'
Replace 
```
 <p>Hack for LA takes donations through Code for America.</p>  
    <ol>
      <li>
        Please follow this link to the Code for America
        <a href="https://www.codeforamerica.org/donate" target="_blank" rel="noopener noreferrer">donation form.</a>
      </li>
      <li>
        To make a donation please select <strong>Hack for LA</strong> under the brigades
        listed.
      </li>
    </ol>            
  </div>
  <img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt="">
  <p class="donation-footer" id='donation-footer'>*100% of donated proceeds go directly to Hack for LA when option is selected.</p>
``` 
with
```
 <p>Hack for LA takes donations through Civic Tech Structure.</p>  
    <ol>
      <li>
        Please follow this link to the Civic Tech Structure Stripe
        <a href="https://donate.stripe.com/bIY9Cpcg8dihfIc5kl" target="_blank" rel="noopener noreferrer">donation form.</a>
      </li>
    </ol>            
  </div>
  <img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt="">
  <p class="donation-footer" id='donation-footer'>*100% of donated proceeds are tax deductible.</p>
```
- [ ] Create an issue to update `_includes/join-donate-card.html`
Replace
```
    <h3 class="title6 page-card--large-icon-header-secondary">Make a donation to Hack for LA</h3>
```
with 
```
<h3 class="title6 page-card--large-icon-header-secondary">Make a donation</h3>
```

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I moved all the issues into the prioritized backlog, with a few minor updates.

The following issues need attention.
- https://github.com/hackforla/website/issues/5447
- https://github.com/hackforla/website/issues/5429
