### ISSUE TITLE
Epic: Create issues to add github-handle to leadership teams

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5441]
### Overview
We need to create issues to define a single variable to hold the github handle for each member of the leadership team.  Eventually, this variable will replace the existing `github` and `picture` variables, reducing redundancy in the project data. 

### "Good First Issues"
- [x] #5504
- [x] #5505 
- [x] #5506 
- [x] #5507 
- [x] #5508 
- [x] #5509 
- [x] #5713
- [x] #5714
- [x] #5715
- [x] #5878
- [x] #5879 
- [x] #5880
- [x] #5881
- [x] #5882 
- [x] #6106 
- [x] #6107 
- [x] #6108
- [x] #6110 
- [x] #6111
- [x] #6123
- [x] #6124
- [x] #6125
- [x] #6126
- [x] #6153
- [x] #6154
- [x] #6155
- [x] #6156
- [x] #6157
- [x] #6167
- [x] #6168
- [x] #6169
- [x] #6170
- [x] #6171
- [x] #6172
- [x] #6173
- [x] #6174
- [x] #6175
- [x] #6176
- [x] #6177
- [x] #6178
- [x] #6179
- [x] #6180
- [x] #6181
- [x] #6182
- [x] #6191 
- [x] #6192 
- [x] #6234
- [x] #6235
- [x] #6236
- [x] #6237
- [x] #6238
- [x] #6239
- [x] #6696
- [x] #6700
- [x] #6701 
- [x] #6702 
- [x] #6703 
- [x] #6704 
- [x] #6705
- [x] #6706 
- [x] #6717
- [x] #6718
- [x] #6719
- [x] #6720
- [x] #6721
- [x] #6722
- [x] #6723
- [x] #6724
- [x] #6725
- [x] #6729
- [x] #6730 
- [x] #6731 
- [x] #6732 
- [x] #6733
- [x] #6734 
- [x] #6735
- [x] #6736 
- [x] #6737 
- [x] #6738 
- [x] #6739 
- [x] #6740 
- [x] #6741 
- [x] #6742 
- [x] #6743 
- [x] #6759
- [x] #6760
- [x] #6761
- [x] #6762 
- [x] #6763
- [x] #6941 
- [x] #6940
- [x] #6939
- [x] #6938 
- [x] #6937 
- [x] #6936 
- [x] #6935 
- [x] #7044 
- [x] #7046 
- [x] #7047 
- [x] #7048 
- [x] #7049 
- [x] #7050 (closed PR #7057 without merging this was a duplicate of #6941)
- [x] #7045 
- [ ] #7102 
- [x] #7103 
- [x] #7171 
- [x] #7172 
- [x] #7173 
- [x] #7174 
- [x] #7170
- [x] #7175 
- [x] #7176 
- [x] #7177 
- [x] #7178 
- [x] #7179 
- [x] #7180 
- [x] #7181 
- [x] #7182 
- [x] #7183 
- [x] #7184 
- [x] #7185 
- [x] #7186 
- [x] #7187 
- [x] #7188 
- [x] #7189 
- [x] #7190 
- [x] #7191 
- [ ]  #7239
- [x]  #7240
- [x] #7241
- [x] #7242
- [x] #7245 
- [x] #7246 
- [x] #7247 
- [x] #7248 
- [x] #7249 
- [x] #7250 
- [x] #7251 
- [x] #7252 
- [x] #7253
- [x] #7254
- [x] #7286
- [x] #7287
- [x] #7288
- [x] #7289
- [x] #7290
- [x] #7291
- [x] #7292
- [x] #7332
- [x] #7333 
- [x] #7334 
- [x] #7335 
- [x] #7336 
- [x] #7337 
- [x] #7351
- [x] #7352
- [x] #7353 
- [x] #7354
- [x]  #7355
- [x] #7356
- [x] #7357
- [x] #7366
- [x] #7380
- [x] #7381
- [x] #7382
- [ ] #7384
- [ ] #7401
- [ ] #7402
- [x] #7403
- [ ] #7430
- [ ] #7431
- [ ] #7432
- [x] #7433
- [ ] #7434
- [ ] #7435
- [ ] #7781 
- [x] #7782
- [x] #7792
- [ ] #7794 
- [ ] #7795 
- [ ] #7799 
- [x] #7800 
- [ ] #7801 
- [x] #7802 

### Issue Making Level 1 Issues
- [x] #5999
- [x] #6000
- [x] #6001
- [x] #6002
- [x] #6695 
- [x] #6697 
- [x] #6698 
- [x] #6699
- [x] #6809
- [x] #6828 
- [ ] ~heart.md~
- [x] #7156
- [x] #7157 
- [x] #7158 
- [x] #7159 
- [x] #7160 
- [x] #7161 
- [x] #7162 
- [x] #7163 
- [x] #7164 
- [ ] undebate ? only 1 issue
- [ ] metro-on-time only 1 issue
- [x] #7266
- [x] #7267
- [x] #7268
- [ ] writeforall 1 issue
- [x] #7265

### Action Items
- [x] Create template for the addition of the variable `github-handle` to a member of a leadership team
       - create issue to make GitHub template: #5541
       - Resulting template:  [template](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D) 
- [x] Create a level 1 issue-making issue for the creation of issues for each project file, using  (https://github.com/hackforla/website/issues/5441#issuecomment-1736824314)
- [ ] When all the issues created from this epic are completed, check each project.md file, to make sure that any new members that have been added also have the `github-handle` variable, and if not, make remaining issues and add them to this issue. - this step gets repeated until every project file has the variable handles on every team member.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
[Spreadsheet with all the project.md files 
](https://docs.google.com/spreadsheets/d/1CX2Xrobtr5WaT7P8KEN4kOR1bK3TWgKar0MX7-juBWA/edit?gid=0#gid=0)

**Comment by roslynwythe** [comment]
#### Template for Complexity: Small issue to add the `github-handle` variable.  The contributor must also populate a value for `github-handle` by copying the handle from the existing `github` variable

### Title: Add new variable github-handle to member [REPLACE WITH MEMBER] in project file [PROJECT FILE]

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team, and set the value of the new variable by copying a portion of the existing `github` URL.    Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [ ] Open the file `[REPLACE WITH PATH TO PROJECT FILE]` in the IDE
- [ ] Replace:
```
- name: [REPLACE WITH NAME]
```
with
```
- name: [REPLACE WITH NAME]
- github-handle: 
```
- [ ] Complete the last line above by copying/pasting in a value for `github-handle`for the specified member.  The GitHub handle can be copied from the last portion (following the final `/`) of the existing `github` variable.  For example, 
```
  - name: Bonnie Wolfe
  - github-handle: ExperimentsInHonesty
```  
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/[REPLACE WITH PATH TO PROJECT FILE]
Webpage: https://www.hackforla.org/projects/[REPLACE WITH PROJECT FILENAME (without .md extension)]
- This issue is part of #5441

**Comment by roslynwythe** [comment]
#### Template for `good first issue` to add the `github-handle` variable (with no value) for a particular member of a project 

### Title: Add new variable github-handle to member [INSERT MEMBER NAME] in [INSERT PROJECT FILE]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [ ] Open the file `_projects/[INSERT PROJECT FILE]` in the IDE
- [ ] Replace:
```
- name: [INSERT MEMBER NAME]
```
with
```
- name: [INSERT MEMBER NAME]
  github-handle: 
```
- [ ] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [ ] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Markdown File: https://github.com/hackforla/website/blob/gh-pages/_projects/[INSERT-PROJECT-FILE]
Project Webpage: https://www.hackforla.org/projects/[INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION]
- This issue is part of #5441

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty please review the [template](https://github.com/hackforla/website/issues/5441#issuecomment-1716198393) or alteratively the sample issue #5504

**Comment by roslynwythe** [comment]
Template for issue-making Level 1 issue: creating issues to modify each member in a project file

Title:  Create Issues to add new variable github-handle for members in [INSERT-PATH-TO-PROJECT-FILE]

### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in [INSERT-PATH-TO-PROJECT-FILE] with a the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [ ] For each team member listed in [INSERT PATH TO PROJECT FILE], create an issue using the [template](https://github.com/hackforla/website/issues/5441#issuecomment-1716198393)
- [ ] For each issue:
   - [ ] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [ ] In the title, replace [INSERT PROJECT FILE] with **INSERT PROJECT FILE**
   - [ ] Under Action Items, replace [INSERT MEMBER NAME] with the member's name  (in 2 places)
   - [ ] Under Action Items, replace [INSERT PROJECT FILE] with **INSERT PROJECT FILE**
   - [ ] Under Resources, replace [INSERT_PROJECT_FILE] with **INSERT_PROJECT_FILE**
   - [ ] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with **INSERT PROJECT FILENAME WITHOUT EXTENSION**
   - [ ] Apply the following labels: "ready for dev lead", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [ ] List the issue number in #5441 under Good First Issues
- [ ] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for merge team"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/[INSERT-PROJECT-FILENAME]
- This issue is part of #5441

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe we might need to add the epic label to the level 1 issue making issues, or figure out a carve out for the dashboard
   - The assignee did not list the issues in their issue #6697
   - example of an assignee who did list them on a similar issue #6695
   - I also added the `epic` label to both those issues, because they that makes issues and have two complexity labels.  See the issue [dashboard >, Anomaly Report > Complexity Labeling Anomalies](https://lookerstudio.google.com/u/0/reporting/6410c484-f38f-44ba-b4ed-c29a6b2a081b/page/p_f952karx9c)

**Comment by ExperimentsInHonesty** [comment]
Level 1 issues need to have the epic label

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 13, 2024 at 12:14 PM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 27, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 3, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 10, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 17, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 1, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 8, 2024 at 12:05 AM PST.</sub>

**Comment by HackforLABot** [comment]
@roslynwythe

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 15, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
Hi @daras-cu, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)
