### ISSUE TITLE
Create issues to add ignorePaths to cSpell configuration file

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5501]
### Overview
We need to create issues to add the setting "ignorePaths" to the spell check configuration file, so that we only spell check files that contain text displayed on the website. Paths that should be excluded from spell checking have been recorded in the "excluded paths" sheet in the HfLA spelling audit spreadsheet[^1]

### Dependency
- [x] #5313

### Action Items
- [x] Open the HfLA spelling audit spreadsheet[^1] and examine the "excluded paths" sheet.  This issue will focus only on those rows for which the column labelled "issue making level 1 issue" is`https://github.com/hackforla/website/issues/5501`
- [x] For each row matching the condition described above, create a new blank issue with the title:
```
Add [REPLACE WITH PATH] to "ignorePaths" array in cspell.json
```
where `[REPLACE WITH PATH]` should be replaced with the value in the column "path to exclude"

- [x] Replace the body of the issue with this [template](https://github.com/hackforla/website/issues/5450#issuecomment-1707386797)
- [x] Apply the following labels to the issue: "good first issue", "Feature: Administrative", "size: 0.25pt", "role: front end", "role: back end/devOps", "ready for dev lead"
- [x] After creating each issue, copy/paste the issue link into the column labelled "issue to add path to cspell.json" in the spreadsheet, and add link under "Dependencies (Issues Created)" in #5450
- [x] When all issues have been created, move this issue into the "Questions/In Review" column and apply the label "ready for dev lead"

### Resources/Instructions
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
[^1]:[HfLA spelling audit spreadsheet - ](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1299740856)

- This issue is part of #5450

**Comment by freaky4wrld** [comment]
- Availability: Today morning at 10:00AM PST
- ETA: EOD

**Comment by freaky4wrld** [comment]
@roslynwythe can you please help me here
List of Issues created 
* https://github.com/hackforla/website/issues/5838#issue-1977789309
* https://github.com/hackforla/website/issues/5839#issue-1977791051
* https://github.com/hackforla/website/issues/5840#issue-1977792152
* https://github.com/hackforla/website/issues/5841#issue-1977793105
* https://github.com/hackforla/website/issues/5843#issue-1977796042
* https://github.com/hackforla/website/issues/5842#issue-1977794282
* https://github.com/hackforla/website/issues/5844#issue-1977796891
* https://github.com/hackforla/website/issues/5845#issue-1977798109
* https://github.com/hackforla/website/issues/5846#issue-1977798718
* https://github.com/hackforla/website/issues/5847#issue-1977799473
* https://github.com/hackforla/website/issues/5848#issue-1977801056
* https://github.com/hackforla/website/issues/5849#issue-1977801963
* https://github.com/hackforla/website/issues/5850#issue-1977802741

 **Although in an attempt to check an Action Button, a useless issue has been created, Please removed it. Very sorry to increase your work.**

Also can you please point me to the `column labelled "issue to add path to cspell.json"`, so that I can paste those created issue there, and get it ready for `Questions/In Review`

**And last question as of now that where should I place these issues on the Project Board?**

**Comment by roslynwythe** [comment]
Hi @freaky4wrld great job creating these issues.  The column "issue to add path to cspell.json" is column C in https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1299740856

When we create new issues, we can simply assign them to "Project Board" and they will automatically go into the "New Issue Approval" column.  There is an easy way for you to assign all the issues at once.  Use the link https://github.com/hackforla/website/issues?q=is%3Aissue+is%3Aopen+no%3Aproject+author%3Afreaky4wrld

then check the boxes and use the "Projects" dropdown.  

You mentioned a useless issue had been created, but I don't see that issue; if you can find it, simply close it as "Not Planned", or send me a link and I'll do that.  

One more thing, if you could send me a Slack message when you put the issue in Questions/In Review, I'll get to it sooner.  Thanks very much for your work on this issue.

**Comment by roslynwythe** [comment]
Great job @freaky4wrld creating these issues.  This issue is completed.
