### ISSUE TITLE
update prework checklist to remove instructions for Google Drive access

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5628]
### Overview
Instructions in the prework checklist issue for new developers to obtain Google Drive access must be updated in order to avoid confusion.  Google Drive access is established with the use of a Tables form and so it is not necessary to create a post in #hfla-site-onboarding.  

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/pre-work-template--dev.md` in your IDE
- [x] Remove the line:
```
- [ ] Share your GitHub handle and Gmail address in the hfla-site-onboarding slack channel so you can be added to the Google Drive (alternative to go to meeting and direct message a merge team member at the [meeting](https://github.com/hackforla/website/wiki/Meetings-and-Agendas
))
```
- [ ] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

**Comment by DorianDeptuch** [comment]
Availability: Weekday Afternoons/Evenings
ETA: 10/4 EoD
