### ISSUE TITLE
HfLA: Dev Lead Team (Merge Team) Agenda 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5653]
### Overview
This issue tracks the agenda for the monthly Website Dev Lead/Merge Team meeting

#### Template
```
## [DATE IN YYYY-MM-DD FORMAT] Meeting Agenda

### Recurring items: 
- [ ] Check to see how merge team members are doing
- [ ] Suggestions for improvements to issue/PR templates, PR instructions?
    
### FYIs (nothing needs to be done, just keeping each other informed)

### New Items 
add issue numbers to be discussed and any notes that will be helpful


### Notes from meeting

### Tasks

### Items for next week's agenda
```

### Prior and upcoming meetings
- Oct 3, 2023

**Comment by roslynwythe** [comment]
## Oct 3, 2023 Meeting Agenda

### Recurring items: 
- [x] Check to see how merge team members are doing
- [x] Request for volunteers to lead meetings  [Monthly Signup for Merge Team/Dev Lead Team Task List Spreadsheet](https://docs.google.com/spreadsheets/d/1phPsEd_RVjQlHI4hsPJVEqqi4Ua-4WI7lhXNggtuc24/edit#gid=664707926)
- [x] Reminder and thanks for monitoring #hfla-site and providing prompt support for members
- [x] Please try to review extra PRs during planning week
- [x] Suggestions for improvements to issue/PR templates, instructions, good first issues..
- [x] meeting schedule:
  - [x] Should we hold meeting on Halloween (Tues Oct 31st)?
  - [x] Meeting on Sunday 11/26th will be cancelled
    
### FYIs (nothing needs to be done, just keeping each other informed)

#### CodeQL
-  #4886 implemented "security and code quality" query set
- weekly scan on Fridays, scan on push, open/commit PRs
- alerts appear in the Security tab [code scanning](https://github.com/hackforla/website/security/code-scanning)
        - tracking alert/issues see [codeql scan alert 24](https://github.com/hackforla/website/security/code-scanning/24) 
        - tracking analysis issue: recommend dismissal or code fix
           - dismissal process, documentation
           - if recommendation is to fix code, who will write the issue with the exact code fix?
  - PRs: code annotation #5204
  - alerts of severity “High” or higher cause a PR check to fail
  - pr instructions regarding alerts: #5196
  - problem with dev dismissing alert - see #5280
     - solution to this problem?   
        - GitHub App can subscribe to CodeQL scan events and create an issue for review of all dismissed alerts. 
      
- [ ] spell checking 
   - first implement local spell checking (VSCode/npm) then repo checking (MegaLinter) 
   - shared config file: `cspell.json`
   - current issues: auditing each page, updating cspell.json with "words", "ignore", and "ignorePath" arrays
   - #4101 and #5652
   - #4470
   - #5202
   - #4469 
      - proposal to develop GHA to add comment with checkbox upon issue assignment
      - proposal to develop GHA to add comment with checkbox in newly created PRs
      - proposal to develop GHA to add comments with checkbox to prework checklists
   - repo-level: use MegaLinter which includes cspell, ESLint, HTML Hint, others
  - Not sure if we will block merge on spell check errors



### New Items 
add issue numbers to be discussed and any notes that will be helpful


### Notes from meeting

### Tasks

### Items for next week's agenda

**Comment by skibidi350** [comment]
bro im only 13 and I wont to learn how to code and hack but its so hard I don't even understand this.....

**Comment by HackforLABot** [comment]
This issue was reopened because it did not have any of the following:
- A linked PR,
- An `Ignore` label
- A `non-PR contribution` label
