### ISSUE TITLE
ER: duplicate slack icons and inconsistent locations

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#5758]
### Emergent Requirement - Problem
We have 4 slack icons in the code base, all with different names and locations.  We should only have one of each color, that we use everywhere.

### Issue you discovered this emergent requirement in
- #1900 

### Date discovered 
2023-10-23

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@jefflueck @ExperimentsInHonesty 

### What happens if this is not addressed
- redundancy in code
- hard to change out the icon for any new icon

### Resources
- [GitHub search for files, excluding html, yml, scss), so mostly svg, or png, etc.](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+slack+-language%3AMarkdown+-language%3AHTML+-language%3ASCSS+-language%3AYAML&type=code)

#### List of files found
- _includes/svg/icon-slack.svg
   - What files this is used in
      - _data/navigation/social.yml
   - Where this appears on the website
      - in the social section of the footer https://hackforla.org
   - Is this Standard icon or custom (please explain if custom)
      - Standard: white (actually the svg has color but the class "icon" causes it to be white)
- _includes/svg/icon-slack-color.svg
   - What files this is used in
      - _includes/resource-card.html
   - Where this appears on the website
      - In the Resources section of most project pages, for example https://www.hackforla.org/projects/writeforall
   - Is this Standard icon or custom (please explain if custom)
      - Standard: color
- assets/images/communities-of-practice/slack-self-invite.svg
   - What files this is used in
      - website/pages/communities-of-practice.html
   - Where this appears on the website
      - https://www.hackforla.org/communities-of-practice.html
   - Is this Standard icon or custom (please explain if custom)
      - Custom: HfLA red version of slack icon
- assets/images/communities-of-practice/slack-join-meeting-channel.svg
   - What files this is used in
      - website/pages/communities-of-practice.html
   - Where this appears on the website
      - https://www.hackforla.org/communities-of-practice.html
   - Is this Standard icon or custom (please explain if custom)
      - Standard: white
      - Is on a button, navigation button.
- assets/images/getting-started/proj-4.png
   - What files this is used in
      - pages/getting-started.html
   - Where this appears on the website
      - https://www.hackforla.org/getting-started
   - Is this Standard icon or custom (please explain if custom)
      - Standard: black

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- Figure out what images we are keeping (without changing the design of any page), eliminate duplicates.
- The icons we are keeping should be moved to the technology's folder as part of refactoring files to use the new location.
- Add content to the wiki in order to indicate that all technology logos go into the technology folder and not in a specific page.

**Comment by ExperimentsInHonesty** [comment]
@jefflueck is going to add all the 
- [x] locations where they appear on website
   - [x] add feature label
- [x] file its used in
- [x] add ready for dev lead label
- [x] unassign
- [x] remove draft label

**Comment by ExperimentsInHonesty** [comment]
```
- [replace with file name]
   - What files this is used in
      - 
   - Where this appears on the website
      - 
   - Is this Standard icon or custom (please explain if custom)
      - Standard: color
      - Standard: white
      - Standard: black
      - Custom: HfLA red version of _____ icon
```

**Comment by jefflueck** [comment]
I finished with the audit of files in this ER.
Updated labels, and ready for Dev Lead.

**Comment by roslynwythe** [comment]
A few notes:
- One advantage of using inline svgs is that potentially we could store just a single version in _includes/svg/ and then change the color using JS to apply appropriate classes. 
- If we do decide to switch the HTML from inline svgs to img tag, I suggest that make the switch for all of the icons that are rendered together, for instance all of the social media icons rendered footer.html, then all of the icons that appear in resource-card.html.

**Comment by roslynwythe** [comment]
- The strategy will be to use `_includes/svg/icon-slack.svg` for all instances of the Slack icon. 
  - [x] First we need an issue to modify the CSS in sass/elements/_icons.scss so that icons in the resource cards will be displayed with their original color, but the default for other instances will be to fill with `currentColor`.  See #5819
  - [x] An issue to modify the html in `_includes/resource-card.html` to use `_includes/svg/icon-slack.svg` and to separate the code that includes the github icon from the slack icon.  See #5826
  - [x] An issue to modify pages/communities-of-practice.html to replace the current `img` element with src `assets/images/communities-of-practice/slack-self-invite.svg` with a liquid include referencing `_includes/svg/icon-slack.svg` and to modify `_sass/components/_communities-of-practice.scss` to specify a fill color #fa114f and to update other styles so the svg is sized/aligned properly   #5827
  - [x] An issue to modify `pages/communities-of-practice.html` to replace the current `img` element with src `assets/images/communities-of-practice/slack-join-meeting-channel.svg` with a liquid include referencing `_includes/svg/icon-slack.svg` and to modify `_sass/components/_communities-of-practice.scss` as needed  #5829
  - [x] An issue to modify `pages/getting-started.html` to replace the current `img` element with src `assets/images/getting-started/proj-4.png` with a liquid include referencing `_includes/svg/icon-slack.svg` and to modify `_sass/components/_getting-started-page.scss` as needed to adjust svg size/layout.  #5830

**Comment by ExperimentsInHonesty** [comment]
I thought that when we last worked on this ER, we decided that we would have only one slack SVG and then adjust the color by CSS depending on where it appears (see RW's comment above https://github.com/hackforla/website/issues/5758#issuecomment-1789866630).  However, I still see the following images in this folder

https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-slack.svg
https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-slack-color.svg

**Comment by roslynwythe** [comment]
> I thought that when we last worked on this ER, we decided that we would have only one slack SVG and then adjust the color by CSS depending on where it appears (see RW's comment above [#5758 (comment)](https://github.com/hackforla/website/issues/5758#issuecomment-1789866630)). However, I still see the following images in this folder
> 
> https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-slack.svg https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-slack-color.svg

- That is correct; we decided we would only use `icon-slack.svg`.  I don't believe `icon-slack-color.svg` is used so I created #6648  to remove it.  

- To document the best method for reusing svgs, scaling them and changing the fill color using svg attributes, see #6654.  I believe that concludes work on this ER.
