### ISSUE TITLE
Write wiki page "Credits YML file templates for Composite Images"

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5895]
### Overview
The existing "credits" YAML file template does not contain sufficient data fields to enable proper crediting of composite images (that is, images that have been modified by combining with other images).   A scheme incorporating two additional YAML files with some additional fields has been devised, and in this issue that technique will be documented.  

### Action Items
- [x] Read #4606 which describes in detail the YAML files required to enable the appropriate display of credit for the composite image "Diversity, Equity and Inclusion".  
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
- [x] Using the process described in the previous Action Item, write a draft wiki page outlining the YAML files required to credit a composite image.  Use the example files from issue #4606
   - [x] 1 - composite image - for example,  `diversity-equity-inclusion-composite.yml` 
   - [x] 2 - main image - for example,  '`diversity-equity-inclusion-main.yml`
   - [x] 3 - secondary image - filename `diversity-equity-inclusion-secondary.yml`

### Resources/Instructions
1. [Credits page](https://www.hackforla.org/credits/)
2. [Wiki page: Credits](https://github.com/hackforla/website/wiki/Credits-page)
3. [Credits YML file template for iconography and imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)

**Comment by iancooperman** [comment]
Availability: 1/28 - 1pm-8pm; 1/29 - 5pm-9pm; 1/30 - 5pm-9pm; 1/31 - 7pm-9pm
ETA: 1/31 EoD

**Comment by iancooperman** [comment]
# Credits page details

### Purpose of page
* To display the images, authors and source for each image on the site, to comply with free license.
* To display the tools, source and where used at Hack for LA for projects that don't have their own website.

### Technical details
* URL: https://www.hackforla.org/credits/
* GitHub location: [pages/credits.html](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html)
* Credits file location: /website/_data/internal/credits/

### How to Write Credits
#### Non-Composite Images
See [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery).
#### Composite Images
A composite image is a digital image that is created by merging two or more elements in separate images. Composite images used on the website require a credit (and corresponding credit file) for not only the composite image itself, but also one for each image used to create the composite image.

The files from the issue https://github.com/hackforla/website/issues/4606 will serve as an example.


##### Composite Image
When crediting a composite image, follow the example below. As the file `diversity-equity-inclusion-composite.yml` demonstrates, `provider` is set to `HfLA composite image`, as opposed to a conventional image source. 
<details><summary>Example</summary><br>

```yaml
---
title: Diversity, Equity, Inclusion
title-link: https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/diversity-equity-inclusion-composite.yml
content-type: image
used-in: Homepage
provider: HfLA composite image
image-url: /assets/images/program-areas/diversity-equity-inclusion.png
provider-link: https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/diversity-equity-inclusion-composite.yml
# If an image was altered, please give the name of the HfLA designer that altered the image
compiled-by: Kristine Eudey
# If an image was altered, please give the LinkedIn URL of the HfLA designer that altered the image
compiled-by-link: https://www.linkedin.com/in/kristine-eudey/
alt: '4 people doing Ready Break! over laptop with progress pride flag'
# alteration: 'edited to remove images from the laptop cover, and then add the "Progress" pride flag'
# This image is a composite image.  If this image is used, credit must be provided to the author of each of the images used in the composite as well as the person who altered it.  
# See the following credits: 
#   main image: https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/diversity-equity-inclusion-main.yml
#   secondary image: https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/diversity-equity-inclusion-secondary.yml
---
```
<br></details>
##### Main Image
When crediting the main image making up the composite image, follow the example below. As the file `diversity-equity-inclusion-main.yml` demonstrates, `used-in` is set to the name of the composite image along with a mention of that fact.
<details><summary>Example</summary><br>

```yaml
---
title: Team Hands Middle Photo
title-link: https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity
content-type: image
used-in: Diversity, Equity, Inclusion (HfLA composite image)
artist: Matthew Henry
provider: Burst
provider-link: https://burst.shopify.com/
image-url: /assets/images/credits/team-hands-middle.jpg
alt: '4 people doing Ready Break! over laptop'
---
```
<br></details>

##### Secondary Image
When crediting a secondary image making up the composite image, follow the example below. As the file `diversity-equity-inclusion-secondary.yml` demonstrates, `used-in` is set to the name of the composite image along with a mention of that fact.
<details><summary>Example</summary><br>

```yaml
---
title: Progress Pride Flag
title-link: https://progress.gay/pages/terms-of-use
content-type: image
used-in: Diversity, Equity, Inclusion (HfLA composite image)
artist: Daniel Quasar
provider: Progress.gay
provider-link: https://progress.gay/
image-url: /assets/images/credits/ProgressSQsm.jpg
alt: '"Progress" Pride Flag'
---
```
<br></details>

**Comment by iancooperman** [comment]
Progress: Draft additions to [Wiki page: Credits](https://github.com/hackforla/website/wiki/Credits-page) complete, but may need revising.
Blockers: Lack of familiarity with HfLA's wiki writing style/guidelines.
Availability: Sat 2/3 - 10am-9pm
ETA: Sat 2/3

**Comment by iancooperman** [comment]
Progress: Barring any feedback, I think I'm done with this. 
Blockers: Because this issue is an edit to a wiki within another repo, I'm not sure how to go about making a PR for this. Any advice?
Availability: 2/4 - 10am-8pm

**Comment by freaky4wrld** [comment]
> Progress: Barring any feedback, I think I'm done with this. Blockers: Because this issue is an edit to a wiki within another repo, I'm not sure how to go about making a PR for this. Any advice? Availability: 2/4 - 10am-8pm

@iancooperman just go to the [website-wiki repo](https://github.com/hackforla/website-wiki) then go through the [getting-started section](https://github.com/hackforla/website-wiki?tab=readme-ov-file#getting-started) the whole `Readme` is to provide you the help in order to use `mkdocs` to get a live preview of the changes you are making!!!

Once you follow the `Readme` then add your commit and create a PR as usual!!

**Comment by LRenDO** [comment]
Hi @iancooperman (and @freaky4wrld)!

The instructions weren't super clear on this issue. It looks like you did a good job following the "How to Contribute to the Wiki" instructions. When there are issues that do not result in pull requests, like additions to the wiki, you can move the issue to the `Questions/In Review` column of the project board and add the `Ready for Dev Lead` label.  We periodically check this column and review any issues there.

Thanks!

**Comment by LRenDO** [comment]
Hi @iancooperman!

I figured I would go ahead and review this for you so you can make a few changes before moving it to the  `Questions / In Review` column and adding the `Ready for Dev Lead` label.  

Overall this wiki page looks great! You did a great job summarizing the information in the issue. I do have a few requests.

- [x] In main image code block, replace `image-url:` with `image-url: [Replace with url to main image]`
- [x] In secondary image code block, replace `image-url:` with `image-url: [Replace with url to secondary image]`
- [x] Clarify where these credit files should be added in the `Technical Details section`. You can see more information about where they are added in the original PR for that issue #6026.
- [x] After `The files from the issue #4606 will serve as an example.`, add something like `See "Proposed future credit files" section.` 
- [x] Use summary and details tags for the code blocks, so they can be toggled. [Example of markdown toggle](https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2)
- [x] While it wasn't clear in the scope of the issue, above the `Composite Images` section, I would add a section at the same level as that heading. Something like `Non-Composite Images` or `Unmodified Images` and include the link to the provided [Credits YML file template for iconography and imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery) page.

Please feel free to ping me here or on Slack if you have any questions or need any help.

Thanks for taking the time to contribute to the wiki!

**Comment by iancooperman** [comment]
ETA: 2/11
Availability: 2/10 - 10am-9pm, 2/11 - 10am-8pm

**Comment by roslynwythe** [comment]
Hi @iancooperman your wiki page looks great.  Please copy a link to your comment into [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

**Comment by roslynwythe** [comment]
Great writing, thank you @iancooperman
