### ISSUE TITLE
Remove mention of CfA in pages/join-us.html

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5934]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to remove mentions of Code for America (CfA) from a webpage so that we can remove CfA as our fiscal sponsor.

### Action Items
- [ ] In your local IDE, navigate to `pages/join-us.html`
- [ ] Change the following in the header:

**from** 
```
        Hack for LA is a project of <strong>Code for America</strong> and is its official
        Los Angeles chapter.
```
**to**
```
        Hack for LA is a project of <strong>Civic Tech Structure, Inc.</strong>
```
- [ ] Using Docker, verify the changes by viewing the Join Us page [^1] in your local environment and include before and after screenshots with your pull request.
  - [ ] Note: By changing the text, the alignment of the second paragraph might change. This alignment problem will be addressed in a separate issue created from this emergent request (ER): #5973 

### Resources/Instructions
- This issue is tracked in #5403 
[^1]: Join Us page URL: https://www.hackforla.org/join

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe 
- Gigi Patel (GitHub handle: GigiUxR) notified us in [this Slack post](https://hackforla.slack.com/archives/C01Q24YF56J/p1700694794866589) about Code for America still appearing on the Join Us page.
- I created this issue to fix it since I didn't see an issue for it in epic #5403.

1) Since it wasn't on the epic, I wanted to double-check this is a change we want. So, do we want to remove mention of CfA from the Join Us header?
2) I wasn't sure how the wording should change. So, should it change to the following?
```
        Hack for LA is a project of <strong>Civic Tech Structure, Inc.</strong>
```
3) I was checking what the new wording would look like on the page and noticed the text alignment changed if the wording changed.
<details>
  <summary>Current page at 1440px screen width</summary>
  <img width="960" alt="current-page" src="https://github.com/hackforla/website/assets/31293603/7dcc9112-fbe6-460e-ac2c-61e78c188776">
</details>

<details>
  <summary>Proposed change at 1440px screen width</summary>
  <img width="595" alt="proposed" src="https://github.com/hackforla/website/assets/31293603/c0045e72-a2ac-4fff-9ddb-5de9c952bb0e">
</details>
Thanks.

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
**Progress:** If no changes are needed to this issue, this issue is `ready for prioritization`. If changes are needed, edits will be made.
**Blockers:** Awaiting response to https://github.com/hackforla/website/issues/5934#issuecomment-1823697447
**Availability:** Depends on when I get a response (see blocker)
**ETA:** Depends on when I get a response (see blocker)

**To Dos**
- [x] Awaiting response to https://github.com/hackforla/website/issues/5934#issuecomment-1823697447
- [x] If no changes are needed to this issue, this issue is `ready for prioritization`
- [ ] If changes are needed, check if the new wording still changes the alignment to center align
<details>
  <summary>Current page at 1440px screen width</summary>
  <img width="960" alt="current-page" src="https://github.com/hackforla/website/assets/31293603/7dcc9112-fbe6-460e-ac2c-61e78c188776">
</details>

<details>
  <summary>Proposed change at 1440px screen width</summary>
  <img width="595" alt="proposed" src="https://github.com/hackforla/website/assets/31293603/c0045e72-a2ac-4fff-9ddb-5de9c952bb0e">
</details>
 
  - [x] This might be a bigger issue than just the Join Us page. How will it impact other pages (About Us, etc) using the same styling?
  - [ ] Also, the Projects page uses different styling. Shouldn't it be the same across pages using that header format?  

### Notes from 2023-11-27 Dev/PM meeting
- [x] Let this issue go through
- [x] Make a separate ER to fix the styling --> Completed. See: #5973
  - [x] Include also making sure the styling doesn't impact other pages, so will need to do a search for where the class(es) are used and make sure it doesn't change other pages

**Comment by MHamza-Aslam** [comment]
@JessicaLucindaCheng 
can i work on this issue

**Comment by JessicaLucindaCheng** [comment]
@MHamza-Aslam 
> @JessicaLucindaCheng can i work on this issue

Nope. Sorry, this issue is not ready to be worked on. 

Also, in order to work on an issue in this repo, you need to be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.

**Comment by roslynwythe** [comment]
- @JessicaLucindaCheng The epic #5403 was based on this doc https://docs.google.com/document/d/1fgNAtd_l0NPRGLbAR4sWIyWi2fP-PYCg5OqLxnXmpZE/edit#heading=h.2q35t5g02tjm and yes it looks like we missed that instance of "Code for America" on the "Join Us" page header.   

I'm not sure how I feel about the change in alignment so I'd like to discuss it with the group in our next meeting.

**Comment by MHamza-Aslam** [comment]
thank you so much for your guidance

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng As discussed in the Dev/PM meeting, the alignment problem needs to get moved to another issue.

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 

> @JessicaLucindaCheng As discussed in the Dev/PM meeting, the alignment problem needs to get moved to another issue.

- I moved it to this ER: #5973

**Comment by jlevot** [comment]
Availability for this week: 6h
My estimated ETA for completing this issue: 3/1/24 6:00pm

**Comment by jlevot** [comment]
Availability: Evening
ETA: 03/01/2024
