### ISSUE TITLE
Create Issues to add new variable github-handle for members in civic-opportunity-project.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6001]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in civic-opportunity-project.md with a the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [x] For each team member listed in _projects/civic-opportunity-project.md`, create an issue using the [template](https://github.com/hackforla/website/issues/5441#issuecomment-1716198393)
- [x] For each issue:
   - [x] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [x] In the title, replace [INSERT PROJECT FILE] with **civic-opportunity-project.md**
   - [x] Under Action Items, replace [INSERT MEMBER NAME] with the member's name
   - [x] Under Action Items, replace [INSERT PROJECT FILE] with **civic-opportunity-project.md**
   - [ ] Under Resources, replace [INSERT-PROJECT-FILE] with **civic-opportunity-project.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-EXTENSION] with **civic-opportunity-project**
   - [x] Apply the following labels: "ready for dev lead", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [x] List the issue number in #5441 under Good First Issues
- [x] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for dev lead"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/[INSERT-PROJECT-FILENAME]
- This issue is part of #5441

**Comment by naveenmallemala5** [comment]
1. Availability: Mon - Friday 9:00 AM - 6:00 PM
2. ETA: 01/20/2024

**Comment by naveenmallemala5** [comment]
Availability: Mon - Friday 9:00 AM - 6:00 PM
ETA: 02/01/2024

**Comment by roslynwythe** [comment]
@naveenmallemala5 You have completed this issue successfully by creating the two issues, which look good.  I re-assigned you to this issue so that you recieve credit for it.  Thank you!
