### ISSUE TITLE
ER: Section 1.7 appears twice in CONTRIBUTING.md and is not listed in steps of Pre-Work Checklist

### ISSUE THREAD

**Issue by danvgar** [hackforla/website#6041]
### Emergent Requirement - Problem
1. Section 1.7 erroneously appears twice in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#17-dev-setup-7-install-local-codebase-spell-checker)
2. Section 1.7 is not listed within the [Pre-work Template - Developers](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Onboarding%2FContributing.md%2Cprework%2Csize%3A+1pt%2Crole+missing%2CComplexity%3A+Prework&projects=&template=pre-work-template--dev.md&title=Pre-work+Checklist%3A+Developer%3A+%5Breplace+brackets+with+your+name%5D)

### Issue you discovered this emergent requirement in
- [Pre-work Template - Developers](https://github.com/hackforla/website/issues/new?assignees=&labels=Feature%3A+Onboarding%2FContributing.md%2Cprework%2Csize%3A+1pt%2Crole+missing%2CComplexity%3A+Prework&projects=&template=pre-work-template--dev.md&title=Pre-work+Checklist%3A+Developer%3A+%5Breplace+brackets+with+your+name%5D)

### Date discovered 
- Jan 2, 2024

### Did you have to do something temporarily
- [ ] YES
- [X] NO

### Who was involved
- @roslynwythe 

### What happens if this is not addressed
 - May prolong future onboardings with clarification questions by attendees

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
 - [ ] Delete first copy of Section 1.7 in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#17-dev-setup-7-install-local-codebase-spell-checker)
 - [ ] Edit copy of item 15 to read Complete steps 1.1 - 1.7 in Part 1: Setting up the development environment within Contributing.md

**Comment by danvgar** [comment]
Hey @roslynwythe, per our call today, I'll go ahead and make this ER into an issue, in similar format to #6187. Let me know if I should go ahead and do the same for the other two ERs I've made this month (#6208, #6209)

**Comment by blaycoder** [comment]
@roslynwythe @danvgar should I go ahead with the potential solutions of this issue

**Comment by danvgar** [comment]
> @roslynwythe @danvgar should I go ahead with the potential solutions of this issue

Woops, I never assigned this to myself so forgot about it. Lesson learned!

@blaycoder we need to turn this into a proper issue first before going ahead and solving it. Let me go ahead and create one and assign it to you after

**Comment by danvgar** [comment]
@blaycoder In the future, only issues listed under `Prioritized backlog` [here](https://github.com/hackforla/website/projects/7#column-7198257) should be taken up as issues. :)

**Comment by blaycoder** [comment]
Noted, I will unassign the issue

**Comment by danvgar** [comment]
> Noted, I will unassign the issue

Thanks, @blaycoder ! I see this issue was erroneously marked as a `good first issue` when it likely is more of a `Complexity: Small` issue. I've updated the labels. Please go ahead and take up a `good first issue` in the Prioritized backlog instead! Sorry for the confusion!

**Comment by blaycoder** [comment]
Alright
Thanks

**Comment by danvgar** [comment]
@roslynwythe This has been split into separate issues as we discussed a few weeks ago.

- #6450 
- #6451 
- #6452 

They have been placed in the `New Issue Approval` column. 

Let me know if you want to chat and discuss further

**Comment by ExperimentsInHonesty** [comment]
@danvgar I am moving this issue to the questions column and adding the ready for dev lead label.  You should do the same next time you are ready for your issue to be reviewed.

**Comment by danvgar** [comment]
> @danvgar I am moving this issue to the questions column and adding the ready for dev lead label. You should do the same next time you are ready for your issue to be reviewed.

@ExperimentsInHonesty Understood, thank you for clarifying the process! I was asking this the past few meetings but was told there aren't any additional steps for me to take

**Comment by jphamtv** [comment]
> @roslynwythe This has been split into separate issues as we discussed a few weeks ago.
> 
> * [Update CONTRIBUTING.md Section 1.7 #6450](https://github.com/hackforla/website/issues/6450)
> * [Update Pre-Work Checklist (Dev) with Section 1.7 #6451](https://github.com/hackforla/website/issues/6451)
> * [Update Pre-Work Checklist (Design) with Section 1.7 #6452](https://github.com/hackforla/website/issues/6452)
> 
> They have been placed in the `New Issue Approval` column.
> 
> Let me know if you want to chat and discuss further

Hey @danvgar I reviewed the issues above and the first two look good and are ready to go. I've set them up to be prioritized. Great work on them! 

For #6452, Section 1.7 isn't relevant to the Pre-work Checklist for Design so I closed that issue and left a comment. Please see that issue for more details.
