### ISSUE TITLE
Rollout Plan: Change code to read data from multiple project repositories

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6138]
### Dependency
The issues in each phase should be completed before work on issues in the next phase.

#### Phase 1
- [x] #5231
- [x] #5160 
- [ ] #6139 

#### Phase 2
- [ ] #6144 
- [ ] #5127

### Overview
We want to change the HfLA website code to read from as many repositories as specified per project so that the languages and contributors data is properly representative of the projects.

#### Constraints
- Any changes we make need to work for all projects with multiple repositories
- We want to protect the contributions of previous contributors
- We want the all-time contributors that appear on any project page, to have all contributors across all repos.
- Languages are pulled directly from the repos and cannot be edited or added to.

### Action Items
- [x] Write an issue to move unrelated content out of the main Access the Data repository. - #6139 
   - [x] Move the [commit for the Jupyter Notebook](https://github.com/hackforla/access-the-data/commit/62609601277509b0473bbf8f6dbf1ef735430c84) to the Data Science Community of practice repo.
   - [x] Move any related issues to the data science community of practice repo
- [ ] Write an issue for each of the following to refactor the HfLA website code to read from as many repositories as specified per project so that the following data is properly representative of the projects:
    - [x] Languages - #5160 
    - [ ] Contributors
- [ ] Write an epic for adding the repositories to the project files:
   - [x] Access the Data - #5127
   - [x] Civic Tech Index - part of #5231 and #5160
   - [ ] Other projects with multiple repos

### Resources/Instructions
- This epic was initiated by this comment: https://github.com/hackforla/website/issues/5127#issuecomment-1734650107

**Comment by JessicaLucindaCheng** [comment]
Initial availability and ETA
- **Availability:** 6 hours
- **ETA:** Monday, January 29, 2024

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** None
- **Availability:** 6 hours
- **ETA:** I need to delay this by a few days, so new ETA is Friday, February 2, 2024.

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** None
- **Availability:** 6 hours
- **ETA:** Not sure for this week. There are a couple of time-sensitive issues that I need to finalize writing and take priority over this one.

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** Water-damaged laptop
- **Availability:** TBD - Need to resolve my computer problems
- **ETA:** TBD; dependent on my fixing my computer

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** Water-damaged laptop but it now works
- **Availability:** TBD - I need this week to catch up and prioritize what needs to be done.
- **ETA:** TBD - I need this week to catch up and prioritize what needs to be done.

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** None
- **Availability:** TBD
- **ETA:** TBD

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** None
- **Availability:** TBD
- **ETA:** TBD

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 13, 2024 at 12:14 PM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 27, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 3, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 10, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 17, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 1, 2024 at 12:04 AM PST.</sub>

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** None
- **Availability:** TBD
- **ETA:** TBD

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 15, 2024 at 12:04 AM PST.</sub>

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** None
- **Availability:** TBD
- **ETA:** TBD

**Comment by JessicaLucindaCheng** [comment]
- **Progress:** Still need to complete writing 1 issue for contributors from multiple repos for a project and an epic for adding additional repos to each project
- **Blockers:** None
- **Availability:** TBD
- **ETA:** TBD
