### ISSUE TITLE
Create Resources for Contributor Tracking

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#615]
### Overview
After Kian was successfully able to include comments as a data point for activity levels of contributors, we would like to document the process and have available to reference. This is a big win and we need to showcase it! 

### Action Items
- [x] Make 100 automations card https://github.com/100Automations/Website/issues/31
   - [x] Blurb about project 
- [x] generic script not specific to HfLA on how to accomplish
   - [x] write up instructions on how to implement script (for the readme)
- [x] Create repo true-github-contributors on at github.com/100automations org
    - [x] Create readme with info from here: https://github.com/100Automations/futureautomations/issues/9
- [ ] Ask for Peer review on readme and code from ops community of practice
   - [ ] integrate changes bases on suggestions
- [x] Implement newer version on HfLA website
- [ ] article to publish on Medium regarding the topic 
   - [ ] Draft outline and review with team 
   - [ ] Finalize article
      - [ ] Publish

### Resources/Instructions
Original issue on the topic is #346. 
[Latest Article draft](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit)

**Comment by KianBadie** [comment]
Should I create a generic script that isn't specific to the context of hfla before writing this so there could be code examples?

**Comment by alexandrastubbs** [comment]
@KianBadie If that is not a huge lift, that would be very helpful.

**Comment by ExperimentsInHonesty** [comment]
@KianBadie yes, it should go into the http://github.com/100automations/ ill add you to that org so that you can create the repo there.

**Comment by ExperimentsInHonesty** [comment]
@KianBadie You can start a draft of what your automation is about by filling out this [issue](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal) (which is like a questionnaire):

**Comment by KianBadie** [comment]
I'm sorry, I'm still not finished with this task. I am still working on making the "generic" version of the script. If you want to see the script to far, it is [here](https://github.com/KianBadie/github-api-test/blob/testing/github-util.js).

**Comment by KianBadie** [comment]
1. Progress - Created some essential functions for generic GitHub API utility script.
2. Blocks - None
3. Availability - Monday, Thursday, Friday, Saturday during the day.
4. ETA - Sunday 8/08

**Comment by KianBadie** [comment]
this is a test comment to test my comment fetching script

**Comment by KianBadie** [comment]
Here is a link to the repo where I am creating the generic script: https://github.com/KianBadie/github-contributor-helper

**Comment by KianBadie** [comment]
@ExperimentsInHonesty @alexandrastubbs For the second action item of "Kian to write up instructions for how to include more than just 'commits' in the Github Contributor tracking", is that a general high level of how to implement the feature? Or is this detailing more specifically how I did it? Because there are multiple ways to do it that could be described in a high level way, but describing it in a way that is specific to how I implemented it would be more detailed.

**Comment by KianBadie** [comment]
Here is my draft for the medium article (it is a work in progress): https://docs.google.com/document/d/1ah_UkZbQCm5HnS50CKeYYr5N7W7f6fJ_4Z-CWB3BqQI/edit#

**Comment by ExperimentsInHonesty** [comment]
@KianBadie Can you fill out this to document the automation requirements/audience, etc.:
https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal

**Comment by KianBadie** [comment]
I filled out that [document](https://github.com/100Automations/futureautomations/issues/9) and made more progress on the article. In [this document](https://docs.google.com/document/d/1KmEW-UOVTIXNEn0Bh0G-aDrvTcOnjSi2W4M_gKijl3s/edit#) I have an outline for the article as well as a draft for the technical directions for implementing the contributor+issue comment functionality. You can ignore the google doc I linked above, as this will replace that eventually.

**Comment by alexandrastubbs** [comment]
Issue created in 100 Automations: https://github.com/100Automations/futureautomations/issues/9

**Comment by KianBadie** [comment]
@ExperimentsInHonesty @alexandrastubbs 
So I looked into [octokit/rest.js](https://github.com/octokit/rest.js). It is an API client for the GitHub API. It's a convenient tool to use instead of having to make API request through something like a request library (which is how I have been interacting with the GitHub API). 

The way I have been currently interacting with the GitHub API is "reinventing the wheel", as octikit/rest.js can handle things like pagination and reduces fetching data from API endpoints, like getting repo languages, to a single method call. This tool could clean up a lot of wheel reinventing in our GitHub API script and make it more approachable to those who want to modify it in the future. It would remove the need to have a github object with data fetching methods like we do now. And that already, can remove a significant amount of code.

As how it related to this issue, I am wondering about the implications to my 100 Automations project because of this convenient tool. Right now, the wheels that I am not reinventing is 
1. The conversion of the Issue Comments Data to a structure that is similar to the Contributors data
2. The combination of said data and the Contributors data into a new contributors list. 

Other than those things, my data fetching methods in my [project](https://github.com/KianBadie/github-contributor-helper/blob/master/github-helper.js) that I submitted to 100 Automations are reinventing the wheel.

I'm going to let that sit with me for a bit as I determine if I feel like it brings any implications or changes to the article I am writing or my 100 Automations project, and would also appreciate any thoughts from anyone as well.

**Edit**
In terms of the article, should the topic now be something like "How to use GitHub's API client octokit/rest.js to represent more project contributors"? I feel like the article, like the 100 Automations project, should build upon the octokit/rest.js client rather than do wheel inventing. The only reason I would see my data fetching code to be useful is if it was faster than octokit/rest.js. I'm not sure the trade-offs between using an API client vs interacting with an API through a request library (and I'm sure it varies from API client to API client), but I feel like the possibility of my code being faster is not too high.

**Edit 2**
I made a demo that does the same thing I outlined in the article, but this time it uses octokit/rest.js. So I don't think it would take long to convert my 100 automations project to user octokit/rest.js

**Comment by KianBadie** [comment]
I have updated my 100 Automations project repository to now work with octokit/rest.js and added the feature to find out contributors by repo. The last thing I want to add is the option to provide a a date parameter so you can get issue comment contributions since a given date.

**Comment by KianBadie** [comment]
@ExperimentsInHonesty I know we discussed this last Sunday, but I thought I could remember some of the points we discussed however I cannot. I pretty much finished the script in it's first form. It can fetch comment contributors, comment+commit contributors, and contributors across an organization based on commits and comments. Next thing I want to add is the ability to get comment contributions across an organization instead of just a repo.

The question I had was for the writing up instructions part, which is the part I forgot we talked about. Are the instructions for how someone could combine the API endpoints to achieve getting more contributors data? If so, where would this information be shared? I ask that second question because it gives me an idea of what style to write this in. And is the article going to be based off of the script I am writing?

**Comment by KianBadie** [comment]
I added more contributors methods to my script. I'm trying to cover a set of contributors data sets (like comment contribution across an org since a give time, commit contributions to a repo after a given time, etc.) I the last one I need to implement is getting commit contributions across an org after a given time. There are also special cases (empty repos) that give me errors, so I have to fix that too.

In terms of technical directions, I made a bare bones tutorial [here](https://docs.google.com/document/d/1KmEW-UOVTIXNEn0Bh0G-aDrvTcOnjSi2W4M_gKijl3s/edit). I say bare bones because I was trying to write the least amount of code to implement the goal of getting commit+comment contributors. I assumed it would be a starting point for people, so I thought the smaller the code, the quicker people can get the general idea and take it where they want. I am also writing documentation for my script, which you can see on the repo. It is not currently up to date as I have added some update to the script. I think it will be like that until the script is in it's 1st complete form, which I hope will be by the end of next week.

1. Progress - Added methods above, created some documentation, made tutorial on how to combine commits+comments
2. Blocks - None
3. Availability - Friday, Saturday
4. ETA - Sunday 8/30

**Comment by alexandrastubbs** [comment]
@ExperimentsInHonesty and @KianBadie to meet Monday at 1pm PST to discuss more

**Comment by KianBadie** [comment]
Spent the week learning/implementing unit testing in my script. Aiming to get 100% code coverage so I can have confidence everything is working correctly. Unfortunately I was not able finish testing completely this week as I would have liked, as I spent a good amount of the week learning. However, I think I learned a lot though and know what I need to do now to finish testing. 

I also saw a a fellow 100 Automations tool [cherp](https://github.com/100Automations/cherp), which is similar to what I'm making in the sense that it builds upon octokit/rest.js. I wanted to modify my script implementation to be more similar to this script, as this script extends octokit/restjs (allows all original functionality of the github api client in addition to the new functionality they made) while my tool uses the github api client internally and provides access to only the few endpoints I'm making (which seems limiting). Thankfully, the implementation of this isn't drastic and would not add significant time to development.   

1. Progress - Started to implement unit testing
2. Blocks - Learning unit testing
3. Availability - Thursday, Friday, Saturday
4. ETA - 9/06

**Comment by KianBadie** [comment]
This week I continued to unit test and modify the structure of the code. The structure I decided to commit to was to create a mixin. The flow I have been doing is modifying each method to the new format and then unit testing it. Yesterday, I had about 3 functions left to test. However today, I realized my tests might have not been implemented how they should be, which will cause a set back as I review my old tests to check things and modify where needed. 

1. Progress - Continued testing and modifying base structure of tool
2. Blocks - Continuing to learn unit testing, realizing unsatisfactory points in my code through unit testing and having to modify them. 
3. Availability - Thursday, Friday, Saturday
4. ETA - 9/13

**Comment by KianBadie** [comment]
I covered the minimum amount of cases I wanted to cover in my tests to be comfortable with the tool. Up next is adding technical directions to the readme on how to use the tool, publishing it on npm, and then refactoring the site to use the tool. You can see the repo [here](https://github.com/100Automations/true-github-contributors).

I also marked some action items as complete because it is simply satisfying. If the ones I marked aren't considered complete then please let me know.

1. Progress - Finished testing
2. Blocks - None
3. Availability - Thursday, Friday, Saturday
4. ETA - Technical directions and npm publishing 9/17, hopefully hfla github script refactoring 9/19.

**Comment by KianBadie** [comment]
Added API Documentation, installation instructions, examples for each endpoint (in a directory in the repository), and updated the `Current State` section of the [readme](https://github.com/100Automations/true-github-contributors) of the project. 

The package is also available on [npm](https://www.npmjs.com/package/true-github-contributors) now!

**Comment by KianBadie** [comment]
My apologies, I wanted to get the script done this weekend, but I had a busier weekend than usual and was not able to complete it. It is almost there though, to the point where I am confident I can get it done on Monday

1. Progress - The script is almost done with incorporating the contributors tool.
2. Blocks - None
3. Availability - Monday afternoon
4. ETA - Will have a pr with the new script Monday 9/27

**Comment by KianBadie** [comment]
I have made a pull request #757 to update the GitHub Data Script. Awaiting review from @cnk and @ruben1s 

**Edit**: I have pushed commits to PR #757 since I have commented this. See the PR for updates/summary of changes.

**Comment by KianBadie** [comment]
#757 was merged a couple days ago!

**Comment by alexandrastubbs** [comment]
@KianBadie is there anything left outstanding for this issue?

**Comment by KianBadie** [comment]
@alexandrastubbs sorry for the lack of updates. Me and @ExperimentsInHonesty met on Monday to discuss the action item "article to publish on Medium regarding the topic". From that conversation, we created a general idea/outline of how we want the article to be. So I have to create my part of that draft. Which is writing a medium-level overview of the research/explanation that went into achieving the `Issue Comments + Commits Contributions` functionality, as well as an explanation of the tool I created. 

Also, I asked for a review of the tool I made in the ops channel, and tried to join the meeting this past Tuesday to ask for review. However, no one contacted me that they can review my code, and the Tuesday meeting was cancelled. I can try to ask again during the next Tuesday meeting.

**Comment by KianBadie** [comment]
1. Progress - I created a first draft of an outline based on the meeting me and @ExperimentsInHonesty in had this past Monday. 
2. Blocks - None
3. Availability - Thursday and Friday afternoon.
4. ETA - Attempting to have a draft based on the outline I created by next week.

**Comment by KianBadie** [comment]
Will be joining next Tuesday's (10/18) ops meeting to ask for review. If ops team is not able to provide review, I will follow with @ExperimentsInHonesty to see alternative options for review.

**Comment by KianBadie** [comment]
Mid week update: 
- I have started a draft based on an outline all in [this](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit) Google Doc in the `Hackforla.org Website` drive. From our meeting last Monday, me and @ExperimentsInHonesty plan on writing the content for the article in that doc.
- I did plan on joining the "ops" meeting last night to ask for code review in person. However, I did not because I felt a little shy/bad to join a meeting where I didn't know anyone and ask for a personal request that isn't related to their meeting. Like I mentioned earlier, I did send a message in the ops slack channel asking for code review. But no one responded to it saying they can review the code and I think the message is the past the point of receiving attention. Any recommendations on next steps regarding this @ExperimentsInHonesty @alexandrastubbs? The article and peer review from ops community are the last action items on here.

**Comment by alexandrastubbs** [comment]
@KianBadie no worries, totally understand, although I wouldn't feel bad attending the ops meeting and asking for help. If it is anything like the product meeting, the structure is pretty fluid and it is all about individuals coming with topics for discussion. 

An alternate option would be to reach out to someone directly. @ExperimentsInHonesty any ideas on someone who might be willing to donate some time?

**Comment by alexandrastubbs** [comment]
@ExperimentsInHonesty is reaching out to people individually to identify someone willing to mentor on this topic.

**Comment by KianBadie** [comment]
Thank you for understanding @alexandrastubbs and thank you for reaching out to people @ExperimentsInHonesty. I will be tuned in to this issue to be ready for any updates as I continue to work on the article :+1:

**Comment by KianBadie** [comment]
1. Progress - I think I have finished a draft of the article that I am comfortable with. Here is another link to the [google doc](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit%EF%BF%BC) (you have to scroll down a little bit to get to the article content). 
2. Blocks - None
3. Availability - Thursday and Friday afternoon 10/29 and 10/30
4. ETA - Will determine once next steps are determined

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty needs to review the google doc and @channel for peer review

**Comment by KianBadie** [comment]
1. Progress - Added new images based on our meeting from last Sunday 10/25. Also changed one of the images of code into an actual code block, and modified some of the wording. Will be awaiting further feedback!
2. Blocks - None
3. Availability - Thursday/Friday afternoon
4. ETA - Will determine once next steps are determined

**Comment by KianBadie** [comment]
I'm going to try review the new section I added to the article tomorrow morning and add/changing anything that is necessary. Just in case i don't get to that, however, here is my update:
1. Progress - Added a section to the [draft](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit) retelling our experience/solution to the abuse rate limit errors we were experiencing. This was based off a meeting me and @ExperimentsInHonesty had. I also edited some of the old parts of the draft slightly.
2. Blocks - Not a block necessarily, but I think the draft needs peer review.
3. Availability - TBD as next week for me has the potential of being busy. I strongly desire to keep the ball rolling on this. So I will try my best to respond quickly to any feedback.
4. ETA - Will be determined on peer review and how much more work the article needs.

**Edit**: This morning I modified the section I added a little bit. For some reason, adding this section does not sit completely well with me yet. The place I feel conflicted is that before I added this section, it seemed the focus of the article was to describe how to create the new contributors data set.

And while this new section is related in the journey we had to create that set, it also feels like it is explaining the solution to a different (but similar) problem. That different problem being building the new contributors data set over time rather than creating the data set at a given point in time (which I felt like the article was describing before this section). Please let me know thoughts on this :+1:

**Comment by KianBadie** [comment]
1. Progress - Continued to make small edits to the [article](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit) and someone was able to review and open a [a couple issues](https://github.com/100Automations/true-github-contributors/issues) for the "True GitHub Contributors" repository.
2. Blocks - None
3. Availability - Evenings/nights on the weekdays
4. ETA - This week

I would like to tie up the loose ends on this issue this week and finally complete this. With the article, the only place I am not sufficiently satisfied with is the "Rate limiting" section (I explain in depth why [here](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit?disco=AAAAKnTak9U) and [here](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit?disco=AAAAHNCJXd4)). To summarize those 2 point though, I feel like the "Rate limiting" section is describing a "maintaining a contributors list" problem as opposed to a "fetching a contributors list" problem, where I felt like the other sections are describing the later. In addition, our solution described in that section is great and can be combined with the best practices suggested by GitHub (and be smart and effective in my opinion), but our solution as described at that point in time in the article did not ultimately adopt the best practices, and it doesn't feel right to advertise a solution without putting emphasis on incorporating the best practices first. And lastly, I think the solution is effective when maintaining a list of contributors and that just the best practices would cover all the bases if you were fetching a contributors list at a certain point in time. Other than that, I am sufficiently satisfied with the rest of the article. 

In regards to the code review: The person who opened the issues was the person that @ExperimentsInHonesty connected me with in order to give some code review. They said they read through the project and said that it was done quite well! The 3 issues they opened were not major issues, so I think responding and incorporating the suggestions they brought up will not take long.

**Comment by KianBadie** [comment]
1. Progress - I created another draft of the [article](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit#) (skip to page 13 to start reading) based on the meeting we had last Sunday. I also updated the `true-github-contributors` repository to add a Getting Started section (which modified some of the current content in the readme to morph into a getting started section) and contributing section (which just links to the contributing document). I was going to also work on the more technical issues brought up in Jonathan's code review, but I had some questions for clarification before implementing because I was not able to understand the suggestions. Jonathan also introduced me to [codeclimate](https://codeclimate.com/github/100Automations/true-github-contributors) which provides automated reviews of repositories. It also had recommendations on things to change. But I think for the sake of my convenience so I can move forward, I will just stick to addressing the things Jonathan brought up. I think I am personally comfortable with sticking to those suggestions he brought up, as I am assuming if he didn't notice other issues, that those issues are not of significant issue.
2. Blocks - Waiting for clarification on Jonathan's suggestions
3. Availability - Evenings/nights on the weekdays
4. ETA -

**Comment by KianBadie** [comment]
1. Progress - I made a new draft of the [article](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit#) based on the comments made to it last Sunday 11/15. I resolved the google doc comments that I felt I addressed, and left other ones open with my responses so that they can be read.  
2. Blocks - None
3. Availability - Saturdays
4. ETA - 

I will be fiddling with the 100 Automations package tonight.

**Comment by KianBadie** [comment]
1. Progress - The [article](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit#) is ready for more review. I added test cases for modification that I wrote last week. Me and Jonathan Shin will get in touch this upcoming week to review the package again.
2. Blocks - None
3. Availability - Saturdays
4. ETA -

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty @KianBadie will get together during the week. 12/8/20 kian will send invite

**Comment by KianBadie** [comment]
1. Progress - Met with @ExperimentsInHonesty this past week and edited some of the article. The whole articles has not been reviewed yet. Jonathan and I did not meet this week. I had a slightly busier schedule with work this week and decided to give the issue a rest for the week.
2. Blocks - None
3. Availability - Saturdays
4. ETA -

**Comment by KianBadie** [comment]
Sorry for the lack of activity. I have been much busier with work the past week and a half, and have been using my free time to just do something non code related. The deadline for my work project is this Monday, which is when I can continue activity on this.

**Comment by KianBadie** [comment]
It seems like this issue has lost some traction. However, I am willing to make availability for whenever I'm needed to work on the article. Please correct me if I'm wrong, but I believe the state of the article is that it is waiting for more review from modifications I have made. So like I said, feel free to let me know if I'm needed for anything like reviewing. Or, please let me know if I'm wrong and if there is something waiting on my end in regards to the article.

In terms of the True GitHub Contributors package, I decided to do one more thorough sweep of the code so that the package can be in a satisfying state for me to put a little bow on it and call it "done". With the modification I made in response to the Code Climate review and Jonathan's review, I made changes to the code base that I felt like modified the inner workings of the package to a significant enough degree. Significant enough that I wanted to go through all my methods, rewrite the corresponding tests cases when needed, and modify/touch up the methods while I'm at it. I worked on this a couple hours last night, and got maybe a 1/4th or a 1/3rd through the package. Like I said, I want this to be one more thorough sweep through the package so I can take my hands of it in peace (unless of course something is needed from me, which in that case I am on standby!). I plan on finishing the rest of the sweep this week.

1. Progress - More thorough answer above. Short answer: waiting for further feedback/review on the article (feel free to contact me if it would be good for me to participate in that) and 1/4th of the way through a thorough sweep/touch up of the code base.
2. Blocks - Further feedback/review on the article.
3. Availability - I can make time as needed! 
4. ETA - I would like to be hands off on the code base by 1/16 (unless something else is needed, which in that case I am on standby). Article is up in the air as it is waiting for review. But please let me know whatever is needed from me and I will make availability for tasks in order to get whatever we need rolling :)

**Comment by KianBadie** [comment]
As a follow up to my previous comment, I am almost done combing the codebase. I want to wrap things up today. But if not today I want to wrap it up Tuesday. As always, feel free to let me know when the article-related things need to be attended to.

1. Progress - Combed about 85% of the codebase
2. Blocks - Further feedback/review on the article.
3. Availability - I can make time as needed! 
4. ETA - Codebase stuff - Tuesday

**Comment by KianBadie** [comment]
Sorry for the delays, again. I wrapped up all the testing I wanted to do yesterday. All that is left for me is to check my changes on actual data, merge my branch, and update the package on npm. I wanted to do this this morning before 10am. However, I unfortunately slept past my alarm, so it will be done later this afternoon. So I will be commenting soon when that is done.

I think the package has improved with the things I changed. However, the current state of the package and its tests is not perfect, and there were still questions I had on how to do testing. However, I think I need to wrap up whatever work I have left today and call it a day for this package, as developing on it through with my own instincts is becoming very hard to bring myself to. I will be more than happy to develop and fix any specific issues or bug that come up though! But I think I am putting down development through my own exploration on this package after today.

**Comment by KianBadie** [comment]
Sorry for the delays, again. I wrapped up all the testing I wanted to do yesterday. All that is left for me is to check my changes on actual data, merge my branch, and update the package on npm. I wanted to do this this morning before 10am. However, I unfortunately slept past my alarm, so it will be done later this afternoon. So I will be commenting soon when that is done.

I think the package has improved with the things I changed. However, the current state of the package and its tests is not perfect, and there were still questions I had on how to do testing. However, I think I need to wrap up whatever work I have left today and call it a day for this package, as developing on it through with my own instincts is becoming very hard to bring myself to. I will be more than happy to develop and fix any specific issues or bug that come up though! But I think I am putting down development through my own exploration on this package after today.

**Comment by KianBadie** [comment]
To follow up on my earlier comment, I think I have wrapped things up with the code base. If I have the desire, I might come back and touch things up for fun. But for the time being, I am calling it a day on that package. If there is anything broken with it however that I did not catch, I would be more than happy to tend to that and fix whatever is broken! As always, please let me know when work is desired to be done on the article, or if anything else is needed from me :+1: 

I have republished the package with all the changes I have done over the past couple of weeks. The new package is available on its npm page!

**Comment by ExperimentsInHonesty** [comment]
next steps are cleaning up this issue and then putting a ux writer label on it.
