### ISSUE TITLE
ER: Find all the places that slack should be Slack and fix

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6163]
### Emergent Requirement - Problem
Slack is a company name and should only be in lowercase (slack) when in a URL, variable or directory name (where the variables or directories are all lowercase).  

### Details
There are 161 files with some form slack in it.

### Issue you discovered this emergent requirement in
- #4685

### Date discovered 
2024-01-25

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
- If it's public facing, it's unprofessional not to fix it.
- if it's in our non-public facing code, it's best practices to use it consistently as intended

### Resources
- [161 files in our repo with some form of the name slack in it](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+slack&type=code)
   - I reviewed all the instances, and divided them up into could, be careful, and must.

#### Examples of locations that could be changed
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/_sass/components/_communities-of-practice.scss#L131
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/CONTRIBUTING.md?plain=1#L11
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/CONTRIBUTING.md?plain=1#L358
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/CONTRIBUTING.md?plain=1#L585
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/.github/ISSUE_TEMPLATE/pre-work-template---design.md?plain=1#L28
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/.github/ISSUE_TEMPLATE/pre-work-template---design.md?plain=1#L65
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/.github/ISSUE_TEMPLATE/pre-work-template--dev.md?plain=1#L36
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/.github/ISSUE_TEMPLATE/pre-work-template--dev.md?plain=1#L84
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/.github/ISSUE_TEMPLATE/pre-work-template--dev.md?plain=1#L85

#### Examples of locations it must be changed
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/pages/project-meetings.html#L14

### Recommended Action Items
- [x] Make an issue template in a comment that will work for all the issues, so that each file reference can be in its own separate issue is easy to make
- [x] move this issue to the questions column and add the `ready for merge team` label with the following note in a comment
   ```
   Please review my issue template comments above, and let me know when I can start making issues from them
   ```
- [ ] Once you receive the signoff, make issues

**Comment by ExperimentsInHonesty** [comment]
We need the language above to be clear that the person who is going to create the issues, will need to check to see if the change can be made without breaking anything.

Steps
- [ ] Make 2 issue templates in comments that will work for all the following types of changes, so that each issue is easy to make
- [ ] Review each potential change and decide if It's something that can be changed 
  - [ ] without risk, in which case it's a good first issue
  - [ ] might have risk and will need to be tested, in case it's a medium issue

**Comment by ExperimentsInHonesty** [comment]
The time sensitive label only refers to the fact that we need the issues this ER will create.  The time sensitive label should not be applied to the issues.

**Comment by tony1ee** [comment]
**Availability**: 05/02/2024 afternoon and evening
**ETA**: 05/02/2024 EOD

**Comment by tony1ee** [comment]
### Draft Issue Templates
---
## Title: Correct Capitalization of `Slack` in CONTRIBUTING.MD
(complexity: small)

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to fix the following line of code to correctly capitalize "Slack" when it's used to refer to the app or the company in our code and content.
[INSERT_LINE_PERMALINK]

### Action Items
- [ ] Open the file `CONTRIBUTING.MD` in your code editor
- [ ] On Line [INSERT_LINE_NUMBER], replace every `slack` with `Slack` **when it's used to refer to the app and the company**, **do not make changes within URLs**.
- [ ] Changes to CONTRIBUTING.md should not be tested locally, rather they need to be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https\://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### For Merge Team
- [ ] Release the dependency for this issue in #6163. If all the dependencies have been completed, close that issue.

### Resources/Instructions
- [Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.MD?plain=1

- This issue is part of #6163.
 
---
## Title: Correct Capitalization of `Slack` in [INSERT_FILE_NAME] (for issue templates)
(complexity: medium)

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to fix the following line of code to correctly capitalize "Slack" when it's used to refer to the app or the company in our code and content.
[INSERT_LINE_PERMALINK]

### Action Items
- [ ] Open the file `[INSERT_PATH_TO_FILE]` in your code editor
- [ ] On Line [INSERT_LINE_NUMBER], replace every `slack` with `Slack` **when it's used to refer to the app and the company**, **do not make changes within URLs**.
- [ ] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin test-update-labels-1234`  
- [ ] The response from the push command will include the URL for creating a pull request. Copy/Paste the URL for creating the Pull Request for later.  
- [ ] Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/8ecf2e55-2187-4ab9-acf1-2fd7548291a1)

  </details> 
- [ ] Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details> 
- [ ] Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  ![image](https://github.com/hackforla/website/assets/16524851/563fc427-ba07-4e47-9440-2580bbfcad52)

  </details> 

- [ ] From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template. 
- [ ] Copy the URL of the issue creation page as [URL OF ISSUE TEMPLATE] and save for later use.  
- [ ] Verify the appearance of the issue template.
- [ ] Complete the Pull Request process by visiting the URL saved from the push command.
- [ ] In the PR copy/paste this text immediately before the section "Screenshots of Proposed Changes Of The Website"
 ```
 ### For Reviewers
- Use this URL to check the updated issue template: [URL OF ISSUE TEMPLATE]
```
- [ ] Replace the text in the square brackets (as well as the square brackets) with the URL of the updated issue template
- [ ] Submit your pull request with your changes for review
- [ ] After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable Issues feature

### For Merge Team
- [ ] Release the dependency for this issue in #6163. If all the dependencies have been completed, close that issue.

### Resources/Instructions
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/[INSERT_PATH_TO_FILE]?plain=1

- This issue is part of #6163.

---
## Title: Correct Capitalization of `Slack` in [INSERT_FILE_NAME] (for all other files)
(good first issue)

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to fix the following line of code to correctly capitalize "Slack" when it's used to refer to the app or the company in our code and content.
[INSERT_LINE_PERMALINK]

### Action Items
- [ ] Open the file `[INSERT_PATH_TO_FILE]` in your code editor
- [ ] On Line [INSERT_LINE_NUMBER], replace every `slack` with `Slack` **when it's used to refer to the app and the company**, **do not make changes within URLs**.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.
- [ ] Create a pull request with your changes

### For Merge Team
- [ ] Release the dependency for this issue in #6163. If all the dependencies have been completed, close that issue.

### Resources/Instructions
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/[INSERT_PATH_TO_FILE]?plain=1

- This issue is part of #6163.

---

**Comment by tony1ee** [comment]
Since we are working with different types of files (css, html, CONTRIBUTING.MD, issue templates), please advise if we need to instruct (and if so, the wording of) the contributors to test their changes. 

For example, I adapted from [issue template testing procedure](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing instructions but it seems to complicate the issues beyond `first good issue` level

**Comment by roslynwythe** [comment]
@tony1ee I agree completely.  In general, issues updating HTML and CSS can be `good first issue` if they are sufficiently presciptive, and that includes instructions on which page to test and what to look for.  Issues that modify CONTRIBUTING.md are generally `Complexity: Small` and should include the link that explains how to check CONTRIBUTING.md in dev's fork.  I usually make updates to issue templates as `Complexity: Medium` because the testing is rather involved.

**Comment by tony1ee** [comment]
@roslynwythe Thanks. That does make sense to me. I've updated the templates to include the label suggestion.

Please review my issue template comments above, and let me know when I can start making issues from them.

**Comment by roslynwythe** [comment]
@tony1ee were you planning to create the issues for correcting the capitalization, or are you planning to create three "Issue Making: Level 1" issues?

**Comment by tony1ee** [comment]
@roslynwythe based on the ER description I was treating this ER as an issue making issue and the next step would be creating 10 issues for fixing the capitalization. Let me know if this should be handled differently.

**Comment by roslynwythe** [comment]
@tony1ee this is labelled "Issue Making: Level 2", meaning that it involves the creation of a template and an `Issue making: level 1` issue.  However, if you feel that it would be easier for you to go ahead and create the issues for fixing the capitalization yourself, I think it would be fine.  We can discuss on Sunday or Monday.

**Comment by ExperimentsInHonesty** [comment]
@tony1ee if you decide to go ahead and make the issues, please move this issue to the in progress column. If you make the template and the Issue making: level 1 issue for other people to create the issues, then once you have done that and we have approved them, this ER can be closed.

The benefit of making the template and the issue to make the issues, is that you can move on to higher value items, and allow the people who are just finished with their small issue to start making issues.  This ER might be sufficiently complex that it is better to make the issues directly.  We will let you decide.

**Comment by tony1ee** [comment]
Update: no changes will be needed to correct the last occurrence in the list:
- https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/pages/project-meetings.html#L14
as the text referenced was already replaced with new text:
- https://github.com/hackforla/website/blob/3013961d0a3ab52a537b0cea745b8086038ed0ad/pages/project-meetings.html#L12

**Comment by tony1ee** [comment]
I will work on creating **Issue Making Issues** for 
1. correcting issue templates (5 issues can be made from this IMI) 
2. correcting CONTRIBUTING.MD (3 issues can be made from this IMI)

And make an **issue** directly for:
- fixing [website/_sass/components/_communities-of-practice.scss](https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/_sass/components/_communities-of-practice.scss#L131)

All using the templates above.

**Comment by tony1ee** [comment]
**Availability**: 05/08/2024 & 05/09/2024 afternoon and evening
**ETA**: 05/09/2024 EOD

**Comment by tony1ee** [comment]
Looks like https://github.com/hackforla/website/blob/3c7c90e384563e35f5535a2784e1bca8b9cd2639/.github/ISSUE_TEMPLATE/pre-work-template--dev.md?plain=1#L84
does not need any changes as it's spelled correctly. I also verified this line in the current `gh-pages` latest commit.  
This is the 8th item in the main comment.

**Comment by tony1ee** [comment]
- [x] Issue #6845, a `good first issue`
- [x] Issue Making Issue #6844 for 3 CONTRIBUTING.MD `small` issues
- [x] Issue Making Issue #6842 for 4 issue template `medium` issues
- [x] Determined that change is no longer needed for 2 instances (see comments above)

Ready to be reviewed

**Comment by tony1ee** [comment]
Progress: created 1 issue and 2 issue making issues.
Blockers: #6842 pending approval by @roslynwythe , the other two are approved by dev lead and pending prioritization
Availability: N/A
ETA: N/A

Expect to close this ER after all issues created are approved.

**Comment by tony1ee** [comment]
all created issues approved/prioritized. Closing this ER.
