### ISSUE TITLE
website-wiki repo readme setup readme development and testing

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6195]
### Overview
We need to validate the development environment setup instructions in the README file for the website-wiki work for other developers.

### Action Items
- [x] Try to follow the instructions
- [x] add notes below as you go
- [ ] Meet with Vanessa and review issues that came up
- [ ] Resolve and update the document.

### Resources/Instructions
readme: https://github.com/hackforla/website-wiki/blob/main/README.md
see the wiki live: https://hackforla.github.io/website-wiki

**Comment by ExperimentsInHonesty** [comment]
### readme Docker notes
1. it would have been helpful if it told me to fork it to my own github profile, then customize the URL
2. why is the latest docker image on Vanessa's repo instead of the github.com/hackforla/website-wiki repo?
![image](https://github.com/hackforla/website-wiki/assets/37763229/d63485c0-22c3-4200-8d71-6f8c7170200a)
I did try to use the URL but with hackforla instead of vraer instead and got the following error message: 
>Error response from daemon: pull access denied for hackforla/hfla-website-wiki, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

but it did work with vraer
3.  I tried to run docker run --rm -it -v ${PWD}:/docs vraer/hfla-website-wiki:latest build
and I got the following error message
> docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "build": executable file not found in $PATH: unknown.

I tried updating docker and still got the same thing so I stopped there.

**Comment by ExperimentsInHonesty** [comment]
### readme python
1. I tried running python3 -m venv venv and got the following error
>Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases. 

So I ran python3 and it launched an installer from the microsoft store which I used.

Then I ran python3 -m venv venv again and it seemed to work.

2. Then I ran source venv/bin/activate and got the following error
> source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
`At line:1 char:1`
`+ source venv/bin/activate`
`+ ~~~~~~`
`    + CategoryInfo          : ObjectNotFound: (source:String) [],` `CommandNotFoundException`
`    + FullyQualifiedErrorId : CommandNotFoundException`

So I stopped there

**Comment by ExperimentsInHonesty** [comment]
My vs code promted me to install some extentions for docker, so I did and ran
docker run --rm -it -v ${PWD}:/docs vraer/hfla-website-wiki:latest

and got a different error this time
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/git/__init__.py", line 89, in <module>
    refresh()
  File "/usr/local/lib/python3.10/site-packages/git/__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "/usr/local/lib/python3.10/site-packages/git/cmd.py", line 393, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 59, in serve
    config = get_config()
  File "/usr/local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 47, in get_config
    config = load_config(
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/base.py", line 378, in load_config
    errors, warnings = cfg.validate()
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/base.py", line 230, in validate
    run_failed, run_warnings = self._validate()
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 182, in validate
    return self.run_validation(value)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1064, in run_validation        
    self.load_plugin_with_namespace(name, cfg)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1102, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1120, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/mkdocs_git_revision_date_localized_plugin/plugin.py", line 21, in <module>
    from mkdocs_git_revision_date_localized_plugin.util import Util
  File "/usr/local/lib/python3.10/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 10, in <module>
    from git import (
  File "/usr/local/lib/python3.10/site-packages/git/__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

**Comment by ExperimentsInHonesty** [comment]
### Tasks
- get Vanessa help to upload the docker image she has created for website-wiki to our docker hub.

**Comment by vraer** [comment]
Hey @ExperimentsInHonesty 

I published a [new branch](https://github.com/hackforla/website-wiki/tree/update-docker) to the website-wiki repo with several updates/hopefully fixes to our install problems.

To sum it up briefly:
- Minor updates to Dockerfile
- Addition of docker-compose.yml (**this should make things much easier for everyone**)
- Updated README instructions with commands for using docker-compose and added Windows commands for python method
- Removed `git-revision-date-localized` plugin from mkdocs.yml and requirements.txt

@roslynwythe please test this locally when you get a chance and let me know if you're still seeing those errors :)

**Comment by ExperimentsInHonesty** [comment]
### Starting installation test again 2023-02-26.
- deleted the fork
- forked the repo again
- cloned the repo
- ran `docker-compose up`
  - got an error
  - started docker desktop 
  - tried again
  - it worked
- ran `docker-compose up`
- site was viewable at localhost 🥇 

## Next steps
- [ ] update https://github.com/hackforla/website-wiki/blob/main/README.md to add instruction After 
  >Getting Started
  and before 
  >Clone or Fork the Repository
- [ ] Move docker image to HackforLA Docker
