### ISSUE TITLE
Update Project Profile: Food Oasis (Reorder leadership member)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6313]
### Dependency
- [x] #6317 

### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to reorder the way the leadership team members are displayed on the Food Oasis page so that members with the same role are grouped together and it looks more organized.

### Action Items
- [x] In your IDE, open the `_projects/food-oasis.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Under the `leadership` section, find Hannah Zulueta's profile information.
- [x] Then, move Hannah Zulueta's profile information so it is after John Darragh's profile information. The resultant code should be:
```
leadership:
  - name: John Darragh
    role: Lead Developer
    links:
      slack: "https://hackforla.slack.com/team/UFLDX9V19"
      github: "https://github.com/entrotech"
    picture: https://avatars.githubusercontent.com/entrotech
  - name: Hannah Zulueta
    role: Lead Developer
    links:
      slack: "https://hackforla.slack.com/team/U9SCMTNK0"
      github: "https://github.com/hanapotski"
    picture: https://avatars.githubusercontent.com/hanapotski
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Food Oasis page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/food-oasis

**Comment by JessicaLucindaCheng** [comment]
### Issue Writing
- **Progress:** I am done writing this issue but need my question under _Blockers_ answered to determine next steps for this issue.
- **Blockers:** I asked the following in the fola Slack channel:
  > On the [Food Oasis](https://www.hackforla.org/projects/food-oasis) page, there is a link to [Hannah Zulueta](https://hackforla.slack.com/team/U01G7AH18J3)'s deactivated Slack account profile. Is Hannah still an active member of the team? Thanks

  - Link to post: https://hackforla.slack.com/archives/CMER3R1RD/p1708228389487439
  - Answer: Hannah's active Slack account is https://hackforla.slack.com/team/U9SCMTNK0
- **Availability:** Dependent on blocker being answered
- **ETA:** Dependent on blocker being answered

### Tasks
- [x] Write an issue to fix Hannah's Slack link so its the active account.
- [x] Fix the link in this issue to be the active one too
- [x] Finalize this issue

**Edit:** I'm done writing this issue.

**Comment by JessicaLucindaCheng** [comment]
Once this issue is in the New Issue Approval column, a dev lead needs to review the issue and determine if it is ready for a PM to prioritize it.

**Comment by t-will-gillis** [comment]
Hi @JessicaLucindaCheng - I am looking over this issue. The main thing I see is that Hannah Zulueta and John Darragh need `github-handle: `

I can either add the two handles to this issue OR write a new issue for adding the handles. Your thoughts?

I think it is easy enough to address the handles with this issue (with some reordering)- and if you agree I will do that.

**Comment by JessicaLucindaCheng** [comment]
@t-will-gillis 

> Hi @JessicaLucindaCheng - I am looking over this issue. The main thing I see is that Hannah Zulueta and John Darragh need `github-handle: `
> 
> I can either add the two handles to this issue OR write a new issue for adding the handles. Your thoughts?
> 
> I think it is easy enough to address the handles with this issue (with some reordering)- and if you agree I will do that.

Thanks for asking! I left it off because
1) I think adding `github-handle:` to existing leadership members is a separate problem, and
2) I know we are using the add `github-handle:` for good first issues. I think eventually someone will write issues for adding `github-handle:` to existing leadership members of the Food Oasis project as part of this epic #5441.

**Comment by t-will-gillis** [comment]
@JessicaLucindaCheng Sounds good! I'll add `Ready for Prioritization` then

**Comment by angela-lee1** [comment]
Availability: 6:00pm -10:00pm 2/26, 2/27
ETA: EOD 2/28
