### ISSUE TITLE
epic: eliminate XSS vulnerability throughout codebase

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6380]
### Overview
We need to examine every Javascript code file for instances in which DOM Elements are dynamically created  by setting the innerHTML property, based on user-generated strings, and to update code as needed, to eliminate the risk of Cross-site scripting (XSS) attacks. 

### Details
- Composing DOM Elements by setting the `innerHTML` property based on user-provided data is an unsafe practice because malicious users can construct strings that result in the execution of scripts within the browser.  Instances of this pattern do exist in our codebase because it was believed that parsing the data using decodeURIComponent() would eliminate any risk, however that may not be the case.  
- In #5654 an XSS vulnerability was identified and resolved in wins.js.  In this epic we need to audit the remaining Javascript codebase and update the code as needed.  

### Action Items
- [ ] Create an epic for auditing of every Javascript file within `/assets/js` for instances of unsafe usage.    
   - [ ] Create a spreadsheet "HfLA Javascript audit" with columns to track issues for audit, the results of the audit (which sections of code should be refactored), and to track issues for fixing code
   - [ ] Create a template for audit issues and an issue level 1 making issue to create the new issues
- [ ] If there are multiple sections of code that need to be refactored, create an epic for refactoring
   - [ ] Create a template for refactoring issues and an issue level 1 making issue to create the new issues

### Resources/Instructions
- This epic resulted from #5654

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty  Would it be better if the Action Items on this issue called for the creation of two child epics, one for auditing the codebase and the other for refactoring?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe yes

**Comment by roslynwythe** [comment]
I don't believe there are any instances of code (other than wins.js) in which present a risk, so closing this issue
