### ISSUE TITLE
ER: Need epic for enhancing all GHAs to use a common key value json file

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6389]
### Emergent Requirement - Problem
We need an epic to manage the enhancing of all GHAs to use a key/value json file.  I only can find this one issue, not an epic for all of it.

### Issue you discovered this emergent requirement in
- #5205

### Date discovered 
2024-02-28

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
- There are a ton of follow on actions that are all dependent on this happening
  - after all the website GHAs are renhanced, then they are going to be exported to the .github repo and then made useable for all teams
  - once all teams can use them, then teams will start using the 2 week inactive, and the gha and scripts that remove people from the repo and drives
- This is crucial because it turns out there can only be 600 people on any Google Drive, so we have to have an automated way to remove people and GitHub activity is that way.

### Resources
https://github.com/hackforla/.github
https://github.com/hackforla/open-source-automations-for-org/issues/10

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by t-will-gillis** [comment]
Discussion topic, when we are ready to make the epic for refactoring the GHAs: how do we plan to address the `/ISSUE_TEMPLATE/` markdown files since these also directly reference labels and I don't believe the md issue templates will work with the label directory, though there are some possible workarounds.

**Comment by t-will-gillis** [comment]
- #6454 intended to be the Epic for refactoring the GHAs to use the common key-value pair
