### ISSUE TITLE
Epic: Create issues to update GHA wiki pages with testing info

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6402]
### Dependencies
- [x] #4819
- [ ] #6403 (we need to know which ones are new, so we don't have to update them)
- [ ] new wiki accepting changes and contributions

### Overview
We need to update wiki pages for GHAs

### Details
Ensure that every GitHub Action is documented in the wiki, and add sections to each wiki GHA page, that provide information about relevant issue labels Aand instructions on how to test the GHA. 

#### Issue for updating the main GitHub wiki page:
- [x] #4841

#### Issues for updating existing GHA wiki pages:
- [x] #4856
- [ ] Update GitHub Data wiki page 
   ```
   ### Resources
   - [github data](https://github.com/hackforla/website/wiki/GHA:-github-data)
   - [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#github-actions-architecture)
   - This epic is a result of ER #4728
   ```
- [x] #5166
- [x] #6399 

#### Template for issues that review/update existing GHA wiki pages 
```
### Action Items
- [ ] Become familiar with [HfLA's GitHub Actions main wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) and [HfLA GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions).
- [ ] Become familiar with [REPLACE WITH LINK TO GHA-SPECIFIC PAGE].  Follow links to the `yml` and `js` files and understand the logic of the GHA.  
- [ ] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki).  Follow the process given in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) when completing the remaining Action Items.  
- [ ] On [HfLA GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) make any necessary updates to the summary of [REPLACE WITH GHA], then review/update the [REPLACE WITH LINK TO GHA-SPECIFIC PAGE] page for accuracy and completeness, and add the new sections
  - [ ]  "Labels" - List those labels on which the GHA depends or affects.  
  - [ ]  "Test Procedure" - Detail the process for testing the GHA in case there is a change in a dependent label/resources/package.  

### Resources/Instructions
- [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#github-actions-architecture)
- This epic is a result of ER #4728
```

#### Workflow file list
- [GitHub Workflows](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Workflows and GHA wiki Audit](https://docs.google.com/spreadsheets/d/1twpWLg6-EkU1UhIaCMIdE8SuyvTLcyKh16MTtR5awkQ/edit#gid=0) spreadsheet

**Comment by ExperimentsInHonesty** [comment]
Need to determine which labels these new issues will have
