### ISSUE TITLE
Epic: Create GitHub Action Wiki pages

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6403]
### Dependency
- [x] #4819 ((this issue needs to be updated with a list of pages missing produced by this issue)

### Overview
We need to make wiki pages for the GHAs that don't yet have them

#### Issue for new page "How to Test/Review GHA Issues"
- [ ] Create a new wiki page to outline the process of testing GHAs and reviewing GHA Pull Requests.  
- [ ] Create a page for each workflow providing testing guidance or link to existing page with that information
   - [ ] For those workflows that contain multiple custom .js scripts, provide testing guidance for each .js script

#### Issue for updating the main GitHub wiki page:
- [x] #4841

#### Issues for updating existing GHA wiki pages:
- [x] #4856
- [x] #5166
- [x] #6399 
- [x] #6643
- [ ] Review/Update GHA: lint scss
- [ ] Review/Update GHA: move closed issues
- [ ] Review/Update GHA: pr instructions - describe the scripts
- [ ] Review/Update GHA: https://github.com/hackforla/website/wiki/GHA:-pull-request-trigger
- [ ] Review/Update GHA: set pr labels
- [ ] GHA: vrms data
- [ ] GHA: wr pr instructions
- [x] #6968 

#### Issues for new pages
- [ ] GHA: CodeQL
```
### Action Items
- [ ] Become familiar with [HfLA's GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) and [HfLA's GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) 
- [ ] Edit [HfLA's GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) adding a new summary to describe [REPLACE WITH GHA].  
- [ ] Create a new wiki page to document [REPLACE WITH GHA] following the template
- [ ] Place link to the new page on [HfLA's GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) 

### Resources/Instructions
- [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#github-actions-architecture)
- This epic is a result of ER #4728
```

### Resources/Instructions
- [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#github-actions-architecture)
- This epic is a result of ER #4728

#### Workflow file list
- [GitHub Workflows](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Workflows and GHA wiki Audit](https://docs.google.com/spreadsheets/d/1twpWLg6-EkU1UhIaCMIdE8SuyvTLcyKh16MTtR5awkQ/edit#gid=0) spreadsheet
- https://github.com/hackforla/website/issues/6402

**Comment by ExperimentsInHonesty** [comment]
Need to determine which labels these new issues will have

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe There are two issues
- This one #6403
- and #6402 

This one is supposed to be for creating any GHA pages in the WIKI that are missing them
6402 is supposed to be for adding the testing info, which is why it has this issue as a dependency.  But instead they are almost identical.  Please update both issues.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I was looking at the ready for prioritization issues and came across 
- https://github.com/hackforla/website/issues/6643 which instructs the assignee to 

>- [ ] "Test Procedure" - Detail the process for testing the GHA in case there is a code change or a change in a dependent label, resource or package.

I didn't see any documentation for how to write tests or test procedures, or which GHAs have tests that the assignee can review as an example.  

- [ ] Do the GHAs already have tests or test procedures, and the person is just documenting them?
- [ ] Or are they expected to write procedures that should be followed when a change is made to the GHA?

**Comment by roslynwythe** [comment]
> @roslynwythe I was looking at the ready for prioritization issues and came across
> 
> * [Update wiki page for GitHub Action: github-data #6643](https://github.com/hackforla/website/issues/6643) which instructs the assignee to
> 
> > * [ ]  "Test Procedure" - Detail the process for testing the GHA in case there is a code change or a change in a dependent label, resource or package.
> 
> I didn't see any documentation for how to write tests or test procedures, or which GHAs have tests that the assignee can review as an example.
> 
> * [ ]  Do the GHAs already have tests or test procedures, and the person is just documenting them?
> * [ ]  Or are they expected to write procedures that should be followed when a change is made to the GHA?

- The existing GHA wiki pages do not include testing guidance, but this completed issue #4856 for updating an existing GHA wiki page did have that requirement, and I think the resulting guidance is very useful; in fact I used it myself to review some PRs and I made a tiny improvement.  If you approve, I will mention this issue as an example.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe

- I do approve and went ahead and revised the action item checkbox in https://github.com/hackforla/website/issues/6643 to say 

> - [ ]  "Test Procedure" - Detail the process for testing the GHA in case there is a code change or a change in a dependent label, resource or package. (see the Test Procedure example in this issue comment Update wiki page for GitHub Action: "add update label weekly"  #4856 (comment))

I also put it in the prioritized backlog
