### ISSUE TITLE
Update Pre-Work Checklist (Dev) with Section 1.7

### ISSUE THREAD

**Issue by danvgar** [hackforla/website#6451]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
The Pre-Work Checklist is used to properly onboard new members with the Hack for LA process. 
At the moment the`Pre-Work Checklist - Dev` only lists completing steps 1.1-1.6 of CONTRIBUTING.md.
It should be amended to list completing steps 1.1-1.7 of CONTRIBUTING.md

### Action Items
- [x] If issue https://github.com/hackforla/website/issues/4944 is closed DO NOT WORK ON THIS ISSUE, instead move this issue to the Questions column, and add the `ready for dev lead label`
- [x] In your local IDE, navigate to `.github/ISSUE_TEMPLATE/pre-work-template--dev.md`
- [x] Replace 
```
- [ ] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
```
with
```
- [ ] Complete steps 1.1 - 1.7 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
```
- [x] With `pre-work-template--dev.md` still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.
- [x] Changes to `pre-work-template--dev.md` cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/.github/ISSUE_TEMPLATE/pre-work-template--dev.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/.github/ISSUE_TEMPLATE/pre-work-template--dev.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
- [Pre-Work Checklist - Dev](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/pre-work-template--dev.md)
- [Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #6041

**Comment by danvgar** [comment]
Hi @lukewangm , this issue is still awaiting approval and isn't ready to be worked on. Please only pick up issues within the [Prioritized Backlog](https://github.com/hackforla/website/projects/7#column-7198257) column! Thank you! :)

**Comment by ExperimentsInHonesty** [comment]
- This has been integrated into the issue that was already started: https://github.com/hackforla/website/issues/4944#issuecomment-2144457123

I am prioritizing this issue, only if issue https://github.com/hackforla/website/issues/4944 has not been finished.

**Comment by elisetvy** [comment]
**Availability**: today 6/5
**ETA**: EOD
