### ISSUE TITLE
epic: Refactor img tags in CONTRIBUTING.md to end without a slash

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6453]
Issues for removing closing slash from CONTRIBUTING.md:
- [x] #5619
- [x] #5620
- [x] #5621 
- [x] #5146 
- [x] #5703
- [x] #7093 
- [x] #7094 
- [x] #7095
- [x] #7096 
- [x] #7097 
- [x] #7098
- [x] #7797 
- [ ] #7835 
### Overview
We need to prepare the remaining issues that will remove the closing slash from img tags within CONTRIBUTING.md.  

### Action Items
- [x] Find rows in HfLA-Website: img Tag Audit spreadsheet[^1] where the "Path to file" column is `CONTRIBUTING.md` and for which the "Link to good first issue" column is blank.   These are the rows which require new issues.  
- [x] For each row matching the above criteria, create an issue using the template text in https://github.com/hackforla/website/issues/5040#issuecomment-1650570533
   - [x] Give each issue a unique title that describes the location of the issue
   - [x] Replace `[Section number]` with the section number 
   - [x] Replace `[INSERT LINE OF CURRENT CODE HERE]` with the matching column of the spreadsheet
   - [x] Replace `[INSERT DESIRED LINE OF CODE HERE]` with the matching column of the spreadsheet
- [x] List each issue above under "Issues for removing closing slash"
- [x] After all issues have been created, move this issue into the "Ice Box" and add a `Dependency` label

### Resources/Instructions
- This epic resulted from #4362 
[^1]: HfLA-Website: img Tag Audit spreadsheet's [img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0&fvid=959329398)

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe ~can we move this issue to the icebox?  Is there anything else it needs for the draft to be complete?~  Nevermind.

I just realized that those are the issues that have been made, not a dependency.  So can we remove the dependency and the draft label and move this into the Epics and ER that are ready to make issues?

**Comment by roslynwythe** [comment]
> @roslynwythe ~can we move this issue to the icebox? Is there anything else it needs for the draft to be complete?~ Nevermind.
> 
> I just realized that those are the issues that have been made, not a dependency. So can we remove the dependency and the draft label and move this into the Epics and ER that are ready to make issues?

OK I will do that, but first I want to check that this is a complete list of issues.  I just glanced at the spreadsheet and it looks like there might be more instances of img tags that need to be fixed in CONTRIBUTING, than I listed above, so I need to go through the list again to check.

**Comment by ExperimentsInHonesty** [comment]
I see the following ending slashes in the contributing file.  Unless they are new it seems like they might have been missed

https://github.com/hackforla/website/blob/769544a076eb35e50c7914262c52733d7a4ea09b/CONTRIBUTING.md?plain=1#L845
https://github.com/hackforla/website/blob/769544a076eb35e50c7914262c52733d7a4ea09b/CONTRIBUTING.md?plain=1#L924

**Comment by ExperimentsInHonesty** [comment]
I found more items, see comment above.  Issues need to be made for this epic before its closed.

**Comment by ExperimentsInHonesty** [comment]
I added to new lines to the spreadsheet and unchecked all the action items so that this issue can get finished.

**Comment by HackforLABot** [comment]
Hi @dvernon5, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by dvernon5** [comment]
@HackforLABot 
Availability: Mon-Thurs 9AM - 6PM  Fri: 9AM - 4PM
ETA: Wednesday 12PM

**Comment by t-will-gillis** [comment]
Thanks for creating the issues- closing as successfully completed.
