### ISSUE TITLE
Create spellcheck audit issues from line 81-90 of spreadsheet

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6499]
### Overview
We need to create issues for the spellcheck audit.  The filepaths for the required issues are found in lines 81-90 of the HfLA spelling audit spreadsheet[^1]

### Action Items
- [x] For each line 81-90 in the HfLA spelling audit spreadsheet[^1]
   - [x] Copy the filepath (for example `pages/toolkit.html`) from column A then create a new issue using the "Spell check audit web page template"[^2]
   - [x] Replace the text `[INSERT FILE HERE]` with the filename (for example `toolkit.html`)
   - [x] Replace the text `[INSERT FILE PATH]` with the full file path (for example `pages/toolkit.html`)
   - [x] Click "Submit New Issue"
   - [x] Copy the issue number and use it to create a link below under "Child Issues that this issue creates" (for example if you enter `- [ ] #6497`, GitHub will expand that into an issue link
   - [x] Copy the issue number and paste it into the "Link to Audit Issue" column in the spreadsheet in the row that corresponds to the filepath
- [x] When all issues have been created, move this issue into the "Questions/In Review" column and add the label "ready for dev lead"

#### Note for Dev Leads after issue signoff
- [x] Add all the issues created by this issue to the Epic #5248

### Resources/Instructions
- This issue is part of #5248
[^1]:[HfLA spelling audit spreadsheet](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1277680545)
[^2]:[Spell check audit web page issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Small%2C+Feature%3A+Administrative%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&projects=&template=spell-check-audit.md&title=Run+VS+Code+Spell+Checker+on+%5BINSERT+FILE+HERE%5D)

#### Child Issues that this issue creates
- [x] #6569 
- [x] #6570 
- [x] #6571
- [x] #6572
- [x] #6573
- [x] #6574
- [x] #6575
- [x] #6576 
- [x] #6577
- [x] #6578

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty please see https://github.com/hackforla/website/issues/5248#issuecomment-2011381056 for context on this issue.  As I mentioned in that comment, I'm not sure if this current issue should be titled/labelled as an epic.   Also I wasn't sure if the child issues (dependencies) should be listed in this issue or back in #5248.  If it looks ok, please prioritize.

**Comment by t-will-gillis** [comment]
Hey @lukewangm Great job- the issues all look correct. Closing this 'issue making issue' as completed. 
Thanks for generating these issues!
