### ISSUE TITLE
How to move a commit from one repo to another repo

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6595]
### Overview
We need to write instructions for how to move a commit from one repo to another repo so that leads at Hack for LA can move files between repos when needed.

### Action Items
- [ ] In a new comment below, write instructions for how to move a commit from one repo to another repo.

### Resources/Instructions
- Link to instructions: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- https://www.elliotblackburn.com/cherry-pick-git-commit-across-repository/

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty Once you prioritize this issue, please assign me to it. Thanks.

**Comment by JessicaLucindaCheng** [comment]
# [WIP DRAFT] How to move a commit from one repo to another using cherry-pick

These instructions were adapted from [Elliot Blackburn's _Moving a git commit from one repository to another_](https://www.elliotblackburn.com/cherry-pick-git-commit-across-repository/).

## Prerequisites
- You know how to or can figure out how to
   - find a commit SHA,
   - use git commands,
   - fork a repository (repo),
   - clone the forked repo onto your computer, and
   - create a new branch based on an existing branch.

## Notes
- If you are trying to preserve author history when moving a file to another repo, the following instructions will only work if you want to move a file with only one commit in its history.
- The instructions are written to adhere to the workflow on the Hack for LA Website Team.

## Assumptions
1. You are using GitHub to host your remote repositories.
2. The repository for where the commits will come from and the repository for where the commits will be moved to exist already or have been created. Also, the repositories have at least one branch, such as the main or master branch.
3. You have Git installed on your local machine. If you need instructions on how to install Git on your local machine, see section [1.2 Dev setup (2): Installing Git](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#12-dev-setup-2-installing-git) from the Hack for LA Website Team's CONTRIBUTING.md file.

## Instructions

### A. Copy Commits From One Repository to Another

#### Forking and Cloning Repositories
On GitHub, do the following
1. Fork the repo where you want to copy the commits to [^fork-a-repo]. For these instructions, I will refer to this as the `forked new repo`.
2. In your `forked new repo`, create a new branch based on the branch you want to work off of, such as the main or master branch [^creating-a-branch]. I will refer to this as the `working branch` and this will be the branch you push your work to.
3. Fork the repo where you have the commits currently [^fork-a-repo]. For these instructions, I will refer to this as the `forked old repo`.
4. Clone a copy of your `forked old repo` to your local machine [^cloning-your-forked-repo].
5. For the commit(s) you want to copy, find the commit(s) SHA. There are multiple ways to find the commit SHA, including on GitHub or locally on your computer [^find-commits-SHA].

#### On Your Local Machine, Copy Commits
6. On your local machine, in your `forked old repo`, add a remote that will fetch and push to your `forked new-repo` [^moving-a-commit-to-another-repo][^adding-a-remote-repo].
   ```
   git remote add [FORKED-NEW-REPO-NAME] https://github.com/[GITHUB-HANDLE]/[FORKED-NEW-REPO-NAME].git
   ```
   - Replace [FORKED-NEW-REPO-NAME| with the name of your remote `forked new repo`.
   - Replace [GITHUB-HANDLE] with your GitHub handle.
   - Replace [FORKED-NEW-REPO-NAME| with the name of your remote `forked new repo`.
7. Fetch your forked new repo [^git-fetch].
   ```
   git fetch [FORKED-NEW-REPO-NAME]
   ```
   - [FORKED-NEW-REPO-NAME| is the name of your remote forked new repo.
8. Create a local branch based on your `forked new repo's working branch` [^moving-a-commit-to-another-repo][^git-checkout]. 
   ```
   git checkout -b [WORKING-BRANCH-NAME] --track [FORKED-NEW-REPO-NAME]/[WORKING-BRANCH-NAME]
   ```
   - [WORKING-BRANCH-NAME] should be replaced with the name of your `forked new repo's working branch`.
   - [FORKED-NEW-REPO-NAME] should be replaced with the name of your `forked new repo`.
9. Cherry-pick the commit you want to copy [^moving-a-commit-to-another-repo][^git-cherry-pick].
   ```
   git cherry-pick [COMMIT-SHA]
   ```
   - [COMMIT-SHA] should be replaced with the commit SHA.
10. If you have more commits to copy, repeat steps 8 and 9.
11. Push cherry-picked commit to the new-repo [^moving-a-commit-to-another-repo][^git-push].
   ```
   git push [FORKED-NEW-REPO-NAME] [WORKING-BRANCH-NAME]
   ```
   - [FORKED-NEW-REPO-NAME] should be replaced with the name of your remote forked new repo.
   - [WORKING-BRANCH-NAME] should be replaced with the name of your `forked new repo's working branch`.

#### Create a Pull Request
12. When creating your pull request [^creating-a-pull-request], 
   - **Base repository** should be the original repo where you want to copy the commits to.
   - **Base** should be the branch where you want to copy the commits to.
   - **Head repository** should be your forked new repo.
   - **Compare** should be your forked new repo's working branch.
   - Example:
   [REDO IMAGE WITHOUT ANNOTATIONS]
  <img alt="" src="https://github.com/user-attachments/assets/87b0de4f-975b-48b1-87fe-a8daf193caaf">

### Merge the pull request
[ADD INSTRUCTIONS HERE]
- I recommend using rebase merging to preserve who authored the file.
- To see examples of the commit history of the various methods of merging, see these branches in my forked repo:
  - [Using rebase & merge](https://github.com/JessicaLucindaCheng/data-science/commits/rebase-merge): Recommended
  - [Using merge commit](https://github.com/JessicaLucindaCheng/data-science/commits/merge-commit): Okay but results in an additional commit.
  - [Using squash & merge](https://github.com/JessicaLucindaCheng/data-science/commits/squash-merge): Not recommended because it doesn't preserve author's credit

## B. Remove files from the old repo
Delete the files 
[ADD INSTRUCTIONS HERE]

## Resources
[^fork-a-repo]: [Forking a repository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#forking-a-repository)
[^creating-a-branch]: [Creating a branch via the branches overview](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository#creating-a-branch-via-the-branches-overview)
[^cloning-your-forked-repo]: [Cloning your forked repository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#cloning-your-forked-repository)
[^moving-a-commit-to-another-repo]: [Moving a git commit from one repository to another](https://www.elliotblackburn.com/cherry-pick-git-commit-across-repository/)
[^adding-a-remote-repo]: [Adding a remote repository](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#adding-a-remote-repository)
[^git-checkout]: [git checkout](https://git-scm.com/docs/git-checkout)
[^find-commits-SHA]: [Finding a commit's SHA](https://stackoverflow.com/a/4784629)
[^git-cherry-pick]: [git cherry-pick](https://git-scm.com/docs/git-cherry-pick)
[^git-push]: [git push](https://git-scm.com/docs/git-push)
[^creating-a-pull-request]: [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
[^git-fetch]: [git fetch](https://git-scm.com/docs/git-fetch)
[^creating-a-branch]: [Creating a branch via the branches overview](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository#creating-a-branch-via-the-branches-overview)
[^git-fetch]: [git fetch](https://git-scm.com/docs/git-fetch)

**Comment by JessicaLucindaCheng** [comment]
### Issue Progress Update
- **Progress:** Started a first draft: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- **Blockers:** None
- **Availability:** 6 hours
- **ETA:** Complete a first draft Thursday, April 18, 2024

**Comment by JessicaLucindaCheng** [comment]
### Issue Progress Update
- **Progress:** Started a first draft: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- **Blockers:** None
- **Availability:** 6 hours
- **ETA:** June 1, 2024

**Comment by JessicaLucindaCheng** [comment]
### Issue Progress Update
- **Progress:** Started a first draft: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- **Blockers:** None
- **Availability:** 6 hours
- **ETA:** July 1, 2024

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 13, 2024 at 12:14 PM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, August 27, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 3, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 10, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 17, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, September 24, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 1, 2024 at 12:04 AM PST.</sub>

**Comment by JessicaLucindaCheng** [comment]
### Issue Progress Update
- **Progress:** Started a first draft: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- **Blockers:** None
- **Availability:** Not sure for this issue this week
- **ETA:** Will give an updated ETA by October 14, 2024

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 15, 2024 at 12:04 AM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 22, 2024 at 12:04 AM PST.</sub>

**Comment by JessicaLucindaCheng** [comment]
### Issue Progress Update
- **Progress:** Started a first draft: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- **Blockers:** None
- **Availability:** Not sure for this issue this week
- **ETA:** TBD

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, November 4, 2024 at 11:04 PM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, November 11, 2024 at 11:04 PM PST.</sub>

**Comment by JessicaLucindaCheng** [comment]
### Issue Progress Update
- **Progress:** Started a first draft: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- **Blockers:** None
- **Availability:** Not sure for this issue this week
- **ETA:** TBD

### Tasks
- Note: cherry-pick only moves the specific commit and not the whole history
- [ ] Will cloning both repos at beginning, remove need to git fetch new repo later?
- [ ] Way to directly cherry-pick items into a specific folder? Or need to work on moving files on the branch after pushing commits to remote? Or separate issue?

**Comment by ExperimentsInHonesty** [comment]
about commits: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/about-commits

**Comment by ExperimentsInHonesty** [comment]
create an issue here to make a new guide https://github.com/hackforla/knowledgebase-content/issues/new/choose

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, December 30, 2024 at 11:04 PM PST.</sub>

**Comment by JessicaLucindaCheng** [comment]
### Issue Progress Update
- **Progress:** Started a first draft: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- **Blockers:** None
- **Availability:** 8 hours
- **ETA:** Monday, January 6, 2025

### Tasks
- [ ] Create an issue here to make a new guide https://github.com/hackforla/knowledgebase-content/issues/new/choose
- [ ] Add info about commits and link to https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/about-commits
- Note: cherry-pick only moves the specific commit and not the whole history
- [ ] Will cloning both repos at beginning, remove need to git fetch new repo later?
- [ ] Way to directly cherry-pick items into a specific folder? Or need to work on moving files on the branch after pushing commits to remote? Or separate issue?

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, January 13, 2025 at 11:04 PM PST.</sub>

**Comment by JessicaLucindaCheng** [comment]
### Issue Progress Update
- **Progress:** Started a first draft: https://github.com/hackforla/website/issues/6595#issuecomment-2047453668
- **Blockers:** None
- **Availability:** 6 hours
- **ETA:** Tuesday, January 21, 2025

### Notes
- Work will continue in this issue: https://github.com/hackforla/knowledgebase-content/issues/130

### Tasks
- [x] Create an issue here to make a new guide https://github.com/hackforla/knowledgebase-content/issues/new/choose
- [x] Add info about commits and link to https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/about-commits
- Note: cherry-pick only moves the specific commit and not the whole history
- [ ] Will cloning both repos at beginning, remove need to git fetch new repo later?
- [ ] Way to directly cherry-pick items into a specific folder? Or need to work on moving files on the branch after pushing commits to remote? Or separate issue?

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, January 27, 2025 at 11:04 PM PST.</sub>

**Comment by JessicaLucindaCheng** [comment]
- Work will continue in this issue: https://github.com/hackforla/knowledgebase-content/issues/130

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, February 10, 2025 at 11:04 PM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, February 17, 2025 at 11:04 PM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, February 24, 2025 at 11:05 PM PST.</sub>

**Comment by HackforLABot** [comment]
@JessicaLucindaCheng

Please add update using the below template (even if you have a pull request). Afterwards, remove the '2 weeks inactive' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Monday, March 3, 2025 at 11:04 PM PST.</sub>
