### ISSUE TITLE
EPIC: Create Issues to add new variable github-handle for members in civic-tech-structure.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6695]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in civic-tech-index.md with a the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [x] For each team member listed in `_projects/civic-tech-structure.md` that does not have a variable `github-handle`, create an issue using the [template](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D)
- [x] For each issue:
   - [ ] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [ ] In the title, replace [INSERT PROJECT FILE] with **civic-tech-structure.md**
   - [ ] Under Action Items, replace [INSERT MEMBER NAME] with the member's name (in 2 places)
   - [ ] Under Action Items, replace [INSERT PROJECT FILE] with **civic-tech-structure.md**
   - [ ] Under Resources, replace [INSERT-PROJECT-FILE] with **civic-tech-structure.md**
   - [ ] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with **civic-tech-structure**
   - [ ] Apply the following labels: "ready for dev lead", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [ ] List the issue number in #5441 under Good First Issues
- [x] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for dev lead"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/civic-tech-structure
- This issue is part of #5441

**Comment by tony1ee** [comment]
**Availability:** 2-6 PM 04/25/2024, 4-8 PM 04/26/2024
**ETA:**  EOD 04/25/2024

**Comment by tony1ee** [comment]
An observation while working on this:
> \- [ ] Under Resources, replace [INSERT-PROJECT-FILE] with **civic-tech-structure.md**

might be inaccurate. Looks like it's referring to making changes to the line 
> For QA to validate change: https\://github.com/hackforla/website/blob/gh-pages/[INSERT-PATH-TO-PROJECT-FILE]  

and the proper action should be 
> \- [ ] Under Resources, replace [INSERT-PATH-TO-PROJECT-FILE] with **_projects/civic-tech-structure.md**

and I've created the following issues thusly:
- #6759 
- #6760
- #6761 
- #6762 
- #6763 

@roslynwythe Looks like this is the last **_Issue Making Level 1 Issue_** in the Epic #5441, so no immediate action is needed, but if future **_Issue Making Level 1 Issues_** will be created, we should probably make changes to either:
- the [add-github-handle issue template](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/add-github-handle.md), or
- action item description in future **_Issue Making Level 1 Issues_**

lf this warrants an ER I'd be happy to create one.

**Comment by roslynwythe** [comment]
@tony1ee You are absolutely correct; the Action Item

>
> > - [ ] Under Resources, replace [INSERT-PROJECT-FILE] with **civic-tech-structure.md**
> 
is incorrect.  In fact we decided to remove this line from the Resources section
> 
> > For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/[INSERT-PATH-TO-PROJECT-FILE]
> 
and so the Action Item quoted above, which relates to this line should be removed.  
>
> 
While checking the issues you created, I removed that line from the Resources section.  If you have time, yes I would appreciate it if you could write an ER documenting the need to remove that line from the issue template.

**Comment by roslynwythe** [comment]
@tony1ee I checked all of the issues you created and they were perfect, so closing this issue as completed.  Thanks very much for creating these issues!

**Comment by tony1ee** [comment]
> write an ER documenting the need to remove that line from the issue template.

ER created: #6771
