### ISSUE TITLE
Create Issues to add new variable github-handle for members in ems-triage-tracker.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6697]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in civic-tech-index.md with a the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [x] For each team member listed in `_projects/ems-triage-tracker.md` that does not have a variable `github-handle`, create an issue using the [template](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D)
- [x] For each issue:
   - [x] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [x] In the title, replace [INSERT PROJECT FILE] with **ems-triage-tracker.md**
   - [x] Under Action Items, replace [INSERT MEMBER NAME] with the member's name (in 2 places)
   - [x] Under Action Items, replace [INSERT PROJECT FILE] with **ems-triage-tracker.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILE] with **ems-triage-tracker.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with **ems-triage-tracker**
   - [x] Apply the following labels: "ready for dev lead", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [x] List the issue number in #5441 under Good First Issues
- [x] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for dev lead"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/ems-triage-tracker
- This issue is part of #5441

**Comment by JackCasica** [comment]
Availability: Today, EOD
ETA: Today, EOD

**Comment by roslynwythe** [comment]
Thank you @JackCasica for creating these good first issues.
