### ISSUE TITLE
Add github-handle for Nicole Doan in ems-triage-tracker.md

### ISSUE THREAD

**Issue by JackCasica** [hackforla/website#6721]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/ems-triage-tracker.md` in the IDE
- [x] Replace:
```
- name: Nicole Doan
```
with
```
- name: Nicole Doan
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/ems-triage-tracker

- This issue is part of #5441.

**Comment by blaycoder** [comment]
Availability: 18/05/2024
ETA:  19/05/2024

**Comment by t-will-gillis** [comment]
Hi @blaycoder Please remember to work on only one issue at a time, and to work on issues of increasing complexity. It appears you have six issues open currently.

It appears that your previous issues were done several months ago. If you are planning to 'restart the ladder', that is continue with two `good first issues`, one `Complexity: Small`, etc. that is OK. (But one at a time)

**Comment by blaycoder** [comment]
Alright
