### ISSUE TITLE
ER: Changes Needed for add-github-handle issue template and Epic instruction comments

### ISSUE THREAD

**Issue by tony1ee** [hackforla/website#6771]
### Emergent Requirement - Problem
we have [decided](https://github.com/hackforla/website/issues/6771#issuecomment-2084205536) to change the QA validation link in the add-github-handle issue template so it defaults to `code` instead of `preview`.

#### Line planned to update in issue template
https://github.com/hackforla/website/blob/caa4f1bc759cfbad28eab8f47dc2ffd0badf17c0/.github/ISSUE_TEMPLATE/add-github-handle.md?plain=1#L38

we want to change it to 
> For QA to validate change: https:\//github.com/hackforla/website/blob/gh-pages/_projects/[INSERT_PROJECT_FILE]?plain=1

### Issue you discovered this emergent requirement in
- #6695 

### Date discovered 
04/25/2024

### Did you have to do something temporarily
- [x] YES
- [ ] NO

### Who was involved
@tony1ee 
@roslynwythe 

### What happens if this is not addressed
If we don't make these changes, future issue makers for `add-github-handle` issues would create new issues that have irrelevant resource link and receive inaccurate instruction on how to populate placeholder in that link.

### Resources
- Epic for creating issues #5441
- add-github-handle issue template [.github/ISSUE_TEMPLATE/add-github-handle.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/add-github-handle.md)
- [testing instructions for issue templates](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024)

### Recommended Action Items 
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Creat an issue to change `add-github-handle` issue template [.github/ISSUE_TEMPLATE/add-github-handle.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/add-github-handle.md). 
Replace:
```
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/[INSERT-PATH-TO-PROJECT-FILE]
```
with:
```
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/[INSERT_PROJECT_FILE]?plain=1
```

**Comment by roslynwythe** [comment]
Thank you @tony1ee for picking up on this problem and creating this detailed ER.  Under "Proposed Solutions", I agree with items 2 - 4  and I completed those changes, so you can remove those items from the Proposed Solutions.  

Regarding the issue I just wanted to suggest that the issue include these [testing instructions for issue templates](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024)

**Comment by tony1ee** [comment]
@roslynwythe the idea of item 4 is to place a link in the main comment of #5441 pointing to the template modified in item 3. 

I suggested this because the _**[item-3 comment](https://github.com/hackforla/website/issues/5441#issuecomment-1736824314)**_ was a bit hard to find in the #5441 thread, and by linking to it therefore making it easier to find, we can reduce the chance of copying from previous Issue Making Issues (which could include inaccurate descriptions).

**Comment by roslynwythe** [comment]
@tony1ee That makes sense.  I've made those changes.

**Comment by tony1ee** [comment]
@roslynwythe 

I changed the main comment to hide the proposal 2-4. 

I also added instructions to include [testing instructions for issue templates](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) when creating issue for proposal 1. 

Please check if this ER is now ready to be moved forward.

**Comment by tony1ee** [comment]
Can I remain assigned as I am interested in writing this issue when it's approved to move forward?

**Comment by ExperimentsInHonesty** [comment]
example of code url https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md?plain=1

**Comment by tony1ee** [comment]
In dev lead meeting 04/29/2024 a decision has been made that we want to keep the QA link but change it slightly so it defaults to `code` instead of `preview`. 

With this new direction, this issue and proposed solution has been updated.

@roslynwythe

**Comment by roslynwythe** [comment]
@tony1ee this looks good.  I made the change you suggested to [this comment of #5441](https://github.com/hackforla/website/issues/5441#issuecomment-1736824314)

**Comment by ExperimentsInHonesty** [comment]
I have added this to the dev/pm agenda for a little cleanup before we prioritize

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe will help @tony1ee re write the proposed issue

**Comment by tony1ee** [comment]
@roslynwythe Please review the revised ER.

**Comment by tony1ee** [comment]
**i. Availability:** SAT 05/11/2024
**ii. ETA:** EOD 05/11/2024

**Comment by tony1ee** [comment]
Blockers: waiting for prioritization

**Comment by HackforLABot** [comment]
Hi @siyunfeng, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by ExperimentsInHonesty** [comment]
- See this issue for an example of the type of content needed in the body of the issue (i.e. steps) https://github.com/hackforla/website/issues/4477

**Comment by siyunfeng** [comment]
**Availability**: 6-10 PM Weekdays (EDT)
**ETA**: 11/11/2024 Monday

**Comment by siyunfeng** [comment]
- @ExperimentsInHonesty An issue for this ER has already been created (#6850) on May 11 2024 and a PR (#6999) was created and merged on June 14 2024. Do I still need to create a new issue or can this ER be closed?

**Comment by ExperimentsInHonesty** [comment]
@siyunfeng yes, it looks like they made the issue, but this ER never got closed.  I will close this now, please pick up another Issue making issue.
