### ISSUE TITLE
Epic: Change appropriate references to `ready for dev lead` label to `ready for merge team`

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6784]
### Dependency
- #6783

Rerun the following searches
- ["ready for dev lead" code only](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22ready+for+dev+lead%22&type=code)
- ["ready for dev lead" open issues](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22ready+for+dev+lead%22++&type=issues&state=open)

after the following issues are complete
- https://github.com/hackforla/website/issues/7600
- https://github.com/hackforla/website/issues/7601
- https://github.com/hackforla/website/issues/7603
- https://github.com/hackforla/website/issues/7604
- https://github.com/hackforla/website/issues/7605
- https://github.com/hackforla/website/issues/7606

### Overview
We need to have two ready for labels.  One for the merge team and one for dev leads so that merge team can take on more work, and the lead only gets the issues they absolutely need to see.

### Action Items
- [x] Create a `ready for merge team` label
- [ ] Evaluate each item could be handled by the merge team (it's procedural, not unique, e.g., issues that have been created from a template and need to have the ready for prioritization label added, etc..  If you don't know, use the discuss value)  (TRUE / FALSE, discuss)
- [ ] Create a roll-out plan to determine in what order items need to change

### Resources/Instructions
- 1.01 Spreadsheet: [Ready for merge team and dev lead rationalization](https://docs.google.com/spreadsheets/d/1aLfyfhjzOvGoxEKB-Bn7bvOCQZuG0W6xdgKE0mY69Q8/edit#gid=0)
