### ISSUE TITLE
ER: Update Project Profile: Expunge Assist

### ISSUE THREAD

**Issue by mariaweissman** [hackforla/website#6834]
### Dependency
- [x] #6866
- [x] #6986 

### Project Name

Expunge Assist

### Project Card URL

expunge-assist.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Curtis Barber

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Emma Thrash
GitHub Handle: emmathrash
Role: UX Content, Team Co-lead
Slack Member ID: U05JUM3881J

- [x] Name: Maria Weissman
GitHub Handle: mariaweissman
Role: Product Manager, Project Manager
Slack Member ID: U06REA9H3FF

- [x] Update Samantha Hyler's role to UX Content, Team Co-lead

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
- **Availability:** 1.5 hours
- **ETA:** Monday, May 20, 2024

**Comment by JessicaLucindaCheng** [comment]
## Issue Writing

### Update
- **Progress:** Wrote an issue (still need to proofread it though) and added it to the dependency section.
- **Blockers:** Need to ask the following:
  - Can Maria's role be `Product Manager, Project Manager` to match the other PMs on the team?
  - Can Emma's role be `UX Content, Team Co-lead` to match the format of other co-leads on the team?
  - Do you want to change Samantha's role from `UX Content, Team Lead` to `UX Content, Team Co-lead`?
- **Availability:** 6 hours
- **ETA:** Depends on when questions are answered.

### Tasks
- [x] Await response from Maria
- [x] Proofread #6866
- [x] Depending on answers, write another issue to finish other requested changes or add those changes to #6866

**Comment by JessicaLucindaCheng** [comment]
@mariaweissman 
I have some questions about the requested changes to the [Expunge Assist page](https://www.hackforla.org/projects/expunge-assist)'s Current Project Team section:
1. Instead of `Project Manager, Product Manager`, can Maria's role be `Product Manager, Project Manager` to match the formatting of other PMs' roles on the team?
2. Can Emma's role be `UX Content, Team Co-lead` to match the format of other co-leads on the team?
3. Do you want to change Samantha's role from `UX Content, Team Lead` to `UX Content, Team Co-lead`?

Thanks.

**Comment by mariaweissman** [comment]
@JessicaLucindaCheng thank you! I spoke with our team and we're unsure of why all of the Product Managers have "Product Manager, Team" and then everyone else has "Team, Role." We're happy to change everyone to whatever creates the most consistency.

1. Can Maria's role be Product Manager, Project Manager to match the other PMs on the team? **Yes**
2. Can Emma's role be UX Content, Team Co-lead to match the format of other co-leads on the team? **Yes**
3. Do you want to change Samantha's role from UX Content, Team Lead to UX Content, Team Co-lead? **Yes**

**Comment by JessicaLucindaCheng** [comment]
Issue Writing Progress
- **Progress:** I wrote two issues to address the request and added them to the Dependency section of the ER.
- **Blockers:** None
- **Availability:** N/A
- **ETA:** N/A

**Comment by JessicaLucindaCheng** [comment]
@ Merge Team
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Add a `ready for stakeholder` label and contact the author of this ER to approve the changes on the [Expunge Assist](https://www.hackforla.org/projects/expunge-assist) page. You can use this message when contacting the author if you want to:
```
Please let us know if the changes made to the [Expunge Assist](https://www.hackforla.org/projects/expunge-assist) page match what you requested by adding a comment to this issue. Then, remove the `ready for stakeholder` label and add the `ready for product` label. Thank you.
```

**Comment by t-will-gillis** [comment]
@mariaweissman Please let us know if the changes made to the [Expunge Assist](https://www.hackforla.org/projects/expunge-assist) page match what you requested by adding a comment to this issue. Then, remove the `ready for stakeholder` label and add the `ready for product` label. Thank you.

**Comment by JessicaLucindaCheng** [comment]
This issue has been in UAT for a long time, and we got no response from the author, so I am moving this to QA.
