### ISSUE TITLE
EPIC: Create Issues to Correctly Capitalize "Slack" in Issue Templates

### ISSUE THREAD

**Issue by tony1ee** [hackforla/website#6842]
### Overview
We need to create issues to correctly capitalize "Slack" in our issue templates when it means when it's used to refer to the app or the company.

### Details
We need to fix the following instances:

- https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/.github/ISSUE_TEMPLATE/pre-work-template---design.md?plain=1#L29
- https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/.github/ISSUE_TEMPLATE/pre-work-template---design.md?plain=1#L66
- https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/.github/ISSUE_TEMPLATE/pre-work-template--dev.md?plain=1#L37
- https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/.github/ISSUE_TEMPLATE/pre-work-template--dev.md?plain=1#L86

### Action Items
For each item in `Details` above, perform the following actions:

- [ ] Create an issue using `Blank Issue Template`, or by clicking [here](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Missing%2C+Feature+Missing%2C+role+missing%2C+size%3A+missing&projects=&template=blank-issue-template.md&title=)
- [ ] Change the Title to `Fix Capitalization of "Slack" in Issue Template [INSERT_FILE_NAME]`, replace `[INSERT_FILE_NAME]` with the file name
- [ ] Replace the description with the following:
````
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to fix the following line of code to correctly capitalize "Slack" when it's used to refer to the app or the company in our code and content.
[INSERT_LINE_PERMALINK]

### Action Items
- [ ] Open the file `[INSERT_PATH_TO_FILE]` in your code editor
- [ ] On Line [INSERT_LINE_NUMBER], replace every `slack` with `Slack` **when it's used to refer to the app and the company**, **do not make changes within URLs**.
- [ ] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin test-update-labels-1234`  
- [ ] The response from the push command will include the URL for creating a pull request. Copy/Paste the URL for creating the Pull Request for later.  
- [ ] Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/8ecf2e55-2187-4ab9-acf1-2fd7548291a1)

  </details> 
- [ ] Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details> 
- [ ] Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  ![image](https://github.com/hackforla/website/assets/16524851/563fc427-ba07-4e47-9440-2580bbfcad52)

  </details> 

- [ ] From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template. 
- [ ] Copy the URL of the issue creation page and save for later use.  
- [ ] Verify the appearance of the issue template.
- [ ] Complete the Pull Request process by visiting the URL saved from the push command.
- [ ] In the PR copy/paste this text immediately before the section "Screenshots of Proposed Changes Of The Website"
```
 ### For Reviewers
- Use this URL to check the updated issue template: [URL OF ISSUE TEMPLATE]
```
- [ ] Replace the text in the square brackets (as well as the square brackets) with the URL of the updated issue template
- [ ] Submit your pull request with your changes for review
- [ ] After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable Issues feature

### For Merge Team
- [ ] Release the dependency for this issue in #6842. If all the dependencies have been completed, close that issue.

### Resources/Instructions
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/[INSERT_PATH_TO_FILE]?plain=1

- This issue is part of Issue Making Issue #6842 and ER #6163.
````

- [ ] in `Overview`, replace `[INSERT_LINE_PERMALINK]` with permalink of line of code
- [ ] in `Action Items`, replace `[INSERT_PATH_TO_FILE]` with actual path to file
- [ ] in `Action Items`, replace `[INSERT_LINE_NUMBER]` with actual line number
- [ ] in `Resources/Instructions`, replace `[INSERT_PATH_TO_FILE]` with actual path to file
- [ ] Remove all existing labels, and apply the following labels: `Complexity: Medium`, `Feature: Onboarding/Contributing.md`, `role: back end/devOps`, `size: 1pt`, `ready for merge team`
- [ ] submit new issue
- [ ] add the newly created issue to `Issues Created` list in issue [#6842](https://github.com/hackforla/website/issues/6842)

### Issues Created 
- 

### Resources/Instructions
- This Issue Making Issue is part of ER #6163

**Comment by roslynwythe** [comment]
Hi @tony1ee I suggest changing 
```
- [ ] Remove all existing labels, and apply the following labels: `Complexity: Medium`, `Feature: Board/Github Maintenance`, `role: front end`, `size: 0.5pt` 
```
to
```
- [ ] Remove all existing labels, and apply the following labels: `Complexity: Medium`, `Feature: Onboarding/Contributing.md`, `role: back end/devOps`, `size: 1pt`, `ready for merge team`
```

**Comment by tony1ee** [comment]
@roslynwythe action item changed as suggested, labels for this epic is also changed accordingly.

**Comment by roslynwythe** [comment]
@tony1ee this looks good to me. Thank you!

**Comment by HackforLABot** [comment]
Hi @roslynwythe, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by roslynwythe** [comment]
Created issues:
- #7192 
- #7193 
- #7194 
- #7195

**Comment by roslynwythe** [comment]
Created issues:
- #7192 
- #7193 
- #7194 
- #7195

**Comment by ExperimentsInHonesty** [comment]
This epic is complete, I have checked each file that was supposed to be fixed and checked all the templates (7) and they all use Slack correctly.
