### ISSUE TITLE
Epic: Create Issues to Correctly Capitalize "Slack" in CONTRIBUTING.MD

### ISSUE THREAD

**Issue by tony1ee** [hackforla/website#6844]
### Dependency
- [x] https://github.com/hackforla/website/issues/6918
- [x] https://github.com/hackforla/website/issues/6931
- [x] https://github.com/hackforla/website/issues/6932

### Overview
We need to create issues to correctly capitalize "Slack" in `CONTRIBUTING.MD` when it means when it's used to refer to the app or the company.

### Details
We need to fix the following instances:
- https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/CONTRIBUTING.md?plain=1#L11
- https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/CONTRIBUTING.md?plain=1#L347
- https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/CONTRIBUTING.md?plain=1#L582

### Action Items
For each item in `Details` above, perform the following actions:

- [x] Create an issue using `Blank Issue Template`, or by clicking [here](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Missing%2C+Feature+Missing%2C+role+missing%2C+size%3A+missing&projects=&template=blank-issue-template.md&title=)
- [x] Change the Title to `Fix Capitalization of "Slack" in CONTRIBUTING.MD`
- [x] Replace the description with the following:
````
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to fix the following line of code to correctly capitalize "Slack" when it's used to refer to the app or the company in our code and content.
[INSERT_LINE_PERMALINK]

### Action Items
- [ ] Open the file `CONTRIBUTING.MD` in your code editor
- [ ] On Line [INSERT_LINE_NUMBER], replace every `slack` with `Slack` **when it's used to refer to the app and the company**, **do not make changes within URLs**.
- [ ] Changes to CONTRIBUTING.md should not be tested locally, rather they need to be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https\://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### For Merge Team
- [ ] Release the dependency for this issue in #6844. If all the dependencies have been completed, close that issue.

### Resources/Instructions
- [Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.MD?plain=1

This issue is part of Issue Making Issue #6844 and ER #6163.
````

- [x] in `Overview`, replace `[INSERT_LINE_PERMALINK]` with permalink of line of code
- [x] in `Action Items`, replace `[INSERT_LINE_NUMBER]` with actual line number
- [x] Remove all existing labels, and apply the following labels: `Complexity: Small`, `Feature: Onboarding/Contributing.md`, `role: front end`, `size: 0.5pt`, `ready for merge team`
- [x] submit new issue
- [x] add the newly created issue to `Issues Created` list in issue #6844

### Issues Created 
- https://github.com/hackforla/website/issues/6918
- https://github.com/hackforla/website/issues/6931
- https://github.com/hackforla/website/issues/6932

### Resources/Instructions
This Issue Making Issue is part of ER #6163

**Comment by roslynwythe** [comment]
@tony1ee great job writing this epic!

**Comment by del9ra** [comment]
ETA: 10 PM 06/02/2024
Availability: 1-3 06/03/2024

**Comment by LRenDO** [comment]
Hi @del9ra! 

Nice work! The new issues look great. You appropriately added the correct line numbers for all three issues to be created. You also listed them on this issue in the appropriate section.

I have a couple requests that weren't explicitly in the instructions and are not required, but would be helpful. Since we say "Release the dependency for this issue in #6844. If all the dependencies have been completed, close that issue." It would be helpful to have a `Dependency` section at the top with a checklist that includes the three issues you listed in the `Issues Created` section. #5248 has an example of a dependency section. It would also be helpful if we begin the title with `Epic:` similar to #5248 as it makes it quicker to recognize it's not a single issue. 

Feel free to ping me here if you have questions or need clarification.

**Comment by del9ra** [comment]
> Hi @del9ra!
> 
> Nice work! The new issues look great. You appropriately added the correct line numbers for all three issues to be created. You also listed them on this issue in the appropriate section.
> 
> I have a couple requests that weren't explicitly in the instructions and are not required, but would be helpful. Since we say "Release the dependency for this issue in #6844. If all the dependencies have been completed, close that issue." It would be helpful to have a `Dependency` section at the top with a checklist that includes the three issues you listed in the `Issues Created` section. #5248 has an example of a dependency section. It would also be helpful if we begin the title with `Epic:` similar to #5248 as it makes it quicker to recognize it's not a single issue.
> 
> Feel free to ping me here if you have questions or need clarification.

Hello @LRenDO,
I've updated the issue. Could you please take a look?
Thank you!

**Comment by LRenDO** [comment]
Hi @del9ra! Looks great. Thanks for the updates. When I included the example it had some completed dependencies and I didn't mention that the dependencies should be unchecked until they are completed. I went ahead and unchecked them since my example wasn't clear. Everything else looks great! Approving your work by removing you as assignee, but leaving the issue open since it is an epic with dependencies. Thanks for creating these issues!
