### ISSUE TITLE
Create spellcheck audit issues from line 110-117 of spreadsheet

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6871]
### Overview
We need to create issues for the spellcheck audit.  The filepaths for the required issues are found in lines 110-117 of the HfLA spelling audit spreadsheet[^1]

### Action Items
- [x] For each line 110-117 in the HfLA spelling audit spreadsheet[^1]
   - [x] Copy the filepath (for example `pages/toolkit.html`) from column A then create a new issue using the "Spell check audit web page template"[^2]
   - [x] Replace the text `[INSERT FILE HERE]` with the filename (for example `toolkit.html`)
   - [x] Replace the text `[INSERT FILE PATH]` with the full file path (for example `pages/toolkit.html`)
   - [x] Click "Submit New Issue"
   - [x] Copy the issue number and use it to create a link below under "Child Issues that this issue creates" (for example if you enter `- [ ] #6497`, GitHub will expand that into an issue link
   - [x] Copy the issue number and paste it into the "Link to Audit Issue" column in the spreadsheet in the row that corresponds to the filepath
- [x] When all issues have been created, move this issue into the "Questions/In Review" column and add the label "ready for dev lead"

#### Note for Dev Leads after issue signoff
- [x] Add all the issues created by this issue to the Epic #5248

### Resources/Instructions
- This issue is part of #5248
[^1]:[HfLA spelling audit spreadsheet](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1277680545)
[^2]:[Spell check audit web page issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Small%2C+Feature%3A+Administrative%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&projects=&template=spell-check-audit.md&title=Run+VS+Code+Spell+Checker+on+%5BINSERT+FILE+HERE%5D)

#### Child Issues that this issue creates
- [x] #7142
- [x] #7143 
- [x] #7144 
- [x] #7145 
- [x] #7146 
- [x] #7147 
- [x] #7148 
- [x] #7149

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I am not sure what I am supposed to do with this issue.  
It seems like all the checkboxes have been checked, which I would assume that means the issues are created.  But I don't know if the issues have actually been created, since there is no reference to them here.
 - [ ] If the issues have been made, just indicate that in a comment with the issues numbers
 - [x] If the issues have not been made, please check this box and do the following
    - [x] uncheck the boxes
    - [x] hide this comment the comment above.

**Comment by HackforLABot** [comment]
Hi @ramitaarora, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by ramitaarora** [comment]
Availability: Weekday mornings
ETA: July 26 EoD

**Comment by roslynwythe** [comment]
Great job @ramitaarora creating the issues, and recording the links in the spreadsheet and the epic.  Thank you for this valuable contribution!
