### ISSUE TITLE
Create spellcheck audit issues from line 119-125 of spreadsheet

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6872]
### Overview
We need to create issues for the spellcheck audit.  The filepaths for the required issues are found in lines 119-125 of the HfLA spelling audit spreadsheet[^1]

### Action Items
- [x] For each line 119-125 in the HfLA spelling audit spreadsheet[^1]
   - [x] Copy the filepath (for example `pages/toolkit.html`) from column A then create a new issue using the "Spell check audit web page template"[^2]
   - [x] Replace the text `[INSERT FILE HERE]` with the filename (for example `toolkit.html`)
   - [x] Replace the text `[INSERT FILE PATH]` with the full file path (for example `pages/toolkit.html`)
   - [x] Click "Submit New Issue"
   - [x] Copy the issue number and use it to create a link below under "Child Issues that this issue creates" (for example if you enter `- [ ] #6497`, GitHub will expand that into an issue link
   - [x] Copy the issue number and paste it into the "Link to Audit Issue" column in the spreadsheet in the row that corresponds to the filepath
- [x] When all issues have been created, move this issue into the "Questions/In Review" column and add the label "ready for merge team"

#### Note for Dev Leads after issue sign-off
- [x] Add all the issues created by this issue to the Epic #5248

### Resources/Instructions
- This issue is part of #5248
[^1]:[HfLA spelling audit spreadsheet](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1277680545)
[^2]:[Spell check audit web page issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Small%2C+Feature%3A+Administrative%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&projects=&template=spell-check-audit.md&title=Run+VS+Code+Spell+Checker+on+%5BINSERT+FILE+HERE%5D)

#### Child Issues that this issue creates
- [x] #7609
- [x] #7610
- [x] #7611
- [x] #7612
- [x] #7613

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I am not sure what I am supposed to do with this issue.  
It seems like all the checkboxes have been checked, which I would assume that means the issues are created.  But I don't know if the issues have actually been created, since there is no reference to them here.
 - [ ] If the issues have been made, just indicate that in a comment with the issues numbers
 - [x] If the issues have not been made, please check this box and do the following
    - [x] uncheck the boxes
    - [x] hide this comment the comment above.
    - [x] remove the `ready for dev lead` label
    - [x] add the `ready for proritization` label

**Comment by HackforLABot** [comment]
Hello @daras-cu, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by HackforLABot** [comment]
Hi @terrencejihoonjung, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by terrencejihoonjung** [comment]
Availability: Mon - Fri, 5pm - 9pm PST
ETA: October 13th, 2024, 11:59pm PST

**Comment by HackforLABot** [comment]
@terrencejihoonjung

Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (optional): "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.

<sub>You are receiving this comment because your last comment was before Tuesday, October 15, 2024 at 12:04 AM PST.</sub>

**Comment by terrencejihoonjung** [comment]
Progress: Haven't started due to unexpected responsibilities this week but will finish this weekend!
Blockers: N/A
Availability: Fri-Sun 5pm - 10pm PST
ETA: 10/19/24, 11:59pm PST

**Comment by terrencejihoonjung** [comment]
Progress: Haven't started due to unexpected responsibilities this week but will finish this weekend!
Blockers: N/A
Availability: Fri-Sun 5pm - 10pm PST
ETA: 10/20/24, 11:59pm PST

**Comment by terrencejihoonjung** [comment]
Hi @roslynwythe 

I noticed that issues were already created for filepaths on lines 119 and 120 in the spreadsheet. I created an issue for line 119 before realizing this and did not create one for line 120. Should I ignore lines 119 and 120? 

For your reference, here is the (accidentally) created issue for line 119: #7608 

Thank you!

**Comment by daras-cu** [comment]
Hi @terrencejihoonjung, it looks like you're right about there already being issues for those lines in the spreadsheet. There must have been some overlap with a previous issue, thank you for catching that. You can close the issue you created for 119 and disregard 120, then this should be ready for approval.

**Comment by terrencejihoonjung** [comment]
Hi @daras-cu,

Thanks for the clarification! I went ahead and closed the issue.

**Comment by jphamtv** [comment]
Hi @terrencejihoonjung - Thanks for working on creating the issues and linking them on the spreadsheet. Everything looks good. I'm closing this issue as completed. Great job!
