### ISSUE TITLE
ER: need to manage spell check false positives in markdown files

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7004]
### Emergent Requirement - Problem
Some portions of markdown generates numerous false positives from the VS Code Spell Checker extension, and it is desirable to exclude those portions from spell checking.  This ER focuses on these instances:
- proper names 
- Lorem ipsum placeholder text

### Details
For HTML and JavaScript files, it is possible to exclude a portion of the text from spell checking, using specially formatted comments.  Examples of such comments can be found [here  in the cspell documentation](https://cspell.org/configuration/document-settings/#enable--disable-checking-sections-of-code).  However for markdown files the situation is different because: 
- since markdown does not support "comments", it is not clear which if any of those those methods can be used
- the formatting in markdown files lends itself it using exclude/include regex patterns in the cspell configuration;  for example we might use regex to exclude lines such as `  - name: Bonnie Wolfe`

### Issue you discovered this emergent requirement in
- #6753

### Date discovered 
6/14/2024

### Did you have to do something temporarily
- [ ] YES
- [ ] NO

### Who was involved
@roslynwythe 

### What happens if this is not addressed
We will have large numbers of false positives, which may pose a bigger problem when we implement spell checking in Pull Requests.   False positives can be managed individually in the cspell configuration file.  Alternatively we could exclude entire files from spell checking.  

### Resources
https://cspell.org/configuration/patterns/
https://cspell.org/configuration/document-settings/#enable--disable-checking-sections-of-code

### Recommended Action Items
- [ ] Make a new issue 1 - #7010
- [ ] Make new issue 2 - #7011
- [ ] Added new issue 3 - #7099

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe Please update the title

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I created issue 1 - #7010 however I'm not sure about the need for issue 2.  So far the only instance of this problem is the `Lorem ipsum` placeholder text, and we wouldn't normally publishing pages with placeholder text anyway.  Please advise.

**Comment by roslynwythe** [comment]
- Created #7010 and #7011

**Comment by roslynwythe** [comment]
- Created #7010 and #7011

**Comment by t-will-gillis** [comment]
Created issue #7099 and added it to the list above since it is part of the same set of issues
