### ISSUE TITLE
Recruit volunteers for team open roles

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#7005]
### Dependency
- [x] need to recruit new team members to website team

### Overview
We need volunteer(s) to work on the open issues we have so that we can move the project forward.

#### Creating a new role post
- [x] Copy the template post from the Community of Practice WIKI, Open Roles Templates (Resource 1.01)
- [x] Paste the template in a comment below
- [x] Customize the comment to reflect your open role
- [x] Open a new issue by using the Open Role template (Resource 1.02)
- [x] Copy and Paste your customized comment to the new issue
- [x] Add the label for the role that you are recruiting for
- [x] Submit the new issue
- [x] Assign yourself to the new issue
- [x] Add the issue to the HfLA: Open Roles project board (Resource 1.03)
- [x] add the link of the new issue to the related comment on this issue 
- [x] keep yourself assigned to this issue until the role is filled

#### Marketing the new role post
-  Post a link to the new issue in the Slack channel for the related Practice Area
   - [ ] Copy the Slack message  (Resource 1.04)
   - [ ] Copy the message into the Slack Channel for the relevant Community of Practice (The Slack channels can be found on Resource 1.01)
     - [ ] Replace the text `[Replace with LINK TO NEW ISSUE]` with link to the issue
   - [ ] check your team Slack channel for people reaching out after every onboarding and at least every other day

#### Once Filled
- [ ] Hide the comment on this issue for the role you just filled
- [ ] Add the following comment to the role posting issue 
  ```
  This role has been filled by @[Replace with GITHUB HANDLE OF PERSON WHO IS TAKING ROLE]
  ```
- [ ] Close the role posting issue
- [ ] Unassign yourself from this issue
- If there are no open roles on this issue (i.e., if there are open roles, there will be unclosed comments)
   - [ ] Add the label: Dependency and uncheck the dependency on top of this issue
   - [ ] Move this issue to the icebox, on the project board

### Resources/Instructions
- 1.01 WIKI: https://github.com/hackforla/communities-of-practice/wiki/Open-Roles-Templates
- 1.02 [Open new Post open role issue](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Small%2C+feature%3A+recruiting%2C+role+missing&projects=&template=post-an-open-role.md&title=HfLA+Website%3A+Open+Role+for%3A+%5BReplace+with+NAME+OF+ROLE%5D)
- 1.03 [HfLA: Open Roles board](https://github.com/orgs/hackforla/projects/67)
- 1.04 Copy to post in CoP Slack Channels when there is an open role
   ```
   Hi, the Website has a volunteer posting, which includes details of how to get in touch with us if you are interested. [Replace with LINK TO NEW ISSUE]
   ```

**Comment by ExperimentsInHonesty** [comment]
### Title
HfLA website: Open Role for: Back End Developer

### Issue
- https://github.com/hackforla/website/issues/6987

### Body
**Project Name**: Hackforla.org Website

**Name of Role**: Back End Developer

**Volunteer Opportunity**: Need someone with experience with GitHub actions automation, Google AppsScript, and working with REST and GraphQL calls. The developer will work very closely with the VRMS and CivicTechJobs teams, who manages the data we receive. **Note:** The Website project is unique in that it is hosted on GitHub Pages. This means we do not have an official backend.

**Duration**: Open-ended

**Meeting times**:  See project page below

**Who to communicate your interest to**
- Slack channel link: #hfla-site
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/website)

**Resources:**
- [Welcome to the HackforLA.org (HfLA) Website Wiki!](https://github.com/hackforla/website/wiki)
- [VRMS](https://www.hackforla.org/projects/vrms)

**Comment by ExperimentsInHonesty** [comment]
#### Title
HfLA Website: Open Role for: Product Manager


### Issue
- https://github.com/hackforla/website/issues/7007

#### Body

**Project Name**: Website

**Name of Role**: Product Manager

**Volunteer Opportunity**: [Replace with CUSTOM RECRUITMENT MESSAGE]

**Duration**: 2-3 months

**Meeting Times**: Flexible

**Who to communicate your interest to**
- Slack channel link: [#hfla-site](https://hackforla.slack.com/archives/C4UM52W93)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/website)

**Comment by ExperimentsInHonesty** [comment]
# Role posts from the Previous Product Management Open Roles board, Filled column

## Post 1
<details><summary>copy code</summary>

```
![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: Hack for LA website

**Volunteer Opportunity**: You will learn to manage the Kanban board and run interdisciplinary team meetings.  You will move the product forward by working on one of the [open product management issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+product+management%22#card-55870123) on a weekly basis  work with Design Lead and help build out the product roadmap

**Duration**: On-going

**Meeting Times**: Sun 10 am to 12 pm

**Who to communicate your interest to**
- Slack channel link: [#product-management](https://hackforla.slack.com/archives/CJY4R382X)
- Slack name of person to contact in the channel: Bonnie Wolfe

[Read more about the project](https://www.hackforla.org/projects/website)
```
</details> 

<details><summary>viewable code</summary>

![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: Hack for LA website

**Volunteer Opportunity**: You will learn to manage the Kanban board and run interdisciplinary team meetings.  You will move the product forward by working on one of the [open product management issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+product+management%22#card-55870123) on a weekly basis  work with Design Lead and help build out the product roadmap

**Duration**: On-going

**Meeting Times**: Sun 10 am to 12 pm

**Who to communicate your interest to**
- Slack channel link: [#product-management](https://hackforla.slack.com/archives/CJY4R382X)
- Slack name of person to contact in the channel: Bonnie Wolfe

[Read more about the project](https://www.hackforla.org/projects/website)
</details>

**Comment by ExperimentsInHonesty** [comment]
# Post from previous UI/UX Design open roles board, Filled column

## Post 1
<details><summary>copy code</summary>

```
![""](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: Hack for LA Website

**Volunteer Opportunity**: 
We are looking for a Design Lead to help lead the Hack for LA website design team. Here you'll have the opportunity to work closely with design, research, stakeholders, product management, & engineering teams to plan the design teams actions and support designers.

We're looking for someone who wants to: 
- Improve their leadership and public speaking skills 
- Be the bridge between design and other multifunctional teams.
- Collaborate with others 
- Work on solutions that not only benefit the users but also the business needs and goals.

**Duration:** 
Ongoing, 6-8 hours per week

**Meetings:**
UX team meetings: Thursday 5-6pm PST
All team meeting (design, dev, PM): Sunday 10-11am PST

**Who to communicate your interest to**
Slack channel link: #hfla-site-ux
Slack name of person to contact in the channel: Phu
```
</details> 

<details><summary>viewable code</summary>

![""](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: Hack for LA Website

**Volunteer Opportunity**: 
We are looking for a Design Lead to help lead the Hack for LA website design team. Here you'll have the opportunity to work closely with design, research, stakeholders, product management, & engineering teams to plan the design teams actions and support designers.

We're looking for someone who wants to: 
- Improve their leadership and public speaking skills 
- Be the bridge between design and other multifunctional teams.
- Collaborate with others 
- Work on solutions that not only benefit the users but also the business needs and goals.

**Duration:** 
Ongoing, 6-8 hours per week

**Meetings:**
UX team meetings: Thursday 5-6pm PST
All team meeting (design, dev, PM): Sunday 10-11am PST

**Who to communicate your interest to**
Slack channel link: #hfla-site-ux
Slack name of person to contact in the channel: Phu
</details>

## Post 2

<details><summary>copy code</summary>

```
[image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

~~**Project Name**: Hack for LA Website

**Volunteer Opportunity**: 
We are looking for designers to join our current team. Here you'll have the opportunity to work on the [hackforla.org](https://www.hackforla.org/) site, designing solutions that support both the needs of our users and the goals of the Hack for LA organization as a whole. 

We're currently working on a big redesign of the site and are looking for people with familiarity and interest in both visual design as well as larger UX/product design methods: 

**Duration:** 
Ongoing, 4-6 hours per week

**Meetings:**
Design team meetings: Wednesday 2:30 PM-3:30 PM PST
All team meeting (design, dev, PM): Sunday 10-11am PST

**Who to communicate your interest to**
Slack channel link: [hfla-site-ux](https://hackforla.slack.com/archives/C018FMQTWMT) 
```@Phuong Van```
```
</details> 

<details><summary>viewable code</summary>

[image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

~~**Project Name**: Hack for LA Website

**Volunteer Opportunity**: 
We are looking for designers to join our current team. Here you'll have the opportunity to work on the [hackforla.org](https://www.hackforla.org/) site, designing solutions that support both the needs of our users and the goals of the Hack for LA organization as a whole. 

We're currently working on a big redesign of the site and are looking for people with familiarity and interest in both visual design as well as larger UX/product design methods: 

**Duration:** 
Ongoing, 4-6 hours per week

**Meetings:**
Design team meetings: Wednesday 2:30 PM-3:30 PM PST
All team meeting (design, dev, PM): Sunday 10-11am PST

**Who to communicate your interest to**
Slack channel link: [hfla-site-ux](https://hackforla.slack.com/archives/C018FMQTWMT) 
```@Phuong Van```
</details>

**Comment by ExperimentsInHonesty** [comment]
# Post from previous UI/UX Research open roles board, Filled column

## Post 1
<details><summary>copy code</summary>

```
![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: HfLA website

**Volunteer Opportunity**: 
We are conducting qualitative and quantitative research that will play a critical role in the website design process. In this process, UX researchers would conduct research, collaborate with cross-functional teams, and assist the entire user experience team.

**Duration**: Open-ended
**Meeting times**: Wed 2PM PST, Sun 11AM PST

**Who to communicate your interest to**
- Slack channel link: [#hfla-site-ux](https://www.hackforla.org/projects/website)
- Slack name of person to contact in the channel: Vaisali

```
</details> 

<details><summary>viewable code</summary>

![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: HfLA website

**Volunteer Opportunity**: 
We are conducting qualitative and quantitative research that will play a critical role in the website design process. In this process, UX researchers would conduct research, collaborate with cross-functional teams, and assist the entire user experience team.

**Duration**: Open-ended
**Meeting times**: Wed 2PM PST, Sun 11AM PST

**Who to communicate your interest to**
- Slack channel link: [#hfla-site-ux](https://www.hackforla.org/projects/website)
- Slack name of person to contact in the channel: Vaisali

</details>

## Post 2

<details><summary>copy code</summary>

```
![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: Hack for LA website

**Volunteer Opportunity**:  (Need 1-2 UX Researchers) 
Help conduct user interviews, usability testing, A/B testing, and other research to help guide designs of new pages and improvements of existing pages. Incorporate Google Analytics findings. Also set research processes for the project.

**Duration**: Open-ended (6-10 hours/week)

**Who to communicate your interest to**
- Slack name of person to contact:  @ Danielle Nedivi

[Read more about the project](https://www.hackforla.org/projects/website)
```
</details> 

<details><summary>viewable code</summary>

![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: Hack for LA website

**Volunteer Opportunity**:  (Need 1-2 UX Researchers) 
Help conduct user interviews, usability testing, A/B testing, and other research to help guide designs of new pages and improvements of existing pages. Incorporate Google Analytics findings. Also set research processes for the project.

**Duration**: Open-ended (6-10 hours/week)

**Who to communicate your interest to**
- Slack name of person to contact:  @ Danielle Nedivi

[Read more about the project](https://www.hackforla.org/projects/website)
</details>

**Comment by roslynwythe** [comment]
- see #7066

**Comment by ExperimentsInHonesty** [comment]
# Post from previous Engineering open roles board, Back End column

<details><summary>copy code</summary>

```
![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: HackforLa.org website

**Volunteer Opportunity**: Javascript Developer, anyone wanting to learn how to do Git commits in a collaborative work environment 

**Duration**: Open Ended

**Who to communicate your interest to**
- Slack channel link: [#hfla-site](https://hackforla.slack.com/archives/C4UM52W93)
- Contacts: https://github.com/hackforla/website/wiki/Meet-the-Team

[Read more about the project](https://www.hackforla.org/projects/website)
```
</details> 

<details><summary>viewable code</summary>

![image](https://user-images.githubusercontent.com/37763229/162992303-b0fae60e-1886-45ce-93c1-d1a27a909327.png)

**Project Name**: HackforLa.org website

**Volunteer Opportunity**: Javascript Developer, anyone wanting to learn how to do Git commits in a collaborative work environment 

**Duration**: Open Ended

**Who to communicate your interest to**
- Slack channel link: [#hfla-site](https://hackforla.slack.com/archives/C4UM52W93)
- Contacts: https://github.com/hackforla/website/wiki/Meet-the-Team

[Read more about the project](https://www.hackforla.org/projects/website)
</details>

**Comment by ExperimentsInHonesty** [comment]
@sofiatajide Please create a new open role issue.  Here is an example issue you can see what the final version will look like https://github.com/civictechindex/BOP/issues/282.  When you are done creating it, please add it to this board https://github.com/orgs/hackforla/projects/67/views/6 (with a status of: Not Ready for Volunteers Yet).

**Comment by sofiatajide** [comment]
### Title
HfLA website: Open Role for: Data Scientist

### Issue
- https://github.com/hackforla/website/issues/7853

### Body
**Project Name**: Hackforla.org Website

**Name of Role**: Data Scientist

**Volunteer Opportunity**: We are looking for a Data Scientist with experience in Google AppsScript to analyze and automate time-tracking data for our internship program. This is an excellent portfolio item, as it will be used organization-wide by numerous volunteers reporting their hours. You will have direct access to stakeholders and significant input into how the data is displayed. 

**Duration**: Open-ended

**Meeting times**:  See project page below

**Who to communicate your interest to**
- Slack channel link: #hfla-site
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/website)

**Resources:**
- [Welcome to the HackforLA.org (HfLA) Website Wiki!](https://github.com/hackforla/website/wiki)

**Comment by Rabia2219** [comment]
#### Title
HfLA Website: Open Role for: Homepage Launch Product Manager


### Issue

- https://github.com/hackforla/website/issues/7952

#### Body
**Project Name**: Hackforla.org Website

**Volunteer Opportunity**: We are looking for 3 product managers to manage the relaunch of the website with new homepage and doubling the size of the website with supporting page.  We believe we are 80% done with the pre-launch items.  We are working to build tracking for the remaining items, identify gaps, find bugs, and create a more accurate timeline.  See https://github.com/hackforla/website/issues/2481 to read more about the current work

**Duration**: On-going

**Meeting Times**: Tuesdays 1pm PST

**Who to communicate your interest to**
- Slack channel link: [#hfla-site](https://hackforla.slack.com/archives/C4UM52W93)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/website)

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
Ready for review (new Open Role post for Homepage Launch PM)

**Comment by rcpeng34** [comment]
#### Title
EA: Open Role for: frontend dev

### Issue
https://github.com/hackforla/expunge-assist/issues/1761

#### Body
![image](https://user-images.githubusercontent.com/78319934/129253133-b41b4aa6-accc-4521-b769-000c1e39a46b.png)

**Project Name**: 
Expunge Assist

**About**: 
Expunge Assist is a free step-by-step tool that helps people with past convictions in California write a declaration. It is one part of the expungement process.

**Volunteer Opportunity**: 
Expunge Assist is looking for frontend developers to help us wrap up the final tickets needed to reach our next milestone, a final review with Hack for LA. Once completed, we’ll begin collaborating with a community partner to adjust our site for their use case. This is a unique chance to contribute at the ground level of a meaningful project launch and help shape a new community partnership.

**Duration**: On-going

**Meeting Times**: 
Mondays evening 8pm pacific ~15 minutes standup meeting (flexible)
Thursday 6pm pacific all team meeting

**Who to communicate your interest to**
- Slack channel link: [#expunge-assist-dev](https://hackforla.slack.com/archives/C04EG4A284F)
- Slack name of person to contact in the channel: [@rick p](https://hackforla.slack.com/team/U07QU3C45MY)

[Read more about the project](https://www.hackforla.org/projects/expunge-assist)
[Project site](https://expungeassist.org/about-us)
