### ISSUE TITLE
Create Issues to add new variable github-handle for members in tech-work-experience.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7160]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in new-schools-today.md with a the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [ ] For each team member listed in `_projects/ tech-work-experience.md` **that does not have a variable `github-handle`**, create an issue using the [template](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D)
- [ ] For each issue:
   - [ ] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [ ] In the title, replace [INSERT PROJECT FILE] with ** tech-work-experience.md**
   - [ ] Under Action Items, replace [INSERT MEMBER NAME] with the member's name (in 2 places)
   - [ ] Under Action Items, replace [INSERT PROJECT FILE] with ** tech-work-experience.md**
   - [ ] Under Resources, replace [INSERT-PROJECT-FILE] with ** tech-work-experience.md**
   - [ ] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with ** tech-work-experience**
   - [ ] Apply the following labels: "ready for dev lead", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [ ] List the issue number in #5441 under Good First Issues 
- [ ] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for dev lead"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/tech-work-experience
- This issue is part of #5441

**Comment by HackforLABot** [comment]
Hi @roslynwythe, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by roslynwythe** [comment]
- #7239
- #7240
- #7241
- #7242
- #7245 
- #7246 
- #7247 
- #7248 
- #7249 
- #7250 
- #7251 
- #7252 
- #7253
- #7254

**Comment by roslynwythe** [comment]
See list of child issues above.
