### ISSUE TITLE
Create Issues to add new variable github-handle for members in not-today.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7161]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in not-today.md with a the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [x] For each team member listed in `_projects/not-today.md` **that does not have a variable `github-handle`**, create an issue using the [template](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D)
- [x] For each issue:
   - [x] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [x] In the title, replace [INSERT PROJECT FILE] with **not-today.md**
   - [x] Under Action Items, replace [INSERT MEMBER NAME] with the member's name (in 2 places)
   - [x] Under Action Items, replace [INSERT PROJECT FILE] with **not-today.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILE] with **not-today.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with **not-today**
   - [x] Apply the following labels: "ready for merge team", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [x] List the issue number in #5441 under Good First Issues 
- [x] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for merge team"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/not-today
- This issue is part of #5441

**Comment by HackforLABot** [comment]
Hello @FamousHero, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by HackforLABot** [comment]
Hi @mchait18, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** M-Th 9:30-3:30 EST
ii. **ETA:** 12/2/2024 12 PM EST

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by mchait18** [comment]
The instruction says - Apply the following labels: "ready for merge team", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page".
I see that the issue automatically has the label "ready for dev lead". Should I remove this label when I apply "ready for merge team" or include both?

Thank you Roslyn for your answer - resolved

**Comment by siyunfeng** [comment]
@mchait18 Please provide the issue number you created based on this Epic in the comment so the merge team can review and process it. You will need to include this Epic in the issues you created if you haven't.

**Comment by mchait18** [comment]
Thanks @siyunfeng.
The issues I created based on this Epic are:
- #7781 and 
- #7782.

**Comment by t-will-gillis** [comment]
Hi @mchait18 - Everything looks great! As @siyunfeng mentioned, for each of the two issues, please add a bullet point at the end of the "Resources/ Instructions" saying something like:  
  ```  
  - This issue initiated by #7161
  ```  
  
Also- I made a small edit in your comment above by putting each issue on its own line with a bullet point. This lets the full issue name get displayed, for example:

Without the bullet point #7161
- With the bullet point #7161

When you are through, let me know and I will close this issue.

**Comment by mchait18** [comment]
Thank you, @t-will-gillis. I corrected what you suggested.

**Comment by t-will-gillis** [comment]
Thanks @mchait18! Closing this as successfully completed.
