### ISSUE TITLE
Create Issues to add new variable github-handle for members in open-community-survey.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7162]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in open-community-survey.md with a the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [x] For each team member listed in `_projects/open-community-survey.md` **that does not have a variable `github-handle`**, create an issue using the [template](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D)
- [x] For each issue:
   - [x] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [x] In the title, replace [INSERT PROJECT FILE] with **open-community-survey.md**
   - [x] Under Action Items, replace [INSERT MEMBER NAME] with the member's name (in 2 places)
   - [x] Under Action Items, replace [INSERT PROJECT FILE] with **open-community-survey.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILE] with **open-community-survey.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with **open-community-survey**
   - [x] Apply the following labels: "ready for dev lead", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [x] List the issue number in #5441 under Good First Issues 
- [x] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for dev lead"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/open-community-survey
- This issue is part of #5441

**Comment by HackforLABot** [comment]
Hi @FamousHero, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by HackforLABot** [comment]
Hi @FamousHero, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by FamousHero** [comment]
i. Availability: Mon(9/9)-Fri(9/13): 5pm-6pm
ii. ETA: Fri (9/13) @8pm

**Comment by LRenDO** [comment]
Hi @FamousHero! Great job with this issue! It looks like you added issues for each person on the leadership team correctly.  You also did a great job with moving the issue to the right column and adding the correct label. 

Going to go ahead and approve this. I do have a quick non-functional request. Please go ahead and check of the last empty check box since you did add the file name.

Thanks for contributing to this epic!

**Comment by FamousHero** [comment]
Thanks @LRenDO! Went ahead and fixed the non-requirement issue, I'll be more thorough next time!
