### ISSUE TITLE
Create Issues to add new variable github-handle for members in public-tree-map.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7163]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in public-tree-map.md with the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [x] For each team member listed in `_projects/public-tree-map.md` **that does not have a variable `github-handle`**, create an issue using the [template](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D)
- [x] For each issue:
   - [x] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [x] In the title, replace [INSERT PROJECT FILE] with **public-tree-map.md**
   - [x] Under Action Items, replace [INSERT MEMBER NAME] with the member's name (in 2 places)
   - [x] Under Action Items, replace [INSERT PROJECT FILE] with **public-tree-map.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILE] with **public-tree-map.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with **public-tree-map**
   - [x] Apply the following labels: "ready for merge team", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [x] List the issue number in #5441 under Good First Issues 
- [x] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for merge team"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/public-tree-map
- This issue is part of #5441

**Comment by HackforLABot** [comment]
Hi @mugdhchauhan, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by mugdhchauhan** [comment]
Availability this week: Daily @ 6 PM - 8 PM (GMT)
ETA: 17 Jan 2025

**Comment by mugdhchauhan** [comment]
The issue summary provided is very helpful. 

For the Action Items section of the issue summary, I have changed this:

```
Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with public-tree-map.md
```
to this (removed the `.md` extension):
```
Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with public-tree-map
```
I also changed the webpage link under Resources/Instructions of the issue summary from https://www.hackforla.org/projects/public-tree-map.md (which resulted in an error) to https://www.hackforla.org/projects/public-tree-map (which correctly opens the project page for Public Tree Map).

**Comment by mugdhchauhan** [comment]
### Progress Report

Provide Update

1. **Progress** 
- I have completed all of the action items in the issue summary. 
- The following issues have been created: 
	- #7792
	- #7794
	- #7795

2. **Blockers**
- No Blockers

3. **Availability**
- Daily @ 6PM - 8PM (GMT)

4. **ETA**
- 17 Jan 2025
- Next steps: Merge Team to approve and close this and move the created issues into the prioritized backlog.

**Comment by t-will-gillis** [comment]
Hey @mugdhchauhan Everything looks great! One at thing, for each of the three issues, please add a bullet as the last line under "Resources/Instructions" that tie those issues back to this one, for example:
  ```  
  - This issue initiated by #7163
  ```  
  
  Shoot me a message when you have done this and I will close this issue. Thanks for working on this!

**Comment by mugdhchauhan** [comment]
Hey @t-will-gillis, thank you for letting me know. I have tied those issues back to this one.

**Comment by t-will-gillis** [comment]
Thanks for adding the note, @mugdhchauhan - closing this issue as successfully completed
