### ISSUE TITLE
Updates to CONTRIBUTING.md to reflect changes in the Project Board and Skills Issue

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7236]
### Overview
We need to update CONTRIBUTING.md to reflect changes in the Project Board and Skills Issue

### Action Items
- [ ] Review CONTRIBUTING.md for sections that are either in conflict with or are redundant with instructions in the new Skills Issue.  
   - [ ] List proposed changes with a link to the specific section below under proposed changes, using this template
      ```
      #### Section [REPLACE WITH SECTION NAME] 
      - [REPLACE WITH DESCRIPTION OF CHANGE NEEDED]
         - [ ] approved?
         - Issue #: 
      ```
      - Consider using hyperlinks from CONTRIBUTING to Skills Issue or Skills Issue to CONTRIBUTING instead of repeating the information.  This will reduce redundancy and make it easier to keep them updated.
   - [ ] put this issue in "Questions/In Review" with "ready for dev lead" label.
- [ ]  For changes in CONTRIBUTING.md that have been approved by dev lead
   - [ ] Create an issue using the [Update CONTRIBUTING.md Issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Small%2C+Feature%3A+Wiki%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&projects=&template=update-CONTRIBUTING.md&title=Update+CONTRIBUTING.md+Section+%5BINSERT+SECTION+%23%5D) 
   - [ ] In the Resources/Instructions section of your new issue, add the following:
      ```
      This issue resulted from #7236
      ```
- [ ] Link the issue under the related proposed change below
- [ ] When all issues have been created, move this issue to `Questions/In Review` column and add the label `ready for merge team`

### Issues Created
- [ ] #7237

**Comment by HackforLABot** [comment]
Hi @roslynwythe, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I don't believe that CONTRIBUTING.md contains any more references to the old Project Board, so I could remove that part of the requirements.  But I thought perhaps we should have someone examine CONTRIBUTING for conflicts and duplication with the Skills issue.  How concerned should we be able duplicate instructions in CONTRIBUTING and in the Skills Issue?

**Comment by ExperimentsInHonesty** [comment]
This issue might be outdated, need to check it against the current issue template

**Comment by kdaca19xx** [comment]
It appears that this issue has been addressed already. Closing it as resolved.

**Comment by HackforLABot** [comment]
This issue was reopened because it did not have any of the following:
- A linked PR,
- An `Ignore` label
- A `non-PR contribution` label

**Comment by kdaca19xx** [comment]
It appears that this issue has been addressed already. Closing it as resolved after changing the status back to `New Issue Approval` and adding the `Ignore: No longer a problem` label.
