### ISSUE TITLE
Create issues to update Project Profile: Guides Team

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/website#7259]
### Overview
The project team from Guides needs its project leadership variable information updated, so that the current team members can be properly displayed on the Hack for LA website

### Action Items
- [ ] Review the Project Update Data below and then follow the instructions for either adding or deleting team members from the project's .md

<details><summary>Adding new volunteers to team page</summary>

- [ ] Create a new issue using the [add new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---add.md&title=Update+Project+Profile%3A+%5BProject+Name%5D+Add+%5BName+of+Volunteer%5D) template
- [ ]  Customize the title with name of project and person to add
- [ ]  Customize the body
   - [ ]   In the ER, go to the value under the line "Project Card URL"
      - [ ]  Copy the file name 
      - [ ] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md)
   - [ ] In the copy block below the line that starts, "Find the `leadership` variable and add the following profile."  add all the information from the ER for the person you are adding.
   - [ ] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [ ] to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [ ] click on its link
      - [ ] copy link
      - [ ] replace brackets on resource 2 with the URL
   - [ ] Add link to the ER on resource 3
- [ ] Choose `Update comment` button
- [ ] Add milestone `Onboarding flow`
- [ ] Review, and if ready, add label
```
Ready for Prioritization
```
- [ ] Add the URL to a comment on this ER
    - [ ] if this is the first add leader issue to be created, paste this into a comment and add the URL of the issue you just created.
```
### Adding Leader issues
-

### Complete
- [ ] Check this when all the Add leader issues have been made
```
- [ ] if the above comment already exists, just add your new issue URL to the list. 
- [ ] Check off the box, if it's the last one that needed to be created.
</details> 

<details><summary>Removing volunteers from team page</summary>

- [x] Create a new issue using the [remove new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---remove.md&title=Update+Project+Profile%3A+%5BName+of+Project%5D+Remove+%5BName+of+Volunteer%5D) template
- [x] Customize the title with name of project and person to add
- [x] Customize the body
   - [x] In the ER, go to the value under the line "Project Card URL"
      - [x] Copy the file name 
      - [x] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md) 
   - [x] Go to https://github.com/hackforla/website/tree/gh-pages/_projects and find and click on the file
      - [x] click on code view
      - [x] copy the code block
      - [x] highlight the text on your new issue where it says `[Insert the lines of code to remove the specified leadership member]` and delete it and replace with the copy block
   - [x] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [x]  to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [ ] click on its link
      - [ ] copy link
      - [ ] replace brackets on resource 2 with the URL
   - [x] Add link to the ER on resource 3
- [x] Choose `Update comment` button
- [x] Add milestone `Onboarding flow`
- [x] Review, and if ready, add label

```
Ready for Prioritization
```
- [ ] Add the URL to a comment on this ER
   1. if this is the first remove leader issue to be created, paste this into a comment on this issue and add the URL of the issue you just created.
```
### Removing Leader issues
-

### Complete
- [ ] Check this when all the removal issues have been made
```
- [ ] if the above comment already exists, just add your new issue URL to the list. 
- [ ] Check off the box, if it's the last one that needed to be created.
</details> 

- [x] When you have completed making all the add and remove issues
   - [x] move this issue into the Questions/Review column
   - [x] add the `ready for product` label

### Project Update Data 

--- 

### Project Name

Guides Team

### Project Card URL

guides-team.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

YES

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Ayma Rahman
Name: Mary Gabrielian

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: France Chan
GitHub Handle: fchan218
Role: PM
Slack Member ID: U07FJRY99SR

Name: Jesus Diaz
GitHub Handle: JesseTheCleric
Role: PM
Slack Member ID: U0725MRMMA9

Name: Aditya Soni
GitHub Handle: Aditya23soni
Role: PM
Slack Member ID:U07F766J29M

### Project Status

Active

**Comment by ExperimentsInHonesty** [comment]
These changes are approved and need to be made into good first issues

**Comment by HackforLABot** [comment]
Hi @bexux, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by bexux** [comment]
Availability: evenings 4-6pm pacific
ETA: by end of Friday

**Comment by bexux** [comment]
### Removing Leader issues
- https://github.com/hackforla/website/issues/7581
- https://github.com/hackforla/website/issues/7582

### Complete
- [x] Check this when all the removal issues have been made

**Comment by bexux** [comment]
### Adding Leader issues
- https://github.com/hackforla/website/issues/7583
- https://github.com/hackforla/website/issues/7584
- https://github.com/hackforla/website/issues/7585

### Complete
- [x] Check this when all the Add leader issues have been made

**Comment by ExperimentsInHonesty** [comment]
@bexux Thanks for making the issues.
