### ISSUE TITLE
Create Issues to add new variable github-handle for members in work-for-la.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7268]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
As developers we need to create issues to update each project team member in work-for-la.md with a the new `github-handle` variable, that will eventually replace the `github` and `picture` variables, reducing redundancy in the project file.   

### Action Items
- [x] For each team member listed in `_projects/work-for-la.md` **that does not have a variable `github-handle`**, create an issue using the [template](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D)
- [x] For each issue:
   - [x] In the title, replace [INSERT MEMBER NAME] with the member's name
   - [x] In the title, replace [INSERT PROJECT FILE] with **work-for-la.md**
   - [x] Under Action Items, replace [INSERT MEMBER NAME] with the member's name (in 2 places)
   - [x] Under Action Items, replace [INSERT PROJECT FILE] with **work-for-la.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILE] with **work-for-la.md**
   - [x] Under Resources, replace [INSERT-PROJECT-FILENAME-WITHOUT-.MD-EXTENSION] with **work-for-la.md**
   - [x] Apply the following labels: "ready for dev lead", "good first issue", "role: front end", "role: back end/devOps", "size: 0.25pt", "P-Feature: Project Info and Page"
   - [x] List the issue number in #5441 under Good First Issues 
- [x] When all issues have been created and listed, move this issue to the "Questions/In Review" column of the Project Board, and apply the label "ready for dev lead"
  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Webpage: https://www.hackforla.org/projects/work-for-la.md
- This issue is part of #5441

**Comment by HackforLABot** [comment]
Hi @rachelcorawood, HfLA appreciates your interest in this issue, but please note that it is in the  **"New Issue Approval"**  column of the Project Board because it has not been finalized, approved, or prioritized, and so it is not ready for assignment. For this reason, you have been unassigned from this issue. Please remember to assign issues only from the  **"Prioritized Backlog"**  column.  

The only exceptions to this rule are if you are writing an issue and the `Draft` label is applied, or if you are self-assigning to your "Pre-work Checklist" (the issue includes the `Complexity: Prework` label).

**Comment by HackforLABot** [comment]
Hi @vorleakyek, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by vorleakyek** [comment]
I created this #7384 ticket and listed it under #5441. It looks like there is only one member in that file.

**Comment by LRenDO** [comment]
Hi @vorleakyek! You did excellent work creating the new issue and replacing the relevant information. I see the issue is linked in the Epic issue. Thanks for contributing to the Epic!

**Comment by kgold2018** [comment]
- ticket  #7384 was created .I am moving to "Done " current issue
