### ISSUE TITLE
Create issues to update Project Profile: 311 Data

### ISSUE THREAD

**Issue by bberhane** [hackforla/website#7301]
### Overview
The project team from 311 Data needs its project leadership variable information updated, so that the current team members can be properly displayed on the Hack for LA website

### Action Items
- [x] Review the Project Update Data below and then follow the instructions for either adding or deleting team members from the project's .md

<details><summary>Adding new volunteers to team page</summary>

- [x] Create a new issue using the [add new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---add.md&title=Update+Project+Profile%3A+%5BProject+Name%5D+Add+%5BName+of+Volunteer%5D) template
- [x]  Customize the title with name of project and person to add
- [x]  Customize the body
   - [x]   In the ER, go to the value under the line "Project Card URL"
      - [x]  Copy the file name 
      - [x] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md)
   - [x] In the copy block below the line that starts, "Find the `leadership` variable and add the following profile."  add all the information from the ER for the person you are adding.
   - [x] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [x] to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [x] click on its link
      - [x] copy link
      - [x] replace brackets on resource 2 with the URL
   - [x] Add link to the ER on resource 3
- [x] Choose `Update comment` button
- [x] Add milestone `Onboarding flow`
- [x] Review, and if ready, add label
```
Ready for Prioritization
```
- [x] Add the URL to a comment on this ER
    - [x] if this is the first add leader issue to be created, paste this into a comment and add the URL of the issue you just created.
```
### Adding Leader issues
-

### Complete
- [ ] Check this when all the Add leader issues have been made
```
- [x] if the above comment already exists, just add your new issue URL to the list. 
- [x] Check off the box, if it's the last one that needed to be created.
</details> 

<details><summary>Removing volunteers from team page</summary>

- [x] Create a new issue using the [remove new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---remove.md&title=Update+Project+Profile%3A+%5BName+of+Project%5D+Remove+%5BName+of+Volunteer%5D) template
- [x] Customize the title with name of project and person to add
- [x] Customize the body
   - [x] In the ER, go to the value under the line "Project Card URL"
      - [x] Copy the file name 
      - [x] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md) 
   - [x] Go to https://github.com/hackforla/website/tree/gh-pages/_projects and find and click on the file
      - [x] click on code view
      - [x] copy the code block
      - [x] highlight the text on your new issue where it says `[Insert the lines of code to remove the specified leadership member]` and delete it and replace with the copy block
   - [x] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [x]  to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [x] click on its link
      - [x] copy link
      - [x] replace brackets on resource 2 with the URL
   - [x] Add link to the ER on resource 3
- [x] Choose `Update comment` button
- [x] Add milestone `Onboarding flow`
- [x] Review, and if ready, add label

```
Ready for Prioritization
```
- [x] Add the URL to a comment on this ER
   1. if this is the first remove leader issue to be created, paste this into a comment on this issue and add the URL of the issue you just created.
```
### Removing Leader issues
-

### Complete
- [ ] Check this when all the removal issues have been made
```
- [x] if the above comment already exists, just add your new issue URL to the list. 
- [x] Check off the box, if it's the last one that needed to be created.
</details> 

- [x] When you have completed making all the add and remove issues
   - [x] move this issue into the Questions/Review column
   - [x] add the `ready for product` label

### Project Update Data 

--- 

### Project Name

311 Data

### Project Card URL

311-data.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Sanju Venugopal
Name: Anna Kim
Name: Ahmed Awadalla
Name: Edwin Jue

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Joy Truex
GitHub Handle: Joy-Truex
Role: UX Design Lead
Slack Member ID: U03VBPSEH52

Name: Allison Jeon
GitHub Handle: allisonjeon
Role: UX Design Lead
Slack Member ID: U05JP94R9B7

### Project Status

Active

**Comment by ExperimentsInHonesty** [comment]
This is ready to be turned into issues. All marked time sensitive.

**Comment by HackforLABot** [comment]
Hi @mmcclanahan, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by mmcclanahan** [comment]
eta: 9/30 EOD
avail: after 7pm sunday, monday-tues all day

**Comment by mmcclanahan** [comment]
### Adding Leader issues
- https://github.com/hackforla/website/issues/7541
- https://github.com/hackforla/website/issues/7542

### Complete
- [x] Check this when all the Add leader issues have been made

**Comment by mmcclanahan** [comment]
### Removing Leader issues
- https://github.com/hackforla/website/issues/7547
- https://github.com/hackforla/website/issues/7548
- https://github.com/hackforla/website/issues/7549
- https://github.com/hackforla/website/issues/7550

### Complete
- [x] Check this when all the removal issues have been made

**Comment by ExperimentsInHonesty** [comment]
@mmcclanahan Good job making the issues to add the people.  I have prioritized those issues.  Looking forward to you finishing making the removal issues.

**Comment by ExperimentsInHonesty** [comment]
@mmcclanahan Good job.  Thanks!
