### ISSUE TITLE
Epic: Create issues to update Project Profile: LA TDM Calculator

### ISSUE THREAD

**Issue by Parisajf** [hackforla/website#7305]
### Overview
The project team from TDM Calculator needs its project leadership variable information updated, so that the current team members can be properly displayed on the Hack for LA website

### Action Items
- [x] Review the Project Update Data below and then follow the instructions for either adding or deleting team members from the project's .md

<details><summary>Adding new volunteers to team page</summary>

- [x] Create a new issue using the [add new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---add.md&title=Update+Project+Profile%3A+%5BProject+Name%5D+Add+%5BName+of+Volunteer%5D) template
- [x]  Customize the title with name of project and person to add
- [x]  Customize the body
   - [ ]   In the ER, go to the value under the line "Project Card URL"
      - [ ]  Copy the file name 
      - [ ] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md)
   - [ ] In the copy block below the line that starts, "Find the `leadership` variable and add the following profile."  add all the information from the ER for the person you are adding.
   - [ ] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [ ] to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [ ] click on its link
      - [ ] copy link
      - [ ] replace brackets on resource 2 with the URL
   - [ ] Add link to the ER on resource 3
- [ ] Choose `Submit new issue` button
- [ ] Add milestone `Onboarding flow`
- [ ] Review, and if ready, add label
```
Ready for Prioritization
```
- [ ] Add the URL to a comment on this ER
    - [ ] if this is the first add leader issue to be created, paste this into a comment and add the URL of the issue you just created.
```
### Adding Leader issues
-

### Complete
- [ ] Check this when all the Add leader issues have been made
```
- [ ] if the above comment already exists, just add your new issue URL to the list. 
- [ ] Check off the box, if it's the last one that needed to be created.
</details> 

<details><summary>Removing volunteers from team page</summary>

- [ ] Create a new issue using the [remove new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---remove.md&title=Update+Project+Profile%3A+%5BName+of+Project%5D+Remove+%5BName+of+Volunteer%5D) template
- [ ] Customize the title with name of project and person to add
- [ ] Customize the body
   - [ ] In the ER, go to the value under the line "Project Card URL"
      - [ ] Copy the file name 
      - [ ] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md) 
   - [ ] Go to https://github.com/hackforla/website/tree/gh-pages/_projects and find and click on the file
      - [ ] click on code view
      - [ ] copy the code block
      - [ ] highlight the text on your new issue where it says `[Insert the lines of code to remove the specified leadership member]` and delete it and replace with the copy block
   - [ ] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [ ]  to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [ ] click on its link
      - [ ] copy link
      - [ ] replace brackets on resource 2 with the URL
   - [ ] Add link to the ER on resource 3
- [ ] Choose `Submit new issue` button
- [ ] Add milestone `Onboarding flow`
- [ ] Review, and if ready, add label

```
Ready for Prioritization
```
- [ ] Add the URL to a comment on this ER
   1. if this is the first remove leader issue to be created, paste this into a comment on this issue and add the URL of the issue you just created.
```
### Removing Leader issues
-

### Complete
- [ ] Check this when all the removal issues have been made
```
- [ ] if the above comment already exists, just add your new issue URL to the list. 
- [ ] Check off the box, if it's the last one that needed to be created.
</details> 

- [x] When you have completed making all the add and remove issues
   - [x] move this issue into the Questions/Review column
   - [x] add the `ready for product` label

### Project Update Data 

--- 

### Project Name

LA TDM Calculator

### Project Card URL

website.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

YES

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

YES

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Ebi Imafidon
Name: Anousha Shadrach
Name: Jane He

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Parisa Jannatifard
Github Handle: Parisajf
Role: Product Manager
Slack ID: U05PG72SL56, 

Name: Mauli shah
Github Handle: maulieshah
Role: Product Manager
Slack ID: U070E9F68QL

Name: Abby Rivard
Github Handle: abbyrivard
Role : UX Research Lead
Slack ID: U05N5Q9TY8Z

Name: Heejung Hong
Github Handle: heejung-hong
Role: Front End Development Lead
Slack ID:U064M7X48SY, 

Name: Melissa Perry
Github Handle: melissaperry09
Role: UX Research Lead
Slack ID:U05MCJTTPN3, 

Nilakshi Sahai
Github Handle: NilakshiS
Role: UX Design Lead
Slack ID:U06SYVD69L7

Marlena Mellody Khim-Sai
Github Handle: marlenamellody
Role: UX Design Lead
Slack ID: U06DSRCSXRD

### Project Status

Active

**Comment by ExperimentsInHonesty** [comment]
@Parisajf You did not submit the form correctly. You submitted as

![image](https://github.com/user-attachments/assets/5127b05c-1edf-4310-a26c-aebb6c81ad22)


The correct format is 
![image](https://github.com/user-attachments/assets/c44744bf-b2c9-4056-9b53-6eb0b6821156)


I have corrected it this time (see above).  Next time, the website team will kick it back to you, if it does not come in properly formatted.

**Comment by ExperimentsInHonesty** [comment]
This is ready to be turned into issues.  All marked time sensitive.

**Comment by Parisajf** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
@Parisajf This issue has been set up, so that team members can make issues from it.  We should have a new crop of volunteers this week.

**Comment by HackforLABot** [comment]
Hi @theogguu, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by theogguu** [comment]
Availability: M > F
ETA: EOD Friday

**Comment by theogguu** [comment]
### Adding Leader issues
- #7643 
- #7644 
- #7645 
- #7646 
- #7647
- #7648
- #7649

### Complete
- [x] Check this when all the Add leader issues have been made

**Comment by theogguu** [comment]
### Removing Leader issues
- #7650 
- #7651 
- #7652 

### Complete
- [x] Check this when all the removal issues have been made

**Comment by theogguu** [comment]
Added the "dependency" label because the template used for the issues asks the developers to uncheck it when it's finished. Was this correct? Could the templates or create issues instructions be outdated?

**Comment by theogguu** [comment]
It's come to my attention that the Slack ID for #7643 was incorrect. It's been changed from U05PG72SL56 to [U05Q5D34ARZ](https://hackforla.slack.com/team/U05Q5D34ARZ).

**Comment by theogguu** [comment]
#7643 - for Parisa Jannatifard, slack ID U05PG72SL56 was found to be incorrect, changed to U05Q5D34ARZ on the issue.

**Comment by ExperimentsInHonesty** [comment]
@theogguu Added notes to the following issue
- https://github.com/hackforla/website/issues/7645
After you fix it and put a ready for prioritization, ill review it and close this epic.

**Comment by theogguu** [comment]
@ExperimentsInHonesty #7645 should be fixed now, could you close the epic please?

**Comment by t-will-gillis** [comment]
@JessicaLucindaCheng 
Had to close manually...
