### ISSUE TITLE
Create issues to update Project Profile: Website

### ISSUE THREAD

**Issue by mayankt153** [hackforla/website#7317]
### Overview
The project team from website needs its project leadership variable information updated, so that the current team members can be properly displayed on the Hack for LA website

### Action Items
- [x] Review the Project Update Data below and then follow the instructions for either adding or deleting team members from the project's .md

<details><summary>Adding new volunteers to team page</summary>

- [x] Create a new issue using the [add new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---add.md&title=Update+Project+Profile%3A+%5BProject+Name%5D+Add+%5BName+of+Volunteer%5D) template
- [x]  Customize the title with name of project and person to add
- [x]  Customize the body
   - [x]   In the ER, go to the value under the line "Project Card URL"
      - [x]  Copy the file name 
      - [x] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md)
   - [x] In the copy block below the line that starts, "Find the `leadership` variable and add the following profile."  add all the information from the ER for the person you are adding.
   - [x] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [x] to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [x] click on its link
      - [x] copy link
      - [x] replace brackets on resource 2 with the URL
   - [x] Add link to the ER on resource 3
- [x] Choose `Update comment` button
- [x] Add milestone `Onboarding flow`
- [x] Review, and if ready, add label
```
Ready for Prioritization
```
- [x] Add the URL to a comment on this ER
    - [x] if this is the first add leader issue to be created, paste this into a comment and add the URL of the issue you just created.
```
### Adding Leader issues
-

### Complete
- [ ] Check this when all the Add leader issues have been made
```
- [x] if the above comment already exists, just add your new issue URL to the list. 
- [x] Check off the box, if it's the last one that needed to be created.
</details> 

<details><summary>Removing volunteers from team page</summary>

- [ ] Create a new issue using the [remove new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---remove.md&title=Update+Project+Profile%3A+%5BName+of+Project%5D+Remove+%5BName+of+Volunteer%5D) template
- [ ] Customize the title with name of project and person to add
- [ ] Customize the body
   - [ ] In the ER, go to the value under the line "Project Card URL"
      - [ ] Copy the file name 
      - [ ] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md) 
   - [ ] Go to https://github.com/hackforla/website/tree/gh-pages/_projects and find and click on the file
      - [ ] click on code view
      - [ ] copy the code block
      - [ ] highlight the text on your new issue where it says `[Insert the lines of code to remove the specified leadership member]` and delete it and replace with the copy block
   - [ ] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [ ]  to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [ ] click on its link
      - [ ] copy link
      - [ ] replace brackets on resource 2 with the URL
   - [ ] Add link to the ER on resource 3
- [ ] Choose `Update comment` button
- [ ] Add milestone `Onboarding flow`
- [ ] Review, and if ready, add label

```
Ready for Prioritization
```
- [ ] Add the URL to a comment on this ER
   1. if this is the first remove leader issue to be created, paste this into a comment on this issue and add the URL of the issue you just created.
```
### Removing Leader issues
-

### Complete
- [ ] Check this when all the removal issues have been made
```
- [ ] if the above comment already exists, just add your new issue URL to the list. 
- [ ] Check off the box, if it's the last one that needed to be created.
</details> 

- [x] When you have completed making all the add and remove issues
   - [x] move this issue into the Questions/Review column
   - [x] add the `ready for product` label

### Project Update Data 

--- 

### Project Name

Hackforla.org Website

### Project Card URL

website.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

NO

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Samhitha Kamma
GitHub Handle: Samhitha444
Role: Product Manager
Slack Member ID: U07FF529MU6

Name: Mayank Tibrewal
GitHub Handle: mayankt153
Role: Product Manager
Slack Member ID: U07FF4G9D0W

Name: Venkatasai Poorna Tushara Chada
GitHub Handle: Tusharachada1406
Role: Product Manager
Slack Member ID: U07FF4FALT0

### Project Status

Active

**Comment by ExperimentsInHonesty** [comment]
This addition looks good to me.  This issue is ready to be made into a small issue.

**Comment by HackforLABot** [comment]
Hi @siyunfeng, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by siyunfeng** [comment]
**Availability**: 6:00 PM - 10:00 PM Weekdays (EDT)
**ETA**: 10/24/2024 Thursday

**Comment by siyunfeng** [comment]
### Adding Leader issues
- #7619
- #7620
- #7621

### Complete
- [x] Check this when all the Add leader issues have been made

**Comment by siyunfeng** [comment]
Hi, @mayankt153 !

I could not find the `Update comment` button mentioned in the action list above **Add milestone `Onboarding flow`**. 
Does it mean to click the `Submit new issue` button instead?

**Comment by daras-cu** [comment]
@siyunfeng thank you for bringing your question up at the meeting tonight, I'm confirming you should use the `Submit new issue` button. If you don't have any other questions about this issue you can move it back to `In Progress` status and remove the `ready for product` label.

**Comment by siyunfeng** [comment]
> @siyunfeng thank you for bringing your question up at the meeting tonight, I'm confirming you should use the `Submit new issue` button. If you don't have any other questions about this issue you can move it back to `In Progress` status and remove the `ready for product` label.

Thank you for clarifying, @daras-cu !

The following actions after creating all the issues from this ER required me to do these:

- [ ] When you have completed making all the add and remove issues
  - [ ]  move this issue into the Questions/Review column
  - [ ]  add the ready for product label
 
I'm still waiting for someone to review this issue. Should I still move this issue back to `In Progress` status and remove the `ready for product` label as you suggested?

**Comment by roslynwythe** [comment]
Thank you @siyunfeng for creating these good first issues
