### ISSUE TITLE
EPIC: Create issues to Update Project Profile: Expunge Assist

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/website#7321]
### Overview
The project team from Expunge Assist needs its project leadership variable information updated, so that the current team members can be properly displayed on the Hack for LA website

### Action Items
- [x] Review the Project Update Data below and then follow the instructions for either adding or deleting team members from the project's .md

<details><summary>Adding new volunteers to team page</summary>

- [ ] Create a new issue using the [add new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---add.md&title=Update+Project+Profile%3A+%5BProject+Name%5D+Add+%5BName+of+Volunteer%5D) template
- [ ]  Customize the title with name of project and person to add
- [ ]  Customize the body
   - [ ]   In the ER, go to the value under the line "Project Card URL"
      - [ ]  Copy the file name 
      - [ ] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md)
   - [ ] In the copy block below the line that starts, "Find the `leadership` variable and add the following profile."  add all the information from the ER for the person you are adding.
   - [ ] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [ ] to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [ ] click on its link
      - [ ] copy link
      - [ ] replace brackets on resource 2 with the URL
   - [ ] Add link to the ER on resource 3
- [ ] Choose `Submit new issue` button
- [ ] Add milestone `Onboarding flow`
- [ ] Review, and if ready, add label
```
Ready for Prioritization
```
- [ ] Add the URL to a comment on this ER
    - [ ] if this is the first add leader issue to be created, paste this into a comment and add the URL of the issue you just created.
```
### Adding Leader issues
-

### Complete
- [ ] Check this when all the Add leader issues have been made
```
- [ ] if the above comment already exists, just add your new issue URL to the list. 
- [ ] Check off the box, if it's the last one that needed to be created.
</details> 

<details><summary>Removing volunteers from team page</summary>

- [x] Create a new issue using the [remove new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---remove.md&title=Update+Project+Profile%3A+%5BName+of+Project%5D+Remove+%5BName+of+Volunteer%5D) template
- [x] Customize the title with name of project and person to add
- [x] Customize the body
   - [x] In the ER, go to the value under the line "Project Card URL"
      - [x] Copy the file name 
      - [x] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md) 
   - [x] Go to https://github.com/hackforla/website/tree/gh-pages/_projects and find and click on the file
      - [x] click on code view
      - [x] copy the code block
      - [x] highlight the text on your new issue where it says `[Insert the lines of code to remove the specified leadership member]` and delete it and replace with the copy block
   - [x] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [x]  to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [x] click on its link
      - [x] copy link
      - [x] replace brackets on resource 2 with the URL
   - [x] Add link to the ER on resource 3
- [x] Choose `Submit new issue` button
- [x] Add milestone `Onboarding flow`
- [x] Review, and if ready, add label

```
Ready for Prioritization
```
- [x] Add the URL to a comment on this ER
   1. if this is the first remove leader issue to be created, paste this into a comment on this issue and add the URL of the issue you just created.
```
### Removing Leader issues
-

### Complete
- [ ] Check this when all the removal issues have been made
```
- [x] if the above comment already exists, just add your new issue URL to the list. 
- [ ] Check off the box, if it's the last one that needed to be created.
</details> 

- [x] When you have completed making all the add and remove issues
   - [x] move this issue into the Questions/Review column
   - [x] add the `ready for product` label

### Project Update Data 

--- 

### Project Name

Expunge Assist

### Project Card URL

expunge-assist.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Analicia Mejia Mesinas

### Add person(s) and info to Leadership?

NO

### Project Status

Active

**Comment by essencegoff** [comment]
### Removing Leader issues
-

### Complete
- [x] Check this when all the removal issues have been made
https://github.com/hackforla/website/issues/7487

**Comment by HackforLABot** [comment]
Hi @mrodz, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by mrodz** [comment]
**Availability**: Weekdays 4-11pm
**ETA**: EOD Thursday, 10/3/24

**Comment by mrodz** [comment]
I just realized @essencegoff worked on this issue without assigning themselves. My bad. I will unassign myself.

**Comment by essencegoff** [comment]
@mrodz Sorry for the delay. I am not working on this issue. I just updated the template. My apologies for the confusion.

**Comment by HackforLABot** [comment]
Hi @DakuwoN, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by DakuwoN** [comment]
Availability: Monday - Thursday 10AM - 7PM CST and Friday - Sunday 5PM CST - 10PM CST 
ETA: Sunday November 3rd, 2024

**Comment by DakuwoN** [comment]
https://github.com/hackforla/website/issues/7686

**Comment by ExperimentsInHonesty** [comment]
@DakuwoN I am sorry @essencegoff misspoke.  She ha already created the issue, as shown above in her comment
- https://github.com/hackforla/website/issues/7487.  So I will be closing #7686 as unplanned.  It's important to read the issue, because many people are just starting out, and there is a risk that they will have made a mistake. Your first assessment was correct.

**Comment by HackforLABot** [comment]
Hello @essencegoff, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by HackforLABot** [comment]
Hello @essencegoff, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by DakuwoN** [comment]
Alright no problem. Thank you Bonnie

**Comment by ExperimentsInHonesty** [comment]
-  Note to QAThis issue can get put in the done column when https://github.com/hackforla/website/issues/7487 has been completed.

**Comment by HackforLABot** [comment]
Hello @essencegoff, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by ExperimentsInHonesty** [comment]
At some point this issue needs to get reassigned to Essence so she can get credit for having worked on it.  But every time I do, it brings it back to new issue approval because she is already assigned to other things.

**Comment by HackforLABot** [comment]
Hi @t-will-gillis, HfLA appreciates your interest in this issue, but please note that it is in the  **"New Issue Approval"**  column of the Project Board because it has not been finalized, approved, or prioritized, and so it is not ready for assignment. For this reason, you have been unassigned from this issue. Please remember to assign issues only from the  **"Prioritized Backlog"**  column.  

The only exceptions to this rule are if you are writing an issue and the `Draft` label is applied, or if you are self-assigning to your "Pre-work Checklist" (the issue includes the `Complexity: Prework` label).

**Comment by HackforLABot** [comment]
Hi @t-will-gillis, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by HackforLABot** [comment]
Hello @essencegoff, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis I cant remember how we said we were going to solve this?

**Comment by t-will-gillis** [comment]
@ExperimentsInHonesty there is a PR in the queue to address this:
- PR #7817 
- fixes #7771 
Hopefully will wrap it up soon

**Comment by t-will-gillis** [comment]
@essencegoff @ExperimentsInHonesty update: the PR is merged- the bot will allow Essence to be assigned to the issue.
