### ISSUE TITLE
EPIC: Create Issues to update Project Profile: Home Unite Us

### ISSUE THREAD

**Issue by lola3736** [hackforla/website#7362]
### Overview
The project team from Home Unite Us needs its project leadership variable information updated, so that the current team members can be properly displayed on the Hack for LA website

### Action Items
- [x] Review the Project Update Data below and then follow the instructions for either adding or deleting team members from the project's .md

<details><summary>Adding new volunteers to team page</summary>

- [x] Create a new issue using the [add new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---add.md&title=Update+Project+Profile%3A+%5BProject+Name%5D+Add+%5BName+of+Volunteer%5D) template
- [x]  Customize the title with name of project and person to add
- [x]  Customize the body
   - [x]   In the ER, go to the value under the line "Project Card URL"
      - [x]  Copy the file name 
      - [x] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md)
   - [x] In the copy block below the line that starts, "Find the `leadership` variable and add the following profile."  add all the information from the ER for the person you are adding.
   - [x] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [x] to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [x] click on its link
      - [x] copy link
      - [x] replace brackets on resource 2 with the URL
   - [x] Add link to the ER on resource 3
- [x] Choose `Submit new issue` button
- [x] Add milestone `Onboarding flow`
- [x] Review, and if ready, add label
```
Ready for Prioritization
```
- [x] Add the URL to a comment on this ER
    - [x] if this is the first add leader issue to be created, paste this into a comment and add the URL of the issue you just created.
```
### Adding Leader issues
-

### Complete
- [ ] Check this when all the Add leader issues have been made
```
- [x] if the above comment already exists, just add your new issue URL to the list. 
- [x] Check off the box, if it's the last one that needed to be created.
</details> 

<details><summary>Removing volunteers from team page</summary>

- [ ] Create a new issue using the [remove new leader to project](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt%2C+time+sensitive&projects=&template=project-profile-leader-updates---remove.md&title=Update+Project+Profile%3A+%5BName+of+Project%5D+Remove+%5BName+of+Volunteer%5D) template
- [ ] Customize the title with name of project and person to add
- [ ] Customize the body
   - [ ] In the ER, go to the value under the line "Project Card URL"
      - [ ] Copy the file name 
      - [ ] On the line that starts "- [ ] In your IDE…" replace brackets with the copy (the text we are expecting is a file name with the extension .md) 
   - [ ] Go to https://github.com/hackforla/website/tree/gh-pages/_projects and find and click on the file
      - [ ] click on code view
      - [ ] copy the code block
      - [ ] highlight the text on your new issue where it says `[Insert the lines of code to remove the specified leadership member]` and delete it and replace with the copy block
   - [ ] On the checkbox line below, "- [ ] Verify the changes by viewing..." replace with name of project
   - [ ]  to Resource 2, find the project on the https://www.hackforla.org/projects/ page
      - [ ] click on its link
      - [ ] copy link
      - [ ] replace brackets on resource 2 with the URL
   - [ ] Add link to the ER on resource 3
- [ ] Choose `Submit new issue` button
- [ ] Add milestone `Onboarding flow`
- [ ] Review, and if ready, add label

```
Ready for Prioritization
```
- [ ] Add the URL to a comment on this ER
   1. if this is the first remove leader issue to be created, paste this into a comment on this issue and add the URL of the issue you just created.
```
### Removing Leader issues
-

### Complete
- [ ] Check this when all the removal issues have been made
```
- [ ] if the above comment already exists, just add your new issue URL to the list. 
- [ ] Check off the box, if it's the last one that needed to be created.
</details> 

- [x] When you have completed making all the add and remove issues
   - [x] move this issue into the Questions/Review column
   - [x] add the `ready for product` label

### Project Update Data 

--- 

### Project Name

Home Unite Us

### Project Card URL

home-unite-us.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Stephen Barkley-Yeung (Developer)
Name: Kristelle Gumaru (Product Manager)
Name: Raji Pradheap (Product Manager)
Name: Bryce Lednar (Product Manager)
Name: Farah Khan (UX/UI Designer)
Name: Eduardo De La Rosa (UX/UI Designer)
Name: Flora Osmond (UX/UI Designer)
Name: Rachel Bracker (Design Lead)
Name: Samuel Kowitch (UX/UI Designer)
Name: Muyin Zheng (UX/UI Designer)
Name: Emily Eldar (Developer)
Name: Name: Jed Stewart (Developer)

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Lola Sarumi
GitHub Handle: lola3736
Role: Lead Product / Project   
Slack Member ID: U06TAL88YUV

Name: Sanya Nijhawan
GitHub Handle: sanya301
Role: Advisory  
Slack Member ID: U031FLYS561

Name: Ariel Lasry
GitHub Handle: lasryariel
Role: Product Manager (Lead Persona)
Slack Member ID: U06MG4S8D2B

Name: Jasika Kalra
GitHub Handle: jasika-ai
Role: Product Manager (Lead Persona)
Slack Member ID: U03J4C686KV

Name: Jasmine Guraya
GitHub Handle: jasmineg95
Role: Product Manager (Lead Persona)
Slack Member ID: U07FMLJGUFM

Name: Gabriella Dominic
GitHub Handle: gabcdominic
Role: Product manager
Slack Member ID: U07FF4FCTUN

Name: John Wroge
GitHub Handle: johnwroge
Role: Developer
Slack Member ID: U05Q7V3KGCU

Name: Paul Espinosa
GitHub Handle: paulespinosa
Role: Developer
Slack Member ID: U058S2D5C95

Name: Nicci Van
GitHub Handle: nlvan
Role: Lead Designer / User Research
Slack Member ID: U07FML1PXJP

Name: Jon Ilaw
GitHub Handle: ilawjon
Role: UI/UX Designer (Persona Lead)
Slack Member ID: U07G0DPTPSM

Name: Amy Li
GitHub Handle: amydli
Role: UI/UX Designer
Slack Member ID: U07FQ7NQUMA

Name: Nihan Durmaz
GitHub Handle: nihandurmaz
Role: UI/UX Designer
Slack Member ID: U07GAJ3BLGY

Name: Jazmyne Newman
GitHub Handle: jazmynn123
Role: User Research
Slack Member ID: U07HLLXHYS2

### Revise this person's listing to change title to this new one
Name: Tyler Thome
GitHub Handle: tylerthome
Role: Lead Developer 
Slack Member ID: ULN1M6UAH

### Project Status

Active

**Comment by HackforLABot** [comment]
Hi @lola3736, we notice that you are assigned to an issue that you authored. Please remember to add the `Draft` label to this issue while you are working on it.

**Comment by essencegoff** [comment]
### Removing Leader issues
- https://github.com/hackforla/website/issues/7472
- https://github.com/hackforla/website/issues/7474
- https://github.com/hackforla/website/issues/7475
- https://github.com/hackforla/website/issues/7476
- https://github.com/hackforla/website/issues/7477
- https://github.com/hackforla/website/issues/7479
- https://github.com/hackforla/website/issues/7480
- https://github.com/hackforla/website/issues/7481
- https://github.com/hackforla/website/issues/7482
- https://github.com/hackforla/website/issues/7483
- https://github.com/hackforla/website/issues/7484
- https://github.com/hackforla/website/issues/7485

### Complete
- [X] Check this when all the removal issues have been made

**Comment by essencegoff** [comment]
### Adding Leader issues
- https://github.com/hackforla/website/issues/7488
- https://github.com/hackforla/website/issues/7489

### Complete
- [x] Check this when all the Add leader issues have been made

**Comment by ExperimentsInHonesty** [comment]
Note for QA after this issue is done: When all the issues for adding people have been completed, We will need to make a new issue to reorder the current members.

**Comment by HackforLABot** [comment]
Hello @DrAcula27, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by ExperimentsInHonesty** [comment]
All the removing issues are done, only two of the adding people issues have been made.

**Comment by HackforLABot** [comment]
Hello @mchait18, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by ExperimentsInHonesty** [comment]
- [x] Make issues for the following people, check them off here and add them to the Sub Issue drop down at the top of this issue when you finish

### The following issues to add people have not been made
- [x] Ariel
Name: Ariel Lasry
GitHub Handle: lasryariel
Role: Product Manager (Lead Persona)
Slack Member ID: U06MG4S8D2B

- [x] Jasika
Name: Jasika Kalra
GitHub Handle: jasika-ai
Role: Product Manager (Lead Persona)
Slack Member ID: U03J4C686KV

- [x] Jasmine
Name: Jasmine Guraya
GitHub Handle: jasmineg95
Role: Product Manager (Lead Persona)
Slack Member ID: U07FMLJGUFM

- [x] Gabriella
Name: Gabriella Dominic
GitHub Handle: gabcdominic
Role: Product manager
Slack Member ID: U07FF4FCTUN

- [x] John
Name: John Wroge
GitHub Handle: johnwroge
Role: Developer
Slack Member ID: U05Q7V3KGCU

- [ ] Paul
Name: Paul Espinosa
GitHub Handle: paulespinosa
Role: Developer
Slack Member ID: U058S2D5C95

- [ ] Nicci 
Name: Nicci Van
GitHub Handle: nlvan
Role: Lead Designer / User Research
Slack Member ID: U07FML1PXJP

- [ ] Jon 
Name: Jon Ilaw
GitHub Handle: ilawjon
Role: UI/UX Designer (Persona Lead)
Slack Member ID: U07G0DPTPSM

- [ ] Amy
Name: Amy Li
GitHub Handle: amydli
Role: UI/UX Designer
Slack Member ID: U07FQ7NQUMA

- [ ] Nihan
Name: Nihan Durmaz
GitHub Handle: nihandurmaz
Role: UI/UX Designer
Slack Member ID: U07GAJ3BLGY

- [ ] Jazmyne
Name: Jazmyne Newman
GitHub Handle: jazmynn123
Role: User Research
Slack Member ID: U07HLLXHYS2

- [ ] Aisha
Name: Aisha Uqdah
GitHub Handle: imanuq
Role: Product Manager
Slack Member ID: U088J0DHZRB


### Create an issue to revise this person's listing to change title to this new one
- [ ] Tyler
Name: Tyler Thome
GitHub Handle: tylerthome
Role: Lead Developer
Slack Member ID: ULN1M6UAH

**Comment by HackforLABot** [comment]
Hello @mademarc, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

We are going to unassign you from this issue so you can focus on your current issue.

Hfla appreciates you! :)

**Comment by HackforLABot** [comment]
Hi @mademarc, HfLA appreciates your interest in this issue, but please note that it is in the  **"New Issue Approval"**  column of the Project Board because it has not been finalized, approved, or prioritized, and so it is not ready for assignment. For this reason, you have been unassigned from this issue. Please remember to assign issues only from the  **"Prioritized Backlog"**  column.  

The only exceptions to this rule are if you are writing an issue and the `Draft` label is applied, or if you are self-assigning to your "Pre-work Checklist" (the issue includes the `Complexity: Prework` label).

**Comment by HackforLABot** [comment]
Hi @mademarc, HfLA appreciates your interest in this issue, but please note that it is in the  **"New Issue Approval"**  column of the Project Board because it has not been finalized, approved, or prioritized, and so it is not ready for assignment. For this reason, you have been unassigned from this issue. Please remember to assign issues only from the  **"Prioritized Backlog"**  column.  

The only exceptions to this rule are if you are writing an issue and the `Draft` label is applied, or if you are self-assigning to your "Pre-work Checklist" (the issue includes the `Complexity: Prework` label).

**Comment by ExperimentsInHonesty** [comment]
The only issues remaining to make are the following
- see top of issues for their details

### Add (Issues Still Needed) 

- [x] Paul Espinosa (Developer)
- [x] Nicci Van (Lead Designer / User Research)
- [x] Jon Ilaw (UI/UX Designer - Persona Lead)
- [x] Amy Li (UI/UX Designer)
- [x] Nihan Durmaz (UI/UX Designer)
- [x] Jazmyne Newman (User Research)

### Revisions Needed

- [x] Tyler Thome → Update title to Lead Developer

**Comment by HackforLABot** [comment]
Hi @Cloid, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by Cloid** [comment]
availability: weekdays 5pm-10pm pst
eta: eod friday

**Comment by Cloid** [comment]
### Adding Leader issues
- #7943 
- #7944 
- #7953 
- #7954 
- #7955 
- #7956 

### Complete
- [x] Check this when all the Add leader issues have been made

**Comment by Cloid** [comment]
### Updating Leader's Role issue
- #7957 

### Complete
- [x] Check this when Updating Leader's Role issues have been made

**Comment by t-will-gillis** [comment]
Hi @Cloid Thank you for completing the remaining issues in this epic- they look great!

Closing this issue as successfully completed.
