### ISSUE TITLE
Milestone to Label Transition for All Issues

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#745]
### Overview
We need to start to leverage labels as a way of grouping issues, rather than using milestones to group issues. This will allow us to quickly filter the board based on a topic and free up milestones for their true purpose - tracking feature launches. 

### Action Items

- [x] Create label for known groupings 
- [x] Tag issues in existing milestones with the label
- [x] Remove issues from milestones and delete any irrelevant milestones 
- [ ] Identify issues that are marked as 'Done' that should have the new label 
- [ ] Identify any issues in the backlog, in progress, or icebox that should have the new labels 

### Resources/Instructions
[Example of how TDM is using labels correctly](https://github.com/hackforla/tdm-calculator/labels)
[HfLA labels](https://github.com/hackforla/website/labels)
[HfLA milestones](https://github.com/hackforla/website/milestones)
[HfLA issues](https://github.com/hackforla/website/issues)

**Comment by alexandrastubbs** [comment]
So far, the following labels have been created: 

1. Feature - Analytics
2. Feature - Project Pages
3. Feature - Toolkit
4. Feature - Guides (maybe should delete if this is redundant to Toolkit)

I am using [this work](https://docs.google.com/spreadsheets/d/12L6YE47DliyZyEwaOGCINfnQd-9dRW_Pwd941dIWufQ/edit#gid=0) that I did previously to guide future label creation. 

I also realize that I should change Analytics to something else because it is not really a 'feature'. 

I would like to update our labels to be more similar to TDM Calculators in that they include things like 'dev:' at the start to also aid in categorization. 

Some other feature labels that I think we would benefit from include: 

1. Feature - Onboarding 
2. Feature - Educational Page (i.e. Join Us, About Us) - maybe not the right name?
3. Research - Analytics (change from Feature - Analytics)
4. Research - Surveys 

More to come. Now, I will be focused on categorizing the issues that exist today with the already existing labels.

**Comment by ExperimentsInHonesty** [comment]
Let's review before you start labeling all the issues

**Comment by alexandrastubbs** [comment]
Status: Will flesh this out into a formal proposal for next week

**Comment by alexandrastubbs** [comment]
Proposal for labels: 

Feature - Analytics (_complete_)
Feature - Project Pages (_complete_)
Feature - Toolkit (_complete_)
Feature - Organizational Page --- would like this to cover other pages like home page, about us, join us, etc. If this gets to be too much, we can divide it up. 

After doing some sifting through the issues, I don't think we need to create any other new labels. We would be categorizing for the sake of categorizing. I did not that TDM calculator uses labels to distinguish between different types of dev work. I propose that we bring this up at the next team meeting and ask if there are any use cases for labels that would be helpful for the team that we are not yet employing.

**Comment by alexandrastubbs** [comment]
All labels have been created and tagged to open issues. Going to close this issue now.
