### ISSUE TITLE
EPIC: Prepare the About Us page for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7662]
### Overview
We need to track existing issues and make new issues to deliver About Us page complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [ ] Make the issues specified
- [ ] Link them as sub issues to this issue
- [ ] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: P-Feature: About Us
    - 1.01.01 Issue Tab: [P-Feature: About Us](https://github.com/hackforla/website/labels/P-Feature%3A%20About%20Us)
    - 1.01.02 Project Board: [P-Feature: About Us](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=label%3A%22P-Feature%3A+About+Us%22)
- 1.02 URL of page on Hack for LA website: https://www.hackforla.org/about/
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data\/internal\/credits\// About Us](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+About+Us&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+About+Us&type=wikis
   - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
- [ ] HOLDING FOR COMPLETION OF SDG ISSUES - Remove the Hack for LA Supports SDGs from the about page. Keep the page/information in code but make it inaccessible from the website. Page/SDG support information can still be found but will not be easy.  

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 8504

### Must Have
- [ ] #7662 
   - why: It is the epic for this page (this issue)
   - status: Ready for Prioritization 
      - draft: True  
      - responsible: nadiaspn0503   
   - role: Product

- [ ] #7506 (the metrics section of the site has a link to Survey Results. The content at that link is being updated by the people responsible for the epic.)
   - why: We need to manage the work for the Org dashboard, so that we can prioritize and recruit.
   - status: New Issue Approval
      - draft: True 
      - responsible: none
   - role: Product

- [ ] #8504
   - why: We need to rewrite the Hack for LA Platform to ensure all the information is correct and up-to-date.
   - status: Ready for Prioritization 
      - draft: False
      - responsible: None
   - role: Product and Writing 

- [ ] #8498
   - why: We need to update the Civic Tech Structure text in the header from Civic Tech Structure to Civic Tech Structure, Inc., a 501(c)(3) nonprofit organization to make the page consistent with the industry standard.
   - status: Ready for Prioritization
      - draft: False
      - responsible: none
   - role: Front end

- [ ] #8484
   - why: We need to post the rewritten letter from the executive director on the site code so that it appears in the designated place on the website.
   - status: Ice box  
      - draft: False
      - responsible: none
   - role: Front end

- [ ] #8483
   - why: We need to rewrite the letter from the executive director to go in the designated space on the website.
   - status: Ice box  
      - draft: False 
      - responsible: none
   - role: Writing

- [ ] #8431
   - why: We need to move the Our Locations section from the events page to the About Us page to highlight that we were an active in person organization that moved to remote meetings.
   - status: New Issue Approval
      - draft: True 
      - responsible: none
   - role: front end and back end/devOps

### Could Have
<details><summary>List of all could have issues</summary>

- #6666 
   - why: Unclear or irrelevant alert message.    
   - status: Ice Box  
      - draft: False  
      - responsible: None 
   - role: Front End

- #4153 
   - why: We want to move and refactor the SDG info and images so that they can be more easily reused. 
   - status: In Progress (actively working)
      - draft: False  
      - responsible: JessicaLucindaCheng 
   - role: Dev Leads   

</details>

### Won't have this time
<details><summary>List of all won't have issues</summary>

- #6819 
- #4282
- #4190 
- #2174

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```
<details><summary>List of all issue by number</summary>

- #8504
- #8498
- #8484
- #8483
- #8431
- #7662
- #7506
- #6819
- #6666
- #4282
- #4190
- #4153
- #2174

</details>

**Comment by ExperimentsInHonesty** [comment]
# List of all issues
- [ ] #7712
- [ ] #7689
- [ ] #7623

**Comment by ExperimentsInHonesty** [comment]
- These notes are transferred from the https://github.com/hackforla/website/issues/2481#issuecomment-2155756054
We made a sub issue for the Accomplishments section.  Determine if we need to make sub issues for the other sections.  If it's just one or two issues we don't, but if it's more complex like Accomplishments we do need to make an epic tracking.

### About Us page
- [x] URL: https://hackforla.org/about
- [x] [About Us issues on project board](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22p-feature%3A+about+us%22)
- Sections
   - ED Letter 
     - [ ] Revise the letter in this closed issue #860
     - [ ] make a new issue to add the letter to the site.
   - Sustainability
     - See SDG section below, the content for this, should be dynamic and be pulled from each project file.
   - Accomplishments 
      - see issue https://github.com/hackforla/website/issues/7663
   - Metrics (dashboard)
      - URL: https://hackforla.org/dashboard
      - [Org Dashboard Issues on the project board](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22p-feature%3A+dashboard%22)
      - [ ] Review survey results and identify what might need to be changed
      - [ ] Add Google Analytics to the Dashboard https://github.com/hackforla/website/issues/4537
      - [ ] See this issue to evaluate if its related https://github.com/hackforla/website/issues/1730
      - [ ] See this issue and see if there are any issues on other repositories that might be required to complete the dashboard.
   - Partners
      - [ ] Change title to be Current and Past Partners
   - Sponsors
      - [ ] Change title to be Current and Past Sponsors

**Comment by priyanka02art** [comment]
# List of all issues
- [ ] #7662  
- [ ] #6819 
- [ ] #6666 
- [ ] #6140 
- [ ] #4282 
- [ ] #4190 
- [ ] #4153 
- [ ] #3019 
- [ ] #2174  


## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7662 
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval  
      - draft: True  
      - responsible: None  
   - role: Product
- [ ] #6666 
   - why: Unclear or irrelevant alert message.    
   - status: Ice Box  
      - draft: False  
      - responsible: None 
   - role: Front End

### Should Have
- [ ] #3019 
   - why: We need to provide information about the scope of Hack for LA's activities, including working with City of LA and other organizations/networks.  
   - status: Ice Box  
      - draft: False  
      - responsible: None 
   - role: User Research 

### Could Have
- [ ] #6140  
   - why: Civic Tech Structures full name is Civic Tech Structure, Inc. and sometimes it makes sense to say Civic Tech Structure, Inc. 501(c)(3) or even Civic Tech Structure, Inc. a non profit 501(c)(3). Different pages have different listings.  
   - status: Emergent Requests  
      - draft: False  
      - responsible: @ExperimentsInHonesty 
   - role: Product
- [ ] #4282  
   - why: We need a system to track and display when specific practice area wins are needed for the randomizer, show which wins are currently included per practice area, and monitor which wins have been used in the past.  
   - status: Ice box 
      - draft: False 
      - responsible: @roslynwythe 
   - role: Front End
- [ ] #4153 
   - why: We want to move and refactor the SDG info and images so that they can be more easily reused. 
   - status: In Progress  
      - draft: False  
      - responsible: @JessicaLucindaCheng 
   - role: Dev Leads   

### Won't have this time
- [ ] #6819 
   - why: Refactor issue 
   - status: Emergent Request  
      - draft: True  
      - responsible: @ExperimentsInHonesty   
   - role: Back end/DevOps 
- [ ] #4190  
   - why: We need a randomizer for the about page so that we can give visibility to different volunteer types.  
   - status: Ice Box 
      - draft: True
      - responsible: None 
   - role: Front End 
- [ ] #2174  
   - why: Need to standardize our elements for all teams in the website project. For this issue, the element to standardize is the sticky side nav on the [about page](https://www.hackforla.org/about/).  
   - status: Ice Box  
      - draft: False  
      - responsible: None
   - role: Front End
#### Templates
```
   - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by ExperimentsInHonesty** [comment]
- [ ] Letter from the executive director (there is an issue where it got written, now we need an issue for adding it to the site before launch https://github.com/hackforla/website/issues/860#issuecomment-2155758500)

**Comment by ExperimentsInHonesty** [comment]
- [ ] Hack for LA Platform needs a rewrite

**Comment by ExperimentsInHonesty** [comment]
- [ ] Issue to remove the HfLA Supports SDGs from the about page

**Comment by ExperimentsInHonesty** [comment]
- [ ] add a comment under the must haves, that links to this issue https://github.com/hackforla/website/issues/7506, with the text: The metrics section of the site has a link to Survey Results.  The content at that link is being updated by the people responsible for the epic.

**Comment by nadiaspn0503** [comment]
2026-08-18
Using this search 
[state:open label:"P-Feature: About Us" is:issue ](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20About%20Us%22%20is%3Aissue)

This is the highest issue number found 8504 it is addressed at the top of this issue.

**Comment by nadiaspn0503** [comment]
To do: Check through each section listed in issue 6140 to see what the industry standard is and make a comment in this issue suggesting what should be done.
- https://github.com/hackforla/website/issues/6140
