### ISSUE TITLE
EPIC: Prepare the About Us, Accomplishment Section for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7663]
### Overview
We need to track existing issues and make new issues to deliver About Us, Accomplishment Section complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [ ] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [ ] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [ ] Make the issues specified
- [ ] Link them as sub issues to this issue
- [ ] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: [p-feature: accomplishments](https://github.com/hackforla/website/labels/p-feature%3A%20accomplishments)
- 1.02 URL of page on Hack for LA website: https://www.hackforla.org/about/#accomplishments
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// accomplishments](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+accomplishments&type=code)
   - https://github.com/hackforla/website/blob/gh-pages/_data/internal/accomplishments.yml (has the 2020 content in it)
   - https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-accomplishments.html controls how it appears in the accomplishments section
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+accomplishments&type=wikis
  - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
TBD

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 8476

### Must Have
- [ ] #7663   
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: nadiaspn0503 
   - role: Product

- [ ] #8476
   - why: We need a new issue form template that will allow project teams add or revise an accomplishment for a specified year.
   - status: New Issue Approval
      - draft: False
      - responsible: None
   - role: Front end

- [ ] #8288  
   - why: Need to create a template to update the accomplishments for the Guides team on the about page
   - status: In progress (actively working)
      - draft: False
      - responsible: ldaws003 
   - role: Front end

- [ ] #7578   
   - why: We need to write brief summaries of project accomplishments for each year of the project's life, to go on the website's accomplishments page. 
   - status: New Issue Approval
      - draft: True  
      - responsible: None   
   - role: Project 

### Could Have
<details><summary>List of all could have issues</summary>

</details>

### Won't have this time
<details><summary>List of all won't have issues</summary>

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #8476
- #8288
- #7663
- #7578

</details>

**Comment by priyanka02art** [comment]
- Use this epic to find all the accomplishment issues for 2021-2024 on each project's repo: https://github.com/hackforla/admin-accomplishments/issues/3
      - https://github.com/hackforla/CivicTechJobs/issues/548#issuecomment-2364227231
   - We have made some issues for projects to give us their accomplishments for the accomplishment page. We have created a new project board to track that [Admin: Project Team Tasks, Accomplishment tab](https://github.com/orgs/hackforla/projects/7/views/10)
   -  We need to find all the relevant issues for each project and add them to the board . Here is an org search for accomplishment https://github.com/search?q=org%3Ahackforla+accomplishments&type=issues

**Comment by ExperimentsInHonesty** [comment]
- These notes were transferred from https://github.com/hackforla/website/issues/2481#issuecomment-2155756054
 - [x] Find all the other accomplishment content that has been written and identify what is missing
 - [x] Move the URLs to top of issue
        <details><summary>URLs for technical issues</summary>
        <p>
           - https://github.com/hackforla/website/blob/gh-pages/_data/internal/accomplishments.yml (has the 2020 content in it)
           - https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-accomplishments.html controls how it appears in the accomplishments section     
        </p>
        </details>

**Comment by priyanka02art** [comment]
# List of all issues
- [ ] #7663  
- [ ] #7578 


## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7663   
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product
- [ ] #7578   
   - why: We need to write brief summaries of project accomplishments for each year of the project's life, to go on the website's accomplishments page. 
   - status: In Progress  
      - draft: False  
      - responsible: @essencegoff   
   - role: Project 

### Should Have
- [ ] #  
   - why:  
   - status:  
      - draft:  
      - responsible:  
   - role:  

### Could Have
- [ ] # 
   - why:  
   - status:  
      - draft:  
      - responsible: 
   - role:  
   
### Won't have this time
- [ ] #   
   - why:  
   - status:  
      - draft:  
      - responsible:  
   - role:  


#### Templates
```
   - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by nadiaspn0503** [comment]
2026-08-18
Using this search 
[state:open label:"p-feature: accomplishments" is:issue ](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22p-feature%3A%20accomplishments%22%20is%3Aissue)

This is the highest issue number found 8628 it is addressed at the top of this issue.

**Comment by nadiaspn0503** [comment]
To do: schedule meeting with Vihar for creating instructions for this issue
- https://github.com/hackforla/website/issues/7578#issuecomment-3408253453
