### ISSUE TITLE
EPIC: Prepare the Projects page for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7666]
### Overview
We need to track existing issues and make new issues to deliver Projects page complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [x] Make the issues specified
- [x] Link them as sub issues to this issue
- [x] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: P-Feature: Projects page
    - 1.01.01 Issue Tab: [P-Feature: Projects page](https://github.com/hackforla/website/labels/P-Feature%3A%20Projects%20page)
    - 1.01.02 Project Board: [P-Feature: Projects Page](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=label%3A%22P-Feature%3A+Projects+page%22+)
- 1.02 URL of page on Hack for LA website: https://www.hackforla.org/projects/
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// projects](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+projects&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+projects&type=wikis
   - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]

---
### Must Have
TBD 

### Should Have
TBD

### Could Have
TBD

---
last updated: 2026-04-21
Highest number found: 8510

### Must Have
- [ ] #7666  
   - why: It is the epic for this page (this issue)
   - status: In Progress (actively working)
      - draft: True
      - responsible: priyanka02art and nadiaspn0503 
   - role: Product

- [ ] #8510
   - why: Our website needs to use the Oxford comma consistently so that the website is correct and uniform. In this issue we will be changing text on the Project Page.
   - status: Ready for Prioritization 
      - draft: False
      - responsible: None 
   - role: Back end/devOps and front end

- [ ] #8507
   - why: We need to correctly classify tools and technologies used in projects so users/volunteers have clarity on what systems are being used.
   - status: New Issue Approval
      - draft: True
      - responsible: kirandhamotharan 
   - role: Front end 

- [ ] #8506
   - why: We need to confirm Docker usage and ensure projects with Dockerfiles have Docker listed in their Technologies section, so users/volunteers have clarity on what systems are being used.
   - status: In progress (actively working)
      - draft: False
      - responsible: kirandhamotharan 
   - role: Project

- [ ] #8496
   - why: We need to fix the bug on the projects and projects check pages that prevents the "whiteboard / paper & pencil" tool filter from being selected so that the website will work correctly.
   - status: Ready for Prioritization 
      - draft: False
      - responsible: none
   - role: Back end/devOps and front end

- [ ] #8485
   - why: We need to Identify the difference between the Docker technology and Dockerfile language filters.
   - status: New Issue Approval
      - draft: False
      - responsible: None
   - role: Front end

- [ ] #8467
   - why: We need to integrate the search bar with the filter system so that search terms update the filter counter, provide immediate visual feedback, and allow users to continuously add multiple search terms.
   - status: New Issue Approval
      - draft: False
      - responsible: None 
   - role: back end/devOps and front end

- [ ] #8466
   - why: We need to fix the mobile view search behavior so that the page maintains its scroll position and the filter bar remains open after a user performs a search.
   - status: New Issue Approval
      - draft: False
      - responsible: None 
   - role: Front end

- [ ] #8332
   - why: Need to have Projects page with correct information.
   - status: Prioritized backlog
      - draft: False
      - responsible: None
   - role: back end/devOps and front end

- [ ] #8054
   - why: Helps PMs and leads know what to do with "Update Project Profile" ERs or epics with sub-issue(s) that have already been written
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role: dev leads, merge team, and product

- [ ] #4434 
   - why: We need to make sure that languages are not being added to tools and technologies fields on project.md cards and that items that should be in tools are not in technologies and vice versa
   - status: Ice Box
      - draft: False
      - responsible: None
   - role: Dev leads and Product

- [ ] #4262 
   - why: Ensure users receive accurate and relevant information to navigate seamlessly between projects.
   - status: In progress (actively working)
      - draft: False
      - responsible: kirandhamotharan 
   - role: Product

### Should Have
- #6138   
   - why: without this projects that have more than one repo, will only have their primary repo show up on the project's page and their project info page  
   - status: In Progress (actively working)
      - draft: False
      - responsible: JessicaLucindaCheng 
   - role: Back end/DevOps and front end

### Could Have
<details><summary>List of all could have issues</summary>

 - #8490
   - why: Potentially we could remove the completed projects to an archived section unless we want to keep them on the site for visibility. 
   - status: Ready for Prioritization 
      - draft: False
      - responsible: None
   - role: back end/devOps and front end

 - #8353
   - why: Need to update 'Languages/Technologies/Tools' filter to be easier to navigate
   - status: In progress (actively working) 
      - draft: False
      - responsible: aadilahmed 
   - role: back end/devOps and front end

- #6675 - this issue might get resolved before we launch but it's not required.
   - why: There seems to be an incorrect alert but not sure what action triggers the alert. need more clarity ExperimentsInHonesty   
   - status: Ice Box
      - draft: False
      - responsible: None
   - role: Front End 
 
- #6143
   - why: To enhance user experience, add a "List View" button on the Projects and Toolkit pages for a more concise presentation of information.
   - status: Ice Box
      - draft: True
      - responsible: None
   - role: Front End
   
</details>

### Won't have this time
<details><summary>List of all won't have issues</summary>

- #6819 

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: YYYY-MM-DD
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #8510
- #8507
- #8506 
- #8496
- #8490
- #8485
- #8467
- #8466
- #8353
- #8332 
- #8054
- #7666
- #6819
- #6675
- #6143
- #6138
- #4434
- #4262

</details>

**Comment by priyanka02art** [comment]
### Notes carried forward from epic 
- URL: https://www.hackforla.org/projects
- [Project Board, label:"P-Feature: Projects page"](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=label%3A%22P-Feature%3A+Projects+page%22)
- The drop downs have to have consistent content in them (problems with languages, technologies and tools).
   - https://github.com/hackforla/website/issues/6709
   - https://github.com/hackforla/website/issues/4434
   - https://github.com/hackforla/website/issues/4262
- Make an ER to address the difference between
   - https://www.hackforla.org/projects-check/?technologies=Docker
   - https://www.hackforla.org/projects-check/?languages=Dockerfile
- The chevron we currently have is unattractive. They need to look better. See http://civictechindex.org/about/faq and make an ER to improve ours

- #2211
- Projects Technologies being up to date

**Comment by priyanka02art** [comment]
# List of all issues
- [x] #7666
- [x] #7525 
- [x] #6819 
- [x] #6675 (need to be reviewed by @ExperimentsInHonesty)
- [x] #6143 
- [x] #6138 
- [x] #4434 
- [x] #4262 


## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7666  
   - why: It is the epic for this page (this issue)
   - status: In Progress
      - draft: True
      - responsible: @priyanka02art 
   - role: Product

- [ ] #4434 
   - why: We need to make sure that languages are not being added to tools and technologies fields on project.md cards and that items that should be in tools are not in technologies and vice versa
   - status: Ice Box
      - draft: False
      - responsible: None
   - role: Product

- [ ] #4262 
   - why: Ensure users receive accurate and relevant information to navigate seamlessly between projects.
   - status: New Issue approval
      - draft: False
      - responsible: None
   - role: Product

### Should Have

### Could Have
- [ ] #7525
   - why: To improve the usability of the filters, search and project display on mobile so that it is easy for people to navigate the project list.
   - status: Questions/In Review
      - draft: False
      - responsible: @aswutmaxcy 
   - role: Front End 
- [ ] #6143
   - why: To enhance user experience, add a "List View" button on the Projects and Toolkit pages for a more concise presentation of information.
   - status: Ice Box
      - draft: True
      - responsible: None
   - role: Front End
- [ ] #6675 - this issue might get resolved before we launch but it's not required.
   - why: There seems to be an incorrect alert but not sure what action triggers the alert. need more clarity @ExperimentsInHonesty   
   - status: Ice Box
      - draft: False
      - responsible: None
   - role: Front End
- [ ] #6138   
   - why: without this projects that have more than one repo, will only have their primary repo show up on the project's page and their project info page  
   - status: In Progress
      - draft: False
      - responsible: @JessicaLucindaCheng 
   - role: Back end/DevOps
   
### Won't have this time
- [ ] #6819  
   - why: Refactor issue 
   - status: Emergent Request
      - draft: True
      - responsible: ExperimentsInHonesty 
   - role: Back end/DevOps


#### Templates
```
   - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by priyanka02art** [comment]
Task items
- [ ] ~Add template under each issue in the MoSCoW list~ skip this
- [x] Review all the issues on [issue tab with P-Feature: Projects page](https://github.com/hackforla/website/labels/P-Feature%3A%20Projects%20page) and add any issues missing from the List of all issues

**Comment by ExperimentsInHonesty** [comment]
@priyanka02art The list of all issues above https://github.com/hackforla/website/issues/7666#issuecomment-2471511005 only covers 5 issues, but there are 11 open issues with the [`P-Feature: Projects page`](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Projects%20page%22) label.  

- [x] We need to list them all, so that we can categorize them.

**Comment by ExperimentsInHonesty** [comment]
already have 
- 7525
- 6143 
- 4434 
- 4262 
- 6675

**Comment by priyanka02art** [comment]
- #7866 
- #7666
- #7525 
- #6819 
- #6709 
- #6675 (need to be reviewed by @ExperimentsInHonesty)
- #6143 
- #6138 
- #6129 
- #4434 
- #4262

**Comment by priyanka02art** [comment]
### Issues list associated with this epic
last updated: 2025-03-13
Highest number found: 7866

**Comment by priyanka02art** [comment]
### New issues to triage

- #7985 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
- #7984 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role:

**Comment by priyanka02art** [comment]
### Issues list associated with this epic
last updated: 2025-03-11
Highest number found: 7985

**Comment by nadiaspn0503** [comment]
### Issues list associated with this epic
last updated: 2025-10-28
Highest number found: 8353
- #8353
- #8334
- #8333
- #8332
- #8054

--- 
### Must have
 - #8334
   - why: Need to have Projects page with correct information.
   - status: New Issue Approval
      - draft: False
      - responsible: None 
   - role: back end/devOps and front end

 - #8333
   - why: Need to have Projects page with correct information.
   - status: New Issue Approval
      - draft: False
      - responsible: None 
   - role: back end/devOps and front end

 - #8332
   - why: Need to have Projects page with correct information.
   - status: New Issue Approval
      - draft: False
      - responsible: None 
   - role: back end/devOps and front end

 - #8054
   - why: Helps PMs and leads know what to do with "Update Project Profile" ERs or epics with sub-issue(s) that have already been written
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role: dev leads, merge team, and product

### Should have

### Could have
 - #8353
   - why: Need to update 'Languages/Technologies/Tools' filter to be easier to navigate
   - status: New Issue Approval
      - draft: False
      - responsible: None
   - role: back end/devOps and front end

### Won't have

**Comment by nadiaspn0503** [comment]
2026-08-18
Using this search 
[state:open label:"P-Feature: Projects page" is:issue ](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Projects%20page%22%20is%3Aissue)

This is the highest issue number found 8711 it is addressed at the top of this issue.

**Comment by ExperimentsInHonesty** [comment]
- [x] Check to see if this already exists as an issue or ER,  if it does, check the below off and add the issue to the should have, if not
   - [x] The chevron we currently have is unattractive. They need to look better. See http://civictechindex.org/about/faq and make an ER to improve ours
- [x] Check to see if this already exists as an issue or ER,  if it does, check the below off and add the issue to the must have, if not
   - [x] Make an ER to address the difference between
      - https://www.hackforla.org/projects-check/?technologies=Docker
      - https://www.hackforla.org/projects-check/?languages=Dockerfile
- [x] Make a final check epic called and attach it as the child of the main initiative and add its link to the top section of this issue at 1.05
   ```
   Product: Final checks for Homepage Launch
   ```
   - [x] Add the following items to the checklist in that issue (action items)
      ```
      - [ ] Is Projects Technologies up to date.
         - [REPLACE WITH INSTRUCTIONS FOR HOW TO CHECK]
      ```
