### ISSUE TITLE
EPIC: Prepare the Dashboard page for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7667]
### Overview
We need to track existing issues and make new issues to deliver Dashboard page complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [x] Make the issues specified
- [x] Link them as sub issues to this issue
- [x] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: P-Feature: Dashboard
    - 1.01.01 Issue Tab: [P-Feature: Dashboard Page](https://github.com/hackforla/website/issues?q=is%3Aopen%20label%3A%22P-Feature%3A%20Dashboard%22%20)
    - 1.01.02 Project Board: [P-Feature: Dashboard Page](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=+label%3A%22P-Feature%3A+Dashboard%22)
- 1.02 URL of page on Hack for LA website: https://hackforla.org/dashboard
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// Dashboard](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+dashboard&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+dashboard&type=wikis
   - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
TBD

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 7725

### Must Have
- #7667 
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: nadiaspn0503 
   - role: Product

If we do have the could have done by the time homepage is ready to launch then create a new issue to hind the metrics section on about page.
### Could Have
<details><summary>List of all could have issues</summary>

- #7725 
   - why: It lists all requirements for the Org Dashboard to ensure clear priorities, resource allocation, and effective management as we move forward with development.
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product

- #7506 
   - why: Manage the work for Org dashboard to prioritize and recruit.
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product

- #6229 
   - why: To detect when the dashboard data script fails
   - status: New Issue Approval
      - draft: True
      - responsible: ExperimentsInHonesty 
   - role: backend/DevOps

</details> 

### Won't have this time
<details><summary>List of all won't have issues</summary>

- #6614
- #4537 
- #128 

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #7725
- #7667
- #7506 
- #6614 
- #6229
- #4537
- #128

</details>

**Comment by priyanka02art** [comment]
# List of all issues
- [x] #7667
- [x] #7725 
- [x] #7506 
- [x] #6614 
- [x] #6229 
- [x] #4537
- [x] #128 

## Relevance of the issues to the Homepage launch
### Must Have 
If we do have the could have done by the time homepage is ready to launch then create a new issue to hind the metrics section on about page.
### Should Have
- [ ] # 
   - why:  
   - status: 
      - draft: 
      - responsible:  
   - role: 

### Could Have
- [ ] #6229 
   - why: To detect when the dashboard data script fails
   - status: New Issue Approval
      - draft: True
      - responsible: @ExperimentsInHonesty 
   - role: backend/DevOps
- [ ] #7667 
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product
- [ ] #7725 
   - why: It lists all requirements for the Org Dashboard to ensure clear priorities, resource allocation, and effective management as we move forward with development.
   - status: In Progress
      - draft: True
      - responsible: @Eleftherios01 
   - role: Product
- [ ] #7506 
   - why: Manage the work for Org dashboard to prioritize and recruit.
   - status: New Issue Approval
      - draft: True
      - responsible: @Eleftherios01 
   - role: Product
- [ ] #6614  
   - why: to identify and start building a roadmap for all the website dashboards, so that we can prioritize, manage and recruit.
   - status: In progress
      - draft: False
      - responsible: @Eleftherios01, @eleftherios06, @ExperimentsInHonesty, @Samhitha444, @Tusharachada1406, @sofiatajide 
   - role: Product
### Won't have this time
- [ ] #4537 
   - why:  Good to have data for analytics about behavior of people on the current HFLA website. 
   - status: ERs and epics that are re.... & New Issue Approval
      - draft: False
      - responsible: None
   - role: Data Analyst
- [ ] #128  
   - why:  Good to have data for analytics about how many people we reach/visit the site are not on the Dashboard. For example: What % of visitors click a top menu item? OR Of that %, what is the breakdown of which menu item they click?
   - status: Ice box
      - draft: False
      - responsible: None
   - role: Backend/DevOps

#### Template
```
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by nadiaspn0503** [comment]
2026-08-18
Using this search 
[state:open label:"P-Feature: Dashboard" is:issue ](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Dashboard%22%20is%3Aissue)

This is the highest issue number found 7725 it is addressed at the top of this issue.
