### ISSUE TITLE
EPIC: Prepare the Program Areas page for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7670]
### Overview
We need to track existing issues and make new issues to deliver Program Areas page complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [ ] Make the issues specified
- [ ] Link them as sub issues to this issue
- [ ] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: P-Feature: Program Area
    - 1.01.01 Issue Tab: [P-Feature: Program Area Page](https://github.com/hackforla/website/issues?q=is%3Aopen+label%3A%22P-Feature%3A+Program+Area%22)
    - 1.01.02 Project Board: [P-Feature: Program Area Page](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=+label%3A%22P-Feature%3A+Program+Area%22)
- 1.02 URL of page on Hack for LA website: https://www.hackforla.org/program-areas
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// Program Area](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+program+areas&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+Program+Area&type=wikis
   - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
- [ ] Clean up program areas
- [ ] Remove SDGs

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 8487

### Must Have
- [ ] #7670 
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: nadiaspn0503 
   - role: Product

- [ ] #8487
   - why: We need to add links to each program area to the page they go to.
   - status: Ready for Prioritization 
      - draft: True
      - responsible: JessicaLucindaCheng    
   - role: Back end/devOps and front end

- [ ] #8470
   - why: The text overflows in the Sustainable Development component in mobile widths. These issues was noticed in the program area pages such as https://www.hackforla.org/program-areas/citizen-engagement. Also, the text forms a thin column to the side when the mobile width is wide enough.
   - status: In progress (actively working)
      - draft: False
      - responsible: DakuwoN and Sk-223    
   - role: Front end

- [ ] #8167
   - why: We want to update the description in the header of the program area pages so that the page can be converted in the future to create a template that works for all our program areas.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng     
   - role: Back end/devOps and front end

- [ ] #2037
   - why: We need to add information to each project md file so that we can display it on the new Impact format
   - status: New Issue Approval
      - draft: True
      - responsible: None    
   - role: Product

### Could Have
<details><summary>List of all could have issues</summary>
   
</details>

### Won't have this time
<details><summary>List of all won't have issues</summary>

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #8487
- #8470
- #8167
- #7670
- #2037

</details>

**Comment by priyanka02art** [comment]
- URL: https://www.hackforla.org/program-areas

- [Program Areas Issues on the project board](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22p-feature%3A+program+area%22)

     [ ]https://github.com/hackforla/website/issues/3328

**Comment by priyanka02art** [comment]
# List of all issues
- [x] #7670
- [x] #7425 
- [ ] #7424 
- [ ] #7404 
- [ ] #7383 
- [ ] #3328 
- [ ] #2037 


## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7670 
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product

### Should Have
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role: 

### Could Have
- [ ] #2037
   - why: We need to add information to each project md file so that we can display it on the new Impact format
   - status: New Issue Approval
      - draft: True
      - responsible: None    
   - role: Product

### Won't have this time
- [x] #7425 
   - why: Refactor issue 
   - status: New Issue Approval
      - draft: True
      - responsible: @JessicaLucindaCheng   
   - role: Front end
- [ ] #7424
   - why: Refactor issue
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Back end/DevOps & Front end
- [ ] #7404
   - why: Refactor issue
   - status: New Issue Approval
      - draft: True
      - responsible: @JessicaLucindaCheng 
   - role: Back end/DevOps & Front end
- [ ] #7383
   - why: Refactor issue
   - status: New Issue Approval
      - draft: True
      - responsible: @JessicaLucindaCheng 
   - role: Back end/DevOps & Front end
- [ ] #3328 
   - why: Refactor issue (We want each program area page created dynamically so we don't have to manually code each page.)
   - status: New Issue Approval
      - draft: True
      - responsible: @JessicaLucindaCheng 
   - role: Front end

#### Template
```
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```

```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by ExperimentsInHonesty** [comment]
@sneha-kataria Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

You can use this template
```
1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary): 
```

**Comment by nadiaspn0503** [comment]
2026-08-18
Using this search 
[state:open label:"P-Feature: Program Area" is:issue ](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Program%20Area%22%20is%3Aissue)

This is the highest issue number found 8470 it is addressed at the top of this issue.

**Comment by JessicaLucindaCheng** [comment]
- https://github.com/hackforla/website/issues/3328: This issue is ready to be prioritized.  
- I'll check these 3 issues this week to see if they can be closed as unplanned with a note or what the next steps will be
  - https://github.com/hackforla/website/issues/7424
  - https://github.com/hackforla/website/issues/7404
  - https://github.com/hackforla/website/issues/7383

**Comment by nadiaspn0503** [comment]
@JessicaLucindaCheng just checking on your last comment from 2025-11-17 where you mentioned you'd "check these 3 issues this week to see if they can be closed as unplanned with a note or what the next steps will be
  - https://github.com/hackforla/website/issues/7424
  - https://github.com/hackforla/website/issues/7404
  - https://github.com/hackforla/website/issues/7383"

Are there any updates that you can provide?

**Comment by JessicaLucindaCheng** [comment]
@nadiaspn0503 


> [@JessicaLucindaCheng](https://github.com/JessicaLucindaCheng) just checking on your last comment from 2025-11-17 where you mentioned you'd "check these 3 issues this week to see if they can be closed as unplanned with a note or what the next steps will be
> 
> * [Epic: Change _program-area Files From -card.yml to .md #7424](https://github.com/hackforla/website/issues/7424)
> * [Template for #7383: Change a `_program-areas` File From `-card.yml` to `.md` for `[Insert the current name of the file].yml` #7404](https://github.com/hackforla/website/issues/7404)
> * [Write Issues to Change `_program-area` Files From `-card.yml` to `.md` #7383](https://github.com/hackforla/website/issues/7383)"
> 
> Are there any updates that you can provide?

I've closed all of them as duplicates.
