### ISSUE TITLE
EPIC: Prepare the Homepage page for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7673]
### Overview
We need to track existing issues and make new issues to deliver Homepage page complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [ ] Make the issues specified
- [ ] Link them as sub issues to this issue
- [ ] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: P-Feature: Home page
    - 1.01.01 Issue Tab: [P-Feature: Home Page](https://github.com/hackforla/website/issues?q=is%3Aopen+label%3A%22P-Feature%3A+Home+Page%22)
    - 1.01.02 Project Board: [P-Feature: Home Page](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=+label%3A%22P-Feature%3A+Home+Page%22)
- 1.02 URL of page on Hack for LA website: https://www.hackforla.org/
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// Homepage page](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+homepage+page&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+Home+Page&type=wikis
  - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
- Take out mentions of DEI

- Revise program areas

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 8353

### Must Have
 - [ ] #2481 
    - why: We need to track and support the final wrap up items for the homepage launch, so that it can be completed.   
    - status: In progress (actively working)
      - draft: False
      - responsible: ExperimentsInHonesty and nadiaspn0503  
   - role: Product  

- [ ] #7673   
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: nadiaspn0503 
   - role: Product

- [ ] #3934 
   - why: We need to create two new composite images to replace the images that we are using, that we don't have a license for, so that we can be in compliance.   
   - status: Ice Box 
      - draft: False  
      - responsible: None 
   - role: Design Lead

- [ ] #2763  
   - why: Finalize images of zooms for homepage  
   - status: New Issue Approval  
      - draft: False  
      - responsible: None  
   - role: User Research

### Should Have
- [ ] #8353 
   - why: Need to update 'Languages/Technologies/Tools' filter to be easier to navigate
   - status: In progress (actively working)
      - draft: False  
      - responsible: aadilahmed 
   - role: back end/devOps and front end

- [ ] #4607 
   - why: It is important to recreate images to maintain credibility, brand consistency and content quality on a website.  
   - status: Prioritized backlog
      - draft: False
      - responsible: None
   - role: Design

### Could Have
<details><summary>List of all could have issues</summary>

- #4282  
   - why: We need a system to track and display when specific practice area wins are needed for the randomizer, show which wins are currently included per practice area, and monitor which wins have been used in the past. 
   - status: Ice Box  
      - draft: False 
      - responsible: None  
   - role: Back end/devOps front End

- #2015
   - why: We need to create personas for our three target user groups (volunteers, donors/partners, and advisors) in order to ensure the design of the site accounts for each of their goals and concerns, and to support alignment and communication across the team.  
   - status: Ice Box  
      - draft: False 
      - responsible: None  
   - role: User Research

- #1838
   - why: We need to collect the contact information for City / Donor / other stakeholders to be interviewed about the homepage redesign.
   - status: New Issue Approval
      - draft: False 
      - responsible: None  
   - role: Org Rep

- #485
   - why: originally this was an issue to Create Submit Your Pitch form but it needs to be a discussion about how we process pitches and what we plan to do, given that we have not started any new projects in the last 12 months.
   - status: New Issue Approval
      - draft: True
      - responsible: None  
   - role: Product

- #186 
   - why: Review the existing stakeholder contact/survey forms to see how they have been utilized and how we might utilize them.
   - status: New Issue Approval 
      - draft: False
      - responsible: None
   - role: User research

</details>

### Won't have this time
<details><summary>List of all won't have issues</summary>

- #6819 
- #1934
- #1711

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #8353
- #7673
- #6819
- #4607
- #4282
- #3934
- #2763
- #2481
- #2015
- #1934
- #1838
- #1711
- #485
- #186

</details>

**Comment by priyanka02art** [comment]
# List of all issues
- [ ] #7673 
- [ ] #6819  
- [ ] #6709 
- [ ] #4607 
- [ ] #4282 
- [ ] #3934 
- [ ] #3019 
- [ ] #2763 
- [ ] #2481 
- [ ] #2015 
- [ ] #1968 
- [ ] #1934 
- [ ] #1838 
- [ ] #1711 
- [ ] #485 
- [ ] #295 
- [ ] #186 


## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7673   
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: None 
   - role: Product
- [ ] #6709 
   - why: The filter behavior for the 'Languages/Technologies/Tools' category on the Home and Projects pages is confusing and inconsistent.
   - status: New Issue Approval  
      - draft: False 
      - responsible: None
   - role: Front end  
- [ ] #2763  
   - why: Finalize images of zooms for homepage  
   - status: New Issue Approval  
      - draft: False  
      - responsible: None  
   - role: User Research
 - [ ] #2481 
    - why: We need to track and support the final wrap up items for the homepage launch, so that it can be completed.   
    - status: In Progress 
      - draft: False
      - responsible: @ExperimentsInHonesty @bansikunalshah @priyanka02art   
   - role: Product  
- [ ] #1968 
   - why: Need to find the right use case to contribute in HFLA  
   - status: Ice Box  
      - draft: False  
      - responsible: None 
   - role: Writing   
- [ ] #295 
   - why: We need to evaluate if we should change the gradient on hero to surround image rather than having a linear gradient from bottom 3rd of the image to bottom of the image.  
   - status: Ice Box  
      - draft: False  
      - responsible: None 
   - role: Design 

### Should Have
- [ ] #4607 
   - why: It is important to recreate images to maintain credibility, brand consistency and content quality on a website.  
   - status: Prioritized backlog
      - draft: False
      - responsible: None
   - role: Design
- [ ] #1711 
   - why: We need to draft a case study for the homepage design process because it will help boost volunteers' portfolios and it will serve as a reference for future HfLA site volunteers.
   - status: Ice Box
      - draft: False
      - responsible: None
   - role: Design

### Could Have
- [ ] #4282  
   - why: We need a system to track and display when specific practice area wins are needed for the randomizer, show which wins are currently included per practice area, and monitor which wins have been used in the past. 
   - status: Ice Box  
      - draft: False 
      - responsible: @roslynwythe  
   - role: Front End
- [ ] #3934 
   - why: We need to create two new composite images to replace the images that we are using, that we don't have a license for, so that we can be in compliance.   
   - status: Ice Box 
      - draft: False  
      - responsible: None 
   - role: Design Lead
- [ ] #3019 
   - why: We need to provide information about the scope of Hack for LA's activities, including working with City of LA and other organizations/networks.  
   - status: Ice Box
      - draft: False 
      - responsible: None  
   - role: User Research
- [ ] #2015 (@ExperimentsInHonesty to confirm the priority)
   - why: We need to create personas for our three target user groups (volunteers, donors/partners, and advisors) in order to ensure the design of the site accounts for each of their goals and concerns, and to support alignment and communication across the team.  
   - status: Ice Box  
      - draft: False 
      - responsible: None  
   - role: User Research
- [ ] #1838 (@ExperimentsInHonesty to confirm the priority)
   - why: We need to collect the contact information for City / Donor / other stakeholders to be interviewed about the homepage redesign.
   - status: New Issue Approval
      - draft: False 
      - responsible: None  
   - role: Org Rep
- [ ] #485 (@ExperimentsInHonesty to confirm the priority)
   - why: originally this was an issue to Create Submit Your Pitch form but it needs to be a discussion about how we process pitches and what we plan to do, given that we have not started any new projects in the last 12 months.
   - status: New Issue Approval
      - draft: True
      - responsible: None  
   - role: Product
- [ ] #1934  
   - why: We need to have a signup (on the webpage) for a newsletter, when we are sending one out, so that people can subscribe.
   - status: Ice Box
      - draft: False
      - responsible: None
   - role: Front End
- [ ] #186 
   - why: Review the existing stakeholder contact/survey forms to see how they have been utilized and how we might utilize them.
   - status: New Issue Approval 
      - draft: False
      - responsible: None
   - role: User Search
### Won't have this time
- [ ] #6819 
   - why: Refactor issue 
   - status: Emergent Requests
      - draft: True
      - responsible: @ExperimentsInHonesty 
   - role: Back end/DevOps


#### Templates
```
   - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by nadiaspn0503** [comment]
2026-08-18
Using this search 
[state:open label:"P-Feature: Home page" is:issue ](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Home%20page%22%20is%3Aissue)

This is the highest issue number found 7673 it is addressed at the top of this issue.
