### ISSUE TITLE
EPIC: Prepare the Events page for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7674]
### Overview
We need to track existing issues and make new issues to deliver Events page complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [x] Make the issues specified
- [x] Link them as sub issues to this issue
- [x] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: P-Feature: Events
    - 1.01.01 Issue Tab: [P-Feature: Events](https://github.com/hackforla/website/issues?q=is%3Aopen+label%3A%22P-Feature%3A+Events%22)
    - 1.01.02 Project Board: [P-Feature: Events](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=+label%3A%22P-Feature%3A+Events%22)
- 1.02 URL of page on Hack for LA website: https://www.hackforla.org/events/
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// Events](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+events+&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+Events&type=wikis
   - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
TBD

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 8566

### Must Have
- [ ] #7674 
   - why: It is the epic for this page (this issue)
   - status: In Progress (actively working)
      - draft: True
      - responsible: kimberlyvaldez07  
   - role: Product

- [ ] #8566   
   - why: We need to check if there are further steps necessary for resolving the continuous POST requests on the Events page. 
   - status: Ready for Prioritization 
      - draft: False
      - responsible: None 
   - role: Front end

- [ ] #8433   
   - why: We need to replace the Happy Hour section with a Summer Meetup to keep the website up to date. 
   - status: Prioritized backlog
      - draft: False
      - responsible: none
   - role: Front end, product, and writing

- [ ] #8432  
   - why: We are no longer an in person organization and have moved remote. 
   - status: New Issue Approval
      - draft: True
      - responsible: None 
   - role: back end/dev Ops and front end 

- [ ] #8431 
   - why: we can move this information to the About page to highlight that we were an active in person organization that moved remote
   - status: New Issue Approval
      - draft: True
      - responsible: None 
   - role: back end/dev Ops and front end 

### Could Have
<details><summary>List of all could have issues</summary>
 
- #6321 
   - why: We need to add info to the wiki under the pages details, that make it easy for future team members to edit and know which pages use which files.  
   - status: Ice Box 
      - draft: False
      - responsible: None
   - role: Front End  

- #3289 
   - why: Ensure consistent text elements on the Events page 
   - status: New Issue Approval
      - draft: False
      - responsible: None 
   - role: Design

</details>

### Won't have this time
<details><summary>List of all won't have issues</summary>

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #8566
- #8433 
- #8432 
- #8431
- #7674
- #6321
- #3289

</details>

**Comment by priyanka02art** [comment]
- URL: https://www.hackforla.org/events

- [ ] [Events Issues on the project board](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22p-feature%3A+events%22)

- [ ] [https://github.com/hackforla/website/issues/6320 (this issue is also relevant to Project info and Project meetings pages]

- [ ] [https://github.com/hackforla/website/issues/6749]

- [ ] [https://github.com/hackforla/website/issues/6369]

**Comment by priyanka02art** [comment]
# List of all issues
- [ ] #7674 
- [ ] #7524 
- [ ] #6321 
- [ ] #6140 
- [ ] #4370 
- [ ] #3289 


## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7674 
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval  
      - draft: True
      - responsible: None 
   - role: Product
- [ ] #4370 
   - why: The client intermittently triggers POST requests for the Jennifer Pahlka video on the events page, causing the loading circle to spin for several minutes. This problem appears to occur only on MacOS.
   - status: ERs and epics that are...
      - draft: False 
      - responsible: None 
   - role: Front end 

### Could Have
- [ ] #6321 
   - why: We need to add info to the wiki under the pages details, that make it easy for future team members to edit and know which pages use which files.  
   - status: Ice Box 
      - draft: False
      - responsible: None
   - role: Front End
- [ ] #6140  
   - why: Civic Tech Structures full name is Civic Tech Structure, Inc. and sometimes it makes sense to say Civic Tech Structure, Inc. 501(c)(3) or even Civic Tech Structure, Inc. a non profit 501(c)(3). Different pages have different listings 
   - status: Emergent Requests
      - draft: False
      - responsible: @ExperimentsInHonesty   
   - role: Product   
- [ ] #3289 
   - why: Ensure consistent text elements on the Events page 
   - status: New Issue Approval
      - draft: False
      - responsible: None 
   - role: Design

### Won't have this time
- [ ] #7524 
   - why: Refactor issue 
   - status: In Progress
      - draft: False
      - responsible: @Khinememe-Kyaw  
   - role: Back end/DevOps


#### Templates
```
   - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by ExperimentsInHonesty** [comment]
@charmainemak09 Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

You can use this template
```
1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary): 
```

**Comment by kimberlyvaldez07** [comment]
2026-08-18
Using this search
[state:open label:"P-Feature: Events" is:issue ](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Events%22%20is%3Aissue)

This is the highest issue number found 8433 it is addressed at the top of this issue.
