### ISSUE TITLE
EPIC: Prepare the Sitemap page for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7676]
### Overview
We need to track existing issues and make new issues to deliver Sitemap page complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [x] Make the issues specified
- [x] Link them as sub issues to this issue
- [x] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: P-Feature: Sitemap
    - 1.01.01 Issue Tab: [P-Feature: Sitemap](https://github.com/hackforla/website/issues?q=is%3Aopen+label%3A%22P-Feature%3A+Sitemap%22)
    - 1.01.02 Project Board: [P-Feature: Sitemap](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=+label%3A%22P-Feature%3A+Sitemap%22)
    -  1.02 URL of page on Hack for LA website: https://www.hackforla.org/sitemap/
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// Sitemap](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+Sitemap+&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+Sitemap&type=wikis
    - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
- [ ] Update the date to be current

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 8514

### Must Have
- [ ] #7676    
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: kimberlyvaldez07 
   - role: Product

- [ ] #8514
   - why: Our website needs to use the Oxford comma consistently so that the website is correct and uniform. In this issue we will be changing text on the Site Map page.
   - status: Ready for Prioritization 
      - draft: False
      - responsible: None 
   - role: Back end/devOps and front end

- [ ] #8501   
   - why: Audit the site map page to know which elements are missing or need to be updated as components in the sitemap change across the homepage sub pages, footer, and future pages
   - status: New Issue Approval
      - draft: True
      - responsible: None 
   - role: Product and design

- [ ] #8489   
   - why: We need to update the last updated date for the sitemap to build strong credibility in our program and process.
   - status: Ready for Prioritization 
      - draft: False
      - responsible: None 
   - role: Front end

- [ ] #8488
   - why: We need to change "Github" to "GitHub" in the footer section of the diagram.
   - status: Prioritized backlog
      - draft: False
      - responsible: None 
   - role: Front end

### Could Have
<details><summary>List of all could have issues</summary>

- #3522
   - why: We need to audit the site map page to know which text elements are missing text components so that we can fix them in Figma, and ensure consistency with the Design System and Implementation by the website team. 
   - status: Prioritized Backlog 
      - draft: False  
      - responsible: None
   - role: Design  

</details> 

### Won't have this time
<details><summary>List of all won't have issues</summary>

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #8514
- #8501
- #8489
- #8488
- #7676
- #3522

</details>

**Comment by priyanka02art** [comment]
- URL: https://www.hackforla.org/sitemap

- [ ] find or make new issue to update sitemap

**Comment by priyanka02art** [comment]
# List of all issues
- [ ] #7676   
- [ ] #3522  


## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7676    
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product

### Should Have
- [ ] #3522   
   - why: We need to audit the site map page to know which text elements are missing text components so that we can fix them in Figma, and ensure consistency with the Design System and Implementation by the website team. 
   - status: Prioritized Backlog 
      - draft: False  
      - responsible: None  
   - role: Design  

### Could Have
- [ ] # 
   - why:  
   - status:  
      - draft:  
      - responsible: 
   - role:  
   
### Won't have this time
- [ ] #   
   - why:  
   - status:  
      - draft:  
      - responsible:  
   - role:  


#### Templates
```
   - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by kimberlyvaldez07** [comment]
2026-08-18
Using this search
[state:open label:"P-Feature: Sitemap" is:issue ](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Sitemap%22%20is%3Aissue)

This is the highest issue number found 8691 it is addressed at the top of this issue.
