### ISSUE TITLE
EPIC: Prepare SDGs across site for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7677]
### Overview
We need to track existing issues and make new issues to deliver SDGs across site complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [ ] Make the issues specified
- [ ] Link them as sub issues to this issue
- [ ] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label name: P-Feature: SDGs 
    - 1.01.01 Issue Tab: [P-Feature: SDGs](https://github.com/hackforla/website/issues?q=is%3Aopen+label%3A%22P-Feature%3A+SDGs%22)
    - 1.01.02 Project Board: [P-Feature: SDGs](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=+label%3A%22P-Feature%3A+SDGs%22)
- 1.02 URLs of pages on Hack for LA website:
   - project pages (e.g., https://www.hackforla.org/projects/311-data)
   - program area detail pages (e.g., https://www.hackforla.org/citizen-engagement)
   - about page: https://www.hackforla.org/about/
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// SDG page](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+sdg+page&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+SDG+page&type=wikis
   - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
- [ ] Evaluate the [UN guidelines for SDG usage](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf) to determine if we can or cannot round edges of the SDGs.  
   - [ ] If we cannot, then we need to update the citizen engagement page to have squared corners like this [figma: citizen engagement](https://www.figma.com/design/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17601-123536&t=z8eB1YcqpTS5xfkq-0)
   - [ ] if we can, we need to evaluate if we want to change the 
      - [ ] [About page Sustainability section](https://www.hackforla.org/about/#sustainability)
      - [ ] [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 8470

### Must Have
- [ ] #7677 
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: kimberlyvaldez07 
   - role: Product

- [ ] #8470
   - why: The text overflows in the Sustainable Development component in mobile widths. These issues was noticed in the program area pages such as https://www.hackforla.org/program-areas/citizen-engagement. Also, the text forms a thin column to the side when the mobile width is wide enough.
   - status: In progress (actively working)
      - draft: False
      - responsible: DakuwoN and Sk-223 
   - role: Front end

- [ ] #6277
   - why: The project.yml file template needs updating to improve SDG formatting and reduce duplicate data.
   - status: In progress (actively working)
      - draft: False
      - responsible: JessicaLucindaCheng 
   - role: Back end/devOps

- [ ] #6223
   - why: We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role: Front End

- [ ] #6222 
   - why: We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role: Front End

- [ ] #6221   
   - why: We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role:  Front End

- [ ] #6220    
   - why: We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role: Front End

- [ ] #4153  
   - why: It is the Epic Page: Rollout Plan: Move, refactor, and add SDG info and images
   - status: In Progress (actively working)
      - draft: False
      - responsible: JessicaLucindaCheng 
   - role: Dev Leads

- [ ] #2037
   - why: We need to add information to each project md file so that we can display it on the new Impact format
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product

### Could Have
<details><summary>List of all could have issues</summary>

- #4676   
   - why: We need to document where all the SDG images and related files are in our repo so that developers know where these files are located and can use them.
   - status: In Progress (actively working)
      - draft: False
      - responsible: JessicaLucindaCheng 
   - role: Dev leads and front end 

- #642   
   - why: We would like to align our projects with the SDGs so that we can identify areas that we are over and/or under-addressing with HfLA projects.
   - status: Ice box
      - draft: False
      - responsible: None 
   - role: Design

</details> 

### Won't have this time
<details><summary>List of all won't have issues</summary>

- #3302 

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #8470
- #7677
- #6277
- #6223
- #6222
- #6221
- #6220
- #4676
- #4153
- #3302
- #2037
- #642

</details>

**Comment by priyanka02art** [comment]
- [SDG issues on project Board](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22p-feature%3A+sdgs%22)
- Issues
   - [ ] Evaluate the [UN guidelines for SDG usage](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf) to determine if we can or cannot round edges of the SDGs.  
      - [ ] If we cannot, then we need to update the citizen engagement page to have squared corners like this [figma: citizen engagement](https://www.figma.com/design/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17601-123536&t=z8eB1YcqpTS5xfkq-0)
      - [ ] if we can, we need to evaluate if we want to change the 
           - [ ] [About page Sustainability section](https://www.hackforla.org/about/#sustainability)
           - [ ] [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
   - [ ] https://github.com/hackforla/website/issues/4229
   - [ ] https://github.com/hackforla/website/issues/2037
   - [ ] https://github.com/hackforla/website/issues/6277
   - [ ] https://github.com/hackforla/website/issues/4153
      - [ ] https://github.com/hackforla/website/issues/6223
      - [ ] https://github.com/hackforla/website/issues/6222
      - [ ] https://github.com/hackforla/website/issues/6221
      - [ ] https://github.com/hackforla/website/issues/6220
- Resources
   - [Program Area Audit Spreadsheet](https://docs.google.com/spreadsheets/d/1wkzmWck-aGTzGxiryYEUhGbKRJX8rDDT3RLsAn-E-9o/edit#gid=0) - has the SDG info for all projects and issue tracking

**Comment by aparnar1920** [comment]
# List of all issues
- [ ] #7677
- [ ] #6277
- [ ] #6223
- [ ] #6222
- [ ] #6221
- [ ] #6220
- [ ] #4676 
- [ ] #4153 
- [ ] #3302 
- [ ] #2037  
- [ ] #642 

## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7677 
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product
- [ ] #4153  
   - why: It is the Epic Page: Rollout Plan: Move, refactor, and add SDG info and images
   - status: InProgress
      - draft: False
      - responsible: None
   - role: Dev Leads
- [ ] #3302  
   - why: Design an SDG page for the hack for LA website
   - status: Prioritized Backlog
      - draft: False
      - responsible: None
   - role: Design 

### Should Have
- [ ] #6223
   - why: We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role: Front End
- [ ] #6222 
   - why: We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role: Front End
 - [ ] #6221   
   - why: We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role:  Front End
 - [ ] #6220    
   - why: We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.
   - status: New Issue Approval
      - draft: True
      - responsible: JessicaLucindaCheng 
   - role: Front End
   
### Could Have
- [ ] #4676   
   - why: SDGs wiki page
   - status: InProgress
      - draft: False
      - responsible: JessicaLucindaCheng 
   - role: FrontEnd 
   
- [ ] #642   
   - why: Add an SDGs page to website
   - status: Icebox
      - draft: False
      - responsible: None 
   - role: Design

### Won't have this time
- [ ] #6277     
   - why: Refactor Issue
   - status: In Progress
      - draft: False
      - responsible: JessicaLucindaCheng 
   - role: BackEnd/DevOps
   
- [ ] #2037 
   - why: add information to each project md file
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product

#### Templates
```
- [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by kimberlyvaldez07** [comment]
2026-08-18
Using this search
[state:open label:"p-feature: SDGs" is:issue](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22p-feature%3A%20SDGs%22%20is%3Aissue)
This is the highest issue number found 8470 it is addressed at the top of this issue.
