### ISSUE TITLE
EPIC: Prepare the Header and Footer navigation for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7678]
### Overview
We need to track existing issues and make new issues to deliver Header and Footer navigation complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [ ] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [ ] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [ ] Make the issues specified
- [ ] Link them as sub issues to this issue
- [ ] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions

<details><summary>Desktop Width of 1440px</summary>

### Header
<details><summary>Full Header</summary>
  <img width="1252" height="112" alt="Full Header" src="https://github.com/user-attachments/assets/e17e88bc-df7f-4a47-98c7-af5f9acced3b" />
</details> 

<details><summary>Our Work</summary>
  <img width="972" height="380" alt="Image" src="https://github.com/user-attachments/assets/dd57b545-ed2a-4a55-be5e-aa04c52de687" />

</details> 

<details><summary>Join Us</summary>
  <img width="976" height="363" alt="Join Us" src="https://github.com/user-attachments/assets/9851561b-8573-4b44-a8ae-e74699fe48d7" />

</details>

<details><summary>Get in Touch</summary>
  <img width="967" height="247" alt="Image" src="https://github.com/user-attachments/assets/27998160-75ae-4064-b131-ce91bbc78d31" />

</details>

<details><summary>Toolkit</summary>
  <img width="973" height="275" alt="Image" src="https://github.com/user-attachments/assets/9cee0c2d-bd0c-4646-b777-3a97f9653b2f" />

</details>

### Footer
<details><summary>Footer</summary>
  <img width="1258" height="317" alt="Image" src="https://github.com/user-attachments/assets/90a2dfb1-45e2-41fa-be98-d895474584d4" />
</details> 
</details> 

---

<details><summary>Tablet Width of 768px</summary>

### Header
<details><summary>Full Header</summary>
  <img width="958" height="102" alt="Image" src="https://github.com/user-attachments/assets/fc1de3d1-de00-4f50-845b-f791691c42fe" />

</details> 

<details><summary>Our Work</summary>
  <img width="957" height="398" alt="Image" src="https://github.com/user-attachments/assets/4201a8a7-4c99-4159-979b-2f9f01423b31" />

</details> 

<details><summary>Join Us</summary>
  <img width="958" height="350" alt="Image" src="https://github.com/user-attachments/assets/e8d504d0-ed48-4bbc-a883-4902d1d0652e" />

</details>

<details><summary>Get in Touch</summary>
  <img width="955" height="224" alt="Image" src="https://github.com/user-attachments/assets/af3e80c4-c0d1-4ee7-9819-a825208b00c2" />

</details>

<details><summary>Toolkit</summary>
  <img width="957" height="233" alt="Image" src="https://github.com/user-attachments/assets/dc47dc7a-f277-4654-a2b6-dd6b12ffeec6" />

</details>

### Footer
<details><summary>Footer</summary>
  <img width="957" height="693" alt="Image" src="https://github.com/user-attachments/assets/9a6a8948-d7b8-4dc3-9df3-f9e924b348e3" />

</details> 
</details> 

---

<details><summary>Mobile Width of 480px</summary>

### Header
<details><summary>Menu Collapsed</summary>
  <img width="596" height="527" alt="Image" src="https://github.com/user-attachments/assets/a6e7f13f-7f80-441f-9a3b-fdb56c96d463" />

</details> 

<details><summary>Menu Expanded</summary>
  <img width="597" height="363" alt="Image" src="https://github.com/user-attachments/assets/6bec9765-cc8f-4d58-8a55-6ff6121d602b" />
</details> 

### Footer
<details><summary>Footer</summary>
  <img width="597" height="690" alt="Image" src="https://github.com/user-attachments/assets/b0088535-1077-46a8-9842-fd3b74ff5652" />

</details> 
</details> 

---

- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label names: P-Features: Footer, P-Feature: Navigation
    - 1.01.01 Issue Tab: [P-Feature: Footer,P-Feature: Navigation](https://github.com/hackforla/website/issues?q=is%3Aopen+label%3A%22P-Feature%3A+Footer%22%2C%22P-Feature%3A+Navigation%22)
    - 1.01.02 Project Board: [P-Feature: Footer,P-Feature: Navigation](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=label%3A%22P-Feature%3A+Footer%22%2C%22P-Feature%3A+Navigation%22+)
- 1.02 URL of page on Hack for LA website: see any page
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data/internal/credits// Navigation](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+navigation&type=code) [repo:hackforla/website NOT language:SVG NOT path:/^_data\/internal\/credits\// footer](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+footer&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+Navigation&type=wikis, https://github.com/search?q=repo%3Ahackforla%2Fwebsite+footer&type=wikis
   - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
TBD

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 7680

### Must Have
- [ ] #7680
   - why: It is the epic for Homepage launch   
   - status: New Issue Approval 
      - draft: True 
      - responsible: kimberlyvaldez07  
   - role: Product

- [ ] #7678  
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: kimberlyvaldez07 
   - role: Product

- [ ] #6161  
   - why: Lists all the placed where github needs to be replaced with GitHub so that we display the company name correctly    
   - status: In Progress (actively working)
      - draft: False  
      - responsible: daras-cu   
   - role: Back end/devOps and front end

- [ ] #2513  
   - why: We need to create a mobile version of the new top nav bar so that it can be implemented and launched alongside the desktop version. 
   - status: Ice Box  
      - draft: False  
      - responsible: None  
   - role: Design 

### Should Have
- [ ] #2686   
   - why: We want to ensure that mobile users will be able to access website content using the accordion style navigation design  
   - status: New Issue Approval 
      - draft: True  
      - responsible: None 
   - role: User Research
 
### Could Have
<details><summary>List of all could have issues</summary>

</details> 

### Won't have this time
<details><summary>List of all won't have issues</summary>

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #7680
- #7678
- #6161
- #2686
- #2513

</details>

**Comment by priyanka02art** [comment]
# List of all issues
- [ ] #8018 
- [ ] #7680
- [ ] #7678 
- [ ] #7112 
- [ ] #6116 
- [ ] #5747 
- [ ] #2686 
- [ ] #2513 


## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7678  
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: Product
- [ ] #8018   
   - why: We need to replace instances of Github and github with GitHub so that we display the company name correctly  
   - status: PRs being reviewed  
      - draft: False  
      - responsible: None 
   - role: Back End/DevOps  
- [ ] #7680 (appears to be a duplicate of 7673) 
   - why: It is the epic for Homepage launch   
   - status: New Issue Approval 
      - draft: True 
      - responsible: None  
   - role: Product  
- [ ] #7112 (appears to be a duplicate of 8018)
   - why: We need to replace instances of Github and github with GitHub so that we display the company name correctly 
   - status: In Progress  
      - draft: False  
      - responsible: ihop-56   
   - role: Front end 
- [ ] #6161  
   - why: Lists all the placed where github needs to be replaced with GitHub so that we display the company name correctly    
   - status: In Progress  
      - draft: False  
      - responsible: daras-cu   
   - role: Front end
- [ ] #5747   
   - why: The Twitter logo is outdated and needs to be updated to the new X logo.  
   - status: Ice Box  
      - draft: True  
      - responsible: None 
   - role: Front End  

### Should Have
- [ ] #2686   
   - why: We want to ensure that mobile users will be able to access website content using the accordion style navigation design  
   - status: New Issue Approval 
      - draft: True  
      - responsible: None 
   - role: User Research
- [ ] #2513  
   - why: We need to create a mobile version of the new top nav bar so that it can be implemented and launched alongside the desktop version. 
   - status: Ice Box  
      - draft: False  
      - responsible: None  
   - role: Design  

### Could Have
- [ ] #  
   - why:  
   - status:  
      - draft:  
      - responsible:  
   - role:  
   
### Won't have this time
- [ ] #  
   - why:  
   - status:  
      - draft:  
      - responsible:  
   - role:  

#### Templates
```
   - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by kimberlyvaldez07** [comment]
2026-08-18
Using this search
[state:open label:"P-Feature: Footer" is:issue](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Footer%22%20is%3Aissue)

[state:open label:"P-Feature: Navigation" is:issue](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Navigation%22%20is%3Aissue)

This is the highest issue number found 7680 it is addressed at the top of this issue.

**Comment by kimberlyvaldez07** [comment]
We need views of both mobile and desktop 

1. Production (copy from live website)
2. Homepage Feature Branch
3. Future Designs (Iterative designs for future homepage feature branch deployment in Figma)

**Comment by kimberlyvaldez07** [comment]
@hackforla/website-merge For this issue we need some screenshots of header/footer on the homepage feature branch. Please add them as a comment to this issue.

**Comment by JessicaLucindaCheng** [comment]
> [@hackforla/website-merge](https://github.com/orgs/hackforla/teams/website-merge) For this issue we need some screenshots of header/footer on the homepage feature branch. Please add them as a comment to this issue.

@kimberlyvaldez07 I can do it this week, so it should be completed by end of day on Mon, 2025-11-17.

**Comment by JessicaLucindaCheng** [comment]
- Availability: 6 hours
- ETA: Mon, Nov 17, 2025

### Tasks
- [x] In a new comment, add screenshots of the homepage on the feature branch in multiple views, which should include:
  - [x] Mobile view
    - [x] Define screen size used in comment
    - [x] Header
    - [x] Footer 
  - [x] Tablet view
    - [x] Define screen size used in comment
    - [x] Header
    - [x] Footer
  - [x] Desktop view
    - [x] Define screen size used in comment 
    - [x] Header
    - [x] Footer

**Comment by JessicaLucindaCheng** [comment]
## Desktop Width of 1440px

### Header
<details><summary>Full Header</summary>
  <img width="1252" height="112" alt="Full Header" src="https://github.com/user-attachments/assets/e17e88bc-df7f-4a47-98c7-af5f9acced3b" />
</details> 

<details><summary>Our Work</summary>
  <img width="972" height="380" alt="Image" src="https://github.com/user-attachments/assets/dd57b545-ed2a-4a55-be5e-aa04c52de687" />

</details> 

<details><summary>Join Us</summary>
  <img width="976" height="363" alt="Join Us" src="https://github.com/user-attachments/assets/9851561b-8573-4b44-a8ae-e74699fe48d7" />

</details>

<details><summary>Get in Touch</summary>
  <img width="967" height="247" alt="Image" src="https://github.com/user-attachments/assets/27998160-75ae-4064-b131-ce91bbc78d31" />

</details>

<details><summary>Toolkit</summary>
  <img width="973" height="275" alt="Image" src="https://github.com/user-attachments/assets/9cee0c2d-bd0c-4646-b777-3a97f9653b2f" />

</details>

### Footer
<details><summary>Footer</summary>
  <img width="1258" height="317" alt="Image" src="https://github.com/user-attachments/assets/90a2dfb1-45e2-41fa-be98-d895474584d4" />
</details> 

## Tablet Width of 768px

### Header
<details><summary>Full Header</summary>
  <img width="958" height="102" alt="Image" src="https://github.com/user-attachments/assets/fc1de3d1-de00-4f50-845b-f791691c42fe" />

</details> 

<details><summary>Our Work</summary>
  <img width="957" height="398" alt="Image" src="https://github.com/user-attachments/assets/4201a8a7-4c99-4159-979b-2f9f01423b31" />

</details> 

<details><summary>Join Us</summary>
  <img width="958" height="350" alt="Image" src="https://github.com/user-attachments/assets/e8d504d0-ed48-4bbc-a883-4902d1d0652e" />

</details>

<details><summary>Get in Touch</summary>
  <img width="955" height="224" alt="Image" src="https://github.com/user-attachments/assets/af3e80c4-c0d1-4ee7-9819-a825208b00c2" />

</details>

<details><summary>Toolkit</summary>
  <img width="957" height="233" alt="Image" src="https://github.com/user-attachments/assets/dc47dc7a-f277-4654-a2b6-dd6b12ffeec6" />

</details>

### Footer
<details><summary>Footer</summary>
  <img width="957" height="693" alt="Image" src="https://github.com/user-attachments/assets/9a6a8948-d7b8-4dc3-9df3-f9e924b348e3" />

</details> 

## Mobile Width of 480px

### Header
<details><summary>Menu Collapsed</summary>
  <img width="596" height="527" alt="Image" src="https://github.com/user-attachments/assets/a6e7f13f-7f80-441f-9a3b-fdb56c96d463" />

</details> 

<details><summary>Menu Expanded</summary>
  <img width="597" height="363" alt="Image" src="https://github.com/user-attachments/assets/6bec9765-cc8f-4d58-8a55-6ff6121d602b" />
</details> 

### Footer
<details><summary>Footer</summary>
  <img width="597" height="690" alt="Image" src="https://github.com/user-attachments/assets/b0088535-1077-46a8-9842-fd3b74ff5652" />

</details>

**Comment by JessicaLucindaCheng** [comment]
### Update 
- **Progress:** I added images of the header and footer on feature-homepage-launch branch in desktop, tablet, and mobile view in this [comment](https://github.com/hackforla/website/issues/7678#issuecomment-3545445467). However, I realized there are collapsed menus in the header I didn't capture in the screenshots, so I will add a few more screenshots showing the menus expanded.
- **Blockers:** None.
- **Availability:** 6 hours
- **ETA:** Wednesday, November 19, 2025

### Tasks
- [x] Add to https://github.com/hackforla/website/issues/7678#issuecomment-3545445467
  - [x] Desktop header
      - [x] Screenshots of each collapsed menu
  - [x] Tablet header
      - [x] Screenshots of each collapsed menu
  - [x] Mobile header
      - [x] Screenshots of each collapsed menu

**Comment by JessicaLucindaCheng** [comment]
@kimberlyvaldez07 

> [@hackforla/website-merge](https://github.com/orgs/hackforla/teams/website-merge) For this issue we need some screenshots of header/footer on the homepage feature branch. Please add them as a comment to this issue.

- I have added the screenshots for the header and footer in this comment: https://github.com/hackforla/website/issues/7678#issuecomment-3545445467

**Comment by nadiaspn0503** [comment]
@JessicaLucindaCheng can you please provide links to each page listed in the footer. If a top line has no link then put "no link".

### Our Work
- Url:
-[ ] About Us Url:
-[ ] Program Areas Url:
-[ ] Projects Url:
-[ ] Our Wins Url:
-[ ] Press Url:

### Join Us
- Url:
-[ ] Donate Url:
-[ ] Advise Us Url:
-[ ] Volunteer with Us Url:
-[ ] Partner with Us Url:
-[ ] Submit your Pitch Url:

### Get in Touch
- Url:
-[ ] Contact Us Url:
-[ ] Events Url:

### Toolkit
- Url:
-[ ] Guides Url:
-[ ] External Resources Url:

**Comment by nadiaspn0503** [comment]
@JessicaLucindaCheng Following up on my previous comments for the links to the pages in the footer. If you don't have time to do it this week we can ask someone else on the merge team to do it. They all should have access to the footer branch correct?

**Comment by JessicaLucindaCheng** [comment]
@nadiaspn0503 

> [@JessicaLucindaCheng](https://github.com/JessicaLucindaCheng) Following up on my previous comments for the links to the pages in the footer. If you don't have time to do it this week we can ask someone else on the merge team to do it. They all should have access to the footer branch correct?

Sorry for not responding to your comment. I had verbally let Bonnie know on Monday, January 26th that I can do it this week. So, eta will be by Monday, Feb 2nd at the latest but I will try to get it done sooner.

Also, yes, all the developers have access to the feature-homepage-launch branch, which is where the footer and headers are for the new homepage.

**Comment by JessicaLucindaCheng** [comment]
| _In the Footer_ | _URL When Using Docker_ | _Equivalent URL to Live Webpage_ | _Notes_ |
| -------------- | ---------------------------- | ------------------------------------- | ------ |
| **Our Work** | http://localhost:4000/# | https://www.hackforla.org/# | Once the redesigned homepage launches, the link will lead to the new redesigned homepage. |
| About Us | http://localhost:4000/about | https://www.hackforla.org/about | |
| Program Areas | http://localhost:4000/program-areas | https://www.hackforla.org/program-areas | |
| Projects | http://localhost:4000/projects | https://www.hackforla.org/projects | |
| Our Wins | http://localhost:4000/wins | https://www.hackforla.org/wins | |
| Press | http://localhost:4000/about#news | https://www.hackforla.org/about#news | |
| | | | |
| | | | |
| **Join Us** | http://localhost:4000/join | https://www.hackforla.org/join | |
| Donate | http://localhost:4000/donate | https://www.hackforla.org/donate | |
| Advise Us | http://localhost:4000/join#advise | https://www.hackforla.org/join#advise | |
| Volunteer with Us | http://localhost:4000/join#volunteer | https://www.hackforla.org/join#volunteer | |
| Partner with Us | http://localhost:4000/join#partner | https://www.hackforla.org/join#partner | |
| Submit your Pitch | mailto:team@hackforla.org?subject=Submitting my pitch to Hack for LA | Same as the one when using Docker | |
| | | | |
| | | | |
| **Get in Touch** | http://localhost:4000/#get-in-touch | https://www.hackforla.org/#get-in-touch | Once the redesigned homepage launches, the link will lead to the Get in Touch section on the new redesigned homepage. |
| Contact Us | http://localhost:4000/#get-in-touch | https://www.hackforla.org/#get-in-touch | Once the redesigned homepage launches, the link will lead to the Get in Touch section on the new redesigned homepage. |
| Events | http://localhost:4000/events | https://www.hackforla.org/events | |
| | | | |
| | | | |
| **Toolkit** | http://localhost:4000/toolkit | https://www.hackforla.org/toolkit | |
| Guides | http://localhost:4000/toolkit#guides | https://www.hackforla.org/toolkit#guides | |
| External Resources | http://localhost:4000/toolkit#external-resources | https://www.hackforla.org/toolkit#external-resources | |

**Comment by JessicaLucindaCheng** [comment]
- Availability: 3 hours
- ETA: Mon, Feb 2, 2026

## Progress
- See table in this comment for the links: https://github.com/hackforla/website/issues/7678#issuecomment-3824680613
### Our Work
- [x] Url:
  - [x] About Us Url:
  - [x] Program Areas Url:
  - [x] Projects Url:
  - [x] Our Wins Url:
  - [x] Press Url:
### Join Us
- [x] Url:
  - [x] Donate Url:
  - [x] Advise Us Url:
  - [x] Volunteer with Us Url:
  - [x] Partner with Us Url:
  - [x] Submit your Pitch Url:
### Get in Touch
- [x] Url:
  - [x] Contact Us Url:
  - [x] Events Url:
### Toolkit
- [x] Url:
  - [x] Guides Url:
  - [x] External Resources Url:

**Comment by JessicaLucindaCheng** [comment]
@nadiaspn0503 

> @JessicaLucindaCheng can you please provide links to each page listed in the footer. If a top line has no link then put "no link".

Yes, the links have been added for the footer. See the table in this comment: https://github.com/hackforla/website/issues/7678#issuecomment-3824680613

**Comment by kimberlyvaldez07** [comment]
For issue #6161 the dependency issue #7112 resolved the issue in the gh-pages, but not the feature-homepage-launch branch. I created issue #8508 to address the feature-homepage-launch. 

In addition, there is a note for #5747 that mentions "As soon as the dependency is cleared that will provide instructions for how to do this, and this ER and its resulting issues can get updated/written." 
   - [ ] https://github.com/hackforla/website/issues/5747#issuecomment-2058081836

For issues #6161 and #5747, we need clarification if new issues need to be made or updated. This has been added to the Dev/PM agenda.

- #6161 
- #7112
- #8508 
- #5747


---
I am going to close issue #8508 as it is not needed based on the comment that JC will update the feature-homepage-launch branch which should resolve discrepancies with gh-pages in https://github.com/hackforla/website/issues/8442#issuecomment-3911135059 and #5747 has been cleaned up and is ready for prioritization.

**Comment by JessicaLucindaCheng** [comment]
@kimberlyvaldez07 
- > For issue https://github.com/hackforla/website/issues/6161 the dependency issue https://github.com/hackforla/website/issues/7112 resolved the issue in the gh-pages, but not the feature-homepage-launch branch. I created issue https://github.com/hackforla/website/issues/8508 to address the feature-homepage-launch.

- In regards to #7112 and #8508, the feature-homepage-launch branch is updated, which fixed GitHub to be the correct capitalization for _data/navigation/social.yml in that branch.

**Comment by ExperimentsInHonesty** [comment]
<details><summary>Desktop Width of 1440px</summary>

### Header
<details><summary>Full Header</summary>
  <img width="1252" height="112" alt="Full Header" src="https://github.com/user-attachments/assets/e17e88bc-df7f-4a47-98c7-af5f9acced3b" />
</details> 

<details><summary>Our Work</summary>
  <img width="972" height="380" alt="Image" src="https://github.com/user-attachments/assets/dd57b545-ed2a-4a55-be5e-aa04c52de687" />

</details> 

<details><summary>Join Us</summary>
  <img width="976" height="363" alt="Join Us" src="https://github.com/user-attachments/assets/9851561b-8573-4b44-a8ae-e74699fe48d7" />

</details>

<details><summary>Get in Touch</summary>
  <img width="967" height="247" alt="Image" src="https://github.com/user-attachments/assets/27998160-75ae-4064-b131-ce91bbc78d31" />

</details>

<details><summary>Toolkit</summary>
  <img width="973" height="275" alt="Image" src="https://github.com/user-attachments/assets/9cee0c2d-bd0c-4646-b777-3a97f9653b2f" />

</details>

### Footer
<details><summary>Footer</summary>
  <img width="1258" height="317" alt="Image" src="https://github.com/user-attachments/assets/90a2dfb1-45e2-41fa-be98-d895474584d4" />
</details> 
</details> 

---

<details><summary>Tablet Width of 768px</summary>

### Header
<details><summary>Full Header</summary>
  <img width="958" height="102" alt="Image" src="https://github.com/user-attachments/assets/fc1de3d1-de00-4f50-845b-f791691c42fe" />

</details> 

<details><summary>Our Work</summary>
  <img width="957" height="398" alt="Image" src="https://github.com/user-attachments/assets/4201a8a7-4c99-4159-979b-2f9f01423b31" />

</details> 

<details><summary>Join Us</summary>
  <img width="958" height="350" alt="Image" src="https://github.com/user-attachments/assets/e8d504d0-ed48-4bbc-a883-4902d1d0652e" />

</details>

<details><summary>Get in Touch</summary>
  <img width="955" height="224" alt="Image" src="https://github.com/user-attachments/assets/af3e80c4-c0d1-4ee7-9819-a825208b00c2" />

</details>

<details><summary>Toolkit</summary>
  <img width="957" height="233" alt="Image" src="https://github.com/user-attachments/assets/dc47dc7a-f277-4654-a2b6-dd6b12ffeec6" />

</details>

### Footer
<details><summary>Footer</summary>
  <img width="957" height="693" alt="Image" src="https://github.com/user-attachments/assets/9a6a8948-d7b8-4dc3-9df3-f9e924b348e3" />

</details> 
</details> 

---


<details><summary>Mobile Width of 480px</summary>

### Header
<details><summary>Menu Collapsed</summary>
  <img width="596" height="527" alt="Image" src="https://github.com/user-attachments/assets/a6e7f13f-7f80-441f-9a3b-fdb56c96d463" />

</details> 

<details><summary>Menu Expanded</summary>
  <img width="597" height="363" alt="Image" src="https://github.com/user-attachments/assets/6bec9765-cc8f-4d58-8a55-6ff6121d602b" />
</details> 

### Footer
<details><summary>Footer</summary>
  <img width="597" height="690" alt="Image" src="https://github.com/user-attachments/assets/b0088535-1077-46a8-9842-fd3b74ff5652" />

</details> 
</details> 

---

**Comment by viet456** [comment]
Created issue #8593 from ER #5747 (Update Twitter Logo). The issue has been submitted for approval.
