### ISSUE TITLE
EPIC: Prepare the entire site (issues that are on many pages) for Homepage Launch

### ISSUE THREAD

**Issue by priyanka02art** [hackforla/website#7680]
### Overview
We need to track existing issues and make new issues to deliver entire site (issues that are on many pages) complete enough for the Homepage launch

#### Details
We need to track and support the final wrap up items for the homepage launch, so that it can be completed.

### Action Items
- [x] List all the issues related to the label
- [x] Identify what open issues have to be resolved before launch, by classifying the issues into the following categories using MoSCoW method in a comment.
   - Must Have
   - Should Have
   - Could Have
   - Won't Have this time
- [x] Add the following details under each issue
   ```
   - why: [ADD WHY ITS IMPORTANT TO TO THE LAUNCH]
   - status: [ADD STATUS e.g., Icebox, Emergent Requests, New Issue Approval, ERs and epics that are ready to be turned into issues, Prioritized Backlog, In Progress (actively working), Questions / In Review]
      - draft: [true OR false]
      - responsible: [ADD GITHUB HANDLES WITHOUT @]
   - role: [ADD ROLE e.g. data scientist, infrastructure, design, design lead, user research, Research Lead, dev leads, data analyst, BA, hfla leadership, back end/devOps, writing, front end, merge team, technical writer]
   ```
- [x] Once you receive sign-off from Staff PM add to `## Relevance of the issues to the Homepage launch`
- [x] Review comments with `Notes carried forward from epic` if it exists, and make sure all previous items are addressed in the top of the issue.
   - If it specifies new issues to make then add explicit action items for making those issue in a new comment on this issue
      - get sign-off on those new issues to make by Staff PM 
- [x] Identify items that need issues opened by looking at the page and features and seeing what is not already addressed by the existing issues or new issues to make list.
- [x] Make the issues specified
- [x] Link them as sub issues to this issue
- [x] Classify them using MoSCoW and add the details (why, status, draft, responsible, role)
- [ ] Get Sign-off and prioritization of the issues by Staff PM
- [ ] If this page has content that must be checked for accuracy before homepage launch, add the detail to the epic for tracking that (resource 1.05)

### Resources/Instructions
- Parent Epic: https://github.com/hackforla/website/issues/2481

#### Used for creating this issue
- 1.01 Label names
   - feature: branding 
   - feature: spelling
   - P-Feature: Navigation
   - 1.01.01 Issue Tab: [label:"feature: branding","feature: spelling","P-Feature: Navigation"](https://github.com/hackforla/website/issues?q=is%3Aopen+label%3A%22feature%3A+branding%22%2C%22feature%3A+spelling%22%2C%22P-Feature%3A+Navigation%22)
   - 1.01.02 Project Board: [label:"feature: branding","feature: spelling","P-Feature: Navigation"](https://github.com/orgs/hackforla/projects/86/views/1?filterQuery=label%3A%22feature%3A+branding%22%2C%22feature%3A+spelling%22%2C%22P-Feature%3A+Navigation%22)
- 1.02 URL of page on Hack for LA website: see every page on the site
- 1.03 URL of link to code search: [repo:hackforla/website NOT language:SVG NOT path:/^_data\/internal\/credits\// branding](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+branding&type=code), [repo:hackforla/website NOT language:SVG NOT path:/^_data\/internal\/credits\// spelling](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+spelling&type=code), [repo:hackforla/website NOT language:SVG NOT path:/^_data\/internal\/credits\// Navigation](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+NOT+language%3ASVG+NOT+path%3A%2F%5E_data%5C%2Finternal%5C%2Fcredits%5C%2F%2F+Navigation&type=code)
- 1.04 URL of WIKI page: https://github.com/search?q=repo%3Ahackforla%2Fwebsite+Navigation&type=wikis
   - 1.04.01 URL of future edits to wiki pages: https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki (check this page to see if there are any other new edits in the queue.)
- 1.05 Issue for adding items to a final checklist: #8417

#### Created by this issue
- 2.01 [EXAMPLE would be a link to an issue related to delivering this page]
---
### Must Have
TBD

### Should Have
TBD

### Could Have
TBD

---

last updated: 2026-04-21
Highest number found: 8539

### Must Have
- [ ] #7680  
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval  
      - draft: True  
      - responsible: kimberlyvaldez07   
   - role: Product

- [ ] #7678 
   - why: We need to track existing issues and make new issues to deliver Header and Footer navigation complete enough for the Homepage launch.
   - status: New Issue Approval 
      - draft: True
      - responsible: kimberlyvaldez07  
   - role: Product

 - [ ] #8539
   - why: Our website needs to use the comma consistently so that the website is correct and uniform. In this issue we will be changing text on the Project Meetings page.
   - status: Ready for Prioritization 
      - draft: False
      - responsible: None 
   - role: back end/devOps and front end

- [ ] #8514
   - why: Our website needs to use the comma consistently so that the website is correct and uniform. In this issue we will be changing text on the Site Map page.
   - status: Ready for Prioritization
      - draft: False 
      - responsible: None 
   - role: Back end/devOps and front end

- [ ] #8513
   - why: Our website needs to use the Oxford comma consistently so that the website is correct and uniform. In this issue we will be changing text on the Join Us page.
   - status: Ready for Prioritization
      - draft: False
      - responsible: None 
   - role: Back end/devOps and front end

- [ ] #8512
   - why: Our website needs to use the Oxford comma consistently so that the website is correct and uniform. In this issue we will be changing text on the Join Us page.
   - status: Ready for Prioritization
      - draft: False
      - responsible: None 
   - role: Back end/devOps and front end

- [ ] #8511
   - why: Our website needs to use the Oxford comma consistently so that the website is correct and uniform. In this issue we will be changing text on the Communities of Practice page.
   - status: Ready for Prioritization
      - draft: False
      - responsible: None 
   - role: Back end/devOps and front end

- [ ] #8510
   - why: Our website needs to use the Oxford comma consistently so that the website is correct and uniform. In this issue we will be changing text on the Project Page.
   - status: Ready for Prioritization
      - draft: False
      - responsible: None 
   - role: Back end/devOps and front end

- [ ] #8488
   - why: We need to change Github to GitHub in the footer section of the Sitemap diagram so that we display the company name correctly.
   - status: Prioritized backlog
      - draft: False
      - responsible: none
   - role: Back end/devOps and front end

- [ ] #8482
   - why: We need to make sure the Oxford comma is in the correct spots across the entire website for consistency.
   - status: In progress (actively working)
      - draft: False
      - responsible: nadiaspn0503 
   - role: Front end and product

- [ ] #6161
   - why: Maintaining proper spelling and capitalization is important for both professionalism and consistency. Public-facing content should be free of errors to uphold credibility, while internal code should follow best practices for clarity. For example, "GitHub" is a company name and should be capitalized, except when used in URLs, variables, or directory names—where lowercase (e.g., github) is standard due to naming conventions.
   - status: In Progress (actively working)
      - draft: False
      - responsible: daras-cu  
   - role: Back End/devOps and front end

- [ ] #5334 
   - why: We need a GHA to scan the files changed in Pull Requests using the Code Spell Checker CLI, in order to ensure that no misspellings are posted on the website.
   - status: Ice Box 
      - draft: True
      - responsible: None 
   - role: Back End/ DevOps

- [ ] #5312  
   - why: To avoid repeatedly flagging false positives, we need to update the Code Spell Checker config file. These entries are tracked in the HfLA spelling audit spreadsheet, which will also be used for issue tracking.
   - status: New issue approval 
      - draft: False
      - responsible: none
   - role: Back end/devOps and front end 

- [ ] #5248  
   - why: We need to create issues to audit all appropriate codebase files for Code Spell Checker results. The HfLA spelling audit spreadsheet1 will be used to track spell check audit issues, record false positives and misspellings, and track resulting issues for resolving errors. 
   - status: new issue approval
      - draft: False
      - responsible: None 
   - role: Backend/devOps 

- [ ] #2513
   - why: create a mobile version of the new top nav bar so that it can be implemented and launched alongside the desktop version.
   - status: ice box
      - draft: false
      - responsible: none
   - role: design

### Should Have
- [ ] #6446
   - why: We need a template for reporting spell check warnings, so that we can create issues to address.
   - status: Ice Box 
      - draft: False 
      - responsible: None
   - role: Back End/ DevOps

- [ ] #5202
   - why: We need to direct developers how to manage spell check messages on changed files locally, and also those that may appear in Pull Request checks.
   - status: Ice Box
      - draft: True
      - responsible: None
   - role: Dev Leads

- [ ] #4349
   - why: create a roll out plan for having all HfLA website developers install the Code Spell Checker VS Code extension so that we can reduce confusion for our dev team 
   - status: New Issue Approval
      - draft: True
      - responsible: None
   - role: back end/devOps and dev leads

- [ ] #4264
   - why: add installation instructions for the VS Code extension, ESLint, so our developers will be aligned on the local spellchecker used.
   - status: ice box
      - draft: false
      - responsible: None
   - role: back end/devOps

- [ ] #2686
   - why: perform usability testing to assess the functionality of the top nav menu (mobile).
   - status: new issue approval 
      - draft: True
      - responsible: none
   - role: user research 

### Could Have

<details><summary>List of all could have issues</summary>

- #3191
   - why: When we present our organization to stakeholders and interviewers, we need a professional and dynamic Zoom background that represents HFLA.
   - status: new issue approval
      - draft: false
      - responsible: none
   - role: design 

- #609
   - why: we need to take a step back and think about our brand identity.
   - status: ice box
      - draft: false
      - responsible: none
   - role: product

</details> 

### Won't have this time
<details><summary>List of all won't have issues</summary>

</details> 

#### Templates
```
- [ ] #
   - why: 
   - status: 
      - draft: 
      - responsible: 
   - role:  
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

<details><summary>List of all issue by number</summary>

- #8539
- #8514
- #8513
- #8512
- #8511
- #8510
- #8488
- #8482
- #7680
- #7678
- #6446
- #6161 
- #5334
- #5312
- #5248
- #5202
- #4349
- #4264
- #3191
- #2686
- #2513
- #609

</details>

**Comment by priyanka02art** [comment]
- [ ] https://github.com/hackforla/website/issues/6140
- [ ] https://github.com/hackforla/website/issues/6161
- all spelling issues
   - [ ] https://github.com/hackforla/website/issues/5248 see this epic issue for details.
   - [ ] https://github.com/hackforla/website/issues/5450
- [ ] confirm that all links on the header and footer work
   - [ ] https://github.com/hackforla/website/issues/2455

**Comment by priyanka02art** [comment]
# List of all issues
- [ ] #7934 
- [ ] #7680 
- [ ] #7678 
- [ ] #6751 
- [ ] #6446
- [ ] #6161 
- [ ] #5334
- [ ] #5312 
- [ ] #5248 
- [ ] #5202 
- [ ] #4349 
- [ ] #4264 
- [ ] #3191 
- [ ] #2686 
- [ ] #2513 
- [ ] #609 

## Relevance of the issues to the Homepage launch
### Must Have
- [ ] #7680  
   - why: It is the epic for this page (this issue)
   - status: New Issue Approval  
      - draft: True  
      - responsible: None  
   - role: Product
 - [ ] #7678 
   - why: It is one of the epic for this page (this issue)
   - status: New Issue Approval 
      - draft: True
      - responsible: None 
   - role: Product
 - [ ] #6751  
   - why: To ensure the quality and professionalism of the HfLA site, we need to audit the codebase for spelling errors using the Code Spell Checker extension in VS Code. 
   - status: Prioritized Backlog
      - draft: False
      - responsible: None 
   - role: Front End
 - [ ] #6161
   - why: Maintaining proper spelling and capitalization is important for both professionalism and consistency. Public-facing content should be free of errors to uphold credibility, while internal code should follow best practices for clarity. For example, "GitHub" is a company name and should be capitalized, except when used in URLs, variables, or directory names—where lowercase (e.g., github) is standard due to naming conventions.
   - status: In Progress
      - draft: False
      - responsible: daras-cu  
   - role: Front End
 - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
 - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 

### Should Have
 - [ ] #6446
   - why: We need a template for reporting spell check warnings, so that we can create issues to address.
   - status: Ice Box 
      - draft: False 
      - responsible: None
   - role: Back End/ DevOps
 - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
 - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
### Could Have
 - [ ] #7934  
   - why: To reduce redundancy in the project file, we need to consolidate the github and picture variables into a single github-handle variable that holds each leadership team member’s GitHub handle.
   - status: New Issue Approval 
      - draft: Yes
      - responsible: Christopher-Chhim 
   - role: Front End
 - [ ] #5334 
   - why: We need a GHA to scan the files changed in Pull Requests using the Code Spell Checker CLI, in order to ensure that no misspellings are posted on the website.
   - status: Ice Box 
      - draft: True
      - responsible: None 
   - role: Back End/ DevOps
 - [ ] #5312  
   - why: To avoid repeatedly flagging false positives, we need to update the Code Spell Checker config file. These entries are tracked in the HfLA spelling audit spreadsheet, which will also be used for issue tracking.
   - status: In Progress 
      - draft: False
      - responsible: roslynwythe  
   - role: Front End  
 - [ ] #5248  
   - why: We need to create issues to audit all appropriate codebase files for Code Spell Checker results. The HfLA spelling audit spreadsheet1 will be used to track spell check audit issues, record false positives and misspellings, and track resulting issues for resolving errors. 
   - status: In Progress 
      - draft: False
      - responsible: essencegoff, roslynwythe  
   - role: Backend/ DevOps
 - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role:

### Won't have this time
 - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role:  
 - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
#### Templates
```
   - [ ] # 
   - why: 
   - status: 
      - draft
      - responsible: 
   - role: 
```
```
### Issues list associated with this epic
last updated: 
Highest number found:
```

**Comment by kimberlyvaldez07** [comment]
### Issues list associated with this epic
last updated: 2025-10-14
Highest number found: 7680

- #7680

---

### Must Have 
- [ ] #2686
   - why: perform usability testing to assess the functionality of the top nav menu (mobile).
   - status: new issue approval 
      - draft: True
      - responsible: none
   - role: user research 
- [ ] #2513
   - why: create a mobile version of the new top nav bar so that it can be implemented and launched alongside the desktop version.
   - status: ice box
      - draft: false
      - responsible: none
   - role: design

### Should Have 
 - [ ] #5202
   - why: We need to direct developers how to manage spell check messages on changed files locally, and also those that may appear in Pull Request checks.
   - status: Ice Box
      - draft: True
      - responsible: None
   - role: Dev Leads
 - [ ] #4349
   - why: create a roll out plan for having all HfLA website developers install the Code Spell Checker VS Code extension so that we can reduce confusion for our dev team 
   - status: New Issue Approval
      - draft: True
      - responsible: No One
   - role: back end/devOps, dev leads
- [ ] #4264
   - why: add installation instructions for the VS Code extension, ESLint, so our developers will be aligned on the local spellchecker used.
   - status: ice box
      - draft: false
      - responsible: no one
   - role: back end/devOps


### Could Have
 - #3191
   - why: When we present our organization to stakeholders and interviewers, we need a professional and dynamic Zoom background that represents HFLA.
   - status: new issue approval
      - draft: false
      - responsible: none
   - role: design 
 - #609
   - why: we need to take a step back and think about our brand identity.
   - status: ice box
      - draft: false
      - responsible: none
   - role: product

### Wont Have

**Comment by kimberlyvaldez07** [comment]
2026-08-18
Using this search

[state:open label:"P-Feature: Navigation" is:issue](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22P-Feature%3A%20Navigation%22%20is%3Aissue)

[state:open label:"feature: branding" is:issue](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22feature%3A%20branding%22%20is%3Aissue)

[state:open label:"feature: spelling" is:issue](https://github.com/hackforla/website/issues?q=state%3Aopen%20label%3A%22feature%3A%20spelling%22%20is%3Aissue)

This is the highest issue number found 8511 it is addressed at the top of this issue.
