### ISSUE TITLE
About-us page updates and bug fixes [Master Issue]

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#835]
### Overview 
The about-us page is a new page that was merged as an MVP.  There are a number of additions and corrections that now need to be addressed.  This issue is intended to serve as a master issue that will keep track our progress. 

### Details 
Each new issue will be described in a new comment.  There should be a description with a checkbox on each comment so we can check it off when it has been completed.  As each sub-issue is addressed a new, small issue will be created and linked back to this master issue.  That will allow us to keep each issue and PR on a smaller scale, and still keep track of the project as a whole. 

(I'm trying to figure out the best way to do that; if anyone has any thoughts on how to make this better, please comment).

### Resources  
https://www.hackforla.org/about-us

**Comment by drubgrubby** [comment]
- [x] In tablet view, the sticky navigation covers up the main content
- [x] On really wide screens the sticky navigation drifts away from the content

### Description
This issue was addressed in @ jbubar's review of the original PR: https://github.com/hackforla/website/pull/811#issuecomment-738679119

And also here: https://github.com/hackforla/website/pull/811#discussion_r536309009

**Comment by drubgrubby** [comment]
- [x] Clean up _about-us.scss file

### Description
There are many classes in this file that would probably be better off being moved to different "master" .scss files so that they can be used more easily on different pages.  Additionally, the file could be somewhat better organized to so that future coders working on this page won't curse my name quite so much. 

I think it would be good to work with @daniellex0 to determine the best strategy for moving files.  (This seems like it could also be part of componentizing the website.)

### Resources
_sass/components/_about-us.scss

### Issue
The sub-issue for this is #842

**Comment by drubgrubby** [comment]
- [x] Put up actual text of Letter form the executive director.

### Description
The page currently has lorem ipsum for the letter.  We need to put up the actual text.

**Comment by drubgrubby** [comment]
- [x] Minor CSS edits from Josh and Danielle's visual reviews.

### Description
Some things just aren't where they're supposed to be.  Extreme CSS tweaking should fix the problem(s).  In the issue I will make a list of the specific changes. 

The major visual issues will get their own issue. 

The sub-issue for danielle's visual review fixes is: #851

**Comment by drubgrubby** [comment]
- [x] Replace static image with animated gif in the donations section

### Description
The image I originally used was a static image.  It needs to be replaced with the intended animated gif. 

### Resources
![HfLA-Donate](https://user-images.githubusercontent.com/68244054/101829408-d3c9b480-3ae7-11eb-80ba-094fddd75401.gif)

https://github.com/civictechindex/CTI-website-frontend/issues/60#issuecomment-673788199

### Issue
The sub-issue is #846

**Comment by drubgrubby** [comment]
- [x] In SDG section, left row of images gets smaller when minimizing the page before it switches over to mobile view. 

### Description
Make it stop doing this: 
<img width="643" alt="Screen Shot 2020-12-10 at 1 03 16 PM" src="https://user-images.githubusercontent.com/68244054/101829677-3a4ed280-3ae8-11eb-99c4-931ac79410cf.png">

Images should be the same size.

**Comment by drubgrubby** [comment]
- [x] Make the Wins card link to the wins section

### Description
Currently, the wins card on the about us page links to dean's linked-in account.  As there wasn't a live wins page at the time, this made sense.  Now, however, it probably makes more sense to link it to the wins page. 

### Resources
http://localhost:4000/wins

Sub-issue: #848

**Comment by drubgrubby** [comment]
- [x] Make the Metrics card look better in tablet view

### Description
The metrics card degrades in unpleasant ways in tablet view.  Make it better. 

In tablet view the cards look different: 
![Screen Shot 2020-12-10 at 1 11 15 PM](https://user-images.githubusercontent.com/68244054/101830362-40917e80-3ae9-11eb-8a53-c4fb120079d4.png)

In full screen the cards look the same: 
![Screen Shot 2020-12-10 at 1 11 30 PM](https://user-images.githubusercontent.com/68244054/101830393-49825000-3ae9-11eb-9735-939fd8ae96cb.png)

**Comment by drubgrubby** [comment]
- [x] Center header text when it first switches to mobile view

### Description
When it first switches to mobile view there is a lot of white space to the right of the text and image.  That should probably be centered as soon as it switches view. 

![Screen Shot 2020-12-10 at 1 14 01 PM](https://user-images.githubusercontent.com/68244054/101830712-c9101f00-3ae9-11eb-9297-5aa210d648c5.png)

Should look more like this: 
![Screen Shot 2020-12-10 at 1 16 28 PM](https://user-images.githubusercontent.com/68244054/101830835-f52ba000-3ae9-11eb-9d85-c830a1284eac.png)

This comment from Josh's code review may have something to do with it: 
https://github.com/hackforla/website/pull/811#discussion_r536258869

Sub-issue: #848

**Comment by drubgrubby** [comment]
- [x] If possible, get rid of "!important" in the .is-active tag.

### Description
See Josh's comment here: https://github.com/hackforla/website/pull/811#discussion_r536302574

(I can't figure an easy way to do this, and it doesn't seem like it's worth the time to figure it out.  "!important" is available for a reason)

**Comment by drubgrubby** [comment]
- [x] Add "cursor:pointer" to .read-more/.read-less tags

###Description
See Josh's comment here: https://github.com/hackforla/website/pull/811#discussion_r536302574

sub-issue:  #848

**Comment by drubgrubby** [comment]
- [x] Does this page, and other pages, need a specific tablet view?

**Comment by drubgrubby** [comment]
- [x] Change page name to "about" 

### Description
Change page name to "about"

**Comment by drubgrubby** [comment]
- [x] Change link from http to https on vrms.io link in the metrics section
Sub-issue: #848

**Comment by drubgrubby** [comment]
- [x] Make partner images in the partners section into links

**Comment by pawan92** [comment]
@drubgrubby david will make individual issues for each item and close this when issues are created
