### ISSUE TITLE
Project Card Issue Updates - Engage, Food Oasis, Home Unite Us, Civic Opportunity

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#867]
### Overview

We need to create an issue for each project to funnel any updates they have to the website team 

### Action Items 
- [x] Get updates from the following 4 projects   
    - [ ] Engage https://github.com/hackforla/product-managment/issues/36
    - [x] Food Oasis https://github.com/hackforla/product-managment/issues/35  -@pawa92 will go to team meeting
    - [x] Home Unite Us https://github.com/hackforla/website/issues/953
    - [x] Civic Opportunity Project https://github.com/hackforla/website/issues/927

#### Action Items per Project 
- [ ] Create an issue using [Project Profile Card review and update Issue Template](https://github.com/hackforla/website/issues/new?assignees=&labels=Role%3A+Product+Management%2C+Feature+-+Project+Info+and+Page&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- [ ] Initial Reach out to Project  
    - [ ] Go to each individual project page on the HfLA website to locate the name/slack handle of the respective product manager 
     - [ ] Reach out to the Product Manager via slack in their project channel to notify them that their project card needs to be updated

![Screen Shot 2020-12-22 at 1 47 46 PM](https://user-images.githubusercontent.com/44422322/102936084-547b9f80-445c-11eb-8c29-4ec5387e4738.png)

  - [ ] Follow up until we can get the necessary updates 
     - [ ] Check in again on the channel after 2 days (" Is __________ still the project PM?" 
     - [ ] Attend their next team meeting

### Resources/Instructions
- [Project Profile Card review and update Issue Template](https://github.com/hackforla/website/issues/new?assignees=&labels=Role%3A+Product+Management%2C+Feature+-+Project+Info+and+Page&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- [Example](https://github.com/hackforla/website/issues/857)
- [Hack for LA Projects](https://www.hackforla.org/#projects)

**Comment by tarang100** [comment]
Engage - Waiting till Bonnie has assigned a PM
Food Oasis - Have to attend their team meeting on Thursday
Home Unite Us - PM Alex has said that she will get back to me. I will check with her during the team meeting on Sunday

**Comment by pawan92** [comment]
@tarang100 Please provide an update 
Progress:
Blockers:
Availability:
ETA:

**Comment by tarang100** [comment]
**Progress**
- **_Civic Opportunity Project_**: Project Card added to Prioritized Backlog for front end development
- **_Home Unite Us_**: Project Card added to Prioritized Backlog for front end development
- **_Engage_**: Waiting for Bonnie to confirm the appointment of new PM(s)
- **_Food Oasis_**: Have reached out multiple times, both on the Slack channel and personally, to Jenny but haven't got a response yet

**Blockers** 

- **_Food Oasis_**: The team did not revert on my request for confirming the meeting times. However, based on the Slack channel conversations it seems that the team meets at 6:30 PM PST on Tuesdays. I am unable to attend these meetings as they start at 8:00 AM IST (my time zone). Need to discuss the way forward with Bonnie

**Comment by pawan92** [comment]
Progress: Reached out to website slack for food oasis meeting for yesterday got no response. I couldnt find the food oasis slack channel but adhi was able to tell me this morning so i will aggressively pursue getting this sorted out asap
Blockers: Food oasis team as tarang outlined
Availability: Yes
ETA: Sunday

**Comment by pawan92** [comment]
Update: 
Progress: Will attend this weeks Food oasis meeting. Did not get the meeting notice in time for last week. Have also reached out to jenny.
Blockers: Food oasis team as tarang outlined
Availability: Yes
ETA: 2/2/21

**Comment by ExperimentsInHonesty** [comment]
Task complete
